### ISSUE TITLE
Managing Images Tab Showing 20 when set to 80 

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#10]
https://puu.sh/xs3NX/70b4d439f8.jpg

Supporter image managing is the same.

**Comment by ousnius** [comment]
Confirmed. But what it actually does is show 16 images when you first visit the link, and when you choose any other amount, the dropdown jumps back to 80 but shows 20 (not 16, not 80, but 20).

**Comment by Rrrafau** [comment]
assigned #150964055 and resolved
