### ISSUE TITLE
Can't give Endorsement from MO2

### ISSUE THREAD

**Issue by Hilli1** [Nexus-Mods/web-issues#1001]
Issue: When endorsing a mod in MO2 the red heart goes away but actually no endorsement is given. When checking for updates the red heart reappears.

I reported the issue to the MO2 devs and they checked my install and the logs. They couldn't see an issue and told me I need to sort it out with Nexus. So here we are.

Technically the red heart goes away when MO2 got the information from Nexus that the mod is endorsed. So obvisiously there is no endorsement given and MO2 got the wrong information from Nexus. When checking for updates, MO2 got the information from Nexus that the mod isn't endorsed. Consequently the red heart reappears. From the view of MO2 everything works correctly. There must be something wrong in the communication between MO2 and Nexus when endorsing the mod.

It seems I am not the only one with this problem. I know at least two other users with exact the same issue.

I forgot to mention, I am on v.2.2.1, the official MO2 Nexus release. The issue is there since the new API was implemented.

**Comment by Pickysaurus** [comment]
Could you try it again?

I am able to endorse through Vortex, which uses the exact same API so if it's still not working then the problem is definitely on MO2's end.
