### ISSUE TITLE
error: an exeption has occcured in the script

### ISSUE THREAD

**Issue by madopapanikolaou** [Nexus-Mods/web-issues#1002]
## Bug/error being reported:
1.) an exeption has occured
2.)Unable to enable shell extention for rar , win rar and 7zip files

## Steps to reproduce:
1.) selecting mod
2.) pressing the installing/enabling mod button
3.) error appears

1.) run as an admin
2.) settings
3.) OS settings
4.) Ticking boxes for shells extention
5.) error: Couldnt add shell extention for rar files
6.) Shell extention association for rar file has been removed by some other process.
Do you want to restore it?
7.) Yes
8.) error appears

## Expected result:
1.) installing the mod
2.) adding the shell extentions so i could fix the first error

## Actual result:
1.) errors

(using version 0.70.9)
[TraceLog20190922181323.txt](https://github.com/Nexus-Mods/web-issues/files/3639919/TraceLog20190922181323.txt)

**Comment by Pickysaurus** [comment]
Hi there, 

This appears to a problem with Nexus Mod Manager (based on the trace log). NMM has been unsupported since December 2016 in favour of Vortex.

You can raise issues on the community build of NMM here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases
