### ISSUE TITLE
Old Search Format Needed on New "design"

### ISSUE THREAD

**Issue by aba42** [Nexus-Mods/web-issues#1003]

**Comment by aba42** [comment]
The new "design" not only removes the header from the mods page (https://www.nexusmods.com/skyrim/mods/), but also removes the old, totally convenient Search feature.  The OLD feature allowed a drop-list of search results to be accessed, and then opened in a new page, thus preserving the underlying "mods" page for later perusing.  The new Search "feature" replaces the mods page with the Search results.  Therefore, users now need to reopen the original window in order to return to the page from which the Search was run.  This is VERY inconvenient!

**Comment by Pickysaurus** [comment]
The quicksearch is still present when you start typing.
