### ISSUE TITLE
Comments Made to Mod Authors by Message not added to "My Conversations"

### ISSUE THREAD

**Issue by aba42** [Nexus-Mods/web-issues#1004]
## Bug/error being reported:
Latest USLEEP Update is NOT a zipped file, but an executable file.  Therefore Mod Organizer does not recognize it as an installation file.  Notified Arthmoor via personal message from "Contact" box on Arthmoor's Author Page.  Comment not added to "My Conversations" list for further reference.
## Expected result:
Expected either a .7z or .rar or .zip file so that latest USLEEP update could be installed.

## Actual result:
MO/MO2 do not recognize filetype .exe for installation.  Notified Arthmoor via "Contact" button on Arthmoor Author page.  Comment not added to "My Convesations" listing.

**Comment by Pickysaurus** [comment]
This was a choice by the mod author, not a bug with the site.
