### ISSUE TITLE
User blocking not working correctly

### ISSUE THREAD

**Issue by christopher4684** [Nexus-Mods/web-issues#1005]
## Bug/error being reported:
Since the new website updates, I have a problem on my mod pages. I have reported this on the report user function but am also reporting it here as it is a bug. If I block a user from my content, it no longer prevents them from harassing me.

## Steps to reproduce:
Block a user from a mod page, they can still leave messages on the public forum.

## Expected result:
I blocked a user, and did not expect them to harass me non-stop on the public forum afterwards since they are blocked.

## Actual result:
Despite being blocked, the user can still post on the public forum of my content and is harassing me.

**Comment by Pickysaurus** [comment]
Please let us know if this issue persists. The best place to report is this using the reporting features on the forum.
