### ISSUE TITLE
NexusMods turns white on Chrome for Android in Dark Mode

### ISSUE THREAD

**Issue by Zobator** [Nexus-Mods/web-issues#1006]
## Bug/error being reported:
When opening any page on Nexusmods with Chrome for Android with Dark mode enabled, the colors are inverted to a bright version because the website has not specified a dark mode css package (see also https://css-tricks.com/dark-modes-with-css/). Default behaviour of the Chrome app with dark mode enabled is to invert all colors when it can't find a dark mode. This turns NexusMods very bright.

## Steps to reproduce:
1. Open Chrome on an android device
2. Go to chrome://flags/#enable-android-web-contents-dark-mode
3. Set the flag to enabled
4. Restart app
5. Go to NexusMods.com

### Example:
https://i.imgur.com/TpOdzV1l.jpg

## Expected result:
Nexusmods displaying as usual since it's already a dark themed website

## Actual result:
Inverted colors, making the website bright.

**Comment by Pickysaurus** [comment]
Your screenshot URL appears to be broken :S

**Comment by Pickysaurus** [comment]
As this is an unreleased feature of Chrome it is not supported. Our design team are aware for when it becomes a user option in an official release, rather than a flag.
