### ISSUE TITLE
"Current Section Viewing:" buttons in modpages

### ISSUE THREAD

**Issue by XxTWDxX** [Nexus-Mods/web-issues#1007]
The "Current Section Viewing:" buttons in the drop down menu (such as: Description, Files, Images...) all do not work on modpages (using mobile). They worked fine before the "new look" of Nexus mods.

These buttons do not work:
![20190926_085211](https://user-images.githubusercontent.com/16338749/65650493-ca1c7400-e03d-11e9-8d31-b077a4f4545a.png)

**Comment by Pickysaurus** [comment]
I'm not able to replicate this. It could be specific to your mobile browser or accessibility settings.
