### ISSUE TITLE
Unable to retrieve signature image dimensions, please try another image.

### ISSUE THREAD

**Issue by TheObstinateNoviceSmith** [Nexus-Mods/web-issues#1009]
## Bug/error being reported:

While trying to use an image from imgur for my forum signature, I received this error.  The image is 450x150 which meets the limit of 450x300.  I tried .jpeg and .png.  

https://i.imgur.com/HztloOT.jpg
https://i.imgur.com/AMecfxf.png

I tried a slightly smaller image:

https://i.imgur.com/HztloOT.jpg

I am using Windows 10 and am on Chrome Browser.

## Expected result:

To have my image work for my forum signature.
## Actual result:

When using this [img]https://i.imgur.com/HztloOT.jpg[/img]:
"Unable to retrieve signature image dimensions, please try another image."

When using this [img=450x150]https://i.imgur.com/HztloOT.jpg[/img]:
"You are not allowed to use that image extension on this community."

**Comment by TheObstinateNoviceSmith** [comment]
I'm still having this issue.  Did I post it to the right place at least?  Is this even an issue or is there something I should know about using images in my signature?

**Comment by Pickysaurus** [comment]
Sorry for the lack of reply. Please try again and if the issue persists, please post in the feedback forum: https://forums.nexusmods.com/index.php?/forum/117-feedback-suggestions-and-questions/
