### ISSUE TITLE
Unable to download files larger than 1GB

### ISSUE THREAD

**Issue by Zsashas** [Nexus-Mods/web-issues#1012]
## Bug/error being reported:
I have been attempting to download the latest version of a mod for several hours now. I have tried using Firefox, Microsoft Edge, and Google Chrome. Every single time, it has failed at precisely 1GB (the file is 1.4GB total). Twice it "completed" the download, but the file was only 1GB in size, and therefore incomplete and useless.

Mod in question: https://www.nexusmods.com/skyrimspecialedition/mods/12244?tab=files
Using Manual Download, as I don't have Vortex
Mod Version 6.5.21

## Expected result:
The download to actually complete properly

## Actual result:
Download fails at precisely 1GB every single time

If there is something I am doing wrong, please tell me. Save me from this hell.

Couldn't find any other place to submit this issue

Also, I did the ping test thing, and this was the result (no idea how good or bad this is):
Pinging files.nexus-cdn.com [185.180.13.131] with 32 bytes of data:
Reply from 185.180.13.131: bytes=32 time=45ms TTL=55
Request timed out.
Reply from 185.180.13.131: bytes=32 time=39ms TTL=55
Request timed out.

Ping statistics for 185.180.13.131:
    Packets: Sent = 4, Received = 2, Lost = 2 (50% loss),
Approximate round trip times in milli-seconds:
    Minimum = 39ms, Maximum = 45ms, Average = 42ms

**Comment by mrmason** [comment]
We've tested downloading this from a number of locations from the LA server, which you're pointing towards - and the file seems to download correctly.

Could you try downloading using a download manager ?

**Comment by Zsashas** [comment]
What do you mean by a download manager?

**Comment by Sikroth** [comment]
I am getting this issue as well and I know several other people from different countries are too. We've tried to download this mod - https://www.nexusmods.com/battletech/mods/393/?tab=stats&topic_id=7947933 , to no avail. The download reports finishing when it hits 1.0 GB resulting in a corrupted file.

**Comment by mrmason** [comment]
@Sikroth - please can you provide the result from ` ping files.nexus-cdn.com` from your computer ?

**Comment by Sikroth** [comment]
@mrmason Sorry for the delay, and apologies for the spanish text - I hope you can figure out the info you need from it.

```
Haciendo ping a files.nexus-cdn.com [195.181.173.81] con 32 bytes de datos:
Respuesta desde 195.181.173.81: bytes=32 tiempo=86ms TTL=51
Respuesta desde 195.181.173.81: bytes=32 tiempo=87ms TTL=51
Tiempo de espera agotado para esta solicitud.
Respuesta desde 195.181.173.81: bytes=32 tiempo=97ms TTL=51

Estadísticas de ping para 195.181.173.81:
    Paquetes: enviados = 4, recibidos = 3, perdidos = 1
    (25% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 86ms, Máximo = 97ms, Media = 90ms
```

**Comment by aufisch** [comment]
I noticed the same problem trying to download the same file as the OP plus the following file: https://www.nexusmods.com/fallout4/mods/35198?tab=posts

As with the others, the download happened normally until it hits 1Gb and it then stops and ultimately fails. I tried to download the mod provided in the link on three different days (29, 30 September and 1 October) and with three different servers (Amsterdam, Canada, Paris). 

My Ping:

Pinging files.nexus-cdn.com [185.152.65.129] with 32 bytes of data:
Reply from 185.152.65.129: bytes=32 time=29ms TTL=54
Reply from 185.152.65.129: bytes=32 time=25ms TTL=54
Reply from 185.152.65.129: bytes=32 time=25ms TTL=54
Reply from 185.152.65.129: bytes=32 time=25ms TTL=54

Ping statistics for 185.152.65.129:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 25ms, Maximum = 29ms, Average = 26ms

**Comment by mrmason** [comment]
Please can you try again now, and let me know if you're still seeing the same issue ?

**Comment by mrmason** [comment]
For reference, I think this is/was the problem - 

https://trac.nginx.org/nginx/ticket/1472

**Comment by aufisch** [comment]
I can confirm that the download of the above mentioned mod (the first link) worked, and that the file unpacked normally and wasn't corrupted.

Thanks for the fix

**Comment by Sikroth** [comment]
It still seems to cut at 1GB for me, I tried it just now.

**Comment by aufisch** [comment]
Ok, this is strange. I just came home to my home computer and reading the post of Sikroth I re-downloaded the same file. And yes, this time it DID cut out at 1Gb again. As did the "Relics of Hyrule"-Oldrim Version.

**Comment by Sikroth** [comment]
Me and my friend both managed to download that 2.6GB file finally a few days ago, for the record.

**Comment by mrmason** [comment]
Great, thanks for letting me know. Enjoy!
