### ISSUE TITLE
Can't download any mod using NMM on any version

### ISSUE THREAD

**Issue by Frost290** [Nexus-Mods/web-issues#1013]
## Bug/error being reported:
Every time I try and download any mod from the Nexus using NMM I get an error and the creation of a new trace file telling me it's tracing an unhandled exception of "object reference not set to an instance of object." I am currently on version 70.9 and it happens with any mod from any game, and prior versions show the same result.

## Steps to reproduce:
1. Find a mod, any mod.
2. Install said mod.
3. Get a trace log.
[TraceLog20190930122401.txt](https://github.com/Nexus-Mods/web-issues/files/3672960/TraceLog20190930122401.txt)

## Expected result:
The mod downloads fine, I'm happy. I download more mods, everything is fine.
## Actual result:
Trace log appears with the exception stating aforementioned message. The full reference is "System.NullReferenceException: Object reference not set to an instance of an object." Also ignoring that the mod will be found as a URL in the downloads section stuck on downloading. Pausing it and unpausing will do nothing for the freeze.

**Comment by Pickysaurus** [comment]
Please report NMM issues here. https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues

NMM has been unsupported since 2016
