### ISSUE TITLE
uplaoded tiny mod file never shows as done and ready to be downloaded

### ISSUE THREAD

**Issue by Tonycubed2** [Nexus-Mods/web-issues#1014]
The url to my mod page is:

https://www.nexusmods.com/skyrimspecialedition/mods/29445?tab=files

The small 22k mod file I uploaded is not showing up and downloadable even  after 30 minutes.   Somethin is wrong.

Respectfully

Tony
tony@dragontechservices.com

**Comment by Pickysaurus** [comment]
Hi Tony,

I can see that you were able to upload correctly in the end. Please do let us know if it happens again.
