### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by UncleGregy** [Nexus-Mods/web-issues#1015]
## Bug/error being reported:
Unable to download the main file from the Nexus for this mod:
https://www.nexusmods.com/skyrimspecialedition/mods/9005?tab=files
All other files on this page and other mod pages download properly.

## Steps to reproduce:
1.  Go to "Landscape Fixes for Grass mods" for Skyrim SE
2.  Open the "Files" tab
3.  Locate the main file and press the "Download Manually" button
4.  A window pops up saying my file is being prepared for download
5.  After a few seconds the webpage turns into full page text document with a bunch of random characters
6.  I have changed download location with the same result

## Expected result:
A properly downloaded mod file

## Actual result:
A screen full of gibberish

**Comment by Pickysaurus** [comment]
Hi there,

Are you using Microsoft Edge? Edge seems to not be able to handle download links properly in some cases.
