### ISSUE TITLE
downloads not registering on skyrim se nexus for some mods

### ISSUE THREAD

**Issue by Tonycubed2** [Nexus-Mods/web-issues#1016]
URL: https://www.nexusmods.com/skyrimspecialedition/mods/29445?tab=files
Username on the Nexus: Tonycubed2	
Bug/error being reported:  downlaods not registering.  shows blank
Steps to reproduce: just look at downloads under latest file
Expected result:  at least 1 download .  I downlaoded once to test.
Actual result:  blank.
Link to the affected mod/image (if relevant):

note; i saw this once before a couple weeks ago.  started working after a few days.

**Comment by mrmason** [comment]
What do you see if you try a different browser or privacy mode?

**Comment by mrmason** [comment]
I've done some more digging on this.

These stats arre built every 5 minutes, and then sent up to the CDN - it's possible they can be cached for a few hours, but we do have a system in place where they _should_ only be cached for 5 minutes even in your browser.

If you check your development tools in the console you should see something like `https://staticstats.nexusmods.com/live_download_counts/files/1704.csv?cachestamp=5236795` and if you look at the headers you should see if your browser is caching it longer than expected.
