### ISSUE TITLE
If you uncheck the "Send me news and information" on the "Create Account" page, you will not get a verification email.

### ISSUE THREAD

**Issue by Nitrokitty** [Nexus-Mods/web-issues#1017]
## Bug/error being reported:
- If you uncheck the "Send me news and information" on the "Create Account" page, you will not get a verification email.

## Steps to reproduce:
- https://www.nexusmods.com/signup
- Register Now
- Create Account
- Fill out Username, Email , Passwords, Registration Question, and Security Check
- **Uncheck** "Send me news and information"
- Check "Terms and Conditions"
- Create Account
- No verification email
- You can also try resending it and it doesn't work

### Example:
- Username: NitrokittyXO
- Email: NitrokittyXO@gmail.com
- Sent multiple verification emails to this account and never recieved them (even after 24hrs)
- I registered again with a different email address (danielletalley@outlook.com) and immediately got the email.

**Comment by Pickysaurus** [comment]
This is not the case.

Your email client is misfiling the activation email. 

Please contact support@nexusmods.com if the issue persists.
