### ISSUE TITLE
Slow Download from Nexus & Vortex

### ISSUE THREAD

**Issue by okoserce** [Nexus-Mods/web-issues#1020]
URL:  https://www.nexusmods.com/fallout4/mods/10737/?tab=files
Username on the Nexus: okoserce
Bug/error being reported: Slow download even on premium w/ Adblock disabled.
Steps to reproduce: attempted download on both Nexus direct as well as Vortex
Expected result: uncapped download speeds
Actual result: Results are varied but sometimes, especially on any larger files the download speed runs to a crawl and goes to 0 KBS
Link to the affected mod/image (if relevant):
![Slow Nexus-Vortex Download](https://user-images.githubusercontent.com/56791354/67159580-0032d800-f30c-11e9-93d9-6a1b2e9736cf.png)

**Comment by Pickysaurus** [comment]
Could you please try download from other servers directly on the site and let me know if the problem exists with all servers for you?

If the speed is consistently slow across all servers it may be a problem with your connection.
