### ISSUE TITLE
when download a bigger mod,they usually crashed

### ISSUE THREAD

**Issue by Thyroke** [Nexus-Mods/web-issues#1021]
## Bug/error being reported:
I'm a player from china, when I download mod on Nexus I found if the flies bigger than 80MB, the download job can start up but suddenly speed would down to 0B/s and report network-error for few minutes, they would happen on both manual download and Vortex.

## Steps to reproduce:
EXample: 
open the fallout4 CBBE's page and attempted download on Nexus direct or Vortex

## Expected result:
Successful download

## Actual result:
if I direct connect to Nexus, the download job's speed would get only 20~30KB/s and crashed up ，if i use vpn, speed would faster than direct but crashed too.(in fact about one hours ago i already downloaded 95% and then chrome report a network-error to me.)

**Comment by Pickysaurus** [comment]
Please see here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
