### ISSUE TITLE
Contributions not listed under user files/my mods

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#1024]
## Bug/error being reported:

The mods an author is contributing to (is given edit/manage permissions) are not listed under user files/my mods. I don't know what mods I'm given access to, or what other authors are managing.

## Expected result:

List of all managed mods after clicking on user files/my mods.

## Actual result:

Just the original uploads.

**Comment by Pickysaurus** [comment]
https://www.nexusmods.com/users/myaccount?tab=other+files

The next tab along has these mods.
