### ISSUE TITLE
Error Uploading Mod Update

### ISSUE THREAD

**Issue by Galadien** [Nexus-Mods/web-issues#1025]
## Bug/error being reported:
I am getting an error saying that files can only contain letters, numbers, spaces, etc. The file I'm uploading is named "Pastel Animals.zip" which does not contain any forbidden characters, in fact the original file had the same name and it uploaded fine yesterday. I tried removing the space and it gave the same error. I also deleted my zip file and recreated it in case it was corrupted, but the new one also gives the same error. The file is only 722 KB, so it isn't too large. 

The mod is called Pastel Animals and is by Galadien

## Steps to reproduce:
Under my mod go to the Manage Files page
Under Add New File, Click "Attach File" 
Click Upload
Click either Save File or Save at the bottom of the page--both give the same error

## Expected result:
A notice that the file uploaded and seeing the the file was in the files list

## Actual result:
Error message: Error The file name can only contain letters, numbers, spaces, brackets, periods, hyphens " - " and underscores " _ "
And the file fails to upload and is not in the files list.

This is the file:
[Pastel Animals.zip](https://github.com/Nexus-Mods/web-issues/files/3790470/Pastel.Animals.zip)

**Comment by Galadien** [comment]
OK, apparently it was giving an error about the details above the uploaded file, not the file itself. I was able to change those and it finally uploaded. 

Could we change this to a suggestion that the error messages be updated so that it is more obvious what they are referring to?

**Comment by Pickysaurus** [comment]
Thank you for updating the ticket with your solution, your feedback has been noted :)

**Comment by jeremybris** [comment]
I was getting this same error. Mine was including the quotation symbol, ", in the Nexus file name.
