### ISSUE TITLE
Notification not dismissed on activation

### ISSUE THREAD

**Issue by shadeMe** [Nexus-Mods/web-issues#1026]
## Bug/error being reported:
Notifications in the notification drawer do not get dismissed when they are clicked upon. This seems to be a Firefox-specific bug, as I can't reproduce the issue on Chrome.

## Steps to reproduce:
* Open Firefox (tested on FF v70 x64, Windows 10).
* Log into your account.
* Click on the notification drawer in the top navbar.
* Click on a notification in the drawer.

## Expected result:
The corresponding page opens and the notification is removed from the drawer.

## Actual result:
The corresponding page opens up, but its notification stays unchanged in the drawer. Nor does the unread notification count badge change.

**Comment by starkgate** [comment]
Same problem here. The notification does get dismissed if you middle click it however.

**Comment by Pickysaurus** [comment]
Seems to be Firefox blocking the Javascript used to clear the notification OnClick. The team are aware but it would require significant effort to get Firefox to play nice with it.

**Comment by starkgate** [comment]
Thanks for the update. It seems unlikely to me that FF would be blocking onClick altogether. Surely there's a way to make it work without putting in too much work. There's nothing about blocking it in the FF doc: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick

**Comment by Pickysaurus** [comment]
It's potentially the combination of a redirect and an onClick request. Firefox is a nightmare of development as it has several so many different settings combinations for more or less paranoid browsing.
