### ISSUE TITLE
Banned from nexusmods - IP Blacklisted 

### ISSUE THREAD

**Issue by Flash0286** [Nexus-Mods/web-issues#1027]
## Bug/error being reported:
Blacklisted IP 103.199.144.241 even though Ive never done more than download mods and endorse based on recommendations everytime I log in. There is no reason to blacklist me (This is not a static IP but dynamic, so it may be an erroneous blacklisting of someone else instead of me)

I am unable to file a complaint or contact nexus mod moderators etc. for any assistance. Please unblock my IP.

**Comment by Pickysaurus** [comment]
Hi there,

The block list is controlled by stopforumspam.com - you can request removal from that list here: https://www.stopforumspam.com/removal

As you say you're on a dynamic IP you may be able to access the site normally once it changes again.

Kind regards,
