### ISSUE TITLE
PayPal buttons use the wrong email address

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#103]
On the redesign, the PayPal buttons make use of the wrong email address.

Instead of sending you to a donation of the PayPal mail entered by the user, it will fill the form with the email address used for the user's Nexus login.

This is a bug and can be a security issue when the PayPal mail differs from the Nexus mail, like in my case. This is not the case on the old site.

**Comment by verenion** [comment]
This has been resolved.
