### ISSUE TITLE
Searching a mod using part of name doesn't find said mod.

### ISSUE THREAD

**Issue by Arindel** [Nexus-Mods/web-issues#1030]
## Bug/error being reported:
Searching doesn't find the mod when I type "lod gen".

## Steps to reproduce:
1. Search "lod gen" in Skyrim Special Edition section
2. Find no results

## Expected result:
Show SSELODGen as result.

## Actual result:
Shows zero results.

## Screenshot of issue:
![image](https://user-images.githubusercontent.com/21239038/68146199-22e60300-ff40-11e9-8465-601ac00e1022.png)

Searching using "sse lod gen" shows the modpage as result. Odd why just searching "lod gen" doesn't find it.

**Comment by Pickysaurus** [comment]
The search currently does not support partial matches. If you type "lodgen" (as it's actually named) or "lod gen" and press enter, the full search will give you the results.
