### ISSUE TITLE
Clicking a video shows the videos page but not the videos

### ISSUE THREAD

**Issue by Guba666** [Nexus-Mods/web-issues#1031]
## Bug/error being reported:
I select a mod, I go into the "videos" page, the lower bar with the big icons appears, I click on a video but there is only the black screen.
No video. Nothing. I click on the next video thumb, but nothing again. 
The "<---" and "---->" signs appear, but no video appears amidst of them.
Browser Firefox. See the attached screenshot.
Mod: Aemer's Refuge SE by LeanWolf
![02](https://user-images.githubusercontent.com/57462465/68336938-b9045f80-00df-11ea-9012-1f1b84eadfa3.jpg)
![01](https://user-images.githubusercontent.com/57462465/68336939-b9045f80-00df-11ea-8ac4-22d569329554.jpg)

**Comment by Pickysaurus** [comment]
It's possible you have a browser add-on preventing the player from loading.
