### ISSUE TITLE
Refreshing a mod description shows an empty description

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1032]
## Bug/error being reported:
Refreshing the page while in the mod's "mod details" editor tab shows an empty mod description.

## Steps to reproduce:
1. Open mod details
2. Hit F5

### Example:
![firefox_2019-11-07_05-01-25](https://user-images.githubusercontent.com/12874678/68359273-ab6ccb00-011b-11ea-8e63-64ce6910e756.png)

## Expected result:
Filled description

## Actual result:
Empty description

**Comment by Pickysaurus** [comment]
Can't replicate this. It may be specific to your setup.

Firefox?

**Comment by starkgate** [comment]
Yes. Tried it on both a Windows and a Linux system.

**Comment by Pickysaurus** [comment]
I will close this for now, but I have noted the issue. It is likely this page will get a significant overhaul at some point in the future.
