### ISSUE TITLE
Pasting scrolls the editing window all the way down

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1033]
## Bug/error being reported:
Pasting anything scrolls the editing window all the way down. Very impractical and frustrating.

## Steps to reproduce:
1. Copy something
2. Open a mod description long enough that it can scroll down
3. Scroll down a little (no bug if you're at the top)
4. Paste anywhere

It's a little hard to reproduce, it doesn't happen under certain conditions and I can't figure out which.

### Example:
![firefox_2019-11-07_05-03-50](https://user-images.githubusercontent.com/12874678/68359454-2d5cf400-011c-11ea-8167-769f3ef320f4.png)
![firefox_2019-11-07_05-04-25](https://user-images.githubusercontent.com/12874678/68359456-2e8e2100-011c-11ea-86ab-409697607237.png)

## Expected result:
Paste and don't scroll

## Actual result:
Scrolls down

**Comment by starkgate** [comment]
Same as #681

**Comment by Pickysaurus** [comment]
Merged into #1205
