### ISSUE TITLE
Pasting cannot be undone with Ctrl+Z unlike any other action

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1034]
## Bug/error being reported:
Pasting cannot be undone with Ctrl+Z unlike any other action.

## Steps to reproduce:
1. Paste something in a mod description
2. Hit ctrl+z

## Expected result:
Undo the pasting action

## Actual result:
Doesn't do anything

**Comment by Pickysaurus** [comment]
Merged into #1205
