### ISSUE TITLE
Detailed description editor height not adapted to screen

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1036]
## Bug/error being reported:
The height of the detailed description editor is impractical. It's way too tall, you have to scroll for a while to get to the toolbar when you're at the bottom.

An additional note since I'm reporting all the bugs that have been annoying me for a long time now. I wish this damned editor received an overhaul, because it's a pain to use. The WISYWYG in particular is broken whenever item lists are involved or slightly complex BBCode. I always end up using direct source code editing to get things done.

### Example:
![2019-11-07_05-17-17](https://user-images.githubusercontent.com/12874678/68359861-fe478200-011d-11ea-9fb8-2fd41e2fb7b1.png)
![2019-11-07_05-17-56](https://user-images.githubusercontent.com/12874678/68359862-ff78af00-011d-11ea-8c3a-b642e69b1be7.png)

## Expected result:
The text box shouldn't be taller than the vertical screen space available.

**Comment by Pickysaurus** [comment]
Merged into #1205
