### ISSUE TITLE
Large text box changelog split into multiple items

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1037]
## Bug/error being reported:
I have a long changelog I pasted into the "large text box" option. When I check the actual changelog, every line of my text box is split into its own item. It doesn't look good.

## Steps to reproduce:
![firefox_2019-11-07_05-46-37](https://user-images.githubusercontent.com/12874678/68360880-030e3500-0122-11ea-83d6-8cdabbbf623e.png)
![firefox_2019-11-07_05-46-14](https://user-images.githubusercontent.com/12874678/68360878-01dd0800-0122-11ea-8a45-48ea4b27cb6b.png)

**Comment by Pickysaurus** [comment]
This is intended behaviour.
