### ISSUE TITLE
Discarding a popup resets your vertical position to the popup's

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1038]
## Bug/error being reported:
Discarding a popup resets your vertical position to the popup's

## Steps to reproduce:
Firefox x64, Windows and Linux.
1. Open a popup: save mod details or any other action that opens a popup.
2. Scroll up or down.
3. Discard the popup by clicking outside it.

### Example:
![Screenshot_2019-11-07_13-20-18](https://user-images.githubusercontent.com/12874678/68388780-ab8fb980-0161-11ea-8cf1-f642f11e54ad.png)
![Screenshot_2019-11-07_13-20-27](https://user-images.githubusercontent.com/12874678/68388784-ad597d00-0161-11ea-8854-459fbf8191d4.png)

## Expected result:
Discard the popup, but stay in the same place

## Actual result:
Discards the popup, but also scrolls to the popup's position.

**Comment by Pickysaurus** [comment]
Merged into #1205
