### ISSUE TITLE
Nexus masthead dropdown icons render as letters in Firefox

### ISSUE THREAD

**Issue by George808** [Nexus-Mods/web-issues#1039]
The dropdown arrows along the top bar on the new nexus site are appearing as letters in Firefox for me.  They work fine in Chrome.  This may well be a problem on my end but I have no way of knowing.  Problem is consistent throughout the site.  Examples below:

<img width="1105" alt="Crop1" src="https://user-images.githubusercontent.com/55743528/68394449-db2bcb00-013b-11ea-8f2a-8b3b98e57543.png">
<img width="1010" alt="Crop2" src="https://user-images.githubusercontent.com/55743528/68394451-db2bcb00-013b-11ea-9807-a1a28d753f01.png">

**Comment by Pickysaurus** [comment]
This is either you blocking fonts (I see you have a script blocker so this is likely) or enforcing a custom font.
