### ISSUE TITLE
Nexus uploader broken

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1042]
## Bug/error being reported:
Multiple Refresh of web page just to upload a mod to the Nexus & missing "Inform users of this mod's requirements before they attempt to download this file" fails to appear 85% of the time on the Manage Files page.

## Steps to reproduce:
1. Go to the Manage Files tab when uploading files to the Nexus.
2. Notice the missing "Inform users of this mod's requirements before they attempt to download this file" checkbox.
3. Type in all required info, then drop the file into the upload field.
4. Watch the upload get stuck when the green bar reaches 100%, forcing one to hit the Refresh button multiple times just to get the upload to go through.

## Expected result:
File upload successful on the first attempt & the aforementioned checkbox appearing under the Manage Files tab if file requirements have been added.

## Actual result:
Uploads failing 85% of the time, forcing multiple Refresh webpage just to get an upload to go through & the aforementioned checkbox missing from the Manage Files tab nearly every time I get to the Manage Files tab to upload files to the Nexus...

**Comment by Pickysaurus** [comment]
I am unsure why this does not appear for you. I have not been able to replicate it.
