### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by mad-matx** [Nexus-Mods/web-issues#1043]
## Bug/error being reported:
502 bad gateway

## Steps to reproduce:
Download Roguetech core file from this page <https://www.nexusmods.com/battletech/mods/79?tab=files> leads to:

https://supporter-files.nexus-cdn.com/2388/79/RogueTech%20Core-79-Project-B-Patch-4-2-1573492477.exe?md5=evApImrqI6_AvoDcR0GPxg&expires=1573523277&user_id=1296894&rip=73.157.11.146
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
download of latest core

## Actual result:
502 bad gateway

**Comment by Pickysaurus** [comment]
Can you confirm you're still having this issue?

**Comment by mad-matx** [comment]
No, eventually I stopped getting that error.  Not sure if the mod creators reposted it, or it just took time, or...?
  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * madmatx: toys in the attic
 

    On Tuesday, November 19, 2019, 3:53:27 AM PST, Mike <notifications@github.com> wrote:  
 
 
Can you confirm you're still having this issue?
