### ISSUE TITLE
Notifications: X New Comments Indistinguishable from old ones

### ISSUE THREAD

**Issue by theFuzzyWarble** [Nexus-Mods/web-issues#1045]
## Bug/error being reported:
When clicking a Notification link stating "X new comments about ...",
I don't know which others, after the first, are new without scrolling/filtering them visually by date.

## Steps to reproduce:
1. Just click a notification with multiple new comments.
2. Have fun..

## Expected result:
When following the Notification link, the result page should have a stylesheet addition to account for a "Per 'new-post'" background/border color change to style it as new/unviewed and is only applied when following the notification link.

## Actual result:
Apart from the I assume chronologically last comment it auto-scrolls to first, it is hard to discern which others are new as well.

**Comment by Pickysaurus** [comment]
I understand this could be clearer, however, the new posts are the ones at the top of the page for new comments or the bottom of the comment chain for replies. 

I've noted this as a suggestion for future enhancement.

**Comment by theFuzzyWarble** [comment]
Yes, I realize the placements for them but in longer involved post it gets hairy.
I've opted to searching by date in that case, but thanks for the future consideration it will be helpful.

**Comment by Pickysaurus** [comment]
This issue has been closed as we are no longer accepting suggestions via this tracker. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
