### ISSUE TITLE
Contributions not listed under user files

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#1046]
## Bug/error being reported:

*** Reposting from https://github.com/Nexus-Mods/web-issues/issues/1024 because only half of the issue has been addressed ***

The mods an author is contributing to (is given edit/manage permissions) are not listed under user files. I can see my files but there's no way to check what other authors are managing.

## Expected result:

List of all managed mods after clicking on user files

## Actual result:

Just the original uploads.

**Comment by Pickysaurus** [comment]
https://www.nexusmods.com/users/myaccount?tab=other+files
