### ISSUE TITLE
Log-in probs

### ISSUE THREAD

**Issue by JimmyRJump** [Nexus-Mods/web-issues#1047]
I created a new password after reading the message and upon login with the new password I got the message page where I needed to reset my password...

I did and had six gateway errors while trying to get past the password thing.  The site reacts normal when hitting a browser link to any of the games, it's just the new password page that seems to be overloaded a touch.

So, there seems to be a problem with being forced to add a new password even after you just changed it.

Brower is Google Chrome

**Comment by Pickysaurus** [comment]
Thanks Jimmy, we're working on these problems as we speak.

**Comment by Pickysaurus** [comment]
The performance issues should now be resolved.

**Comment by JimmyRJump** [comment]
Cheers Picky.
