### ISSUE TITLE
Lasspass Autofill not working in new Login flow

### ISSUE THREAD

**Issue by shadeMe** [Nexus-Mods/web-issues#1048]
## Bug/error being reported:
The LastPass password manager extension's autofill feature does not work with the new login flow. I'm on Firefox v70 and have the latest version of the extension.

## Steps to reproduce:
1. Go to the new login page.
2. Click on the LastPass fill-icon inlaid in the username text field.
3. Select the account.

## Expected result:
The username and password fields are filled in automatically by the extension.

## Actual result:
Both text fields remain empty and the following error is logged to the console:
```
Not filling because tld mismatch between https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Lf4vsIUAAAAAN6TyJATjxQbMAcKjBZ3rOc0ijrp&co=aHR0cHM6Ly91c2Vycy5uZXh1c21vZHMuY29tOjQ0Mw..&hl=en&v=75nbHAdFrusJCwoMVGTXoHoM&size=invisible&cb=bsf7mdd9k00 and nexusmods.com
```
Source of the error message is the extension, I believe, but the cause is the login page itself and its implementation of reCAPTCHA. I saw no reCAPTCHA prompt when attempting to autofill nor when manually typing/pasting in the credentials and submitting them.

**Comment by mrmason** [comment]
Is this happening for you ? We found another issue with lastpass auto filling, and it does now seem to be working correctly for us.

**Comment by shadeMe** [comment]
I gave it another shot just now. Logged out and then logged in. Ran into the same issue (and the same error message in the console). Also tried to reload the page whilst bypassing the browser cache.

**Comment by Pickysaurus** [comment]
Seems to work fine here. Do you have LastPass in any other browser to test?

**Comment by shadeMe** [comment]
Logged out and logged back in to test, and it worked this time. Guess the issue can be closed now.

**Comment by Pickysaurus** [comment]
Thanks for confirming :)
