### ISSUE TITLE
Incongruous "Password changed" notification email text

### ISSUE THREAD

**Issue by shadeMe** [Nexus-Mods/web-issues#1049]
## Bug/error being reported:
Not a bug per-se, but the notification email one receives after changing their password has the following text:
```
Hello <user>

Your password has been successfully changed at Nexus Mods.

If this was not you, please change your password immediately to secure your account.
```
The last line is rather vexing. How can one change their password if someone else has already changed it without your knowledge? It would be a good idea to rephrase that line.

**Comment by Pickysaurus** [comment]
You can reset your password if your email address still matches the account by using the password recovery process.  :)
