### ISSUE TITLE
I can not my password with any approach

### ISSUE THREAD

**Issue by astral1** [Nexus-Mods/web-issues#1050]
## Bug/error being reported:
Login process navigates to reset the password page. But, I can't change my password with the below message:

```
Validation failed: Name can only contain alphanumeric characters
```

### Reset with login

1. Sign in
1. Redirected to a password reset page
1. Type my new password into a form

### Reset with the link about `forgot password`

1. Sign out
1. Navigate to sign-in page
1. Click the link labeled with `Forgot your password`
1. Click a reset link in my inbox
1. Try to change my password

### Change my password from `https://users.nexusmods.com/user/edit`

1. Sign in
1. Redirected to a password reset page
1. Move to `https://users.nexusmods.com/user/edit` directly
1. Click security tab

## Expected result:

I can change my password with any method.

### Reset with login

get below message and failed

```
Validation failed: Name can only contain alphanumeric characters
```

POST /user/change_password -> `HTTP Status 422`

### Reset with the link about `forgot password`

get HTTP 500 error

### Change my password from `https://users.nexusmods.com/user/edit`

GET /user/security/edit -> `HTTP Status 422`

**Comment by mrmason** [comment]
Thanks for reporting this - we are aware of the issue and are working on a fix, but it might take a few days.

The base problem lies in the fact that your username was created at a time when the username validation was either not working correctly, or if your account is very old, the validation was much more relaxed.

If you reach out to the community team on `support@nexusmods.com` with your username they will be able to help you - if your username contains underscores, spaces or is over 26 characters then you'll need to provide them with a username you'd like to change to that doesn't have any spaces, special characters and is under 26 characters long.

Sorry for the invoncenvience.

**Comment by Vaporous** [comment]
Was trying to figure this out myself because I was getting the same error. Guess I have to get my account of 12 years (I went digging, my "Welcome to The Nexus Forums" email is from 2007) renamed because you guys decided in the last year (or likely, 6 months or newer) underscores in user names are bad, but thanks for the email address to contact so I'll be able to eventually get back in.

**Comment by Pickysaurus** [comment]
These issues should now be resolved. Please contact support@nexusmods.com if you continue to have issues.
