### ISSUE TITLE
New User Portal: Security, Mobile Number not working

### ISSUE THREAD

**Issue by FelesNoctis** [Nexus-Mods/web-issues#1051]
## Bug/error being reported:
In the new portal, when attempting to add a cell phone number for recovery, the "Update Mobile Number" form button isn't functioning. Clicking it shows no response, no traffic, and refreshing the page shows no changes have been made.
_**Update:** This appears to be the case with or without 2FA enabled._

## Steps to reproduce:
1. Go to https://users.nexusmods.com/user/security/edit
2. Attempt to add mobile phone number for recovery

## Expected result:
Mobile phone added to account, confirmation text sent to phone.

## Actual result:
No response from page.

**Comment by mrmason** [comment]
Thanks, we're looking into other similiar reports at the moment, are you trying to add a US number or are you from another country ?

**Comment by mrmason** [comment]
Can you please try again now, we've changed a few things on our end - we were trying to send SMS from a UK mobile number, and it looks like a USA one works better!

**Comment by FelesNoctis** [comment]
Sorry for the delay! Apparently these got lost in my email. I also apologize, I'd forgotten to add that I'd tried both US and CAN numbers.

This appears to be resolved now! I was able to enter my CAN number and successfully receive the confirmation SMS, and enter code. Thank you!
