### ISSUE TITLE
API lack of data

### ISSUE THREAD

**Issue by robertas92** [Nexus-Mods/web-issues#1053]
## Bug/error being reported:

Lack of data at Nexus Mods Public API for Upload permissions.

`/v1/games/{game_domain_name}/mods/{mod_id}/files/{file_id}.json`

## Steps to reproduce:

https://api.nexusmods.com/v1/games/newvegas/mods/67841/files/1000057460.json

## Expected result:

 {
      "file_id": 1000057460,
      "name": "Fire Animation Variants",
      "version": "1.1",
      "category_id": 1,
      "category_name": "MAIN",
      "is_primary": true,
      "size": 981,
      **"upload_permission": true, // allowed or not?**
      "file_name": "Fire Animation Variants-67841-1-1-1573521273.7z",
      "uploaded_timestamp": 1573521273,
      "uploaded_time": "2019-11-12T01:14:33.000+00:00",
      "mod_version": "1.1",
      "external_virus_scan_url": "https://www.virustotal.com/file/d9cce30222a5bd7aae277c16ae76bfa0cb7da8440d8370142cc552a3b1ee4828/analysis/1573521284/",
      "description": "Have fun!",
      "size_kb": 981,
      "changelog_html": "Fixed Lever Action Shotgun shells.\nAdded two variants for the Varmint Rifle. (2hrAttack8)",
      "content_preview_link": "https://file-metadata.nexusmods.com/file/nexus-files-meta/130/67841/Fire Animation Variants-67841-1-1-1573521273.7z.json"
    }

![image](https://user-images.githubusercontent.com/49637695/69435983-328b8700-0d49-11ea-8f42-5b2c5425a7e2.png)

## Actual result:

```
 {
      "file_id": 1000057460,
      "name": "Fire Animation Variants",
      "version": "1.1",
      "category_id": 1,
      "category_name": "MAIN",
      "is_primary": true,
      "size": 981,
      "file_name": "Fire Animation Variants-67841-1-1-1573521273.7z",
      "uploaded_timestamp": 1573521273,
      "uploaded_time": "2019-11-12T01:14:33.000+00:00",
      "mod_version": "1.1",
      "external_virus_scan_url": "https://www.virustotal.com/file/d9cce30222a5bd7aae277c16ae76bfa0cb7da8440d8370142cc552a3b1ee4828/analysis/1573521284/",
      "description": "Have fun!",
      "size_kb": 981,
      "changelog_html": "Fixed Lever Action Shotgun shells.\nAdded two variants for the Varmint Rifle. (2hrAttack8)",
      "content_preview_link": "https://file-metadata.nexusmods.com/file/nexus-files-meta/130/67841/Fire Animation Variants-67841-1-1-1573521273.7z.json"
    }
```

**Comment by Pickysaurus** [comment]
We do not return any permission information via the API, so this is not a bug. Thanks for the suggestion.
