### ISSUE TITLE
Manual Downloads won't download

### ISSUE THREAD

**Issue by SovietAmerica2** [Nexus-Mods/web-issues#1054]
## Bug/error being reported:
When I go to manually download mods i click download mods, then nothing happens except the URL changes.

## Steps to reproduce:
1.Go to a mod on Nexus (The ones I've had trouble with are New California for FNV and Underground hideout for FNV)
2.click on manual download

## Expected result:
For it to pop up on the bottom of my browser saying its downloading like everything else does when you manually download it

## Actual result:
Nothing except the URL was changed. For example, with the underground hideout mod, the original URL was https://www.nexusmods.com/newvegas/mods/37884 once I clicked on manual download it changed to https://www.nexusmods.com/newvegas/mods/37884?tab=files

**Comment by Pickysaurus** [comment]
That is normally because you have to pick from multiple main files.
