### ISSUE TITLE
validation emails links not working

### ISSUE THREAD

**Issue by deathbydigre** [Nexus-Mods/web-issues#1055]
## Bug/error being reported:
username:  deathbydigre
Trying to validate my account from inactivity and Validation link from email, all i get is
ERROR
Confirmation token has expired or was invalid.

## Steps to reproduce:
Login
Click on resend activation email
Open email and click on confirm my account
Error shows up that token is expired or was invalid
*no big wait time is between these steps to cause the expiration of the email*

## Expected result:
to validate my account

## Actual result:
unable to validate my account

**Comment by Yobleed** [comment]
Getting the same problem here. 
![Naamloos](https://user-images.githubusercontent.com/13781636/69517563-6a671a00-0f55-11ea-9804-a927670cf03c.png)

**Comment by Yobleed** [comment]
Got the same problem here. 
![Naamloos](https://user-images.githubusercontent.com/13781636/69517626-95ea0480-0f55-11ea-8ce4-401fbed2511b.png)

**Comment by deathbydigre** [comment]
for those who don't know how to resolve this problem ASAP 
https://help.nexusmods.com/article/34-i-cannot-register-or-login-to-my-account-what-can-i-do
use the alternative step from that and they should validate it quickly if you follow what is asked on that page

**Comment by Yobleed** [comment]
Resending Confirmations is broken now too.

**Comment by Pickysaurus** [comment]
Hi guys, 

Can you please email support@nexusmods.com and we'll look into each of your accounts.
