### ISSUE TITLE
Error 521 - Web Server is Down

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1056]
## Bug/error being reported:
Cannot access the Nexus Mods sites

## Expected result:
Skyrim SE Nexus home page on my screen

## Actual result:
Error 521 - Web Server is Down error message in my browser.

**Comment by mrmason** [comment]
Thanks - we're aware of the issue and are working on getting everything back up at the moment.

**Comment by scjohnson1981** [comment]
You're welcome.

**Comment by Pickysaurus** [comment]
This should be now resolved.
