### ISSUE TITLE
User Password Restrictions need a redo.

### ISSUE THREAD

**Issue by uretard** [Nexus-Mods/web-issues#1058]
## Bug/error being reported:
Password strength restrictions favor bruteforce attacks and non-user friendliness.

## Expected result:
Follow more modern password strength designs. Even the guy who made these recommendations back in the day regrets doing so: [Source](https://gizmodo.com/the-guy-who-invented-those-annoying-password-rules-now-1797643987) TLDR: He's sorry, length trumps restrictions, lose the character type restrictions.

## Actual result:
Still stuck with frustrating archaic password rules that encourage users to put a number and special character at either end of the password, which basically means most passwords will be 10 random characters, with the first or last 2 characters being a number and special character, thus reducing the brute force set. Essentially: less security AND frustrated users.

**Comment by Pickysaurus** [comment]
Not a bug.
