### ISSUE TITLE
Forum search in topic is not working 

### ISSUE THREAD

**Issue by qeerl** [Nexus-Mods/web-issues#1059]
## Bug/error being reported:
Forum search in topic not working 

## Steps to reproduce:
Go to a topic on https://forums.nexusmods.com, type something to search for, click the magnifying glass to seach "This topic".

## Actual result:
The search redirects to: https://forums.nexusmods.com/app=core&module=search&do=search&fromMainBar=1

Tried with FF, Chromium, Edge, IE

**Comment by Pickysaurus** [comment]
We are aware of this issue and working on a fix.

**Comment by qeerl** [comment]
> 
> 
> We are aware of this issue and working on a fix.

Ok, thanks !

**Comment by Pickysaurus** [comment]
This was fixed a few weeks ago.

**Comment by JoaquinSuez** [comment]
It is broken again. Redirects to https://forums.nexusmods.com/index.php?app=core&module=search&do=search&fromMainBar=1
