### ISSUE TITLE
Going to the next page on search takes you to the bottom of the next page, not the top

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#106]
As per title, if you're going to the next page on mod search you go to the bottom of the page. This means you have to scroll to the top to brows the mods in the intended order. It's a minor annoyance.

**Comment by NoShotz** [comment]
Can confirm.

**Comment by verenion** [comment]
Assigned PT#151607713

**Comment by mrmason** [comment]
This should be fixed.
