### ISSUE TITLE
Previews of uploaded images in profile activity are visible after the image is deleted

### ISSUE THREAD

**Issue by dracaenamarginata** [Nexus-Mods/web-issues#1061]
## Bug/error being reported:
Previews of images that were deleted are visible on a non-supporter account, on a non-supporter account with adult content turned off, when logged out of Nexus. 

## Steps to reproduce:
1. Open the profile of a user that
a) chose the _Show activity on your profile_ option under _Your activity on Nexus_ in their preferences;
b) uploaded an image that was later deleted or otherwise closed access to.
2. Clicking on a link to the image leads to **ERROR Image not found** page.
3. Preview of the image is still visible in their profile.

### Example:
Warning: image previews you can see using the links below are NSFW (nudity)
1. https://www.nexusmods.com/users/4026490 (user: innorvous)
2. https://www.nexusmods.com/users/50692446 (user: shabota1)

## Expected result:
The previews are deleted or censored.

## Actual result:
The previews are visible to anyone.

**Comment by Pickysaurus** [comment]
We are aware of this issue, thanks for the report.

**Comment by Pickysaurus** [comment]
This isn't likely to be something we fix until we rebuild the entire activity log system so I will close this for now.
