### ISSUE TITLE
'Download with Vortex' button doesn't appear, Vortex won't 'Fix Nexus Mods Links in Chrome'

### ISSUE THREAD

**Issue by DayleD** [Nexus-Mods/web-issues#1063]
## Bug/error being reported:
I'm logged into my account in the manager and Chrome.
I've tried 'fixing' chrome for compatability, and Vortex says there was no issue and no changes were made.
All downloads only show the 'manual' button.
I'm trying to mod Witcher 3, which is listed as supported.

## Steps to reproduce:
Install latest version of Vortex. 
Install Chrome v 78.0.3904.108.
Log into Nexus with Chrome.
Pair Chrome to Vortex.
Refresh Chrome, access mods as sorted by most popular.
Click 'files'.  Observe lack of corresponding button.
Close Chrome. Click "Fix Nexus Mods Links in Chrome", open Chrome.
Observe lack of corresponding button.

## Expected result:
'Download with Vortex Button' appears.

## Actual result:
No 'Download with Vortex Button' appeared.

**Comment by Pickysaurus** [comment]
It may be that the author disabled the button, you'll need to provide examples.
