### ISSUE TITLE
 PROBLEMS WITH FOLLOWERS skyrim

### ISSUE THREAD

**Issue by Correas7** [Nexus-Mods/web-issues#1064]
## Bug/error being reported:

I have mods in the game, but all installed through vortex, the problem is that when I'm going to talk to a follower, it gives me the option to follow me, but nothing else, it stays in that dialogue and now, it doesn't follow me or I can do anything with him

## Steps to reproduce:
nothing, it’s just trying to talk to them,

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
what I hope is that someone can tell me how I do so that they are the followers as they should be, with all their options and others, and that they follow me

**Comment by Pickysaurus** [comment]
This is not a problem with our website, please use our support forums, Discord server or the mod page for the mods you're using.
