### ISSUE TITLE
New update broke EVERYTHING

### ISSUE THREAD

**Issue by longlivethestarrk** [Nexus-Mods/web-issues#1066]
## Bug/error being reported:

Website won't even show up. Everything is white and code is everywhere. Can't even access the website because of it
## Expected result:

To be able to access a nice user friendly mod nexus
## Actual result:

A broken website that is unusable 
![2019-12-13](https://user-images.githubusercontent.com/58863956/70830698-70af2000-1db6-11ea-8e03-70933ac097a1.png)
![2019-12-13](https://user-images.githubusercontent.com/58863956/70830723-7dcc0f00-1db6-11ea-9191-bb3676570ede.png)

**Comment by longlivethestarrk** [comment]
All I wanted was to download mods. I don't even care about the new cheap schemey Premium advertising's. Just fix this damn mess already

**Comment by mrmason** [comment]
The CSS and Javascript isn't loading for you - is this happening in all browsers ? Everything seems to be working correctly from here.

**Comment by longlivethestarrk** [comment]
I'm using Google Chrome right now and that's where the CSS and Javascript doesn't appear to be loading. It took me awhile since Microsoft Edge is kinda already broken on my computer, but nexus appears to be working on there. Chrome is still a mess though

**Comment by Pickysaurus** [comment]
If this problem continues, feel free to reopen the issue. It appears to be exclusive to your setup.
