### ISSUE TITLE
pop-up box/separate page file download method setting doesn't work

### ISSUE THREAD

**Issue by yarrmateys** [Nexus-Mods/web-issues#1068]
## Bug/error being reported:
the pop-up box/separate page setting for file download method doesn't seem to work anymore. file download itself defaults to separate page instead, while mod requirements default to pop-up box. changing between settings doesn't have any effects.

## Steps to reproduce:
click the download button.

## Expected result:
expected the pop-up box setting to merge the download page's results into the required mods pop-up that appears. expected the separate page to merge the pop-up's requirements into download page.

## Actual result:
required mods always appear on a pop-up. download always appears on a separate page, instead of merging both to appear on one page and respecting the setting, redownloading all the data again and contributing to increased bandwidth usage (and thus bigger server costs) for both the server and user.

**Comment by Pickysaurus** [comment]
The recent changes to the download page for non-Premium users have made this option redundant. I will raise it with the team as we may need to remove the option. 

Thanks for the report.

**Comment by Pickysaurus** [comment]
This setting has been removed.
