### ISSUE TITLE
Painfully Slow

### ISSUE THREAD

**Issue by GamerPerson1** [Nexus-Mods/web-issues#1069]
## Bug/error being reported:
Painfully slow loading of website. And clicking every link takes forever. This has only started following the recent update. I have been downloading Subnautica mods for the last year with no speed issues whatsoever.

## Steps to reproduce:

Simply visit the site and click on "files" on any of the mods.

## Expected result:
Regular loading times, just like it has been for the past year that I have been using the site.

## Actual result:
Extremely slow loading. 3 or 4 mintutes from click to anything loading.

**Comment by mrmason** [comment]
If this only happened around 1hr ago, then I think it was us deploying a fix for some downloads showing requirements when there weren't any. If not, and this is still happening then ...

Is this _only_ on the file tab, or is this every page?

If it's every page then please can you scroll to the bottom of the page, and in the footer it should say something like `Page served in 0.954s (rd04)` - what is that showing for you ?

**Comment by BIack-X** [comment]
I also have this issue throughout the entire nexus, not just file tab, **regardless** of the browser I use.

Page served in
20.42s (rd09)

That load time is an average. Sometimes it exceeds 60 seconds. It all started after the last update.

**Comment by Pickysaurus** [comment]
If the problem persists, please re-open the ticket.
