### ISSUE TITLE
Sorting not following default sort order

### ISSUE THREAD

**Issue by NoShotz** [Nexus-Mods/web-issues#107]
I have my default sort order set to by endorsements
![image](https://user-images.githubusercontent.com/13302841/31076410-f4b70f8a-a747-11e7-86f7-a92840c68433.png)
But when i go to to a mod category, the sort is set to by date published
![image](https://user-images.githubusercontent.com/13302841/31076452-29c17c92-a748-11e7-894d-b9794e47f5ad.png)

**Comment by Thallassa** [comment]
Yes it also doesn't respect default number of items to show per page. 

It _was_ working when we initially got access, I think somewhere along the line of fixing other bugs with search, this one broke. (It wasn't working before you fixed the pagination bug though).

**Comment by verenion** [comment]
Assigned PT#151607427

**Comment by mrmason** [comment]
This should be fixed.
