### ISSUE TITLE
New User Portal: Locked Out Due to Site-Level Bug

### ISSUE THREAD

**Issue by Riddle78** [Nexus-Mods/web-issues#1070]
## Bug/error being reported:

Cannot log into Nexus Mods; Site demands I reset my password,then the validation fails when I do,claiming my email is already taken.
## Steps to reproduce:

1. Go to login page.
2. Attempt to log into an account that existed before the new User Portal.
3. Reset password.
## Expected result:

Password resets,and I can browse Nexus Mods at my leisure.
## Actual result:

The site throws up an error box; "ERROR. Validation failed: Email has already been taken." Additionally,the password isn't reset,functionally locking me out of Nexus Mods,and literally all of its meaningful content. See attached image for the error page.
![Untitled](https://user-images.githubusercontent.com/58883265/70849942-11531d80-1e53-11ea-980f-296a4a7a5d12.png)

**Comment by mrmason** [comment]
Please can you provide your account ID ? If you'd prefer to do it privately then please e-mail support@nexusmods.com with the details

**Comment by Riddle78** [comment]
How would I go about getting my Nexus Mods account ID? I use the unofficial continuation of NMM,not Vortex,and since I cannot actually log into Nexus Mods,I can't get it from the Nexus Mods site directly.

**Comment by mrmason** [comment]
I can get it from your username if you know that.

**Comment by WhyDoesThouForcethMe** [comment]
Having the same issue here. I'm logged in to the mods site (where I host my mods) just fine. It's the forums I can't access. Keeps asking to reset password, but can't get past that (RESET PASSWORD is grayed out). Also takes forever to load this page.

![image](https://user-images.githubusercontent.com/58970395/70973286-65d4e380-2073-11ea-8dd1-bacbe04c06ba.png)

**Comment by Riddle78** [comment]
It's been over a week,and my situation's unchanged,and there has been absolutely zero indication that this is anything more than screaming into a hurricane.

**Comment by mrmason** [comment]
Did you email the support team ? If so, please give me your ticket number so I can take a look - otherwise please respond here with your username.

**Comment by Pickysaurus** [comment]
The user has still not contacted support, however, I was able to extrapolate the account details from the provided screenshot. 

You had two accounts with the same email address. I have removed the duplicate.
