### ISSUE TITLE
Tracking Center

### ISSUE THREAD

**Issue by mitzie92** [Nexus-Mods/web-issues#1071]
None of my tracked mods are showing. Just tons of page tabs with zero content. I updated my account the day before so this might be the issue. I should only have one page. Tried to re-track some and they still dont show. Download history seems fine. I already checked Java and have no Ad Blocking.

Click on link

One page of tracked mods

Empty tabs

**Comment by Pickysaurus** [comment]
If this is still a problem could you please open a new report including a screenshot?
