### ISSUE TITLE
No way to access user settings on mobile style

### ISSUE THREAD

**Issue by LostDragonist** [Nexus-Mods/web-issues#1074]
With the usual style, clicking on your user icon gives you the ability to navigate to your "preferences" and your "settings".  
![image](https://user-images.githubusercontent.com/7862539/71345159-cc4d7c00-2521-11ea-9c5e-948ee73d991f.png)

Clicking preferences leads to https://www.nexusmods.com/users/myaccount
Clicking settings leads to https://users.nexusmods.com/user/edit

With a smaller window size, the site switches over to a mobile style, and the only option available is "settings".  
![image](https://user-images.githubusercontent.com/7862539/71345250-04ed5580-2522-11ea-81ac-a76df5228ea1.png)

Clicking settings leads to https://www.nexusmods.com/users/myaccount

Issues:
1.  The two styles are inconsistent on what clicking "settings" will take you to.
2.  There is no method available to reach https://users.nexusmods.com/user/edit on the mobile style.

**Comment by Pickysaurus** [comment]
The team are aware and will include it in a future update.

**Comment by BigBizkit** [comment]
An "Account Settings" button has since been added.
