### ISSUE TITLE
error reseting my password

### ISSUE THREAD

**Issue by LeoRaiju** [Nexus-Mods/web-issues#1075]
![NEXUS SCREW UP](https://user-images.githubusercontent.com/59192752/71399266-0e91be80-25f1-11ea-85f3-581b7528c386.png) i just put in a series of eight "1"s to show how it is

## Bug/error being reported:
"Can't reset my password"
I tried to log into nexus, got my password and was told I NEEDED to reset it, I proceeded to try and do so but after typing in the password on the "password" and "confirm password" boxes,  the reset password button stayed greyed out and it had a red outline around the boxes, along with the words "Password" and "confirm password" in the boxes bleeding through making it near impossible for me to check what I wrote. I attempted atleast a dozen different passwords I could use including with capital letters, lower case letters, numbers and symbols like the pound symbol, none worked and it all left a red like around the boxes and the reset password button greyed out.
completely preventing me from accessing my account

## Steps to reproduce:
I explained it there but I guess
1: attempt to reset password
2: check for grey boxes?

## Expected result:
I was expecting to reset my password and easily sign in again

## Actual result:
am now completely unable to access the nexus and all the mods I had saved that I wanted to try

**Comment by mrmason** [comment]
The Javascript doesn't seem to be rendering correctly in your browser, are you perhapbs blocking it ?

![image](https://user-images.githubusercontent.com/93157/71401412-ac04e680-2621-11ea-977d-f64b5ada09f8.png)

This is what you should be seeing

**Comment by LeoRaiju** [comment]
thank you for the assistance, I do not think I'm blocking it, but I have
just been tired and having horrible luck with technology lately, so maybe I
missed something.
it is now allowing me to reset my password, thank you again for your help
