### ISSUE TITLE
Image upload does not work - can't publish mods

### ISSUE THREAD

**Issue by VikMorroHun** [Nexus-Mods/web-issues#1077]
##Bug/error being reported:
Image upload does not work. I've created two translation mods. I can't upload images to any of them. Thus I can't publish them.

## Steps to reproduce:
1. Create a mod. 
2. Go to media. 
3. try to add image(s). Upload message appears but nothing happens.

## Expected result:
Uploaded image(s) appear on Nexus.

## Actual result:
Nothing happens aside from a Javascript error message. Something like "--". Doesn't really help.
Tried Vivaldi and Google Chrome (which are basically the same.)

**Comment by Pickysaurus** [comment]
This should be fixed. Thanks for the report.
