### ISSUE TITLE
Impossibility to edit my "About me" page in my profile.

### ISSUE THREAD

**Issue by ClanggedinNexus** [Nexus-Mods/web-issues#1078]
**What is the issue?**

Since two days at least, I have been unable to edit my "About me" page in my profile.

**What happens exactly?**

What happens is that every time I want to save the changes, I am send to a capcha page, asking me to check a box to verify I am not a robot, I check this box, which validate the capcha, and then, I end up on a empty page.

Here is a screenshot of this page: 
![Capture d’écran (61)](https://user-images.githubusercontent.com/59284968/71517937-9eb15b80-28b0-11ea-8b54-8089b8f9dac6.png)

It is worth noting that with continued attempts, I have been able to progressively rebuild part of my page that had been deleted by a previous attempt; the bug was occurring at random, with identical edits being saved or leading to that Internal server error page; until it becomes completely impossible to save any edit after roughly one hour of attempts, and from then, any and every attempt failed.

**How to reproduce it:**

Go on your "About me" page on your profile, write anything or place any link, then save and validate all capchas you are asked to complete.

## Expected result:

The expected result is the page saving the changes made.

## Actual result:

The result that actually happens is an error message, as shown in the screen previously posted.

**Remarks:**

I have remarked that the capcha system where you were asked to find diverse things like bus on a mosaic was occurring randomly; also, I have noticed that the failure rate was much higher when the capcha was occurring.
Also, I first thought it could be tied to the URL links present in my "About me" page, however, before I try to edit that page and encounter that issue, my page counted much more URL links than currently, and I never encountered any issue when editing that page and adding new URL links; so I highly doubt that it can suddenly cause issues now.

Thanks for your work.

**Comment by Pickysaurus** [comment]
This should be working now.
