### ISSUE TITLE
Slow site loading/Error 522 (Connection Timeout) & 524 (Bad Gateway)

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1079]
## Bug/error being reported:
Getting numerous Error 522 & Error 524 when navigating the Nexus/sending Nexus PMs...

## Expected result:
Fast Nexus site loading/send or receive Nexus PMs without having to deal with slow loading times/Error 522/Error 524...

## Actual result:
Slower than molasses loading times/random Error 522/Error 524 when attempting to navigate the sites...  This has been an ongoing issue & is getting beyond ridiculous.  Nexus is the only site I have issues getting to run correctly half the time.  All other sites like Yahoo/E-Bay/etc load up just fine.

**Comment by Pickysaurus** [comment]
This was due to high traffic on the site and should return to normal over the next few days
