### ISSUE TITLE
"Gateway Time-out" and "Invalid download index" Errors when using MO2

### ISSUE THREAD

**Issue by phrayz** [Nexus-Mods/web-issues#1080]
## Actual result: The file showed as "Pending" in the downloads window and then failed with the error: 

19: 03: 06 [D] Download started
19: 03: 06 [D] download requested: nxm://SkyrimSE/mods/22603/files/116979?key=JmY5waVvQUHvvwueTTwowA&expires=1577926980&user_id=4059947
19: 03: 06 [D] add nxm download: nxm://SkyrimSE/mods/22603/files/116979?key=JmY5waVvQUHvvwueTTwowA&expires=1577926980&user_id=4059947
19: 03: 45 [C] uncaught exception in handler (object qt_scrollarea_viewport, eventtype 82): state: invalid download index 2506

And then when checking the mod for an update:

19: 04: 11 [D] Downloads after refresh: 2507
19: 04: 23 [W] request failed: Error transferring https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/22603/files - server replied: Gateway Time-out
19: 04: 23 [D] Request to Nexus failed: Error transferring https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/22603/files - server replied: Gateway Time-out
19: 05: 05 [I] Checking updates for 1 mods...

Link to the affected mod/image (if relevant): https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=116979&nmm=1&game_id=1704

I've included the log from MO2. It's not very extensive though. I know that you don't troubleshoot MO2 issues. I'm wondering if this is an error that you've seen before and if you know of a fix for it. It only started happening over the past few days, but it seems to be getting worse.

[mo_interface.log](https://github.com/Nexus-Mods/web-issues/files/4011671/mo_interface.log)

**Comment by Pickysaurus** [comment]
This is simply the site getting overwhelmed by the number of users online. It should be back to normal now.

**Comment by phrayz** [comment]
I'm still receiving Invalid download index errors.

**Comment by BIack-X** [comment]
At this moment in time it is completely impossible for me to download anything through any of the Mod Managers. Downloads simply pending for about half a minute and then either one of three things:
Gateway Time-out;
Failed to request file info from nexus: Operation cancelled;
Request failed: Operation cancelled
