### ISSUE TITLE
Forum Chat Unavailable

### ISSUE THREAD

**Issue by YourFriendJessie** [Nexus-Mods/web-issues#1081]
## Bug/error being reported:
Nexus Forum chat unavailable/not responding, displays error "forums.nexusmods.com redirected you too many times."

## Steps to reproduce:
1. Log into your Nexus Mods account.
2. Enter the "Community" drop down and select "Forums".
3. Select the "Chat" tab located at the top right of the window.

![image](https://user-images.githubusercontent.com/57145363/71634812-2d91e100-2bed-11ea-825a-0b37fe6c44d4.png)

![image](https://user-images.githubusercontent.com/57145363/71634836-55814480-2bed-11ea-8f0a-790edb7c93f5.png)

## Expected result:
To be redirected to a chat window.

## Actual result:
Host fails to respond/host doesn't resolve.

**Comment by YourFriendJessie** [comment]
Clearing cookies doesn't solve the issue, the issue is likely server side rather than client.

**Comment by Pickysaurus** [comment]
The chat function on the forum was retired a long time ago. You can join our Discord at https://discord.gg/nexusmods
