### ISSUE TITLE
cant download 

### ISSUE THREAD

**Issue by bertbertson69** [Nexus-Mods/web-issues#1082]
Bug/error being reported:
it keeps failing to download things when i try to download them through vortex

Steps to reproduce:
download things

Expected result:
it downloads

Actual result:
it doesnt download

**Comment by VikMorroHun** [comment]
It happens to me too. I think this is related somehow to mods which have required files (either on the Nexus or other sites, like SKSE64).

**Comment by halliecat99** [comment]
Same. It is really aggravating when I have to try a dozen times before a mod downloads, especially since I paid for premium membership in order to get faster downloads.
Most common reasons: esockettimedout and API currently not reachable. This has been over the last 2 or so weeks.

**Comment by mcbarker69** [comment]
Downloads failing with NexusMods and Vortex... same as above.

**Comment by BIack-X** [comment]
At this moment in time it is completely impossible for me to download anything through any of the Mod Managers. Downloads simply pending for about half a minute and then either one of three things happen:
Gateway Time-out;
Failed to request file info from nexus: Operation cancelled;
Request failed: Operation cancelled

**Comment by Pickysaurus** [comment]
This was a temporary issue caused by high traffic
