### ISSUE TITLE
Corrupted installation error on fresh install

### ISSUE THREAD

**Issue by Bus42** [Nexus-Mods/web-issues#1083]
## Bug/error being reported:

Every time I launch Vortex I get an error saying that my installation is corrupted.

## Steps to reproduce:

Completely delete wine prefix to erase all traces of the previous installation.
Download Vortex self-installer
Rename to FalloutNVLauncher as per instructed to launch via Steam/Proton
Launch through Steam
Remove installer, copy Vortex.exe to Fallout New Vegas folder and rename FalloutNVLauncher.exe
Boom - there's the error on launch.

## Expected result:

Expected Vortex to launch like it always did

## Actual result:

Get an error saying my installation is corrupt.

Never had a problem before this update, always performed clean installs.
As a workaround, I simply install Vortex every time I play FNV. Kind of tedious.

Running Vortex 1.1.5 on Linux Ubuntu Budgie 19.10 using Proton 4.11-11 on Steam. Previously ran Vortex 0.14.3

**Comment by Pickysaurus** [comment]
This is not the place to add Vortex reports, please see https://github.com/Nexus-Mods/Vortex
