### ISSUE TITLE
Site flavor pictures are borked.

### ISSUE THREAD

**Issue by Draveurs** [Nexus-Mods/web-issues#1087]
## Bug/error being reported:
Pictures that are used site wide, to add flavor to the tabs (Home, Mods, Media, etcetera) and everywhere else, are not present. Replaced instead with text stating what should be there or with just a letter. Since no one else seems to be having this issue, I imagine it's my browser, but I have no idea how since Firefox is still popular (I think).
The issue persists even when enabling all cookies, turning off anti trackers, turning off Firefox Enhanced Tracking Protection, and disabling all addons.

## Expected result:
Site loads with all its neat little graphics that improve the overall look of the site.

## Actual result:
This.
![2020-01-07 16_14_53-Creation Kit Multiple Masters Fix at Skyrim Special Edition Nexus - Mods and Com](https://user-images.githubusercontent.com/59625605/71930328-6db30f80-3169-11ea-9edc-e4a1d28949ee.png)

**Comment by Draveurs** [comment]
Also while I'm here I just wanna say that I really liked how when you clicked Manual Download on a mod before, it only opened an in window pop up instead of a new page altogether, and that I don't like how it works now.

**Comment by Pickysaurus** [comment]
Your font issue is caused by the custom font you are enforcing.
