### ISSUE TITLE
New uploads are not available for download.

### ISSUE THREAD

**Issue by DeadCodex** [Nexus-Mods/web-issues#1088]
## Bug/error being reported:
I have uploaded some new files but even after 3 hours they still say that the files are being uploaded to the Nexus servers and will be available shortly.

## Steps to reproduce:
You can check the [updated] tab in Skyrim Special Edition and see that first 9 mods are still not available for download.

**Comment by DeadCodex** [comment]
Seems the issue has been resolved. But I would like to know why it had happened.

**Comment by mrmason** [comment]
Thanks for the report.

One of our workers as part of the upload system had crashed and didn't recover automatically like it should, we'll investigate further next week and attempt to fix the worker so it does recover when something goes wrong.
