### ISSUE TITLE
Automatic email not being sent

### ISSUE THREAD

**Issue by vovalos** [Nexus-Mods/web-issues#1089]
## Bug/error being reported:
Apparently I haven't used the site for a bit, so when logging in it asks to verify email. However the verification email is not being sent to me(it's been a few hours and I've tried multiple times in different browsers). If I try to register again under the same email, I get an email about already being registered instantly, so there's no issue with my email provider or emails from you being blocked.

## Steps to reproduce:
not sure, you would know better.

## Expected result:
verification email sent

## Actual result:
no email being sent (or at least none being received)

**Comment by Pickysaurus** [comment]
This is not a bug. It's either your email provider or your account doesn't use the email address you think it does.

Please see this help page https://help.nexusmods.com/article/102-i-am-not-receiving-emails-from-nexus-mods-what-can-i-do

If you're still having issues, contact support@nexusmods.com

**Comment by vovalos** [comment]
So the issue is that I'm receiving emails from nexusmods in general, just not the verification email. So it's not an issue with my provider or junk or focused view. I'm getting the email saying that my email already has an associated account with no issues instantly and consistently.
I'm also 100% certain that the email when I try to sign in is right, after all your log in form does recognize that there's an associated account. 

I understand that it's easy to write this off as user incompetence, but this is a bug. I can provide screenshots if you like...

**Comment by Pickysaurus** [comment]
I appreciate you may still be having issues, however this can only be resolved by contacting support@nexusmods.com from the email address linked to your account. :) 

If the email wasn't sending at all I'm sure we'd have hundreds of users reporting this.

**Comment by vovalos** [comment]
That is reasonable. Couldn't find any contact info apart from "report a bug" on the website. Will send them an email
