### ISSUE TITLE
Sort by function un-intuitive 

### ISSUE THREAD

**Issue by Fatman0091** [Nexus-Mods/web-issues#109]
URL: https://rd.nexusmods.com/newvegas/mods/?BH=0
Bug/error being reported: Sort Menu
Steps to reproduce: Click on sort menu
Expected result: see all search functions including trending and last comment
Actual result: only see up to random
© 2017 GitHub,

**Comment by mrmason** [comment]
Assigned `PT#152602418` - and delivered.
