### ISSUE TITLE
Allow Vortex (Mod Manager) Usage without Website Login

### ISSUE THREAD

**Issue by Zottelchen** [Nexus-Mods/web-issues#1091]
## Feature request (Summary):
Please let me click on "Mod Manager Download" on the website without the need to login to the website.

## Steps to reproduce:
I let my browsers clean my history with each shutdown for privacy reasons. That means if I just want to quickly download a mod I have to login to nexus, do 2FA (which requires another device, and an fingerprint login there) and then navigate to the mod.

## Expected result:
Instead it would be great if I could just click on "Mod Manager Download" without login. Vortex should be able to verify that I am a valid (premium) user and just download.

### Alternatives
1. Add a button to vortex, which opens a browser and instantly logs me in.
2. An in-app mod browser. But that would have to be very good and able to open multiple mod pages to compare etc.

## Actual result:
Frustration.

([Please don't say this is a Vortex request😅](https://github.com/Nexus-Mods/Vortex/issues/5846#issuecomment-577655827).)

**Comment by mrmason** [comment]
Hi Zottelchen,

I can see why this is a bit annoying, and I've discussed it with the team here and we're inclined not to change it for a number of reasons -

1) Almost all users are logged into the website already.
2) If you're not logged in then there is no way of knowing if you are premium, and so we can only serve premium links to the files, which then wouldn't work correctly in any mod manager for a non premium user.
3) We have checks for inactivity for security on the website which could cause problems if you’re never logged in.

There are other, smaller, reasons that also add to this decision as well - so I’m afraid we probably won’t be changing this at this time.

In the more medium term though, I think your other two suggestions are more likey to happen and I will discuss those with the team when the time comes.
