### ISSUE TITLE
Details page of one mod not shown in Browser

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1092]
https://www.nexusmods.com/skyrimspecialedition/mods/32175
after create it, finished and say publish it's listed and header seen, but details page is cut
This issue is with this mod only
Re-publish did not help.

**Comment by BigBizkit** [comment]
Pretty sure the issue lies with the image link that was absolutely massive. How did you go about adding the image? It seems it's a raw jpeg. 

Anyway, I replaced the image link and now it's working fine.

**Comment by Dreifels** [comment]
thanks,
I have no idea what happened and how. But sometimes upload of files need extreme long, like massive lags or such.
