### ISSUE TITLE
Reset Password  - ERROR Validation failed: Name cannot be used

### ISSUE THREAD

**Issue by centaur0215663** [Nexus-Mods/web-issues#1094]
## Bug/error being reported:

I've tried to log in after a long absence (1-2 years) and was asked to reset my password after validating my account with my email. No matter what password i put in, even random strings of characters and numbers generated by lastpass, i get the 

Error
Validation failed: Name cannot be used

I've tried firefox, chrome, ie, and edge.

## Expected result:

I was expecting the site to accept a password

## Actual result:

accepted none of the 23 passwords ive tried, both hand picked and generated.
![Nexus Mods Error Reporting 1](https://user-images.githubusercontent.com/7551210/74091411-38118700-4a85-11ea-8138-df20cb29eb35.png)

![Nexus Mods Error Reporting 2](https://user-images.githubusercontent.com/7551210/74091424-54152880-4a85-11ea-9c49-3d410acf1339.png)

I HAVE noticed 4 other similar issues on the github page, but they have all been closed. I don't know whats causing the bug.

**Comment by dracaenamarginata** [comment]
Is it possible that you got banned because of the username? See Nexus TOS, section [Accounts and User Identity](https://help.nexusmods.com/article/18-terms-of-service#accounts):
> When creating an account on our services, the username you choose must be appropriate for all audiences (i.e. be free of profanity). Accounts registered with inappropriate usernames will be subject to an immediate ban.

And also [this ](https://forums.nexusmods.com/index.php?/topic/514346-inappropriate-user-names/) notice:
> If your account is banned and you don't see a notice, consider whether your username is inappropriate, and if it is, you may make a new account to ask a member of staff about it.

**Comment by Pickysaurus** [comment]
Please contact support@nexusmods.com to arrange a name change :)
