### ISSUE TITLE
Image order problems in mod with multiple editors

### ISSUE THREAD

**Issue by hypermorphicmods** [Nexus-Mods/web-issues#1095]
I recently granted another user Edit access to my mod and it's revealed a few bugs in the handling of image order on the Images tab.

1. 3 of this person's user images were promoted to mod images (this is probably the expected behavior)

1. The 3 images appear first in the mod images on every view, presumably because his username sorts before mine in the alphabet.  I'm not able to change anything about their order using the Edit Media page.  After clicking Save, the order reverts back.

1. Changing the order of my own images on Edit Media is now off by 3 positions.  To put an image where I want it, I have to place it in the grid as if the first 3 images (from the other user) didn't exist.  Specifically:

- The mod has 3 images from another author that always appear first, and 24 of my own
- On the Edit Media page, I drag the last and most recently uploaded image (position 24 of mine, 27th in the grid overall) to position 10 in the grid
- I click Save and the page reloads
- The image appears in position 13 in the grid, or as my 10th image.

**Comment by Pickysaurus** [comment]
This issue is not likely to be addressed before we migrate the mods system to use the new media library UI currently in use with Collections.
