### ISSUE TITLE
Author log displays incorrect thumbnails, is missing correct ones

### ISSUE THREAD

**Issue by megapatato** [Nexus-Mods/web-issues#1096]
## Bug/error being reported:
In the `Activity Logs` section of two of my mod pages (`10235` and `9319`), under `Author's Activity`, there is an entry for `Mod Image Added` that displays a thumbnail for an image not belonging to any of my mods. Specifically, the first `Mod Image Added` event right after the `Mod Creation` event displays a wrong image. Moreover, not all images added to the mod's page are displayed in the log.

## Steps to reproduce:
Open any of the two mods in question, go to their logs tab, expand the author's activity log, scroll to the earliest records, see the wrong images displayed, and some of the correct images not displayed. 

Do note, these mods were created Apr/Jun 2017

### Example:
1. Divine Intervention mod (`mods/10235`) 
    1. In the below screenshot, the first image I don't recognize, is not displayed in the image gallery of this mod, and probably belongs to a different mod. I included the details Firefox gave me of the image to aid in tracking what is displayed where. Observe the mismatch between the first component of the thumbnail file name and the mod id (`77169` vs `10235`).
![Annotation 2020-02-11 181444](https://user-images.githubusercontent.com/60947952/74288473-75cb1580-4cfa-11ea-8705-e3ef79e434ab.png)
    1. Moreover, none of the three images I did upload for that mod (as seen in the mod images section) are displayed in the log, and the other only entry for a `mod image added` event points to `https://staticdelivery.nexusmods.com/mods//images/thumbnails/`, with two parameter missing (I presume one for the mod, the other for the image).
1. Harvest Flora and Find any Ore (`mods/9319`)
    1. Similar behavior, displaying a thumbnail for some other mod at `https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/15927-1-1427854552.jpg` just after mod creation
    1. Of the three images I added, only the last one is displayed in the log. The two others don't even have an event associated to them.
1. A third mod I maintain (`mods/13572`) does not display this behavior.

## Expected result:
A mod's author's activity log should not display images from other mods and authors, and should display all the activity for that mod from that author.

## Actual result:
A mod's author's activity log displays images from third parties, and is missing entries.

**Comment by Pickysaurus** [comment]
Raised a Pivotal task #171379361 for this

**Comment by Pickysaurus** [comment]
Looks like there's an issue with multiple mod image uploads being logged. A fix is being worked on for this.
