### ISSUE TITLE
I cannot access my Site Settings nor can I buy premium.

### ISSUE THREAD

**Issue by axelblade013** [Nexus-Mods/web-issues#1097]
Every time I try to access my Site Settings it tells me that I do not have access to that page. I've tried logging out and back in, other browsers, and checking if my account was activated. Then I thought it was because I didnt have premium so I went to buy the 1 month premium plan and the site tells me that I need to be logged in to do so even though I'm logged in. I've tried with adblocker on and with with it off. I'm at a loss at what to do,

I have no idea how to reproduce this issue as I dont know whats causing it in the first place.

The result I'm expecting is to be able to access my site settings and pay for premium

I keep getting errors saying I dont access to do either such action.
![nexus1](https://user-images.githubusercontent.com/60941740/74299465-bcc90300-4d1a-11ea-8dcf-dc246311017c.png)
![nexus2](https://user-images.githubusercontent.com/60941740/74299467-bdfa3000-4d1a-11ea-9456-5490b125a467.png)

**Comment by Pickysaurus** [comment]
Looks like you never validated your email address when you initially registered. I've updated your account settings now. Please ensure your email address is correct.
