### ISSUE TITLE
502 Bad Gateway on Specific Mod?

### ISSUE THREAD

**Issue by mercerjt** [Nexus-Mods/web-issues#1098]
URL: https://www.nexusmods.com/oblivion/mods/49784?tab=files&file_id=1000023931

Username on the Nexus:  mercerjt

Bug/error being reported:  Attempting to download Oblivion Remastered mod (manual or with Vortex) leads to a 502 Bad Gateway page on any computer (tested with/without VPNs and on different computers).

Steps to reproduce:  Navigate to the URL and attempt to download the single file mod

Expected result:  Downloaded mod

Actual result:  502 Bad Gateway page

Link to the affected mod/image (if relevant):  https://www.nexusmods.com/oblivion/mods/49784?tab=files&file_id=1000023931

**Comment by Pickysaurus** [comment]
https://www.nexusmods.com/oblivion/mods/49784?tab=files


Please try starting at the file page rather than linking directly to the file. 


I'm not getting a 502 with that URL either way.

**Comment by mercerjt** [comment]
Yeah I figured out it's some weird combination of using CloudFlare DNS over HTTPS. Took a lot of digging and testing for that annoyance.
