### ISSUE TITLE
problematic login with 2FA or disable 2FA

### ISSUE THREAD

**Issue by khandurov** [Nexus-Mods/web-issues#1102]
## Bug/error being reported:
I can't get positive result (with 2FA) while trying to login to the site or disable 2FA.
OK, I have my recovery codes! Let's try them! Good, I'm here.
Now to the security page and try to disable 2FA.
Unsuccessfully.
Repeated 3 times with different browsers: Opera GX v.66.0.3515.75, IE v.11.657.18362.0, MS Edge 44.18362.449.0

## Steps to reproduce:
1. Open browser
2. Enter login/passsword
3. Enter 2FA code.
-->

## Expected result:
Successfull login to the nexusmods.com with 2FA and/or properly disable/enable 2FA.

## Actual result:
Window with 2FA 6-digit code just blinks and shows small red circle with exclamation mark.

![Clipboard 1](https://user-images.githubusercontent.com/61331914/75070614-a97d1b00-5504-11ea-887d-f18bb340b4f0.jpg)

**Comment by Pickysaurus** [comment]
What browser are you using? Looks like IE or Edge?

**Comment by khandurov** [comment]
Hi! It's Opera. 
--
Отправлено из Mail.ru для Android вторник, 03 марта 2020г., 19:21 +03:00 от Mike  notifications@github.com :

**Comment by Pickysaurus** [comment]
I've just installed the latest Opera browser and did not have the problem you describe. Out of interest did you add a space between the number groups?

**Comment by khandurov** [comment]
Hi!
I've never tried to put space between groups of digits.
Later I'll try to both variants - update browser and trick with space and numbers.
Best regards,
Dmitri
--
Отправлено из Mail.ru для Android пятница, 06 марта 2020г., 16:06 +03:00 от Mike  notifications@github.com :

**Comment by khandurov** [comment]
Thank you very much!
Although none of methods worked, your hint about space and group numbers gave me an idea.
I checked Google Authentificator/Settings/Time correction for codes.
After I did this, 2FA codes became perceived on "nexusmods.com".

**Comment by khandurov** [comment]
In case that 2FA keys don't work and you use GoogleAuthenticator try to check/renew GoogleAuthenticator/Settings/Time correction for codes.
