### ISSUE TITLE
Can't access to site preferences

### ISSUE THREAD

**Issue by EmpireDemocratiqueDuPoulpe** [Nexus-Mods/web-issues#1103]
**## Bug/error being reported:**
Every time I try to access to site preferences, the website show me an error "_You are not allowed to access this area!"_. This error doesn't show up with another account. My account username is Nounours7000.

**## Steps to reproduce:**
1. Connect to the account.
2. Click your profile picture.
3. Click "site preferences".

**## Expected result:**
The "site preferences" page.

**## Actual result:**
_"Error: You are not allowed to access this area!"_

Url: https://www.nexusmods.com/users/myaccount
![Error](https://user-images.githubusercontent.com/45202304/75111333-f95cfe80-5638-11ea-99d9-f6ce363bd82f.png)

**EDIT n°1:**  Same for the _"download history"_ and _"tracked mods"_ pages.

**Comment by Pickysaurus** [comment]
Please contact support@nexusmods.com it is very likely you never validated your email address when signing up. If this is the case we can fix it quite quickly :)
