### ISSUE TITLE
Issue with downloading the Official Kingdom Come Deliverance Modding Tools

### ISSUE THREAD

**Issue by benix981** [Nexus-Mods/web-issues#1104]
## Bug/error being reported: 
The mod always crash while downloading.

## Steps to reproduce: 
Go on the mod page (https://www.nexusmods.com/kingdomcomedeliverance/mods/864?tab=files&file_id=4527), click on slow download (because i'm not premium) and wait till it stops.

## Expected result: 
It's supposed to finish the download. 

## Actual result: 
It stop between 1-2 GB every time. I tried many different browsers (Chrome, Edge, Firefox) and they all stops and say : network error. I even tried with Vortex and it still stop at about 1-2 GB saying : Requesting url ''https://supporter-files.nexus-cdn.com/2298/864/Kingdom%20Come%20Deliverance%20Official%20%20Modding%20Tools-864-3-0-1581490177.zip?md5=oaoMhTodkooylD7LR6GyoA&expires=1582417256&user_id=82952053&rip=173.178.221.14'' failed with status ''504 Gateway Time-out''. 

When I tried to ping the server, this was the result :
Pinging files.nexus-cdn.com [185.246.209.245] with 32 bytes of data:
Reply from 185.246.209.245: bytes=32 time=20ms TTL=58
Reply from 185.246.209.245: bytes=32 time=32ms TTL=58
Reply from 185.246.209.245: bytes=32 time=27ms TTL=58
Reply from 185.246.209.245: bytes=32 time=30ms TTL=58

Ping statistics for 185.246.209.245:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 20ms, Maximum = 32ms, Average = 27ms

**Comment by Pickysaurus** [comment]
Does this issue persist? I am unable to replicate it.

**Comment by benix981** [comment]
I tried on an other computer and it worked! Thanks for trying :)
