### ISSUE TITLE
Req:  Search in Posts tab

### ISSUE THREAD

**Issue by Darklocq** [Nexus-Mods/web-issues#1105]
## Bug/error being reported:
It's rare for a site like this to have a Posts-type feature and no way to search it. Even this bug tracker I'm using right now has that feature, as does the Nexus Forum.  I don't think I've ever seen any sort of webboard/forum site without this basic feature before - just the main NexusMods site.

## Expected result:
Need to be able to search the Posts tab by keyword, phrase, quoted string, etc.

## Actual result:
Due to lack of this feature, most Posts tabs are full of repetitive material.  E..g. here:
 https://www.nexusmods.com/skyrim/mods/47989/?tab=posts
there are over 200 posts, but about 80% of them are people asking the same 5 or so questions over and over and over again.

This is a common problem; any Posts tab that has more than a page or two of comments just turns into people re-re-re-asking and -answering the same stuff endlessly. Or getting angry with each other for asking again, and/or angry for others telling them to just go look in old posts - which is a completely impractical idea when there's more than a handful of them. So, it has an impact on community civility, not just on individuals' expediency.

I meant to request this feature about 3 years ago, but figured it was just some very temporary lack, and that surely it would be added in the next rev.  But here is it 2020, and still no searchable posts. So, time to make the request. :-)

**Comment by adhesivewombat** [comment]
This would be a great feature to have. 

I tried upping the page_size on the url call for the comments section and the server still only returns 10 comments when you ask for 20, 50, 100 etc. 😔 It seems some of the other url params don't have an effect either (skip_opening_post)

ex. https://www.nexusmods.com/Core/Libs/Common/Widgets/CommentContainer?RH_CommentContainer=game_id:110,object_id:47989,object_type:1,thread_id:1232547,tabbed:1,skip_opening_post:0,display_title:0,page_size:100,page:1

**Comment by Pickysaurus** [comment]
Moved to here: https://feedback.nexusmods.com/posts/92/search-in-comments-section
