### ISSUE TITLE
7 Days to Die Mod install issue

### ISSUE THREAD

**Issue by XythQ** [Nexus-Mods/web-issues#1106]
## Bug/error being reported:

Vortex will only load/install the first mod in a set of mods located in the Mods folder for the game 7 days to Die

## Steps to reproduce:
Load the creaturepacks mod for that game

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
all 5 mods would be install

## Actual result:
Only the first mod loads

**Comment by Pickysaurus** [comment]
Hi there,

This tracker is for problems with the Nexus Mods website. For help with mods, please use the comments section on the mod pages.
