### ISSUE TITLE
Being Capped at 2.0 after paying for premium. 

### ISSUE THREAD

**Issue by Dudecomeonalreadyjustcreatetheaccount** [Nexus-Mods/web-issues#1107]
Paid for premium like a dumb bastard and I'm still capped at 2.0 Mb/s been trying to get in contact with these degenerates all day to no avail... 
![20200303_101608](https://user-images.githubusercontent.com/61753900/75835694-6e84ae00-5d74-11ea-9ec2-b1456de293cb.jpg)

**Comment by Pickysaurus** [comment]
If you're still having issues, please email support@nexusmods.com however you screenshots show you downloading at 3.8MB/s (as you have two active downloads) so perhaps that is the limitation of your connection.
