### ISSUE TITLE
Site not using unique downloads counter from mod page

### ISSUE THREAD

**Issue by Maidenfan724** [Nexus-Mods/web-issues#1108]
## Bug/error being reported:
Nexus site is not using the unique downloads tracker from my mod page. Donation Points opt-in page displays lower number of unique downloads than my mod page. Site also used this lower number to determine that I was a mod author only after the lower number reached 1,000 unique downloads despite having had over 1,000 displayed on my mod page for several days.

## Steps to reproduce:
Check https://www.nexusmods.com/witcher3/mods/4456 for my mod page, and then check whatever number is displayed on the Donation Points opt-in page.

## Expected result:
I expected unique downloads to be calculated by the number displayed on my mod page.

## Actual result:
They appear to use some other metric as listed on the DP opt-in page, of which I do not know the origin.

**Comment by mrmason** [comment]
This is a known problem and will be fixed at some point - we have a feature in the pipeline that includes the fix - that number you're seeing ( the smaller one ) is downloads made via the website only, and doesn't include downloads made via mod mangers. 

The numbers on your mod page are correct, and the numbers used in the DP system monthly reports are correct.

**Comment by Maidenfan724** [comment]
Alright. Good to know. Thank you for the quick response!

**Comment by Pickysaurus** [comment]
This should now be fixed
