### ISSUE TITLE
Can't login, turned into error page

### ISSUE THREAD

**Issue by wcx19911123** [Nexus-Mods/web-issues#1109]
## Bug/error being reported:
I have login problem.

## Steps to reproduce:
1. open nexusmods.com
2. click log in
3. input username and password(and verify code sometimes)
4. click log in

## Expected result:
successfully login.

## Actual result:
go into an error page.
the url is https://users.nexusmods.com/auth/sign_in
![批注 2020-03-13 220108](https://user-images.githubusercontent.com/5677587/76628083-27b66580-6577-11ea-9a1f-7d82b6b6e911.jpg)

**Comment by verenion** [comment]
Can you confirm what browser you are using and what extensions (if any) you have installed. We've seen a similar issue to this caused by extensions that block/modify cookies.

**Comment by wcx19911123** [comment]
> Can you confirm what browser you are using and what extensions (if any) you have installed. We've seen a similar issue to this caused by extensions that block/modify cookies.

chrome for windows, version 80.0.3987.149.
list of extensions may modify cookies: adblock, checker plus for gmail, sad panda, Suspicious Site Reporter, Tampermonkey

**Comment by verenion** [comment]
I suspect it's one of those. If you could first try to login using chrome's incognito mode (Ctrl+Shift+N), which should disable all extensions you have installed, then just try disabling those extensions and attempting to login again.

**Comment by wcx19911123** [comment]
> I suspect it's one of those. If you could first try to login using chrome's incognito mode (Ctrl+Shift+N), which should disable all extensions you have installed, then just try disabling those extensions and attempting to login again.

final result is falied, but I tried these steps:
1. open chrome and go into incognito mode
2. login to nexusmods
3. turn to a page witch request me to input realname and country
4. click the homepage of nexusmods(I thought I already logged in at this time)
5. homepage shows that I didn't log in
6. try to login via homepage(sometimes need to click verify checkbox)
7. no result(I still stay at homepage without successfully login or failure alert)
8. tried step 6 about 3 times, still no any result
9. the last time I tried to login, it shows the error page again(The change you wanted was rejected.)

**Comment by Pickysaurus** [comment]
Hi there, we have a full troubleshooting guide here

https://help.nexusmods.com/article/113-troubleshooting-website-issues

If the issue persists, please contact support@nexusmods.com
