### ISSUE TITLE
Mods listed not correctly if updated

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1110]
https://www.nexusmods.com/skyrimspecialedition/mods/thisweek/?BH=0
click on Mods / All games/Skyrim Special Edition/New mods this week
filter "sort by last updated"
Mod that I updated not listed
affected:
https://www.nexusmods.com/skyrimspecialedition/mods/18553  (updated  15 March 2020 12:03AM )
https://www.nexusmods.com/skyrimspecialedition/mods/20907 (updated  14 March 2020 5:58PM )
These are samples only, same issue I notice with other updates, same is if I say "last month" or give no filter. Updates not listed well.

**Comment by verenion** [comment]
The "New mods this week" page only show new mods, not mods that have been updated. If you go to the "Updated" tab, you can see "Beyond Reach" on page 9.
