### ISSUE TITLE
Donation Points report is incorrectly all 0 in "downloads" and "mod rewards" fields

### ISSUE THREAD

**Issue by opusGlass** [Nexus-Mods/web-issues#1112]
## Bug/error being reported:
Fields for "Mod Unique Downloads" and "Mod Rewards" on monthly Donation Point reports are incorrectly 0 for all mods, retroactively for all past reports as well as the most recent report.

The other fields including "Your Ratio" and "Your Reward" are working correctly.

### Example:
![image](https://user-images.githubusercontent.com/26558324/76887693-41420080-6848-11ea-8582-7c06fd5f34ca.png)

**Comment by verenion** [comment]
I've just uploaded a fix for this. If you could confirm this is working and let me know, that would be great

**Comment by mrmason** [comment]
internal tracking [#171839664]

**Comment by opusGlass** [comment]
@verenion It's working (at least on mobile). Thanks!
