### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by Moria8** [Nexus-Mods/web-issues#1113]
## Bug/error being reported:
Try to purchase premium month and when I click on the link it tells me that I need to pick a subscription. I go back, make sure I have checked a subscription box and try again, same result.  I have tried several different times and on multiple days. It never will allow me to subscribe.

## Steps to reproduce:
1. Click on link to see premium plans
2. Check box of plan you want.
3. Clink on link to purchase plan.
4. Get error message that you have not chosen a plan.
5. Try going back to plans and checking a different plan (or same plan)
6. Same error message.

## Expected result:
The result would be to purchase a premium plan.

## Actual result:
Error message stating that I have never chosen a plan.

**Comment by Pickysaurus** [comment]
Hi Moria,

This is a known isse
