### ISSUE TITLE
Button "Slow donwload" when downloading mods on Stardew Valley does not work

### ISSUE THREAD

**Issue by DrDrawLT** [Nexus-Mods/web-issues#1114]
## Bug/error being reported:
 When I try to download a mod for this game and go to the page with a suggestion to choose the download option, the "slow donwload" button just doesn’t click, although the neighboring donat button works fine.
Also in the page code, I found the following:
`<button` id="slowDownloadButton" class="rj-btn rj-btn-secondary rj-btn-full" data-download-url="#ERROR-download-location-not-found"><span>Slow `download</span></button>`

## Steps to reproduce:
1.Go to the download menu of any file (mod) for the game Stardew Valley
2.Click on the "Slow Donwload" button

## Expected result:
Start downloading the desired file or go to the page with the file and download it from there

## Actual result:
 Nothing happened, it just doesn’t work, however the animation of the click is going on

**Comment by Pickysaurus** [comment]
Hi there,

This sounds like you have addons installed that interfere with our download page. Such as "Universal Bypass" or some other kind of script. 

Please disable these addons to use the site correctly.

**Comment by DrDrawLT** [comment]
> Hi there,
> 
> This sounds like you have addons installed that interfere with our download page. Such as "Universal Bypass" or some other kind of script.
> 
> Please disable these addons to use the site correctly.
Sorry, but I probably turned off everything that could be in the browser related to blocking such things, but the button still does not work, even in another browser, in which there are no settings, it does not work

**Comment by DrDrawLT** [comment]
Sorry, but I probably turned off everything that could be in the browser related to blocking such things, but the button still does not work, even in another browser, in which there are no settings, it does not work

**Comment by DrDrawLT** [comment]
> Hi there,
> 
> This sounds like you have addons installed that interfere with our download page. Such as "Universal Bypass" or some other kind of script.
> 
> Please disable these addons to use the site correctly.
Sorry, but it didn’t help, I turned off everything that’s possible, I even went through a browser that is not subject to any settings and it does not work, even kill
