### ISSUE TITLE
Mod pages jumping to bottom where add is playing.

### ISSUE THREAD

**Issue by AllUsernamesTakenn** [Nexus-Mods/web-issues#1117]
URL: N/A, happening with all mod pages. 
Username on the Nexus: Smexy Tempest
Bug/error being reported: Mod pages instantly jumping to bottom where add is playing when       scrolling or loading new page.
Steps to reproduce: Scroll or load a new mod page (with safari?).
Expected result: Being able to use the damn page without constantly having to scroll back up.
Actual result: Constantly jumping to the bottom where the add is playing (I hope this isn't some ploy to get us to watch the adds).

**Comment by Pickysaurus** [comment]
Hi AllUsernamesTakenn,

Can you please report this on our forums following the guide here? We need the information described there so it can be passed to our advertising provider for a resolution. 

https://help.nexusmods.com/article/100-how-to-report-bad-or-inappropriate-ads

Thanks!

**Comment by AllUsernamesTakenn** [comment]
Will do. As detailed as I could. Hope it's enough.
