### ISSUE TITLE
Deleting a bug report in the bug section breaks bugsection and doesn't remove reference to bugreport on the comment

### ISSUE THREAD

**Issue by iforgotmysocks** [Nexus-Mods/web-issues#1118]
## Bug/error being reported:
When a conversation (including replies) is moved to the bug section without hiding it in the comments and deleted afterwards, following 2 issues appear:
1. The conversation in the comment section is still linked to the removed bugreport and can't be moved again. The button will link to the general bug section instead.
2. Random bugreports not belonging to my mod start showing up.

## Steps to reproduce:
1. Create a conversation in the general comment section of a mod
2. Move it to the bug section having "include replies" checked and hide original posts unchecked
3. Delete bug
4. Try to move the conversation again

## Expected result:
The conversation should be movable to the bugsection again, if the issue there was deleted and only bug reports belonging to the mod should show up.

## Actual result:
After deletion of an issue the conversation in the comment section can no longer be moved to issues, but is still referenced to the deleted issue. Random bugreports not belonging to the mod start appearing in the bug section.

**Comment by Pickysaurus** [comment]
I have to say, trying to move the same comment to bugs twice is not expected behaviour, but I'll have a look and see if I can replicate this.

**Comment by Pickysaurus** [comment]
I am not able to replicate this, deleting the report does seem to reset the link between the report and the bug so I cannot try to move it over again. 
![image](https://user-images.githubusercontent.com/31670524/80791572-f9720100-8b89-11ea-818e-8c48e0928692.png)
