### ISSUE TITLE
Strange Doubled-Folders of the Game-Name?

### ISSUE THREAD

**Issue by H8DCarnifeX** [Nexus-Mods/web-issues#1119]
## Bug/error being reported:
I added my "Mount & Blade II: Bannerlord"-Mod: "Zweihander" under Mod-Category: Modules,
and the Folder Structure is shown like this:
All games / Mount & Blade II: Bannerlord / Mods / Mount & Blade II: Bannerlord / Modules / Zweihander

As you can see, the Name of the Game appears 2 times.

## Steps to reproduce:
- as example just visit: https://www.nexusmods.com/mountandblade2bannerlord/mods/249
- take a look at the folder structure as described above (doubled game-name)

## Expected result:
I expected this Folder Structure:
All games / Mount & Blade II: Bannerlord / Mods / Modules / Zweihander

**Comment by Pickysaurus** [comment]
@H8DCarnifeX Thanks for the report, we'll be deploying a fix for this shortly
