### ISSUE TITLE
Specify own permissions option no longer available

### ISSUE THREAD

**Issue by Zaldir** [Nexus-Mods/web-issues#112]
The "I would like to specify my own permissions in the "Permission instructions" text box below and not use the drop-down menus" option is no longer available for the new site, rendering a lot of such instructions unclear. If someone have specified their own permission instructions on the old design, these instructions are now displayed alongside the standard instructions on the new site, which may lead to contradictory instructions, and thus, confusion about what people are allowed to do with those files.

**Comment by DRSSX4756** [comment]
Was about to point this out too. 

Custom provisions, such as releasing under a license that the standard choices don't cover, should completely override anything standard, as before, not be buried under it. 

In the past, we could just pick the prefab choice that's closest to what we wanted, knowing that the custom stipulation would override them anyway in the permissions tab. Having such placeholder choices be not only visible but above our stipulation, which has been always been called "notes" but is now actually demoted to that status by looking like an afterthought, leads to Nexus seemingly imposing restrictions on redistribution that I never wanted for a few mods that I released as entirely public domain.

**Comment by iamtiz** [comment]
Assigned #152031368

**Comment by iamtiz** [comment]
Fixed
