### ISSUE TITLE
Vortex error for Bannerlord Extension

### ISSUE THREAD

**Issue by Ijustwanttoreportabugcurseyou** [Nexus-Mods/web-issues#1121]
## Bug/error being reported:
Vortex throws an error when attempted to download the extension required for it to work with Mount & Blade 2: Bannerlord.

## Steps to reproduce:
-Be me
-Open 'Games' section of Vortex
-Search for Bannerlord
-Click 'Manage' button at the center of bannerlord icon
-Click the 'download' button at the bottom right of the popup
-Recieve a 'failed to install extension, check notifications' error.
![Vortex Bannerlord 1](https://user-images.githubusercontent.com/63316181/78711734-1560ea80-78dd-11ea-9f29-fd9340a85450.png)
- A green "extension installed' notification is listed along with a red 'Download failed' notification
![Vortex Bannerlord 1 5](https://user-images.githubusercontent.com/63316181/78711740-17c34480-78dd-11ea-97df-4508d557ea77.png)
![Vortex Bannerlord 2](https://user-images.githubusercontent.com/63316181/78711746-1bef6200-78dd-11ea-81dc-a2ebbe478de3.png)
-Despite the green notification, Bannerlord remains unmanaged.

### Example:
See above

## Expected result:
The vortex bannerlord extension to be downloaded

## Actual result:
Error saying it failed to download

**Comment by Pickysaurus** [comment]
Please log into your account and try again

**Comment by Ijustwanttoreportabugcurseyou** [comment]
It's hard to cure my stupid- thanks, that did it.
