### ISSUE TITLE
Certain mods don't show up in search

### ISSUE THREAD

**Issue by Jack-0-Spades** [Nexus-Mods/web-issues#1123]
Certain mods don't show up when I search for them. I have had this issue for a long time, but did not pursue any solution as I thought it was just an issue with the search engine, but recently I have found what could be the source of the problem. I went to look at Arthmoor's profile to look at the mods he was supporting and found that many of them will not show up  "due to content you have blocked."  I believe this is the source of the problem and I am not the only one to have it.

https://www.reddit.com/r/nexusmods/comments/52sqp1/nexus_doesnt_show_all_mods/d7ofzz4/

![Capture](https://user-images.githubusercontent.com/40483800/79184876-62642580-7de3-11ea-8304-436aeb34c095.PNG)
![Capture2](https://user-images.githubusercontent.com/40483800/79184929-89225c00-7de3-11ea-9628-d9feccd40418.PNG)

**Comment by Pickysaurus** [comment]
This is not a bug. Those mods do not appear in the search because you have blocked tags they use. This is expected behaviour.

**Comment by Jack-0-Spades** [comment]
I have never blocked any tags before. I don't even know how to do that, so if tags were blocked on my account, that is the bug. Furthermore,  based on the link I posted it seems likely or at  least feasible that others have had this happen to them.
