### ISSUE TITLE
File stuck on being uploaded to servers

### ISSUE THREAD

**Issue by avianavatar** [Nexus-Mods/web-issues#1125]
**URL:** https://www.nexusmods.com/skyrimspecialedition/mods/30386?tab=files
**Username on the Nexus:** Megalorex
**Bug/error being reported:** 
There are what appears to be two identical files listed under Main Files but one of them says:
_The file is currently being uploaded to our file servers and it will be ready to be downloaded soon._
**Steps to reproduce:**
Go to the above url and find the above message in the Main Files section
**Expected result:**
I would be able to download that file (assuming it's not a duplicate that's not supposed to be there)
**Actual result:**
I can't download that file (again assuming I'm supposed to be able to and it's appearing there isn't another glitch)
**Link to the affected mod/image (if relevant):**
![nexus glitch](https://user-images.githubusercontent.com/63683960/79284411-abfd5f00-7f0e-11ea-8edb-b31b4e6b4409.png)

**Comment by Pickysaurus** [comment]
Looks like two entries got create for the same mod file. The one below is the exact same and downloads correctly. I'll remove the extra one, thanks.
