### ISSUE TITLE
Nexus Mod Manager

### ISSUE THREAD

**Issue by DarkPanzerfaust** [Nexus-Mods/web-issues#1126]
When i try to download a mod in nexus mod manager I get an error that says ''Unrecognized game mode: skyrimspecialedition'' uninstall nexus mod manager and I reinstalled it I got the same error Some help?

**Comment by Pickysaurus** [comment]
Hi there,

I'm afraid we no longer support Nexus Mod Manager, in favour of our new mod manager: [Vortex](https://www.nexusmods.com/about/vortex/?).

If you need support with NMM, you can visit the community driven GitHub page here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

I would suggest you first ensure you have the latest version.

Hope this helps.
