### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by mannotbad** [Nexus-Mods/web-issues#1128]
## Bug/error being reported:

I tryed Downloading Mafia II Friends For Life Mod and once it reachs to 1gb it tells netwrok error tryed couple of times from couple of browsers and the problem still happens
## Steps to reproduce:
upload it to a better server Google Drive For example

1. Make a google account 
2. go to drive.google.com
3. and upload lul
## Expected result:

to get it downloaded
## Actual result:

Failed Network Error
https://www.nexusmods.com/mafia2/mods/115

**Comment by Pickysaurus** [comment]
Are you PigPog37 from the Discord server?

You need to provide the information in this article so we can help you: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

The article also directs you to the appropriate forum to post your feedback.
