### ISSUE TITLE
!!!Game breaking!!! bug Freshlyground xb1

### ISSUE THREAD

**Issue by Iadite1399** [Nexus-Mods/web-issues#1129]
## Bug/error being reported:
Game breaking bug with the xbox version of the !!!!==>(freshlyground)<==!!!! mod. Instant crash when npcs use grindstone mill. Potential it could corrupt game saves not sure on that though if it's just a fluk with my game. It happened twice for me, though. So beware when testing. Or all your saves are gone. I mean !!ALL!!! not just the one your playing. Vanilla and modded. Kiss all your hours of saving tamrial goodbye.

## Steps to reproduce:
I received the letter from yarl 'falkreath' at hiliarken hall manner (my modded start with live another life mod) courier used mill. instant crash. Corrupted two different saves trying to fix my load order to be safe it wasn't me. Its the mod. Trust me.

### Example:
1. Hiearkin hall mill stone
2. N/a
3. N/A
 (*not going to corrupt more save files on this part. sorry)
-->

## Expected result:
Don't know what I expect. Was pretty jarring losing my 200+ hour save to full save data corruption. When it happened i actually started crying. Maybe you could make npcs unable to touch the things. Stop it at the source. Don't want every 20 something incell to start cry on yuh like i did. Least till a better solution is found.

## Actual result:
A dead save file, Tears, and a courier using my grain wheel. (Hashtag)RIPLidiot

**Comment by Pickysaurus** [comment]
This GitHub page is for issues with the Nexus Mods website. I think you reported it in the wrong place? You should probably report this to the author of the mod.

**Comment by Iadite1399** [comment]
Oh.. well do you know how I can do that.

**Comment by Iadite1399** [comment]
He didn't have a open comment board

**Comment by Iadite1399** [comment]
Sorry for the mix up i Don't do this forum stuff very often
