### ISSUE TITLE
Slower than molasses load times (Skyrim SE Nexus)

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1130]
Load times for Skyrim SE Nexus are slower than molasses

1.  Navigate to Skyrim SE Nexus.
2. Watch as the page takes upwards of 1 minute to load fully...

Instant loading of the Skyrim SE Nexus homepage.

Skyrim SE Nexus homepage loading at a snail's pace...

**Comment by Pickysaurus** [comment]
What does the load time say in the site footer? For me it's this:
> Page served in
> 0.301s [rd05]

There looks to be some intermittent, temporary problems with images but that's probably due to site traffic more than anything.

**Comment by scjohnson1981** [comment]
The issue is random/intermittent with the entire page struggling to load at times...

**Comment by mrmason** [comment]
There are no reported problems overnight, no slowness on the APM monitor or any alerts with any services, so I'm going to close this.

@scjohnson1981 - if you see this, or anything similar again then please can you provide some more information, such as what @Pickysaurus has asked for ( which server your request has been rendered from ) - and also, if possible, any debugging information from your browser on what is happening in the network tab - also your location ( vague geographic ) and what page/s you're trying to load that are taking time.

I'm afraid that without at least some of this information there is almost nothing for us to investigate.
