### ISSUE TITLE
The mods that no longer work

### ISSUE THREAD

**Issue by poppajq** [Nexus-Mods/web-issues#1131]
## Bug/error being reported:
I am no longer able to use certain mods.

## Actual result:

Hello

I have a problem I am trying to track down that perhaps you folks can please help me with. I had to upgrade my hard drive due to lack of space and now, I am no longer able to use certain mods. I reloaded my Fallout 4 w DLC mod pack, disabled and re-enabled them and, reloaded them (three times) to no avail. I am still able to use mods like  OCDecorator, Homemaker, Easy Homebuilder, DD standalone all in one, Working Double Beds and video of the wasteland

The mods that no longer work are: Build your own pool, invisible furniture, more invisible furniture, Rebuild - Modular Sanctuary Pre-War and Post, Settlement Activity Markers, Snap and build, Snappy house kit, Simple modular homes and Workshop Rearranged. Not even a menu shows in workshop. if it has one. The modders that responded said their mods are fine (of course) so I am thinking the reasons these mods are having issues: 1. A Bethesda update is blocking them. 2. The DLC mod pack is blocking them 3. A F4se update is not enabling them 4. The Vortex program is having issues with them. 5, The non working mods lack a script or program the working mods have.

Could someone there please check to see if vortex is the issue? I am not a modder so, I  am not sure what to look for.  If my hair wasn't buzz cut, I'd be pulling it out by now.

thanx

Poppajq

**Comment by Pickysaurus** [comment]
Hi there,

This tracker is for posting issues with the Nexus Mods website. For modding support I recommend creating a post on our forums or our Discord server:

https://forums.nexusmods.com/index.php?c=3485,3500
https://discord.gg/nexusmods
