### ISSUE TITLE
Scroll bar request

### ISSUE THREAD

**Issue by poppajq** [Nexus-Mods/web-issues#1132]
On the mod and plug in pages, could you please widen the scroll bars or at least add a different to it, add  arrows on the scroll bar? It is hard to tell where it is sometimes.

Also could you please provide a feature that allows you to disable/enable groups or all mods/plug-ins for trouble shooting?

**Comment by Pickysaurus** [comment]
Hi there,

If you're referring to Vortex, please add your feedback here: https://github.com/Nexus-Mods/Vortex

Or send it through the application from the "Send feedback" option in the top right menu.
