### ISSUE TITLE
Download speed error

### ISSUE THREAD

**Issue by tubirus** [Nexus-Mods/web-issues#1133]
## Actual result: The download spead doesn't even pass 50 KB/s

![image](https://user-images.githubusercontent.com/64620738/80771671-85ecd700-8b2a-11ea-97b6-709be15723f5.png)

**Comment by Pickysaurus** [comment]
Hi there,

It looks like you may have a bad connection to our servers. 

Please can you consult this article, it includes the if we need to troubleshoot and where you should post it.

https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
