### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1134]
## Bug/error being reported:
Downloads are broken across all Nexus servers.  Manual downloads result in 0 KB downloads...
## Steps to reproduce:

1. Click any mod file to download.
2. Observe the "Server busy/unavailable" message spam in one's mod manager.  Manual downloads show 0 KB file sizes.

## Expected result:
File downloads without issue.

## Actual result:
Server busy/unavailable errors/0 KB manual downloaded files.

**Comment by Madnessing** [comment]
![Capture](https://user-images.githubusercontent.com/64676104/80855169-a3d23e80-8bf3-11ea-9c58-f430b3f53a76.PNG)
Hoping that will make it easier for you.

**Comment by scjohnson1981** [comment]
What exactly is that?  I'm far from a coding expert...

**Comment by gameLvr85** [comment]
Can't download anything large file, sse mods, if file is in KBs, its downloading just fine but large files like 2K texture files that maybe around 40~70MB+ are broken.
Fix it please.

**Comment by Madnessing** [comment]
![34](https://user-images.githubusercontent.com/64676104/81004292-064c5a00-8e01-11ea-93c2-3e86f47ab83d.JPG)
That is the Error console from the failed download page. If you are on a page that wont give you the download, after you try to download your mod press F12 and choose console you will see what the errors are.

**Comment by Noth211** [comment]
Servermessage: API currently not reachable, please try again later.
URL: https://api.nexusmods.com/v1/games/{gameId}/mods/{modId}

**Comment by Pickysaurus** [comment]
To report download issues, please follow the process here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

@Madnessing your issue appears to be caused by something in your setup blocking the required JavaScript
