### ISSUE TITLE
Misclicking Anywhere off the 'report a bug' popup closes popup with all entered data lost

### ISSUE THREAD

**Issue by OrnoCav** [Nexus-Mods/web-issues#1135]
## Bug/error being reported:
title says it all, but to reiterate, Mis-clicking Anywhere off the 'report a bug' popup closes popup with all entered data lost, no confirmation, just gone.

## Steps to reproduce:
1) click on 'report a bug' for any mod
2) popup window appears
3) click anywhere BUT on said popup window, popup goes away with complete loss of all information entered

## Expected result:
mis-clicking should NOT close a window that has had information entered. at the minimum, a confirmation window should confirm cancelling the report before closing the popup.

## Actual result:
no confirmation, just gone.

## Desired Result:
either confirm the off-popup click to close the popup, or make the bug report popup an entirely self sufficient page of its own

**Comment by Pickysaurus** [comment]
Sorry about this. It's something we're aware of and happens with all pop-up boxes on the site. It's been noted as something we want to fix in our new design (if it's not possible to fix it before then).
