### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by TagasZX** [Nexus-Mods/web-issues#1136]
Greetings. I can’t absolutely download anything from the site, because the speed is as low as possible! I have weak internet (max. 400 kb / s) and I did not buy premium because I do not need it, but without premium, the speed should be a maximum of 2 mb / s, that is, it should reach 400 kb / s, but less and less every day. Now it has generally fallen to 20 kb / s !! Please correct! And yes, everything works fine on other sites, only yours had it before and everything was fine on yours (a month ago, at least). Files weigh a lot, but the speed is minimal! And today, by the way, I could not connect to your site, your host did not allow it. But now everything is fine.
P. s. I write through Google, because Russian.
![Снимок](https://user-images.githubusercontent.com/49083928/81278956-2c445980-90a2-11ea-929c-e6787cab99ab.PNG)

**Comment by mrmason** [comment]
Hello,

Please can you let us know the results of running these commands from command line ?

```
ping supporter-files.nexus-cdn.com

tracert supporter-files.nexus-cdn.com
```

Also, can you try downloading these two files and let me know if they're both slow ?

http://amsterdam.nexus-cdn.com/100M
http://prague.nexus-cdn.com/100M

**Comment by TagasZX** [comment]
Everything is ready. Conducted tests downloading two files.
1.100M
      maximum speed starts from 3 mb / s and decreases to 200-350 kb / s, which is exactly what you need. (2 more tests are almost the same)
2.100M
      maximum speed starts from 1.2 mb / s and decreases to a minimum and slowly rises to normal. And so the speed is not stable, it constantly jumps from 50 kb / s (the very first test the maximum speed is 30 kb / s, the latter after a while keeps at 200 kb / s)
Command line screenshots:
![Снимок3](https://user-images.githubusercontent.com/49083928/81281699-e6899000-90a5-11ea-8d29-da24b65687e1.PNG)
![Снимок1](https://user-images.githubusercontent.com/49083928/81281705-e9848080-90a5-11ea-83d0-7a4424d02557.PNG)
![Снимок2](https://user-images.githubusercontent.com/49083928/81281761-f86b3300-90a5-11ea-9fec-9dc655ea2531.PNG)

**Comment by TagasZX** [comment]
Nick is the same as here - TagasZX.

**Comment by TagasZX** [comment]
Today, the speed does not even reach 20 kb / s. In my opinion, tomorrow there will generally be a server error ... And as I understand it, I don’t have one such problem.
![Снимок](https://user-images.githubusercontent.com/49083928/81363568-60b22700-912f-11ea-9b6c-b04abd037d48.PNG)

**Comment by TagasZX** [comment]
I don’t know what happened, but the speed became normal. Thanks, if that.
