### ISSUE TITLE
[Suggestion] Get permalink to posts

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1138]
Similarly to how you can get a permalink to a post on github or reddit, it'd be nice if it was possible to get permalinks to posts on Nexus. The feature is already partially implemented with the "jump_to_comment" URL parameter. It'd be nice to have a button to get these links, for now you only get them as part of notifications.

![2020-05-11_11-34-29](https://user-images.githubusercontent.com/12874678/81546929-63a15780-937b-11ea-9c12-338d019f7587.png)

**Comment by Pickysaurus** [comment]
You can right-click on the date shown on the forum to link directly to that post in the forum. This isn't possible on the site and won't be until we rebuild the comments system.
