### ISSUE TITLE
Category page sorted by Endorsements does not show all mods

### ISSUE THREAD

**Issue by opusGlass** [Nexus-Mods/web-issues#114]
If I go to the Creature category sorted by Endorsements: https://rd.nexusmods.com/skyrimspecialedition/mods/categories/83/?BH=2

My mod Splendor should be in the 8th spot. ( https://rd.nexusmods.com/skyrimspecialedition/mods/9670/? )

Ctrl+F searching for it shows a result, but it can't show me where that result is. Seems to be invisible...

The old nexus shows it correctly: https://www.nexusmods.com/skyrimspecialedition/mods/searchresults/?src_cat=83

**Comment by verenion** [comment]
Assigned PT#151632683

**Comment by opusGlass** [comment]
Update: It was suggested to me that this might be related to tags. Splendor did not have any accepted or rejected tags at all; but two people had recommended the lore-friendly tag. As soon as I accepted this tag, the mod became visible again.

**Comment by mrmason** [comment]
This should be fixed now - please let us know.
