### ISSUE TITLE
other users report they can't see my supporter images

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1140]
Now I got the 2nd comment of a registered user, that he cannot see my supporter images, i.e. https://www.nexusmods.com/skyrimspecialedition/supporterimages/1909
read
https://forums.nexusmods.com/index.php?/topic/7888548-midwood-isle/page-50 posting  #497 
another user told me, he had to register first althought he is registered already.
I personal don't habe this issue, but sounds for me as there is something not correct working

**Comment by BigBizkit** [comment]
The user stating that they cannot see your supporter images is a regular user i.e. not a supporter. The supporter image share can only be viewed and uploaded to by supporter/premium members. I hope that clears things up for you.
