### ISSUE TITLE
can't signup/register

### ISSUE THREAD

**Issue by derbenx** [Nexus-Mods/web-issues#1141]
URL: https://users.nexusmods.com/register
Bug/error being reported: won't accept my email address
Steps to reproduce: sign up with email address; *****@writeme.com
Expected result: signup just works
Actual result: ERROR Email address was not valid.

*email address censored for forum.
**email address works.

**Comment by Pickysaurus** [comment]
Hi derbenx, 

We do not allow email addresses from providers that are known to be used by spammers. Please register with an alternate email address. You can see writeme.com and it's variations on the master list here: https://github.com/FGRibreau/mailchecker/blob/v3.3.3/list.txt
