### ISSUE TITLE
Slower than molasses downloads/site loading

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1142]
Downloads/site loading times are slower than molasses...

## Steps to reproduce:
<!--
1. Navigate to Skyrim SE Nexus
2. Watch as the site takes an eternity to load...

Near-instant loading of the Nexus sites/fast download speeds...

Slower than molasses downloads/site loading...

**Comment by Pickysaurus** [comment]
If you wish to report a download issue, we'll need you to make a forum thread including all the information requested here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

Without this information we cannot help you troubleshoot. 

Thanks!
