### ISSUE TITLE
Post breaks the whole page

### ISSUE THREAD

**Issue by light6486** [Nexus-Mods/web-issues#1143]
## Bug/error being reported:
Post breaks the whole page
https://i.imgur.com/CUYXlUm.png

## Steps to reproduce:
1. I've posted here. https://www.nexusmods.com/witcher3/mods/3522?tab=posts
2. Then I edited my post on forum to be a reply to other post.
https://forums.nexusmods.com/index.php?/topic/7387081-witcher-3-enhanced-edition/page-629#entry80461963

looks like this:
[quote name="denexusar" post="80461963" timestamp="1588630799"]
[i]In response to post [url=?showtopic=7387081&p=80460848]#80460848[/url]. [/i]

[spoiler]
[quote][b]Undershaft wrote: [/b] [i]I found the quest "Wandering in the Dark" to be a colossal pain in the ass -- specifically, the part with the portal hounds in the icestorm.
Only managed to get through this part on my second attempt at the quest because I knew it was coming (having failed it countless times on my first run and reloaded a savegame before entering the cave) and had brought a sackload of Dragon's Dream bombs to blow the dogs to smithereens as soon as they spawned.

Not a good experience. Usually, I have no problem getting my ass kicked in combat, but this quest is too long and too early in the game for it to end in an almost unwinnable encounter (if not fully prepared for this specific situation) you can't turn back from.[/i]
[/quote]
[/spoiler]
You don't need to do it early in the game, although there is some sweet loot for early game (like dimeritium bomb) and you unlock keira's shop with the sweet sweet rime, corrosive and flamable oils. But, anyway, if you want to get past the frost-ghouls part, there are 3 ways of cheesing it:
1) get the dimeritium bomb recipe, it's a hidden cave marked by an octopus connected (through an underwater tunnel) with the "old elven port" part. If you took some glowing ore/dimeritium ore (you get that eary game from dismantling swords with yellow backgroud), you can craft dimeritium bombs. Throw the dimeritium bomb at the portal and it will close.
2) activate quen inside keiras bubble, then you can walk out freely, ghouls are only a problem if you are stuck inside a small place with reduced vision of your surroundings
3) 3 basic grapeshots do the work (don't get cluster skill, it sucks early game, get riving blasts instead). Aim to the front of the portal and wait until you can catch 3 ghouls with the blast. 3 bombs will kill 3 ghouls, the rest will be a lot easier, even easier if you apply (2).

Also I'd suggest enhanced falka's blood and enhanced swallow. Ghouls are a lot less dangerous if they stagger some of the times they attempt to hit you. You can stop the regeneration with axii, but I prefer saving the vigor for quen.

So yes, you need to know what's coming to prepare properly, but even in worst case scenario you can just quen and run around freely smacking frost-ghouls in the bum.
[/quote]

and
my reply here.

## Expected result:
Obvious.

## Actual result:
https://i.imgur.com/CUYXlUm.png

**Comment by Pickysaurus** [comment]
Apologies for the delay, this looks to have been fixed.
