### ISSUE TITLE
05/17/20 Users posting images break their profiles and one can't sign in

### ISSUE THREAD

**Issue by FastBlackCat** [Nexus-Mods/web-issues#1144]
This user, who is a friend, posted this sticky on his image upload on F4:  "This is Marthos, it looks like my account has been hacked or somethings gone rather tits up. After I posted these images last night I tried to reply to a pm from 0bm only to be told I don't have permission to do that.

My username has changed, my premium membership is gone, the main forums just give me a message stating that I'm not allowed to visit this community and my profile states that I joined in 1970 when I was just 2 years old.

I've tried contacting admin but have not received a reply, if someone that knows me would report this post and an admin could click on my Marthos link below the picture they'll see that it takes them to my botched profile page."  The link to the image upload is here:  https://www.nexusmods.com/fallout4/images/177772

Before I saw this just now, I visited another friend's image posting (his user name is LesJones) early this morning.  While I was looking at the set, the page "jumped", initially said "I didn't have permission to view this" then got a message "this user's account was deleted".  I went o.O and went to his profile and now his usename is showing as the title of his image upload!

This probably has happened to other folks, too.

**Comment by Pickysaurus** [comment]
We are aware of this issue and have temporarily shut off image uploads while we investigate. 
https://forums.nexusmods.com/index.php?/topic/8722948-image-uploads-temporarily-unavailable/

**Comment by Pickysaurus** [comment]
@FastBlackCat if you're speaking with Marthos, can you please get them to contact me. Either support@nexusmods.com or through our Discord? I need to ask them some questions to restore the account properly.

**Comment by FastBlackCat** [comment]
Thanks, just sent a message to him just in case he hasn't already contacted
you. 👍
