### ISSUE TITLE
Send Donation Point feature is broken 

### ISSUE THREAD

**Issue by Painter2099** [Nexus-Mods/web-issues#1145]
## Bug/error being reported:
Send Donation Point to another user feature is not functioning, as "search button" doesnt work, thus target user can't be selected

**Comment by Pickysaurus** [comment]
Hi Painter,

We're aware of this issue and working on a fix. 

Thanks for the report : )

**Comment by Pickysaurus** [comment]
Can you please try now and let us know if it's still an issue for you? 

You may need to log out and back in for it to work as expected.

**Comment by Painter2099** [comment]
It now says "user XXX cannot be added", regardless of username

**Comment by Pickysaurus** [comment]
Hmm, strange. Did you try logging out and back in?

**Comment by Pickysaurus** [comment]
After checking with the devs. The message is either caused by the username being spelt incorrectly or that user is not opted into the DP system. Please try copying it from below, ensuring when you paste it there are no spaces before or after the username
`ErosDkAl`

**Comment by Painter2099** [comment]
Logged out and looged in, used the username you provided, still the same

https://imgur.com/a/YUDfrmx

**Comment by Pickysaurus** [comment]
Just for the sake of argument, can you see if it lets you add me (Pickysaurus)?

**Comment by Painter2099** [comment]
No, still the same issue

**Comment by Pickysaurus** [comment]
Thanks for the update. Our team believe they've found the issue now and are working on a fix. Turns out it was a problem with the permissions - which I didn't have because I'm an admin.

**Comment by Pickysaurus** [comment]
Can you please try one more time :)
