### ISSUE TITLE
Quotes in mod description not removed when used in meta og:description

### ISSUE THREAD

**Issue by isNaN** [Nexus-Mods/web-issues#1146]
## Bug/error being reported:
The mod description field when uploading a new mod allows quotes. This description field is used directly in the meta og:description element in the header, without removing the quotes.

## Steps to reproduce:
1: Create a new mod where you have quotes in the mod description field.,
2: Look at the resulting html, the quotes are not filtered out, prematurely ending the content attribute.

## Expected result:
Quotes being filtered out when used in a html attribute so all the text remains for engines using the og:description field, usually for presenting web snippets for links.

## Actual result:
Quotes weren't filtered out, the attribute prematurely ends, engines like discord/facebook whomever uses the og:description for making interactive snippets to webpages miss out on description text.

**Comment by Pickysaurus** [comment]
Thanks for the report!

**Comment by Pickysaurus** [comment]
A fix will be pushed out for this soon.
