### ISSUE TITLE
Using ‘ in a message and then sending turns it into an â (safari/iPhone)

### ISSUE THREAD

**Issue by i0brendan0** [Nexus-Mods/web-issues#1148]
## Bug/error being reported:

I sometimes use my phone to reply to messages and whenever I use ‘ either deliberately or by autocorrect, it will change it to â when the message is sent. I am on an iPhone so this might make a difference. 

## Steps to reproduce:

1. Go on safari (or an iPhone might be enough)
2. Send a message with a ‘
3. Save message
4. See â

## Expected result:

For a ‘ to be in place of where ‘ was used. 

## Actual result:

‘ turns into â when the message is sent.

**Comment by Pickysaurus** [comment]
Seems like your iPhone is using a "smart quote" which is not a supported character in the comments section. This is something we'll look to change at some point, but for now I believe you can turn this off in your keyboard settings.
