### ISSUE TITLE
Allow to search by last updated date, not orignal upload date

### ISSUE THREAD

**Issue by gamax92** [Nexus-Mods/web-issues#1149]
When you select a time range to search by say, 30 days or 1 year or a custom range, the search seems to only return mods that were initially uploaded with that time range. If there's any mods that were uploaded 10 years ago but have been recently updated, they won't show up in my results if I restrict things to the past 30 days. My only option seems to leave the time range to 'All time' and then sift through all the mod dates, seeing if they're updated or not.

I would like a way to restrict returned mods from search based on their 'Last Update' time rather than their 'Uploaded' time.

**Comment by Greg-Nexus** [comment]
Moved to our Feedback page: https://feedback.nexusmods.com/posts/27/search-by-last-updated-date-not-orignal-upload-date
