### ISSUE TITLE
Image crop preview displays image URL instead of picture preview

### ISSUE THREAD

**Issue by literallybyronic** [Nexus-Mods/web-issues#115]
Trying to adjust my banner to deal with the new banner dimensions, going to the mod page>manage>media, it shows the banner, go to crop, the crop window opens but instead of the picture being displayed it only shows a staticdelivery url above the "crop & save" button.

**Comment by verenion** [comment]
Assigned PT#151632704

**Comment by Rrrafau** [comment]
@literallybyronic can you point us to the mod you are having issues with.

**Comment by mrmason** [comment]
I cannot replicate this with any of the mods I've tried. It's possible this was a temporary problem.

If you can let us know the exact mod you're seeing this with then we can re-open the case.
