### ISSUE TITLE
Comments not display Thai font

### ISSUE THREAD

**Issue by artdekdok** [Nexus-Mods/web-issues#1150]
## Bug/error being reported:
Comments in posts tab not display Thai font.

## Steps to reproduce:
Check https://www.nexusmods.com/desperados3/mods/1/?tab=posts for my mod page and add comment in Thai.

## Expected result:
I expected Thai font would be display correctly in comments

## Actual result:
Thai font in comment displays as ?

## Image :
![image](https://i.imgur.com/HF9CbJg.jpg)

**Comment by Pickysaurus** [comment]
Our forum does not currently support non-Latin characters so it's not possible to post in Thai at the moment. We'll hopefully be able to fix this when we replace the commenting system.
