### ISSUE TITLE
The Leviathan mission itself is fine, but after that the game breaks

### ISSUE THREAD

**Issue by ijy10152** [Nexus-Mods/web-issues#1151]
## Bug/error being reported:
 After I finish the final Leviathan mission, instead of talking to Hackett I just appear in the comm room and If you look into the war hub it's literally just outer space. You can see the outline of the next door, but everything else is space. 

## Steps to reproduce:
 step 1 install these mods: ME3Recalibrated, SP Controller Support, Spectre Expansion, Expanded Galaxy, The Happy Ending, Extended Conversation with Anderson, ALOT of Textures.

## Expected result:
After the Leviathan mission ends I'm supposed to have a briefing with Hacket. 

## Actual result:

The mission ends and I just spawn in the comm room and there are no crew members on the ship. Also it is possible to fall through the ship.

**Comment by Pickysaurus** [comment]
This is not related to the Nexus Mods website
