### ISSUE TITLE
Comment thread locked by moderation accidentally re-opened via permissions tab

### ISSUE THREAD

**Issue by toddhowardprivatemods** [Nexus-Mods/web-issues#1152]
## Bug/error being reported:
I have accidentally discovered a bug where if a mod author were to edit the mod page's permissions, the comment thread would be re-opened despite being locked by Nexus moderators. 

## Steps to reproduce:
1. Lock comment thread
2. Edit file permissions tab and save
3. Comment thread unlocked
-->

## Expected result:
Comment thread should remained locked

## Actual result:
Comment thread should unlocked

**Comment by Pickysaurus** [comment]
We've not been able to replicate this issue.
