### ISSUE TITLE
Duplicate comments: "couldn't find your comments siblings"

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1154]
## Bug/error being reported:
From time to time, answers to comments fail to appear with the following message: "There was an error fetching your comment's siblings. Comment not found"

1. The error appears after trying to answer a comment:
![firefox_2020-06-09_10-04-37](https://user-images.githubusercontent.com/12874678/84122902-67d39a00-aa39-11ea-8a3c-a8b787ad95a6.png)
2. If I reload the posts section, my comment still doesn't appear. However, if I look in the forums page, my comment is in fact there, only with no reference to the comment it's answering.
![firefox_2020-06-09_10-04-46](https://user-images.githubusercontent.com/12874678/84122906-6904c700-aa39-11ea-9d66-8d1148c935a3.png)
3. If I try to post the same (or supposedly a different) reply again, the 2 appear.
![firefox_2020-06-09_10-05-13](https://user-images.githubusercontent.com/12874678/84122913-6a35f400-aa39-11ea-933f-c5bff4676edf.png)
4. Even though the first one still doesn't reference the comment it's answering.
![firefox_2020-06-09_10-05-26](https://user-images.githubusercontent.com/12874678/84122904-6904c700-aa39-11ea-8c87-fd9c56a06dde.png)

## Steps to reproduce:
I've no idea. I know it happens sometimes, but I can't figure out how to reproduce it.

**Comment by Pickysaurus** [comment]
This is a known, intermittent bug which seems to occur when you have a lot of "enhanced privacy" settings and addons. I have not been able to reproduce it myself.

**Comment by starkgate** [comment]
I only have uBlock Origin and Firefox's default settings.

**Comment by Pickysaurus** [comment]
Best guess is this happens when the site is under heavy load, or there's a connection issue between the browser and the server.
