### ISSUE TITLE
Rate Limit exceeded messages at after arbitrary number of downloads and for arbitrary times of lockout

### ISSUE THREAD

**Issue by bradhenderson** [Nexus-Mods/web-issues#1155]
## Bug/error being reported:
Vortex version 1.2.16 updated last night and immediately gave me a rate limit message. happened again 24 hrs later after a few downloads.

Rate Limiter on vortex premium appears after only a couple of downloads since last night at update time.

## Steps to reproduce:
1. After I launch vortex and ensure that I'm logged in as myself "Faun". 
2. I use a Vortex Mod to navigate to a Nexus webpage for a mod to retrieve. 
3. I use the Mod Manager DL, or the Manual DL so the file downloads. 
4. On the next Mod download, it throws up the rate limiter message and blocks me for an arbitrary time, in the last case about 10 minutes.

## Expected result:
As a premium member, I'm not expecting rate-limiting for my account.

## Actual result:
Rate limiting occurs for random and arbitrary times after one or a few downloads.

**Comment by Pickysaurus** [comment]
Hi there,

You can read more details about rate limiting here: https://help.nexusmods.com/article/105-i-have-reached-a-daily-or-hourly-limit-api-requests-have-been-consumed-rate-limit-exceeded-what-does-this-mean

**Comment by bradhenderson** [comment]
I read those articles, yet I also noticed the calls were disappearing faster in this new version than before. Using Mod Organizer 2 I can see the calls left, and fewer calls are made in MO2. 

I've removed Vortex again in favor of MO2 until resolved. just because I'm a premium user I shouldn't have more server calls be used for the same activities.
