### ISSUE TITLE
Issue Downloading Up to Date Version of Mods

### ISSUE THREAD

**Issue by AngriestBird** [Nexus-Mods/web-issues#1156]
## Bug/error being reported:
Every time I  go to download mods of any kind the download is always an older version. I.e. I download a version 2.0 and it downloads as version 1.0

I have tried with multiple games such as Bannerlord and Fallout 4

## Steps to reproduce:
1. Click manual on any mod
2. Downloads 
3. Tries to install
4. Files remain unchanged

## Expected result:
The new version of the mod from the servers.

## Actual result:
Received older version of mod so I can't update it.

**Comment by Pickysaurus** [comment]
Is this still happening for you? I can replicate it and we've had no other reports about it.

**Comment by AngriestBird** [comment]
Its no longer happening anymore. Thank you tho for looking into it :) My download bugged out for whatever reason.
