### ISSUE TITLE
Stadew Valley Missing Category

### ISSUE THREAD

**Issue by GoatUnicorn** [Nexus-Mods/web-issues#1157]
## Bug/error being reported:
When refining by category in Stardew Valley, the 'New Characters' category is missing. I noticed this when browsing new and saw said category, which I thought was a new category, but it turned out that the oldest mod in the category was from July 28th 2019. I decided to fiddle with the URL at this point, and it turned out there were 26 categories when using the URL even though only 24 is displayed using the refine by category feature, through the URL category 1 turned out to be no category filtering, so there's 25 categories in total, incidentally category 24 is the missing 'New Characters' category.

As you can see in the image below, even though there indeed is a 'New Characters' section, it is not displayed between 'Modding Tools' and 'Pets / Horses' as it should've been. You can also see there's 3 pages, so there's plenty of mods in this category which is hard to find due the bug. I've also included the URL in the image so you can see that category 24 is 'New Characters'.
![NewCharactersMissingCategory](https://user-images.githubusercontent.com/67080227/84963464-c10e8e00-b109-11ea-8d41-df58ba8cd136.PNG)

## Steps to reproduce:
To reproduce the bug you need to either,
1. Go to the Stardew Valley section ( https://www.nexusmods.com/stardewvalley )
2. Sort by new today, where there'll hopefully be a 'New Characters' mod
3. Click on the orange texted 'New Characters' under the name of the mod, at this point you'll be taken to ( https://www.nexusmods.com/stardewvalley/mods/categories/24/ ) where you can now see the missing category

Alternatively, if there's no new mods categorized 'New Characters'
1. Paste this URL > ( https://www.nexusmods.com/stardewvalley/mods/categories/24/ ) which is the missing category 

## Expected result:
I was expecting to be able to sort by all 25 categories.

## Actual result:
All but one category (New Characters) is shown.

**Comment by Pickysaurus** [comment]
This seems to be because the "New Characters" category is nested inside another category. It could be moved to the top level, but I feel having both "Characters" and "New Characters" on the top level is confusing. 

Alternatively I can merge the two categories together.
