### ISSUE TITLE
Media loader not working properly. Images displaying on incorrect order.

### ISSUE THREAD

**Issue by LeyendaV** [Nexus-Mods/web-issues#1159]
## Bug/error being reported:
When loading images for a new/existing mod on the Media page, the elements won't save on the correct order after being moved and rearranged. 
Sometimes they stick to some random order and can't me changed. Sometimes it the order will change every time you move an image, but will never stay as you listed them.
Also, which images are affected seems to be random as well.

## Steps to reproduce:
Simply upload a bunch of images to the Media page of a mod and try to arrange them in any particular order. Save and see the results. 
Doesn't seem to happen every single time, so I'm not 100% sure of the actual steps.

### Example:
1. Attempt to arrange images in a certain order: [https://i.imgur.com/3UoloPw.png](https://i.imgur.com/3UoloPw.png)
2. Result after saving: [https://i.imgur.com/KClBbh0.png](https://i.imgur.com/KClBbh0.png)

## Expected result:
Having your images saved on the same order you put them.

## Actual result:
Images randomly changing places.

**Comment by VVL99** [comment]
https://jpegshare.net/images/d6/20/d620ef5da4bcf0d678ad592904a18427.png

**Comment by VVL99** [comment]
There has been an error with this file

**Comment by Pickysaurus** [comment]
This is related to #1095 so I will continue to monitor this issue from the older issue.
