### ISSUE TITLE
Mod details don't allow multingual mods

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#116]
The 'mod language' field is now required:
> ![error message](https://user-images.githubusercontent.com/230581/31095429-ce8e78cc-a786-11e7-9984-6e7d9ce31c7e.png)

...but there's no option for multilingual mods. For example: Stardew Valley mods can bundle multiple translations, and the ones matching the current game language will be used in-game. With the old design those simply left the language blank, which is no longer allowed.

I suggest adding two options:

option | meaning
------ | -------
_Multilingual_ | The mod supports multiple languages.
_No text_ | The mod has no text, so it's language-agnostic.

**Comment by verenion** [comment]
Assigned PT#151632726

**Comment by mrmason** [comment]
This should be fixed.

**Comment by Pathoschild** [comment]
(More specifically, the field is no longer required. There's still no way to categorise multilingual mods, but it now matches the old behaviour.)
