### ISSUE TITLE
site preferences mot working at all

### ISSUE THREAD

**Issue by Dieonyx** [Nexus-Mods/web-issues#1160]
## Bug/error being reported:
when I click on the site preferences I get an error 

Error
You are not allowed to access this area!

I don't know why. I know some options are locked behind premium but why would I not be allowed in at all?

## Steps to reproduce:
1. Click on the user icon in the top right corner.

2. Click site preferences

I would like to add as well I am not doing anything special to get this error. as far as I can tell i should be able to access preferences that's why I am submitting it as a bug.

**Comment by Pickysaurus** [comment]
Please email support@nexusmods.com from the email address linked to your account. This happens when a user didn't validate their email address when they first registered on the site. It should be fairly quick to fix :)
