### ISSUE TITLE
Almost endless loop when signing in

### ISSUE THREAD

**Issue by LRN** [Nexus-Mods/web-issues#1161]
## Bug/error being reported:
When signing in, the sign-in page constantly reloads without actually signing me in.

## Steps to reproduce:
1. Go to sign-in page for nexusmods.com
2. Enter your credentials
3. Press the button
4. The page will reload, showing reCAPTCHA (this _always_ happens)
5. Solve reCAPTCHA (until the green checkmark is shown)
6. Enter your credentials (again)
7. Press the button (again)
8. The page will reload, showing reCAPTCHA (again)
9. Goto 5

## Expected result:
Website should allow signing in with correct credentials. Without CAPTCHA or anything. At the very least, it should only require CAPTCHA to be completed exactly once.

## Actual result:
Just spent 15 minutes trying to sign in over and over again. Eventually the step 8 changed and signed me in instead of reloading the page, but it took a long time and multiple exit node changes.

Using TorBrowser 9.0.9

P.S. reCAPTCHA is extremely bad, particularly because it discriminates against Tor users (by refusing correct answers multiple times, or by refusing to show the challenge outright). But this issue is not about that (bad CAPTCHA just exacerbates the problem).

**Comment by Pickysaurus** [comment]
> Using TorBrowser 9.0.9

^ I suspect your problem lies here. 

This is not a bug, it's a problem with your local setup. We have a helpful guide for such issues here: https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by LRN** [comment]
Are you sure? If it were a problem with my local setup, i would not have been able to log in *at all*. But sometimes i am able, so *something* changes *somewhere*, and i'm pretty sure it's not my browser. I could try disable some of the add-ons, see how it goes. But my guess is that it will have no effect.

**Comment by Pickysaurus** [comment]
Hi again,

I have never been able to replicate this issue without installing "paranoid" extensions, which block things willy-nilly. 

The browsers we officially support are Chrome, Firefox, Edge, Opera and Yandex.

The problem reoccurs in one of those browsers (without addons) than there may be a bug in the site.
