### ISSUE TITLE
Download speed always low when downloading at nexus mod manager

### ISSUE THREAD

**Issue by HizkiaSyaukani** [Nexus-Mods/web-issues#1162]
## Bug/error being reported:
Hello,my nexus username is GhostSK98. why i always get slow download speed when downloading big mod files in nexus mod manager, about 10mb++ files size i get about 60kbps,but at 10mb-- file size i get max capped download speed at 1 mbps

**Comment by Pickysaurus** [comment]
Hi there,

Sorry to hear about this issue. 

So we can look into it please can you follow the troubleshooting instructions and create a forum post as detailed here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

Without all of this information, we will not be able to look into your issue. 

Thanks
