### ISSUE TITLE
Endorsement

### ISSUE THREAD

**Issue by Destroyer555** [Nexus-Mods/web-issues#1163]
## Bug/error being reported:
I am not able to endorse a mod even though I have download the mod in February of this year.

Error Our Records show you recently tried to rate this file, (Highlighting Enemy & Corpses (aka HUD)), but couldn't either because you hadn't downloaded the file or because you were trying to rate the file too soon...

## Steps to reproduce:
<!--
Optimally an ordered list with the steps needed to reproduce the bug

### Example:
Cannot reproduce because i have already downloaded the fill.  oters seem to work fine

## Expected result:
![Screenshot_2020-07-08 Highlighting Enemy and Corpses (aka HUD)](https://user-images.githubusercontent.com/32977018/86976293-1ad20900-c148-11ea-8007-8a9a09c1f2eb.png)

To be able to endorse

## Actual result:
n/a

**Comment by Pickysaurus** [comment]
Can you please provide your username and a link to that mod so I can check this?

**Comment by Pickysaurus** [comment]
Please re-open this issue or post a new one if the problem persists.
