### ISSUE TITLE
Unresponsive Script prevents me from editing my mod's description

### ISSUE THREAD

**Issue by emarron** [Nexus-Mods/web-issues#1165]
## Bug/error being reported:

Cannot edit mod description. Only on this specific mod [https://www.nexusmods.com/skyrimspecialedition/mods/38231/](https://www.nexusmods.com/skyrimspecialedition/mods/38231/).
The page loads forever because it cannot grab this script. [https://i.imgur.com/F30HRY2.jpg](https://i.imgur.com/F30HRY2.jpg)
It does this on different browsers (chrome, firefox, edge) on different devices (Windows/Linux/Android). I apologize that I cannot get a better description, but I have no skills with web stuff. "Script: https://www.nexusmods.com/Contents/Scripts/BBoC-1594649772:js:1198"

## Steps to reproduce:

1.  [https://www.nexusmods.com/skyrimspecialedition/mods/edit/?id=38231&game_id=1704&step=details](https://www.nexusmods.com/skyrimspecialedition/mods/edit/?id=38231&game_id=1704&step=details) Edit my mod's description.
## Expected result:

Being able to edit my mod description.
## Actual result:

 Unresponsive script prevents me from editing my mod. If I stop the script, I can access the page, but I cannot save my input. I've left the page up for an hour before and still no load. IDK, what you could do. Maybe delete my description, so I can rewrite it? 😂 Thanks.

**Comment by Pickysaurus** [comment]
I can verify this and have escalated it to our developers.

**Comment by emarron** [comment]
Wow, you are so fast! Thank you so much.

**Comment by Pickysaurus** [comment]
This should be fixed shortly. It seems one of the scripts got stuck in a loop.
