### ISSUE TITLE
Mod version mismatch when reporting a bug on mod as creator

### ISSUE THREAD

**Issue by Fate-EX** [Nexus-Mods/web-issues#1166]
## Bug/error being reported:
As the creator of a mod, posting a bug report defaults to the version last downloaded. Typically, creators don't download their own mod(s), especially when the size ranges in the >1gb.

## Steps to reproduce:
1. As creator of a mod, navigate to it's "Bugs" tab.
2. Report a bug, complete the form as applicable, and submit.
3. Look at the "Version" for the submitted bug.

## Expected result:
Either default to current version when reporting a bug, or allow the option to change the version for the bug report, as the creator. Preferably, add the option "Change version" within the "Manage" dropdown menu.

## Actual result:
Reported bugs default to the last version downloaded by creators with no way to correct it.

**Comment by Pickysaurus** [comment]
Thanks for the feedback. A possible way around this, for now, would be to click the manual download option for your latest file, then cancel the download. This will place that file as the latest version in your download history and display it when added bugs.

**Comment by Pickysaurus** [comment]
This issue has been closed as we are no longer accepting suggestions via this tracker. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
