### ISSUE TITLE
Tracking Centre changing the order of tracked mods

### ISSUE THREAD

**Issue by recaptchaa** [Nexus-Mods/web-issues#1168]
## Bug/error being reported:
From 2018 to 2019 I went through all of the mods on the Nexus, on all the TES and Fallout games, and tracked everything that interested me, that left me with 292 pages of tracked mods on Skyrim Nexus.

This year I'm trying to thin down my tracked mods, but I needed to look at all of them first, and that's where the issue began, where no matter what order of sorting I use, be it Date Published, Author Name and File Name, the order always changes drastically after a few days. Obviously I didn't test while sorting by Last Upload because it changes the order based on the updates anyways.

I've actually downloaded the last page ( page 292 ), when sorting my tracking centre by Author Name, on Descending order, as a pdf, one time last month ( 06/28/2020 ) and another time recently this month ( 07/17/2020 ), to have actual proof of this happening, and the last time I tracked anything on the Nexus was July 22 ( 06/22/2020 ), so the order changed by itself, without any interference of mine.

## Steps to reproduce:

I guess that one would only be able to reproduce this by doing the same as me, having someone that has many mods tracked, sort it by anything other than Last Upload, and wait maybe a couple weeks and sort it again and compare it with the results last time, but just to see how the orders are all incorrect, I've just now sorted it by Date Published, and saw that the first mod is from 14 February 2012, the name is "Summon Skeletal Horde" ( /skyrim/mods/9583 ), and that can't be the first, since I'm tracking many 2011 mods. The 6th mod showing is CBBE burning Textures fix, ( /skyrim/mods/9822 ), but how can a fix for CBBE show up, while CBBE itself, that was published at 04 December 2011, and I've checked it and its tracking, not show up anywhere on that page?

Here's the .pdf converted to jpg from 06/28/2020 when sorting by "Author Name":

![Tracking Centre sorted by Author Name from 06-28-2020-1](https://user-images.githubusercontent.com/68620437/88117578-e58ad980-cb91-11ea-8b91-a31927335491.jpg)
![Tracking Centre sorted by Author Name from 06-28-2020-2](https://user-images.githubusercontent.com/68620437/88117583-e91e6080-cb91-11ea-8c9d-fcd4a79e5d7b.jpg)

Here's the .pdf converted to jpg from 07/17/2020 when sorting by "Author Name":

![Tracking Centre sorted by Author Name from 07-17-2020-1](https://user-images.githubusercontent.com/68620437/88117633-081cf280-cb92-11ea-80b8-76d9c1e608fe.jpg)
![Tracking Centre sorted by Author Name from 07-17-2020-2](https://user-images.githubusercontent.com/68620437/88117648-0c491000-cb92-11ea-9fdb-418ae4431757.jpg)

And here's the .pdf converted to jpg from today, 07/21/2020, showing the Date Published sorting is wrong:

![Tracking Centre sorted by Date Published from 07-21-2020-1](https://user-images.githubusercontent.com/68620437/88117720-43b7bc80-cb92-11ea-974b-4d9cb79dfd0f.jpg)
![Tracking Centre sorted by Date Published from 07-21-2020-2](https://user-images.githubusercontent.com/68620437/88117728-47e3da00-cb92-11ea-9556-18cfc36b8725.jpg)

I hope I provided enough information and the files are uploaded correctly.

**Comment by Pickysaurus** [comment]
Thanks for the detailed feedback. 

We are aware that the tracking centre could be improved in a lot of ways and will be undertaking a project to improve it at some point in the future.
