### ISSUE TITLE
Nexus Site Notices clearing before even getting a chance to read, clicking bell

### ISSUE THREAD

**Issue by Jaderivers** [Nexus-Mods/web-issues#1169]
User - Jaderivers 
Skyrim tracking notices more than once , have just disapeared when clicking the bell icon , before I even get a chance to read
them ? ..
Its happening mostly on skyrim  nexus mod page , but now noiticing it happening on skyrim speical edition...
I can't replicate it myself because it happens more than once anyway, my browser is chrome Version 84.0.4147.89 (Official Build) (64-bit)..
I can't explain why it might be happening as I don't really know , hence why I'm here...

**Comment by Jaderivers** [comment]
Aww c'mon   Picky,  you marked it as " can't replicate"  O.o 
No theories , nothing ! or trouble shooting possible solutions ?  >_<
So I'm stuck with losing out on reading posti replies to mod I'm tracvking then,  O_o , the only thing I can think to try , is to un track weait a couple of sec then click track again ?

**Comment by Pickysaurus** [comment]
I suspect browser addons or privacy settings may be messing with the site. 
https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by Jaderivers** [comment]
Well I took a look at my settings,  and just about everything was " yes"  the only things in no were new games on nexus, and translations , and s it still happens, I'm getting so fed up with it , I don't know what else I can do ?

**Comment by Jaderivers** [comment]
I don't think I can even downgrade the browser to an later version either, to where it possibly wasn't been happening o.O

**Comment by Pickysaurus** [comment]
The only reasons for the notices to disappear would be either:
- Something in your setup is automatically pressing the "dismiss" button. 
- You have already read the notification on another device and the version you're looking at was out of sync. 

Does it _only_ happen from tracking updates or all notifications under the bell icon?

**Comment by Jaderivers** [comment]
It happens on all notifications, I don't get to read any, because they'll
all get auto cleared clicking in the bell icon to get the drop down listing
, tho, " touch wood "  it hasn't been happening as much lately ! ...but it
happens on both skyrim and special edition  skyrim , not sure about fo4,
haven't been the few days now ....
Thanks for your responses btw ! ...

**Comment by Pickysaurus** [comment]
I'm afraid I'm not able to reproduce this and there are no other reports like it, so I can only assume it's something in your local setup.
