### ISSUE TITLE
Comment section contrast issue and user icon transparency

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#117]
Overall loving the redesign. Some minor issues :
The font color chosen for the game Mass Effect is too light. The contrast between the font and the white of the background isn't very enjoyable to see.
![firefox_2017-10-02_21-31-19](https://user-images.githubusercontent.com/12874678/31095515-630c6360-a7b9-11e7-881e-2d3ecd36debd.png)

I'm wondering if having a transparent background to the box that contains the icon wouldn't look better. Here you have my icon for example, that uses transparency. Doesn't look great in a big blue box.
In the same screenshot, the menu buttons could use with a bigger hitbox. Not big mobile buttons, but a bit larger than just the font, to allow for some margin in the clicks.
![firefox_2017-10-02_21-31-37](https://user-images.githubusercontent.com/12874678/31095516-6315b8c0-a7b9-11e7-9ee1-0085ffa38d0b.png)

As said, very minor issues, but issues nonetheless :).

**Comment by iamtiz** [comment]
Fixed
