### ISSUE TITLE
Problems logging in with hCaptcha 

### ISSUE THREAD

**Issue by mononeko** [Nexus-Mods/web-issues#1171]
## Bug/error being reported:

can't log in even after doing the captcha
on Firefox,Edge and chrome
 
Help us prevent spam by completing the captcha challenge.
## Expected result:

i log in

## Actual result:

Help us prevent spam by completing the captcha challenge. loop

**Comment by geekblogio** [comment]
Same for me. (Chrome)

**Comment by mrmason** [comment]
Thanks for the report, we're aware of an issue and should be pushing a fix very shortly.

**Comment by elpsyho** [comment]
same. for me (opera + mozilla)

**Comment by mrmason** [comment]
Can you please let us know if it's working correctly now ?

**Comment by geekblogio** [comment]
Works for me now.
