### ISSUE TITLE
cnt login. hcaptcha problem.

### ISSUE THREAD

**Issue by elpsyho** [Nexus-Mods/web-issues#1172]
## Bug/error being reported:
i cnt login today cuz i cnt solve captcha. i mean- i press button, but "puzzle" frame not appear. that hape in mozilla and opera browsers, but in damn IE captha work fine... 

## Steps to reproduce:
attempt to log in

## Expected result:
succes in log in ofc

## Actual result:
i cnt login cuz "puzzle" frame from captcha not appear

can u plz give alternative way to log in? another captcha or sending code to email/phone?

**Comment by Pickysaurus** [comment]
This issue is likely caused by your privacy settings or browser addons. Please see https://help.nexusmods.com/article/113-troubleshooting-website-issues for additional help.

**Comment by elpsyho** [comment]
i have only 1 addon- "freegate" (inactive for nexus), no ad blokers etc. browsers security settings r low like- no "privacy browsing", no defense against "traking down" etc. i even turned off my antivirus...
