### ISSUE TITLE
ImprovedGarrisonModPayment

### ISSUE THREAD

**Issue by Scuzzlebutt11** [Nexus-Mods/web-issues#1174]
## Bug/error being reported:
Crash/Error

## Steps to reproduce: 

Nothing specific just have mod active

### Example:
[_132405617893183695.htm#.pdf](https://github.com/Nexus-Mods/web-issues/files/5004646/_132405617893183695.htm.pdf)

## Expected result:
Units should get paid and the game continues or as I'm trying to review amount to be deducted I can see it by hovering my mouse over coin icon

## Actual result:
When payment processes for troops the game crashes, or prior to payment being made to troops I'll hover mouse over coin icon to check on payment and game crashes

**Comment by Pickysaurus** [comment]
This bug tracker is for the Nexus Mods website. Please post on the relevant mod page to report this.
