### ISSUE TITLE
Site Redirect Phishing?

### ISSUE THREAD

**Issue by AiJhae** [Nexus-Mods/web-issues#1175]
## Bug/error being reported:
Site being redirected to (fake?) Virgin survey
https://eu.marketwatchjpm.xyz/d9889233c868125e77c6a103221d58cc/index.html?ip=86.17.170.143&siteid=YjY0MTU2ODQxNjAwMTU0NDczNjMzMiMxNTk2MjgyMDk0QDU3MDhAXzIxMjFhYzZkYzc2YmM2YzllODI2YjZkY2RjNzZiMDZk&trackid=202008011141435779

## Steps to reproduce:
1. Open site
2. Login
3. Wait
-->

## Expected result:
Expected to stay on site

## Actual result:
Redirected with no ability to go back

**Comment by Pickysaurus** [comment]
Sorry to hear about this issue.

Can you please file a report on the forums including the information requested here? https://help.nexusmods.com/article/100-how-to-report-bad-or-inappropriate-ads

Thanks!

**Comment by AiJhae** [comment]
Hi Mike

I can't do this, the redirect keeps applying! 

I downloaded Firefox url blocker, and now it has a different url. I can now briefly return to a page, but then the redirect is reapplied.

I cannot keep the page up long enough to report the issue. 

⁣Regards
John Perks​
