### ISSUE TITLE
CROSS_MojaveManhunter  when you equipped the duster the pipboy disappears !!

### ISSUE THREAD

**Issue by Judgejdredd** [Nexus-Mods/web-issues#1176]
## Bug/error being reported:
CROSS_MojaveManhunter  when you equipped the duster the pipboy disappears !!
I started put the duster on and pipboy disappears completely.You can the put other parts of the outfit on........but the duster is the only thing you can't use or the pipboy will disappear.Is there any way you can fix this?

**Comment by Pickysaurus** [comment]
This bug tracker is for issues with the Nexus Mods website. Please leave a comment on the mod page if you're having issues with a specific mod.

**Comment by Judgejdredd** [comment]
Why was the issue with this mod from the Nexus website here: https://www.nexusmods.com/fallout4/mods/32214 Why was it closed?

**Comment by Jaderivers** [comment]
Close Because it doesn't belong here and you also answered your own question within the question ... this is for nexus site issues only..

**Comment by Judgejdredd** [comment]
It is a Nexus issue!!! I was on Nexusmods.com and it brought me here to report a bug or issue.Which I did !!! So I report it here and you closed it for no real reason. So I'm reporting a bug with this mod: CROSS_MojaveManhunter part of Nexusmods.com/Fallout 4 for PC  on this Nexus link here: https://www.nexusmods.com/fallout4/mods/32214. If this is not the RIGHT website to report issues & bugs to. Can you please give the right website to report any issues or bugs from Nexusmods/Fallout 4 about mods that have issues or bugs. Please e-mail back and give the correct website or websites to report any bugs or issues too.Thank you.

**Comment by Judgejdredd** [comment]
> 
> 
> Closed Because it doesn't belong here and you also answered your own question within the question ... this is for nexus site issues only..

What do you mean I answer my question with a question???  I did get the mod from the Nexusmods.com/Fallout 4 website this link here: https://www.nexusmods.com/fallout4/mods/32214  and if it does belong here where do I go to report this issue or bug?

**Comment by Pickysaurus** [comment]
You are reporting a problem with a specific mod. This tracker is for issues with the Nexus Mods website. For example, if a mod page fails to load or a button doesn't do what is expected. You need to report mod issues or the mod page as they won't be seen by the author here.

**Comment by Judgejdredd** [comment]
> 
> 
> You are reporting a problem with a specific mod. This tracker is for issues with the Nexus Mods website. For example, if a mod page fails to load or a button doesn't do what is expected. You need to report mod issues or the mod page as they won't be seen by the author here.

Okay thank you. I think https://www.nexusmods.com/fallout4 website should try to fix problems with their website so it won't bring me or anyone else to the wrong website. When you try to report an issue or bug with any mod. I do apologize & sorry bother you on reporting the bug here instead of the correct website. Thanks a bunch for your help.
