### ISSUE TITLE
Forum profile does not properly track/display posts in history

### ISSUE THREAD

**Issue by creedangelus** [Nexus-Mods/web-issues#1177]
## Bug/error being reported:
Forum profile does not properly track/display posts in history

## Steps to reproduce:
Post a reply to a forum thread via a mod's comments page/tab on nexus.
Navigate to "Posts" tab under forum profile
Click Find Content
Click "Only Posts" tab

## Expected result:
The latest post on Posts tab and the Only Posts tab should be the same.
The Only Posts tab should be able to track all user's posts, up to the first one ever posted on nexus.

## Actual result:
Posts tab functions fine, displaying latest post.
Only Posts tab does not display latest post.
Only Posts tab also does not track many of the oldest posts.

**Comment by Pickysaurus** [comment]
I have been able to replicate this, however, it seems to be an issue with the IPBoard software that powers the forum. We are not planning to make any significant changes to the forum for the foreseeable future. We will, at some point, be working on the commenting system as a whole where little things like this will be easier to pick up. 

Thanks for the report.
