### ISSUE TITLE
TrackingCenter appearing empty after upgrading to premium account.

### ISSUE THREAD

**Issue by Darkinian** [Nexus-Mods/web-issues#1178]
## Bug/error being reported:

For some unknown reasons, after upgrading to premium, the tracking center stopped working properly for me. I can't get it, for the life of me, to display mods I have tracked. While it shows the number of pages, nothing loads. The problem started as soon as I became a premium account. I am a multimedia integrator so I checked if Javascript was enabled, disabled all blocking extensions as well as pop up blockers, reset the 
![unknown](https://user-images.githubusercontent.com/69497084/89859161-5c523b80-db6e-11ea-994f-2136975d25eb.png)
cache, etc. 

## Steps to reproduce:

In my case, it was 1. Get premium. 2. noticing the tracking center has suddenly display issues.
## Expected result:

Normally, my tracking center has no issue. It just suddenly became a problem after upgrading to premium.
## Actual result:

The current result is nothing appears, but it still understands it has content for it shows me the page numbers.

**Comment by Pickysaurus** [comment]
I can't think of anything on our end that would cause this. Can you try the troubleshooting steps here? https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by Darkinian** [comment]
Hi again, I did. I am still stuck in the same situation. Even I don't really think the premium is the issue, it's more the coincidence of the timing, it simply happened after I upgraded, strangely. I am still looking into it, I tried with different browsers, same issue. If I find anything, I'll let you know.
