### ISSUE TITLE
forget it. You either want money or you don't.

### ISSUE THREAD

**Issue by SLiM3RC** [Nexus-Mods/web-issues#1180]

**Comment by SLiM3RC** [comment]
Upgrade your account today
Oops! Something went wrong! does not want money for 1 month ticked and selected

**Comment by jakedraddy** [comment]
Trying to buy 1-month plan from https://users.nexusmods.com/register/memberships, brings me to page with the above mentioned error

Oops! Something went wrong!

You must select at least one package to purchase

**Comment by Pickysaurus** [comment]
This is a known issue as @jakedraddy points out you have a pending renewal invoice which is the cause of the bug. On the forum click the drop down next to your username and select "Client Area" from there you'll see a "Pay Now" on the expired plan.
