### ISSUE TITLE
Skyrim: Sacrosanct Lord Vampire stopped absorbing lifeblood

### ISSUE THREAD

**Issue by Moronta7562** [Nexus-Mods/web-issues#1181]
## Bug/error being reported:
Stopps absorbing lifeblood

## Steps to reproduce:
over the 12 and the 19 perk that i achiev after it says: "a new perk is available" when i continue killing it stopps from absorbing lifeblood, so i ignore not recieving more messages, and even if the bar is completly full, i dont get more perks points.

**Comment by Pickysaurus** [comment]
This is not a bug with the Nexus Mods website. Please use the mod page to report it to the author
