### ISSUE TITLE
Unable to launch Vortex

### ISSUE THREAD

**Issue by popsoda27** [Nexus-Mods/web-issues#1182]
![Annotation 2020-08-13 184418](https://user-images.githubusercontent.com/20932783/90125708-0ad7c580-dd95-11ea-89ca-4fa44d5f6bb1.png)
## Bug/error being reported:
Vortex unable to launch at all. Error window pops up each time when trying to run Vortex. Refer to screenshot

## Steps to reproduce:
1. Double clicking on program shortcut on desktop
2. Or running program from Start menu
3. Or running exe directly from program folder
All 3 gives the same error

## Expected result:
Tried uninstalling, reinstalling, restarting PC before attempting to run program. Expected to be able to run properly as usual.

## Actual result:
Still same error window

**Comment by Pickysaurus** [comment]
Looks like you're trying to use Vortex on a 32-bit computer. If that's correct I'm afraid Vortex is not compatible with your system. Please also be aware this is not the place to report Vortex bugs, that can be found here: https://github.com/Nexus-Mods/Vortex/issues
