### ISSUE TITLE
We value your privacy pop-up

### ISSUE THREAD

**Issue by scribblefingers** [Nexus-Mods/web-issues#1183]
## Bug/error being reported:

Every time I open a new page on nexus I am given the 'we value your privacy' pop-up and asked to disagree, more options or agree. If I agree or disagree, it pops up again on every new page I open, not saving my answer. If I choose more options, I cannot 'save and exit' or 'agree'. The buttons change colour to show I've clicked on them but the pop-up doesn't go away. I have to refresh the page and choose either agree or disagree, thereby continuing the loop. This has happened several days in a row, both when I was not signed in and when I was.

**Comment by Pickysaurus** [comment]
Sounds like you might be blocking cookies which means your choice isn't saved

**Comment by scribblefingers** [comment]
Yes I had third party cookies disabled. One I enabled those it fixed it. Thanks!

**Comment by Pickysaurus** [comment]
Glad to hear it. Although this does seem to be happening for others intermittently so I'll leave this report open.
