### ISSUE TITLE
Email change verification code email is being sent with no actual code. 

### ISSUE THREAD

**Issue by ChrisD202076** [Nexus-Mods/web-issues#1184]
URL: 
https://users.nexusmods.com/user/security/edit

Username on the Nexus:
kafkaspawn

Bug/error being reported:
Unable to change email adress

Steps to reproduce:
Follow link above, choose to change email, fill in current password and new email, check your email account for the verification code

Expected result:
I expected to receive and email with a code in it, I also expected to have a place to fill in that code. 

Actual result:
I received an email without a code, instead informing me someone is trying to change email. 

This is the text in the email
Nexus Mods Account Warning
There isn't anything to worry about, we're just alerting you that someone has attempted to use this email address for registering a new Nexus Mods account, or they've attempted to change their e-mail address to this one.

If this was you, then you already have an account registered on this address, so please log in to your existing account.

If this wasn't you, then there's nothing you need to do, we haven't changed any details or allowed the registration / e-mail change.

**Comment by Pickysaurus** [comment]
Hi there,

As the email says, you already have a Nexus Mods account with the email address you're trying to use. Please log in to that account and delete it so you can update your main account.
