### ISSUE TITLE
Samsung internet not loading tabs

### ISSUE THREAD

**Issue by NeverExists07** [Nexus-Mods/web-issues#1185]
Only the description tab works cause its the default. It works before you sign in, then after that it stops working. Other people have reported this. There is a report of this in 2017 and still has not been fixed.

**Comment by Pickysaurus** [comment]
This seems to be a problem localised to your device/browser (unless you can provide links to the other reports you mention).

I believe it may be related to your browser zoom level. I also strongly recommend using Google Chrome on an Android phone for maximum compatibility with all websites. 
https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by NeverExists07** [comment]
How does that make sense when its only after i log in? It works fine if I dont log in.

**Comment by Pickysaurus** [comment]
I'm afraid I'm not able to replicate this problem, can you reproduce it was another browser?

**Comment by NeverExists07** [comment]
OK I tried removing the zoom option, and it works now. My bad! Thanks for the help.
