### ISSUE TITLE
Download issues with my mod

### ISSUE THREAD

**Issue by eeekie** [Nexus-Mods/web-issues#1186]
## Bug/error being reported:
I have had several reports of download errors with my mod. 

## Steps to reproduce:
I personally have not been able to reproduce the error on my end at all, and many others download without issue. However, for those that cannot complete the download, I'll direct them to an external download if they have issues. I'm not sure if there's a way to confirm that there is an issue with my mod itself or if this is one of many user limitations that are described in your "download issues" FAQ. Here is the mod link: 

https://www.nexusmods.com/skyrimspecialedition/mods/30757

**Comment by Pickysaurus** [comment]
I'm afraid this seems to be a problem with the specific user's connection. It's odd that several of them have all reported this to you at once. The best thing they can do is look at our troubleshooting guide and report the problem to us on the forums.
