### ISSUE TITLE
Some modpacks are not downloading

### ISSUE THREAD

**Issue by aprox2** [Nexus-Mods/web-issues#1189]
## Bug/error being reported:
I am not able to download multiple mod packs. There are no internet issues on my end all other download are downloading at atleast 4mb/s including other mods from the site.
Mods that are not downloading:
https://www.nexusmods.com/skyrimspecialedition/mods/659 (1% after 7h)
https://www.nexusmods.com/skyrimspecialedition/mods/3820 (1% after 7 h)
https://www.nexusmods.com/skyrimspecialedition/mods/21423 (0% after 7h)
## Steps to reproduce:
1. Open the link
2. Click on download
3. Notice it's not downloading even tho you have internet
### Example:
![2020-09-04 02_29_16-](https://user-images.githubusercontent.com/52548590/92183316-b46f1b80-ee56-11ea-88d6-52ab9381ae90.png)
**Note it is downloading all of them at once, but it doesn't make a difference if I download the 1by1 and I have nexusmods premium**
## Expected result:
It should be downloading

## Actual result:
It is not

**Comment by Pickysaurus** [comment]
Sorry to hear about this. Please see https://help.nexusmods.com/category/10-policies-and-guidelines for download troubleshooting and the correct way to report these issues. Thanks
