### ISSUE TITLE
Bug section - Loading issue label remains after bug has been loaded

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#119]
Title is self explanatory, see example below :
![firefox_2017-10-02_21-58-02](https://user-images.githubusercontent.com/12874678/31096623-d7a30316-a7bc-11e7-95a4-41991323de4e.png)

It doesn't happen every time. Maybe 1/3 of the time, from my testing. Very inconsistent.

**Comment by verenion** [comment]
Assigned PT#151632798

**Comment by iamtiz** [comment]
Fixed
