### ISSUE TITLE
Scroll Scouting bug with Legacy of the Dragonborn

### ISSUE THREAD

**Issue by GamerMom1956** [Nexus-Mods/web-issues#1190]
## Bug/error being reported:
 Putting the Elder Scroll (Dragon) into the museum display after acquisition results in an error during the Dawnguard quest. "Scroll Scouting" quest begins, instructing player to "buy back the Scroll from Urag gro-Shub, even though the Scroll was never sold to him. Impossible to remove quest from log. Also difficult to continue with Dawnguard DLC beyond "Beyond Death" quest stage, as "Seeking Disclosure" does not initiate.

## Expected result:
 Attempted console commands to advance "Scroll Scouting" to end the quest.

## Actual result:
 Console command to end "Scroll Scouting" did not end quest.

**Comment by Pickysaurus** [comment]
This tracker is for issues with the Nexus Mods website.
