### ISSUE TITLE
Active Effect bug - Scales of Pitiless Justice - Legacy of the Dragonborn

### ISSUE THREAD

**Issue by GamerMom1956** [Nexus-Mods/web-issues#1191]
## Bug/error being reported:
 Cannot remove active effect of the benefits/penalties granted by the Scales of Pitiless Justice, even after placing item in the museum. Currently have a permanent penalty to Speech.

## Steps to reproduce:
 Found Scales of Pitiless Justice. Received increase to Stamina, Carry Weight and Magicka Regen, and penalty to Speech. Placed artifact in museum, but benefits/penalties were not removed. Console commands do not remove active effects. Blessing of Dibella suppresses Speech penalty for a time, but it is not a permanent fix.

## Expected result:
 Expected the buffs/debuffs to be temporary, as long as item was in my possession.

## Actual result:
 Buffs/debuffs are permanent, and am not happy about that.

**Comment by Pickysaurus** [comment]
This tracker is for issues with the Nexus Mods website.
