### ISSUE TITLE
can't switch from SSE to LE mods

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1192]
## Bug/error being reported:
When I'm login (for SSE mods) and licke left above on LE to change what is shown, I get SSE again.
The oly way to see LE for me is too start browser new and choose LE and make a new login.
This had been not before, i.s. some weeks ago.
## Steps to reproduce:
![01](https://user-images.githubusercontent.com/40837496/92478308-445bef00-f1e2-11ea-9975-f2edfe9f7309.jpg)
![02](https://user-images.githubusercontent.com/40837496/92478319-4756df80-f1e2-11ea-9693-009e351330c9.jpg)

**Comment by BigBizkit** [comment]
I'm having a hard time trying to understand what you're saying, but it sounds like you want to have Skyrim LE in your favourites?

If so: 
1. go here: https://www.nexusmods.com/games
2. Hover over "Skyrim"
3. Hover over the Plus in the top right corner of the game tile 
4. Click "Add to Favourites"

That will add Skyrim LE to your Favourite tray (what's shown under "my games").
