### ISSUE TITLE
Can't create an Article

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1193]
## Bug/error being reported:
when I (only) try to write an Article with this text below, and try to save, I get Error because unallowed characters. I Can't see where is an unallowed character in the text.
---start text ---
Anleitung - Straßen in Shumer in World Map sichtbar machen
Shumer hat ja schöne breite gepflasterte Straßen, aber leider in der Weltkarte nicht sichtbar. Ist der Spieler nun neu in Shumer, startet gerade die erste Quest, ist er mit M für World Map nicht schlauer, wohin er nun laufen soll. Als ich Shumer erstmalig startete, bin ich querfeldein gelaufen, keine Idee, außer der Himmelsrichtung. Selbst Konsole brachte da keine Hilfe.
Da hab ich mich nach meiner Himmelsrand-Karte gesehnt.
---end text---

**Comment by BigBizkit** [comment]
If this part is the title "Anleitung - Straßen in Shumer in World Map sichtbar machen" then the issue is the hyphen (-) and the "ß" character, neither are allowed in the title field.
