### ISSUE TITLE
Can't Sign in to Nexus Mods

### ISSUE THREAD

**Issue by j-Desktop** [Nexus-Mods/web-issues#1194]
## Bug/error being reported:
I cannot sign into or create a new nexus mods account. When I try to, I am redirected to a new page saying "The change you wanted was rejected. Maybe you tried to change something you didn't have access to. If you are the application owner check the logs for more information."

## Steps to reproduce:

Optimally an ordered list with the steps needed to reproduce the bug
1. On home page click 'Log In'
2. On the Log in page click 'Log in' after inputting username and password
3. Redirects to a new page with a white background and a text box outlined in red
(The same happens when I try to create a new account)

### Example:
https://user-images.githubusercontent.com/71064137/92694116-eb2ebf80-f389-11ea-80bf-d58925e97473.png

## Expected result:
I was expecting to log into nexus mods or create a new account.

## Actual result:
This screenshot below
https://user-images.githubusercontent.com/71064137/92694116-eb2ebf80-f389-11ea-80bf-d58925e97473.png

**Comment by Pickysaurus** [comment]
This is very likely to be caused by your browser add-ons or privacy settings. Please see this help article: https://help.nexusmods.com/article/113-troubleshooting-website-issues

If the issue persists, please email support@nexusmods.com from the address linked to your account and we'll looking into it further.

**Comment by j-Desktop** [comment]
Thank you very much for the quick reply, you were right it was my ad block.  Kind regards, j-Desktop   From: MikeSent: Thursday, 10 September 2020 5:35 PMTo: Nexus-Mods/web-issuesCc: j-Desktop; AuthorSubject: Re: [Nexus-Mods/web-issues] Can't Sign in to Nexus Mods (#1194) This is very likely to be caused by your browser add-ons or privacy settings. Please see this help article: https://help.nexusmods.com/article/113-troubleshooting-website-issuesIf the issue persists, please email support@nexusmods.com from the address linked to your account and we'll looking into it further.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
