### ISSUE TITLE
Can't upload media for mods

### ISSUE THREAD

**Issue by moderndemon84** [Nexus-Mods/web-issues#1196]
URL: https://www.nexusmods.com/
Username on the Nexus: moderndemon84
Bug/error being reported: Can't upload media
Steps to reproduce: Edit mod -> Media
Expected result: To upload the media
Actual result: Doesn't upload the media and prints "There has been a error with this file",no matter the picture I choose.

**Comment by Pickysaurus** [comment]
#1198 is the same issue, please can you provide the footer information requested there?
