### ISSUE TITLE
Main file version update does not update mod version

### ISSUE THREAD

**Issue by megapatato** [Nexus-Mods/web-issues#1197]
## Bug/error being reported:
Uploading a new version of the main file does not update the mod's version, only the file's version. As the mod version is out of sync with the main file version, when Vortex checks for updates, it detects there is an update, but clicking the changelog icon doesn't show the current/latest versions properly.

## Steps to reproduce:
Create / update a main file to have a more recent version number, upload the file to Nexus, save & publish. The file's version reflects the correct value, but the mod's wasn't updated.

### Example:
Using my mod Magnusdottir's Triumph (https://www.nexusmods.com/skyrimspecialedition/mods/39539)
1. Original upload had the file at v1.0 and the mod likewise at v1.0
1. I updated the main file to v1.1
1. The mod did not update to v1.1
1. I had to manually adjust the mod's version to v1.1

Other mods that were recently updated (e.g. mods/37197, mods/37792, mods/27789) seem to be having the same issue, where the mod's version does not track the main file's latest version.

## Expected result:
When updating the main file, the mod's version should inherit the version update. This was the behavior some months ago. 

## Actual result:
Mod's version requires manual tweaking after updating the main file because the mod's version was not modified.

**Comment by Pickysaurus** [comment]
You need to check the checkbox under the file version number to update it on the mod page automatically. 

Also to correctly inform Vortex of the update chain, when you want to update a file. Select the "Manage" menu on the file (from the editing page) and select "Upload a new version of this file" or make sure you add the old file to the "This is a new version of an existing file" part of the upload form. Version numbers alone aren't reliable to determine updates as many authors don't use proper version numbering. 

While I agree this could be made clearer, it is not a bug.
