### ISSUE TITLE
Can't upload images to a mod page

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1198]
ANY header image I try to upload gives "There has been an error with this file"
jpg, gif, less than 400kb
by that I can't create new mod site
https://www.nexusmods.com/skyrimspecialedition/mods/edit/?id=40421&game_id=1704&step=media
![error](https://user-images.githubusercontent.com/40837496/93018768-74383780-f5d2-11ea-8110-c5d5b630a146.jpg)
![error 2](https://user-images.githubusercontent.com/40837496/93018789-9f228b80-f5d2-11ea-8b00-358c4a89d318.jpg)

**Comment by Pickysaurus** [comment]
I'm not able to replicate this, but we have had a few similar reports. Can you please tell me what it says in your page footer under "Page served in"? It may be one specific web server is having problems with image uploads.

**Comment by Dreifels** [comment]
1) I'm not sure what oyu mean with "page footer", It didn't save.
2) in between I made a new one with different name, and that worked with same files.
Also I notice, that you changed settings: Now I read max size is 750kb, before it was 400kb
https://www.nexusmods.com/skyrimspecialedition/mods/edit/?id=40423&game_id=1704&step=media
https://www.nexusmods.com/skyrimspecialedition/mods/edit/?id=40421&game_id=1704&step=media

**Comment by Dreifels** [comment]
ok, same issue with next mod site creating,
"There has been an error with this file" when I upload the header image,  but maybe this is a hint:
Now I again have "Max file size 400KB" while the other (the 2nd, working) mod upload had "Max file size 750KB" notice.
Means, that's not only a diferent server but also a different side template code (and by this probably different settings)
As it does not save any, I cannot see what server it is.

Confusing also is " Mod page header area (Optional) " as I cannot let it empty, it will noot accept other images, if that is not done before. ( Your mod images (At least 1 required to publish) )

brwoswer debug says
blocked:
https://secure.quantserve.com/quant.js
https://secure.quantserve.com/quant.js
<anonym>https://www.nexusmods.com/skyrimspecialedition/mods/edit/:101:33
<anonym>https://www.nexusmods.com/skyrimspecialedition/mods/edit/:102:15

GET
https://pw.nexusmods.com/piwik.js
host www.nexusmods.com
filename /Contents/Images/small_ajax_loader.gif
Adresse 104.22.3.55:443
Status404
Not Found

**Comment by Dreifels** [comment]
well, it's definitely different pace code, I now deleted the unfinished mods and started new and get "max 750" and it works fine. You have to investigate where "max 400" ist stored in upload page., what server.

**Comment by Pickysaurus** [comment]
The footer is the bottom of the page. Where all the links are. I'll need to know what the server ID was in the footer to help the team track this down.

Glad to hear it worked out though

**Comment by Pickysaurus** [comment]
I have had the developers look into this and we believe we have resolved the problem, if it happens again please let us know.

**Comment by Pickysaurus** [comment]
Another report of this on the forum, so it may not be resolved yet: https://forums.nexusmods.com/index.php?/topic/8265298-cant-upload-mod-images-help/#entry85074893

> Still log jammed.
> 
> Page served in
> 0.035s [of01]
> Page served in
> 0.035s [of01]

https://forums.nexusmods.com/index.php?/topic/9111143-image-uploads-stuck/

**Comment by Dreifels** [comment]
1) if I see 750kb - it does work fine, if I see 400, I get error message
![test2](https://user-images.githubusercontent.com/40837496/93116615-c73ae900-f6bd-11ea-9273-d0f6ef7647ec.jpg)

2) this is the footer, yes? As you see, there is nothing related Server ID
![test](https://user-images.githubusercontent.com/40837496/93116671-e0dc3080-f6bd-11ea-8956-81092c6db693.jpg)

**Comment by greyday01** [comment]
I can't upload pictures to my mod page either. I drag a jpg image onto the "drop an image here to upload" box. I get a green status bar and a message saying uploading my file name. then when finished there is a pop up box at the top saying "Nexusmods.com says "" [OK]. No picture appears. It looks as though it was downloaded but where is it going?

**Comment by Pickysaurus** [comment]
@greyday01 please read the comments before yours. I need the information from page footer to help us track this down. 

![image](https://user-images.githubusercontent.com/31670524/93204946-dfa71400-f74e-11ea-9a2e-16ce43bcd1b6.png)

**Comment by Pickysaurus** [comment]
This issue should now be resolved. Please re-open this issue if it persists.
