### ISSUE TITLE
again: upload file gives error

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1201]
Error
The file version can only contain letters, numbers, minus sign and full stops. E.g. 0.15.2-beta
but the filename is 
The Shadow of Meresis-1-3-DV-kompl-LOOSE
and now pls explain waht is wrong.

**Comment by Pickysaurus** [comment]
> The **file version** can only contain letters, numbers, minus sign and full stops. E.g. 0.15.2-beta but the **filename** is The Shadow of Meresis-1-3-DV-kompl-LOOSE and now pls explain waht is wrong.

Perhaps that is the problem?

**Comment by Dreifels** [comment]
not, not "perhaps"
In betwen I coould upload it with exact sane name, after I reboot PC, cleaned cache and deleted all coockies.
Your system stores a false attemp and does not delete it before next. So, if one  error then  alwas error for the uploader..

**Comment by Pickysaurus** [comment]
I think you missed my point, caps for emphasis. The error you reported was related to the file VERSION, but you are looking at the file NAME. These are two different fields on the form.

**Comment by Dreifels** [comment]
and again, after correct a type it not longer accepts any. System dies not read new the corrected content.
Thsi it complains again:
---start copy---
Experience Multipliers 2.1 DV
2.1 DV
Skepmanmods  Translation Dreifels
Aendern Sie mit den MCM-Schiebereglern für jede Fertigkeit, wie schnell oder wie langsam sich Ihre Faehigkeiten verbessern
dummy
---end copy---
Error
The file version can only contain letters, numbers, minus sign and full stops. E.g. 0.15.2-beta
