### ISSUE TITLE
Tracking Centre Bugs/Feature Requests

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#1204]
This report is to collate all bugs/feature requests for the tracking centre. If you agree with any of the suggestions, please leave a comment or add a thumbs up to the original issue.

# Bugs #
- Inconsistent sorting #1168 (Can't replicate) 
- Some items are missing from paginated views #971 

# Feature Requests #
- Remove deleted mods from the "Comments" tracking area #929 
- Better searching and filtering controls #928 #940 #669 #936 
- More granular notifications for tracked/owned mods #169 
- Tracked mods need sort by tracked date #1268

**Comment by 0ldi** [comment]
I receive notifications about untracked mods, I did not find functionality how to stop receiving notifications about mods that I did not like, how to block them, etc.

**Comment by Pickysaurus** [comment]
All of these are covered by suggestions here: https://feedback.nexusmods.com/?tags=tracking-notifications
