### ISSUE TITLE
Mod Page WYSIWYG Editor Improvements

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#1205]
A collation of all previous reports and requests for the description page WYSIWYG editor. 

- #1038 Discarding a popup resets your vertical position
- #1036 Description editor is too tall to fit on the screen
- #1034 Ctrl + Z does not undo paste actions
- #1033 Pasting with Ctrl + V scrolls to the bottom of the page (but not with right-click paste) 
- #917 Text cursor is not synchronized between BBCode and full views

**Comment by Greg-Nexus** [comment]
I'm going to close this as we're working on a new WYSIWYG editor, I've copied a link to these issues to our internal issue tracker for testing.
