### ISSUE TITLE
A Download Pop-Up Change that is a Pain

### ISSUE THREAD

**Issue by mlandstreet** [Nexus-Mods/web-issues#1206]
## Bug/error being reported:
Formerly you could click anywhere outside of the download with manager pop-up on the browser screen and the pop-up would close. Now you have to click on the little x. The assumption was that the x was there for people who had not discovered that you could click anywhere to close and for those who were OCD about close icons.

## Steps to reproduce:
In Firefox (I do not use other browsers) download any file using file manager with the pop-up option turned on. Click outside of the pop-up box. Nothing happens. (Before this change the pop-up box closed.)

## Expected result:
Expect the pop-up to close like it has for years.

## Actual result:
The pop-up box waits patiently for you to click on the little x.

**Comment by Pickysaurus** [comment]
A change was made to the pop-up behaviour as they used to hide as you say, which would mean any text entered into the pop up would be lost. I am currently reviewing the list of popups to see which ones we can add exceptions for so I'll make a note.

In the meantime, the Esc key can serve as a way to quickly close it.

**Comment by Pickysaurus** [comment]
We haven't had any other complaints about this since the change. Closing this ticket for now.
