### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by silyar** [Nexus-Mods/web-issues#1207]
## Bug/error being reported:
Cannot create a new account on nexusmods.com. 

## Steps to reproduce:

1. Step 1: entering email-adress, captcha and click "verify email"
2. Step 2: Error 524 Ray ID: 5d6bc9e46b41fa28 • 2020-09-22 11:47:00 UTC A timeout occurred
several times yesterday and today again
3. Step 3: get confirmation code per email, but nowhere to enter it, as the register site leads to a timeout
-->

## Expected result:
place to enter confirmation code

## Actual result:
timeout

**Comment by Pickysaurus** [comment]
Can you please try again? This may have been a temporary issue.

**Comment by silyar** [comment]
Today it is indeed working. Thank you!
