### ISSUE TITLE
Updating a mod with a new file doesn't create a change log entry

### ISSUE THREAD

**Issue by JasonFJ** [Nexus-Mods/web-issues#1208]
## Bug/error being reported:
Replacing the main mod file for a mod doesn't provide a way to add change log text. The change log only shows earlier versions.

## Steps to reproduce:

1. Go to the mod (e.g. https://www.nexusmods.com/7daystodie/mods/835)
2. Choose Manage -> Files
3. Choose Manage - Upload new file version
4a. Check the "This is a new version of an existing file"
4b. Set the file as the main Vortex file
4c. Fill out the form and attach the new version of the mod
4d. Do not check "Remove the previous version after this file has been successfully uploaded"
5. Click "Save" or "Next" (it makes no difference)
6. When you go back to the main mod page and open Changelog... there is no change entry and cannot create one.

## Expected result:
The process of attaching a new file as a replacement of the main file should have an "Changelog" text box which should copy to the main Changelog history.

## Actual result:
The Changelog on the main mod page has no entry, and no ability to add text to describe what has changed (in this case, only a version number update).

Hope this helps!

**Comment by Pickysaurus** [comment]
Changelogs are managed separately from the files at the moment. You need to go to the documentation tab to add to it.

**Comment by JasonFJ** [comment]
There isn't an option to add changelogs via documentation tab unfortunately :(

 See attached.

![changelog2](https://user-images.githubusercontent.com/13237317/94013660-abfd6700-fdaa-11ea-9159-393a6ab0937b.jpg)
![changelog1](https://user-images.githubusercontent.com/13237317/94013662-ac95fd80-fdaa-11ea-8b87-a2f827f4cfb6.jpg)

**Comment by Pickysaurus** [comment]
It's at the bottom of this page: https://www.nexusmods.com/7daystodie/mods/edit/?id=835&game_id=1059&step=docs

**Comment by JasonFJ** [comment]
Ah I see... you have to be in "edit" mode before you click on Docs. Probably needs an "Edit" button on that page... but thanks for the guidance in the meantime.
