### ISSUE TITLE
Hot files sorting broken?

### ISSUE THREAD

**Issue by Tinuvia** [Nexus-Mods/web-issues#1210]
## Bug/error being reported:
Hot files (for Fallout 4) is no longer counting endorsements but seems arbitrary. EDIT: Same for other games (at least Skyrim and Skyrim SSE)

## Steps to reproduce:
see the front page of Fallout 4 on Nexus Mods

### Example:
This is the order of the Hot files today (and it has been oddly sorted for at least a few days, regardless of being logged in as a user or not)

Endorsements Modname
87	Recharger Gun
24	Kirov
53	Military Soldier Vest
32	BFV PPK
16	DiMA Face Fix	
10	Big E's CROSS Vertibird Flightsuit Retexture Pack	
11	Vault Suit Customization - Creation Club - CBBE Bodyslide 

## Expected result:
Our mod published yesterday, Children of Atom Power Armor, https://www.nexusmods.com/fallout4/mods/47586 has 18 endorsements meaning I would expect it to be #4 on the list, or at least above DiMA Face Fix. I'm not sure why Kirov with 24 endorsements is above Military Soldier Vest etc. Sorting by endorsements is also what I would expect from reading the Hot Files section on the Nexus Wiki: https://wiki.nexusmods.com/index.php/Hot_files

## Actual result:
Our mod is not among the 7 that are appointed Hot Files. Clicking "More Hot Mods" it's not even on the first three pages, regardless of having the default sorting by "Date Published" (which also has changed) or "Trending". I can see how this is not a big issue, but it makes such a huge difference in the life of a new mod. Getting to Hot Files on the first day (after which the mod will no longer be on the first page of Nexus) means that the mod enters the happy state of feedback loops from being seen, downloaded, endorsed, seen by more, etc. 

Cheers, 
Tinuvia

**Comment by Pickysaurus** [comment]
We are aware of this issue and will address it as soon as we can. Because it's the weekend it may be Monday at the earliest

**Comment by Pickysaurus** [comment]
We have resolved this issue. Thanks for being patient.

**Comment by Tinuvia** [comment]
Thank you!
