### ISSUE TITLE
Content blocking only partially working

### ISSUE THREAD

**Issue by cuyima** [Nexus-Mods/web-issues#1212]
## Bug/error being reported:
Blocked tags don't seem to be working at the moment. Mods with blocked tags still show up in new today/new this week but not in the search results.

## Steps to reproduce:
Block a common tag and it will still show up in the new mods section.

## Expected result:
Keep blocked tags from showing in new mods.

## Actual result:
Blocked tags still showing in new mods.

My blocked tags
![blocked tags](https://user-images.githubusercontent.com/52758909/94362232-2f280100-00ba-11eb-99a3-5c933e0a7e55.PNG)
New this week section
![New This Week section](https://user-images.githubusercontent.com/52758909/94362228-2afbe380-00ba-11eb-8d3a-1487af8dbd65.PNG)
the mod is properly tagged
![Mod is properly tagged](https://user-images.githubusercontent.com/52758909/94362230-2d5e3d80-00ba-11eb-9da3-b3e7964768db.PNG)
it won't show in search as intended
![Mods don't show in search as intended](https://user-images.githubusercontent.com/52758909/94362252-57176480-00ba-11eb-9dab-865edc2c3088.PNG)

**Comment by Pickysaurus** [comment]
This is likely the same issue that has already been reported in #1210 and #1211, which we're aware of.
