### ISSUE TITLE
Chrome - download not starting 

### ISSUE THREAD

**Issue by zzjay88** [Nexus-Mods/web-issues#1214]
## Bug/error being reported:
Files bigger than 20 MBs are not downloadable anymore. it gives this message all the time:
[https://www.nexusmods.com/witcher3/mods/2815?tab=files&file_id=19557](https://media.discordapp.net/attachments/469559842961358859/760550869170126888/unknown.png)

## Steps to reproduce:

1. Browser: Google Chrome.
2. Location: Italy (i asked anotherfriend from italy to check and the problem was there for them too, but not for a german "Pale Moon" user)
3. Try downloading this:
https://www.nexusmods.com/witcher3/mods/2815?tab=files&file_id=19557

## Expected result:
I expected to download a mod

## Actual result:
And got this instead:
[https://www.nexusmods.com/witcher3/mods/2815?tab=files&file_id=19557](https://media.discordapp.net/attachments/469559842961358859/760550869170126888/unknown.png)

For files bigger than 20mb.
My connection works properly and i can download files from any other platform. nly nexus does this.

**Comment by Pickysaurus** [comment]
Hi there,

Sorry to hear you're having a problem. Please try our troubleshooting steps here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

If you are unable to find a solution there, the article includes instructions on where to post your results for investigation.
