### ISSUE TITLE
Can't set Donation Points permissions if "Not without permission from me first" is selected for asset permissions

### ISSUE THREAD

**Issue by Revan7even** [Nexus-Mods/web-issues#1215]
## Bug/error being reported:
Can't set Donation Points permissions if "Not without permission from me first" is selected for asset permissions.

## Steps to reproduce:
1. Manage permissions on a new or existing mod.
2. Select "Not without permission from me first" under "Give permission for users to use assets contained in my files in their own files?"
3.  "Give permission for users to be able to earn Donation Points for their mods if they use my assets?" becomes faded, but options are still selectable.
4. Select something other under "Give permission for users to be able to earn Donation Points for their mods if they use my assets?"
5. Save changes.
6. View Mod Page
7. Expand "Permissions and Credits" drop-down.

## Expected result:
1. Select to manage permissions on a new or existing mod.
2. Select "Not without permission from me first" under "Give permission for users to use assets contained in my files in their own files?"
3.  "Give permission for users to be able to earn Donation Points for their mods if they use my assets?" should not become faded.
4. Select something other under "Give permission for users to be able to earn Donation Points for their mods if they use my assets?"
5. Save changes.
6. View Mod Page
7. Expand "Permissions and Credits" drop-down.
8. "Asset use permission in mods/files that earn donation points" reflect settings chosen while managing permissions.

## Actual result:
1. Select to manage permissions on a new or existing mod.
2. Select "Not without permission from me first" under "Give permission for users to use assets contained in my files in their own files?"
3.  "Give permission for users to be able to earn Donation Points for their mods if they use my assets?" becomes faded, but options are still selectable.
4. Select something other under "Give permission for users to be able to earn Donation Points for their mods if they use my assets?"
5. Save changes.
6. View Mod Page
7. Expand "Permissions and Credits" drop-down.
8. "Asset use permission in mods/files that earn donation points" is set to "You are not allowed to earn Donation Points for your mods if they use my assets", regardless of settings chosen while managing permissions.

**Comment by Revan7even** [comment]
An author should not have to select the blanket "Yes, but you must credit me as the original creator" option just to allow other authors to earn donation points if they use the original author's assets. Mod authors should have the choice of granting or denying permission to earn Donation Points to other authors who ask to use their assets. Requiring others to ask permission to use an author's assets should not automatically prevent anyone granted permission from earning Donation Points.
If "Yes" is selected for Donation Point permissions that would mean permission is granted along with asset use permission.
If "Contact me for permission" is selected that would mean Donation Points permission is granted or denied separately from asset use permission.

**Comment by Pickysaurus** [comment]
The logic is, if they have to ask you permission for asset use, you can clarify DP usage with them during that conversation.

**Comment by Revan7even** [comment]
I understand that should happen in the conversation, but by that logic I
would expect donation points should be locked to ask for permission - not
locked to no - if asset use is set to ask for permission. In fact that is
the bahavior on old mod pages before the site redesign and introduction of
DP, as mods on Skyrim nexus that haven't been updated since 2012 have
donation points set to ask for permission if asset use is set the same,
even though the author never set that setting and newer mods can't select
that combination.
