### ISSUE TITLE
and again: try to upload replacement of mod version = fase error because chars

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1216]
I upload same (!) file as replacment, did not change any text, except version number, and get error because character. All text is same as accepted before and version number format is valid.
![05](https://user-images.githubusercontent.com/40837496/95114876-e836ad00-0744-11eb-947e-94da521cdf33.jpg)

**Comment by Pickysaurus** [comment]
Can you provide a screenshot of the actual error message?

**Comment by Dreifels** [comment]
the same standard  message line as always.
However, some hrs later I could upload it w/o any change.

**Comment by Pickysaurus** [comment]
I'm afraid without a screenshot of the error I cannot advise you further. If it happens again please reopen this ticket and including the exact error you see. 

Thanks
