### ISSUE TITLE
Box to answer comments too small

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1217]
![Screenshot_2020-10-07_18-48-09](https://user-images.githubusercontent.com/12874678/95361930-a7b66b00-08cd-11eb-81bf-11543e130c64.png)
The box to answer comments in the bugs section is too small, I can't even see the cursor.

Link to reproduce: https://www.nexusmods.com/masseffect2/mods/68/?tab=bugs&issue_id=482408

I'm using Firefox 81.0 on Linux Mint 20 x64.

**Comment by Pickysaurus** [comment]
Looks fine for me. Perhaps this is yet another case of Firefox shenanigans, I'll feed it back.
![image](https://user-images.githubusercontent.com/31670524/95363771-cd407600-08c7-11eb-897e-6e30368d23b7.png)

**Comment by Pickysaurus** [comment]
Actually, aren't you using that "compact nexus" restyler theme or something? Perhaps that's the cause if so?

**Comment by starkgate** [comment]
> Actually, aren't you using that "compact nexus" restyler theme or something? Perhaps that's the cause if so?

Not on this computer, uBlock is also deactivated.

**Comment by Pickysaurus** [comment]
We've managed to replicate this. It seems to only happen when you are the mod page owner. Thanks for the report :)

**Comment by EthereralCoder** [comment]
If it helps, I found a temporary work-around: by clicking BBCODE on then off again, it re-drew the box the correct size.

Happy hunting!

**Comment by Pickysaurus** [comment]
A fix was just pushed out for this. Let us know if you're still having problems.

**Comment by starkgate** [comment]
Works for me.
