### ISSUE TITLE
Internal Mail Issue (User to User)

### ISSUE THREAD

**Issue by Klipperken** [Nexus-Mods/web-issues#1218]
URL: https://forums.nexusmods.com/index.php?app=members&module=messaging&section=send&do=form&fromMemberID=6307289
Username on the Nexus: Klipperken
Bug/error being reported: Fail to mail (User to User)
Steps to reproduce: Use my account and try to mail any user.
Expected result: Mail being sent.
Actual result: Mail NOT being sent.
Link to the affected mod/image (if relevant): [https://ibb.co/FmZZrpd](url)

**Comment by Pickysaurus** [comment]
As shown in your screenshot, you are logged out on the forum. Please use the "Log in" button at the top of that page.

**Comment by Klipperken** [comment]
Bizarre, I even had logged in from that 'site' as it requested it.
It just kept saying I had no permission.
Just now, I retried, and did not even had the sign in option, just went straight to the mail part.

My apologies, sir!
