### ISSUE TITLE
Feature Request: Sort by compatible game version. 

### ISSUE THREAD

**Issue by MalteMagnussen** [Nexus-Mods/web-issues#1220]
## Bug/error being reported:
I am not able to sort mods by compatible game version. 

## Steps to reproduce:
1. Go to Nexusmods /mods - Fx: https://www.nexusmods.com/mountandblade2bannerlord/mods/
2. Observe that there is no way to sort by compatible version. 
![image](https://user-images.githubusercontent.com/11192971/95458901-231e2800-0973-11eb-8e37-dec0ec324ee4.png)

## What I'm suggesting:
For example for Bannerlord, I'd like to be able to select the version (fx currently 1.5.2 is the stable release, 1.5.3 is the beta, but many many mods are only compatible with 1.4.2 or 1.4.1 fx). 

So I'd like to be able to select the version of Bannerlord that I am on (fx 1.5.2), and then only see a list of the mods that are compatible/works with that version of the game. 

I've already spent a lot of time trying to get Bannerlord to work, and manually sorting through mods and their compatibility. Hope this feature can be added in the future! Thanks for all the work you're doing at Nexusmods and for the great platform.

**Comment by Pickysaurus** [comment]
We don't currently store a game version in relation to mods/files. It's also worth noting that some developers (TaleWorlds included) don't use standardised versioning for their games, so the information could only be so reliable. 

It is my hope that at some point in future we will be able to set requirement per-file and in there we could incorporate a game version requirement.

**Comment by Kutomore** [comment]
This would be a godsent for any game that has many playable versions, Bannerlord as the OP mentioned in particular would be great.

**Comment by Pickysaurus** [comment]
Moved to here: https://feedback.nexusmods.com/posts/94/show-compatible-game-version-s-for-mods-collections
