### ISSUE TITLE
No login because constant server timeout

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1222]
https://users.nexusmods.com/auth/sign_in

https://users.nexusmods.com/oauth/authorize?client_id=nexus&redirect_uri=https://www.nexusmods.com/oauth/callback&response_type=code&referrer=%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fusers%2F5872020%3Ftab%3Duser%2Bfiles

![error](https://user-images.githubusercontent.com/40837496/95662250-d9316f80-0b35-11eb-9437-dab31f18f6c9.jpg)
![error2](https://user-images.githubusercontent.com/40837496/95662256-e189aa80-0b35-11eb-9d44-66eb15595056.jpg)

**Comment by Dreifels** [comment]
and now authentication error
![error3](https://user-images.githubusercontent.com/40837496/95663017-c28e1700-0b3b-11eb-9635-a3ad4bcd1a9c.jpg)

**Comment by Dreifels** [comment]
and then this and after that again the error mesaage iof before, and so on
![error4](https://user-images.githubusercontent.com/40837496/95663050-20bafa00-0b3c-11eb-8b8a-c00b07c29a01.jpg)

**Comment by mrmason** [comment]
Please can you check to see if this is working correctly now - our user service seems to be under a DDOS attack, which we're trying to mitigate.

**Comment by TheDrunkMonk** [comment]
Same issues here, have been repeating the process for about 10 minutes. Getting OAuth error and already logged in when hitting Sign In button

**Comment by mrmason** [comment]
Thanks for reporting that, any luck now ?

**Comment by scarface52** [comment]
It's fixed for me as of now.

**Comment by mrmason** [comment]
Great, thanks, I may or may not have inadvertently blocked ourselves from our own oauth service whilst trying to stop the bots. :sob:
