### ISSUE TITLE
Post section is broken

### ISSUE THREAD

**Issue by TechAngel85** [Nexus-Mods/web-issues#1223]
## Bug/error being reported:
The Post section of one of my mod pages has been completely broken with a comment from a user. I've hidden and reported the comment and have confirmed it looks normal to other users now, however, as the author I can still see the comment and the section is still broken.

#### EDIT:
Upon reload, the comment is gone and the page is normal. The user or a moderator may have already removed the comment causing the error.

## Steps to reproduce:
No idea what the user did with the new editor, but it's not good.

## Expected result:
Normal Post section.

## Actual result:
https://www.nexusmods.com/skyrimspecialedition/mods/11583/
Moderator/admin will have to view the page as I am able to view it.

**Comment by Pickysaurus** [comment]
I believe this was resolved by a moderator?
