### ISSUE TITLE
Editing posts moved to the bugs reports section doesn't work

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#1226]
## Bug/error being reported:
Really weird error with posts moved to the bugs section. I'm not sure what it is you changed recently, but it looks like a few bugs appeared.

Trying to edit one of these posts and clicking submit results in an empty orange error banner and an error in the browser's log. Also interesting to note is that the text within the post to edit is entirely HTML.

## Steps to reproduce:
1. Move a post to the bug reports section with the replies
2. Try to edit one of the replies
3. Click submit

![firefox_TlRJZ52ccl](https://user-images.githubusercontent.com/12874678/95789883-a2e32400-0cde-11eb-8b58-977b780e160b.png)
![firefox_cM1xwVbbfb](https://user-images.githubusercontent.com/12874678/95789921-b3939a00-0cde-11eb-9d43-d1b78def362b.png)

**Comment by Pickysaurus** [comment]
We are already aware of the problem editing bug reports. It's on the snagging list for the new editor

**Comment by Pickysaurus** [comment]
#1219 appears to be the same issue, so I'll close this one in favour of that one.
