### ISSUE TITLE
can't login - DDoS protection by Cloudflare not working corretly

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1228]
Firefox 81.02
https://users.nexusmods.com/auth/sign_in
for more than 1 hr now same
![000](https://user-images.githubusercontent.com/40837496/95988369-17c27500-0e29-11eb-8be4-bf90daf2434b.jpg)

**Comment by Pickysaurus** [comment]
Duplicate of #1227
