### ISSUE TITLE
You can scroll right on mod description (mobile) (extremely minor) 

### ISSUE THREAD

**Issue by TheUltimateHuman** [Nexus-Mods/web-issues#123]
You can scroll the page to the right (not the left) while on the mod description page, which cuts off some of the information and shows the background. You can of course just scroll back, but it seemed unintentional. This was on mobile, using a Galaxy S7 edge and the Chrome browser.

**Comment by verenion** [comment]
Assigned PT#151673163

**Comment by verenion** [comment]
Fix has been pushed
