### ISSUE TITLE
Can't reply to bug reports

### ISSUE THREAD

**Issue by tarlazo** [Nexus-Mods/web-issues#1230]
## Bug/error being reported:
When trying to reply to a bug report, an editor toolbar opens but there's no box where to write a text.
**EDIT - please ignore** - it was already reported in "Box to answer comments too small #1217"

## Steps to reproduce:
Select "reply" in bug reports.
![Untitled](https://user-images.githubusercontent.com/45424939/96197810-5d7b5c80-0f53-11eb-9a1f-a28e38cea938.jpg)

**Comment by Pickysaurus** [comment]
Closed in favour of #1217 

Thanks for the report.
