### ISSUE TITLE
Hitting Submit when replying to Bug Report entries does nothing

### ISSUE THREAD

**Issue by EthereralCoder** [Nexus-Mods/web-issues#1231]
## Bug/error being reported:
Submit button appears to do nothing.

## Steps to reproduce:
Reply to a bug report entry
Type in text
Hit Submit button
Nothing happens

## Expected result:
My response appears as a reply to the user

## Actual result:
Nothing happens

URL example
https://www.nexusmods.com/skyrimspecialedition/mods/25471/?tab=bugs&issue_id=482706

![SubmitDoesNotWork](https://user-images.githubusercontent.com/72972973/96245297-08901400-0f5c-11eb-8851-144c0751ffba.PNG)

**Comment by Pickysaurus** [comment]
I just replied to "elder gleam package missing alias" on that page successfully. Although I'll admit it's odd because your screenshot doesn't show the WYSIWYG editor.

**Comment by Pickysaurus** [comment]
Can you try hitting Ctrl + F5 and see if that helps?
