### ISSUE TITLE
Listing New Mods sorted by Last Updated not correct 

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1233]
https://www.nexusmods.com/skyrimspecialedition/mods/thisweek/?BH=0
Sort by Last Updated
list as newest
Dark Brotherhood Assassins - Improvements - Date uploaded - 17 Oct 2020, 3:40PM
The Lost Wonders of Mzark-1-1-BETA DV nur esp und 5 scripte - Date uploaded - 17 Oct 2020, 3:09PM

and this is not listed:
Wheels of Lull SSE 4.1.5 DV FOMOD komplett - Date uploaded - 17 Oct 2020, 3:53PM

**Comment by Pickysaurus** [comment]
This should be resolved.
