### ISSUE TITLE
again login not working correctly

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1234]
again, login not working correctly

1) I click on shortcut on my desktiop for
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files
I get image 1 + 2 (the 2nd is with server ID)
2) I click on Login and get image 3 where I typ ein username and PW and click on Log In
3) nothng happens, except that the color of the LogIn changes to grey, see image 4
4) I wait, nothing happens, I press F5 twice and get image 5
5) I let this open and click again on the shortcut on my desktop to 
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files
and get image 6
6) I click on continue and at least I'm in and on my page, then I close the still open first Window (image 5)

This is every login today

![01](https://user-images.githubusercontent.com/40837496/96470577-bafefa00-122e-11eb-8918-8ef949f38500.jpg)
![02](https://user-images.githubusercontent.com/40837496/96470590-be928100-122e-11eb-9bd6-9938de133da0.jpg)
![03](https://user-images.githubusercontent.com/40837496/96470607-c3573500-122e-11eb-9505-67c5c9b09547.jpg)
![04](https://user-images.githubusercontent.com/40837496/96470614-c5b98f00-122e-11eb-9517-d306f6abb668.jpg)
![05](https://user-images.githubusercontent.com/40837496/96470624-c7835280-122e-11eb-87e8-1f436f879607.jpg)
![06](https://user-images.githubusercontent.com/40837496/96470635-cbaf7000-122e-11eb-895f-9699dc914f31.jpg)

**Comment by Pickysaurus** [comment]
Please try signing all the way out at users.nexusmods.com and sign back in fresh. It seems your session details may have become mismatched somehow.

**Comment by Dreifels** [comment]
this is (probably) also a cockie-issue. It is after I shut down PC and start PC new, means, all stored cockies got deleted by shutdown of PC.
Just tested, if I logout at nexus and login new, then this is not but regular login. But as this issue is not always but on some days only, there is something with your coockie handling, maybe depending what server (i.e. Saturday I didn't had this issue)

**Comment by Dreifels** [comment]
correction: now I have the issue but did not shut down PC and no cockies deleted.
But when clock on Login a 2nd time I get
 Error 524 Ray ID: 5e4bb5853b33c49a • 2020-10-19 16:01:35 UTC
A timeout occurred at users.nexusmods.com
Cloudflare Ray ID: 5e4bb5853b33c49a
