### ISSUE TITLE
Download capped at 1mb only when using vortex

### ISSUE THREAD

**Issue by Ouch660** [Nexus-Mods/web-issues#1235]
## Bug/error being reported:
download from nexus capped at 1mb when using vortex but capped at 2mb when downloading manually
should be 2mb as a non-premium member with adblock turned off
## Steps to reproduce:
tried with and without vortex, adblocker turned off for nexus, single download

**Comment by Pickysaurus** [comment]
https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

**Comment by Ouch660** [comment]
Pointless link, none of that will help determine why nexus is only throttling downloads via vortex, funny really the article even says talk to mod manager devs if the problem only happens then but vortex devs state any posts about download speed from nexus will be ignored,

**Comment by Pickysaurus** [comment]
Apologies for posting only the link, I must've got distracted when replying. 

This bug tracker is for the Nexus Mods Website. For Vortex issues you can get help from one of the following sources: 

In the Vortex app, use the top-right menu to "Send Feedback". 
https://github.com/Nexus-Mods/Vortex
https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/

It should be noted that Vortex doesn't actually have any code in it that _could_ throttle your downloads so it is more likely a problem in your setup.

**Comment by Ouch660** [comment]
I don't have any code to throttle speeds to vortex only either, only nexus can control the download speed based on whether I click Manual Download or Mod Manager Download button

**Comment by brazenvoid** [comment]
Having the same issue since a long while, it is always explicitly capped at 1MBps and half the day rarely goes above 500KBps. 

Now I have stopped downloading through vortex for bigger files altogether, the website works completely fine, it is just a bit of an additional hassle but worth the 2-8x times speed.
