### ISSUE TITLE
Search results incorrect in Skyrim Special Edition

### ISSUE THREAD

**Issue by InfamousNate** [Nexus-Mods/web-issues#1236]
## Bug/error being reported:
Using the search bar at the top of the page shows more results than what appears once the enter key is pressed

## Steps to reproduce:
 1. Type jk's into the search bar to see aprrox 45 results.  
 2. Pressing enter or clicking on "45 results" opens a page with only 1 mod listed (Guards of Skyrim - Riverwood Guards (JK's compliant))
 3. clearing the search results and using refine search (enter jk's into "Filename Contains..." produces the same results.

## Expected result:
A list of search results that contain "jk's" in the file name.

## Actual result:
Only one mod appears with "jk's" in the Filename.

![image](https://user-images.githubusercontent.com/16141506/96902022-ffbea700-1461-11eb-842e-e085104165b8.png)
![image](https://user-images.githubusercontent.com/16141506/96902102-18c75800-1462-11eb-8d9a-9d5b51a4a862.png)

**Comment by Pickysaurus** [comment]
This is a known (but minor) issue. Remove the apostrophe from your query to get the correct results.

**Comment by InfamousNate** [comment]
Searching just Jks (Jk's without the ') produces similar, incorrect search results (2 mods this time, neither of them being the mod in the above screenshot).  The best I've been able to do is just to simply search for JK and scroll through the drop down.  The down side here is only 50 of 59 results are available and pressing enter denies my search as it's under 3 characters.  Using refine search and adding "jk" into the "Filename contains" field will circumvent that restriction in this instance and produce all 59 results.

**Comment by Kpblcep** [comment]
So, apostrophe is not a solution. I replicate this issue through typing "Pandorable" in the search field.
What i must see:
![image](https://user-images.githubusercontent.com/78299192/106380515-f67b9980-63c3-11eb-906d-a465c53030b3.png)
What i get:
![image](https://user-images.githubusercontent.com/78299192/106380534-0c895a00-63c4-11eb-8093-dda0d73ebafe.png)
Can someone fix this?
