### ISSUE TITLE
"Bugs" mod section - large image in bug report remove all content in every bug report 

### ISSUE THREAD

**Issue by RoGreat** [Nexus-Mods/web-issues#1239]
URL: https://www.nexusmods.com/mountandblade2bannerlord/mods/1483?tab=bugs
Bug Report: Crashing even after saving and reloading
Nexus Username: RoGreat

## Bug/error being reported:
Large image files posted in the "Bug Reports" section of a mod are not loaded properly.

## Steps to reproduce:
Copy a large image from Snipping Tool and paste it into the bug report post or reply.

### Example:
1. Open up Snipping Tool
2. Capture a large image that cannot fit into the bug report 
3. Copy the image
4. Paste the image into the bug report by replying to it or creating a new bug report

## Expected result:
A downscaled image or an error if the image cannot load correctly.

## Actual result:
The content in the bug report is no longer visible and if it is still opened, all other content in bug reports when opened are no longer visible unless the culprit HTML element is removed by using inspect element.

**Comment by Pickysaurus** [comment]
Thanks for the report, this is a known issue with Firefox (the problem child of modern browsers). I'll see if we can get that report fixed on the database side.

**Comment by Pickysaurus** [comment]
The offending comment has been deleted. This bug already exists on our internal tracker so I'll close the issue here.
