### ISSUE TITLE
Mod Thumbnails show name of author, but links to uploader profile

### ISSUE THREAD

**Issue by Ghaunadaur** [Nexus-Mods/web-issues#124]
If the uploader of a mod is not the original author (eg translations) the name of the original author is shown in the thumbnail, which is fine, but clicking on the name takes me to the profile page of the uploader.

I tested with a translation I made some years ago , but I can also reproduce this issue with other mods.

![unbenannt-1](https://user-images.githubusercontent.com/32500291/31153574-3348064a-a8a2-11e7-90cb-ae2ed8cc981d.jpg)

**Comment by Rrrafau** [comment]
assigned #151673086

**Comment by mrmason** [comment]
Fix is pushed for this.
