### ISSUE TITLE
Mod author posts are no longer highlighted on mod pages

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1240]
## Bug/error being reported:
Mod author posts are no longer being highlighted on mod pages

## Steps to reproduce:
1. Load any mod page on Skyrim SE Nexus.
2. Notice the missing blue highlight surrounding mod author posts...

## Expected result:
Blue highlight around mod author posts/responses to user questions/concerns.

## Actual result:
Mod author posts showing up as normal posts...

**Comment by Pickysaurus** [comment]
A fix for this should be deployed shortly. Thanks for the report.

**Comment by scjohnson1981** [comment]
Thank you.  This has been an issue for the past 48 hours or so...
