### ISSUE TITLE
Infinite tracking loop

### ISSUE THREAD

**Issue by chillcat222** [Nexus-Mods/web-issues#1241]
[Nexus Profile](https://www.nexusmods.com/users/30468000)

## Bug/error being reported:
Whenever I click "Track" on a mod, whether from the search page, or in the mod page, the gear popup will infinitely spin on the screen unless I close it, and if I try to press "Track" again it brings up the error that I'm already tracking it. This only started happening in the past week or so
## Steps to reproduce:
Press "Track mod"
## Expected result:
The gear will spin for a few seconds and then change to say "Success, You are now tracking (Mod name here)"

## Actual result:
The gear never stops spinning and never gives a popup

**Comment by Pickysaurus** [comment]
This should be fixed now. If it's still not working try Ctrl + F5

**Comment by chillcat222** [comment]
Many thanks for your support and quick service ^w^
