### ISSUE TITLE
Opera GX no ads bug

### ISSUE THREAD

**Issue by Parkerno** [Nexus-Mods/web-issues#1242]
Bug/error being reported:Being Able To Not Get ads without nexus premium

## Steps to reproduce:
Step 1:instal Opera GX
Step2:go to nexus 
Step3: go to the shield in the top right corner, click on it and hit block ads with your cursor
## Expected result:
to get rid of the popups

## Actual result:

all ads are gone

**Comment by Pickysaurus** [comment]
You are enabling ad blocking, which is blocking ads on the website. This is not a bug with our site. We do not have any "pop-up" advertising anyway :)
