### ISSUE TITLE
The Gemstone Prophecy II Deception - unable to download 

### ISSUE THREAD

**Issue by avs36** [Nexus-Mods/web-issues#1243]
## Bug/error being reported:
I have attempted to download it using the manual download method and it downloads until around 90% or so then keeps saying interrupted network error yet I can download anything else from nexus and its fine

## Steps to reproduce:
Step 1 - Go to Gemstone Prophecy page
Step 2 - Go to Files
Step 3 - Click on manual download of main file
Step 4 - Click on slow download

## Expected result:
Completed download of the file

## Actual result:
Constantly receive error as stated above

Link https://supporter-files.nexus-cdn.com/1704/30759/The%20Gemstone%20Prophecy%20-%20Deception%20SE-30759-2-0-1601517707.7z?md5=5h-iSEe3d7SlUzHGw4Qcjg&expires=1606149889&user_id=1394007&rip=105.226.204.247

**Comment by Pickysaurus** [comment]
Hi there,

Sorry to hear you're having a problem. I'm afraid this isn't a problem with the website, it's a connection issue. 

To help us troubleshoot this issue, follow the guidance here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

If the steps there do not fix your problem the article includes instructions on where to post the results. 

That said, it seems like it may be a timeout of some kind. Possibly an ISP restriction.
