### ISSUE TITLE
M&B II: Bannerlord Mod Error

### ISSUE THREAD

**Issue by Marajaladli** [Nexus-Mods/web-issues#1245]
I could play M&B II Bannerlord with mods in version 1.5.2, but I had to format it and then I downloaded it again, installed version 1.5.4, downloaded the Vortex app and started installing the modes, but I can't activate the modes, while the modes never appear on Mod Launcher and Steam, and Vortex is a little different. At first it didn't appear there either, but I translated the rar files of the modes I downloaded into folders and threw them where bannerlord was installed, and most of the modes were activated (there are some that are not activated) but I still can't introduce the modes and play them. The game is original, while Vortex is the latest version.

**Comment by Pickysaurus** [comment]
This tracker is for problems with the Nexus Mods website, you may be able to get help by posting in the forum linked below or joining our Discord:
https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/
