### ISSUE TITLE
"Block user from all of my contents" cannot block some users

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#1246]
The option to block users - who have commented on only articles - "from all of my contents" fails with this error:

> This user didn't leave any comments on your content!

Authors should be able to block users "from all of my contents" who have commented on their articles.

**Comment by fireundubh** [comment]
"From this Mod article" also does not work.

**Comment by Pickysaurus** [comment]
We are aware of this issue. Bug reports and articles are not currently counted as "posts" that are required to block the user. If the user is being a nuisance, please report them to the moderators who can manually apply a block, if appropriate (and their behaviour breaches the ToS).

**Comment by Pickysaurus** [comment]
This is now fixed.
