### ISSUE TITLE
Unable to upload images to a mod.

### ISSUE THREAD

**Issue by tectonicLeader** [Nexus-Mods/web-issues#1247]
## Bug/error being reported:
A mod author asked me to upload images of their mod that I posted to Facebook to the nexus mod page but I am unable to do so.  the bar gets nearly full for the first two images then nothing happens it freezes.

Below is the images in question and a picture of where it has been for an hour on the fifth try.

https://www.nexusmods.com/skyrimspecialedition/mods/42917?fbclid=IwAR25AqWc_0kfwUZfogwAHniv1VsSNgc7_afYehbGq69Ex7frbqm8G_wOmL8&tab=images&BH=0

![Capture](https://user-images.githubusercontent.com/64884955/100842062-44b50080-3446-11eb-829d-0944747124ac.PNG)
![5 (2)](https://user-images.githubusercontent.com/64884955/100842068-467ec400-3446-11eb-9ebd-1f2642676e0d.png)
![5 (3)](https://user-images.githubusercontent.com/64884955/100842077-48e11e00-3446-11eb-83bf-52bb47b5ed60.png)
![5 (4)](https://user-images.githubusercontent.com/64884955/100842084-4c74a500-3446-11eb-91f2-1263a4a343e9.png)
![5 (5)](https://user-images.githubusercontent.com/64884955/100842100-51395900-3446-11eb-8d08-417bbb2223f7.png)
![5 (1)](https://user-images.githubusercontent.com/64884955/100842104-54cce000-3446-11eb-86be-d59e4a63e34d.png)

Edit:  I was able to upload after converting them to a jpg

**Comment by Pickysaurus** [comment]
Do the PNGs exceed 8mb?

**Comment by tectonicLeader** [comment]
> Do the PNGs exceed 8mb?

6.25mb average they do not exceede 8 i had to compress them from 125 mb .bmp files.

**Comment by Pickysaurus** [comment]
I cannot replicate the problem, if it happens consistently feel free to re-open the ticket.
