### ISSUE TITLE
Paid my annual Membership fees but account is not being recognised as Premium!

### ISSUE THREAD

**Issue by Boydie05** [Nexus-Mods/web-issues#1248]
## Bug/error being reported:
Paid my annual Premium Membership in November but my Account is no longer Premium!

## Steps to reproduce:
logging into the website..

## Expected result:
I've paid my annual fees so i expect to have my Premium status and benefits! 

## Actual result:
i am locked to slow download speeds and certain mods are unavaileable to me!
![image0 1362](https://user-images.githubusercontent.com/75499061/101201809-36dac780-3660-11eb-9d65-2e790c7bbada.png)

**Comment by Pickysaurus** [comment]
Sorry to hear you're having problems.

Please send this to support@nexusmods.com along with your username and we'll look into it for you.
