### ISSUE TITLE
Unable to upload files to mod

### ISSUE THREAD

**Issue by R-Vaccari** [Nexus-Mods/web-issues#1249]
## Bug/error being reported:
I can't upload files in order to update my mods. The bar never changes and errors are thrown in developer console.

## Steps to reproduce:
Simply trying to upload a file at 'Manage Files' section.

### Example:
1. Edit mod details
2. Manage Files
3. Upload file

## Expected result:
File uploaded.

## Actual result:
Console errors:

Access to XMLHttpRequest at 'https://upload.nexusmods.com/uploads/chunk' from origin 'https://www.nexusmods.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
BBoC-1607006126.js:1900 POST https://upload.nexusmods.com/uploads/chunk net::ERR_FAILED

These errors are thrown constantly. By the time I closed the time, 17 thousand errors were thrown.

**Comment by Pickysaurus** [comment]
As you seem to be the only person having this problem, please can you try a different browser or your current browser with all addons disabled? 
https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by R-Vaccari** [comment]
Thank you, but the issue has been resolved by Nexus' internal updates. By the way, I had tried Firefox and Chrome (I use Opera) and it had not worked.
