### ISSUE TITLE
Endorsement Notifications Regarding Random Mods

### ISSUE THREAD

**Issue by feykrow** [Nexus-Mods/web-issues#1252]
## Bug/error being reported:
I will get notifications asking me to rate mods I have recently downloaded. Three of these mods (called "AutoLockpick When Sneaking", "Follower -Ronja the Red-" and "Renna Standalone Follower SE") are ones I've never downloaded or even seen before, anywhere.

## Steps to reproduce:
Receive mod rating notification

## Expected result:
Be asked to rate mods I have recently downloaded

## Actual result:
Be asked to rate mods I have never heard of

**Comment by BigBizkit** [comment]
Thank you for the report. 

I've checked the download history for "feykrow" - assuming that is your Nexus Mods account and, indeed, the mods you mentioned don't appear there so you should not have been reminded about them. It is an issue that rears its head every once in a while but we've not been able to reliably reproduce it as of yet.

If it happens again would you mind taking a screenshot?

**Comment by Pickysaurus** [comment]
I can confirm this issue. 

My working theory is that it's not due to a mod you haven't downloaded, but a mod page that has been hidden/deleted since you downloaded it. 

I am getting it myself so hopefully, we'll be able to track down the problem.
