### ISSUE TITLE
Bug in Stardew Valley Expanded 1.12. No Harvey scene at 10 hearts.

### ISSUE THREAD

**Issue by Kaliknita** [Nexus-Mods/web-issues#1254]
## Bug/error being reported:
Bug in the mod Stardew Valley Expanded 1.12.
URL: https://www.nexusmods.com/stardewvalley/mods/3753?tab=description

## Steps to reproduce:
When Harvey has 10 hearts, after he sent you a note asking you to meet in the train station between 9:00 and 17:00.

### Example:
Enter in the area after 9:00

## Expected result:
The cutscene should appear or at least the option to skip it.

## Actual result:
The game freezes. It shows you a scenery of the area but nothing happens and it's impossible to skip.

**Comment by Pickysaurus** [comment]
This tracker is for problems with the Nexus Mods website. Please report this to the mod author.
