### ISSUE TITLE
Hard to check all posts or reply posts

### ISSUE THREAD

**Issue by mahengrui1** [Nexus-Mods/web-issues#1256]
## Bug/error being reported:

Since the forum reply function is banned, hard to reply one.

## Steps to reproduce:

1 open https://forums.nexusmods.com/ click username/ my contents
2 See this member's / only posts
3 open a topic and see who replies me

## Expected result:

click a reply button to reply

## Actual result:

since function closes, and no button to jump back to https://www.nexusmods.com/...?tab=posts so i must search the name of mod again to locate it

Otherwise, don't use https://forums.nexusmods.com/ then i cant see all my posts

**Comment by Pickysaurus** [comment]
This isn't a bug with the site, it is, unfortunately, a limitation of the forum/site integration. The forum knows nothing about mod pages so we can't show a link back to the mod page version of the comment at the moment. 

We may improve this when we come to overhaul commenting across the site.
