### ISSUE TITLE
Buying premium actually made my download speed slower

### ISSUE THREAD

**Issue by masteradasdas** [Nexus-Mods/web-issues#1257]
## Bug/error being reported:
last month I was experiencing slow download speed with premium and didn't subscribed to nexus early this month. Today I decided maybe the problem is solved and I gave it a try. But after downlading some files on non premium and premium I figured out that actually downloading was faster without subscribing.  (my nick is masteradasdas in Nexus too)

## Steps to reproduce:
Have no clue to be honest.

## Expected result:
Being able to use premium faster.

## Actual result:
Premium server connection is slower than non premium.

**Comment by Pickysaurus** [comment]
So that we can help you with this, please see our troubleshooting guide. It includes all the information we need from you and the correct place to post it: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
