### ISSUE TITLE
Vortex Mod Manager Extensions Not Installing

### ISSUE THREAD

**Issue by TheGreatGrump** [Nexus-Mods/web-issues#1258]
The extensions "Gamebryo Ba2 Support"; "Gamebryo Plugin Management"; and "Gamebryo Savegame Management" will not install on Vortex Mod Manager.

Upon installing or reinstalling Vortex (even with all anti virus software turned off) these three extensions will not install. 
All three state they have 'Failed'.
I click on "Gamebryo Plugin Management" to enable
Vortex prompts me to restart
I restart Vortex 
An orange error pops up in the top right stating "Some of the installed extensions couldn't be loaded because they have missing dependencies"
I click 'Fix'
A red error pops up stating "Failed to install extension" 
I click 'More'
A text box appears stating "The extension "gamebryo-plugin-management" wasn't found in the repository. This might mean the extension isn't available on Nexus at all or has been excluded for compatibility reasons. Please check the installation instructions for this extension." 
I close the text box
I check extensions
"Gamebryo Plugin Indexlock" has now failed and "Gamebryo Plugin Management" is now diasbled
I enable "Gamebryo Plugin Management"
Vortex prompts me  to restart
I restart Vortex
"Gamebryo Plugin Management 'Failed' and "Gamebryo Plugin Indexlock has now enabled.

Attached
[Vortex Log.docx](https://github.com/Nexus-Mods/web-issues/files/5758476/Vortex.Log.docx)
 is the log of that description.

**Comment by Pickysaurus** [comment]
Sorry to hear about this issue, please post Vortex related questions here: https://github.com/Nexus-Mods/Vortex/issues
