### ISSUE TITLE
Logout link is too close to profile link.

### ISSUE THREAD

**Issue by heavyoak** [Nexus-Mods/web-issues#126]
look at the old site. logout is in a drop down menu, along with several useful links like user area and profile.

new site has the logout so close to the profile link that you can't click one without clicking on the other.

the other links, missing as far as I can tell. 

its clear that the new site is not meant for desktop users, and its design is not meant for gamers.

no idea who the new site is meant for, but you're going in the wrong direction.

**Comment by rscottexe** [comment]
> new site has the logout so close to the profile link that you can't click one without clicking on the other.

Ermm, the two are definitely far enough apart for you to be able to click between the two. Are you viewing the page at a lower zoom (e.g. less than 100%) or something? I think any "gamer" should be able to not misclick between the "Log out" link and the "profile" avatar button, else they likely shouldn't be gaming! At least nothing multiplayer that might get a teammate killed from misclicking ;)
