### ISSUE TITLE
Blade and Sorcery

### ISSUE THREAD

**Issue by DrTurk** [Nexus-Mods/web-issues#1261]
## Bug/error being reported:
Every time I open Vortex it downloads a file "game-bladeandsorcery_0.2.2.7z" 
Is this a bug? How do I stop this from happening?  I do not want this. I have been a premium member for years and this did NOT used to happen.  Is it time to use a different mod manager?

## Steps to reproduce:
Open Vortex

## Expected result:
No unwanted downloaded files

## Actual result:
This same file shows up every time I open Vortex

**Comment by Pickysaurus** [comment]
This tracker is for issues with the Nexus Mods website. Vortex has it's own issue page here: https://github.com/Nexus-Mods/Vortex/issues

What you are seeing is an automatic update of a built-in element of Vortex, however, it seems to be failing to install for some reason. You can ignore the file it downloads without any issues or you can look in your %appdata%/vortex/plugins folder and delete the Blade and Sorcery folder there. Next time you restart it should download one final time and install correctly. If that fails please open a ticket on the Vortex page or our support forum.
