### ISSUE TITLE
Unable to Upload images to my mod, as a result I cannot publish it.

### ISSUE THREAD

**Issue by worldsprayer** [Nexus-Mods/web-issues#1263]
URL: https://www.nexusmods.com/mountandblade2bannerlord/mods/edit/?step=media&id=2594
User: Worldsprayer

## Bug/error being reported:
I am attempting to upload images to my mod, both header and base images, and they will not complete upload.
Uploading header simply states 'cannot upload this file"
Uploading images results in an error window that states the following:
www.nexusmods.com says
<html>
<head><title>500 internal server error<title></head>
<body>
<center><h1>500 internal server error <.h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>

## Steps to reproduce:
<!--
Optimally an ordered list with the steps needed to reproduce the bug

1) Create a mod to upload, details and files appear unnecesary
2) drag/drop or click upload in either header or image repository sections
3) select file
4) wait for error

## Expected result:
The file should upload and the mod publishing form should allow publishing

## Actual result:
As the images are rejected, the mod cannot be published

**Comment by romelsalwi** [comment]
Same here!
![image](https://user-images.githubusercontent.com/39900953/103870158-58aceb80-50f1-11eb-92ad-c2951a487a42.png)

**Comment by Pickysaurus** [comment]
This issue should be fixed. Sorry about that!
