### ISSUE TITLE
Uploaded file has not been loaded to servers after 16 hours

### ISSUE THREAD

**Issue by lazworks** [Nexus-Mods/web-issues#1264]
## Bug/error being reported:
I uploaded a file and the status has remained "The file is currently being uploaded to our file servers and it will be ready to be downloaded soon." for the last 16 hours.

## Steps to reproduce:

1. Uploaded file.
2. The file passed the virus check.
3. File is still not available for download.

## Expected result:
I expected the file to be available for download within 10 minutes.

## Actual result:
The file is not available for download after 16 hours.

## Link to the affected mod:
[https://www.nexusmods.com/neverwinter/mods/824?tab=files](url)

**Comment by Pickysaurus** [comment]
Sorry about that, the virus scan got stuck for this file. I've fixed it for you now.
