### ISSUE TITLE
Bug report side for a mod is defect - see screenshots

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1265]
Firefox 84.1
when I goto a mod where I already had made a Bug Report and click visit again times later and click again Bug Report, I see all in long vetical lines and multiple.
Had not been times agao (past year) maybe related to update of Firefox to v.84 ? as this would correspondence with the time since I have this.
Reload (F5) does not help, but if I leave the page and come back immedately, then it's gone and all is normal.
This is from https://www.nexusmods.com/skyrimspecialedition/mods/23316?tab=bugs
![bb](https://user-images.githubusercontent.com/40837496/103810138-00c3a580-505b-11eb-8dd1-ddef563e77ef.jpg)
![aa](https://user-images.githubusercontent.com/40837496/103810145-04572c80-505b-11eb-8b65-3071d6b4e561.jpg)

**Comment by Pickysaurus** [comment]
This does seem to be a Firefox-specific issue. I have not been able to replicate it myself though.

**Comment by AntoniX35** [comment]
Same problem on Google Chrome 88, but I can't reproduce this problem on another computer.
