### ISSUE TITLE
Foreign (Russian) text gets converted to wrong codeset in Private Messages?

### ISSUE THREAD

**Issue by SteveBotter** [Nexus-Mods/web-issues#1266]
Username on the Nexus: Steve64b
Bug/error being reported: Possibly (Russian) character codeset issues in the Conversation/Private Messages module?
Expected result: readable/translatable message in private messages
Actual result: Incoherent garbled text

Steps to reproduce: An admin may want to check the posts at [topicID=4195048](https://forums.nexusmods.com/index.php?app=members&module=messaging&section=view&do=showConversation&topicID=4195048), I suspect either the user vit**** submitted data in a different codeset, or something is going wrong in storing the data in the database.

**Comment by Pickysaurus** [comment]
Russian characters are not currently supported by the Encoding using on the IPBoard forum (which powers PMs and comments). We are aware of this and as we slowly migrate parts of the site away from using the forum they will have a wider range of supported characters. For example, mod pages currently support most language characters.

**Comment by SteveBotter** [comment]
Alright, thanks for the quick feedback! Glad I could see their comments on the mod posts section, good luck the migrating parts! :)
