### ISSUE TITLE
Mods not showing up in Tracking Centre

### ISSUE THREAD

**Issue by boyer92** [Nexus-Mods/web-issues#1267]
## Bug/error being reported:
Mods not showing up in the Tracking Centre. I just bought premium and then afterwards no mods are showing up. No ad block program is installed and javascript is enabled. Please help me

[Screenshot (5)](https://user-images.githubusercontent.com/77175133/104069269-0dffa200-51cb-11eb-9539-59588de033ad.png)

## Steps to reproduce
N/A

## Expected result:
 Looking at my tracked mods

## Actual result:
No mods are showing up

**Comment by boyer92** [comment]
Fixed it! You have to click on the items showing drop down menu and switch to 60 items!

**Comment by Pickysaurus** [comment]
https://forums.nexusmods.com/index.php?/topic/9494273-no-tracked-mods-in-tracking-centre/#entry88964298
