### ISSUE TITLE
updates shows a number, but nothing is there.

### ISSUE THREAD

**Issue by heavyoak** [Nexus-Mods/web-issues#127]
![fireshot capture 034 - swordsman s assortment at skyri_ - https___rd nexusmods com_skyrim_mods_86988](https://user-images.githubusercontent.com/6599392/31171848-d33cf704-a8c6-11e7-8aa6-5da3ccb4ca42.png)

also, what is the point of this? it wasn't on the original site and I don't see what it's to do.

**Comment by Rrrafau** [comment]
assigned #151676086

**Comment by iamtiz** [comment]
Duplicate of #113

**Comment by iamtiz** [comment]
This should now be fixed
