### ISSUE TITLE
Attempting to renew a premium subscription or cancel an invoice will result in a timeout

### ISSUE THREAD

**Issue by Scaranman** [Nexus-Mods/web-issues#1272]
## Bug/error being reported:

When attempting to renew a premium membership subscription or cancel an invoice, the page will load until it times out

## Steps to reproduce:

1. Go to Client Area
2. Go to Purchases
3. Select an expired subscription
4. Select "Renew"
5. Select "Renew Now"

or

1. Go to Client Area
2. Go to Invoices
3. Select an invoice
4. Select either "cancel" or "pay"

or

1. Go to Client Area
2. Go to Invoices
3. Select "pay" on an invoice

## Expected result:
The invoice will be canceled or you will be brought to the renewal options page

## Actual result:
The page will load until it times out

## Additional Information

- I have attempted this on both Firefox and Chrome
- I found the following error messages in console on both browsers:

```
index.php?app=nexus&module=clients&section=invoices:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://code.jquery.com/jquery-3.3.1.min.js' with computed SHA-256 integrity 'FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8='. The resource has been blocked.

Platform.js:2 Uncaught ReferenceError: jQuery is not defined
    at Platform.js:2

skinbox.js:1 Uncaught ReferenceError: jQuery is not defined
    at skinbox.js:1
```

**Comment by Pickysaurus** [comment]
After checking with our web team, this error is caused by something on your end blocking jQuery. Usually privacy-related browser extensions. 
https://help.nexusmods.com/article/113-troubleshooting-website-issues

Thanks for your interest in supporting the site!
