### ISSUE TITLE
Hidden status not consistent

### ISSUE THREAD

**Issue by Bladehawke** [Nexus-Mods/web-issues#1273]
## Bug/error being reported:
A mod set to hidden may be hidden at the URL but shows up in "My Mods" as Visible

## Steps to reproduce:
1. Create a basic mod
2. Set the mod to hidden from the Manage dropdown.
3. Click on your profile pick and select "My Mods"
4. See your mod listed as Visible

## Expected result:
Mod shown as Hidden in both locations

## Actual result:
Mod shows as hidden when I go to its URL, but the visible radio button is ricked in "My Mods"

**Comment by Pickysaurus** [comment]
There is around a 5 minute cache on the website. Once this updates it will display correctly
