### ISSUE TITLE
BitTorrent support for larger mod files?

### ISSUE THREAD

**Issue by mrudat** [Nexus-Mods/web-issues#1274]
It seems like it might be useful to add (possibly optional) BitTorrent support for some of the larger mod files, specifically with the [Web Seeding](https://en.wikipedia.org/wiki/BitTorrent#Web_seeding) feature enabled.

I'm somewhat surprised that there isn't an issue where this has been discussed and possibly dismissed for pretty good reasons.

**Comment by Pickysaurus** [comment]
We did look at this as an option a long time ago, however, there were a number of concerns with this method (not least security). It's not something we're planning to implement going forward. We have, however, just launched a only Premium CDN which may help with this:  https://www.nexusmods.com/news/14463
