### ISSUE TITLE
2FA - QR code problems

### ISSUE THREAD

**Issue by Mochito35** [Nexus-Mods/web-issues#1277]
## Bug/error being reported:
When trying to verify 2FA on NexusMods on Opera browser, the QR code does not work, whilst the manual code works fine.
## Expected result:
Successful verification through both QR code and manual code in a two-step verification app, depending on which option I choose.
## Actual result:
2FA only works when added as a manual code in a two-step verification app.
## Hardware and software used:
Opera version 73.0.3856.344 - Windows 10
Android 9 - EMUI 9.1.0
Google Authenticator -> Aegis verification app
## What happened:
This situation happened when I was switching from one verification app to another - neither of the codes worked (while being identical), until I manually changed the 2FA code.

I am not a technician of any kind but I would expect the QR code and manual code to be identical.

**Comment by Pickysaurus** [comment]
I tested this system fairly extensively last week (based on an unrelated report). The QR code works correctly. If you're having problems I suspect it's an issue with whatever you're using to read the code.

**Comment by Mochito35** [comment]
Interesting, so you think that the Aegis verification app is the one doing the problem? Well I think that is unlikely since I added a few other accounts and it worked with QR codes just fine. NexusMods was the only troublemaker so I thought that was the root of the problem.

I will check the Aegis app GitHub and see if there are any issues reported with QR codes.

**Comment by Mochito35** [comment]
I just checked the Aegis issues tab and only thing I could find about QR code was this recent bug: https://github.com/beemdevelopment/Aegis/issues/657  which does not describe the problem I found. 

Issue in that post is with the Aegis app not registering the QR code - on my end the app registered the code just fine but **NexusMods didn't accept the code as the right one** which is definetly wrong since as I said before I was switching from one app to the other and **both apps had the same identical code at the same time**. Also the apps were correctly synchronized.

**Comment by Pickysaurus** [comment]
It may not be the app directly but I have had a problem with Discord from time-to-time where pointing my phone camera at the QR code just did not work. As I said though, I recently tested this pretty heavily and added/removed my 2FA around 10-15 times using my phone camera to scan the QR code each time.

**Comment by Mochito35** [comment]
I understand thought that does not answer the question as to why it would suddenly stop working properly. But, since noone so far except me reported on the issue, I guess it was a random bug occurence or some other problem that currently can not be directly linked to NexusMods.

**Comment by Pickysaurus** [comment]
I have re-tested 2FA today and could not find any significant issues. I'm going to mark this as closed for now.
