### ISSUE TITLE
Inconsistencies in Mod Search vs Mod Page

### ISSUE THREAD

**Issue by romelsalwi** [Nexus-Mods/web-issues#1278]
This is the info it shows me when I see through "my mod" page (300, 240 endorsements):
![image](https://user-images.githubusercontent.com/39900953/105611712-de60b480-5ddc-11eb-97fa-f28161480578.png)

This is the info it shows up when I see my profile and while browsing mods (234, 216 endorsements):
![image](https://user-images.githubusercontent.com/39900953/105611737-11a34380-5ddd-11eb-8c60-06e537e8ba36.png)

![image](https://user-images.githubusercontent.com/39900953/105611757-37c8e380-5ddd-11eb-93e9-1e5fa9436a73.png)

**Comment by romelsalwi** [comment]
Here's more:
On description page:
![image](https://user-images.githubusercontent.com/39900953/105627118-b7e15e80-5e5a-11eb-8349-b75a0458a665.png)

On Browsing:
![image](https://user-images.githubusercontent.com/39900953/105627131-ce87b580-5e5a-11eb-9693-bb8b3eee1161.png)

**Comment by Pickysaurus** [comment]
We are currently testing a new "back end" to the mod search. While this is ongoing there may be inconsistencies in the results.

**Comment by Pickysaurus** [comment]
This issue should now be solved. Please be aware that mod search results may be cached for up to 10 minutes so the counts may be slightly behind.
