### ISSUE TITLE
Some form fields are inaccessible with tabbing

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#128]
Pressing `TAB` to navigate through forms skips over some fields and buttons, which decreases accessibility and flow.

### Example
The manage-files checkboxes and upload form aren't accessible without a mouse:
> ![image](https://user-images.githubusercontent.com/230581/31186459-b3d2f00e-a8fc-11e7-99b6-8c2c61d7c4d9.png)

### Proposed solution
* Some of the buttons use `<button>` (like save/next) and others use `<div>` (like the browse-files button). Using `<button>` consistently should fix it for buttons.
* The checkboxes use a `<div>` to fake the checkbox, but it's possible to [make those keyboard-accessible](https://medium.com/claritydesignsystem/pure-css-accessible-checkboxes-and-radios-buttons-54063e759bb3).

**Comment by iamtiz** [comment]
assigned #155027030

**Comment by iamtiz** [comment]
fixed (let us know if you find any non-accessible button or control)
