### ISSUE TITLE
Blank Bug Report on Bugs Page After Newest Reply

### ISSUE THREAD

**Issue by Acerbicon** [Nexus-Mods/web-issues#1281]
## Bug/error being reported:
When I went to look at a response to a _specific_ bug report, opening said bug report just reveals a blank form. Once I open this particular bug report, all other bug reports also do this.

## Steps to reproduce:
1. Going to [https://www.nexusmods.com/stardewvalley/mods/988?tab=bugs](url)
2. Opening the second Bug down, entitled "Texture issues/Possible Conflicts?"
3. Bug happens.

## Expected result:
Being able to read the bug report and replies.

## Actual result:
A blank bug report along with all other bug reports becoming blank.

**Comment by Pickysaurus** [comment]
I've fixed the issue you reported. One of the comments included an image which was directly pasted into the report. We don't support this and actively block it. However, paranoid browsers (like Firefox) seem to have was to circumvent our restriction and break the page as a result. We are investigating a better way to control this behaviour.

**Comment by Pickysaurus** [comment]
Related: #1260
