### ISSUE TITLE
Brave Browser issue with View Images

### ISSUE THREAD

**Issue by Sorbe** [Nexus-Mods/web-issues#1282]
## Bug/error being reported:
When viewing images for a mod, Brave will show the image if you move FORWARD through them with the right arrow/clicking.
If you move BACKWARD through the images, they will be shown further and further to the left on the page until you can barely see the images.

**Note: I cannot tell if this is a Brave browser bug or a Nexusmod site coding bug!**

## Steps to reproduce:
1. Open NexusMods.com
2. Pick an SSE mod and goto the mod page
3. Click in the images tab (the more images the better)
4. Click on one of the images to show it at full size
5. Click on the left arrow or use the left arrow on the keyboard

## Expected result:
I would expect the images to load and display correctly regardless of left or right clicking

## Actual result:
Images are rendered increasingly offset to the left as you click on the left arrow.

**Comment by Pickysaurus** [comment]
Can you include a screenshot to illustrate your issue?

I suspect it's a Firefox/Brave problem as I don't see any issues in Chrome.

**Comment by Sorbe** [comment]
![Uploading image.png…]()

**Comment by Sorbe** [comment]
It also seems like it happens sooner if the images are not already loaded.

**Comment by Pickysaurus** [comment]
Thanks for the screenshot, I definitely can't replicate that. Are you able to temporarily disable your browser addons and see if it happens then? I've asked one of our team who uses Brave to try it out too.

**Comment by Sorbe** [comment]
![image](https://user-images.githubusercontent.com/7958470/106469121-b9f77e80-6453-11eb-9ad6-5c8ff68c6e16.png)

More repro info: Find a "new mod" that you haven't looked at the image for yet so none are loaded.   Open the first image, minimize the mod thumbnails, use arrow keys to rapidly move left to to the not yet loaded images.  Soon, the unloaded images (black to start) seem to cause this problem even after they are loaded.

**Comment by Sorbe** [comment]
The above screenshot was done with ALL Brave extension disabled.

**Comment by Sorbe** [comment]
Note also, that even though I initially "minimized" the thumbnails before I used left arrows, that the thumbnails are back, without any user action.

**Comment by Sorbe** [comment]
![image](https://user-images.githubusercontent.com/7958470/106470033-e5c73400-6454-11eb-9334-2174c3f2e686.png)
Here a mod with a lot of images where it was still trying to load one.

**Comment by Sorbe** [comment]
One other observation, the -> graphic is still active like this, even though it's also drawn off center.

**Comment by Sorbe** [comment]
It's definitely triggered by hiding the "thumbnails" using the [:::] button on the left, and then using the "left arrow".

**Comment by Sorbe** [comment]
No repro in Microsoft Edge so far.  Five minutes of testing.

**Comment by Pickysaurus** [comment]
Thanks for that. I've had our developer who runs Brave on Linux try this and it didn't happen with him. So it's either something related to the Windows version or a combination of browser addons/privacy settings.

**Comment by Sorbe** [comment]
One other minor observation, when this happens in Brave not only do the image "thumbnails" return at the bottom of the image view page, but when you press left arrow, the thumbnails not quite drawn at the correct vertical location AND the thumbnail "minimize" button "[:::]" is missing.  It's like the browser still thinks the "image" thumbnails should be hidden, but they are shown.
