### ISSUE TITLE
Webpage showing moblie version on PC

### ISSUE THREAD

**Issue by Kuurz** [Nexus-Mods/web-issues#1283]
## Bug/error being reported:
The bug is on the main website, where the site is scaled for mobile screens.
The issue is that i am on PC and the website now looks like a page for the visually impaired. (Please view screenshot)

## Steps to reproduce:
Go to https://www.nexusmods.com/
[scaling issue]
Try logging in
[Still scaling issue]

## Expected result:
The webpage should be scaled to my screen. Which would be for my instance 1920x1080 or 16:9.

## Actual result:
The webpage is scaled to 9:16 moblie aspect ratio.

![why is it like this](https://user-images.githubusercontent.com/29149120/106343547-3cdad680-62a6-11eb-86ae-8a4f597d09fc.PNG)
![makes no sense](https://user-images.githubusercontent.com/29149120/106343610-7b709100-62a6-11eb-95c8-3a3d1d8a7695.PNG)

When I press F12 the site seems to think my browser is on mobile. I can rescale the site but it's only a resize, not an actual fix.
![website seems to think my pc is on mobile](https://user-images.githubusercontent.com/29149120/106343769-53cdf880-62a7-11eb-8252-cd7b6da7b3c2.PNG)

**Comment by themagickoala** [comment]
It looks like you've zoomed into the page. Click the zoom icon in the address bar to reset it.

![image](https://user-images.githubusercontent.com/48416253/106347919-1b83e580-62ba-11eb-99b2-7ef56450a43a.jpeg)
