### ISSUE TITLE
jump_to_comment doesn't work if the comment is in the forum tab

### ISSUE THREAD

**Issue by taggartaa** [Nexus-Mods/web-issues#1284]
## Bug/error being reported:
When clicking on a comment in the notification bar that was made on a topic in the forum tab, it does not put the correct url params to navigate to that forum comment.

## Steps to reproduce:
1. Click on a notification for a comment made to a forum topic.
2. Get redirected to the the wrong tab.

## Expected result:
Should go to the forum tab and navigate to the post (within the topic) from the notification. Something like this url:
https://www.nexusmods.com/stardewvalley/mods/1019/?tab=forum&topic_id=9577763&jump_to_comment=89971958

This is separate issue than https://github.com/Nexus-Mods/web-issues/issues/1139, but I suspect that bug would also reproduce with the above link.

## Actual result:
It goes to the posts tab:
https://www.nexusmods.com/stardewvalley/mods/1019/?tab=posts&jump_to_comment=89971958

**Comment by Pickysaurus** [comment]
This issue will not be fixed in the current system, but the new comments system (WIP) will include permalinks to comments to remedy this.
