### ISSUE TITLE
Some mods show don't show up on PC browser but do show on mobile.

### ISSUE THREAD

**Issue by soundsofsilence** [Nexus-Mods/web-issues#1286]
## Bug/error being reported:
I recently noticed that many mods (mainly ones that had been downloaded before and have a newer version out) don't show up in my desktop browser but show up in my phone's browser.

## Steps to reproduce:
not sure

## Expected result:
https://i.ibb.co/0jhVn85/Screenshot-20210131-180921-Edge.jpg

## Actual result:
https://i.ibb.co/TbL8mM5/Screenshot-2021-01-31-181001.jpg

**Comment by Pickysaurus** [comment]
Related to #1278
