### ISSUE TITLE
Slow Manual Download Button Doesn't Work (Firefox,Chrome,Chromium)

### ISSUE THREAD

**Issue by Peremious** [Nexus-Mods/web-issues#1288]
URL: Any mod on Nexus

Username on the Nexus: Peremos

Bug/error being reported:
When clicking download "Slow Download", nothing will happen. No pop up, no download, nothing

Steps to reproduce:
1. Be on Firefox, Chrome, or Chromium
2. Select a mod on nexus to download
3. click slow download

Expected result: The mod downloads

Actual result: Nothing happens at all
![Screenshot from 2021-02-03 01-24-05](https://user-images.githubusercontent.com/43022063/106712416-88e78d00-65be-11eb-9208-3c1bb4d29f81.png)

**Comment by Pickysaurus** [comment]
This issue is most likely related to your browser addons or privacy settings, please see our help page here: https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by Peremious** [comment]
> This issue is most likely related to your browser addons or privacy settings, please see our help page here: https://help.nexusmods.com/article/113-troubleshooting-website-issues

I have tried without addons, changing browsers entirely, using a different pc. None of those worked.
