### ISSUE TITLE
Mod page doesn't change/update after download

### ISSUE THREAD

**Issue by AIeskander** [Nexus-Mods/web-issues#1289]
## Expected result:
Mod page will show "Downloaded" outside. Redownloading from a mod page changes "Update Available" to "Downloaded". File downloaded from the page under the files tab shows a small blue symbol that it was downloaded.

## Actual result:
None of the above Expected happens.

**Comment by Pickysaurus** [comment]
We're currently doing some behind the scenes work on the download history, this will correct itself once we're done.

**Comment by Pickysaurus** [comment]
This should now be resolved.
