### ISSUE TITLE
Show some basic file detail on the collapsed title

### ISSUE THREAD

**Issue by rshackleton** [Nexus-Mods/web-issues#129]
It would be nice to see the file version on the file accordion title, it would help when scanning for a file where the mod author hasn't specified the version in the file name.

https://rd.nexusmods.com/skyrimspecialedition/mods/12604?tab=files

![image](https://user-images.githubusercontent.com/13448395/31200739-0c102adc-a954-11e7-9ea6-874b472ac21e.png)

**Comment by iamtiz** [comment]
Done
