### ISSUE TITLE
Feature Request: Ability to set a desired language

### ISSUE THREAD

**Issue by chillcat222** [Nexus-Mods/web-issues#1290]
## Bug/error being reported:

Something to function exactly like the language selector in the "Refine Results" drop down menu, but persistent so you don't have to select your language from the drop down every single time. This would be very helpful since result are always cluttered with translations for languages you may not speak, but you can't block the tag "Translations" since there are quite a few great mods that are in English but have the "Translation" tag because they are translated into English or have their own translations included.

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/249/allow-users-to-select-which-languages-they-want-to-see
