### ISSUE TITLE
New Mod not showing up in "New Today" or "Updated" 

### ISSUE THREAD

**Issue by mrfox** [Nexus-Mods/web-issues#1291]
## Bug/error being reported:
Mod does not show up in "New Today" (https://www.nexusmods.com/cyberpunk2077?tab=new+today) or  "Updated" (https://www.nexusmods.com/cyberpunk2077?tab=updated). It does show up in "New this week" (https://www.nexusmods.com/cyberpunk2077?tab=new+this+week)

This is the mod in question: https://www.nexusmods.com/cyberpunk2077/mods/1467

I had published it once and encountered the error so I deleted the mod (I waited around 12 hours). Now I have published it again (original deleted) and still encounter same error.

Sometimes it shows up other times it doesn't. 

These images have the same URL: https://www.nexusmods.com/cyberpunk2077?tab=new+today
[Here it shows up](https://i.imgur.com/6w4z6z9.jpg)
[Here it doesn't](https://i.imgur.com/2q57YzR.jpg)

**Edit: 15minutes later**
Welp... nevermind looks like it's working now.
[Now it's showing up](https://i.imgur.com/czZccUZ.jpg)

**Comment by chrisharrison** [comment]
We've been having deploying a new system for listing mods over the last week or so. This has caused these synchronisation issues. We think updates should reflect much more quickly now.

If you have this problem again, please let us know.

**Comment by stronny** [comment]
Hello, I have a similar problem. This is my mod that I've published some 20-30 minutes ago. Not only does it not show up anywhere, I'm also unable to download the file from MO2 (forbidden). The mod is here: https://www.nexusmods.com/fallout4/mods/49936
