### ISSUE TITLE
Uploaded a new mod enb but i still can't see it on my mods page or in skyrim new mods page.

### ISSUE THREAD

**Issue by godsp33d6** [Nexus-Mods/web-issues#1292]
## Bug/error being reported:
Uploaded a new mod enb but i still can't see it on my mods page or in skyrim new mods page.

## Expected result:
I expect new mod uploaded appear already on skyrim page it still show i have 26 mods.Before i uploaded the enb mod i had 25 mods with new mod uploaded it count i have 26 mods but still don't appear.

**Comment by godsp33d6** [comment]
With the  new mod i have 26 mods uploaded but it still don't appear on my mods page or skyrim page mods.
![image](https://user-images.githubusercontent.com/77836060/107155480-78704300-692d-11eb-8e43-44a1435a201d.png)

**Comment by Bpendragon** [comment]
Similar issue here. Uploaded a Stardew Valley mod at ~20:00 PST 2021-02-06, as of ~11:00 PST 2021-02-07 (15 hours) it is not showing up in the new queue or search on the Stardew Valley page. [affected mod](https://www.nexusmods.com/stardewvalley/mods/7985). There are also reports of items taking several hours to appear in the SDV discord or not appearing at all. 

It feels like the indexing service took an unplanned vacation.

**Comment by godsp33d6** [comment]
EDIT: I can see my mod and link ONLY IF I CLICK ON MY PROFILE AND MY MODS LIKE ON THIS IMAGE WILL APPEAR VISIBLE FOR ME LOL.
![image](https://user-images.githubusercontent.com/77836060/107157770-d6efee00-693a-11eb-8af6-28999c200961.png)

**Comment by weds4** [comment]
Same issue for this mod 
https://www.nexusmods.com/skyrimspecialedition/mods/45326
it's been published for nearly 24 hours

**Comment by godsp33d6** [comment]
Hide the mod for being visible and set again to visible it fix the issue.Temporary solution.

**Comment by Pickysaurus** [comment]
This is related to #1278 - We are working on a fix. As a workaround, edit your mod description (add or remove a space) and click save. It should get indexed by the search shortly after.

**Comment by Bpendragon** [comment]
> This is related to #1278 - We are working on a fix. As a workaround, edit your mod description (add or remove a space) and click save. It should get indexed by the search shortly after.

Thanks, this at least got mine to appears in the  search bar for me. Still not showing up in new, but that's a slightly lesser issue than people being unable to find it at all.

**Comment by godsp33d6** [comment]
SET mod to hidden then visible again will make appear in queue.
