### ISSUE TITLE
Apparent File Corruption in all CDN/Servers

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/web-issues#1294]
## Bug/error being reported:
I last downloaded this file on Dec 13th, 2020, and at that time the file extracted and worked just fine. However, today, if you download the file you will see that the downloaded hash has changed, and that the file is now corrupt. The TOC is fine, but if you tell 7zip to extract the entire archive it will throw errors for several of the files it attempts to extract. The file downloaded on the 13th does not have these issues. 

Game: Skyrim Special Edition
ModID: 26270
FileID: 123694

```
MD5 from Dec 13th (good file) : 4E037E0C1CA963B94029A8C509ABD6F7
MD5 today (bad file) :          4331C0220356DE289DFEFC0A5167B899
```

I tried using : `https://app.swaggerhub.com/apis-docs/NexusMods/nexus-mods_public_api_params_in_form_data/1.0#/Mods/get_v1_games_game_domain_name_mods_md5_search_md5_hash.json` to search for these MD5, and they always returned a not found result. 

I also tried looking at the MD5 of the file via `mods/26270/files.json` and that result didn't return a md5 for any of the files. 

If it helps at all, about 3 of my users have hashed their already downloaded copies of this file and they match what I downloaded on the 13th. However our newly downloaded copies don't always match for some reason.

## Steps to reproduce:
* Find a older copy of the above file
* Download a new copy
* Compare the files by hash or contents

## Expected result:
That files don't go corrupt or change after they're uploaded

## Actual result:
File is not extractable, and the downloaded hash doesn't match a previous hash of the file.

**Comment by Pickysaurus** [comment]
Confirmed here

**Comment by Pickysaurus** [comment]
This ticket didn't get updated (sorry about that!), however, MrMason was not able to replicate the issue when he tried.

**Comment by mrmason** [comment]
I've checked every single server we've got with a copy of this file and they're all the same MD5

```
4e037e0c1ca963b94029a8c509abd6f7  Blended Roads Redone 2K-26270-1-4-1581453882.7z
```

My only guess here is that we had a cache problem at the time and that file was somehow corrupted.
