### ISSUE TITLE
Private message code page

### ISSUE THREAD

**Issue by Bxaa** [Nexus-Mods/web-issues#1295]
**Forum private message**
No support utf-8 or win1251? 
Example: russian or other cyrillic not correct work in private forum message.
<a href="https://ibb.co/dcZ8sKQ"><img src="https://i.ibb.co/mBpfrzH/image.jpg" alt="image" border="0"></a>
Do you have a plan to fix it? This is critical annoying bug!

**Comment by Pickysaurus** [comment]
This is a limitation of the character set in use by the IPBoard forum that powers PMs. We are slowly migrating away from this old system. Anything new we build will usually have full character support.

**Comment by Bxaa** [comment]
Five years ago i don't have a some trouble :)
All new is just forgetted old  :)
Thanks for response. And thanks for nexus!

**Comment by Pickysaurus** [comment]
No worries. I'm going to mark this as closed but don't worry, it's not something we're likely to overlook :)
