### ISSUE TITLE
File Server DNS Down

### ISSUE THREAD

**Issue by EzequielDM** [Nexus-Mods/web-issues#1296]
## Bug/error being reported:
When trying to download mods you receive a CloudFlare warning saying there was an error on the Origin DNS meaning it can't resolve cf-files.nexusmods.com.

## Steps to reproduce:
Just try to download any files.

## Expected result:
It was expected for the download to start...

## Actual result:
but it doesn't.

![image](https://user-images.githubusercontent.com/17010688/107833528-541fc680-6d72-11eb-8dc3-d7e7e3c5d535.png)

**Comment by EzequielDM** [comment]
You also receive an error message while trying to use Vortex.
![image](https://user-images.githubusercontent.com/17010688/107833563-744f8580-6d72-11eb-81bf-118c25f37382.png)

**Comment by mrmason** [comment]
Thanks for the report - We're aware of this - it's a problem with one of our suppliers - hopefully it will be resolved soon.

**Comment by EzequielDM** [comment]
Perfect!

**Comment by mrmason** [comment]
This should have all been sorted out last night.
