### ISSUE TITLE
Pages loading logged out

### ISSUE THREAD

**Issue by Gh0sTG0** [Nexus-Mods/web-issues#1297]
URL: any, https://www.nexusmods.com/skyrimspecialedition/mods/42102 for example
Username on the Nexus: Gh0sTG0

Bug/error being reported: I have my modlist as a list of bookmarks in my browser. Now I'm trying to check them for updated descriptions, new Requirements, etc. I'm opening them by 10+- bookmarks a time. On 2-3 open it starts loading pages with me as I'm logged out of nexus. After I log in it will be logged in for another 20-30 pages.

Steps to reproduce:
1) Log in on nexus;
2) Have 100+ mods bookmarked in your browser;
3) Open 10+ of them with one click (first-shift-last-enter);
4) Scroll through pages, checking them for changes, closing checked;
5) Open another 10+ bookmarks;
6) Now or on next 10+ bookmarks see that Nexus loads them logged out (all that "adult" things, etc)

Expected result: Nexus loads me pages logged in untill I press Log Out or Clear Cookies, or etc.
Actual result: Nexus loads me pages logged out so I need to relogin every 20-30 mods.

Upd: Without doing something. Just checked over 100 mods without logging out.

Upd2: One more logout in some hours.

**Comment by Gh0sTG0** [comment]
Ok. Don't know why, but no logouts more for me... I'll close this tomorrow if no more starts

**Comment by Pickysaurus** [comment]
Thanks for the report, we're looking into it.

**Comment by Pickysaurus** [comment]
This issue should be resolved, feel free to reopen the issue if it persists.
