### ISSUE TITLE
Origin DNS error

### ISSUE THREAD

**Issue by loulou2444** [Nexus-Mods/web-issues#1298]
I have some trouble to download mods 
mod : http://www.nexusmods.com/fallout4/mods/10816/

when I try , I get 

Error 1016
Origin DNS error

**Comment by liam-87** [comment]
Having similar problems. Can't download any files.

**Comment by Agent042s** [comment]
Same with the mod : https://www.nexusmods.com/fallout4/mods/37794?tab=files&file_id=177318
Vortex download failed and manual showed 1016 Origin DNS error.

For Admins: You need to manually reconnect theese sites. It can be residual from the crash of February 12th. If more mods shows the same error in next 60 minutes, it can be another big cloudflare crash.

**Comment by liam-87** [comment]
Yea. I've tried several different files for several different games, both mod manager and direct download. None work.

**Comment by deliluhh** [comment]
Receiving the same error on https://www.nexusmods.com/cubeworld/mods/7?tab=files

**Comment by Ryzio270** [comment]
Same here, [this](https://www.nexusmods.com/skyrimspecialedition/mods/22551?tab=files) and [this](https://www.nexusmods.com/skyrimspecialedition/mods/20684?tab=files ) don't work

**Comment by mrmason** [comment]
Thanks guys, we're aware of this - it's a problem caused by a file host we're using - https://twitter.com/backblaze - they've had their domain suspended by GoDaddy. This happened to them before and it took a few hours to resolve.

**Comment by Agent042s** [comment]
> Thanks guys, we're aware of this - it's a problem caused by a file host we're using - https://twitter.com/backblaze - they've had their domain suspended by GoDaddy. This happened to them before and it took a few hours to resolve.

Ok. Thanks for support.

**Comment by liam-87** [comment]
I'm able to download again!

**Comment by loulou2444** [comment]
same here , the temporary fix work
