### ISSUE TITLE
Opening updates in a new tab (RMB or MMB) keeps them active

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#13]
On the old site, clicking the notifications button flagged all current notifications as viewed, but on the new design you need to actually click for them to be flagged and greyed out.

This works, but not when you use the middle mouse button to open the update entries in a new tab instead of normally clicking on them. I don't know if this can be intercepted with JavaScript events, probably can.

**Comment by mrmason** [comment]
Assigned `PT#150668723`

**Comment by mrmason** [comment]
This should be fixed.
