### ISSUE TITLE
After using the file description editor, and then clicking save down slash characters are stripped out

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#130]
After using the file description editor, and then clicking save down slash characters are stripped out

So ..
 
textures \ actors \ character \ female \ femalebody_1.dds
 
becomes ..
 
textures actors character female femalebody_1.dds

How can we describe file paths with this editor behaviour ?

Using the old page editor I can put them back in again successfully, but the new page editor will do the same thing every time.

**Comment by Rrrafau** [comment]
assigned #151712202

**Comment by verenion** [comment]
Fix has been pushed
