### ISSUE TITLE
Mod won't upload after 3 hours

### ISSUE THREAD

**Issue by kogex56** [Nexus-Mods/web-issues#1300]
**The Phoenix Flavour - Conflict Resolution Patch** and **The Phoenix Flavour - Universal Loadorder TXT** were uploaded almost 3 hours ago and still are not available.

Username on the Nexus: **kogex56**
Bug/error being reported: **mod will not upload**
Steps to reproduce: **N/A**
Expected result: **mod available**
Actual result: **mod still not uploaded after almost 3 hours**
Link to the affected mod/image (if relevant): https://www.nexusmods.com/skyrimspecialedition/mods/14223?tab=files
![image](https://user-images.githubusercontent.com/51246373/108273465-9c0f6680-7141-11eb-84f0-7ee93478d6b3.png)

**Comment by mrmason** [comment]
Sorry, this was the same problem as #1299 and #1298

I've manually pushed you file for you now so it should be working.
