### ISSUE TITLE
Mod files download failure

### ISSUE THREAD

**Issue by LionHead8812** [Nexus-Mods/web-issues#1301]
## Bug/error being reported:
Mod files from "free download" link fail to start downloading. 

## Steps to reproduce:
Choose mod, choose files and select free download. Page will load and then return with "connection refused" on 'supporter-files.nexus-cdn. Reloading the page doesn't solve the issue.
![Opera 快照_2021-02-18_102207_supporter-files nexus-cdn com](https://user-images.githubusercontent.com/79237216/108296412-754e4000-71d4-11eb-8c57-645b0f03823b.png)
![Opera 快照_2021-02-18_103017_supporter-files nexus-cdn com](https://user-images.githubusercontent.com/79237216/108296424-7b442100-71d4-11eb-86e2-0d0a20f85a19.png)

I have also tried Nexus on Edge with the same result. 
## Expected result:
For the selected file to start downloading

## Actual result:
Page results in error.

**Comment by Pickysaurus** [comment]
I can't replicate this, so it must be something on your end. Please see the help article below for possible fixes: 
https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by LionHead8812** [comment]
This actually was occuring yesterday when you were having the CDN issues. I send a trouble ticket to inform you of the situation.

I think though there are some things causing the slow and sometimes failing downloads. Although I can access Nexus in China, I think the GFW isn't helping matters. They are known to slow down external traffic in favour of domestic traffic and it gets progressively worse throughout the day. 

I have to say that today everything seems to be running normally, although after reading the link you sent me I did disable my adblocker for Nexusmods. I'm not able to buy premium just yet so it's the best I can do to help you guys out for now.

**Comment by Pickysaurus** [comment]
Please see: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

We've made a change to our CDN today that may have fixed this issue.
