### ISSUE TITLE
Uploading multiple times with the same filename

### ISSUE THREAD

**Issue by Sidies** [Nexus-Mods/web-issues#1302]
Hey, 
the other day I updated [my mod](https://www.nexusmods.com/mountandblade2bannerlord/mods/688?tab=files) and uploaded the wrong file. I noticed this misstake, deleted the wrong version and uploaded a new one and this time made sure to use the correct file to upload. Well people were still reporting issues even though I was certain this time the correct file has been used. I suspected this issue to be with nexus mods and after some testing found out that even though I uploaded a new file, the old (deleted) file would still be used.

## Bug/error being reported:
When uploading a zip file and then deleting it and uploading a new zip file with the **same name**, the before deleted file is still used when downloading.

## Steps to reproduce:

1. Upload a zip file (a) with a specific name
2. Upload a second file (b) with the **same** name
3. When downloading (b) you get the content of (a) 

## Expected result:
If you download (b) you expect to get the content of (b)

## Actual result:
If you download (b) you get the content of (a)

**Comment by Pickysaurus** [comment]
Yes, you need to use a different file name. The chunks from the uploader are kept on the server for a few days in case anything goes wrong with the file.

**Comment by Sidies** [comment]
Alright if this is intended the report may be closed. :-)
