### ISSUE TITLE
Translation mod don't appear 

### ISSUE THREAD

**Issue by Gothuska** [Nexus-Mods/web-issues#1303]
This translation mod Working Crimson Caravan Traders - Es https://www.nexusmods.com/newvegas/mods/71367/
don't appear in nexus fallout nv page and dont't appear too on my mod page https://www.nexusmods.com/users/42430300?tab=user+files
Thanks

**Comment by Pickysaurus** [comment]
This is a known issue, we're looking into it. To force your mod to be re-indexed by the search, make a small edit to the description and click save.

**Comment by Gothuska** [comment]
Is working, 
Thanks
