### ISSUE TITLE
Unable to Change the Changelog Version Numbers if Version Contains Non-Numeric Chars

### ISSUE THREAD

**Issue by derekShaheen** [Nexus-Mods/web-issues#1305]
## Bug/error being reported:
When entering a change log into the provided rows on this page: https://www.nexusmods.com/valheim/mods/edit/?step=docs&id=X, if you enter letters into the version field, once this has been submitted, it is not possible to modify the version afterward. Normally if I enter "1.3" into the version field, I can then submit and double click "Version 1.3" in the "Manage changelogs" section, and I'm able to change it. If I originally entered "1.3 (Upcoming)" for example, I am not able to modify this under "Manage changelogs".

## Steps to reproduce:

1. Go here: https://www.nexusmods.com/valheim/mods/edit/?step=docs&id=X
2. Add a changelog row with the values - 1.1 | This is a test changelog
3. Add another row with the values 1.2  (Upcoming) | This is a test changelog
4. Press Save
5. Scroll to "Manage Changelogs"
6. Double click "Version 1.1" and change it to "Version 1.0"
7. Double click "Version 1.2 (Upcoming)". This is the error, it does not allow this to be changed.

## Expected result:
I should be able to modify the version with non-numeric characters in it.

## Actual result:
I was unable to make any change.

**Comment by Pickysaurus** [comment]
You shouldn't really be typing "Version" into the version field, otherwise, it shows as "Version Version 2.1". Ideally, your version numbers should be numerical (and semantic). I'll look into this Monday if I remember though.

**Comment by derekShaheen** [comment]
To clarify, I would be typing "1.1" or "1.2 (Upcoming)" in this field, not specifically the word "Version" on top of it. I was referring to what the system shows after saving and looking at it again. If it is not intended for having a (Upcoming) or something like that in the change log, then that was a mistake on my part, and perhaps shouldn't be a feature. Is this something that makes sense logically to include if I want to provide a preview for upcoming features?

**Comment by Pickysaurus** [comment]
Fair enough, thanks for clarifying. Personally, I make the first item under each version header "Release Date: TBC" until that version is actually available to download, then I change it to the date of release.

**Comment by derekShaheen** [comment]
I appreciate the tip! Can you confirm, do you mean like this?
![image](https://user-images.githubusercontent.com/38998433/108557667-8a9f9900-72be-11eb-8dd3-dc3e113aa170.png)
