### ISSUE TITLE
Slow download? Free user

### ISSUE THREAD

**Issue by FallenCorn** [Nexus-Mods/web-issues#1307]
## Bug/error being reported:
It is not a bug or error. It just weird slow download speed. I am totally aware that free users only have capped download speed with 1Mb. But when I tried to download big file mod, like CA Eagle Rising which is 1.4gb. IT TOOK AGES. It's like aroud 30kbps -40kbps. 
Meanwhile, if I download small mod, I don't have the issue. max 1Mb.
My internet is fine, heck I can watch movie with HD and stream it without problem. 

## Expected result:
1Mb speed - 500kbps

## Actual result:
30kbps - 40kbps

**Comment by Pickysaurus** [comment]
Please see our troubleshooting advice here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
