### ISSUE TITLE
Unable to Download Any Mods

### ISSUE THREAD

**Issue by hanigi123** [Nexus-Mods/web-issues#1308]
## Bug/error being reported:
Free download links fail to work . This just started happening today and there weren't any issues a couple of days ago. 
EDIT: It turns out the free download works on some files, but only the small ones, namely under 10mb. Files that go above 100mb can't be downloaded
EDIT 2: I've tested downloading from my mobile device and the same thing happens. Only files under 10mb can be downloaded.

## Steps to reproduce:
Simply download a file manually (that is 100mb or above) from the free download links, or through NMM (I have not tried Vortex). 

I've been able to reproduce it consistently for any mods

Tried this on Edge and Chrome with the same result

## Expected result:
Selected files to download normally

## Actual result:
![SharedScreenshot](https://user-images.githubusercontent.com/79745172/109383737-f87d3d80-791a-11eb-9daf-d5b93d612136.jpg)

![232](https://user-images.githubusercontent.com/79745172/109383753-219dce00-791b-11eb-8d00-1a30599bdd4d.jpg)

Error page from both browsers (haven't tried other browsers, but i'm pretty sure same thing will happen as well) and unable to download in NMM.

**Comment by hanigi123** [comment]
Another update: i'm able to download the files now, but through proxy. This has never been necessary until now.

**Comment by Pickysaurus** [comment]
Please see: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

We've made a change to our CDN today that may have fixed this issue.
