### ISSUE TITLE
Image viewer doesn't always load gifs properly

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#131]
When viewing images via the new image viewer, gifs do not load or play properly unless they have been previously loaded into another tab and then they will play. If you dont do they they remain permanently displaying the first frame of the gif.
Works on my Jks Lite page on Skyrim: https://rd.nexusmods.com/skyrim/mods/71018
Does not work on this dragons dogma mod: https://rd.nexusmods.com/dragonsdogma/mods/97

**Comment by Rrrafau** [comment]
Cannot replicate on my end. Might be the case that the gifs are just very large and take a long time to load.

**Comment by mrmason** [comment]
I can confirm gifs are working on both pages for me on 3 different browsers on OSX ( Firefox / Safari / Chrome ).

If you're still seeing this - can you let us know the exact environment for replicating the issue ?

**Comment by Nazenn** [comment]
Working now for me as well, even though I checked three times over the last two days. No idea whats going on. Sorry for the unneeded report :)
