### ISSUE TITLE
Unable to download Stardew Valley Content Patcher

### ISSUE THREAD

**Issue by Salembb** [Nexus-Mods/web-issues#1310]
## Bug/error being reported:
 I've downloaded SMAPI and once I tried to download the content patcher it didn't allow me to, saying I have to download SMAPI before. Which I already have. I've tried refreshing the page, going on a new page, uninstall SMAPI then reinstalling, and even restarted my computer in hopes it'll work. Yet I'm still unable to download the Content Patcher. Please help.

There should be a section on the pop up that lets you proceed anyway if you've already downloaded the first part.

**Comment by Pickysaurus** [comment]
You just need to press "Download" under the reminder to get SMAPI

**Comment by Salembb** [comment]
Hi, I already downloaded SMAPI, I'm trying to download the next one in order to get mods which is the Content Patcher. But no matter how many times I try to download it I can't because it says I haven't downloaded the SMAPI yet.
    On Saturday, February 27, 2021, 01:09:32 PM CST, Mike <notifications@github.com> wrote:  
 
 


You just need to press "Download" under the reminder to get SMAPI
