### ISSUE TITLE
Bepinex Installs Itself in Subnautica Games

### ISSUE THREAD

**Issue by MellowRebel** [Nexus-Mods/web-issues#1311]
## Bug/error being reported:
I t installs by itself in both Subnautica games. It broke BelowZero. I only installed it into Valheim!!!

## Expected result:
Not to have a broke game!

## Actual result:
Got a broke game!

**Comment by Pickysaurus** [comment]
This bug tracker is for the Nexus Mods website. Vortex bug reports can be submitted in the app itself. However, I have confirmed with the Vortex Team thet BepInEx for Subnautica won't impact Valheim and vice versa.

**Comment by MellowRebel** [comment]
Thing is I never installed it in Subnautica. It installed itself!!!
________________________________

**Comment by Pickysaurus** [comment]
The Subnautica extension is maintained by the community, you can send them feedback through the mod page here: https://www.nexusmods.com/site/mods/202
