### ISSUE TITLE
md5 search not finding some files based on hashes

### ISSUE THREAD

**Issue by dandels** [Nexus-Mods/web-issues#1312]
## Bug/error being reported:
The md5 search API reports "File hash does not exist" for a recently downloaded file even if the hash is correct.

## Steps to reproduce:
1. Download latest version (v2.27.0) of [Imperious - Races of Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/1315)
2. Calculate its md5 hash (25ff38589731e16dcdf9a4fea5a6a93c). 
3. Verify the hash is correct by cross-referencing the virus scan results at [Virustotal](https://www.virustotal.com/gui/file/f0427a3d9f5cc62996d5d9b52ec1bd0e72f491aed93085cb310291a8aacd19b9/details). The Virustotal URL was obtained from the file listing for this mod.
4. `curl -X GET "https://api.nexusmods.com/v1/games/skyrimspecialedition/mods/md5_search/25ff38589731e16dcdf9a4fea5a6a93c.json" -H  "accept: application/json" -H  "apikey: $redacted"`

## Expected result:
A response containing the file details for that file

## Actual result:
```
{
  "code": 404,
  "message": "File hash does not exist"
}
```

**Comment by Pickysaurus** [comment]
I can replicate this issue. I have passed it to the devs on our internal tracker.

**Comment by Pickysaurus** [comment]
We're aware of this issue and are taking steps to improve the data, this specific case should now be resolved.
