### ISSUE TITLE
Mismatch between order and number of endorsements in the Trending Mods 

### ISSUE THREAD

**Issue by LamaKreis** [Nexus-Mods/web-issues#1313]

**Comment by chrisharrison** [comment]
When viewing the 'trending mods' page, what do you have under the 'Sort by' drop-down?

If it's something other than 'Endorsements', does switching it to that field create an order consistent with the number of the endorsements?

**Comment by LamaKreis** [comment]
Oh sorry, it was my mistake. Please excuse me for stealing your time. Sometimes you don't see the simplest thing and feel like a fool. Sorry again.

 

Gesendet: Sonntag, 07. März 2021 um 10:26 Uhr
Von: "Chris Harrison" <notifications@github.com>
An: "Nexus-Mods/web-issues" <web-issues@noreply.github.com>
Cc: "LamaKreis" <jan_alexy@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Nexus-Mods/web-issues] Mismatch between order and number of endorsements in the Trending Mods (#1313)


 

When viewing the 'trending mods' page, what do you have under the 'Sort by' drop-down?

If it's something other than 'Endorsements', does switching it to that field create an order consistent with the number of the endorsements?
