### ISSUE TITLE
Unable to Create New Entries In Mod Changelog

### ISSUE THREAD

**Issue by Sireyn** [Nexus-Mods/web-issues#1314]
## Bug/error being reported:
I am unable to create new entries to the changelog in a mod I manage.

## Steps to reproduce:
I go to my mod's page, then Manage > Documentation, then scroll down to the Add New Changelog box. 

From there, using either Large Text Box or Separate Text Fields options, I add a new line for the latest mod version. 

Selecting the Save option at the bottom or top of the page results in no changes being saved. Selecting an existing line and changing that does work as intended.

**Comment by Pickysaurus** [comment]
Can you include the mod page link you're trying this on? 

Does it fail if you use a version number that already exists or a new version number?

**Comment by Sireyn** [comment]
This mod. It only fails when using a new version number. Editing old numbers works fine.

https://www.nexusmods.com/wargamereddragon/mods/1

**Comment by Sireyn** [comment]
Thanks, can't believe I didn't think to check. Glad it was me being dumb instead of the website at least.
