### ISSUE TITLE
Trojan:Script/Conteban.A!ml / aaMasih Boeing 787Korean_gPX2w.rar

### ISSUE THREAD

**Issue by snajohnwayne** [Nexus-Mods/web-issues#1315]
## Bug/error being reported:

Trojan:Script/Conteban.A!ml

**Comment by Pickysaurus** [comment]
This report lacks all context.

**Comment by snajohnwayne** [comment]
The context is the subject line.

*My Nexus download:* aaMasih Boeing 787Korean_gPX2w.rar
*Contained this malware:*  Trojan:Script/Conteban.A!ml

**Comment by Pickysaurus** [comment]
There's a very high chance it's a false positive, but please link to the mod page you are referring to. 

Every file on the site is virus scanned and the report can be seen by clicking the green tick icon. This is more reliable than any local anti-virus app as it uses over 50 different scanning engines:

![image](https://user-images.githubusercontent.com/31670524/111612569-7ecbc780-87d5-11eb-84f0-d398ac79e0e4.png)
