### ISSUE TITLE
Non-premium download countdown passes in under a second

### ISSUE THREAD

**Issue by Fto0n** [Nexus-Mods/web-issues#1316]
## Bug/error being reported:
The countdown that occurs whenever downloading a mod with a non-premium account goes by rapidly (Couldn't even see the actual)

## Steps to reproduce:
Download any mod through vortex off the site. I was trying to download [this](https://www.nexusmods.com/fallout4/mods/20300?tab=files&file_id=109788&nmm=1) mod on the fallout 4 page, so maybe it's specific to that one.

## Expected result:
A ~5 second timer before the download starts

## Actual result:
A blur that lasts >1 seconds

**Comment by Pickysaurus** [comment]
Thanks for the report. Can you please verify if this still happens with default browser settings and no addons?
https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by Fto0n** [comment]
@Pickysaurus  Thanks for the reply! It looks like Ublock Origin is causing this issue. I'll just go ahead and disable it when downloading :)
