### ISSUE TITLE
Inline BB 'code' tag is displayed as block

### ISSUE THREAD

**Issue by Karandra** [Nexus-Mods/web-issues#1317]
## Bug/error being reported:
In mod details tab in the mod description WYSIWYG editor (#1205) the inline code tag `text [code]content[/code] more text` is always displayed as a block instead of inline. I don't know if this happens only in editor preview or it'll get saved that way if I save changes. I don't want to break my mods descriptions to test this. Existing descriptions are displayed correctly.

## Steps to reproduce:
Open the mod description editor and paste the following fragment:
```bb
Library [code]IpHlpAPI.dll[/code] is loaded by game automatically, which preloads the plugins, then redirects all function calls to the original [code]IpHlpAPI.dll[/code] file in your system directory.
```
Checked in Chrome and Chromium Edge.

## Expected result:

![123](https://user-images.githubusercontent.com/32564546/111031963-2c785880-841b-11eb-80ec-7cff6b520df4.png)

## Actual result:
![unknown](https://user-images.githubusercontent.com/32564546/111031908-e58a6300-841a-11eb-88c3-50b68f1f6be1.png)

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/250/inline-code-blocks
