### ISSUE TITLE
Mod Description editor is wayyyyyyyyyyyyyy too tall

### ISSUE THREAD

**Issue by Mgamerz** [Nexus-Mods/web-issues#1319]
## Bug/error being reported:
Unless the majority of your userbase uses vertical monitors, which I highly doubt they do, the mod descriptior editor is PAINFUL to use because of it being WAY TOO TALL.

![image](https://user-images.githubusercontent.com/2738836/111085831-c6eda000-84de-11eb-8ad8-f9077d11b7da.png)

## Steps to reproduce:
1. Use the mod description editor and put in a bunch of content that you have to use the formatting bar for.

## Expected result:
It is not an absolute chore to use 

## Actual result:
It is an absolute chore to use because I have to constantly scroll up and down, including when pasting

For something that *every* mod developer must deal with when they upload a file this is painful. I don't write lots of extra info into my mods, I instead just redirect them offsite to my own webpage where I have things like an FAQ, because it is rage inducing trying to use the NexusMods description editor with formatting tools for anything substantial. Why is it so tall AND have a scrollbar?

**Comment by JadeBarker** [comment]
Agreed.

I absolutely dread having to make mod pages for my mods because of the editor. It's such a bother to use.

**Comment by billw2012** [comment]
I just don't use it now, I switch to BBCODE and edit it in a desktop application. The editor is just too buggy in non-bbcode mode, and too hard to read IN bbcode mode. Really hope they will consider switching to Markdown also, as we can just put our github readme into the description then!

**Comment by Pickysaurus** [comment]
We've adjusted the max height of the editor from 2000px to 750px. This change will take effect next time we deploy the website.
