### ISSUE TITLE
Recommended UI/UX Enhancements

### ISSUE THREAD

**Issue by valiantshadow** [Nexus-Mods/web-issues#132]
# Recommended UI/UX Enhancements

These are recommendations that would improve small parts of the site.

## Favorite Removal Confirmation

Removing games from favorites should have a confirmation dialogue. I could see someone removing a game from favorites accidentally. Adding a confirmation dialogue would prevent this.

## Favorites Tweaks

The favorites menu can be improved aesthetically, with the removal of the "Empty Favourite" placeholder boxes.

_See image below._
<img src="https://i.imgur.com/joNHLxJ.jpg">

## Redundant Actions

Some elements of the UI are redundant, and unnecessary.

_The image below is the main page._ 
<img src="https://i.imgur.com/fRRzc87.jpg">

_The image below is one of the game pages._
<img src="https://i.imgur.com/AiZxnL9.jpg">
## Subscription Status Indicators

In user settings, the subscription status indicators can be consolidated,

_See image below._
<img src="https://i.imgur.com/LnyJAQ7.jpg">

**Comment by mrmason** [comment]
Thanks for the feedback - We will address some of these at a later date with our new head of UX/UI once we've gone live with the re-design - right now we're a 100% committed to fixing bugs - I'm going to close this for now,.
