### ISSUE TITLE
The "More Trending" tab's default sort option is causing good mod releases to quickly fade from the community

### ISSUE THREAD

**Issue by spartangoove** [Nexus-Mods/web-issues#1320]
## Bug/error being reported:
If I remember correctly, the "More Trending" tab (not the "Trending Mods" page), used to sort mods by endorsements, and that allowed the better new mods to be more visible for a week after their release. 
The new default sorting option of the tab shows less interesting mods than the old endorsement based sorting, and I don't know whether that's a bug or an intended change.

## Steps to reproduce:
Press "More Trending" tab on a game's home page.

## Expected result:
Good mods of the week sorted from top to bottom, with the top 7 of this list being consistent with the "Hot Mods" of the game's homepage and not showing in the "More Trending" tab.

## Actual result:
Less interesting mods (than that week's good mods that disappeared) show up and, in some cases, some mods show up in "Hot Mods" and also in "More Trending" tab.
Edit: And the top 7 trending (not top 7 endorsed in the current week) mods do not show up in "Hot Mods" nor "More Trending" tab unless they are also part of the 7 endorsed.

**Comment by Pickysaurus** [comment]
I'll add a note to look into this. The tab is intended to show the most endorsed over x days (i.e. which mods have had the most endorsements this week) so it won't necessarily sort by total endorsements if some of them were from outside the time period. 

If I am understanding correctly the problem you are describing is that it's no longer a continuation of the hot files (i.e. most endorsements but also only releases over x days)?

**Comment by spartangoove** [comment]
Thanks for your time.
The tab is indeed intended to show the most endorsed over x days, which is not the case at this moment.
Take 2 mods for example, as of now: 
[Shadow of the Commonwealth - A S.T.A.L.K.E.R. Inspired ENB](https://www.nexusmods.com/fallout4/mods/50748) stands at 21 endorsements.
[Looksmenu Preset Heather Casdin 123](https://www.nexusmods.com/fallout4/mods/50766) at 6 endorsements.
Both mods were released the 14th of the current month.
If we check the [More Trending tab](https://www.nexusmods.com/fallout4?tab=more+trending), we can see that "Looksmenu Preset Heather Casdin 123" is ranked higher than "Shadow of the Commonwealth - A S.T.A.L.K.E.R. Inspired ENB".
What's worse, some more recent mods with more endorsements than the "Looksmenu Preset Heather Casdin 123" don't even show up in the Trending Tab.

And yes, the Tab is no longer a continuation of the hot files.

**Comment by spartangoove** [comment]
The issue have been fixed.
