### ISSUE TITLE
'Additional files required' popup confuses players

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#1322]
## Bug/error being reported:
When a non-premium user downloads a mod that has dependencies, this popup is shown first:
> ![image](https://user-images.githubusercontent.com/230581/111859489-be9ac800-8917-11eb-8df4-86528c0f24a2.png)

That often causes confusion. Players reinstall the dependency, try it again, then get frustrated because it doesn't recognize they already have it. Since most players don't report issues, more players probably just give up on downloading the mod instead.

## Steps to reproduce:
1. Login as a user without a Premium subscription.
2. Open a mod page that has dependencies (e.g. [Tractor Mod](https://www.nexusmods.com/stardewvalley/mods/1401)).
3. Click the manual download button.

## Expected result:
A message is shown which doesn't confuse players. For example, show the download button first and visually separate the mod dependencies message, similar to what Premium users see:
> ![image](https://user-images.githubusercontent.com/230581/137009130-ccb659be-8d6c-43f2-b5ef-925a0b881514.png)

## Actual result:
The displayed popup often confuses players. For example (and this is just the subset of cases I saw myself):
* [2022-11-09 Nexus](https://user-images.githubusercontent.com/230581/200928090-7986fd19-e0c1-48fb-90c6-51be887034fb.png)
* [2022-06-29 Nexus](https://user-images.githubusercontent.com/230581/176927099-e29483c1-e42f-4eaa-b9c6-7b5d0c7ce12e.png)
* [2022-05-07 Nexus](https://user-images.githubusercontent.com/230581/167260823-a038c2d8-3587-4bef-8373-36cf1539696a.png)
* [2022-03-16 Nexus](https://user-images.githubusercontent.com/230581/160510273-8b7cd20b-f5e4-4383-a5b8-6e0671799c03.png)
* [2022-03-11 Nexus](https://user-images.githubusercontent.com/230581/158290965-d03a78e0-bbfa-46d0-a1de-a44cfdb8aac2.png)
* [2022-02-16 Nexus](https://user-images.githubusercontent.com/230581/154372995-c3928bbf-2e8e-4d72-90f6-ecd260cb9e22.png)
* [2022-01-05 Nexus](https://user-images.githubusercontent.com/230581/148692283-8ec68f1a-560e-4b49-9d61-bb065665b936.png)
* [2021-12-30 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/147796723-3bd4ec9e-2bc6-42a0-b51b-8bf8151d86b9.png)
* [2021-12-25 Stardew Valley Discord](https://user-images.githubusercontent.com/66890515/147397459-e0966ecc-28ff-4e39-a9ba-8b64a74febaa.png)
* [2021-10-10 Nexus](https://user-images.githubusercontent.com/230581/137008940-60188eb6-4d14-41af-ad52-e12b7c2a3bea.png)
* [2021-08-05 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/128347860-285b0a4c-92e7-42dc-89d5-d7abc3950320.png)
* [2021-07-13 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/125538217-1fa0aaa1-4fca-46d7-a446-743fc7796525.png)
* [2021-06-23 Nexus](https://user-images.githubusercontent.com/230581/123352626-b7deab00-d52d-11eb-86f7-0d2ce174f5eb.png)
* [2021-06-20 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/148692551-5a5ec245-e792-4e31-9bb0-da1e87230f5d.png)
* [2021-05-08 Nexus](https://user-images.githubusercontent.com/230581/117545934-e512e080-aff5-11eb-9ff4-967596c197f5.png)
* [2021-03-19 Nexus](https://user-images.githubusercontent.com/230581/111859818-ff93dc00-8919-11eb-880c-9c0a153c64db.png)
* [2021-02-18 Nexus Discord](https://user-images.githubusercontent.com/230581/111859770-9ca24500-8919-11eb-802c-a5ea0d680775.png)
* [2021-02-05 Nexus](https://user-images.githubusercontent.com/230581/111859803-dd01c300-8919-11eb-80ed-45fc064a0d95.png)
* [2020-09-04 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/111875861-54634100-8972-11eb-9098-dedd5675de65.png)
* [2020-07-26 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/111875803-06e6d400-8972-11eb-833b-251622021afb.png)
* [2020-07-07 Stardew Valley Discord](https://user-images.githubusercontent.com/230581/148692786-a355703c-e0aa-438b-8c36-060ee90fa5b0.png)

**Comment by LenneDalben** [comment]
![Screenshot_20211225-213122](https://user-images.githubusercontent.com/66890515/147397459-e0966ecc-28ff-4e39-a9ba-8b64a74febaa.png)
Here's another example of that confusion to add to the list!

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/254/free-user-requirements-pop-up-is-confusing
