### ISSUE TITLE
[Registration button] Pressing the "REGISTER" button in main on the page https://www.nexusmods.com/valheim goes to the page https://users.nexusmods.com/auth/sign_in and gives the error "ERROR You need to sign in or sign up before continuing. "

### ISSUE THREAD

**Issue by virtualvanix** [Nexus-Mods/web-issues#1323]
## URL 
https://www.nexusmods.com/valheim

## Username on the Nexus: 
virtualvanix

## Bug/error being reported:
Pressing the "REGISTER" button in main on the page https://www.nexusmods.com/valheim goes to the page https://users.nexusmods.com/auth/sign_in and gives the error "ERROR You need to sign in or sign up before continuing. "

## Steps to reproduce:

1. Launch the browser;
2. Follow the link https://www.nexusmods.com/valheim;
3. Click on the button "REGISTER" in main;
4. See the result.

## Expected result:
Pressing the "REGISTER" button on the page https://www.nexusmods.com/valheim goes to the page https://users.nexusmods.com/register

## Actual result:
Pressing the "REGISTER" button in main on the page https://www.nexusmods.com/valheim goes to the page https://users.nexusmods.com/auth/sign_in and gives the error "ERROR You need to sign in or sign up before continuing. "

![1](https://user-images.githubusercontent.com/81045648/111884089-d9c51080-89c7-11eb-9b48-8dba7a3fb7e8.png)
![2](https://user-images.githubusercontent.com/81045648/111884092-dfbaf180-89c7-11eb-9447-2ccce9424ce2.png)

p.s. I'm sorry for my English, I wrote through a translator;)

**Comment by Pickysaurus** [comment]
A fix for this is in the works. Thanks for the report!
