### ISSUE TITLE
Notifications no longer working after update

### ISSUE THREAD

**Issue by Ninja2dan** [Nexus-Mods/web-issues#1324]
## Bug/error being reported:
Since the update, I am no longer getting notifications for ANY mods that I'm tracking. I have checked the settings multiple times, have closed and reopened my browser, cleared cache, and even restarted the computer.

## Steps to reproduce:
My settings are as follows:
Display notifications - On
Show game specific notifications - On
New games - Off
Site news (important news will be issued) - Off
Changes to your files by team members - On
Comments on your files, images and videos - On
Replies on bugs you reported - On
Bug reports on your files - On
Files you're tracking - On
Authors you are tracking - Off
New images and videos added to your files - On
Social interactions from other users - On

## Expected result:
With those settings, I should be seeing a notification for any comments, bug reports, or file updates for all mods that I'm tracking. I should also only be seeing notifications for the game that I am currently viewing (Fallout 4, Skrim SE, etc).

## Actual result:
I have been seeing zero new notifications. I have looked in the comments section of a few mods that I'm tracking, and there have in fact been new comments posted. It's just not pushing any new notifications since the update.

**Comment by Pickysaurus** [comment]
New comments on files you are tracking are not included as part of the initial release. Any other notifications should come through though.

**Comment by Pickysaurus** [comment]
We've pushed an update that should resolve these issues.
