### ISSUE TITLE
Mod pages are cut in half/zoomed in

### ISSUE THREAD

**Issue by TwoShots0Kills** [Nexus-Mods/web-issues#1327]
Zoomed in/ cut in half mod pages
Every Mod I click on/ try to download page's are very zoomed in. It seems to affect the background image, videos on mod page, and any writing. The only parts not affected are the title, track, endorse, and vote buttons, as well as the mods statistics under the title.

I have no idea what caused this, I just simply opened nexus and all mods were affected.
I have tried using zoom commands to see if it was a settings issue, but that only made it worse.

Until I can find a fix for this I am unable to download any mods or know what is in any mods.

**Comment by Pickysaurus** [comment]
Without a screenshot, I'm afraid I'm not sure what to suggest.

If you're on PC try pressing Ctrl + 0 and if you're on mobile try going into your accessibility settings and turning off "Force zoom".
