### ISSUE TITLE
(Some) mods sort by and display "last update" incorrectly

### ISSUE THREAD

**Issue by coredumperror** [Nexus-Mods/web-issues#1328]
## Bug/error being reported:
Dragon Quest S: Definitive Edition mods display and sort wrong when ordered by Last Update. Perhaps based on an outdated "last update" field?

## Steps to reproduce:
Go to this page (Dragon Quest S: Definitive Edition mods), and change the sort to "Last Update":
https://www.nexusmods.com/dragonquestxisdefinitiveedition/mods/

## Expected result:
Project Rebuild should appear 2nd on the list, because it was updated on April 3rd.

## Actual result:
Project Rebuild instead appears 8th, and displays that it was last updated on March 29th. 
![Screenshot 2021-04-04 134137](https://user-images.githubusercontent.com/413571/113520994-82887980-954b-11eb-9cac-e6adc2ea6a24.png)

But if you go to the Project Rebuild [mod page](https://www.nexusmods.com/dragonquestxisdefinitiveedition/mods/22) itself, it says it was last updated on April 3rd (which is the correct date).
![Screenshot 2021-04-04 133632](https://user-images.githubusercontent.com/413571/113520912-02621400-954b-11eb-9f79-6da996c94d74.png)

I'm guessing this is some sort of cache mismatch? Though if it's that, the fact that the sort order is wrong as well seems extra odd... So maybe not. 

Perhaps it's accidentally sorting by Publish date, instead of Update date? But that doesn't explain the incorrect "Last Update" field on the listing page.

So yeah, I'm kinda stumped.

**Comment by Pickysaurus** [comment]
This should have been resolved. Let us know if you are still having problems.
