### ISSUE TITLE
Download names inconsistent in mod managers

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#1329]
## Bug/error being reported:

The mod names after installation (using Vortex as an example but it happens with any mod manager using Nexus API) are inconsistent and are sometimes made of just file name or full mod name + file name.

Example: [https://imgur.com/0UJscuy](https://imgur.com/0UJscuy)

## Steps to reproduce:

1. Download file: https://www.nexusmods.com/skyrimspecialedition/mods/45307?tab=files
2. Download file: https://www.nexusmods.com/skyrimspecialedition/mods/45192?tab=files

## Expected result:

The mod entry in mod manager using the same pattern of either: 
<file_name>
or
<mod_name> - <file_name> 

## Actual result:

Selected semi-randomly between mod name, file name or both.

**Comment by Pickysaurus** [comment]
This is not a bug (also this tracker is for site issues). 

Vortex does a comparison between the file name and the mod name. If the file name is significantly different the mod name is appended to the start. This is for cases where the author uploads the file was a name like "2k". Calling it "2k" gives you no context on where that came from whereas "Some mod name - 2k" would.

**Comment by zax-ftw** [comment]
> Vortex does a comparison between the file name and the mod name. If the file name is significantly different the mod name is appended to the start. This is for cases where the author uploads the file was a name like "2k". Calling it "2k" gives you no context on where that came from whereas "Some mod name - 2k" would.

@Pickysaurus  
What is happening to the 3 files at the bottom then? They are not same as mod name yet the file name without mod name prefix is used? Is some substring comparison being made here?
