### ISSUE TITLE
No visual differance between endorsing and abstaining on mod page

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#133]
If via your Downloads page you chose to abstain from endorsing a file, when you actually go to that mod page it looks exactly like you have endorsed it:
Eg: https://www.dropbox.com/s/xhkj5e6sn62ks9a/Screenshot%202017-10-05%2014.36.42.png
In the above image you can see it looks like I have endorsed the mod when I havent leading to a lot of confusion. It only tells you its not an endorsement when you click on it to try and 'undo' it

**Comment by Rrrafau** [comment]
assigned #151711987

**Comment by iamtiz** [comment]
Fixed so that the 'endorse' button on mod pages has the same behaviour as the current site
