### ISSUE TITLE
No notification when user comment on a issue.

### ISSUE THREAD

**Issue by Digus** [Nexus-Mods/web-issues#1330]
## Bug/error being reported:
Before the update to the new notification system, we would get reports about issues being created and when an user commented on a existing issue.
Now I only get notification for new issues being reported.
I end up missing user responses to issues is I don't remember to check.

## Steps to reproduce:
Comment on a bug report.
Check the notification tab of the user the issue was commented.

## Expected result:
Should get notification when someone reply to an issue of mods you own.

## Actual result:
No notification being shown.

**Comment by Pickysaurus** [comment]
If this is still an issue, feel free to reopen the ticket.
