### ISSUE TITLE
No notifications of posts to followed mods

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#1331]
## Bug/error being reported:
My Notification (dys)function shows only Nexus News, new games added and comments made to my own mods. It has not shown comments made to my FOLLOWED mods since March 22 when the new, egregiously-broken system went live, claims by staff that it all works now notwithstanding. It does not "all work now," Todd. ☺

## Steps to reproduce:
1. Browse to Nexus Mods
2. Click the Notifications icon
3. Cry when you see that your former 20 notifications per day is still just 5... or 3...
4. Cry harder when you realize that the only thing working is Nexus blurbs and comments on your own mods
5. Fall to your knees and BEG Nexus mods to bring back the old Notification system which was the envy of the free world

## Expected result:
I expect to see ~20 notifications per day like I saw with the old Notifications system, which actually "worked a treat" as the British are wont to exclaim

## Actual result:
(How many times must I reiterate?)
I get no notifications on mods I follow and have followed for years- only Nexus News and comments made to my own uploaded mods (please see the topic headline and sections 1, 2 and 3 {no Oxford comma required} above for the previous ways I have stated the exact same thing.) Not to put too fine a point on it, the new system is a giant leap backwards into the Stone Age of notification systems. It sucks brackish swamp water. It does not work. 

And even if it worked, the bloated 5-line UI is a disaster and an affront to users.

Please, Good Sir Knight, I know you think it's fixed, but it's **not** fixed. It won't be fixed until it actually works. Please stop responding to the litany of complaints about it with rectification fantasies and just fix it.

**Comment by RubixRevenge** [comment]
Same experience here. Sometimes, I am not even notified of responses to my own comments.

**Comment by Pickysaurus** [comment]
This has been resolved.
