### ISSUE TITLE
LA CDN: File missing?

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#1332]
## Your username/username(s) affected
All users connected the the LA CDN. 

## Bug/error being reported:
https://www.nexusmods.com/fallout4/mods/51299?tab=files
Unable to download the Fallout 4 mod file from the LA server. 
Mod ID: 51299
File ID: 20549

## Steps to reproduce:
Attempt to download the file from the LA CDN (or be a free user automatically connecting to it). 

## Expected result:
File download starts

## Actual result:
502 error

### Note
I have selected "Retry B2 upload" in the admin panel to see if this triggers a reupload of the file to the LA server.

**Comment by mrmason** [comment]
Fixed: #1334
