### ISSUE TITLE
Content blocking filters does not work on new mods tab

### ISSUE THREAD

**Issue by Dementore711** [Nexus-Mods/web-issues#1333]
## Your username/username(s) affected
NikhilSajan

## Bug/error being reported:
Content blocking filters not working on new mods tabs (New today, New this week). 

## Steps to reproduce:
<!--
Optimally an ordered list with the steps needed to reproduce the bug
Block translation and languages other than English
Check new mods tabs (New today, New this week). 

### Example:
I have blocked translation and languages other than English in my filters

## Expected result:
Mods with translation and languages other than English tags should not appear on new mods tabs

## Actual result:
Mods with blocked tags still appears

**Comment by Pickysaurus** [comment]
This should have been fixed a while ago now. Thanks for the report.
