### ISSUE TITLE
502 error on mod download

### ISSUE THREAD

**Issue by jinncrazey** [Nexus-Mods/web-issues#1334]
## Your username/username(s) affected

jchernandez
## Bug/error being reported:

Can't download mod. link: https://www.nexusmods.com/fallout4/mods/48042?tab=files
## Steps to reproduce:

1. Go to mod and click mod manager download or manual download. 
2. Both would not work and give 502 error.
3. 
## Expected result:

Mod gets downloaded.
## Actual result:

![image](https://user-images.githubusercontent.com/82301040/114291962-d8b26b00-9abd-11eb-849b-2839c6294566.png)

Mod download gives 502 error. Screenshot attached.

**Comment by mrmason** [comment]
Thanks for the report, I've fixed this - there was a problem with logs on a CDN node in LA.
