### ISSUE TITLE
Window for "download confirmed" does not scroll with page, does not intuitively close when clicking outside of bounds

### ISSUE THREAD

**Issue by Seraphim343** [Nexus-Mods/web-issues#1335]
## Your username/username(s) affected
Chaser343

## Bug/error being reported:
When using the download button on a mod page (using Cyberpunk 2077 in this case), clicking outside of the "download starting" window no longer closes the window.

The "download starting" window also does not follow the page scroll. Only removes when scrolling completely away from the window until it is no longer in view, then clicking anywhere else. This also causes the page to shift down/up towards where ever the window was situated prior to clicking.

I am unsure if this is a bug, but felt like clicking outside the window previously worked flawless.

## Steps to reproduce:
1.) Go to mod download page -> files
2.) Download with Vortex
3.) Attempt to click outside the window or scroll, the issue will reveal

## Expected result:
Expected to click outside of the window to close and continue browsing, as previously able.

## Actual result:
The window stays displaying and allows scrolling of the page, but does not remove itself nor the darkened background.
Included is a gif of the result. I was able to close it finally by scrolling all the way back up and clicking the banner.
https://i.imgur.com/StSN44S.gif

**Comment by Pickysaurus** [comment]
Clicking outside the window to close was prevented a while back. You can press the Esc key to close a popup, but I do agree the behaviour could be improved.

**Comment by Pickysaurus** [comment]
This will not be fixed in the current website design, but modals in the new site layout will follow the page properly.
