### ISSUE TITLE
Feature request: notifications on author's actions on hidden mods or warning to authors on hiding files

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1338]
Sorry if it's already done in the notification system update, since it's not easy to check.
You recieve no notifications about any of author's actions when a mod is hidden. Many authors don't know about it, which results in notifications on files you're tracking being lost even after the mod is unhidden. What i suggest is to either send all the notifications once a mod is unhidden or place a warning on hiding a mod saying that users won't receive any notifications.

**Comment by Pickysaurus** [comment]
Moved to here: https://feedback.nexusmods.com/posts/242/inform-mod-authors-that-hiding-the-mod-prevents-notifications
