### ISSUE TITLE
Feature request: default font size

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1339]
Currently you can't select the default font size in the dropdown, you can only select size that is either smaller (Small) or bigger (Normal) than the default one. What would make more sense imo is to add an option that sets the default size or change the default size.

**Comment by Pickysaurus** [comment]
You can use the "Remove formatting" button to set it back to default. 
![image](https://user-images.githubusercontent.com/31670524/117114370-ac6bd080-ad83-11eb-99f4-cceadbc1cce7.png)


Hope this helps.
