### ISSUE TITLE
FALSE Mod Has Been Updated Since Last Download Message

### ISSUE THREAD

**Issue by ThisNekoGuy** [Nexus-Mods/web-issues#134]
I had downloaded some mods from Skyrim Special Edition this week and it says that some mods that I downloaded have been update since I last downloaded them, with the green checkmark/icon.

That would be fine, except the mods it told me that for weren't actually updated.

For example, Immersive Citizens didn't have an update within the last few days since I downloaded and installed it and NMM reflects that to be true.

**Comment by Rrrafau** [comment]
assigned #151712772

**Comment by iamtiz** [comment]
This is now fixed

**Comment by mrmason** [comment]
Please let us know if you see any more issues with the caching on this one.
