### ISSUE TITLE
My deleted mod is still visible after a few days after deletion

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1340]
## Your username/username(s) affected
lilebonymace

## Bug/error being reported:
I deleted my mod No Spikes Damage (via Delete option on MY MODS tab as usual) from both SE https://www.nexusmods.com/skyrimspecialedition/mods/25629 and LE https://www.nexusmods.com/skyrim/mods/97042 already a few days ago and when you visit these pages you see that they're deleted and i can't manage it anymore, however the mod is still visible on my profile https://www.nexusmods.com/users/59086436?tab=user+files&BH=1, in search results and browsing mods. Not sure if it's a common problem currently or something went wrong in my particular case.

**Comment by mrmason** [comment]
Thanks for the report, we're already aware of this and are tracking it internally `nexusmods/-/issues/706`.

We'll update here when we've got a fix.

**Comment by Pickysaurus** [comment]
This should be resolved.
