### ISSUE TITLE
Nexus Forums Error 522 - Connection Timeout

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1341]
ff7legend

Error 522 - Connection Timeout (Nexus Forums only)

1. Navigate to any Nexus homepage.
2. Attempt to navigate to the Nexus Forums.
3. Watch as Error 522 - Connection Timeout splashes across one's screen...

Successful navigation to the Nexus Forums.

Error 522 - Connection Timeout is displayed across my screen.  If it's of any consolation, I use the Google Chrome web browser.

**Comment by mrmason** [comment]
Thanks for the report - one of our suppliers is having an outage, once they recover the forum should start working again.
