### ISSUE TITLE
Vortex Update

### ISSUE THREAD

**Issue by zygster525** [Nexus-Mods/web-issues#1342]
Update to Vortex, now can't log in in Vortex to download mods

**Comment by BigBizkit** [comment]
As one of our suppliers is having an outage, our API is currently down which is very likely the cause of your download issues -  rather than the last Vortex update.

Sorry about that, but I'm afraid it's outside of our control though we are hopeful that it will be sorted soon.

**Comment by zygster525** [comment]
Incorrect, I was able to Manually Download Mod, without an issue, (not a
server problem) Vortex had an Update, and caused the issue, a subsequent
Vortex Update fixed the issue. Before that last update NONE of the mods I
have installed were working, that is not a server issue, it is a software
issue.
