### ISSUE TITLE
Failed Vortex Login + API Key won't work. Website Login is working fine

### ISSUE THREAD

**Issue by Voevoden** [Nexus-Mods/web-issues#1343]
Voevod

## Bug/error being reported:
Failed Login to Vortex. Even when C/P API key it won't work. Login to website works fine

## Steps to reproduce:
Tried several times?

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

**Comment by Pickysaurus** [comment]
This was due to a temporary outage. This should be back to normal shortly.
