### ISSUE TITLE
Pasting an image

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/web-issues#1345]
## Your username/username(s) affected
thany2

## Bug/error being reported:
When I paste an image in a bug report, the image gets pasted, and the bug report displays as expected. Then whenever I revisit the same page later on, I notice that the image is, I guess, un-encoded back into base64 text.

## Steps to reproduce:
1. Open a new bug report somewhere.
2. Paste an image. That is, pixel data from the clipboard, not the url to an image.
3. Post it
4. (the posted bug looks as intended)
5. F5
6. (the posted bug is now horrifcly garbled)

## Expected result:
Image stays an image even after an F5, or presumably when someone else looks at it.

## Actual result:
```
[img]data:image/png;base64,iVBORw0KGgoAAAAN... (a LOT of base64 text here)[/img]
```
This becomes visible literally.

**Comment by Pickysaurus** [comment]
Please do not directly paste images into the comment editor. This is not supported. Unfortunately, the library we use for our WYSIWYG editors doesn't correctly prevent this behaviour.

**Comment by thany** [comment]
Maybe so, but the url that is pasted inside the `[img]` tags is actually a correct url, so I wonder why that doesn't work.

**Comment by Pickysaurus** [comment]
Related to https://github.com/Nexus-Mods/web-issues/issues/1326
