### ISSUE TITLE
Pasting a url

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/web-issues#1346]
## Your username/username(s) affected
thany

## Bug/error being reported:
If I paste a url, it isn't made clickable.

## Steps to reproduce:
1. Open a bug report or something.
2. Paste a url
3. Post it
4. Try clicking the url.

## Expected result:
Url is clickable.

## Actual result:
Url is not clickable.

**Comment by Pickysaurus** [comment]
For now, you can use the "Add URL" toolbar icon and paste the link into both fields to create a clickable link. We'll review this functionality when next update the comment editors

**Comment by Pickysaurus** [comment]
Our new comments system is using Markdown which links URLs by default.
