### ISSUE TITLE
Update not shown in list with new release as updated

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1347]
1) https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files&BH=0
sort by last updated
Insel von Artaeum SSE 1.972 DV
Quests and Adventures
Uploaded: 22 May 2020
Last Update: 12 Mar 2021
but it got updated today 1.981 DV
https://www.nexusmods.com/skyrimspecialedition/mods/36317

same, if you look at "Mods"-"Brwose all"-Sorted by last updated
while here two pdates are not shown as updad: (1) the Insel von Artaeum SSE and (2)  
Aethernautics- A Space Travel Mod 2.3.1 DV
Dungeons
Uploaded: 17 Dec 2020
Last Update: 26 Apr 2021
https://www.nexusmods.com/skyrimspecialedition/mods/43409

**Comment by Pickysaurus** [comment]
Please let us know if you're still seeing this issue. I am fairly sure it has since been fixed.
