### ISSUE TITLE
Mod File Upload hangs at approximately 99%

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#1349]
Vyxenne

Everyone
## Bug/error being reported:

Mod file upload hangs at very high percentage of completion (unknown exactly how high because the system no longer displays percent completion). Cancelling it, then attempting to restart the upload results in the absurd admonition to only upload one file at a time, yet there is no way to restart the upload or to re-drop the file or to browse and select the file for upload. As a result, all the previous work on the page is wasted and must be repeated.

## Expected result:

The upload progresses from 98% to fully complete in under 3 weeks
## Actual result:

Unknown how many weeks I could have waited, but the number "infinity" comes to mind. A chronically dysfunctional uploading system like the Nexus's is simply nuts for a website whose ENTIRE EXISTENCE IS ABOUT USERS UPLOADING FILES.

The Nexus uploading process has been backwards (i.e. retarded) for years. Won't you please consider fixing it? Thanks.

**Comment by Pickysaurus** [comment]
We're aware of this issue but cannot reliably replicate it. I suspect it's related to browser addons blocking the uploader after a period of time. The advice here may help: https://help.nexusmods.com/article/113-troubleshooting-website-issues

If you cancel the upload and click the file selector (not drag and drop) you'll be able to resume it.

**Comment by Vyxenne** [comment]
Thank you. 
-------- Original message --------From: Mike ***@***.***> Date: 5/5/21  03:22  (GMT-06:00) To: Nexus-Mods/web-issues ***@***.***> Cc: Vyxenne ***@***.***>, Author ***@***.***> Subject: Re: [Nexus-Mods/web-issues] Mod File Upload hangs at approximately
  99% (#1349) 
We're aware of this issue but cannot reliably replicate it. I suspect it's related to browser addons blocking the uploader after a period of time. The advice here may help: https://help.nexusmods.com/article/113-troubleshooting-website-issues
If you cancel the upload and click the file selector (not drag and drop) you'll be able to resume it.
