### ISSUE TITLE
Coping text into visual editor results in extraneous line breaks

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#135]
If you copy text from an external source such as yoru clipboard or even just dropping and dragging from word directly into the visual editor rather then into the BBC viewer, you end up with extra line breaks half way through sentences where its been pushed onto a new line. 

**Eg, copying this into the editor**

This means effectively that mods placed in these arc files are broken but cannot and should not be just reinstalled. If you reinstall them, you are casting off possibly crucial data required by the engine updates to run correctly.

**Results in this outcome:**

Thismeans effectively that mods placed in these arc files are broken but cannot and
should not be just reinstalled. If you reinstall them, you are casting off
possibly crucial data required by the engine updates to run correctly.

This is a bug that been inherited from the old site, its always been an issue, but just didn't have a reliable way to report it before and it would be nice to see it fixed if possible.

**Comment by Rrrafau** [comment]
assigned #151712794

**Comment by verenion** [comment]
This seems to be related to the editor we use for BBCode. We don't maintain this code, and it is even an issue on their own website (http://wysibb.com/). I will add to to the ice box to be looked at later.
