### ISSUE TITLE
corrupt files

### ISSUE THREAD

**Issue by Celyste** [Nexus-Mods/web-issues#1351]
## Your username/username(s) affected
dragonsfire777

## Bug/error being reported:
corrupted mods

## Steps to reproduce:
download a mod, install it, most (70% ish) .dds files are unreadable or corrupt

### Example:
dl'd a mod (doesnt matter which)
installed mod (doesnt matter whether or not its through NNM or maunal)
opened .dds file (doesnt matter whether its diffuse, normal, or specular)
file is possibly corrupt, distorted image or image is a series of lines sometimes the image is just black (some cases all files were unreadable)

## Expected result:
for the mod to work normally and the files to produce what is intended in the game

## Actual result:
the files were corrupt, textures wouldnt appear properly in game or in other model viewing programs

**Comment by Pickysaurus** [comment]
I'm afraid without specific files I cannot verify this. I suspect there may be a connectivity issue causing this. Please see https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
