### ISSUE TITLE
Tracking not workin gproper

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1353]
sample:
https://www.nexusmods.com/skyrimspecialedition/mods/49431?tab=posts
05 May 2021, 1:16AM new posting from Starblast16
when I log in I have no notification, but mod tracking is on

**Comment by Pickysaurus** [comment]
Make sure you have the relevant setting enabled

![image](https://user-images.githubusercontent.com/31670524/117113615-a1647080-ad82-11eb-9b52-0cd540fb1762.png)

If this is enabled, we are currently working on some preferences related issues for notifications that should fix this in the near future.

**Comment by Dreifels** [comment]
I had it, then you changed my settings by change again this interface part
