### ISSUE TITLE
New Notification System. Notifications for mods don't stack up...

### ISSUE THREAD

**Issue by Drax90** [Nexus-Mods/web-issues#1354]
## Expected result:

Notifications used to stuck up when there were changes in the mod thread I was trucking, with the old system, now they don't.

## Actual result:

Now, I need to scroll down over 100+ notifications to find new notifications on a specific mod, just in case I missed something.
Imagine living it like this over a week to 600+ notifications... I will sure need a new mouse...! :P

**Comment by Pickysaurus** [comment]
Hi there, perhaps you can include a screenshot to illustrate your point?

The stacking works differently from the previous system. Notifications are currently grouped by 24hr periods.

**Comment by Drax90** [comment]
> 
> The stacking works differently from the previous system. **_Notifications are currently grouped by 24hr periods._**

So, **this** is the problem...! :)
Most mods here update every **1**-**2** months! But the ideal would be a 3 month period! Please, IF it is possible...?!

Thanks!

**Comment by Drax90** [comment]
So it is not possible...! :(
I'll let it stack then, till the mods will be transfered at the Steam Workshop!

Anyway, thanks for the response!

**Comment by Pickysaurus** [comment]
Sorry for the slow reply. Changing how grouping works is going to be one of the focuses of a future update to the system. I can't say for sure what it will look like as we haven't explored it fully yet.

**Comment by Drax90** [comment]
Slow reply is better than no reply!!!

Thank you! :)

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/243/better-notification-grouping
