### ISSUE TITLE
Keep getting auto-logged out of my Nexus account

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1355]
## Your username/username(s) affected
ff7legend

## Bug/error being reported:
Site keeps logging me out

1. Navigate to Skyrim SE Nexus
2. Click on any mod shown on the front page
3. Page displays but the Log In box appears instead of my username even though I'm signed into my Nexus account

## Expected result:
Stay logged into my Nexus account

## Actual result:
Log In box appears & when clicked, it states I'm already logged in & asks if I want to continue as ff7legend.

**Comment by Pickysaurus** [comment]
We're aware of this issue and work on it. Sorry about this.

**Comment by scjohnson1981** [comment]
The issue was sporadic yesterday but now happens each time I navigate to the Nexus site & click on any link...

**Comment by Pickysaurus** [comment]
The issue should be resolved now, we've reverted the changes that were causing it.
