### ISSUE TITLE
Nexus Mods losing log-ins, now not recognising premium membership

### ISSUE THREAD

**Issue by Tetrol88** [Nexus-Mods/web-issues#1356]
## Your username/username(s) affected
 Tetrol88

## Bug/error being reported:
 As I move around the nexus mods site, keeps asking for me to log-in, when I click log-in it says I already am. Loses the page I have navigated from as well. Now it has decided to not honour my premium membership - asking for me to go premium, capping my DL speed - If I look at my profile I am listed as premium. Essentially, there is a disconnect between my profile and the mod site.

## Steps to reproduce:
 Step 1 - Navigate to a new page, site loses my log-in
Step 2 Click "log in" - site states I am already logged in
Step 3 No way of directly returning to the page I was just on

Now also not recognising my premium membership, despite profile stating "premium"

## Expected result:
 A site that works

## Actual result:
 A site that doesn't

**Comment by chrisharrison** [comment]
Which browser are you using?

**Comment by Pickysaurus** [comment]
No reply for 18 days, please re-open this ticket if you are able to reply.
