### ISSUE TITLE
Mobile view doesn't refresh notifications when removing one

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#136]
Android Chrome.

**Comment by ousnius** [comment]
Now that I'm home, I can elaborate a little more.

When I clicked the notifications button on my phone and clicked "Remove" on one of the entries, nothing happened visually. Upon reloading the page manually, the notifactions was gone.

The notifications list should be refreshed automatically.

**Comment by iamtiz** [comment]
Assigned #151760152

**Comment by iamtiz** [comment]
Notifications are now removed on the fly when browsing from a mobile device, too
