### ISSUE TITLE
Nexus file server serving old file instead of uploaded file

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#1361]
Possible regression of #601? The main difference is both new versions did not match any existing versions.

Is it possible the file server decided the uploaded file was not substantive enough bytewise to store and instead served the old file under a new name to save space?

# Affected File

[https://www.nexusmods.com/skyrimspecialedition/mods/23603](https://www.nexusmods.com/skyrimspecialedition/mods/23603)

# Timeline

Version | Upload Time
:--- | :---
1.1.1 | 14 May 2021, 8:41AM
1.1.2 | 14 May 2021, 11:58AM
1.1.2.1 | 14 May 2021, 6:17PM

# CRC Differences

![https://i.imgur.com/sEGArDA.jpg](https://i.imgur.com/sEGArDA.jpg)

**Comment by mrmason** [comment]
Every upload should be unique - however if you uploaded a file that was of the same name, with the same size, but with different contents soon after another one, then the upload system will assume it is the same file. To be safe with small files it's worth renaming the file on your end before uploading to ensure this never happens. 

This are the md5 hashes for all of the files we have for that mod

```
e670e2afc331d5cfaef15fc3015bfda1  Stay with Me-23603-1-0-1550720631.zip
afdb485f1d1e0fbf858b771f4cccec10  Stay With Me-23603-1-1-1-1621006895.zip
83a8c0fc03cff1d9a10986bf5db8184f  Stay With Me-23603-1-1-1620962393.zip
afdb485f1d1e0fbf858b771f4cccec10  Stay With Me-23603-1-1-2-1-1621041420.zip
afdb485f1d1e0fbf858b771f4cccec10  Stay With Me-23603-1-1-2-1621018732.zip
```

So it looks like the scenario I gave above may have happened ?

**Comment by fireundubh** [comment]
> Every upload should be unique - however if you uploaded a file that was of the same name, with the same size, but with different contents soon after another one, then the upload system will assume it is the same file. To be safe with small files it's worth renaming the file on your end before uploading to ensure this never happens.

The uploaded file ("What Author Uploaded") contains an ESL flagged ESP. The ESP in 1.1.1 is not ESL flagged. That's why the CRCs are different. It was a uniquely different upload.

The problem is your system cares only about file name and file size, not about content.

**Comment by mrmason** [comment]
Sorry, I meant renaming the name of the .zip file you're uploading - not the file inside the archive.

This is potentially something we can fix on our end, but this system is in place so that people can resume file uploads if something goes wrong,
