### ISSUE TITLE
invisible comment on mod page "bug" section

### ISSUE THREAD

**Issue by Slowpoke501** [Nexus-Mods/web-issues#1362]
## Your user/users affected
Slowpoke501

## Bug/error being reported:

I was replying a bug report on my mod page, in order to explain better i have add an image, after clicking reply the complete section turn invisible the new comments and the old ones too
![image](https://user-images.githubusercontent.com/45579045/119213526-006df900-ba96-11eb-9616-88729672a527.png)

I had try to relod the page several times but the issue still there

I was sending this image, i hope it helps to realise what was wrong
![image](https://user-images.githubusercontent.com/45579045/119213586-ad487600-ba96-11eb-96f9-4ce3df357ad0.png)

This is my mod page: https://www.nexusmods.com/skyrimspecialedition/mods/49074?tab=bugs

## Steps to reproduce:

1. on a mod page in the "Bug" section
2.  reply the comments with text and an image

## Expected result:
I was especting to show a screenshot of a posible solution in the comments

## Actual result:
then all the comment turn invisible

**Comment by Pickysaurus** [comment]
Delete a comment where the user tried to directly paste images into them (which is unsupported)

User: https://www.nexusmods.com/skyrimspecialedition/users/62697066
> there is no need to put the meshes out of the correspoding folder
in any case thi is the path that the meshes shoud have
Data\meshes\actors\character\character assets
inside should be the folder:
> 
> DCS sos patch
> 
> DCS unp patch
> 
> inside the DCS unp patch should be all the female, feet and hand .nif files
> 
> An other think that could be happening is that WICO is overwritting the meshes path to his own path
