### ISSUE TITLE
Category Pulldown can have an empty list

### ISSUE THREAD

**Issue by Hugh-McCurdy** [Nexus-Mods/web-issues#1363]
URL: https://www.nexusmods.com/images/add
Bug/error being reported: Category pulldown can have an empty list
Steps to reproduce: Enter information, including category, & upload image.  Then click on the link for Terms and Conditions.  Then back arrow.
Expected result: That the pulldown menu is populated
Actual result: That the pulldown menu is vacant (and orange in the screen shot)

![Nexus20210524](https://user-images.githubusercontent.com/2231337/119414365-73a58400-bcbd-11eb-82fc-360399909de4.png)

**Comment by Pickysaurus** [comment]
Using the back arrow is the issue in this situation, you can fix it by reselecting the game. Or by uploading your images via the game-specific URL: https://www.nexusmods.com/skyrimspecialedition/images/add
