### ISSUE TITLE
Feature Request: Notifications API

### ISSUE THREAD

**Issue by Sonozuki** [Nexus-Mods/web-issues#1364]
New APIs that allow us to interface with the notification system to retrieve unread, mark notifications as read, and unmark notifications as read.

**Comment by mrmason** [comment]
Thanks for the suggestion, we will keep it in mind when expanding our APIs - we have written this system in away that makes this feature possible, but we don't have it planned in short term.

**Comment by TomKranenburg** [comment]
Just tagging my interest onto this. Love the site. One of the best on the web. I'd like to be able to tell when I get new notifications immediately if possible. An API would do that job I think. Or better yet just email notifications for premium memebers.

**Comment by Sonozuki** [comment]
Personally, I would rather have an API, as I can make an app to get desktop notifications, but I could see why emailing notifications could be useful for some, though that's likely a separate request

**Comment by TomKranenburg** [comment]
API is preferable for me too. I think it might have less of a resource overhead for them also. However the first thing I'm going to do is write a email notification script.

The site has really grown into something huge. I'd like to know as soon as something drops.

**Comment by Sonozuki** [comment]
That's fair enough, completely agree though, having a tab open and refreshing every now and then is not ideal at all

**Comment by TomKranenburg** [comment]
I do this also. I wonder if an API might stop people refreshing the actual page and cut down on server usage. Interesting question.

**Comment by Sonozuki** [comment]
Hadn't thought of the potentially reduced server load in that respect, certainly interesting

**Comment by Pickysaurus** [comment]
Moved to here: https://feedback.nexusmods.com/posts/16/notifications-api
