### ISSUE TITLE
Some mods are missing from Trending Mods

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#1368]
For example this mod has 18 Endorsements (at the time of posting this issue): https://www.nexusmods.com/skyrimspecialedition/mods/50461? but it isn't displayed in Trending Mods: https://www.nexusmods.com/skyrimspecialedition/mods/trending/?BH=0 among other 20-15 Endorsements mods. 

I saw it happen to many different mods already, might be worth checking?

**Comment by Pickysaurus** [comment]
This should have been resolved some time ago. Sorry for not replying sooner.
