### ISSUE TITLE
1-10kbps/RTO download speed on free. See attached pictures for your reference.

### ISSUE THREAD

**Issue by jerrykhodoughnutoh** [Nexus-Mods/web-issues#1369]
URL: supporter-files.nexus-cdn.com
Username on the Nexus: CaptRicoPH/jerrykhodoughnutoh@gmail.com
Bug/error being reported: 1-10kbps/RTO download speed
Steps to reproduce: pinged and tracerouted supporter-files.nexus-cdn.com
Expected result: 2mbps download speed
Actual result: 1-10kbps/RTO download speed
Link to the affected mod/image (if relevant): 
![image](https://user-images.githubusercontent.com/85025418/120073463-fb7afc00-c0ca-11eb-8395-250765340a36.png)
![image](https://user-images.githubusercontent.com/85025418/120073509-2bc29a80-c0cb-11eb-8cbb-cd615d69c108.png)

**Comment by Pickysaurus** [comment]
Hi there,

Sorry to hear about your issue. Please see the help page below for instructions on how to test your connection and the best place to post the results. 

https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
