### ISSUE TITLE
updates are still not fixed (10/5/17)

### ISSUE THREAD

**Issue by heavyoak** [Nexus-Mods/web-issues#137]
![fireshot capture 037 - skyrim nexus - mods and community - https___rd nexusmods com_skyrim](https://user-images.githubusercontent.com/6599392/31241555-ccb13cb6-a9c9-11e7-899c-b534c11d10d9.png)
![fireshot capture 038 - skyrim nexus - mods and community - https___rd nexusmods com_skyrim](https://user-images.githubusercontent.com/6599392/31241575-e27d5156-a9c9-11e7-9c90-9dac88a7b5e7.png)

still not fixed. also, get rid of the all caps, I don't need a website screaming at me.

**Comment by mrmason** [comment]
If this is a new bug report regarding the updates, then please can you provide some more information about how this bug has happened - or if this is a current issue already reported, then please post in that bug so we can track it and know what's going on.

In terms of the all caps - as specified in the post we made regarding the new re-design - the time for making design choices is closed for now - there was a 12 month period where the community was able to influence the design, which they did heavily. 

We are open to listening to what people want changed after we've finished fixing bugs and missing features - we've even just hired a new UI/UX designer who will make decisions on this - however none of this is going to get changed on a whim.

**Comment by heavyoak** [comment]
you don't seem to be paying attention.  this issue was marked as "fixed" in #127  but its not.

also, the community influence was closed/not public. there was never any mention of a site redesign in the public areas until the post on reddit.

**Comment by mrmason** [comment]
I'm re-opening #127 - please add any relevant information you have in there.

**Comment by mrmason** [comment]
Sorry - I'm re-opening #113 as #127 is a duplicate.
