### ISSUE TITLE
Game won't show up in the Vortex 

### ISSUE THREAD

**Issue by river425** [Nexus-Mods/web-issues#1370]
## Your username/username(s) affected
river425

## Bug/error being reported:
I have the game fallout 4 installed but when I go to the vortex it is not there.  I have used the vortex before with the fallout 4 game but now it is gone.   I have logged into the game, and it still well not show up the list of unmanaged games.   Please help

**Comment by mrmason** [comment]
I'm afraid this is the website bug tracker - you'll be better served here - https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/
