### ISSUE TITLE
No feedback is given when submitting a file report

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#1371]
Go to any file, click the "Report Abuse" button on the description page. Fill out the form as normal.

When the report is submitted, no feedback is given to the user on whether it succeeded or failed.

**Comment by Pickysaurus** [comment]
If the modal disappears, that generally means it succeeded. I can see that this could use some improvement.

**Comment by Pickysaurus** [comment]
Moved to here: https://feedback.nexusmods.com/posts/241/show-a-confirmation-when-submitting-a-mod-report
