### ISSUE TITLE
Add a fried faked - I never did add someone as friend but again get messge that I had done it

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1374]
https://www.nexusmods.com/users/5872020
18 June 2021, 9:46PM
    Dreifels added NanakiSaikome as a friend

I had not done it and the other of NanakiSaikome look suspect, too
(In fact, I never did add someone as friend, so all with same entry are fakes)

https://www.nexusmods.com/users/66172361/

Hacked site?

**Comment by Pickysaurus** [comment]
If your account is set to auto accept friend requests (default) this is normal. This is not a bug or a "hack".

**Comment by Dreifels** [comment]
I understand that one can mane me as friend, but but decide what I do.
How to remove this autorequest? I do NOT want to make one as friend autimatically and give wrong impression about relations.
A friend is a rate status, otherwise you can add all users instantly and make it worthless anyways.
If one clicks another t o become friend, so he espressses that he does like him, but forcing that the other does like the opponemt is grotesc.
