### ISSUE TITLE
Files - Download counter not working proper

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1375]
https://www.nexusmods.com/skyrimspecialedition/mods/48761?tab=files
total downloads = 0, unique downloads = 0
but I had download it before, so minimum 1 shouldbe shown
![001](https://user-images.githubusercontent.com/40837496/122644231-735da480-d114-11eb-8f6a-dcb1c2378b96.jpg)

**Comment by Pickysaurus** [comment]
This may have been a temporary issue, but I cannot replicate it.

If the issue persists, it will be your browser addons/settings blocking the JavaScript which is used to update the counts: https://help.nexusmods.com/article/113-troubleshooting-website-issues
