### ISSUE TITLE
Download History Lost?

### ISSUE THREAD

**Issue by alfaz62** [Nexus-Mods/web-issues#1376]
## Your username/username(s) affected
-Alfaz62

## Bug/error being reported:
Mod page says i never downloaded the mod before, and all records of all the iterations i've downloaded no longer appear.

## Steps to reproduce:
in Mo2, i clicked "visit nexus page" and it took me to the correct page. my account was signed in.  the description page said i had never downloaded with red x. the downloads tab had no history of any of my downloads.

its so broken it doesnt even have steps. i just open the page and its bugged immediately on all DL history notifies.

### Example:
1. Open the page    
2.  see bug
3. 
-->

## Expected result:
![image](https://user-images.githubusercontent.com/77950426/122653207-089e7000-d0f8-11eb-8b05-14ebcbc484b2.png)
![image](https://user-images.githubusercontent.com/77950426/122653241-3d122c00-d0f8-11eb-8ebb-6a9c3882a150.png)
![image](https://user-images.githubusercontent.com/77950426/122653248-4c917500-d0f8-11eb-94bb-97a509b8041d.png)

## Actual result:
![image](https://user-images.githubusercontent.com/77950426/122653170-d856d180-d0f7-11eb-9eb3-cffb8c2e35f9.png)
![image](https://user-images.githubusercontent.com/77950426/122653183-ea387480-d0f7-11eb-8f93-b2781fe2d5d1.png)
![image](https://user-images.githubusercontent.com/77950426/122653299-91b5a700-d0f8-11eb-83e5-54a8f4decf36.png)

**Comment by rbarkhordar** [comment]
The same thing is happening to me. Just started today. Didn't change any settings. My extensive download history is just not being recognized by Nexus anymore. Hopefully this is something on Nexus-Mods side and they will address it soon? Frustrating. At least it is not affecting anything on Vortex or my games.

**Comment by FireGeneral** [comment]
Same issue is happening to me...
I've downloaded more than 3000+ mods from Nexus Now!!
Now my tracked mods look like a total mess....
Please fix this!!! And hopefully not require us to download everything ALL OVER AGAIN!!!!!

**Comment by mrmason** [comment]
Thanks for the report - this should all be working now and no data has been lost.
