### ISSUE TITLE
Problem with missing games in Vortex

### ISSUE THREAD

**Issue by MegaMorticas** [Nexus-Mods/web-issues#1378]
URL: 
Username on the Nexus:  volp9072

Bug/error being reported: 

In the vortex mod manager app i have been moding Skyrim SE for the past few days and now all of a sudden, vortex suddenly does not recognize Skyrim as a game, it no longer appears on my "games" tab and i cant find it in the "search games" feature to add games to your library. i have also tried setting a custom destination for vortex to search for the game directly in the Skyrim folder and it still does not find any thing. The Nexis website still recognize it as a game so I'm not sure what to do.

Steps to reproduce: (unknown)

Expected result:
login in to vortex on my pc and have access to Skyrim se as my active game to mod.
Actual result:
vortex no longer recognizes it as a game.

Link to the affected mod/image (if relevant): (none)

**Comment by Pickysaurus** [comment]
This tracker is for support with the Nexus Mods website. Please post in our support forums for Vortex issues: https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/
