### ISSUE TITLE
Getting Ads as a Premium Member

### ISSUE THREAD

**Issue by DarthFalcon** [Nexus-Mods/web-issues#1379]
## Your username/username(s) affected
DarthFalcon

## Bug/error being reported:
getting ads as a premium member

## Steps to reproduce:
just visiting the site

## Expected result:
no ads

## Actual result:
ads on every page
![firefox 06_21 317](https://user-images.githubusercontent.com/16762617/122812389-9ec0ca80-d29f-11eb-8a63-830ecb915405.png)
![firefox 06_21 318](https://user-images.githubusercontent.com/16762617/122812474-b8621200-d29f-11eb-920e-1ddc59efa443.png)
![firefox 06_21 319](https://user-images.githubusercontent.com/16762617/122812571-d4fe4a00-d29f-11eb-80d0-031af6ebdddb.png)

**Comment by Pickysaurus** [comment]
Sorry about this. Our ad provider has changed the ad code and cause this little ad to sneak through. We're working with them to resolve the issue.

**Comment by DarthFalcon** [comment]
not a problem, just thought I should report it :) thanks for the swift response!

**Comment by Pickysaurus** [comment]
It was actually fixed when I commented, so should be fine now :) We're looking into the cause to see if there is anything we can do better to stop this from happening again.
