### ISSUE TITLE
Premium not working even though i paid for it

### ISSUE THREAD

**Issue by HojoWo** [Nexus-Mods/web-issues#1381]
## Your username/username(s) affected
HojoWow

## Bug/error being reported:
Premium not working

## Expected result:
Going to download using premium 
## Actual result:
Didnt also dont have premuim

**Comment by BigBizkit** [comment]
Hi there, sorry to hear about this issue.

Could you please send an email to support@nexusmods.com about this problem from the email attached to your account and providing a receipt? Thank you!
