### ISSUE TITLE
Premium days left can go in the negatives

### ISSUE THREAD

**Issue by thepwrtank18** [Nexus-Mods/web-issues#1384]
## Your username/username(s) affected
TheTank2007

## Bug/error being reported:
Premium days left go in the negatives instead of expiring

## Steps to reproduce:
1. Get premium
2. Wait 30 days
3. See it hit the negatives

## Actual result:
Premium hits the negatives, effectively lasting forever

![image](https://user-images.githubusercontent.com/57580668/124225492-24791d00-dacd-11eb-9c61-39a52a48999b.png)

**Comment by Pickysaurus** [comment]
We are currently upgrading our membership system, which should resolve this issue.
