### ISSUE TITLE
Server error preventing mod file uploads

### ISSUE THREAD

**Issue by finley243** [Nexus-Mods/web-issues#1385]
## Your username/username(s) affected
finley243

## Bug/error being reported:
Unable to upload file to existing mod. Upload progress bar appears but does not make move (stuck at 0%). Chrome console shows a 500 status code with the message "Failed to load resource" immediately after clicking the upload button (no errors are shown on the page itself). The file I am trying to upload is a 4.86 KB zip archive, though I have tried uploading other files (just to see if it would work) and I get exactly the same behavior.

## Steps to reproduce:
1. Go to "My Mods" and click "Manage files" on the mod (I have also tried clicking Manage -> Files from the mod page).
2. Click "Or browser for files" and select the file (I have also tried dropping the file on the uploader).

## Expected result:
File uploads successfully.

## Actual result:
Progress bar appears, 500 status code appears in the console, and nothing else happens.

**Comment by SlavicPotato** [comment]
Experiencing this too, POST https://upload.nexusmods.com/uploads/chunk responds with code 500.

**Comment by donZappo** [comment]
Same. Trying to upload a 141 Mb file. The progress bar gets about 25% complete, then jumps to the end and the file never uploads. Same error code reported in Chrome. Attempting to upload it using Edge also results in the same problem.

**Comment by mrmason** [comment]
Thanks for the report - this should be fixed now, and shouldn't happen again - a script that cleans up old files wasn't functioning correctly.
