### ISSUE TITLE
Premium paid, but no benefits.

### ISSUE THREAD

**Issue by mickplouffe** [Nexus-Mods/web-issues#1388]
## Your username/username(s) affected

Mickplouffe

## Bug/error being reported:

Just paid the premium and still have Max 2MB/s

## Steps to reproduce:

Have full speed download.

## Actual result:

Locked at 2MB/s

![image](https://user-images.githubusercontent.com/1342758/125879317-f06b8f44-70f1-42ec-920a-d82df729914a.png)
![image](https://user-images.githubusercontent.com/1342758/125879325-ab7b92e0-b113-4496-b6db-adba7cdd630a.png)

**Comment by Pickysaurus** [comment]
Please content support@nexusmods.com if this issue persists.
