### ISSUE TITLE
Bottom of images on New RD Mod pages are being obscured by the Title bar

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#139]
Bottom of images on New RD Mod pages are being obscured by the Title bar

Go to https://rd.nexusmods.com/skyrimspecialedition/mods/12649?tab=images

There are three images there designed to show the difference between nipple choices out of the diffuse map options, followed by another bunch showing differences between pubic hair options .. But part of the image is obscured by the title strip at the bottom in the middle.
The top of the image also has a faded bar with the tools on it which also semi obscures details of the images.

Screenshot in case its Browser specific - https://i.imgur.com/etEslUz.png

I use Open Source Chromium http://chromium.woolyss.com/

Could we have unobscured presentation of images please :)

Maybe put the image in-between these bars ?.
Or how about having the film strip of other images vertically up the left side, with controls on the right ? (seeing as most screens are wide screen these days, even on laptops, vertical screen space is a premium). Thanks in advance.

**Comment by mrmason** [comment]
Playing around with this I can see what you're saying - it seems to be only quite small resolutions that this effects - we will have a look and see if there are any other options to deal with this, but it won't be a priority right now.

**Comment by m0lz** [comment]
Thank you, presentation is quite important for mods, and people being able to see the difference between options is vital to make choices, when users have to start right clicking and opening images in new tabs because the source page is obscuring their view .. Your web design has failed in its user friendliness.

**Comment by iamtiz** [comment]
Closing this, keeping #284 open
