### ISSUE TITLE
Bug Report tab broken, only on one of my mods.

### ISSUE THREAD

**Issue by AnteMaxx** [Nexus-Mods/web-issues#1390]
URL: https://www.nexusmods.com/baldursgate3/mods/97?tab=bugs&BH=0
Username on the Nexus: AnteMaxx
Bug/error being reported: I cannot view reported bugs on my BG3 mod, Basket Full of Equipment NSFW mod's Bugs tabs. When I try to open an issue, there is just a huge empty window. Even zooming out on the page did not reveal any content.
Steps to reproduce: Go to the URL and try to open a Bug Report
Expected result: Bug report opens.
Actual result: Empty grey window opens.
Link to the affected mod/image (if relevant): https://imgur.com/a/G6nvNck

**Comment by Pickysaurus** [comment]
This is because a user attempted to directly post an image into the bug reply, an action that is not supported.

I have removed the offending comment.
