### ISSUE TITLE
Time is one hour ahead

### ISSUE THREAD

**Issue by lawliet89** [Nexus-Mods/web-issues#1391]
## Your username/username(s) affected

lawliet89

## Bug/error being reported:

The times shown on Nexusmod is one hour ahead of the real time. The right timezone is set (+8). No DST is in place.

## Expected result:

Actual time

## Actual result:

+1 hour from actual time

If you look at the screenshot below, the time now is 10am. But the comment I just posted is listed as being one hour in the future.

![image](https://user-images.githubusercontent.com/983101/126923585-7133a003-d4e5-474c-9101-2a9e96e414b6.png)

**Comment by Pickysaurus** [comment]
This is an issue with DST in the United States, some parts of the website do not currently cater for it and use BST (British Summer Time) instead.
