### ISSUE TITLE
Bosses despawned

### ISSUE THREAD

**Issue by Nandersun** [Nexus-Mods/web-issues#1392]
## Steps to reproduce:
<!-

###
1. Enter Deepest Crevice and die multiple times to the fireball caster in the small room
2. Exit deepest crevice without killing the enemies to better prepare for the fight
3. Reenter deepest crevice
-->

## Expected result:
<!— Fighting the two enemies after being better prepared for them -->

## Actual result:
<!— The enemies despawned with seemingly no way to have them return -->

**Comment by Pickysaurus** [comment]
This tracker is for issues with the Nexus Mods website. Please post on the mod page you need help with for advice on this problem.

**Comment by Nandersun** [comment]
Oh ok, I’m sorry about that I was unaware.

Thank you for letting me know!
