### ISSUE TITLE
Error trying to buy Skyrim SE with points

### ISSUE THREAD

**Issue by Bl00dsire** [Nexus-Mods/web-issues#1393]
So I tried buying Skyrim SE with nexus points in their store, but the site keeps giving me an error during the purchase. Does anyone know what might be the issue? I have a verified email and enough points to buy it.

**Comment by Pickysaurus** [comment]
Without more specific information on the error, my best guess is your browser addons are causing it. Please see https://help.nexusmods.com/article/113-troubleshooting-website-issues for advice.

**Comment by Pickysaurus** [comment]
This should now be resolved
