### ISSUE TITLE
Unable to download "Base Coat" for Skyrim SE

### ISSUE THREAD

**Issue by xii7** [Nexus-Mods/web-issues#1394]
## Your username/username(s) affected
xii7

## Bug/error being reported:
Unable to download Base Coat for SSE manually or via Wabbajack

## Steps to reproduce:
1. https://www.nexusmods.com/skyrimspecialedition/mods/46850
2. Download file - CDN, or any server
3. File fails to download due to Network Error

## Expected result:
Successful download of Base Coat manually or through Wabbajack

## Actual result:
File fails to download manually - Network error
File halfway downloads in Wabbajack, then stalls at the halfway point.

[Wabbajack 2021-08-02 10_15_08.log](https://github.com/Nexus-Mods/web-issues/files/6920438/Wabbajack.2021-08-02.10_15_08.log)

[1.zip](https://github.com/Nexus-Mods/web-issues/files/6920440/1.zip)

**Comment by Pickysaurus** [comment]
Wabbajack is not an application we provide support for. If you are unable to download manually please see the troubleshooting guide: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

You may want to try using a VPN to see if that improves your connection?
