### ISSUE TITLE
Bypassing the email address verification at https://users.nexusmods.com/register

### ISSUE THREAD

**Issue by frame** [Nexus-Mods/web-issues#1397]
## Your username/username(s) affected
n/a

## Bug/error being reported:
I believe I found a way to bypass the email-validation at the user registration screen (https://users.nexusmods.com/register)

## Steps to reproduce:
1. Open https://users.nexusmods.com/register (logout first or use an incognito window)
2. At **Step 1 of 3**: Enter `support@nexusmods.com` as email address (I used this one for my test), solve the hCaptcha and click on "Verify Email".
3. At **Step 2 of 3**: Here you're supposed to enter the 4 digit code sent to the email provided at step 2, but we're entering something else:
4. Type in `%` into all input fields
5. Open the Developer Tools and "inspect" the first input field. Change the attribute `pattern="[0-9]"` to `pattern="[0-9\%]"`
6. Repeat for the other three input fields
7. Click on "Verify Email"

## Expected result:
The server should not consider the email validated and return to **Step 2 of 3**.

## Actual result:
The registration proceeds to **Step 3 of 3**. I suspect the DB query to match the 4 digit code doesn't filter out non numbers properly and maybe even uses a LIKE-Statement to match. This would explain why `%` works. The fix could be a simple to change `LIKE` to `=`

![capture_20210803_164615](https://user-images.githubusercontent.com/339569/128036039-ed64d30b-2b63-4fdd-ab5a-fb8ed2fc350a.png)
![capture_20210803_162409](https://user-images.githubusercontent.com/339569/128036061-e3e75200-e92a-4aab-9682-3b5699ed68c4.png)
![capture_20210803_162541](https://user-images.githubusercontent.com/339569/128036086-44e616ab-3b26-4a99-91ee-23cedfccaf20.png)

**Comment by mrmason** [comment]
Thanks for the report - I assume that once you get to the create account page you can't actually create the account though - it should throw an error ?

**Comment by frame** [comment]
Hi @mrmason mrmason, I didn't proceed to create an account. I was just curious if I was able to get past the check (and I didn't want to create an account. I can repeat the test if you like, with a dummy email I control.

**Comment by mrmason** [comment]
Thanks - we'll do a bit more research into this on our end too.

**Comment by frame** [comment]
Note: I'm no longer able to reproduce this. After entering % I see now the expected "Validation code was incorrect" message. I did however get quite a few 503 error pages from Cloudflare while testing.

**Comment by Pickysaurus** [comment]
If this issue returns, feel free to reopen the ticket.

Thanks for the report.
