### ISSUE TITLE
Mod description editing: BBC showing up wrong/broken scrolling

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#14]
Sorry for the horrible title. Hard to explain. Images included:
https://www.dropbox.com/s/hjkysnqojgul6ki/Screenshot%202017-09-06%2000.15.21.png?dl=0

Left screen in image (preview mode):
BBC should not be appearing in this editor and it is in multiple places. Seems to be related to a change in how the size tag is handled but it makes it incredibly hard to edit old mods. 
Some BBC is also not showing up properly such as the image being encased in the same center tags as the small text below it, but not showing centered while the text is when in the preview mode, sizes and colors also being wrong for text

Right screen in image (BBC mode):
Every time you swap to BBC input the description is automatically scrolled down to the bottom of the description, regardless of where you are or were previously. Happens each time you swap between the modes, not just the first. Minor thing, but a big pain for larger descriptions.

Edit: As confirmed by others below, BBC in general is broken in descriptions majorly. Eg this mod page from rd or the main site:
https://www.nexusmods.com/skyrim/mods/68425
https://rd.nexusmods.com/skyrim/mods/68425

**Comment by RoyBatty64** [comment]
Can confirm, all BBCode formatting is broken to some extent. Fonts, sizes, colors.

**Comment by ousnius** [comment]
Can confirm, for mod pages and for comments.

**Comment by verenion** [comment]
Assigned PT#151002943

**Comment by verenion** [comment]
I've pushed a fix for the first issue, which was in fact a bug. I've created another issue as a "enhancement" for the second issue. #48
