### ISSUE TITLE
Search strips special characters, resulting in 'no matching entries' when searching for mods with these characters by name

### ISSUE THREAD

**Issue by SierraKomodo** [Nexus-Mods/web-issues#140]
An example mod is `CC's Enhanced Ore Veins SSE Edition` for Skyrim Special Edition - Searching for this exact string strips the apostrophe, searching instead for `CCs Enhanced Ore Veins SSE Edition` which doesn't find a match.

**Comment by SierraKomodo** [comment]
Discovered to be doing the same with the dash (`-`) - Example mod for this scenario being `Realistic Dialogue Overhaul - RDO SE`, also for Skyrim Special Edition

**Comment by mrmason** [comment]
Assigned `PT#151756138`

**Comment by verenion** [comment]
Fix has been pushed
