### ISSUE TITLE
Cant remove or add games on favorites list

### ISSUE THREAD

**Issue by TheGrandSage23** [Nexus-Mods/web-issues#1401]
TheGrandSage23

Not letting me remove any game from favorites list.. I get a 'There's a problem with your request"

 ## Expected result 
remove game and add new game to favorites

## Actual result:
removed game was re-added and would not let me add new game, there was a problem with your request

**Comment by steampilot** [comment]
I had the same Problem.
I deleted the Nexusmods.com web cookies.
Restarted the browser, and logged into my account again.
now the removed games show as removed and i am able to add other games

Possible Sollution: Delete the Cookies and restart.

**Comment by linkpascual** [comment]
Also have this problem... deleting cookies did not help. restarted browser as well... nothing. Using Chrome.
