### ISSUE TITLE
Unable to pay for Premium Membership

### ISSUE THREAD

**Issue by MuniversalRabat** [Nexus-Mods/web-issues#1403]
## Your username/username(s) affected
MuneSol

## Bug/error being reported:
When I try to make a payment to reactivate my Premium Membership, it gives me an error message to try again later, and I've been trying for about 24 hours now.

## Steps to reproduce:
1. Click upgrade to Premium
2. Enter Payment Method
3. Select either the Monthly or Yearly payment amount.
4. Click to process the payment
5. Afterwards, an error message pops up and the payment does not go through.

## Expected result:
Payment processes and I get the Premium Membership again

## Actual result:
I get an error message and nothing happens.

**Comment by mrmason** [comment]
Hello, thanks for the report - we've fixed a number of bugs in the last few days so hopefully this should work for you now - please let us know if it doesn't.

**Comment by AlexKirko** [comment]
Still an issue for me. Login is AMatamune.
