### ISSUE TITLE
Fallout 76 support isn't working properly

### ISSUE THREAD

**Issue by Eliasyoussef47** [Nexus-Mods/web-issues#1405]
## Your username
Elias47

## Bug/error being reported:
The extension [Fallout 76 Support (Wastelanders)](https://www.nexusmods.com/site/mods/110) is the official support extension in Vortex for Fallout 76, but the main version (1.0.0) doesn't work properly.

With version 1.0.0 of this extension (which is the main file) the mods downloaded for Fallout 76 are not added to the "Fallout76Custom.ini" file, which results in the downloaded mod not working in the game.
However, the beta version of that extension (version 2.0.0) seem to be working properly. The beta version was uploaded on 13 Jan 2021 but the author has still not made it the main file.
Seeing how Vortex automatically downloads the main file, many people get a non working version, which makes Vortex pretty much useless to the people unaware of the beta version.

The author of this extension doesn't seem to be responding to any posts or bug reports on the extension's page on NexusMods.com.

I would like for the beta version to be set as the main file so that Vortex installs a working version without any confusion for the users.
## Steps to reproduce:

1. Start managing Fallout 76 in Vortex. Vortex will prompt you to download the support extension for the game.
2. Download a mod for Fallout 76 that requires registration in the "Fallout76Custom.ini" file using vortex.
3. Start the game and notice that the mod isn't working.

## Expected result:

Version 2.0.0 of the [Fallout 76 Support (Wastelanders)](https://www.nexusmods.com/site/mods/110) should be the main file, which will result in Vortex downloading a working version.
Then, when downloading a mod, the mod should automatically be added to the "Fallout76Custom.ini" file.
## Actual result:

Downloaded mods aren't added to the "Fallout76Custom.ini" file. Resulting in the mods not working in Fallout 76.

**Comment by Pickysaurus** [comment]
Please report this to the extension developer, we do not maintain this extension.

**Comment by Eliasyoussef47** [comment]
@Pickysaurus As I said in my initial post. The extension developer is ignoring all bug reports and this extension is being used as the main Fallout 76 support in Vortex.

I don't know if this is the right place but I'm asking for support about how to solve this problem.

**Comment by Eliasyoussef47** [comment]
[This has been resolved. ](https://github.com/Dakraid/Vortex_Fallout76/issues/2)
