### ISSUE TITLE
Error 522 - Connection Timeout

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1406]
ff7legend

Error 522 - Connection Timeout

1. Attempt to navigate to any Nexus site (Skyrim Special Edition Nexus in my case)
2. Watch as a blank page attempts to load...
3. Error 522 - Connection Timeout is displayed in the browser (Windows 10 Pro - Google Chrome)

Skyrim Special Edition Nexus homepage displayed on my screen.

Error 522 - Connection Timeout is prominently displayed instead.

**Comment by verenion** [comment]
Thanks for the report, we are aware of the issue and are currently investigating.
