### ISSUE TITLE
Feature request: Deleting your posts and/or bug reports

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1407]
It would be nice if it were possible to delete your posts, especially considering that you can edit them at any time anyway. The lack of this feature results in many posts when people ask a question and then edit their post writing that they found the answer, or report an issue and then edit the post writing that the problem was another mod, or just edited comments like "sorry, please delete my post" (tbh i even did some of that myself).
Same applies to bug reports. Why if i hastened to report a bug and then realised i was doing something wrong, i can't just delete my own report? And then reports like that remain forever on mods, whose authors are inactive.

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/247/allow-users-to-delete-their-own-comments-bug-reports
