### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by Quirinea** [Nexus-Mods/web-issues#1408]
Quirinea (may affect everyone)

502 Bad gateway trying to download a mod

https://www.nexusmods.com/stardewvalley/mods/7286?tab=files
Choose manual download of the topmost file.
Choose Download
Choose Slow Download

https://supporter-files.nexus-cdn.com/1303/7286/Ridgeside%20Village-7286-1-2-14-1629163528.zip?md5=5qVKn8pCcN5OcGnir4kOmA&expires=1629201296&user_id=64556811&rip=82.181.197.96

## Step502 Bad Gateway
nginx/1.15.1

Expected result: Downloading the file

Actual result: Error 502.

**Comment by mrmason** [comment]
please can you run a ping against `support-files.nexus-cdn.com` and let me know the result ?

**Comment by Quirinea** [comment]
laura@Tullius:~$ ping supporter-files.nexus-cdn.com
PING supporter-files.nexus-cdn.com (185.152.65.129) 56(84) bytes of data.
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=5 ttl=57 time=50.7 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=19 ttl=57 time=68.4 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=20 ttl=57 time=49.4 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=21 ttl=57 time=53.9 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=22 ttl=57 time=50.8 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=23 ttl=57 time=50.8 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=24 ttl=57 time=49.0 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=25 ttl=57 time=51.4 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=26 ttl=57 time=57.1 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=27 ttl=57 time=64.1 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=28 ttl=57 time=47.8 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=29 ttl=57 time=56.3 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=30 ttl=57 time=57.4 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=31 ttl=57 time=51.5 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=32 ttl=57 time=60.6 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=33 ttl=57 time=52.1 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=34 ttl=57 time=53.6 ms
64 bytes from unn-185-152-65-129.datapacket.com (185.152.65.129): icmp_seq=35 ttl=57 time=51.3 ms
^C
--- supporter-files.nexus-cdn.com ping statistics ---
35 packets transmitted, 18 received, 48% packet loss, time 34429ms
rtt min/avg/max/mdev = 47.861/54.281/68.448/5.370 ms

And when I just looked at the site the "please endorse" popup appeared, but it was impossible to endorse (nothing happened when I tried to click. The same problem, I presume.

**Comment by mrmason** [comment]
Can you please check again now - this should be fixed.

**Comment by Quirinea** [comment]
Yes, works now.
