### ISSUE TITLE
All the "Downloaded" tags are missing.

### ISSUE THREAD

**Issue by FireGeneral** [Nexus-Mods/web-issues#1409]
FireGeneral

The tags which are used to indicate the mods users have downloaded have disappeared.
We can no longer "endorse" any mods anymore.

## Steps to reproduce:
1. Go to Skyrim or Skyrim SE mod page.
2. Notice the tags are all gone.

## Expected result:
Restore the tags, hopefully without needing us to re-download everything all over again...
These kinds of things have already happened before~

## Actual result:
Already Fixed!! Nice!!
Thanks!

**Comment by Putinizer** [comment]
No, not already fixed. Still getting the issue as of right now.
