### ISSUE TITLE
502 Bad Gateway + 524

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1413]
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files&BH=0
Error 502 Ray ID: 687f30c66c25fad8 • 2021-09-01 14:30:16 UTC
Bad gateway

www.nexusmods.com
Host
Error

Cloudflare Ray ID: 687f30c66c25fad8 • Your IP: 87.78.221.99 • Performance & security by Cloudflare

https://www.nexusmods.com/oauth/callback?code=zpmP9l-uIVl4V0LNlcgaGvuln6v66ceXbcO0vGsfmCQ&referral_url=%2F%2Fwww.nexusmods.com%2Fskyrimspecialedition%2Fusers%2F5872020%3Ftab%3Duser%2Bfiles%26BH%3D0

Error 524 Ray ID: 687f3827aa5c876a • 2021-09-01 14:36:05 UTC
A timeout occurred

www.nexusmods.com
Host
Error

Cloudflare Ray ID: 687f3827aa5c876a • Your IP: 87.78.221.99 • Performance & security by Cloudflare

**Comment by Pickysaurus** [comment]
We're aware of this issue and working on a solution. Thanks for your patience.
