### ISSUE TITLE
Tracking a mod scrolls to the top of the page.

### ISSUE THREAD

**Issue by iaz3** [Nexus-Mods/web-issues#142]
Url: All

When clicking the track button, the page scrolls to the very top, losing the current position and making it hard to track more than one interesting mod on, for example, search results or the home page with it's popular/new today tabs

Expected result: Do not destroy the current page/scroll position.
Actual result: Destroys the current page/scroll position

**Comment by Rrrafau** [comment]
assigned #151755369

**Comment by Nazenn** [comment]
Actually, doing almost anything that opens a notification or confirmation window scrolls to the top of the page. I only just really noticed it now, but this goes for a lot more then just tracking

**Comment by valiantshadow** [comment]
Also occurs when endorsing mods on your user download page: https://rd.nexusmods.com/users/myaccount?tab=download+history

When endorsing a large amount of mods, it scrolls back to the top with every endorsement, which is extremely annoying.

**Comment by iamtiz** [comment]
This shouldn't happen anymore

**Comment by Nazenn** [comment]
Confirmed fixed, thank you
