### ISSUE TITLE
400 Bad Request Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by HollowedHorizon** [Nexus-Mods/web-issues#1420]
##HollowedHorizon

## Steps to reproduce:
1. Step 1-Click on Nexus Mod Website
2. Step 2-Click on SkyrimSE 
3. Step 3-Click on any SkryimSE mod

## Expected result:
 Being able to access SkyrimSE mod

## Actual result:
Recieve 400Bad Request message

**Comment by ShadyBunny** [comment]
Having this very same issue. Can't view any mods on Nexus for Skyrim SE.

**Comment by hngdog** [comment]
seems to be working now

**Comment by Pickysaurus** [comment]
Can't replicate this so it was likely a temporary problem
