### ISSUE TITLE
Blank web pages (Nexus)

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#1421]
ff7legend

Blank Nexus pages

1. Navigate to any Nexus homepage/mod page
2. Watch as the Nexus loads a blank page with only the background graphic loading
3. Refreshing/navigating to another Nexus page gives the same result.
4. Nexus Forums/Messenger seems to be working just fine.

Nexus home page with all appropriate links, etc displaying properly

Blank Nexus pages with only the background graphic loading...

**Comment by IrishmansLuck7** [comment]
![image](https://user-images.githubusercontent.com/91681448/135475097-12f09bc2-75ce-4021-999b-75dea46f86f9.png)
I believe mine is doing the same thing.

**Comment by scjohnson1981** [comment]
Glad I'm not the only one experiencing this...  Beyond RIDICULOUS.  Never have I witnessed a website with so many issues like I have the Nexus over the past decade...

**Comment by scjohnson1981** [comment]
Update: Now I'm getting an Error 521 - Web server is down splashed across my screen via Cloudfare...  Seriously, what the heck is up Nexus?

**Comment by IrishmansLuck7** [comment]
![image](https://user-images.githubusercontent.com/91681448/135478712-12b81b35-d0ee-424f-b071-54de25d12b22.png)
Just trying to get this some more attention

**Comment by IrishmansLuck7** [comment]
We're back up!

**Comment by scjohnson1981** [comment]
The site may be back up but for how long?  I've never seen a website that is so buggy/glitchy/has so many issues running properly over the past decade as I have with the Nexus...  As the old saying goes, "If it ain't broke, DON'T FIX IT".
