### ISSUE TITLE
Drop Down Menu's not working

### ISSUE THREAD

**Issue by echie173** [Nexus-Mods/web-issues#1422]
## Your username/username(s) affected
echie173

## Bug/error being reported:
 None of the dropdown menus on the website are working. Mods, Media, Support, Messages, Notifications, Profile, nothing

## Steps to reproduce:

Literally try to click on anything that would give a dropdown 

## Expected result:
 I would get a dropdown 

## Actual result:
 didn't get a dropdown 

##EDIT
only having this issue in chrome, edge seems to be working fine

**Comment by Pickysaurus** [comment]
Do Ctrl+F5 and try again :)

**Comment by NucclearGandhi69** [comment]
I'm having the same issue and cannot fix it

**Comment by Pickysaurus** [comment]
See my previous post for the fix. Your browser either had a bad version of the site JavaScript files or you have browser addons blocking it.
