### ISSUE TITLE
cannot download mods on nexus

### ISSUE THREAD

**Issue by npthinh1** [Nexus-Mods/web-issues#1423]
## Your username/username(s) affected

npthinh
## Bug/error being reported:

cannot download mods on nexus, apear on vortex's download but stuck on pending, sometime the download said that the connection was not permitted and need to change the fire wall setting even though the fire wall was off and if try to download manually, the connection error pop out, sometime it will start the manual download but after that it will fail during the download
## Expected result:

the mods gets download 
## Actual result:
![image_2021-10-02_191012](https://user-images.githubusercontent.com/91771695/135715531-1e5f184e-272b-4bb3-a63b-cced464c215c.png)

the mods stuck on pending

**Comment by Pickysaurus** [comment]
This should be resolved if you retry. You can report issues with Vortex itself via the top-right menu of the app.
