### ISSUE TITLE
Search does not find a mod Perfection Tweaker

### ISSUE THREAD

**Issue by Quirinea** [Nexus-Mods/web-issues#1424]
## Your username/username(s) affected
Quirinea
## Bug/error being reported:
Mod "Perfection Tweaker" not found by search

## Steps to reproduce:
1) searchword "Perfection" did not return anything
2) searchword "Tweak" gave a list of mods having "tweak, tweaks, tweaked etc." in their name but not the one I was searching.

## Expected result:
Finding the mod "Perfection Tweaker" and possibly some others containing that word
nexusmods.com/stardewvalley/mods/8615
## Actual result:
Nothing found

I found the mod seemingly intact (not hidden or the like) by browsing my downloads.

**Comment by Pickysaurus** [comment]
Seems to show for me. Perhaps you have a tag blocked?
![image](https://user-images.githubusercontent.com/31670524/135981577-321023f7-e029-4699-ad4f-0189a2d103a1.png)
