### ISSUE TITLE
Long delay before edited comments are updated

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#143]
If you edit a comment under the 'posts' tab, it takes a while (≈3.5 minutes) for the new text to appear on the redesigned site. (If you switch to the old design, the new text is shown immediately.)

**Comment by Rrrafau** [comment]
assigned #151755381

**Comment by Pickysaurus** [comment]
This seems to be true of almost all changes. Like adding new changelogs etc

**Comment by iamtiz** [comment]
We'll look into that as well

**Comment by iamtiz** [comment]
Fixed
