### ISSUE TITLE
Endorsements counter not working proper

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1433]
Hello,
I see at
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files&BH=0
just 41 endorsements

but here that are 42
https://www.nexusmods.com/skyrimspecialedition/mods/57088

Best
Dreifels

**Comment by Pickysaurus** [comment]
Endorsement values are cached. They should show correctly after a short time.
