### ISSUE TITLE
Community Editor Program  Load Bug

### ISSUE THREAD

**Issue by DropBear1800** [Nexus-Mods/web-issues#1435]
## Your username/username(s) affected
Peter.genu@outlook.com

## Bug/error being reported:
Trying to start community editor the follow errors are received. 
Unknown Map Type 473 TotalyPlaytime
.... followed by
There was an error loading your account file.
You can load abackup to continue, a bug report on Discord would also be appreciated :)

## Expected result:
An explanation of what to do on my end. 
Note: I am not attached to the game files being saved, I would prefer it but I have the attitude that it is not precious, just a distraction.

**Comment by Pickysaurus** [comment]
Not a bug with the website
