### ISSUE TITLE
Mod not being displayed on "more trending"

### ISSUE THREAD

**Issue by austioxv** [Nexus-Mods/web-issues#1436]
## Your username/username(s) affected
austioxv

## Bug/error being reported:
Currently you have a mod showing up under hot mods and then a duplicate of it in "more trending", meanwhile my mod has disappeared from the list altogether, but remains on the standard trending list. My mod is https://www.nexusmods.com/skyrimspecialedition/mods/57370

## Steps to reproduce:
Look at the front page and more trending/trending sections

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
My mod to be listed under "more trending"

## Actual result:
It is not
![BikiniTimesTwo](https://user-images.githubusercontent.com/93229787/138972733-89db1a30-a56d-41c6-a280-16b1bf06d8f5.PNG)
![MyModTrendsHereButNotThere](https://user-images.githubusercontent.com/93229787/138972756-6c099f6f-4046-49dd-b4b4-445c0331f1a8.PNG)

**Comment by Pickysaurus** [comment]
This may have been fixed by an update to our site search around the time of the report. Or, you're filtering your own mod with your tag blocks.
