### ISSUE TITLE
no mods loading on website page

### ISSUE THREAD

**Issue by dayyluu** [Nexus-Mods/web-issues#1437]
stabbyshootyguy

## Bug/error being reported: I cant see any mods on the site for any game
no mods on any games page

## Expected result:
 i hope that the nexus team can help me fix this error as i would like to continue to use nexus for my mods.

![Screenshot 2021-10-29 221424](https://user-images.githubusercontent.com/93414767/139516983-6c567ba7-6efe-4fa7-a26a-c838c2228a38.png)

**Comment by Pickysaurus** [comment]
I see from the screenshot you have browser add-ons that look like they interfere with page loading. Can you please try either disabling the add-ons or try and reproduce in a different browser?
