### ISSUE TITLE
Banner can't be set using existing uploaded images.

### ISSUE THREAD

**Issue by Arindel** [Nexus-Mods/web-issues#144]
Missing functionality.

Can't change banner using existing images from modpage.

The only way I can change banner is by uploading another image from PC eventhough it's already uploaded as image on mod page.

**Comment by Rrrafau** [comment]
assinged #151835578

**Comment by RoyBatty64** [comment]
I reported this back in September and it was closed as can't reproduce.

**Comment by iamtiz** [comment]
We added this feature back a few weeks ago
