### ISSUE TITLE
Elle's Seasonal Buildings download bug

### ISSUE THREAD

**Issue by zuto1140** [Nexus-Mods/web-issues#1441]

**Comment by mrmason** [comment]
This file seems to be working correctly - please can you provide the URL of the file that is failing, and what is your location ?

**Comment by zuto1140** [comment]
> This file seems to be working correctly - please can you provide the URL of the file that is failing, and what is your location ?
> 
> ( by URL I mean the actual link for the download your browser is trying to download - not the URL for the file page )

I'm in Indonesia, and ( https://www.nexusmods.com/stardewvalley/mods/1993?tab=files&file_id=46800 ) is this what you mean? sorry if my English bad

**Comment by Pickysaurus** [comment]
Can't replicate the issue. 

Please re-open the ticket if it persists.
