### ISSUE TITLE
Virus on Nexus Mod!

### ISSUE THREAD

**Issue by PigeonGris07** [Nexus-Mods/web-issues#1442]

**Comment by Pickysaurus** [comment]
No detail provided. Please use the "Report abuse" button on the mod page.

Be aware, however, that all files on the site are scanned with at least 1 AV software before you can download them. Any positives from your installed AV program are likely to be a false positive

**Comment by PigeonGris07** [comment]
Hello. I put that here beacause i don't know where are the virus report. When i try to modding my Dark Souls 2 i downloaded this mod - "Dark Souls II FOV Fix (for original game and Scholar of the First Sin)" After downloading him with Vortex my virus scan sent me a message "Menace détectée" (i'm french, the message is in french) so "Malware Detected".  It was a trojan "Trojan:Win32/Glupteba!ml". I have a screen for proves it.
<img width="960" alt="Desktop Screenshot 2021 11 08 - 08 28 14 81" src="https://user-images.githubusercontent.com/93904407/140701106-5be4123a-1f8a-4073-97c5-2f3b6f2ac815.png">
So Please fix it or point me whare i can report virus, i don't find the section.
Sorry for my trash English, i'm pretty bad in english. Thanks for according me a little time to read and treat my message.

**Comment by Pickysaurus** [comment]
That looks like a false positive to me. Mods for DS2 often look like viruses even when they aren't
