### ISSUE TITLE
Error adding or removing favourite games

### ISSUE THREAD

**Issue by scottishdrunk** [Nexus-Mods/web-issues#1443]
## Your username/username(s) affected
matthewpeters12321@gmail.com

## Bug/error being reported:
when I delete a favorited game under My Games It remains in the selected category as a non-existent empty file that interrupts me from adding anything else to my gaming collection

## Expected result:
the file is to be expended from the category

## Actual result:

3667 has already been deleted. please refresh and try again. I've already done this step many times to no avail.

**Comment by Pickysaurus** [comment]
This is a known issue, it should self correct in a few hours

**Comment by disgusdad** [comment]
Occuring again today 3/26/2022, Google Chrome and Firefox

**Comment by Pickysaurus** [comment]
https://github.com/Nexus-Mods/web-issues/issues/1547
