### ISSUE TITLE
Clicking outside the length of a line does not position caret at the end of the line

### ISSUE THREAD

**Issue by avidichard** [Nexus-Mods/web-issues#1445]
**NM username:** avidichard

**Issue description:**
When in the editor to edit your description, if you click outside the line or a place where there is no text, the caret position will not show up or show up somewhere at the bottom of the editor box. I can't say which one it is because it seems random to me. Most of the times, the caret simply dissapears.

**Steps to reproduce:**
Image is self explanatory
![imgur screenshot of issue](https://i.imgur.com/xlsEffx.png)

**Browser used:** Microsoft Edge on Windows 11

**Expected result:**
Position caret at the end of the line.

**Actual result:**
Caret simply dissapears or is position elsewhere much lower in the editor box.

**Comment by Pickysaurus** [comment]
This is may unfortunately be just a limitation of the library we use for our text editor. https://wysibb.com/

**Comment by avidichard** [comment]
> This is may unfortunately be just a limitation of the library we use for our text editor. https://wysibb.com/

Well, about a year ago, this was not a problem (asside from the pasting issue, the rest was fine). So I guess you may have updated your text editor by then and this issue popped up. I can live with it, it's just very annoying, but I still submit mods. I just thought I had to share this issue now because it has been bothering me a few times when editing my descriptions. It obliges me to be ultra precise with my mouse to position my caret at the right place. Even on empty lines, I need to specifically position my mouse EXACTLY where the empty space is to start typing a text.

But, issue is reported so at least you know it. Thanks for the quick reply!

**Comment by avidichard** [comment]
Just got an update for this. Issue seems to happen on Microsoft Edge and other CHROMIUM based browsers. In Firefox, there is no issue and the text boxes work fine.

**Comment by Pickysaurus** [comment]
This issue will not be fixed as we're moving to a new editor in the future.
