### ISSUE TITLE
Submitting a reply to a bug report breaks the interface, preventing a second reply until you refresh the page

### ISSUE THREAD

**Issue by VlitS** [Nexus-Mods/web-issues#1448]
## Your username/username(s) affected
VIitS

## Bug/error being reported:
When I reply to a bug report on one of my mods, and then try to reply to a second bug report (or make an additional reply to the same one), the "Change status" dropdown becomes grayed out, and clicking submit to post the reply without changing the status does nothing. 

This was tested in Chrome, Firefox, and Edge. 
-Chrome is the only one with significant numbers of extensions or non-standard settings. 
-Firefox has a couple extensions, but the only one that should impact the page is uBlock Origin, and disabling it (which I don't mind doing since I have a lifetime membership so no ads) makes no difference, Chrome or Firefox. 
-Edge has no extensions, I have never used it on this computer before today, and it still has the same issue. 

Note: I was able to reply to a couple dozen comments without issue under the "Posts" tab, issue appears limited to bug reports. 

## Steps to reproduce:

1) Reply to a bug report on an owned mod (does not matter if you change the status).
2) Try to reply to a second bug report.

## Expected result:
I am able to reply to multiple bug reports.

## Actual result:
I have to refresh the page to reply to each report.

**Comment by Pickysaurus** [comment]
This is a known issue, but will not be fixed. 

We are currently working on a new bug-reporting system to replace the current one.
