### ISSUE TITLE
Search filter checkboxes are re-selecting after filtering

### ISSUE THREAD

**Issue by mrmason** [Nexus-Mods/web-issues#145]
1) Go to https://rd.nexusmods.com/skyrim/mods/
2) Filter the search > Go to attributes, uncheck ever box, and click apply
Page loads, filter has applied correctly, but the boxes appear checked once again.

Reported by @Thallassa

**Comment by verenion** [comment]
Assigned PT#151882580

**Comment by verenion** [comment]
Fix has been pushed.
