### ISSUE TITLE
Security Issue: `nexusid` cookie is valid after logout and password change.

### ISSUE THREAD

**Issue by Digitalroot** [Nexus-Mods/web-issues#1450]
## Your username/username(s) affected
Digitalroot

## Bug/error being reported:
`nexusid` cookie is valid after logout and after a password change.

### Steps to reproduce: 
1. Log into nexusmods.com
2. Get value of `nexusid` cookie from browser
3. Log out of nexusmods.com
4. Log back into nexusmods.com
5. Get new value of `nexusid` cookie from browser
6. Compare new and old value, validate they are different
7. Replace new value with old value.
8. nexusmods.com functions with the old cookie value.

### Expected result:
Old cookie value should no longer be valid after a hard logout of the site. 

### Actual result:
Old cookie value is still valid, even days after the logout action.

### Steps to reproduce: 
1. Log into nexusmods.com
2. Get value of `nexusid` cookie from browser
3. Change password to a new value.
3. Log out of nexusmods.com
4. Log back into nexusmods.com
5. Get new value of `nexusid` cookie from browser
6. Compare new and old value, validate they are different
7. Replace new value with old value.
8. nexusmods.com functions with the old cookie value.

### Expected result:
Old cookie value should no longer be valid after a password change.

### Actual result:
Old cookie value is still valid,

## Requested change
1. Clicking the logout button on the site expires the session cookie associated with the session that triggered the logout.
2. A password change on the site expires all session cookies associated with the account. 

## Nice to have
1. A button in the account profile that allows a user to logout of all sessions. Clicking this button will expires all sessions associated with the account.
2. A page in the account profile that displays all unexpired sessions with their created and last used date, along with a button that allows a user to logout/expire specific sessions. 

## Background
I ran into this while developing a GitHub action to upload new versions of my mod. Both my API key and `nexusid` cookie were compromised in the process. I am able to rotate the API key, but I can not get the compromised `nexusid` cookie to expire.

**Comment by Pickysaurus** [comment]
Thanks for the report, I've passed this to our team for review.
