### ISSUE TITLE
Mod listing pages not working properly

### ISSUE THREAD

**Issue by rdh1896** [Nexus-Mods/web-issues#1454]
URL: https://www.nexusmods.com/bladeandsorcery/mods/thisweek/ 
Username on the Nexus: russman3112
Bug/error being reported: Mod search produces zero results for entire Blade and Sorcery repository. Still can browse to mod pages via URL, however the mod browser and searching functions produce zero results for any mod. Have tested across browser (Brave and Edge) and same result is produced.
Steps to reproduce: Attempt to search or browse for any Blade and Sorcery mod. Untested on other Nexus-supported games.
Expected result: Display list of mods by search term or in browser.
Actual result: No mods displayed

**Comment by rdh1896** [comment]
Update: It appears to be happening across games. Just tested Fallout: New Vegas and the same result occurred.

**Comment by Pickysaurus** [comment]
This is a known issue. The site is rebuilding the cache now but this can take a few hours worst case

**Comment by Pickysaurus** [comment]
This issue is now resolved.
