### ISSUE TITLE
"you don't have any mods" massage at the opt-in page

### ISSUE THREAD

**Issue by notaprofi** [Nexus-Mods/web-issues#1459]
## Your username/username(s) affected
notaprofi

## Bug/error being reported:
Can't opt-in for mod rewards

## Steps to reproduce:
I've just created a new mod:
https://www.nexusmods.com/darksoulsremastered/mods/467

then followed the link on the mod page, which says "This mod is currently not opted in to our mod rewards program. Opt-in":

https://www.nexusmods.com/darksoulsremastered/modrewards#/mods/1?searchTerm=Krivoj%20Perevod%20-%20Poorly%20Translated%20Edition%20In%20Russian

but it says "YOU DON'T HAVE ANY MODS"

I tried to clear the search query https://www.nexusmods.com/darksoulsremastered/modrewards#/mods/1
and I see my mods, but the list doesn't include the new mod.

## Expected result:
I expect to see the new mod on the page and an "opt-in" link.

## Actual result:
"you don't have any mods"

**Comment by Pickysaurus** [comment]
Allow up to an hour for the new mod to appear
