### ISSUE TITLE
Files page - Expanded descriptions being Auto closed is undesireable.

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#146]
See this post https://forums.nexusmods.com/index.php?/topic/5964518-help-us-test-the-new-nexus-mods-design/page-14#entry53574288

And another expressing the same https://forums.nexusmods.com/index.php?/topic/5964518-help-us-test-the-new-nexus-mods-design/page-18#entry54302373

And another who came to express the same as my first post https://forums.nexusmods.com/index.php?/topic/5964518-help-us-test-the-new-nexus-mods-design/page-14#entry53604933

Could we have the files tab not closing the mini description of other options when you expand any other one of them ?, or make it Mod Author choice to expand them all or not.
 
There have been lots of occasions I can recall when its good to compare the mini descriptions to see what the differences are, especially when there are a huge amount of optional files to compare.
 
Here's one example, Navetseas CBBE Skin texture V2 V3 Plus Thepal and UNP Compatible
https://rd.nexusmods.com/skyrim/mods/6554/?tab=files
 
Say I want to look at two optional of files descriptions, or I may want to open all of them so that I can scroll through and skim any description differences ..
 
.. You cant, because opening one, closes the previous one opened.
 
Navetseas files are also still very much desired from the Old sets of files too, there are a couple which I know of that are better in the resolution and detail than a newer similar option, but they just did not have a few refinements to moles / pimples, so can be very useful options even though listed as old .. If you can figure out among them which ones are which. Being able to open multiple descriptions at the same time would be useful.
 
Which ones have I read, and which ones have I not read .. Aaaargh they all closed again. Feck lets start from the top.

Also, on the same mods files page, scroll way down the bottom .. Oooh look, a Miscellaneous file BELOW the old files .. Whos gonna go look way down there for a file that is still relevant and useable = OLD FILES should be at the bottom of all other file categories.
 
 
Also, having just one open by default makes it look to the user that the top opened file is the one the Mod Author may be recommending as a preference to the rest .. Which we cannot control so it is giving a false impression. I would rather have a couple of my mods with all options descriptions presented initially as open, so that it does not suggest to anyone that the High Res option for example is best - It may well not be for their machine but they will not realise that if they just dont bother expanding the other options.
 
Example case where I as the author think the best option is being hidden by default
Alt Navetsea UNP Seamless
https://rd.nexusmods.com/skyrimspecialedition/mods/11879/?tab=files
In that case Vanilla size is best, but High Res is by default expanded.
 
Example case where user deciding the appropriate option for there system is crucial
Vanilla Reduced Textures
https://rd.nexusmods.com/skyrim/mods/14504/?tab=files
I certainly dont want everyone just choosing the 256 Legendary version, it may well be much too low res for a lot of people and just plain put them off trying any other options
Only people still with a potato like my old machine should be using that option.

**Comment by m0lz** [comment]
It may be cool, it may be neat programming, it may sit well with your design theme .. But from a user and Mod author point of view it sucks, we need options for this file collapsing behaviour especially for the mod author, but really for the dear reader too

**Comment by Rrrafau** [comment]
assigned #151943527

**Comment by CreeperLava** [comment]
Also see #118
