### ISSUE TITLE
Donation Points - Monthly reports which are too long overflow their div container

### ISSUE THREAD

**Issue by XJDHDR** [Nexus-Mods/web-issues#1460]
## Your username/username(s) affected
XJDHDR

## Bug/error being reported:
When I was checking the latest Donation Points report for my account, I noticed that the list extended past the bottom of the grey box that is supposed to contain it and pushed itself into and displaced the contents of the website's footer.

If it helps, the list of mods is in an unordered list with the class "store-items" and the grey box is a div container with the class "container" inside another with "mod-rewards-container". I thought that the problem was an errant "max-height" style tag but I didn't see anything like that in the inspector. 
On a side note, adding a "**style="height: 1200px"**" attribute to the container div made this specific report work.

## Steps to reproduce:

1. Find and open a DP monthly report that has more than approx. 12 entries in it. My own account's report for Dec. 2021 (which is where the 2nd screenshot comes from) is an example of such a report.
2. You should see the issue manifest for the entries after that 1st dozen.

## Expected result:
Something similar to this report where the list of mods is still contained within the div container:
![DP working report](https://user-images.githubusercontent.com/7355441/148465598-cec428e1-e032-4318-8333-0053cf1e4b28.png)

## Actual result:
The list of mods I earned DPs for overflowed it's div container:
![DP Monthly Report bug](https://user-images.githubusercontent.com/7355441/148465774-1236ab1b-cc6f-4bb5-9882-2c3323aa6aa1.png)

**Comment by Pickysaurus** [comment]
Thanks for the report, I've passed it to our dev team.

**Comment by Pickysaurus** [comment]
This should now be resolved.
