### ISSUE TITLE
Error while trying to log in via web site

### ISSUE THREAD

**Issue by magius96** [Nexus-Mods/web-issues#1464]
## Your username/username(s) affected
magius96

## Bug/error being reported:
Trying to log in via website and get
"We're sorry, but something went wrong. If you are the application owner check the logs for more information."

## Steps to reproduce:
open nexusmods.com, click login.  Enter email address and password, click login.  Error displayed.
open nexusmods.com, click login,  Enter username and password, click login.  Error displayed. 

## Expected result:
Expect to login.

## Actual result:
Error displayed.

**Comment by magius96** [comment]
Tried again and got a error that my username or password were invalid.  I'm not sure if that is related to the previous error, but it seems to have self resolved.

**Comment by magius96** [comment]
OK, so it still occurs.  I use a password manager to store my passwords, so I'm certain that I'm entering the correct password.  My theory right now is that this error occurs when I enter the correct credentials.  I tested by entering nonsense in the password field and that nets me the invalid credentials message.  But when I enter valid credentials it sends me to the error message indicated, and screenshot below.

![NexusError](https://user-images.githubusercontent.com/17016935/150620048-8dbe5c67-b1d0-4ba7-8a93-b94e1d766e08.png)
.

**Comment by magius96** [comment]
I should note that I am using Google Chrome, Version 97.0.4692.99 (Official Build) (64-bit).  I thought maybe it might be out of date, so I updated the browser and tried again, with the same results.

**Comment by magius96** [comment]
I thought maybe it might have been because I was still logged into the nexus application, so I logged out of it.  Why in gods name do you redirect to the website for the application login, instead of using a login form in the app?  Now I can't log back into the app either.

**Comment by magius96** [comment]
Still thinking it might be my browser, I tried again using Microsoft Edge, with the same results.

**Comment by magius96** [comment]
Did notice an option to use Manual Login on the app.  Clicked that and it gave me a link 

https://www.nexusmods.com/users/myaccount?tab=api+access

Tried the link and it says I don't have access to that area.

**Comment by magius96** [comment]
Thought maybe it might be an issues with cookies, so I added nexusmods.com to the cookie whitelist in chrome so that the site is always full permission.  Same results.

**Comment by magius96** [comment]
I should probably note that at the beginning of this when I got the first message about invalid credentials, I used the forgot password feature to get a link to reset my password, but as of now, I have not received the email, and I am checking my spam folders.

**Comment by magius96** [comment]
This is really a pain because I MUST be logged in to download mods.  Since I can't log in, I can't download mods.

**Comment by magius96** [comment]
Can't Login Or Register On Nexus Mods Website #1439

Clearly, I'm not the only person having this issue.  It's also clear that no one is responding to these tickets since the ticket indicated above was opened on November 6th and has absolutely 0 responses.  In my humble opinion, no other bug matters when the client can't log in.

**Comment by timobeesycamore** [comment]
A friend and I are on a discord call right now and we are both having this same issue. I am trying to register a new account and she is trying to login.

**Comment by uretros** [comment]
tengo el mismo problema si encuentran solucion favor informar plis

**Comment by theman489** [comment]
Also having the same issue, can't log in

**Comment by Thomas-Lake** [comment]
I am having the same issue where I cant even create an account

**Comment by magius96** [comment]
I tried again this morning and now it's all magically working.

@uretros @theman489 @Thomas-Lake 
Please confirm if it is working for you as well.  If so, I'll go ahead and close this ticket.

**Comment by theman489** [comment]
@magius96 Also magically works again for me. Thank you for checking!

**Comment by Thomas-Lake** [comment]
@magius96 Also working for me too, cheers!
