### ISSUE TITLE
Bad Gateway Error 499 during the download

### ISSUE THREAD

**Issue by ichhabe567** [Nexus-Mods/web-issues#1467]
## Your username/username(s) affected
 ichhabe567

## Bug/error being reported: 
 This message pops up durring the download with MO2: 
[2022-02-03 08:12:06.375 W] Error transferring https://supporter-files.nexus-cdn.com/1704/62983/Lorien - High Poly Standalone Follower - 3BA-62983-1-1-1643875135.7z?md5=WA7BbTqh1wQ5rYKOZGQqUw&expires=1643890322&user_id=124533098 - server replied: Bad Gateway (499)   

Just tried to download the latest Version of my Mod: https://www.nexusmods.com/skyrimspecialedition/mods/62983
I also noticed, that the manual download doesn't work for this Mod/Version of the Mod...This message pops up: 
502 Bad Gateway
nginx/1.15.1

Relinking my account...doesn't changed something
I also waited 10h...doesn't change anything :(
## Steps to reproduce:
 Just try to download the latest version of my Mod

## Expected result:
 The mod will be downloaded with the MO2 or Manuel

## Actual result:
 Error Bad Gateway 499 and Error Bad Gateway 502 are poping up

**Comment by Pickysaurus** [comment]
Seems fine here. As the mod is new, it may just need a few mins to be available worldwide.

**Comment by ichhabe567** [comment]
Okay, thanks for the fast response ...But I just reuploaded the latest Version today, because the download doesn't work of the same Version (little bit older Verions from yesterday)... it's just a little bit weird, this happend to me the first time :)

**Comment by Pickysaurus** [comment]
I can only recommend this link as I can't replicate this: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
