### ISSUE TITLE
Mods NOT downloading

### ISSUE THREAD

**Issue by QueenUlyana** [Nexus-Mods/web-issues#1469]
I can't download mods from your site. I can't download any mod. I wait 5 seconds, the download does not start. I click on "click here" the download still does not start. Disabled all extensions and tried with different browsers. Nothing helps.

**Comment by Pickysaurus** [comment]
Please provide more information if you'd like us to help you.

- Which mods? (Provide examples)
- Which browser are you using? 
- What are the exact steps you are following? 
- What's your Nexus Mods username?
- Are you Premium?
- Are you using a mod manager?

**Comment by QueenUlyana** [comment]
Well?

**Comment by QueenUlyana** [comment]
It's just tin, how is this possible on such a popular site.

**Comment by Pickysaurus** [comment]
Thanks for the info. 

I see the problem here. You're clicking "Mod Manager Download", but you're not using a mod manager. 

You either need to install [Vortex](https://www.nexusmods.com/about/vortex/?) or click the "Manual Download" button instead.

**Comment by Pickysaurus** [comment]
Feel free to re-open this issue if that doesn't answer your question.
