### ISSUE TITLE
Mod Page Banner Image is being cropped at the ends on the RD site

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#147]
Comparison ..

Original page https://www.nexusmods.com/skyrimspecialedition/mods/12649/?

New RD page https://rd.nexusmods.com/skyrimspecialedition/mods/12649/?

You chopped her 'ed n feets off, cruel, heartless, barmpops :)

**Comment by mrmason** [comment]
There isn't anything we can do about this - we've notified mod authors to give them a heads up about the change, and once the sites are switched over then hopefully everyone will go around improving their banners :)

**Comment by m0lz** [comment]
OK but your hope of everyone adapting will not happen for many mods which have been left behind and no longer maintained. They will just remain looking bad, and in some cases chopping off information included in the banners for the immediate attention of users.

You say "we've notified mod authors" but Personally I have not seen any such notification and I am pretty active around the bazaars. For mod authors who are less likely to revisit or do not show up on the nexus forums (I am guessing you may mean an article there somewhere) .. These issues which are a result of the site change will not be resolved.

**Comment by mrmason** [comment]
We've had internal discussions on making the header area smaller depending on image size, but it's not a priority right this minute - we'll probably hand over to our new UX/UI designer to come up with a solution to this at some point :)
