### ISSUE TITLE
I can't download some files

### ISSUE THREAD

**Issue by Opfatier** [Nexus-Mods/web-issues#1470]
## Your username/username(s) affected
Opfatier

## Bug/error being reported:
i get the message bad gateway 502 when i try to download some mods

## Steps to reproduce:
1. try to download faster hdt-smp for skyrim se/ae
2. click on download with mod manager
3. doesn't work, get the message bad gateway 502
3. click on download manual
4. doesn't work, get the message bad gateway 502
4. try to download BHUNP (UUNP Next Generation) SSE
5. click on download with mod manager
6. doesn't work, get the message bad gateway 502
6. click on download manual
7. doesn't work, get the message bad gateway 502

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
the download of the mod starts

## Actual result:
get the message bad gateway 502

**Comment by Pickysaurus** [comment]
Please use the template when posting a bug report. It's there because it includes information we need to understand your issue.

```
## Your username/username(s) affected
<!-- list of affected usernames -->

## Bug/error being reported:
<!-- A description of the bug that you are reporting -->

## Steps to reproduce:
<!--
Optimally an ordered list with the steps needed to reproduce the bug

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
<!-- The result you were expecting -->

## Actual result:
<!-- The result that actually happened -->
```

**Comment by Pickysaurus** [comment]
A fix has been applied to an issue from earlier, so I suspect this is fixed.
