### ISSUE TITLE
Error unlocking tags "You are already blocking this tag"

### ISSUE THREAD

**Issue by amokiller** [Nexus-Mods/web-issues#1471]
## Your username/username(s) affected

Amokiller

## Bug/error being reported:

"Sorry i'm not english"
Turn off blocked tags show msg "You are already blocking this tag" and never unblock.

I try with Chrome, Edge and Firefox (this in portable version)

![webNexus](https://user-images.githubusercontent.com/1351789/152533913-c80a2071-4544-4e25-a832-59fab5b7ab7f.png)

**Comment by Pickysaurus** [comment]
Are you clicking them from the "Currently blocked tags" section at the top of the page?

**Comment by amokiller** [comment]
Omg. I'm stupid. Very stupid.
Thanks a lot.
