### ISSUE TITLE
502 Bad Gateway on Stardew Valley Mod Ridgeside Village 2.0.5

### ISSUE THREAD

**Issue by dykanthropy** [Nexus-Mods/web-issues#1473]
## Your username/username(s) affected

 boyhowdyboyhowdy

## Bug/error being reported:

Attempts to download Ridgeside Village 2.0.5 Hotfixed 3 result in 502 Bad Gateway Error. Link here https://www.nexusmods.com/stardewvalley/mods/7286?tab=description 

## Steps to reproduce:

1. Click manual download on affected mod
2. Click slow download

## Expected result:

Save file

## Actual result:

502 Bad Gateway Error

**Comment by Maplassie** [comment]
I'm getting the same for Morrowind Intelligent Transfers, cannot download it manually or via mod manager, opened a ticket as well as I am also getting 502 Bad Gateway

**Comment by mrmason** [comment]
Thanks for the reports, this should be fixed now.
