### ISSUE TITLE
New "Collections" Feature

### ISSUE THREAD

**Issue by Elephant42** [Nexus-Mods/web-issues#1476]
No I do not want to "Download curated lists of mods easily..." and yes I am sick of seeing the banner urging me to do so...

**Comment by Pickysaurus** [comment]
Click the little X in the top right of the banner to dismiss it. If you are blocking cookies you'll need to allow them. If that still doesn't work clear your cookies and dismiss it again. 

This tracker is for bugs with the website. Our feedback forum is a better place for questions like this.
