### ISSUE TITLE
Spoiler tags not working / forced to hide page

### ISSUE THREAD

**Issue by Drali500** [Nexus-Mods/web-issues#1478]
## Your username/username(s) affected
Drali500 

## Bug/error being reported:
Hide tag not working 

## Steps to reproduce:
Just updating the page for new version added new spoilers tags and all spoilers broken

[https://www.nexusmods.com/witcher3/mods/6204](url)

## Expected result:
 proper spoiler tags

## Actual result:
not working tags

**Comment by Pickysaurus** [comment]
The spoilers appear fine based on the limited info provided.

What is normally the problem in these cases is that you've added more `[spoiler]` tags than `[/spoiler]` tags. Make sure you pair them up properly to avoid strange behaviour. 

Feel free to reopen with more details if you believe this is actually a bug.
