### ISSUE TITLE
Cannot upload mods to Nexus in the Monster Hunter World sub-page

### ISSUE THREAD

**Issue by gradashy** [Nexus-Mods/web-issues#1479]
## Your username/username(s) affected

User: Gradashy

## Bug/error being reported:

The site is completely unstable and not possible to upload mods at all, not even images, returning just an unknow error in upload.

## Expected result:
Works as normal

## Actual result:
Unknow Error

**Comment by gradashy** [comment]
The Error I got from uploads are **500 Internal Server Error**

**Comment by Pickysaurus** [comment]
Sorry about that, this was a temporary error.
