### ISSUE TITLE
Comment thread occasionally not being created for images.

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#148]
I set comments to be enabled on this https://rd.nexusmods.com/newvegas/images/107984 the same thing happened earlier with this guy https://rd.nexusmods.com/newvegas/images/107981 sadly he deleted the problem image.

**Comment by verenion** [comment]
Assigned PT#151944861

**Comment by JimUKNexus** [comment]
I don't know if this helps narrow it down but the issue has been known to occur on the old site, it might be something that's been carried over.

**Comment by iamtiz** [comment]
That was happening for images with titles containing quotes, it should be fixed now.
I've manually created a topic for your image, too
