### ISSUE TITLE
Attach File / Upload not working

### ISSUE THREAD

**Issue by dragoncosmico** [Nexus-Mods/web-issues#1484]
## Your username/username(s) affected
dragoncosmico

## Bug/error being reported:
The file never uploads.

## Steps to reproduce:
Just choosing the file and waiting forever.

### Example:
-Create a new mod
-Go to the Manage Files section
-Try to upload anything

## Expected result:
The file uploads.

## Actual result:
File doesn't upload.
![asd](https://user-images.githubusercontent.com/100284028/155311365-70b5d51a-e5a0-45cb-a439-c5a4cd52e552.png)

**Comment by Pickysaurus** [comment]
Thanks for the report, this should be fixed in a few minutes.

**Comment by Pickysaurus** [comment]
Fixed
