### ISSUE TITLE
Bug Report: More Trending page incorrect first item

### ISSUE THREAD

**Issue by doodlum** [Nexus-Mods/web-issues#1485]
## Your username/username(s) affected
Doodlezoid

## Bug/error being reported:
My mod Screenshot Helper was at top of More Trending page. Instead, Neloth's Experimental Subject Quest (DLC2TTR4a) Fix is at the top of that page, as well as bottom slot on Hot Files.

So top of "More Trending" list can be replaced with bottom of "Hot Files" list.

Viewing the separate More Trending page, Screenshot Helper is ahead of Neloth's Experimental Subject Quest (DLC2TTR4a) Fix in the list

![image](https://user-images.githubusercontent.com/15017472/155864775-14f4eac5-0ae5-4d71-9924-9e0c2d5eb29e.png)

## Steps to reproduce:
No real reproduction steps unless viewing at this time

## Expected result:
Screenshot Helper at top of More Trending page

## Actual result:
Neloth's Experimental Subject Quest (DLC2TTR4a) Fix at top of More Trending page

![image](https://user-images.githubusercontent.com/15017472/155863239-ba23e419-4d91-4de3-8bd4-d1ecaa5ab2fd.png)

**Comment by Pickysaurus** [comment]
This might just be a cache thing if the hot files are in flux

**Comment by doodlum** [comment]
Yeah, it came back. Then just went away again. I think only affects the current top "More Trending" mod.
