### ISSUE TITLE
Nexus/Vortex Downloads wrong version of BelpinEx (16 overwrites 19)

### ISSUE THREAD

**Issue by firetigeris** [Nexus-Mods/web-issues#1486]
## Your username/username(s) affected
all Nexus Vortex Valheim Users

## Bug/error being reported:
BelpinEx 5.4.16 keeps overwriting correctly installed 5.4.19 even with script extenders and Belpin Support turned off (Extensions/Interface)

## Steps to reproduce:
Run Vortex and install Nexus mods, if you have 5.4.19 installed it will revert to 5.4.16

## Example:
1. Run Vortex
2. Install a Nexus Mod
3. Find that 16 has rewritten 19
-->

## Expected result:
I Expect with Purge mods that BeplinEx Would run, it wont, I expect that Vortex would not overwrite a newer version of BelpinEx

## Actual result:
Every time I use Nexus mods through Vortex I must rewrite Belpin 19 over 16.

**Comment by Pickysaurus** [comment]
Please report this inside Vortex or on the Valheim extension page: https://www.nexusmods.com/site/mods/210 (after ensuring you have the latest version). 

This tracker is for issues with the website.
