### ISSUE TITLE
profile picture not showing on nexus mods

### ISSUE THREAD

**Issue by athenavee** [Nexus-Mods/web-issues#1488]
## Your username/username(s) affected

athenavee

## Bug/error being reported:

avatar not showing on nexus mods

## Expected result:

picture to change
## Actual result:

profile picture is default nexus

**Comment by Pickysaurus** [comment]
Your avatar is showing as this:
![https://forums.nexusmods.com/uploads/profile/photo-thumb-79537188.jpg?r_=1646817140](https://forums.nexusmods.com/uploads/profile/photo-thumb-79537188.jpg?r_=1646817140)

I suspect it didn't appear for you right away due to caching.
