### ISSUE TITLE
Minor bug reports issues

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#149]
So two issues I've seen with the menus that update the bug report status.
1) Comment drop down says 'solved' but Manage menu says 'Fixed'
![nexus](https://user-images.githubusercontent.com/31670524/31566669-97151578-b063-11e7-9eb3-fba9a7487df3.jpg)

2) Using the comment drop down doesn't immediately update the view like the 'Manage' menu version. 

3) Possible enhancement - if the comment reply drop down is set to 'Fixed' then perhaps allow the version number to be entered?

**Comment by Pickysaurus** [comment]
Oh and the free text box on the comment drop down is a little superfluous

**Comment by verenion** [comment]
Assigned PT#151988549

**Comment by verenion** [comment]
> Oh and the free text box on the comment drop down is a little superfluous

Can you elaborate on this? Not sure I understand what you are referring to.

1 and 2 have been resolved and I will raise 3 with the team.

**Comment by Pickysaurus** [comment]
If you see in the left photo there is a text entry box at the top of the drop down. As there are only 8 options it seems like we don't need it

**Comment by verenion** [comment]
Should be fixed now.
