### ISSUE TITLE
Slime rancher mods not working 

### ISSUE THREAD

**Issue by Bassaroo1** [Nexus-Mods/web-issues#1490]
## Your username/username(s) affected
 Bassaroo1

## Bug/error being reported:
 The game isn't loading mods

## Expected result:
 mods working fine

## Actual result:
 vanilla game

**Comment by Pickysaurus** [comment]
This is not a fault with the website. Please make sure you are reading the mod author's instructions properly.

**Comment by Bassaroo1** [comment]
okay thank you

**Comment by Bassaroo1** [comment]
though it's all the mods
