### ISSUE TITLE
duplicate mod folders in mods file when deploy mods is used

### ISSUE THREAD

**Issue by phenyxasher** [Nexus-Mods/web-issues#1491]
phenyxasher

## Bug/error being reported:
when I deploy mods in vortex, for 7d2d under either the load order or the mods window, it creates a duplicate file of each of my mods except The Wasteland, Bdubs vehicles, SCORE and SNPC mods. If I remove the mods they are still there in the folder. but do not show up in the vortex list. My vortex does not have a separate folder for staging mods, deploying mods, or a mods folder that is separate from steam. I have uninstalled and reinstalled vortex 4 times to fix this. I am still not getting the above folders and vortex just wants to create more files in the game mods folder. 

## Steps to reproduce:
<!--I am not sure what to tell you about this more than I have already done
I noticed a problem with duplicating files
I uninstalled the files [and archives] and then reinstalled
I then tried uninstalling Vortex and reinstalling it, noticed that the mods folders did not show up in Vortex and all my mods were still in Vortex when I went in.
the load order started to work again [i was having a JSON error previous to this] but if I deployed in either the mods window or the load order, it would duplicate the mod files [except for the above mentioned ones] and if I removed the duplicates it would still tell me I had duplicates or it would disable the file.

## Expected result:
I was expecting it to perform normally, but every since the last update with the collections features I have been having issues. 

## Actual result:
really, do I need to restate what happened? Just let me know if there are any files you need to help in fixing this. I have no idea what might be needed.

**Comment by Pickysaurus** [comment]
This tracker is for website issues. You can send feedback via Vortex by using the "Send Feedback" option in the top-right menu.
