### ISSUE TITLE
Back button after switching tabs

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/web-issues#1493]
## Your username/username(s) affected
N/A

## Bug/error being reported:
After switching to a different tab, the browser back button doesn't go back to the previous tab.

## Steps to reproduce:
1. Go to any mod page
2. Switch to the FILES tab
3. Press the back button on your browser  

## Expected result:
URL changes back, and page goes back to where the user came from.

## Actual result:
Only the URL changes back.

**Comment by Pickysaurus** [comment]
This is a known issue. A workaround is to simply click the "Description" tab again.

**Comment by thany** [comment]
Seems pretty important, but I've been seeing this for a long time. Now that I know the workaround, no one else still does. Also doesn't make it any less confusing when the back button doesn't appear to work, more so when the address bar isn't fully visible, and even more so when I have to scroll back up to reach the tabs.

I wouldn't call it "simply".

"Simply" use React and the super nice React Router, to do singlepage routing on the frontend.

**Comment by Pickysaurus** [comment]
This is a very minor problem. I can see that our new Tabs on Nexus Mods Nexus behave in a similar way. I can't really think of a site I've used where tabs behave in the way you describe.

**Comment by thany** [comment]
> I can't really think of a site I've used where tabs behave in the way you describe.

Then:

1. Don't change the url when switching tabs
2. Make the back button go back to the previous *whole* page on the first click

Currently, you've got a broken mismatch between letting the browser handle it, and doing magic stuff in javascript. I say either do it right, or don't do it.

**Comment by thany** [comment]
Closed means fixed?

**Comment by Pickysaurus** [comment]
It has been closed because it was marked with "Won't fix". It's not likely to change in the current iteration of the site but will be considered for the next version.
