### ISSUE TITLE
Bug reports: find MY reports

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/web-issues#1494]
**Is your feature request related to a problem? Please describe.**
On popular mods, it's hard to find bugs I reported.

**Describe the solution you'd like**

1. A way to see who posted a bug without having to open each and every one.
2. A way to filter it down to bug reports I have created.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm sure there's some space to plonk down a username to fix (1) 😅
![image](https://user-images.githubusercontent.com/152227/158604317-ab926505-c7c5-4655-9fd9-71131fe7f6c2.png)

**Comment by Greg-Nexus** [comment]
Closed: We haven't made this change for Mods yet, but are mid-development on a new re-worked Bug Report feature that will allow users to sort by Reporter. This will get ported over to Mods as soon as we are able to do so.
