### ISSUE TITLE
Vote vs Track vs Endorse

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/web-issues#1496]
**Is your feature request related to a problem? Please describe.**
There are three ways to give exposure to a mod. We only need one.

**Describe the solution you'd like**
So tracking is to keep getting updates. Endorsing is a signal of liking a bug. Voting also means you like it.

These three features can be merged into one. When you "track" a bug, it's indicative of liking it. So endorsing and tracking is essentially the same thing. Voting for a bug can be implied from endorsements and downoads and whatall, using an algorithm. There doesn't need to be an explicit voting system, because it will exclude people who don't notice the button, or who seldom visit the site.

On top this, having three buttons adds [unneccesary noise, or visual clutter](https://givegoodux.com/signal-vs-noise-cleaning-up-visual-clutter-in-ui-design/). The site already has a billion buttons, all screaming for the same visual importance. 

**Describe alternatives you've considered**
Personally I ignore stuff I don't understand what it's for, so that's a pretty crappy alternative, innit.

**Comment by Pickysaurus** [comment]
These three buttons serve three specific purposes:

1. Track - Add this mod to your tracking centre. You will be updated about changes via site notifications.
2. Endorse - Show support for this mod and its author. (Requires the file to have been downloaded)
3. Vote - Vote for this mod to win "Mod of the Month" for the current month. Winners are shown here each month: https://www.nexusmods.com/stardewvalley/mods/motm

While the UI could be refined these three functions will remain distinct.

**Comment by thany** [comment]
Exactly my point. Why do these three distinct functions need to exist?

Track and Endorse are the same thing. They are. No, really, *they are*.
Vote can be implied from endorsements. That's literally what an endorsement is. Otherwise endorsing a mod is totally meaningless.

**Comment by Pickysaurus** [comment]
I think you're still misunderstanding, tracking and endorsing are definitely not the same thing. 

Think of Facebook, if you "Like" a post you don't get notified of updates about it. 

Track is saying "I want to be notified of changes".

Endorse is saying "I like and support this content and the author".

**Comment by thany** [comment]
If you want to be notified of updates, you're implicitly endorsing/liking the thing. And vice versa: if you like something, surely you'd want updates about it.
