### ISSUE TITLE
Upload Mod Error

### ISSUE THREAD

**Issue by Cosmicalex** [Nexus-Mods/web-issues#1497]
## Your username/username(s) affected
cosmicalex

## Bug/error being reported:

Cannot add a picture as a header of any size or format.

## Steps to reproduce:
Select Upload on site. Go to Media and try to upload image or drag one.
Tried on 3 pc with 4 browsers.

Optimally an ordered list with the steps needed to reproduce the bug

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
Image shown and ready to crop image

## Actual result:
Nothing appeared.

<img width="654" alt="Nexus Mod Error" src="https://user-images.githubusercontent.com/101732008/158630957-726dc0f7-9598-44b2-8803-40dd373f815e.png">

**Comment by Pickysaurus** [comment]
Thanks for the report, can confirm the following error:
> Refused to load the image 'blob:https://www.nexusmods.com/ac16b022-07ec-48b0-95cd-7e6ab61f393d' because it violates the following Content Security Policy directive: "img-src 'self' https: data:".

**Comment by Cosmicalex** [comment]
So how can this issue be fixed? Uploading game screen shots works fine as well as mod files.
