### ISSUE TITLE
DL And Total View Stats Blank On iOS For All Mods

### ISSUE THREAD

**Issue by effs** [Nexus-Mods/web-issues#1499]
## Your username/username(s) affected
Happens both logged out and logged in. 

## Bug/error being reported:
The Unique DLs, Total DLs, and Total Views fields are all `--` when viewed on iOS 15 (at least), both logged in and logged out. (The stats do show up on *desktop* in responsive mode emulating iOS.)

Device: iPhone 12 Pro Max
OS: iOS 15.4

## Steps to reproduce:
1. Go to any mod page (tested on Cyberpunk2077 and Skyrim, presumably any others too)

## Expected result:
The stats show up correctly

## Actual result:
The Unique DLs, Total DLs, and Total Views fields are all `--`.

See screenshot below.

**Screenshots**
![PNG image](https://user-images.githubusercontent.com/13802421/159133227-e9e9f41f-985b-4527-b96a-057cb03d51bf.png)

**Comment by Pickysaurus** [comment]
Can replicate but this seems to be something specific to iOS - as you point out it works fine in an emulated browser. Perhaps it's some kind of security setting? These stats are requested via AJAX after the page loads IIRC.
