### ISSUE TITLE
Mod-list hover effect is sub-optimal

### ISSUE THREAD

**Issue by neokio** [Nexus-Mods/web-issues#150]
When hovering over a mod in any mod list (e.g. https://rd.nexusmods.com/fallout4/mods/), the mod darkens, and "VIEW MOD" appears. This is suboptimal UX in that it doesn't reward selection, rather it punishes the user by obscuring the very thing they are interested in. My user experience is that the topic of my interest, that which I have just moused over, is now less visible (covered by text) and has gone dark. I know I can click because the cursor is now a pointer, I don't need something in the shape of a button that isn't a button thrown in my face. One of the things which Google got right in their Material Design guidelines is that people respond better to their mouseovers popping up/out of the page.

One solution would be to have hoverable mod images at `0.9` opacity, and upon hover, do two things: (a) bring them to `1.0` opacity, and (b) add a dropshadow around the image box.

Simplest short-term workaround would be to hide the "VIEW MOD" (`.view-label` class) entirely, and reduce the opacity MUCH less that you currently are. Doesn't take much to trigger the perception of interaction.

**Comment by Thallassa** [comment]
This was one of the most common complaints in the redesign thread, with over 6 reports up to page 23.

**Comment by iamtiz** [comment]
fixed
