### ISSUE TITLE
the graphics of vortex are completely bugged on a 1440 monitor

### ISSUE THREAD

**Issue by beastbro9823** [Nexus-Mods/web-issues#1500]
## Your username/username(s) affected
beastbro9823

## Bug/error being reported:
white line/artifacts when using vortex on a 1440p monitor

## Steps to reproduce:
1: install vortex on a device and have a 1440p display
2: occasional artifacts occur at slightly random intervals

## Expected result:
clean graphics

## Actual result:
difficult to navigate interface because of the lines
<img width="1280" alt="Screenshot 2022-03-20 100947" src="https://user-images.githubusercontent.com/101981090/159166549-60fa2474-fdcd-4309-a326-ef236d9a116e.png">

**Comment by Pickysaurus** [comment]
Please report issues with Vortex here: https://github.com/Nexus-Mods/Vortex/issues/new/choose

https://wiki.nexusmods.com/index.php/Frequently_Asked_Questions#Why_is_Vortex_blurry?
