### ISSUE TITLE
LE3 Community Patch fails to download when reaching 2.0gb out of 2.9

### ISSUE THREAD

**Issue by MightyKombat** [Nexus-Mods/web-issues#1502]
## Your username/username(s) affected
MightyK2018

## Bug/error being reported:
Attempting to download the Mass Effect LE3 Community Patch always fails when 2.0gb is downloaded. Mod Manager either gives an error message or simply never stops trying to download and has to be closed via Task Manager, while manual downloading also fails and gives the standard browser download failure message. A lot of LE3 mods rely on this patch and the mod framework to actually function. Have checked and am able to download larger files (over a considerable amount of time) on my ISP so am fairly certain this is a Nexus site problem.

## Steps to reproduce:
Simply download the mod from the Nexus page provided: https://www.nexusmods.com/masseffectlegendaryedition/mods/13

## Expected result:
The download to finish.

## Actual result:
Error messages and the download failing.

![LE3CommunityPatchDownloadFail1](https://user-images.githubusercontent.com/102255984/159787464-7654646d-f5ec-445d-adad-47705384b7c9.png)

![LE3CommunityPatchDownloadFail2](https://user-images.githubusercontent.com/102255984/159787841-eeb4f8b4-a9f3-4d75-902a-b1bf5407f999.png)

![LE3CommunityPatchDownloadFail3](https://user-images.githubusercontent.com/102255984/159787985-7381a740-7e49-48a1-b575-a6c7600959b1.png)

**Comment by Pickysaurus** [comment]
Please see our advice on download issues here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

**Comment by MightyKombat** [comment]
Can I at least post my info here in a reply?

Country: UK
ISP: Three UK
Average Download Speed: 1.5mb/s the highest

Download tests:
Amsterdam: 1.4MB/s the highest
Prague: 1.5mb/s
Los Angeles: 1.7mb/s
Chicago: 805kb/s
Miami: 1.6mb/s
Premium CDN: 1.3mb/s

Download Links:

Biggest file: https://supporter-files.nexus-cdn.com/110/607/COMPLETE%20LITE-607-1-7.zip?md5=8v_cJ76Tjtu6jGwBw1_rSg&expires=1648090726&user_id=54212107&rip=92.40.191.147
Smallest: https://cf-files.nexusmods.com/cdn/1704/1137/Ordinator%209.31.0-1137-9-31-0-1635693140.zip?md5=NrQ6JMe2sOKk2Bd_P_MkIA&expires=1648090658&user_id=54212107&rip=92.40.191.147

Tracing route to files.nexus-cdn.com [195.181.173.81]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  192.168.1.1
  2     *        *        *     Request timed out.
  3    54 ms    36 ms    42 ms  172.25.211.33
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6     *       57 ms    43 ms  172.25.216.93
  7     *        *        *     Request timed out.
  8    42 ms    33 ms    44 ms  172.25.195.150
  9     *       40 ms    40 ms  core-backbone.exs.cash [80.255.15.58]
 10    64 ms    51 ms    46 ms  ae28-0.lon10.core-backbone.com [80.255.15.57]
 11    73 ms    44 ms    43 ms  ae3-2072.ams10.core-backbone.com [80.255.15.165]
 12    47 ms    55 ms    41 ms  core-backbone.cdn77.com [5.56.18.14]
 13    53 ms    62 ms    56 ms  vl204.ams-dc1-dist-2.cdn77.com [138.199.0.115]
 14     *       54 ms     *     unn-195-181-173-81.datapacket.com [195.181.173.81]
 15    46 ms     *       73 ms  unn-195-181-173-81.datapacket.com [195.181.173.81]

Trace complete.
