### ISSUE TITLE
time cooldown 15 min for endorsement not working correctly

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1505]
time cooldown 15 min for endorsement not working correctly. Clock defect?
I downloaded 04:25 + 04:26 the files at https://www.nexusmods.com/skyrimspecialedition/mods/28921?tab=files&BH=0 , and we now have 04:49 and I can't give an endoresemt but get
_Error
Our records show you recently tried to rate this file but couldn't either because you hadn't downloaded the file or because you were trying to rate the file too soon after downloading it. There is a 15 minute cooldown on rating files after this point to save on server resources. Please try again soon._

**Comment by Dreifels** [comment]
Edit: in fact 30 min. I had to wait until I could give an endorsement.

**Comment by Pickysaurus** [comment]
I cannot replicate this.
