### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by keiwaiyu** [Nexus-Mods/web-issues#1506]
## Your username/username(s) affected

KeiWaiYu
## Bug/error being reported:

error when trying to download the mod Purplish Blue Hud edits
## Steps to reproduce:

1. Step 1 Go to https://www.nexusmods.com/cyberpunk2077/mods/4223?tab=files
2. Step 2 click download
3. Step 3 click slow download
## Expected result:

the file started downloading
## Actual result:

Error 502: Bad Gateway
nginx/1.15.1

**Comment by StrangeWolf12** [comment]
Getting the same issue. Can't download anything throughout the entire site!

**Comment by Nietros** [comment]
Can confirm. Getting this when downloading mods for both Skyrim SE and Fallout 4. Manual Download results in 502 and Votex results in 502 as well for the same mods.

**Comment by BullOnMars** [comment]
Can confirm too, only affected certain mods uploaded like yesterday or today.

**Comment by Corndog480** [comment]
Same here.  The  mods that I cannot download are the ones that have been either added, or updated within the last couple days.

**Comment by Pickysaurus** [comment]
Please create a thread in our feedback forum with some examples if this problem still persists. 

https://forums.nexusmods.com/index.php?/forum/117-feedback-suggestions-and-questions/
