### ISSUE TITLE
Download speed cap?

### ISSUE THREAD

**Issue by LegitOldSchool** [Nexus-Mods/web-issues#1508]
## Your username/username(s) affected
dtb25175

## Bug/error being reported:
Download speed capped at 200 kb/s

## Steps to reproduce:
1-Download a mod file
2-Notice slow speed?

## Expected result:
Download at 2mb/s

## Actual result:
![Screenshot_2](https://user-images.githubusercontent.com/102879876/161400757-75e3633e-3fd0-47e3-a22d-23fb1b62ff60.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/102879876/161400758-6d89f2fa-9966-4b8b-af4b-d2588cc055fd.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/102879876/161400786-8b839968-861b-4ba1-986f-32edeb61dd39.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/102879876/161400812-d7b3fc1a-72b0-4029-80b9-2fd21e87d656.jpg)

**Comment by Pickysaurus** [comment]
Please see this troubleshooting guide 
https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

**Comment by LegitOldSchool** [comment]
<a href="https://www.speedtest.net/result/12981519603"><img src="https://www.speedtest.net/result/12981519603.png"/></a>

**Comment by Pickysaurus** [comment]
Hi again,

Please post the results on the forum (as the help article says) so that we can look into this.

**Comment by LegitOldSchool** [comment]
It was.

https://forums.nexusmods.com/index.php?/topic/11270508-download-capped-at-200kbs/
