### ISSUE TITLE
Unable to upload (503 Service Unavailable)

### ISSUE THREAD

**Issue by ctrlsecRaton** [Nexus-Mods/web-issues#1509]
## Your username/username(s) affected

ctxrlsec
## Bug/error being reported:

Cannot upload a mod
## Steps to reproduce:

1. Add a mod
2. Manage files
3. Upload the mod

## Expected result:

The mod gets uploaded

## Actual result:

The mod never gets upload and it shows this in console over and over

![1](https://user-images.githubusercontent.com/32195821/161450872-e84cbff0-8064-4285-bd9b-4ecff76004dd.png)

**Comment by Willlux** [comment]
Yep, I can't upload either.

**Comment by OptiHuman** [comment]
same here. I upload a mod every other year and it had to happen now haha...
username : JokingmaN

**Comment by Mirrorman95** [comment]
I'm also having the same problem:
Access to XMLHttpRequest at 'https://upload.nexusmods.com/uploads/chunk' from origin 'https://www.nexusmods.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
My uploads failed on Chrome and Firefox.

**Comment by GamerKC** [comment]
same for me. stuck and can't upload. hopefully it gets fixed soon, i wanted to release a bug fix on one of my mods lol

**Comment by Dogrules23** [comment]
I haven't looked at the console, but my upload is also not doing anything. I just want to upload my first Cyberpunk 2077 "mod".
Username: Dogrules23

**Comment by BLNJ** [comment]
Seems to work again, was just able to upload a file, without 503 Errors in console

**Comment by Mirrorman95** [comment]
> Seems to work again, was just able to upload a file, without 503 Errors in console
I can confirm this.

**Comment by Pickysaurus** [comment]
This has been resolved. Thanks for the report.
