### ISSUE TITLE
Giving kudos moves you off game specific nexus address onto generic site

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#151]
If you give a kudos to anyone on their author page for a specific game, such as Skyrim nexus, when the kudos is given the page reloads and moves you to the base nexus address

Eg: Giving a kudos on this page:
https://rd.nexusmods.com/skyrimspecialedition/users/48478818
Refreshes the page once the kudos is given and you end up here:
https://rd.nexusmods.com/Users/48478818

Just an annoyance, nothing major, but a pain if you're trying to navigate an authors profile within a specific games context and it moves you off that

**Comment by iamtiz** [comment]
Assigned #151987294

**Comment by iamtiz** [comment]
Fixed
