### ISSUE TITLE
click on lionk I got by search gives Not Found

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#1510]
search for "Skyrim at War - Anniversary Edition"
I got link
https://www.nexusmods.com/skyrimspecialedition/mods/66107
I made translation of it, created page
https://www.nexusmods.com/skyrimspecialedition/mods/66152
, and link it to original page

copy link
https://www.nexusmods.com/skyrimspecialedition/mods/66107
but Link now gives

Not found
The mod you were looking for couldn't be found

But if I follow the link shown in search, I get the original page, However, my page is not listed as translation.

**Comment by Pickysaurus** [comment]
Please allow at least 15 minutes before raising a bug. The site is cached so things take a while to appear sometimes.

![image](https://user-images.githubusercontent.com/31670524/162283607-6f6e1bdf-32c9-4fe0-ab7d-3fa3d1947655.png)
