### ISSUE TITLE
Unable to preview  or submit a post on the forums

### ISSUE THREAD

**Issue by Devilofether** [Nexus-Mods/web-issues#1511]
## Your username/username(s) affected
Devilofether

## Bug/error being reported:
Unable to preview or submit a post in the nexus mods forums, there is a browser check before booting me to the forum homepage, with no post added. my post was somewhat long

## Steps to reproduce:
1. press the "new post" button (in the elden ring game-specific forum)
2. create a post with title, tags and content (enough content to activate the scroll wheel), the post also had formatting like font sizes, an unordered list, underlining, and bolding
3. press either the "preview post" button, or the "submit post" button

## Expected result:
to be brought to a post preview page, or to be brought to the page I was posting in, with my post added to the list of existing posts (assuming I pressed the correct buttons)

## Actual result:
being brought to the homepage of the forum, as if I had never made the post in the first place

**Comment by Pickysaurus** [comment]
I can't replicate this. 

Please see this help page: https://help.nexusmods.com/article/113-troubleshooting-website-issues
