### ISSUE TITLE
Preventing Saving

### ISSUE THREAD

**Issue by JezzyCrazyTV** [Nexus-Mods/web-issues#1513]
If i write to much the text bellow disapears so i hope a screenshot is enough

![Screenshot (1757)](https://user-images.githubusercontent.com/82102312/162702480-570b20ea-be24-4d99-8aee-a05ed9ded4a3.png)

**Comment by themagickoala** [comment]
This issue tracker is for problems with the Nexus Mods website. I'm sorry you're having trouble with Slime Rancher, but we can't help you here. You should try looking for help in the Slime Rancher modding community, or ask for help on the mod pages for the mods you are using.

**Comment by JezzyCrazyTV** [comment]
ok sorry

**Comment by JezzyCrazyTV** [comment]
first i tried searching for discord server

**Comment by JezzyCrazyTV** [comment]
i think i found something srml discord i think they migth help so bye and feel free to close this up

**Comment by JezzyCrazyTV** [comment]
No i found a fix made and folder with that error name and saving works now.

**Comment by JezzyCrazyTV** [comment]
No i found a fix i made an folder with that error name and saving works now.
