### ISSUE TITLE
cannot lock thread

### ISSUE THREAD

**Issue by germedowls** [Nexus-Mods/web-issues#1514]
## it does not

https://www.nexusmods.com/newvegas/mods/75600?tab=posts

**Comment by jasondude7116** [comment]
Please give this issue some priority. Mods will have to be set to hidden until this issue is fixed.

**Comment by mrmason** [comment]
Thanks for reporting this - it should now be fixed.

Internal reference `/web-dev/nexusmods/-/issues/1376`
