### ISSUE TITLE
Posts: Corrupted DOM beyond a certain user post

### ISSUE THREAD

**Issue by mongoose3736** [Nexus-Mods/web-issues#1515]
The DOM of https://www.nexusmods.com/cyberpunk2077/mods/3815/?tab=posts appears corrupted beyond a certain post (see screen capture or page capture below).

![corrupted-dom](https://user-images.githubusercontent.com/87887014/163111578-b3624850-ffcc-409c-842b-44b0cf20d995.png)

The page source is [not valid HTML](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.nexusmods.com%2Fcyberpunk2077%2Fmods%2F3815%2F%3Ftab%3Dposts), but the last reported fatal error doesn't seem related to this.

Copy: 
[corrupted-dom.zip](https://github.com/Nexus-Mods/web-issues/files/8478646/corrupted-dom.zip)

Didn't check any details, but should be wary of a **possible XSS**.

Observed with Firefox 99.0.1.

**Comment by rscottexe** [comment]
This issue was caused by malformed BBCode in the post by Koushkinn. I have rectified the issue manually and the page is now working correctly again.
