### ISSUE TITLE
why keep closing & hiding the vortex issues instead of fixing them?

### ISSUE THREAD

**Issue by lemmonysnickett** [Nexus-Mods/web-issues#1516]
## Bug/error being reported: (connect ETIMEDOUT 104.22.3.55:443)  failed to download

![image](https://user-images.githubusercontent.com/103716760/163514191-cb7c0d13-000f-490b-9217-69517bc766a9.png)

### Example:
1. Step 1check for updates/ download updates
2. Step 2check for updates/ download updates
3. Step 3check for updates/ download updates
-->

## Actual result:

![image](https://user-images.githubusercontent.com/103716760/163514303-3f4a5e39-3dd3-41b8-9481-c719b3fef164.png)

**Comment by Pickysaurus** [comment]
https://github.com/Nexus-Mods/Vortex/issues/new/choose

**Comment by Pickysaurus** [comment]
As listed in the options when raising an issue here, there is a separate repo for Vortex issues. This issue is also most likely a network issue or something in your local setup blocking Vortex from accessing the internet

**Comment by TanninOne** [comment]
@lemmonysnickett @Pickysaurus a ETIMEDOUT means that a network message timed out, as in: it took too long or, likely, got dropped.
This is either a "your own network" or an ISP or a cloudfare or a server problem. The one component that doesn't cause network timeouts is the client. As such: Vortex/issues is even less appropriate.

Network problems happen, no server on the internet is 100% reliable. Don't report them and just try again later.
