### ISSUE TITLE
Mod preview image not showing

### ISSUE THREAD

**Issue by dragoncosmico** [Nexus-Mods/web-issues#1518]
URL: https://www.nexusmods.com/users/myaccount?tab=files
Username on the Nexus: dragoncosmico
Bug/error being reported:  the mod pic with the star doesn't show up in mod list
Steps to reproduce: upload a mod (it happened with my last 2 mods)
Expected result: 
Actual result: see picture
Link to the affected mod/image (if relevant):
![Sin título](https://user-images.githubusercontent.com/100284028/163688481-cbc1afe6-f975-41c8-ba90-0ffe560e8f04.png)

**Comment by mrmason** [comment]
I cannot replicate this myself, can you please give any more detailed instructions on the actions you've taken to make this happen - for example was it with a new mod only ? How soon after you uploaded the mod did you see this problem ? Did it eventually fix itself ?

**Comment by dragoncosmico** [comment]
This happened the first time on April 15 with this mod https://www.nexusmods.com/thevanishingofethancarter/mods/2
Now I have 4 mods like this... I see the same in every web browser:
![Sin título](https://user-images.githubusercontent.com/100284028/163732324-87ee20f8-55ef-44dc-8e9c-cc0ed652dc0e.png)
.
I also have issues with the header image of the mod page.. It takes 3 or 4 times of uploading it to the image to stay in place...
The problem is not solved.

**Comment by dragoncosmico** [comment]
Update: When I look at my files from outside my account (private browsing) the error is not reflected.. The pics are missing ONLY from inside my account..  
Here's a pic from private browsing of my page:
![Sin título](https://user-images.githubusercontent.com/100284028/163732738-eefee1a6-2566-48cd-a0c2-dc44245ed590.png)

**Comment by dragoncosmico** [comment]
So I think this is not an actual isssue since everyone else can see the mods as they are... but it's a little annoying for me not knowing if the mods are well uploaded

**Comment by dragoncosmico** [comment]
I've just uploaded a mod and the same thing keeps happening...
![Sin título](https://user-images.githubusercontent.com/100284028/163740969-4d0bc949-3e3d-4ab4-a662-e49f0475a98f.png)

**Comment by mrmason** [comment]
Can you please let me know how you're uploading the images for the mod ? ( from which page )

**Comment by dragoncosmico** [comment]
I was logged out... when I log in again the problem was solved.
