### ISSUE TITLE
Deleted mods come back when refreshing the browser.

### ISSUE THREAD

**Issue by dragoncosmico** [Nexus-Mods/web-issues#1519]
## Your username/username(s) affected
dragoncomsico

## Bug/error being reported:
Deleted non-published mod keeps comimg back 

## Steps to reproduce:
-Have a non-published mod. 
-Delete it.
-Confirm the deletion.
-Press F5 to refresh the browser.
-Mod is back in the list.

I have reproduced this in 2 different browsers with the same result.

## Expected result:
Delete the mod.

## Actual result:
Mod is still there.

![1](https://user-images.githubusercontent.com/100284028/163701659-6687b6ba-5d89-49a4-802e-73271e84c862.png)
![2](https://user-images.githubusercontent.com/100284028/163701664-03384b0c-c0e6-4fe0-839a-e64f039ddc0e.png)
![3](https://user-images.githubusercontent.com/100284028/163701666-165f8ec7-1896-4ac7-88eb-6a1c1bf610b6.png)

**Comment by mrmason** [comment]
I'm unable to replicate this one either - I can successfully delete both a published and unpublish mod from "My Files" and it's reflected instantly. 

If you're still experiencing this problem please can you let me know the exact steps you get to cause this problem and I'll run through them? Thanks.

**Comment by dragoncosmico** [comment]
This one solves itself after a while.... I closed the browser and afer a couple of hours I went back to my mods page and the mod wasn't there so I supposed I was about high traffic on the server at the time I got the error because this don't happen anymore.
