### ISSUE TITLE
There is no way to disable daylight saving.

### ISSUE THREAD

**Issue by Fhaarkas** [Nexus-Mods/web-issues#152]
Daylight saving is erroneously applied for my time zone (GMT+8, Singapore) and there is no obvious way to disable it.  

If DLS setting is not automatic, there should be a checkbox to toggle it near timezone setting.

Not exactly an RD issue, but perhaps it's an opportune time to fix it. ;)

**Comment by verenion** [comment]
This is something managed by the forum, and is outside of our control. I will add this to our icebox for something to look at later.
