### ISSUE TITLE
Opt-in link does nothing

### ISSUE THREAD

**Issue by dragoncosmico** [Nexus-Mods/web-issues#1521]
## Your username/username(s) affected
dragoncosmico

## Bug/error being reported:
Since 3 days ago I can't Opt-in my last mod. I've already lost the points of 37 downloads... it's anoying

## Steps to reproduce:
-Upload a mod
-Wait until the virus scan and the first download is made
-Click Opt-In in the Mod page
-Mod Rewards shows up
-Click Opt-In i the Mod Rewards page
-NOTHING HAPPENS

I reproduce this from 3 different web browsers in pc.
I also tried to Opt-In from cellphone using 4G and is the same.

## Expected result:
Opt-in my mod into the Mod Rewards program

## Actual result:
I can't Opt-in my mod

**Comment by dragoncosmico** [comment]
Here's a video showing the issue

https://www.youtube.com/watch?v=FE-3q4mQ--A

**Comment by Pickysaurus** [comment]
You haven't lost any points. As long as the mod is opted in before the end of the month it'll still count. Will raise this tomorrow but it sometimes takes an hour or so to appear to opt in. You haven't provided a link to the mod you're talking about so I can't look further at the moment.

**Comment by dragoncosmico** [comment]
Oh sorry, this is the mod https://www.nexusmods.com/readyornot/mods/1110
I know sometimes I have to wait a couple of hours but this time is 3 days and counting.
Is good to know that the downloads will be counted. Thanks.

**Comment by dragoncosmico** [comment]
Just for you to know, today I've uploaded another mod and I have no issues opting-in, but I still can't opt-in this one https://www.nexusmods.com/readyornot/mods/1110

**Comment by Pickysaurus** [comment]
Can you please confirm if this is still an issue? I haven't been able to find anything wrong from our side.

**Comment by dragoncosmico** [comment]
The same thing. Very weird since I can Opt-in every other mod.

**Comment by dragoncosmico** [comment]
Ok, I finally managed to Opt-in the mod.
But it was no easy. The only way I could do it was this weird way:

-In the start page of Nexus I click on Mods in the upper menu.
-Clicked on Mod Rewards in the sub menu.
-As you can see in the video shared in this post the navigation buttons don't work at all, so for reaching the page where this mod is listed I had to right-click on the Next Page link and open it in a new tab.
-I had to do that until I reached the page where this mod is listed.
-From there the Opt-in frame showed up so I finally was able to opt-in.

Very extreme to figure this... the simple way (clicking opt-in directly in the mod page) never worked.
