### ISSUE TITLE
Changelog entries disappear

### ISSUE THREAD

**Issue by Cook66** [Nexus-Mods/web-issues#1522]
## Your username/username(s) affected
Cook66

## Bug/error being reported:
Changelog inconsistent. It doesn't show all versions.
I have 3 versions of my mod, but sometimes only 1 version is shown.
When I tried adding a missing changelog item back, suddenly the old one was there, but now after releasing a new version only v1 is visible.

It's missing in the mod manager and on the public page.

## Steps to reproduce:
 Add new changelog
  Separate text fields
  Set version to v1.2
  Add some text
  Save

Come back later, and it's gone, but it seems to take a while.

## Expected result:
A change log with all items in it

## Actual result:
A change log with items missing

**Comment by Pickysaurus** [comment]
There are currently some intermittent caching issues. Please allow 24hours for the changelog to appear for all users.
