### ISSUE TITLE
502 Bad Gateway when downloading a mod

### ISSUE THREAD

**Issue by nwn9** [Nexus-Mods/web-issues#1523]
URL: https://supporter-files.nexus-cdn.com/1704/29736/The%20Elder%20Scrolls%20Loading%20Screen%20Replacer-29736-Prime-1651183010.rar?md5=kus4_ojlCs55oQW2nuK8KQ&expires=1651270605&user_id=2145634&rip=185.234.91.150
Username on the Nexus: nwn9
Bug/error being reported: Can't download a particular mod (Immersive The Elder Scrolls Lore Loading Screen) both from the website and via the Vortex app.
Steps to reproduce: Visit the mod page and try to download the mod.
Expected result: Being able to download the files.
Actual result: An error message when trying do download it via browser: "502 Bad Gateway nginx/1.15.1" or an instant error in Vortex that download failed with status 502 Bad Gateway.
Link to the affected mod/image (if relevant): https://www.nexusmods.com/skyrimspecialedition/mods/29736

**Comment by dseszu** [comment]
Having the same issue, although on moremods. The one linked above also doesn't work for me. 
Originially stumbled upon this issue by trying to download this mod:https ://www.nexusmods.com/masseffectlegendaryedition/mods/5
I live in Austria, so I'm most likely being connected to the Prague server.

**Comment by Schiavonesca** [comment]
Same Problem, 502 Bad Gateway nginx/1.15.1 on manual download, can't download particular mods (Beyond Skyrim - Wares of Tamriel SE, Legacy of the Dragonborn Patches (Official) and I can't finish Beyond Skyrim - Bruma (1,4GB out of 2,7GB)
MO2 gives me this error:
[2022-04-30 06:33:04.633 W] Error transferring https://supporter-files.nexus-cdn.com/1704/31519/Beyond Skyrim - Wares of Tamriel-31519-1-4-1636666120.zip?md5=bicSb7rYFXjVgg4UFEcAwQ&expires=1651314787&user_id=1073161 - server replied: Bad Gateway (499)
Username on the Nexus: Kizaru
I'm downloading from Switzerland

**Comment by Pickysaurus** [comment]
This is most likely a temporary issue. Please let us know if it is still happening.
