### ISSUE TITLE
2FA QR code OTP incorrect.

### ISSUE THREAD

**Issue by Rash-in** [Nexus-Mods/web-issues#1525]
## Your username/username(s) affected

RashConcealment

## Bug/error being reported:

Setting up 2FA with 1password authenticator app.

## Steps to reproduce:
When enabling 2FA with an authenticator app the QR code reads properly and produces a code (i checked the formatting for the otp URL), but after entering in the code on the site for verification, it fails stating that it is the wrong code. (I also checked the time settings and all match.)

Using 1password as the authenticator app. I used google authenticator prior to this and it works (which is odd considering it is the same thing in the QR code URL). Additionally, I have opened a ticket with 1password in the case that it is something specific with that app, however, if there is something reproducible with your site that can be checked, it would be appreciated. 

## Expected result:
Successful setup

## Actual result:
Wrong code identified

**Comment by Rash-in** [comment]
I received a workaround. Still unsure if this is only specific to 1pass or the sites implementation of 2FA.

But in case there are others that come across this. The QR code translates to a URL in the format: 
`otpauth://totp/Nexus%20Mods:myemail@somedomain.com?secret=SOMECODEPROVIDEDBYSITE?issuer=Nexus%20Mods`

Remove the ?issuer section so that the URL is:
`otpauth://totp/Nexus%20Mods:myemail@somedomain.com?secret=SOMECODEPROVIDEDBYSITE`

**Comment by Pickysaurus** [comment]
While this doesn't seem to be a widespread bug, I really appreciate you adding the solution here :)
