### ISSUE TITLE
Nexus Forum Profile won't sync with Nexus Mods Profile

### ISSUE THREAD

**Issue by momokolove** [Nexus-Mods/web-issues#1527]
URL: https://www.nexusmods.com/users/37700840
Username on the Nexus: momokolove

Bug/error being reported: Nexus Forum Profile won't sync with Nexus Mods Profile

Steps to reproduce: upload new profile picture at https://forums.nexusmods.com/index.php?showuser=37700840
Expected result: profile picture on nexus mods will match the one on forums
Actual result: old nexus mods profile remains

Link to the affected mod/image (if relevant):
![Screenshot (201)](https://user-images.githubusercontent.com/6791592/168427166-06c41a59-b4a9-4a1c-b31f-28ebe83de0bc.png)
![Screenshot (202)](https://user-images.githubusercontent.com/6791592/168427172-c9371618-1399-44d6-8b39-5e7153e8ddcc.png)

**Comment by Pickysaurus** [comment]
This is due to cache. Please allow some time for the site profile to update

**Comment by momokolove** [comment]
> This is due to cache. Please allow some time for the site profile to update

Sorry, I assumed that at first as well but since a few days had already gone by without change I got worried.

Thanks!

**Comment by momokolove** [comment]
> This is due to cache. Please allow some time for the site profile to update

Hey, it still hasnt updated!!
