### ISSUE TITLE
unable to download any mods

### ISSUE THREAD

**Issue by Lady-Zev** [Nexus-Mods/web-issues#1528]
## Your username/username(s) affected
LadyZev

## Bug/error being reported:
 Unable to download any mod via the slow method

## Steps to reproduce:
1. went to the mod page for potion craft to download the developer console by aedenthorn
2. went to download the mod
3. do the slow download
4. the slow download button doesn't work, but the premium button does
5. tried other mods on a different game page and the same result

## Expected result:
downloaded mods

## Actual result:
no Mods :(

Update:
I was using Chrome when this happened and I tried Firefox and Opera GX and it worked. Idk what's wrong between Chrome and Nexus>

**Comment by BluesockMC** [comment]
this is happening to me too

**Comment by Inny78** [comment]
Same here.
