### ISSUE TITLE
[Redesign] When using a tab in the media part, clicking a picture and going back the tab is still selected but it displays the first tab

### ISSUE THREAD

**Issue by Zwizzor** [Nexus-Mods/web-issues#153]
Hi, when scrolling to the media part from the main page, if you click on a tab (popular 30 days for instance), click a picture from that tab and use the browser function to go back to the previous page, the tab will appear to still be selected, but it will display the content of the first tab.

**Comment by verenion** [comment]
Assigned PT#151988854

**Comment by Rrrafau** [comment]
Hi, having trouble replicating this issue. Can you please confirm that it's still happening for you and if so can you provide steps to replicate it? Thanks!

**Comment by mrmason** [comment]
I can replicate this.

1) Goto https://rd.nexusmods.com/skyrim
2) Scroll down to 'Media'
3) Click `Popular ( 30 Days )`
4) Choose any image and goto it
5) Click back
6) The tab `Popular ( 30 Days )` will be open, but it's showing the content from the `New Today` tab

**Comment by Zwizzor** [comment]
@mrmason Yup, here's a quick video showing it happen. I'm using a redirecting extension but it still happens with it disabled.
https://youtu.be/jTuYm2ONbKs

**Comment by mrmason** [comment]
This should now be fixed!
