### ISSUE TITLE
"Refine by category" Filter not working/registering 

### ISSUE THREAD

**Issue by LiadNeumann** [Nexus-Mods/web-issues#1533]
URL:  https://www.nexusmods.com/fallout4/mods/?BH=3&RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:1151,advfilt:true,include_adult:true,show_game_filter:false,page_size:20,page:1,sort_by:date,open:true,categories%5B0%5D:3,categories%5B1%5D:4,categories%5B2%5D:5,categories%5B3%5D:35,categories%5B4%5D:34,categories%5B5%5D:33,categories%5B6%5D:36,categories%5B7%5D:17,categories%5B9%5D:6,categories%5B10%5D:7,categories%5B11%5D:8,categories%5B12%5D:9,categories%5B13%5D:10,categories%5B14%5D:11,categories%5B15%5D:44,categories%5B16%5D:45,categories%5B17%5D:50,categories%5B18%5D:12,categories%5B19%5D:14,categories%5B20%5D:16,categories%5B21%5D:15,categories%5B22%5D:51,categories%5B23%5D:43,categories%5B24%5D:21,categories%5B25%5D:47,categories%5B26%5D:2,categories%5B27%5D:18,categories%5B28%5D:19,categories%5B29%5D:20,categories%5B30%5D:22,categories%5B31%5D:23,categories%5B32%5D:24,categories%5B33%5D:25,categories%5B34%5D:26,categories%5B35%5D:27,categories%5B36%5D:52,categories%5B37%5D:28,categories%5B38%5D:48,categories%5B42%5D:29,categories%5B43%5D:53,categories%5B44%5D:30,categories%5B45%5D:31,categories%5B46%5D:46,categories%5B47%5D:57,categories%5B48%5D:37,categories%5B49%5D:38,categories%5B50%5D:39,categories%5B51%5D:40,categories%5B52%5D:41,categories%5B53%5D:42,categories%5B54%5D:56,has_images:true,attributes%5B%5D:1069_true,attributes%5B%5D:1755_true,attributes%5B%5D:1795_true,attributes%5B%5D:2101_false,attributes%5B%5D:2096_false,attributes%5B%5D:2043_true,attributes%5B%5D:1429_true,attributes%5B%5D:1068_true,attributes%5B%5D:3378_true,attributes%5B%5D:2061_true,attributes%5B%5D:1040_true,attributes%5B%5D:2492_true,attributes%5B%5D:1073_true,attributes%5B%5D:2497_true,attributes%5B%5D:1428_false,range_endorsements:69%3B999999&RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:1151,advfilt:true,include_adult:true,show_game_filter:false,page_size:20,page:1,sort_by:date,open:true,categories%5B0%5D:3,categories%5B1%5D:4,categories%5B2%5D:5,categories%5B3%5D:35,categories%5B4%5D:34,categories%5B5%5D:33,categories%5B6%5D:36,categories%5B7%5D:17,categories%5B9%5D:6,categories%5B10%5D:7,categories%5B11%5D:8,categories%5B12%5D:9,categories%5B13%5D:10,categories%5B14%5D:11,categories%5B15%5D:44,categories%5B16%5D:45,categories%5B17%5D:50,categories%5B18%5D:12,categories%5B19%5D:14,categories%5B20%5D:16,categories%5B21%5D:15,categories%5B22%5D:51,categories%5B23%5D:43,categories%5B24%5D:21,categories%5B25%5D:47,categories%5B26%5D:2,categories%5B27%5D:18,categories%5B28%5D:19,categories%5B29%5D:20,categories%5B30%5D:22,categories%5B31%5D:23,categories%5B32%5D:24,categories%5B33%5D:25,categories%5B34%5D:26,categories%5B35%5D:27,categories%5B36%5D:52,categories%5B37%5D:28,categories%5B38%5D:48,categories%5B42%5D:29,categories%5B43%5D:53,categories%5B44%5D:30,categories%5B45%5D:31,categories%5B46%5D:46,categories%5B47%5D:57,categories%5B48%5D:37,categories%5B49%5D:38,categories%5B50%5D:39,categories%5B51%5D:40,categories%5B52%5D:41,categories%5B53%5D:42,categories%5B54%5D:56,has_images:true,attributes%5B%5D:1069_false,attributes%5B%5D:1755_false,attributes%5B%5D:3258_false,attributes%5B%5D:1795_true,attributes%5B%5D:2101_false,attributes%5B%5D:2096_false,attributes%5B%5D:2043_true,attributes%5B%5D:1429_true,attributes%5B%5D:1068_true,attributes%5B%5D:3378_true,attributes%5B%5D:2061_false,attributes%5B%5D:1040_false,attributes%5B%5D:2492_true,attributes%5B%5D:1073_true,attributes%5B%5D:2497_true,attributes%5B%5D:1428_false,range_endorsements:69%3B999999 for example but any search result.
Username on the Nexus: WOLFDWARF
Bug/error being reported: when unchecking an option from the "Refine by category" list and then clicking Apply Filters. The unchecking of the unchecked option does not seem to register and, the unchecked option returns to be checked. Thereby the filtering does not take place. 
Steps to reproduce: For example in the above url, if one would wish to uncheck the "Body, Face, and Hair" option from the options, such that one no longer sees "Body, Face, and Hair" mods in the search result, then press Apply Filters, then momentarily the results would return but the "Body, Face, and Hair" option in the "Refine by category" would yet again be checked.
Expected result: The unchecked option to remain unchecked and the corresponding mods to be filtered/refined out.
Actual result: The unchecked returns to be checked.

**Comment by Pickysaurus** [comment]
I believe this bug may be because of the URL you've used. 

If you're browsing from https://www.nexusmods.com/fallout4/mods/ it doesn't seem to happen.
