### ISSUE TITLE
Painfully slow site access/site access failure. 

### ISSUE THREAD

**Issue by Bored2022** [Nexus-Mods/web-issues#1536]
## Your username/username(s) affected
SteveB88

## Bug/error being reported:
Recently, the Nexus Website has been almost inaccessible. Most of the time, I am given the "unable to connect" message in Firefox or the "ERR.CONNECTION CLOSED" in Edge. There are very times I am able to connect, when I can connect it is extremely fast for a moment or so and then the site just gives up, usually being comically slow and causing my browser to spit out error codes. 

## Steps to reproduce:
Try to access Nexus Mods. 
Firefox produces blank page or error message. Edge follows same procedure, usually "ERR.CONNECTION RESET" error code.

## Expected result:
To be able to access the site and download mods (seriously, this is the 21st century. Is it so difficult to get a website to work efficiently?)

## Actual result:
Timed out error code. 
![Web capture_2-6-2022_111554_www nexusmods com](https://user-images.githubusercontent.com/105631917/171546443-559b83cf-8546-4534-8e65-50df599b812b.jpeg)

**Comment by Pickysaurus** [comment]
I would imagine this was a temporary outage when you opened this issue.

**Comment by Bored2022** [comment]
This isn't a temporary issue. This is quite common happening several times a day. Most of the time, it is near impossible to access the site.

**Comment by Pickysaurus** [comment]
As this seems to be an issue that is exclusive to your setup, I'd suggest starting here: https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by baldnick** [comment]
I also encountered with the same problem too, for some mods and the vortex manager app it occurs, exactly connection time out. Even if I download mod with the vortex manager(I got the manager from git hub) the download still fails even in the manager. However some mod still works, this is very weird.

**Comment by baldnick** [comment]
![connection time out](https://user-images.githubusercontent.com/69240256/183286945-667bf28f-e57c-4f3b-b2a9-97c91c1a2c7c.png)

**Comment by baldnick** [comment]
![connection time out ye](https://user-images.githubusercontent.com/69240256/183286967-34015861-c079-49f0-9c28-d6deb315b9b2.png)

**Comment by baldnick** [comment]
However, I discovered that I am able to download files that are smaller in size, like around few mbs.
