### ISSUE TITLE
Video review - linked mod does not save and does not show up on mod page for user video

### ISSUE THREAD

**Issue by juliandwillett** [Nexus-Mods/web-issues#1537]
## Your username/username(s) affected
KittenChariot1243

## Bug/error being reported:
I am submitting video reviews on Nexus, seeking to link the discussed mods in the appropriate box. Despite entering the correct link leading to the mod, the video does not show up on the mod's user videos. When I attempt to look at the video again in the edit scene, the link is no longer there. As an aside, you can only enter one mod per video versus multiple mods as I do in my videos.

## Steps to reproduce:
1. Upload video putting down the mod you are referencing.
2. Open the edit video feature after uploading the video
3. Note that the entry for the linked mod is no longer there (and that you can only enter one mod at a time)

## Expected result:
The video link remaining in the entry and the video showing up on the mod page as a user-submitted video.

## Actual result:
Video link does not stay or show up on mod user videos.

**Comment by Pickysaurus** [comment]
The video needs to be approved by the mod author before it will appear.
