### ISSUE TITLE
Hot Mods Section at Top of All Game Homepages Broken as of 30th May

### ISSUE THREAD

**Issue by Dmitrias** [Nexus-Mods/web-issues#1541]
## Your username/username(s) affected

All nexus users, because it happens regardless of whether you're logged in or out.

## Bug/error being reported:

Since the 30th of May, the hot mods section displayed **at the top** of the homepage for games are being displayed in the **wrong order.** Less endorsed mods are **passing** more endorsed mods that were released in the same timeframe.

## Steps to reproduce:

1. Go to a games homepage, e.g the witcher 3 homepage: [link.](https://www.nexusmods.com/witcher3) Ensure there are no slashes after the games name in the URL. 

Technically that's all you need to do to reproduce the bug, but, of course I shall expand on how you can confirm it is a bug in the following steps.

2. To confirm the bug is there, look at the hot mods displayed at the top of this homepage - take a mental note of the order that they go in, from the top left corner, all the way down to the bottom right corner.

3. Now, pull up the actual dedicated trending mods page [here](https://www.nexusmods.com/witcher3/mods/trending/) for **reference only,** as this particular page is not bugged, we are just looking at it to confirm the homepage is misordered. 

4. On the dedicated trending page, click the "sort by" drop-down menu in the top right corner, and select "endorsements." This will show the correct order that the featured hot mods on the separate homepage site linked in step 1 would normally use in a non-bugged situation.

5. Make a mental note of the order that the mods on the dedicated trending page are going in, then return to the homepage, and look at the hot mods displayed at the top of page, compare the order of those mods to those on the trending page, you will notice the discrepancy that the homepage has.

## Expected result:

The most endorsed mod released in the eligible timeframe (in witcher 3's case, 28 days since release) should be in the top left corner of the hot files section on the homepage. 

The second most endorsed mod should be to the right of the most endorsed one.

The 3rd most endorsed mod should be underneath the most endorsed one, the 4th most endorsed mod should be to the right of the 3rd most endorsed one, and so on and so forth until you reach the 7th most endorsed mod in the bottom right corner.

## The result that actually happened:
The hot mods were all mixed up at the top of the homepage.

## Pictures of the bug:
First, here is the **functioning trending page,** which shows the correct order for the the mods (labelled for ease of use):
![trending example](https://user-images.githubusercontent.com/107069526/172474824-c0d9df1f-f47d-4d37-902a-571d39dea006.png)

Then, here is the **bugged homepage,** with the wrong order (labelled for ease of use):
![homepage example](https://user-images.githubusercontent.com/107069526/172475193-c114ebe2-3472-4e6c-a3d4-8015609afac8.png)

**Comment by Dmitrias** [comment]
As an addendum: at times, the 2 very top hot files on the homepage do sometimes go in the right order, giving the illusion that the glitch has gone away.

But then, once you look at the hot files mods beneath the featured top 2, and then compare that to the order of those of the separate trending page sorted by endorsements, you realize that the following mods beneath it on the homepage are ordered incorrectly.

Weirdly, the order of the mods do seem to rotate from day to day, although I've not seen it go in the right order for all 7 featured hot mods on the homepages yet so far.

So I'm not really sure what data it's currently using to rotate the mods with. Because whilst it's not the endorsement counter currently, right now...

Mods that have been released too long after the timeframe in which a mod can be featured do fall off the hot mods page as expected, but, even when all the most endorsed mods are recent enough, it still shuffles them around from day to day, so, I wonder what it's basing this off?

Anyways, those are my extra observations. Thanks! ^^

**Comment by Pickysaurus** [comment]
Sorry for the late reply. We've had problems replicating this reliably as it appears to be a cache issue. Each time this is reported, it appears to have corrected itself by the time we are able to check it.

**Comment by Dmitrias** [comment]
Is there anything I could do on my own end, then? Because I have the opposite issue, it never reverts for me.

**Comment by Pickysaurus** [comment]
I have been able to replicate it so we are investigating it. The working theory is a mismatch in when the endorsement counters are recalculated vs when the mod caches are updated.

**Comment by Pickysaurus** [comment]
This should have been fixed a few days ago now.

**Comment by Dmitrias** [comment]
It seems to be still ongoing on my end. But I appreciate those who looked into it!

**Comment by Pickysaurus** [comment]
Could you give another example so I can pass it on? It looks fine to me.

**Comment by Dmitrias** [comment]
Hi, yes I can, here's an example of the issue on the dragon age: inquisition nexus homepage (and link to the homepage here: https://www.nexusmods.com/dragonageinquisition)
![dai example2](https://user-images.githubusercontent.com/107069526/182706705-8e1d2991-b768-4df3-893e-a19b5511427a.png)

As you can see, the no repeat requisitions mod (https://www.nexusmods.com/dragonageinquisition/mods/3832) has 8 endorsements, whilst the C.A.R.P. - Concept Art Sera Overhaul mod (https://www.nexusmods.com/dragonageinquisition/mods/3826) has 16 endorsements.

So, the Concept Art Sera mod has more endorsements than the no repeat requisitions mod, but, it's the no repeat requisitions mod that is occupying the spot where the most endorsed mod for the designated timeframe would normally go.

The timeframe for mods to stay trending is 28 days since release on the dragon age: inquisition nexus, no repeat requisitions was released on 29 July 2022, and the Concept Art Sera mod on 24 July 2022, so the Concept Art Sera mod is still eligible to occupy the top spot.

**Comment by Dmitrias** [comment]
Oh, also, here's another example I found, on the red dead redemption 2 nexus homepage. (link: https://www.nexusmods.com/reddeadredemption2)

So here's a picture of the homepage, labelled with the number order in which they should be appearing in - 1) and 2), the 2 most endorsed for the time period are ordered as expected, but the rest aren't:

![red dead homepage](https://user-images.githubusercontent.com/107069526/184134802-17a7d487-3571-4fdb-b3bc-c72d287fa002.png)

Then here's a picture of the correctly ordered trending page, I set it to sort by endorsements and set the timeframe to the last 28 days since that's the time period for mods to stay trending on this games nexus:
![red dead exampe](https://user-images.githubusercontent.com/107069526/184135456-5e913feb-648f-4a74-9bd5-69045c76c947.png)

So the disordered files on the homepage are as follows:
Vignette disabler (https://www.nexusmods.com/reddeadredemption2/mods/1569) has the 3rd most amount of endorsements at the time I am posting this, but is placed in the spot for the 5th most endorsed mod at the time I am posting this.

LIT (https://www.nexusmods.com/reddeadredemption2/mods/1587) missing from the hot mods section on the homepage entirely, despite it being the 4th most endorsed mod for this time period.

Personal boat (https://www.nexusmods.com/reddeadredemption2/mods/1585) has the 5th most amount of endorsements, but is placed at the spot for the 7th most endorsed mod on the homepage.

Maps, Maps, Maps (https://www.nexusmods.com/reddeadredemption2/mods/1579) this is the 6th most endorsed mod for the timebeing, but is missing from the hot mods section of the homepage entirely. 

Brawling Style Switcher 1.3 (https://www.nexusmods.com/reddeadredemption2/mods/1607), has the 7th most endorsements but is placed at the 3rd most endorsements spot on the hot mods section of the homepage.

And some of the other mods which you can see by the number labels.

**Comment by Pickysaurus** [comment]
Sorry this took so long, the issue should now be fixed again (hopefully for good this time!)

**Comment by Dmitrias** [comment]
It seems it doesn't want to stick this time around, as well. Sorry! But appreciated, anyhow.
As example:

From witcher 3 nexus [homepage](https://www.nexusmods.com/witcher3) - long shadows ([link](https://www.nexusmods.com/witcher3/mods/7045)) published 23 October, 80 endorsements, featured top hot mod (witcher ability icons redone, [link](https://www.nexusmods.com/witcher3/mods/7073)) has 68 endorsements:

![hot mods](https://user-images.githubusercontent.com/107069526/200860496-487a5d3f-b99c-4e10-ada5-f8649fde4064.PNG)

If it's not possible to fix well then thankyou for everybody that looked into it, either way!

**Comment by Pickysaurus** [comment]
Thanks for the report, it seems the fix that was applied made all games use the 7 day period rather than whatever is set on the game config.

**Comment by Pickysaurus** [comment]
After digging into this, it appears that the feature is working as intended but it is poorly documented.

We had assumed the Hot Files show "mods uploaded in the last X days sorted by endorsements", however, what it actually shows is "mods uploaded over the last X days sorted by endorsements over 7 days". 

This is definitely a bit confusing as we didn't know that was how it worked until our team dug into the original code, but it has been that way for many years. 

We've updated the tooltip for the "Trending" tab to reflect what it is actually showing. 

If you'd like to suggest an improvement to the sorting, please feel free to do so here: https://feedback.nexusmods.com/
