### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Moedav93** [Nexus-Mods/web-issues#1542]
## Your username/username(s) affected
Enralin 

## Bug/error being reported:
ERROR
Unfortunately there was an error while processing your payment: Authentication Required. (Transaction ID: n15j7pb7)
Please check your payment information and try again. If the problem persists please contact your payment provider. 

## Steps to reproduce:

When trying to pay for a premium, I recieve this message after confirming payment. 

## Expected result:
 Premium access activated 

## Actual result:
Recieves error message

**Comment by col427** [comment]
also having this issue.

**Comment by Pickysaurus** [comment]
Unfortunately, there's not anything we can do there. Your payment provider is rejecting the purchase. Please contact your bank or try the PayPal option.
