### ISSUE TITLE
My vortex is broken NEED HELP!!!

### ISSUE THREAD

**Issue by MonkeyMan6969** [Nexus-Mods/web-issues#1545]
Battle2Modder

for some reason, my vortex thinks my steam libary is on another drive but it's not and is no longer allowing me to use it without breaking my games.

This keeps happening every time I open vortex

I want Vortex to work properly and for me to install and use mods

It keeps trying to access

 a drive that doesn't exist on my PC
<img width="479" alt="s" src="https://user-images.githubusercontent.com/69944757/174462407-98858074-2c23-4406-bac5-f7dff19c54f3.PNG">

**Comment by Pickysaurus** [comment]
This tracker is for issues with the Nexus Mods website. For help with Vortex, see our support forums here: https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/
