### ISSUE TITLE
Bug in 2FA setup process

### ISSUE THREAD

**Issue by techsavvy531** [Nexus-Mods/web-issues#1546]
## Your username/username(s) affected
CyberSavvy

## Bug/error being reported:
When trying to switch authenticator apps for account sign-in, QR code given when trying to add the new authenticator app not only did not work when trying to verify, but it was actually the exact same QR code given to the previous authenticator app as well.

## Steps to reproduce:
IMPORTANT: Remember each security key generated when going through the 2FA setup process.
1. Setup a Nexus Mods account with 2 step verification using an authenticator app (In my case, I was switching from Google Authenticator).
2. Now, disable that same 2FA that you enabled in step 1. Do NOT delete the entry from the authenticator app itself. You'll need this for comparison. Do NOT sign out of the Nexus account after doing so either.
3. Go through the steps to setup 2FA on the Nexus account again, but this time use a different authenticator app (I opted for LastPass Authenticator).
4. First, compare the security keys from each 2FA setup iteration. In my case, they were the exact same.
5. Now compare the actual authentication codes being generated in each authenticator app. They should also be the same including time sync.
6. Lastly, when trying to verify the authentication code from the second authenticator app, Nexus Mods declines it saying it is incorrect when it fact it was the code that was given.
7. The only thing that corrected this issue was relogging my Nexus account and trying the 2FA setup again. At that point, a new security key was generated and I was able to enable 2FA using the new authenticator app (LastPass Authenticator).

## Expected result:
For a new security key to be generated with EVERY initiation of a 2FA setup. Even in the same browser session.

## Actual result:
The same 2FA security key as my recently disabled 2FA method was given to me for setting up a new 2FA authenticator app.

**Comment by Pickysaurus** [comment]
Try the steps outlined here. Problems with the user system are often caused by your setup: https://help.nexusmods.com/article/113-troubleshooting-website-issues

**Comment by techsavvy531** [comment]
Just saying, this unlikely an issue in my end. It's not that I can't login,
but I encountered that bug when setting up 2FA. It's an issue with the code
your website displays to me. I have no control over that.
