### ISSUE TITLE
Unable to remove favourite games

### ISSUE THREAD

**Issue by WeirdScience06** [Nexus-Mods/web-issues#1547]
## Bug/error being reported:

The ability to remove games from favourites is broken

## Steps to reproduce:
<!--
1. Hover over any favourite game
2. Click X to remove

### Example:
1. Click X on game Days Gone within the favourites bar

## Expected result:
The game to be removed from favourites

## Actual result:
Results in an error message
'There was a problem with your request

3803 has already been removed. Please refresh and check again.'
<img width="1015" alt="firefox_kcH9WeiPUW" src="https://user-images.githubusercontent.com/1296569/175365842-e5c8e2c4-d8f0-4248-afbc-cd057922639b.png">

**Comment by Pickysaurus** [comment]
This is a known issue, try again in a few hours and it will work again.
