### ISSUE TITLE
Issue logging into Vortex

### ISSUE THREAD

**Issue by Nosirrath** [Nexus-Mods/web-issues#1548]
## Your username/username(s) affected

Nosirrath

## Bug/error being reported:

Tried to login to vortex. After being taken to the website and selicting "authorise" I was taken back to vortex and tol "login attempt failed"

At first, I thought it was similar to issue #895 on the Vortex forum about the display/UI not showing correctly. But after restarting the Vortex app, it still says I'm not logged in

edit: After posting this comment I realised its on the web-issues page and I don't know how to change it, sorry. Issue 895 that I mentioned is this one https://github.com/Nexus-Mods/Vortex/issues/895

## Steps to reproduce:

Login to account on Vortex

## Actual result:

"login attempt failed"

<img width="1043" alt="Screenshot 2022-06-28 204813" src="https://user-images.githubusercontent.com/108367687/176273442-b0ab722a-b4ae-47b3-8e6f-d053849046dc.png">

**Comment by BigBizkit** [comment]
Works as expected now.
