### ISSUE TITLE
error 401 in login process

### ISSUE THREAD

**Issue by viniroxo** [Nexus-Mods/web-issues#1549]
## Your username/username(s) affected
Viniceba

## Bug/error being reported:
When trying to log in to the desktop app I get an error 401

## Steps to reproduce:
just try to log in and the 401 error notification appears

## Expected result:
I hope I can login and download the mods

## Actual result:
401 error happens in all the requests I make

**Comment by Pickysaurus** [comment]
Duplicate of #1548
