### ISSUE TITLE
Odd problem with moving comment to bug reports.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#155]
This may well be a one-off. But when I moved a comment to bug reports it actually copied a bug report from a completely different mod to my page.... the report was still owned by the original mod creator and seems to be persistent. 
![bugreportweirdness](https://user-images.githubusercontent.com/31670524/31588312-da0b5222-b1e7-11e7-92ad-450ea1d17ff0.PNG)

**Comment by Pickysaurus** [comment]
https://rd.nexusmods.com/skyrimspecialedition/mods/11802?tab=posts

**Comment by verenion** [comment]
Assigned PT#151988946

**Comment by iamtiz** [comment]
It was a weird occurrence indeed. The link from the post to the bus issue is now the correct one, and the underlying code which most likely caused the issue is also fixed
