### ISSUE TITLE
Profile Option to Censor NSFW images in Search and Feeds

### ISSUE THREAD

**Issue by Webmetz** [Nexus-Mods/web-issues#1550]
**Is your feature request related to a problem? Please describe.**
I don't want to exclude NSFW mods from my searches, but I still want to be able to share my search screen with other people without nude images appearing.  This often an issue for Twitch Streamers as well.  They can't even visit the homepage of your site without fear of violating TOS.

**Describe the solution you'd like**
An option in the profile to "Censor NSFW images in Search and Feeds".  That way we can still see the **title** and **description** of the item, but not the **nsfw preview image**.  This would allow streamers to visit your site without worrying about being banned from the streaming platform.  
The Censoring could be in the form of a heavy blur, pixelation, black box, placeholder, or just no image.

**Comment by Pickysaurus** [comment]
This isn't something we are going to do short-term so it's best to turn off adult content for now.

**Comment by Pickysaurus** [comment]
https://feedback.nexusmods.com/posts/54/nsfw-blur-option-learn-of-new-nsfw-mods-via-name-w-o-the-constant-deluge-of-boobs-and-porn
