### ISSUE TITLE
Blocked users on an unpublished mod I did not block myself

### ISSUE THREAD

**Issue by dovaya** [Nexus-Mods/web-issues#1551]
## Your username/username(s) affected
[dovaya](https://www.nexusmods.com/users/37990475)

## Bug/error being reported:
On an unpublished mod of mine, there are blocked users that I did not block myself. They were already there when I first entered the "Permissions" section of the mod. I have never interacted with or blocked said users on any mod of mine. It is unknown who blocked them. One of them was even blocked before I registered on Nexus.

I am the sole mod author, no one else has access. Here is a link to the unpublished mod where the blocked users show up:
https://www.nexusmods.com/enderal/mods/edit/?id=299&game_id=2736&step=permissions
![bug](https://user-images.githubusercontent.com/30447927/176949724-0d71b63c-e57c-47aa-9e7a-895fe2fd78b2.png)

## Steps to reproduce:
Go to the unpublished mod, got to the "Permissions" section of the edit page and check the blocked users.

## Expected result:
No blocked users.

## Actual result:
Blocked users I did not block myself who are unknown to me.

**Comment by dovaya** [comment]
There is another mod where this issue came up. Another unpublished mod, two users blocked that I didn't block myself. Same phenomenon
![bug2](https://user-images.githubusercontent.com/30447927/178157435-8a76f6f1-38f0-44a4-a7af-5aeded3ac2e6.png)
.

**Comment by dovaya** [comment]
And another one:
![bug3](https://user-images.githubusercontent.com/30447927/178164021-eff40592-0707-441b-962a-52fcdc6223c1.png)

**Comment by Pickysaurus** [comment]
I have not been able to replicate this. The link you provided does not show any blocked users.

**Comment by dovaya** [comment]
Yeah I know, I unblocked them all because I was about to publish these mods. Just wanted to let you know that there might be something off in your backend.
