### ISSUE TITLE
card verification failed when buying premium but still get a hidden transaction of 1 pound.

### ISSUE THREAD

**Issue by yuri8822** [Nexus-Mods/web-issues#1552]

**Comment by Pickysaurus** [comment]
Hi yuri8822,

I'm afraid we have no control over credit/debit card validation. This is a communication between BrainTree and your bank. I would suggest making sure your card details are correct and if it still fails, you may want to ask your payment provider why they aren't allowing the payment to go through. 

In the event your bank is rejecting the transaction, you may have more success with the PayPal option. 

As far as I know, the £1 transaction is used as a test of the authorisation with your bank and is only put on hold for a short time before being refunded.
