### ISSUE TITLE
Page's html gets downloaded instead of actual mod

### ISSUE THREAD

**Issue by Nontu2** [Nexus-Mods/web-issues#1553]
## Your username/username(s) affected
NOBOZOLOL

## Bug/error being reported:
Whenever i try to dowload any mod, page's html get dowloaded instead of actual mod

### Example:
1. I click on slow download button
2. Html gets dowloaded
3. Repeat
-->

## Expected result:
Mod should get dowloaded

## Actual result:
Page's html gets dowloaded instead

**Comment by Pickysaurus** [comment]
Please see this help article: https://help.nexusmods.com/article/113-troubleshooting-website-issues
