### ISSUE TITLE
Stuck In Ranni's Tower after Coop session.

### ISSUE THREAD

**Issue by Blarney77** [Nexus-Mods/web-issues#1554]
## Your username/username(s) affected
Blarney77

## Bug/error being reported:
We did the quest where we speak to Ranni and then speak to Iji and the sorcerer but Blaidd was NOT in the tower as he is supposed to be.  I believe since he was not there, and perhaps in MY world I was not far enough yet?... because I could not talk to Blaidd I could not leave.  No NO NPCs are there and Ranni is asleep.  I can join someone else in their world, but as soon as I am back I am stuck.  When a friend joined me he was stuck there as well.  He had to leave my world to do anything.  When I return to my world I'm stuck here.

## Steps to reproduce:
I joined another player.  We quested.  We did the Ranni quest with him and I accepted to join Ranni.  Only two out of three NPCs were in the tower.  No Blaidd.  Now all NPCs are gone or asleep and no exit is possible unless joining someone else in their world.

## Expected result:
Kinda Obvious.

## Actual result:
Still Stuck!

**Comment by Pickysaurus** [comment]
This tracker is for problems with the Nexus Mods website. Please use the comments/bugs section on the mod page for mod specific support.
