### ISSUE TITLE
Two different pages for the same game

### ISSUE THREAD

**Issue by derbayer36** [Nexus-Mods/web-issues#1555]
## Your username/username(s) affected
derbayer36

## Bug/error being reported:
Street Figher 4 has two separate pages:

One is called Street Fighter 4 
https://www.nexusmods.com/streetfighteriv

While the other is Ultra Street Figher IV
https://www.nexusmods.com/ultrastreetfighter4

Both are actually the same game and mods from both pages work in both versions of the game. I think that both pages should be merged together.

**Comment by Pickysaurus** [comment]
I see you sent an email to our support team about this, so you'll get a reply there.
