### ISSUE TITLE
Pale Moon browser cannot log in due to aggressive DDoS protection

### ISSUE THREAD

**Issue by Knatan** [Nexus-Mods/web-issues#1556]
## Your browser affected
Pale Moon version 28.9.3 (64-bit)

## Bug/error being reported:
When I click Log In it takes me to the cloudflare ddos protection page and stays there forever.

## Steps to reproduce:
Go to https://www.nexusmods.com/
Click Log In button in upper right corner
"DDoS protection by Cloudflare" kicks in and browser is stuck there permanently

## Expected result:
It's supposed to allow me to type my log in credentials. Unfortunately I can't even reach the page where I type the log in data.

## Actual result:
It's stuck on the cloudflare page.
A few things worth noting
1. at the bottom of my browser it says this:
https://i.imgur.com/MA7W2qJ.png
Sometimes it permanently says this.
Sometimes when I reload and try again, it says that momentarily, then it says "Done", which is normal.

2, In the address bar it says "https://users.nexusmods.com/auth/sign_in"
But occasionally it will show this for a split-second
https://i.imgur.com/VbBZNAT.png
(I have obfuscated part of the random address for safety concerns)
After the split-second it shows "https://users.nexusmods.com/auth/sign_in" again.

**Comment by themagickoala** [comment]
This article should help shed some light on why this happens and how you can prevent it: https://www.ghacks.net/2022/05/05/fix-pale-moon-browser-not-passing-cloudflares-checking-your-browser-verification/

**Comment by 12port** [comment]
I have the same problem. Clicking the link for the article above does the same thing. This same problem happened a couple months ago. NEXUS! CLOUDFARE SUCKS! USE SOMETHING ELSE

**Comment by Pickysaurus** [comment]
More general tips. Be aware that if you use a non-standard browser it's less likely to be supported. We support Firefox but not any of the offshoots. https://help.nexusmods.com/article/113-troubleshooting-website-issues
