### ISSUE TITLE
Super slow download speeds ~(20-250 kbps)

### ISSUE THREAD

**Issue by Novaaa-UwU** [Nexus-Mods/web-issues#1558]
## Your username/username(s) affected
OVERHAUL2004, OVERHAUL201310

## Bug/error being reported:
Sometimes the download speeds are normal but most of the times download speeds from nexus mods are super slow as mentioned above in the title.

**Screenshot of the download Speeds below:**
![image](https://user-images.githubusercontent.com/98371469/179737976-69351011-834d-46fc-bdd9-f81a65956c88.png)

## Account info:
I am a free user and I have disabled my ad blocker for this website.

## ISP info & Speed Test:

- ISP             : JIO Fiber Broadband, India
- Speed Test : 
![image](https://user-images.githubusercontent.com/98371469/179741387-02956b80-ef26-4e17-abce-1b62d31a3d7f.png)

## Steps Taken:

1.  I have tried using two different accounts, still getting slow speeds
2.  I have even tried downloading on different browsers but no difference.
3.  I have even tried using external download manager such as IDM and XDM, still the same results.

### I entered the following commands on *Command Prompt* and here are the results:

-  **_`ping supporter-files.nexus-cdn.com`_**
![image](https://user-images.githubusercontent.com/98371469/179740078-17f7b350-9701-4b74-aa19-d2d8ccce5856.png)

- **_`tracert supporter-files.nexus-cdn.com`_**
![image](https://user-images.githubusercontent.com/98371469/179740572-3c4610f1-6b55-4089-9378-20357cb5d9df.png)

## Expected result:
Atleast 1-2 mbps

## Actual result:
20-250 kbps

**Comment by Pickysaurus** [comment]
Sorry to hear you're having problems. Please see our help guide here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
