### ISSUE TITLE
Trying to download a Collection

### ISSUE THREAD

**Issue by MrBuddha19** [Nexus-Mods/web-issues#1559]
## Your username/username(s) affected

MrBuddha19

## Bug/error being reported:

![image_2022-07-23_203234526](https://user-images.githubusercontent.com/14022324/180630997-70391d16-f48a-49b1-9fae-d267acca459d.png)

## Steps to reproduce:
1. Finding a collection to download
2. Click Add to Vortex
3. Warning Pops up

## Expected result:

Adding the collection to Vortex

## Actual result:

Getting a Warning: Uncaught exception: invalid nxm-link: nxm://stardewvalley/collections/tckf0m/revisions/16

**Comment by Pickysaurus** [comment]
You have an outdated version of Vortex. Please check your software is up to date before reporting bugs

**Comment by MrBuddha19** [comment]
I checked my vortex to the vortex download on the website and i have the current version

**Comment by Pickysaurus** [comment]
This error only occurs with versions older than 1.5.0 - if you have the latest version please report this via the in-app feedback system and include a log file. This tracker is for issues with the website.

**Comment by Pickysaurus** [comment]
Scratch that. The screenshot you are showing is from Mod Organizer - so this is unrelated to Vortex. Set Vortex to handle NXM links to fix this.

**Comment by MrBuddha19** [comment]
how do i do that?

**Comment by Pickysaurus** [comment]
Vortex -> Settings -> Download -> Handle Mod Manager downloads -> Turn it on.

**Comment by MrBuddha19** [comment]
ok it works now thank you
