### ISSUE TITLE
Webpage menu sizing

### ISSUE THREAD

**Issue by Karna5** [Nexus-Mods/web-issues#156]
Hello. I'm using Windows 10 Edge browser with 300% magnification and a desktop resolution of 4k with 350% font increase, and I notice your menus don't fit in the drop down boxes. Other websites don't have this issue. You can see the photo below where the menu on the right is clipped short.
![newsite](https://user-images.githubusercontent.com/32823595/31589673-89b3fe1e-b1d3-11e7-8465-9b724c235710.jpg)

**Comment by mrmason** [comment]
Hi, these boxes don't actually exactly align on any resolution - I'm not sure that we can make them fully align on all browsers on all resolutions - it might be possible - We will take a look into this at a later date.

**Comment by Karna5** [comment]
Hi, MrMason. That makes sense. I used to work with a web designer some years back when I was  software developer, and he was always having to deal with multiple browsers as they updated. On a side note, though, I think adding an always-on scroll bar to menus like that could solve the problem. It's up to you, of course, as it's your site :)
