### ISSUE TITLE
This file is currently being uploaded to our CDN servers.

### ISSUE THREAD

**Issue by Bruce-AM** [Nexus-Mods/web-issues#1560]
Username: BruceAM
Problem: This file is currently being uploaded to our CDN servers. If this is taking longer than expected, please contact a moderator or [email us.](mailto:support@nexusmods.com)
Link to the mod: https://www.nexusmods.com/stormworksbuildandrescue/mods/19?tab=files

**Comment by Pickysaurus** [comment]
Fixed, strange it took so long for anyone to report it.
