### ISSUE TITLE
Download error. Files dont download with his extension file (.rar)

### ISSUE THREAD

**Issue by Markul91** [Nexus-Mods/web-issues#1561]
URL: https://www.nexusmods.com/finalfantasy7/mods/42?tab=files
Username on the Nexus: MisterMarkul
Bug/error being reported: When i download a file .rar of some mod, the download dont have the .rar extension(some users report the same to me) . I test this with 3 different mods, and always download  without the .rar extension.  I use Firefox  102.0.1 (64-bit)

**Comment by Pickysaurus** [comment]
This appears to be an issue exclusive to some Firefox users. I suspect it's related to a browser addon of some kind.
