### ISSUE TITLE
can't pay for membership

### ISSUE THREAD

**Issue by Alexcap006** [Nexus-Mods/web-issues#1562]
## Your username/username(s) affected
alexcap006

## Bug/error being reported:
I am trying to use a visa gift card to buy a membership  but it keeps saying that there is an error

## Steps to reproduce:
1. Step 1 i went to buy the memebrship
2. Step 2 i typed everything in like 1000 times
3. Step 3 and i pressed enter

## Expected result:
that it would let me buy the stupid membership 

## Actual result:
kept saying over and over, "Credit card verification failed. Please check your information and try again." even though i checked it like 20 times

**Comment by Pickysaurus** [comment]
I'm afraid we have no control over credit/debit card validation. This is a communication between BrainTree and your bank. I would suggest making sure your card details are correct and if it still fails, you may want to contact your payment provider. 

Thanks for supporting our community!
