### ISSUE TITLE
Slow Download Bypass

### ISSUE THREAD

**Issue by pvlsdlk** [Nexus-Mods/web-issues#1563]
## Your username/username(s) affected
My username on Neuxs is AWolf359 (https://www.nexusmods.com/users/102046778)
everyone can do this

## Bug/error being reported:
Slow download waiting time (5 second timer) can be totally bypassed using Firefox with a uBlock Origin extension installed.

## Steps to reproduce:

1) Download latest firefox browser
2) Download uBlock Origin extension to your firefox browser
3) Visit nexus mods with uBlock enabled and try to download any file on the site using slow download
4) 5 second timer takes approx. 0.3 miliseconds to fill and your download file starts downloading almost instantly thus bypassing any timer
5) win?

## Video how to reproduce bug (without sound):
First Attempt: Downloading with uBlock Origin DISABLED - timer works
Second Attempt: Download with uBlock Origin ENABLED - timer bypassed

https://youtu.be/KcYvV-_1KrM

**Comment by Pickysaurus** [comment]
Thanks for the report. This should be resolved.

**Comment by Evan-Sackmann** [comment]
thanks dick

**Comment by alejandro-esquivel** [comment]
> ## Your username/username(s) affected
> My username on Neuxs is AWolf359 (https://www.nexusmods.com/users/102046778) everyone can do this
> 
> ## Bug/error being reported:
> Slow download waiting time (5 second timer) can be totally bypassed using Firefox with a uBlock Origin extension installed.
> 
> ## Steps to reproduce:
> 1. Download latest firefox browser
> 2. Download uBlock Origin extension to your firefox browser
> 3. Visit nexus mods with uBlock enabled and try to download any file on the site using slow download
> 4. 5 second timer takes approx. 0.3 miliseconds to fill and your download file starts downloading almost instantly thus bypassing any timer
> 5. win?
> 
> ## Video how to reproduce bug (without sound):
> First Attempt: Downloading with uBlock Origin DISABLED - timer works Second Attempt: Download with uBlock Origin ENABLED - timer bypassed
> 
> https://youtu.be/KcYvV-_1KrM

Thanks for ruining the website.
