### ISSUE TITLE
Search not including all results that match keywords exactly

### ISSUE THREAD

**Issue by Eri-Boden** [Nexus-Mods/web-issues#1564]
## Your username/username(s) affected
EriBoden

## Bug/error being reported:
When searching for most things the search will leave out a lot of results that SHOULD have been present, mods that are present in modder's profiles but are missing from searches unless certain unknown parameters are met. I've noticed it for multiple different searches over the years when trying to find old mods and losing them due to the search function not finding them but I found one that I can reproduce at the moment. I'm now beginning to wonder how many mods I'm missing out on that simply aren't appearing in searches despite having the correct keywords in them.

**I have no blocked tags or authors. NSFW is enabled. My settings haven't been adjusted very much, I simply pay for premium to remove ads.**

## Steps to reproduce:
1. Search Fallout 4 Nexus for "Halo".

## Expected result:
A list of EVERY mod that has the word "Halo" in it's name.

## Actual result:
17 mods appear. A mod named "CROSS_Halo" by Niero is missing despite explicitly containing the word "Halo" in it's title. The mod is visible from their Userfiles but not through the search function. This would explain why sometimes I cannot find mods through the search despite knowing the exact words that were in the filename.

Link produced by clicking "Shareable Link": https://www.nexusmods.com/fallout4/search/?RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:1151,advfilt:true,search%5Bfilename%5D:halo,include_adult:true,page_size:20,show_game_filter:false
![image](https://user-images.githubusercontent.com/24725763/182944985-ec4ccef4-c966-460d-b59c-835ee53889c7.png)

**Comment by Eri-Boden** [comment]
Interesting update: I decided to sort by Random and new results appeared, including the expected mod. Every other sorting method excludes the same mods except random.

**Comment by Pickysaurus** [comment]
Seems like the underscore `_` is tripping up the search. Unfortunately this isn't something we're likely to be able to fix for the time being.
