### ISSUE TITLE
Blocking Users Stopped Working

### ISSUE THREAD

**Issue by Ensrick** [Nexus-Mods/web-issues#1565]
## Your username/username(s) affected
StormyG7

## Bug/error being reported:
Blocking a user no longer works.

## Steps to reproduce:
Optimally an ordered list with the steps needed to reproduce the bug

1. Go to the user's home page
2. Block the User
3. A message pops up saying the user was successfully blocked, but the user will not be blocked.

OR

1. Go to site preferences and content blocking
2. Type the username you want to block
3. The username will be added to the list, but upon refreshing the webpage, the user will not be blocked
-->

## Expected result:
I was expecting the user to be blocked. 

## Actual result:
The user is not blocked.

## More Info:
I've blocked thousands of authors. In order to modify Skyrim SE and sort through all the content, using tags has proven ineffective filters, so instead of blocking authors, I seem to have uncovered a bug after blocking thousands of users. I tested unblocking a few mod authors to see if I could then block others, but it still is broken.
![Screenshot 2022-08-05 220434](https://user-images.githubusercontent.com/65567354/183231023-d7db5e19-2a21-44ef-9f6b-b0563093e7d4.png)
![Screenshot 2022-08-05 220511](https://user-images.githubusercontent.com/65567354/183231030-cb451cc4-07e3-464c-b525-b65e7d54f8e1.png)

**Comment by Pickysaurus** [comment]
There's a limit to how many authors and tags you can block before it stops working. Try removing some and it will work again.

**Comment by Ensrick** [comment]
That's just the point though. I need to be able to block more in order to effectively sort through mods. I shouldn't have to unblock someone I don't want to unblock in order to block someone else.

**Comment by Pickysaurus** [comment]
I'm afraid it's not something we'll be able to fix in the short term. Large block lists put a lot of strain on the search system to generate your results. 

I'd imagine some of the authors you've blocked haven't posted anything in a long time and can be unblocked without you seeing a notable difference.

**Comment by Ensrick** [comment]
A large strain? Really?

54000 mods for Skyrim SE puts a large strain on me. I've only managed to get it down to 10700 by blocking creators. I guess I could try making a simple browser extension to block authors. There's got to be a way to do it that doesn't put so much strain on the system.
