### ISSUE TITLE
Please add mod category "Character Presets" that is separate from "Body, Face and Hair"

### ISSUE THREAD

**Issue by mdavis199** [Nexus-Mods/web-issues#1567]
You have one category "Body, Face, and Hair" that covers textures, meshes, and presets.  But, `presets` should be its own category.  While I love to see different skins, tattoos, beards and wigs I can use for NPCs and my character, I HATE seeing someone else's own character configuration.  Someone looking for new textures or meshes is NOT looking for a character `preset`. Someone looking for a predefined character appearance is NOT looking for general textures and meshes.

**Describe the solution you'd like**
A separate category for `Character Presets`.    I would also like it if, initially, any "Body, Face, and Hair" mod that had the word `preset` in its title was automatically moved to the `Preset` category.

**Describe alternatives you've considered**
Blocking mods that are presets, but there is no way to do this.

**Also consider**
This category is getting overrun with users simply storing their characters preset on nexus, not for the general user's benefit, but so they can more easily restore their personal game.

**Comment by Pickysaurus** [comment]
Character presets is a tag, you can block this tag.
