### ISSUE TITLE
New Vortex Update Unflags all ESL-flagged ESPs

### ISSUE THREAD

**Issue by enragedbard** [Nexus-Mods/web-issues#1568]
## Your username/username(s) affected

![Light flags](https://user-images.githubusercontent.com/109352488/183715599-8a847af9-32a3-49a2-aaf5-e355a6b53285.jpg)

## Bug/error being reported:

When I updated vortex, it automatically unflagged all my ESL-flagged ESPs.  Just wondered if there was an error in something, and should be aware of it.

## Steps to reproduce:
 To download an update and have my mods the same way they were left.

## Actual result:
 I now have to manually flag 700+ mods again.  EDIT:  It actually seems like the flags are still set, noted in xEdit.  Vortex is just confused about that fact.  Game still starts.

**Comment by Pickysaurus** [comment]
This tracker is for issued with the website, please report this via "Send Feedback" in the app or on the Vortex tracker. Thanks.
