### ISSUE TITLE
Updates/Notifications tab always has at least 1 notice flag

### ISSUE THREAD

**Issue by redbaron148** [Nexus-Mods/web-issues#157]
The updates tab always has a notification of 1 unread update even if they're all read.  This persists until I click "clear all notifications."  This may be considered a new feature but this is not how the old website worked.

![capture](https://user-images.githubusercontent.com/250288/31590926-0d93736e-b1ce-11e7-83b8-e7e662ae322d.PNG)

**Comment by iamtiz** [comment]
Do the read notifications diappear after you click "clear all notifications", or are they persisting too?
And could you check, if possible, whether there's any error returning from the "network activity console" when you click the "clear all notifications" link?

**Comment by redbaron148** [comment]
The read notifications do disappear after clicking "clear all notifications."  I'm not sure how to go about checking the network activity console so I don't know what it said after clicking "clear all notifications."

**Comment by iamtiz** [comment]
And is the counter still indicating 1 unread update?

**Comment by Skinripper** [comment]
For me the Update dropdown list will disappear randomly and unexpectedly , without taking any action to do so, and I have to start all over again.  I have time to read maybe 10 updates, then the list will just disappear.  Is there a way to display more that 5 items when clicking More at the bottom of the list.

**Comment by redbaron148** [comment]
No, the counter was cleared after clicking "clear all notifications" but the issue I was meaning to point out with this bug report is the fact that already read updates (greyed out, but still visible in the updates list) were still causing an unread update count of 1 to appear.  The "Clear all notifications" link has always properly cleared the updates/notifications tab which does also clear the number of updates visible on the tab itself.
