### ISSUE TITLE
Unable to Log In to Nexus Mods Collections in Firefox 

### ISSUE THREAD

**Issue by Ryebread095** [Nexus-Mods/web-issues#1570]
## Your username/username(s) affected
Ryebread036

## Bug/error being reported:
unable to log in to collections on Firefox web browser.  this does work in Google Chrome

## Steps to reproduce:
1. go to https://next.nexusmods.com/ using Firefox version 103.0.2 (latest at time of writing)
2. click Login in top right corner, it takes us to https://users.nexusmods.com/auth/sign_in
3. enter login credentials and click Log In

## Expected result:
i should be able to log in to the website

## Actual result:
a black screen shows with a message saying "Try signing in with a different account." and a button below that seems to only refresh the page that reads "Sign in with Nexus Mods".  URL is https://next.nexusmods.com/api/auth/signin?error=OAuthCallback

## Findings:
from the console log (loginError.png)
Cookie “__cf_bm” has been rejected because it is already expired.

![loginError](https://user-images.githubusercontent.com/74842276/184517976-82471faf-c36f-47a8-ae98-7c674f13f4ba.png)

**Comment by Pickysaurus** [comment]
Hi there,

Please see our troubleshooting guide here: https://help.nexusmods.com/article/113-troubleshooting-website-issues

You may want to try clearing your cookies/cache too.
