### ISSUE TITLE
Spoiler Tag Preview not working on "posts" section

### ISSUE THREAD

**Issue by suamor** [Nexus-Mods/web-issues#1573]
## Your username/username(s) affected
ssuamier
Tested on chrome browser.

## Bug/error being reported:
[spoiler]Hidden Text[/spoiler] preview is not working.
Instead it is shown as normal text.

## Steps to reproduce:
1. Go to mod page of a mod with "posts section" like https://www.nexusmods.com/skyrimspecialedition/mods/38326?tab=posts
2. Create new comment or answer to existing one
3. Add comment text
4. Add spoiler text (or image, same result)

## Expected result:
- Text is hidden and can be shown when pressing on spoiler button
- After posting when pressing "Show" text is not change to "Hide"

## Actual result:
- [spoiler] ... is shown. It looks like Tag "spoiler" does not work but it actually works after posting.
- After posting when having pressed "Show" it remains like that (hiding works, only text is incorrect).

**Comment by Pickysaurus** [comment]
This is intended behaviour. If the spoiler collapsed the text in the editor that would make it harder to edit. We are looking at improving the editor in a future update.
