### ISSUE TITLE
Mod page doesn't reflect that I downloaded a mod

### ISSUE THREAD

**Issue by AIeskander** [Nexus-Mods/web-issues#1576]
## Your username/username(s) affected
LuluAshfield

## Bug/error being reported:
Mod page doesn't show I downloaded the file. Tested on 2 different mod/mod pages on Fallout 4 Nexus

## Steps to reproduce:
1. Download any mod file manually from any mod page.
2. After download, refresh page

## Expected result:
1. After download, the description tab should read "You last downloaded a file from this mod on dd mmm yyyy"
2. After download, the download tab should show the downloaded file should have a download icon next to it's name

## Actual result:
1. After download, the description tab still reads "You haven't downloaded this mod yet"
2. After download, the download tab still shows the downloaded file without a download icon next to it's name

**Comment by Pickysaurus** [comment]
This is a temporary issue while we migrate some data in the background. Please wait a few hours for the process to finish and it should start working as expect again.

**Comment by AIeskander** [comment]
Understood. Thank you for the reply.
