### ISSUE TITLE
 .7z file, upon download and extraction, has no folders, instead adding the folder path to every file name 

### ISSUE THREAD

**Issue by twicecurved** [Nexus-Mods/web-issues#1577]
## Your username/username(s) affected
Joelmolely

## Bug/error being reported:
Skyrim, requiem mod, .7z file, upon download and extraction, has no folders, instead adding the folder path to every file name. This is an likely an issue with the download, as the preview file contents shows the folders, and the files without the path added to the file name

## Steps to reproduce:
Tried on multiple files, and through the vortex manager and manually, reqiuem 4.02, requiem 4.01, requiem 3.30, all had same issue

## Expected result:
Mod folder would extract with files inside folders

## Actual result:
Folder extracted with no folders included, but with every file named with the folder path, with an  to replace the dash. e.g.
coredocumentationCredits.pdf
coremeshes74_wstavesstaff_wooden.nif

Addition- Solved (for me) by uploading the file to a 7z. to zip converter online, and downloading it as a .zip file from there

**Comment by Pickysaurus** [comment]
Sounds like you had a bad download, but as the ticket doesn't include any relevant links I can't try and reproduce the issue.
