### ISSUE TITLE
Vortex errror when downloading with WI-FI " Network connect was not permitted, please check your firewall settings "

### ISSUE THREAD

**Issue by rubyr47** [Nexus-Mods/web-issues#1578]
Your username/username(s) affected
RubyR47

**Describe the bug**
This may be a temporary issue, please try again later Network connect was not permitted, please check your firewall settings

**To Reproduce**
1.  click mod manager download https://www.nexusmods.com/skyrimspecialedition/mods/18560 tab=files&file_id=59909&nmm=1 ( an example file which has " 100mb++ " file, but i can download with wifi if it's below " 30mb " )
2. wait for 5 second 
3. it prompt to send data to vortex
4. failed showing the error shown in " describe the bug "
5. This happen when i use " WI-FI ", and donwload works when i use "MOBILE DATA/ PACKET DATA/ INTERNET QUOTA ( and yeah i cant use mobile data/packet data/ internet quota forever, i'm not rich and most of my mobile data/packet/internet quota are for my job )
6. i already allowed firewall for vortex and even the browser
7. i also exluded vortex or browser i use in microsoft defender

**Expected behavior**
Download normally when using WI-FI

**Screenshots**
![image](https://user-images.githubusercontent.com/77791473/187330618-bad65c9d-b193-4b00-b806-b67ab5340b6a.png)
![Uploading image.png…]()

**Platform (please complete the following information):**
 - OS: Windows 11
 - Processor: Intel Core i7-9750 CPU @2.60GHZ (12 CPU ) ` 2.6GHZ
 - GPU : NVIDIA GEFORCE 1650
 - Vortex 1.6.8

**Additional context**
please help fix this or "maybe" this is app problem

edit: i thought, i was in the wrong place to ask but no. i'll reopen again

**Comment by Pickysaurus** [comment]
This tracker is for issue with the website. You can send Vortex feedback via the app although this doesn't appear to be a Vortex problem
