### ISSUE TITLE
No option to manage unmanaged games in vortex.

### ISSUE THREAD

**Issue by PuddingMancer** [Nexus-Mods/web-issues#1579]
## Your username/username(s) affected
InfinitePudding

## Bug/error being reported:
When I search for a game in Vortex the result doesn't have a manage game option. No game I search for allows me to manage the game. I don't know when this bug started but I can't manage any new games. I can still use already managed games though. If I unmange a game, I can't re-manage it.

**Comment by Pickysaurus** [comment]
This tracker is for issue with the website. When making the ticket you should have been given an option to raise a Vortex bug in the appropriate place.

In the top right swap back to grid view as a workaround

**Comment by davsheep** [comment]
Still occuring for me in 1.6.8, despite being "fixed".

**Comment by Pickysaurus** [comment]
Once again, this tracker is not for Vortex. Swapping back to Grid View will fix it. 

If that doesn't work, feel free to create a post detailing your problem on the forum https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/
