### ISSUE TITLE
CERT_HAS_EXPIRED : certificats has expired error on both website and Vortex

### ISSUE THREAD

**Issue by Thisisjuke** [Nexus-Mods/web-issues#1580]
## Your username/username(s) affected
GOOZAB

## Bug/error being reported:
Certificats has expired on many mods like : https://www.nexusmods.com/skyrimspecialedition/mods/3479?tab=files
![image](https://user-images.githubusercontent.com/23522065/188270940-4478abb7-f31f-4d9c-b31f-9d602d3ddb23.png)

## Steps to reproduce:

1. Download a Mod collection that contains Immersive armors like vanilla+ : https://next.nexusmods.com/skyrimspecialedition/collections/w7fk1b?tab=about
2. Wait for the mod collection to be downloaded
3. Click sur install

## Expected result:
Mods are being installed properly without certificat issues

## Actual result:
We need to download it manually.

## Additional informations:
[Link to certificat issue](about:certificate?cert=MIIGQDCCBSigAwIBAgIMRIKxiKlEUE6Vknv4MA0GCSqGSIb3DQEBCwUAMEwxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSIwIAYDVQQDExlBbHBoYVNTTCBDQSAtIFNIQTI1NiAtIEcyMB4XDTIwMDgwMTExMzcyN1oXDTIyMDkwMzA3NDMxM1owGjEYMBYGA1UEAwwPKi5uZXh1cy1jZG4uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxFGyla1edRb7nCIeotLwat24tWgED2KTgNwGeF2Z%2BeSV9z0UslIn%2F9MKMf6%2B%2Fo9Jt7i%2BEz89zkYP%2FAZLxC94SrmDXeW2JGA98%2BFAdFiVufK6yf0TxrqWARkMfUkzEKrpEz49SMNX4thCjsXGXt0zwFtwWVQM8E1GEVA91xq7OAFI8YyEMoetXYJUNu7jOejlClx50pSeOlmtsAd8nm3pPGn66Z3jveYC3FGpZr%2B%2FRa0%2FKChW5Vve56jQniuBubtkj2P2LwZRcWWs9MelQ1H4MUoDE3W8ICVXj%2B1CGKvYgQ%2BEgovD9iexRaKUoUSjl%2FddkzhknAALbiP10UBZKKgbAQIDAQABo4IDUjCCA04wDgYDVR0PAQH%2FBAQDAgWgMIGJBggrBgEFBQcBAQR9MHswQgYIKwYBBQUHMAKGNmh0dHA6Ly9zZWN1cmUyLmFscGhhc3NsLmNvbS9jYWNlcnQvZ3NhbHBoYXNoYTJnMnIxLmNydDA1BggrBgEFBQcwAYYpaHR0cDovL29jc3AyLmdsb2JhbHNpZ24uY29tL2dzYWxwaGFzaGEyZzIwVwYDVR0gBFAwTjBCBgorBgEEAaAyAQoKMDQwMgYIKwYBBQUHAgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAgGBmeBDAECATAJBgNVHRMEAjAAMD4GA1UdHwQ3MDUwM6AxoC%2BGLWh0dHA6Ly9jcmwyLmFscGhhc3NsLmNvbS9ncy9nc2FscGhhc2hhMmcyLmNybDApBgNVHREEIjAggg8qLm5leHVzLWNkbi5jb22CDW5leHVzLWNkbi5jb20wHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB8GA1UdIwQYMBaAFPXN1TwIUPlqTzq3l9pWg%2BZp0mj3MB0GA1UdDgQWBBRKlCmF%2FRUV0HhW3ZNHMrC2iJWmgzCCAYAGCisGAQQB1nkCBAIEggFwBIIBbAFqAHcAb1N2rDHwMRnYmQCkURX%2FdxUcEdkCwQApBo2yCJo32RMAAAFzqdAKxQAABAMASDBGAiEA9PZErw5D2n1PzbO2CIcXukK9UcfhAn36gkQm6Pl0aMoCIQCLtAWSiMlSqt78G%2FRHJGvOtTBd%2FRCJOtdaUPxFcjtGfgB2ACl5vvCeOTkh8FZzn2Old%2BW%2BV32cYAr4%2BU1dJlwlXceEAAABc6nQCm8AAAQDAEcwRQIgPhPa8duVI4ihG3X%2BOye3dKCdT2C41S8f6ooEGSAsumgCIQCRa8MXVJ1Bh7OY6jVVzA180IPpNk%2Bsd84Y2xT1eu1TOQB3AFWB1MIWkDYBSuoLm1c8U%2FDA5Dh4cCUIFy%2Bjqh0HE9MMAAABc6nQCo4AAAQDAEgwRgIhANdG2D9PxfSeWb0iUW15ab5qTnZzQFn%2B5rbbbdngHeDlAiEA%2B60s7cIc%2BGdW4tQmlhDG3c7kESVfFp02Yf5sxgwtUjcwDQYJKoZIhvcNAQELBQADggEBAMwe5iVRiM5vnnkOik8%2FuCWpjMzJSs27VvO7COwuTrnib96C%2F1faC5B69Tcq0%2FbUdEy1FSW2MSloJDVfXEZACftFCZYsjYE72raR3%2FWr2sUQSZdLiKPc85eFXJs7syBrRfI35g5jDfvP%2FFOdPd3EG%2F2musF4AVFn%2BbAsH%2F3SXrA20kFsTYgpbtwg45eKc3Eqlj4Bk4LtqW2fssj8hYdbJ%2B9GTVvS7yjIVM0fCOzodKarKZH6OEi9rg3trPg%2BLwjOQuKmQoYkg3KkRxHJPTtfx3r87QcvRRs97xpuAHHicZEcJG88D3cc7EGAyRtCWOWZEgEeKQIjoS4kkliZA1Uvp9c%3D&cert=MIIETTCCAzWgAwIBAgILBAAAAAABRE7wNjEwDQYJKoZIhvcNAQELBQAwVzELMAkGA1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jvb3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw0xNDAyMjAxMDAwMDBaFw0yNDAyMjAxMDAwMDBaMEwxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMSIwIAYDVQQDExlBbHBoYVNTTCBDQSAtIFNIQTI1NiAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2gHs5OxzYPt%2Bj2q3xhfjkmQy1KwA2aIPue3ua4qGypJn2XTXXUcCPI9A1p5tFM3D2ik5pw8FCmiiZhoexLKLdljlq10dj0CzOYvvHoN9ItDjqQAu7FPPYhmFRChMwCfLew7sEGQAEKQFzKByvkFsMVtI5LHsuSPrVU3QfWJKpbSlpFmFxSWRpv6mCZ8GEG2PgQxkQF5zAJrgLmWYVBAAcJjI4e00X9icxw3A1iNZRfz%2BVXqG7pRgIvGu0eZVRvaZxRsIdF%2BssGSEj4k4HKGnkCFPAm694GFn1PhChw8K98kEbSqpL%2B9Cpd%2Fdo1PbmB6B%2BZpye1reTz5%2Folig4hetZwIDAQABo4IBIzCCAR8wDgYDVR0PAQH%2FBAQDAgEGMBIGA1UdEwEB%2FwQIMAYBAf8CAQAwHQYDVR0OBBYEFPXN1TwIUPlqTzq3l9pWg%2BZp0mj3MEUGA1UdIAQ%2BMDwwOgYEVR0gADAyMDAGCCsGAQUFBwIBFiRodHRwczovL3d3dy5hbHBoYXNzbC5jb20vcmVwb3NpdG9yeS8wMwYDVR0fBCwwKjAooCagJIYiaHR0cDovL2NybC5nbG9iYWxzaWduLm5ldC9yb290LmNybDA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAGGIWh0dHA6Ly9vY3NwLmdsb2JhbHNpZ24uY29tL3Jvb3RyMTAfBgNVHSMEGDAWgBRge2YaRQ2XyolQL30EzTSo%2F%2Fz9SzANBgkqhkiG9w0BAQsFAAOCAQEAYEBoFkfnFo3bXKFWKsv0XJuwHqJL9csCP%2FgLofKnQtS3TOvjZoDzJUN4LhsXVgdSGMvRqOzm%2B3M%2BpGKMgLTSxRJzo9P6Aji%2BYz2EuJnB8br3n8NA0VgYU8Fi3a8YQn80TsVD1XGwMADH45CuP1eGl87qDBKOInDjZqdUfy4oy9RU0LMeYmcI%2BSfhy%2BNmuCQbiWqJRGXy2UzSWByMTsCVodTvZy84IOgu%2F5ZR8LrYPZJwR2UcnnNytGAMXOLRc3bgr07i5TelRS%2BKIz6HxzDmMTh89N1SyvNTBCVXVmaU6Avu5gMUTu79bZRknl7OedSyps9AsUSoPocZXun4IRZZUw%3D%3D)

![image](https://user-images.githubusercontent.com/23522065/188271243-2c9ef316-fb85-4948-b8ea-e4247803c036.png)

**Comment by mrmason** [comment]
This should be sorted now. Thanks for the report.
