### ISSUE TITLE
Deleted mods unintended(?) showing; sequential deletion

### ISSUE THREAD

**Issue by Plantelo** [Nexus-Mods/web-issues#1581]
## Your username/username(s) affected

Plantelo
## Bug/error being reported:

Deleted mods still show up in the "My Files" tab for the owner; they can be deleted again. Every time this happens, " - DELETED" gets  appended to its name.
## Steps to reproduce:

1. Go to My Nexus Account -\> My Files
2. Delete a mod
3. Reload the page
## Expected result:

The deleted mod is not present, or is present, but has a different card, and cannot be modified.
## Actual result:

The mod is displayed like usual, with all the buttons (except the delete button) leading to a 404-style page; the delete button works as usual, and allows for sequential deletion of the mod an arbitrary number of times.

![Screenshot 2022-09-03 183917](https://user-images.githubusercontent.com/63164279/188280165-a94034fc-da0b-4a99-960b-36553c7d5a08.png)

**Comment by SleepyEngi** [comment]
Getting this same issue.

**Comment by Pickysaurus** [comment]
This is now fixed.
