### ISSUE TITLE
Please help me i think i tried everything

### ISSUE THREAD

**Issue by GivWar** [Nexus-Mods/web-issues#1582]
## Bug/error being reported:

i cant launch my game using vortex because he is located into Xbox games, i tried to change location of the game and also the security permissions, every security rules accept to be changed, except for SkyrimSE.exe, the game launcher...
i can launch the game without vortex, and i already tried to launch vortex as administrator

so i actually dont know what to do...

here a screen of the error when i try to select the exe file from vortex
![aedae](https://user-images.githubusercontent.com/112890076/188482347-64dd1ded-3296-4c6b-b312-4482d91ff711.PNG)

**Comment by Pickysaurus** [comment]
I'm afraid this tracker is not for Vortex issues. (As explained on the screen that shows before you create the ticket).

You can create a detailed post on our support forum if this is a Vortex issue: https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/

If you're having issues with a specific mod, try posting on the mod page.
