### ISSUE TITLE
Download speeds over 1GB throttled to 544 kb/s - Premium user

### ISSUE THREAD

**Issue by Monoexo** [Nexus-Mods/web-issues#1583]
## Your username/username(s) affected
 
Darkness732

## Bug/error being reported:

I downloaded a collection for skyrim and the mods over 1GB are throttled down to 544kb/s as oppose to anything less than 1GB which downloads with 6MB/s. I flushed my DNS, restarted router, restarted PC, cleared cache, nothing seems to work.

## Steps to reproduce:

To download all files with normal speed.

## Actual result:

Speed being throttled for larger files.

**Comment by Pickysaurus** [comment]
Please see our troubleshooting guide: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
