### ISSUE TITLE
Notifications for new replies to threads I did not start but have replied to

### ISSUE THREAD

**Issue by xaliber** [Nexus-Mods/web-issues#1584]
## Your username/username(s) affected
Xaliber13

## Bug/error being reported:
Sometimes people would reply to my comments but I didn't get any notification from the notification panel. I have everything turned on except for "Show game specific notifications" and "Show notifications for new games"

## Steps to reproduce:
Started having this issue after I got a notification on my comment on this article: https://www.nexusmods.com/skyrimspecialedition/articles/3836 which when clicked led me not to that link, but to the mod page. So maybe:

1. Got a notification on an article
2. Clicked the notification and got redirected to the mod page
3. Didn't get other notification for other replies

## Expected result:
Gets notified when there's a new reply

## Actual result:
Sometimes I get notification, sometimes I don't

**Comment by Pickysaurus** [comment]
You are only notified if you started the comment thread. If you reply to someone else's comment in a nested chain you will not be notified of further replies.

**Comment by xaliber** [comment]
Oh that explains, thank you. This is more of feature request, but is there any chance in adding another setting for notification in someone else's comment chain?

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/255/notifications-for-comment-chains-i-did-not-start
