### ISSUE TITLE
text MelonLoader becomes Meldata-no-onloader

### ISSUE THREAD

**Issue by MeitziQ** [Nexus-Mods/web-issues#1588]
## Bug/error being reported:
When you put text "MelonLoader" on your mod page, it will shown as "Meldata-no-onloader" to the user. 

### Example:
https://www.nexusmods.com/carmechanicsimulator2021/mods/105

**Comment by MeitziQ** [comment]
It seems does not happend any more. Maybe i was just crazy, i dont know

**Comment by mrmason** [comment]
Don't worry - you're not crazy - thanks for reporting it - we were working on some improvements to our parser, and this was very helpful. It should all be working now, and we're checking for MelonLoader when we make changes now!
