### ISSUE TITLE
Download History Vanished

### ISSUE THREAD

**Issue by mmwookie** [Nexus-Mods/web-issues#1589]
## Your username/username(s) affected

mmwookie

## Bug/error being reported:

While venturing, I noticed that all of the update status indicators above the mods I had downloaded disappeared. After clearing cache, switching browser, signing out and back in, nothing appears on my download history.

**Comment by Lordkevin89** [comment]
I, Accountname Lordkevin89 have the same issue.

Looks like a Server Data storage issue.

**Comment by themagickoala** [comment]
Please could you try again, there was a temporary issue which should now be resolved.

**Comment by Potato95** [comment]
Still gone for me.

**Comment by Beba007** [comment]
Hi, I have this bug as well.
Account name Beba.

**Comment by Pickysaurus** [comment]
This should be resolved now.

**Comment by Lordkevin89** [comment]
Hi, It is fixed

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: zondag 25 september 2022 18:03
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [Nexus-Mods/web-issues] Download History Vanished (Issue #1589)


Please could you try again, there was a temporary issue which should now be resolved.
