### ISSUE TITLE
Download requirements not shown by default

### ISSUE THREAD

**Issue by Ghetto05** [Nexus-Mods/web-issues#1592]
## Your username/username(s) affected
Everyone who uploads a file with requirements

## Bug/error being reported:
The setting "Inform downloaders of this mod's requirements before they attempt to download this file" on files is off by default, while it makes barely any sense to have this setting to begin with. The setting isn't shown during the upload process either, it has to be done after uploading has finished.

## Steps to reproduce:
-upload a file
-add requirements
-forget to return to the file to change the setting

## Expected result:
The setting is on by default, so everyone downloads the required file(s) as well

## Actual result:
The setting stays off, resulting in 99% of the bug reports being caused by the missing required file(s)

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/244/show-download-requirements-by-default
