### ISSUE TITLE
Reupload of file with same version number but different contents still references the old version

### ISSUE THREAD

**Issue by SlavicPotato** [Nexus-Mods/web-issues#1593]
## Your username/username(s) affected
slavicpotato1

## Bug/error being reported:
Reupload of file with same version number but different contents still references the old version

## Steps to reproduce:
1. Uploadefirst version
2. Upload update to file without updating version within a short period of time (less than 15 minutes)

## Expected result:
Download should point to the most recent file uploaded.

## Actual result:
Downloaded files were not the ones most recently submitted, but the previous versions.

## Additional info:

Scripts/Source/IED.psc and Scripts/IED.pex were updated in the new file(s).

Here are the most recent files which were submitted: https://github.com/SlavicPotato/ied-dev/releases/tag/1.6.0
Mod page: https://www.nexusmods.com/skyrimspecialedition/mods/62001?tab=files

Archives uploaded to github were pulled directly from the prep folder where they were initially zipped, old ones were manually deleted before creating new ones so I'm fairly sure I didn't mess something up there.

**Comment by Pickysaurus** [comment]
This is an intended feature. The uploads are cached by file name in case the upload is interrupted. Simply rename the file you're uploading to something different.
