### ISSUE TITLE
rate limited when trying to Log In

### ISSUE THREAD

**Issue by Mr-Hyde99** [Nexus-Mods/web-issues#1595]
URL:https://users.nexusmods.com/auth/sign_in
Username on Nexus:3rr0r99
Bug/error: when clicking on Log In on the Website I am always getting rate limited 
Steps to reproduce: -click on Log In
                               -reactivate Account via the Link in Email
                               -try to Logh In again
Expected result: Log In mask pops up and I can Log In
Actual result: "Error 1015 you are being rate limited"
Note:Bug appears for 3 days in a row now.

**Comment by Pickysaurus** [comment]
This should clear automatically if you wait a few minutes. If it doesn't, there's a problem in your browser config (or you're using a VPN or something that is caused CloudFlare to think you're already limited).
