### ISSUE TITLE
Comments on mod page for Taverns Redone have lost their comment styling

### ISSUE THREAD

**Issue by XJDHDR** [Nexus-Mods/web-issues#1596]
## Your username/username(s) affected
N/a (My username is XJDHDR, but same bug happens if not logged in)

## Bug/error being reported:
I've noticed that the comment section for one specific mod has become broken, for some reason. Every comment appears to be there, but all except the first is not receiving the styling that a comment is supposed to have. I have not seen this happen for any other mod's comment section so far.

I saw this behaviour from Firefox, Google Chrome and Opera. All of which were with a fresh profile for each browser (therefore, it's not an extension). 

Looking at the HTML inspector for the problem comment section, it seems that something happened which made the website's scripting fail to place the list items containing the individual comments inside the correct ordered list, other than the first. My guess is that there is something in SonOfKrampus' comment that is breaking a parser somewhere.

## Steps to reproduce:
Open the comment section for the mod page of the Daggerfall Unity mod, [Taverns Redone](https://www.nexusmods.com/daggerfallunity/mods/43?tab=posts) and look at the comments that are posted.

## Expected result:
This screenshot of the comment section for one of my mods is what I expected to see. Namely, the comments are correctly styled:
![Expected result](https://user-images.githubusercontent.com/7355441/194785719-7af6467a-9504-4f9d-9e5a-f1ecdc78a2ee.png)

This is a screenshot from the HTML inspector for the working comment section:
![Working comment section HTML](https://user-images.githubusercontent.com/7355441/194785927-6dee2380-98f6-4e3a-b4a5-c9b165f9ba24.png)

## Actual result:
This screenshot shows the problem I see with the Taverns Redone comment section. The first comment looks fine, but the rest don't have the correct styling applied to them:
![Problem comment section](https://user-images.githubusercontent.com/7355441/194785967-7cc61828-5584-4df4-b2f1-b3c49f6aab84.png)

This is a screenshot from the HTML inspector for the problematic comment section:
![Problem comment section HTML](https://user-images.githubusercontent.com/7355441/194785990-839cb0f7-0532-4c8a-a822-add54fa59c48.png)

**Comment by Pickysaurus** [comment]
This was caused by a styling error in the top post I have correct for you. Thanks for the report.
