### ISSUE TITLE
Game not found for manage

### ISSUE THREAD

**Issue by ZackCelestial** [Nexus-Mods/web-issues#1597]
## Your username/username(s) affected
Shawn3

## Bug/error being reported:
I want to manage "Total War : Three Kingdoms but it always Game not found - This directory doesn't appear to contain the game. Expected to find these files: launcher\launcer.exe, Three_Kingdoms.exe" . I have the game but not from steam but before there no problem with other game that not from steam. Maybe it because the version game when i got to extension I saw version 0.0.1

## Expected result:
Hope it got fix

## Actual result:
same answer like earlier

**Comment by Pickysaurus** [comment]
Please report issues with Vortex either in this repo or via the feedback option in the app.
https://github.com/Nexus-Mods/Vortex/issues/new/choose
