### ISSUE TITLE
Collection page not loading after becoming premium member

### ISSUE THREAD

**Issue by grumplin** [Nexus-Mods/web-issues#1598]
## Your username/username(s) affected
pumpin21

## Bug/error being reported:
Oops!
Something went wrong
You can try refreshing the page, or instead discover some new collections.

## Steps to reproduce:
just open any games collection page. e.g.:
https://next.nexusmods.com/cyberpunk2077/collections

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
show collections and add to vortex mod manager
## Actual result:
error as mentioned:
"
Oops!

Something went wrong

You can try refreshing the page, or instead discover some new collections"
![error](https://user-images.githubusercontent.com/60156327/195944762-8173e5bd-03e0-4ce4-9002-4503ec9ae5ad.jpg)

**Comment by marcinmoroz** [comment]
Doesnt matter if it is premium or not premium account if u are registered collections stops working.
I have premium and then created new one i can see collections when i signout but if i log in i cant see it
(users : mmoroz82 - this is premium, encja - this is just registered account ).
Problem is cause of wrong query generated from site to graphql

![image](https://user-images.githubusercontent.com/42942884/195948264-93741c11-fed1-474a-ba9e-56f07388ec3f.png)

i attach payload 

`
{"query":"\n  query Collections(\n    $count: Int\n    $gameDomain: String\n    $offset: Int\n    $userId: Int\n    $viewAdultContent: Boolean = false\n    $sortBy: String\n    $viewListed: Boolean\n    $viewUnlisted: Boolean\n    $viewUnderModeration: Boolean\n    $facets: CollectionsFacet\n  ) {\n    collections(\n      count: $count\n      gameDomain: $gameDomain\n      offset: $offset\n      userId: $userId\n      viewAdultContent: $viewAdultContent\n      sortBy: $sortBy\n      viewListed: $viewListed\n      viewUnlisted: $viewUnlisted\n      viewUnderModeration: $viewUnderModeration\n      facets: $facets\n    ) {\n      nodesCount\n      nodesFacets {\n        facet\n        value\n        count\n      }\n      nodes {\n        id\n        slug\n        name\n        collectionStatus\n        adultContent\n        endorsements\n        totalDownloads\n        listedAt\n        latestPublishedRevisionRating\n        publishedAt\n        updatedAt\n        draftRevisionNumber\n        latestPublishedRevision {\n          modCount\n          fileSize\n        }\n        category {\n          name\n        }\n        game {\n          id\n          domainName\n        }\n        metadata {\n          downloadedAt\n        }\n        permissions {\n          key\n          global\n        }\n        user {\n          memberId\n          avatar\n          name\n        }\n        tileImage {\n          altText\n          thumbnailUrl(size: large)\n        }\n      }\n    }\n  }\n","variables":{"count":40,"offset":0,"facets":{"adultContent":["false","true"],"categoryName":[],"collectionRating":[],"collectionStatus":[],"gameName":[],"gameVersion":[],"tag":[],"hasDraftRevision":[],"hasPublishedRevision":[]},"sortBy":"endorsements_count","viewListed":true,"gameDomain":"monsterhunterrise","viewUnlisted":false,"viewAdultContent":true,"viewUnderModeration":false},"operationName":"Collections"}
`

no response just HTTP 500

**Comment by marcinmoroz** [comment]
looks like problem got fixed

**Comment by lupusdeus1** [comment]
I got the same problem :(

**Comment by PerfectYoda** [comment]
I am getting this issue now after I bought premium as well

**Comment by lupusdeus1** [comment]
For me it works again!

**Comment by Meebsy** [comment]
I'm getting this too, but for me it seems to be only on collections that I have added to Vortex and only ones with a significant number of addons in the collection.
