### ISSUE TITLE
unable to download any mod

### ISSUE THREAD

**Issue by unknownslayerx** [Nexus-Mods/web-issues#1599]
[](url)## unknownslayerx affected

## Steps to reproduce:
1. used "slow download" button to download "blended Roads by Uploader: T4gtr34um3r (Result: Download failed)
2. Pressed "retry" in Vortex (Failed)
3. Logged out of Vortex & Nexusmods.com & logged back in, repeated step 1 (failed)
4. Restarted computer, logged back into Nexusmods.com & Vortex and repeated step 1 (failed)
5. Attempted to download a different mod "Dynamic animations replacer" Uploaded by
 Felisky384 (failed)

- Every failure resulted in status code 500 as indicated by the **Inspect** button inside the Vortex app and further explains "This code is usually the responsibility of the server and will likely be temporary".

(Note: I was unable to attach a .JPEG file to show an image of the issue, otherwise I would)

I'm unsure if this is a server issue multiple users are experiencing as of 10/14/2022 2:00 P.M. (central time) or if it's just me, but I would appreciate any response to this issue at the earliest convenience of whomever is reading this. Thank you!

**Comment by unknownslayerx** [comment]
Update: The current work around I've discovered is to manually download mods from the page and drag/ drop the files into Vortex's manager. As a basic solution for less complex mods, it is working at the moment.

**Comment by mrmason** [comment]
Thanks for reporting this - we had a problem with some infrastructure - this should all be working again now.

**Comment by unknownslayerx** [comment]
Sweet! Thanks for the timely response. It is working properly again on my end.

**Comment by Vegemit3** [comment]
having the same problem here, tried all above suggested solutions, issue is with every mod I try to download from nexus the mods I'm trying to get are for new vegas if that helps.

**Comment by ripface444** [comment]
same issue here but for fallout 4

**Comment by 2Elliot** [comment]
^bump
