### ISSUE TITLE
[Bug] Tile view broken in some areas.

### ISSUE THREAD

**Issue by DuIslingr** [Nexus-Mods/web-issues#160]
On No Man's Sky at least, the Popular (30 Days) tab is broken.

https://rd.nexusmods.com/nomanssky?tab=popular+%2830+days%29

![alt text](https://a.safe.moe/3Jtly.png)

![alt text](https://a.safe.moe/x7pV5.png)

Edit:
Occurs here as well
Click page 2 and you will see it looks similar to above in the images
https://rd.nexusmods.com/nomanssky/mods/?BH=0

**Comment by verenion** [comment]
Assigned PT#152029434

**Comment by verenion** [comment]
Should be resolved now.

**Comment by verenion** [comment]
Reopening issue as this isn't actually fixed.

**Comment by verenion** [comment]
Seems resolved now.
