### ISSUE TITLE
Unable to opt in or out of donation points on any mod

### ISSUE THREAD

**Issue by Sonderbain** [Nexus-Mods/web-issues#1600]
## Nothing happens when I click save:

on this mod and any mod of mine currently. I have tried on multiple internet platforms and devices
https://www.nexusmods.com/skyrimspecialedition/mods/77116
![Capture](https://user-images.githubusercontent.com/115845473/195953360-219e7f9c-8edd-426f-88b4-02c10bce071d.PNG)

**Comment by Pickysaurus** [comment]
This should have been a temporary issue. Let us know if it persists.

**Comment by Sonderbain** [comment]
Seems to have been resolved

**Comment by lfrazer** [comment]
I'm having this exact issue right now..
