### ISSUE TITLE
Hash only the first 1KB or 4KB of a file when providing for the query info api

### ISSUE THREAD

**Issue by v1ld** [Nexus-Mods/web-issues#1601]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by v1ld** [comment]
MO2 currently hashes the whole file before it can resolve the mod that a file belongs to.  If the hash is being used as a key in a lookup - I haven't looked at your API, apologies - please consider allowing the hash to cover a fixed prefix of the file instead of the whole file.  There will be sufficient variation in even 1KB to differentiate.

Just sat through it hashing the entire 6GB+ Skyland AIO file, hence the request. :)

Thanks.

**Comment by Pickysaurus** [comment]
All files are indexed by MD5 of the entire file in our database. This isn't likely to change any time soon I'm afraid.
