### ISSUE TITLE
BTD 6

### ISSUE THREAD

**Issue by Azura7** [Nexus-Mods/web-issues#1602]
## Bug/error being reported: BTD6 your mods are dogshit not allowing me to play coop or even save my progress.

Example: 1. Step 1 - start game 2. Step 2 - play game 3. Step 3 - reload game, it has reverted back to save point it was at from before i downloaded mods

**Comment by Pickysaurus** [comment]
This tracker is for issues with the website, please post a constructive comment on the mod page you need help with.

**Comment by Azura7** [comment]
pLeAse pOsT a CoNsTrUcTiVe cOmMeNt. bitch i did. it tells you that your
shit dont work. the support page for NEXUSMODS led me to the github. its a
collection of mods. youre just too slow to understand what it is im
asking/telling you about dumb fuck
