### ISSUE TITLE
Linked Video On Mod Page Does Not Play

### ISSUE THREAD

**Issue by Teralitha** [Nexus-Mods/web-issues#1603]
User - Teralitha

1. Videos that are linked in the video section of a mod do not play
2. How To - Click to play the linked video from the mod page.
3. Expected the video to start playing.  It used to work, but now for some reason it does not.  The video is still up on youtube and plays from youtube just fine.  So the problem must be with nexus.
4. Just the spinning circle that never goes away when trying to play the video.

Here - https://www.nexusmods.com/morrowind/mods/45846?tab=videos

**Comment by Pickysaurus** [comment]
It plays fine here. Can't replicate the issue.
