### ISSUE TITLE
CAN'T DONLOAD MODS WITH VORTEX

### ISSUE THREAD

**Issue by Vegemit3** [Nexus-Mods/web-issues#1604]
Vegemit3 affected 

**Bug/error being reported: Unable to download mods for new vegas via vortex on a Windows 10 PC as indicated by message "Download failed" (status: 500) on the application.**

ISSUE:   CANNOT DOWNLOAD NEW VEGAS MODS FROM NEXUS WITH SLOW DOWNLOAD BUTTON.
Basically stealing another post I saw about skyrim mods that was closed as it was fixed for him

STEPS TO REPRODUCE: 
Downloading any mod from nexus for FNV In my experience it happened with kNVSE Animation Set - Classic AK-112 - The Adytum Rifle by FalloutBones1 and many others as I was attempting to update a few mods, ive made sure there is no VPN or firewall on and I can download anything else onto my computer.

Every failure resulted in status code 500 as indicated by the Inspect button inside the Vortex app and further explains "This code is usually the responsibility of the server and will likely be temporary".

## Expected result:
download

## Actual result:
fail download
![image_2022-10-21_211628478](https://user-images.githubusercontent.com/116411452/197310017-7d7c15a4-3dab-436c-8737-dbd1c3c943fb.png)

**Comment by jdpartin** [comment]
Same issue since 6pm CT and cannot access the mod collections page once I sign in to my account for Skyrim mods

**Comment by Passione2** [comment]
had the same issue while I was downloading mods for new vegas

**Comment by Pickysaurus** [comment]
Based on the message this was a temporary server error.
