### ISSUE TITLE
Can't download to MO2: "Internal Server Error"

### ISSUE THREAD

**Issue by tjanke42** [Nexus-Mods/web-issues#1605]
## Your username/username(s) affected
tjanke42

## Bug/error being reported:
"internal server error" response from Nexus using MO2

## Steps to reproduce:
Start MO2
MO2 reports "_login successful_"
goto any Fallout 4 mod page on Nexusmods, File tab
click _Mod Manager Download_ button
click _Slow Download_ button

## Expected result:
mod downloads into MO2

## Actual result:
MO2 displays error msg:

Failed to request file info from nexus: Error transferring https://api.nexusmods.com...
<_some letters & numbers_>@expires=1666578<_three numbers_>
\- server replied: Internal Server Error

where:
   _<some letters & numbers>_ is a short alphanumeric string that changes from attempt to attempt,
  <_three numbers_> is a three-digit number that changes from attempt to attempt.

**Comment by buttaholic** [comment]
I have the same issue. Yesterday my download speed was like 200-300kb allthrough my adblock is disabled and my average download speed is 6-7mb. Now i can't download anything.

**Comment by tjanke42** [comment]
Don't know what you guys did (nothing has changed on my end), but the problem appears to be resolved.  Downloads now proceed normally.  Thanks, whatever you did!
