### ISSUE TITLE
Cannot download SSE mod

### ISSUE THREAD

**Issue by sameh-sharaf** [Nexus-Mods/web-issues#1609]
## Your username/username(s) affected

DRSIKO

## Bug/error being reported:

I am trying to download the SSE mod (Unofficial High Definition Audio Project) several times manually and every time after downloading for a while the download fails with the error (resource changed).

The reason I tried to download it manually in the first place is because Wabbajack fails to download it too.

## Steps to reproduce:

1. Go to https://www.nexusmods.com/skyrimspecialedition/mods/18115?tab=files
2. Scroll down to Voices EN - Part 1
3. Click Manual Download
4. Download starts

## Expected result:

The mod should download successfully

## Actual result:

Download fails after reaching 70% with message (resource changed)

**Comment by Pickysaurus** [comment]
Please see our help article regarding downloads here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
