### ISSUE TITLE
Download History Not Showing

### ISSUE THREAD

**Issue by RogueTech67** [Nexus-Mods/web-issues#1610]
## Your username/username(s) affected

ROGUETECH86

## Bug/error being reported:

Starting todaye 10/25/2022, the Download History is not showing.  Also, mods I've downloaded are showing as never being downloaded.  It was working up until yesterday

**Comment by aristotle999** [comment]
I have the same problem.  Please fix.  Worked fine yesterday.

**Comment by shadowking1443** [comment]
Same issue on my end as well

**Comment by chxytrh2** [comment]
Same here

**Comment by QAwesomeman2** [comment]
Same problem, but the history just showed up a few minutes ago.

**Comment by RogueTech67** [comment]
As of 10/25/2022 - 5:40pm EST, the Download History is now showing.

**Comment by mrmason** [comment]
Thanks for reporting this - we've made a few changes to this today which has caused this problem.

We've fixed the problem for now and will monitor it going forward.
