### ISSUE TITLE
Ad blockers break the whole website, even for premium ad-free accounts

### ISSUE THREAD

**Issue by Cooper-Meister** [Nexus-Mods/web-issues#1611]
## Your username/username(s) affected
Twoyoudude

## Bug/error being reported:
Website breaks with adblocker installed, even though I have premium. None of the games show up on the main page, the top tabs are unclickable, and the pages for individual mods are broken and unusable. If im able to get to the download screen, it does not download at all, both manually and with vortex. Only turning ad block off fixes this.

## Steps to reproduce:
1. Using firefox with ublock origin installed, go to nexusmods.com
2. Log in and proceed to home screen
3. Tabs are unclickable and games are missing, so scroll down to the mods section and click any mod
4. Navigate to the downloads screen if possible, and attempt to do a manual download. Nothing downloads

## Expected result:
I was expecting the standard view of the homescreen, with the list of games on the front page. I was expecting to be able to download mods.

## Actual result:
The games section was blank. The tabs at the top of the page are unclickable, and even if i do get into another webpage, the elements are broken and wrongly sized. If I click download, nothing happens
![Screenshot (18)](https://user-images.githubusercontent.com/98918224/198190170-ddee568c-a52a-4344-bc95-ddc6ab4f274f.png)
![Screenshot (17)](https://user-images.githubusercontent.com/98918224/198190176-f638edf6-8e67-4577-bbae-0be3d264881a.png)

**Comment by newyevon2** [comment]
I use brave browser and I can second this issue, except I dont have premium. I would assume its something site admins are doing to stop ad blockers.

**Comment by GeneralMole** [comment]
I have the same bug with opera GX ublock origin

**Comment by Cooper-Meister** [comment]
> We added a fix, if you manually update the `uBO-filters` list the issue should be solved. The list automatically updates every 4 days, so every user will get the fix.
> 
> > I would assume its something site admins are doing to stop ad blockers.
> 
> It was not the fault of site admins.

Thank you! I can confirm its fixed for me, i just had to manually update the filter lists.

**Comment by Eduuux** [comment]
I am having the same problem, I have updated the filters manually and have not been able to fix it.
