### ISSUE TITLE
Sort Tracked Mods by Download Count

### ISSUE THREAD

**Issue by pritster5** [Nexus-Mods/web-issues#1612]
**Problem:** Quickly finidng the most important mods among your Tracked mods is difficult if you have a lot of them.

**Proposed Solution:** Being able to sort the tracked mods by download count (e.g. a tracked mod with the most downloads is first)

I've considered sorting by date and then looking for the oldest mods as they are usually foundational mods but this is not correct nor ideal.

![image](https://user-images.githubusercontent.com/7132319/198423508-c891485e-4909-4c50-965c-7e7b7a6b1070.png)

**Comment by Pickysaurus** [comment]
Hey there, you can make suggestions on our new feedback site: https://feedback.nexusmods.com/
