### ISSUE TITLE
INFINITE Checking if the site connection is secure 

### ISSUE THREAD

**Issue by ayanami8k** [Nexus-Mods/web-issues#1614]
## Your username/username(s) affected
ayanami8k

## Bug/error being reported:
infinite bot check when im trying to login

## Expected result:
login into my account

## Actual result:
infinite Checking if the site connection is secure

**Comment by Pickysaurus** [comment]
Something in your setup is preventing this page from resolving, please see our help page here: https://help.nexusmods.com/article/113-troubleshooting-website-issues
