### ISSUE TITLE
Nexus API  Call Limit Reached - Wabbajack

### ISSUE THREAD

**Issue by throwawaysubmit** [Nexus-Mods/web-issues#1615]
## Your username/username(s) affected
throwawaysubmit

## Bug/error being reported:
when downloading any mod list from Wabbajack, all files appear as 0kb and error returned is "Nexus API call limit reached - Remaining limit 10000".  Have not used Nexus mods since before the last Skyrim patch when I initially downloaded Septimus 3, over a month ago, so I can't possibly have reached a download limit." 

![nexus](https://user-images.githubusercontent.com/116392795/198893213-f9c2ad07-85c7-4e9b-aedf-226808e94b26.jpg)

**Comment by Pickysaurus** [comment]
Please see this help article: https://help.nexusmods.com/article/105-i-have-reached-a-daily-or-hourly-limit-api-requests-have-been-consumed-rate-limit-exceeded-what-does-this-mean

**Comment by throwawaysubmit** [comment]
> Please see this help article: https://help.nexusmods.com/article/105-i-have-reached-a-daily-or-hourly-limit-api-requests-have-been-consumed-rate-limit-exceeded-what-does-this-mean

I appreciate the response, but the issue is that I have not downloaded anything in the last 24 hours.  I've been attempting to redownload the modlist for Septimus 4 since the last patch nerfed it.  I was even out of town for a week and nowhere near my computer or nexus, and the error still perseists - so I'm not sure this applies to me.  Furthermore, the files are showing up as 0kb in Wabbajack but I can open the link in my browser and download the file without issue.

**Comment by Pickysaurus** [comment]
I'm afraid this sounds like a fault with the Wabbajack client. There was an issue with a few versions ago that used up all your API requests quickly, so make sure you've updated. 

Also, if you allow other people to use your PC/your account then they may have used all your requests.
