### ISSUE TITLE
Site Pages UI Elements are Pushed Out of Alignment by Photos Displaying in Multiple Rows

### ISSUE THREAD

**Issue by B4TTL3P1G** [Nexus-Mods/web-issues#1616]
## Your username/username(s) affected
B4TTL3P1G

## Bug/error being reported:
Site Pages UI Elements are Pushed Out of Alignment by Photos Displaying in Multiple Rows
https://imgur.com/a/GiXez1W

## Steps to reproduce:
1. open any mod page or landing page for game selection, the issue should be present upon page load.
2. changing to the videos tab or another tab that includes no pictures appears to fix the issue once the description page is reselected.

### Example:
https://imgur.com/a/GiXez1W

## Expected result:
I should be able to click the track button and other buttons as well, but they do not work until the above steps are followed.

## Actual result:
Buttons are not clickable, and all the images attached to the mod page are displayed on page load.

**Comment by SeaDaddytheRed** [comment]
This is happening to me too since a few day ago.  If I reload the page a bunch it eventually works but 99% of the time this happens on first visiting any page on the nexus.

**Comment by B4TTL3P1G** [comment]
I'm sorry that's happening to you too, but I am a bit glad I'm not the only one.  Are you using the Edge browser by any chance, or at least another Chromium browser?

**Comment by SeaDaddytheRed** [comment]
Yes, I am using Edge.  Is this happening on Chromium browsers?  I only use Brave and Edge which I think are both Chromium.

**Comment by B4TTL3P1G** [comment]
I'm not sure, I was going to download some others to try since I'm not sure yet.  I'll update once I know for sure.

**Comment by SeaDaddytheRed** [comment]
I found this same [issue ](https://github.com/Nexus-Mods/web-issues/issues/501)from 2018.  Was marked solved...

**Comment by B4TTL3P1G** [comment]
Well, that's disappointing.  Good find though.

**Comment by Pickysaurus** [comment]
This is very likely to be caused by browser add-ons or privacy settings. uBlock Origin has been breaking the site recently.

**Comment by SeaDaddytheRed** [comment]
I have that installed, along with Ghostery.  I'll try whitelisting it.

**Comment by B4TTL3P1G** [comment]
Oh wow, thanks for the heads up, I didn't even think to check that. I whitelisted it and it's instantly fixed!
