### ISSUE TITLE
The famous double reply error fetching comments bug

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1617]
## Bug/error being reported:
When you reply to a post on a modpage, sometimes it doesn't get added and you get an error, then you try again and see both the posts added.

## Steps to reproduce:
1. Reply to a post on a modpage 
2. Happens randomly sometimes: "There was an error fetching comments" or something like that error, and you don't see that the post gets added even if you reload the page, however it actually gets added. 
3. Then you try to reply again and your reply appears along with the first one that as you thought wasn't added

Browser: latest Firefox
This happened to me when replying to comments on my mods, though it seems it's a common error that happens to many users, so not sure why it's not fixed yet.

**Comment by Pickysaurus** [comment]
This seems to be a very rare error that happens when the website is under heavy load.

**Comment by starkgate** [comment]
Can confirm, happens to me regularly as well

**Comment by Pickysaurus** [comment]
This is not something we are going to fix in the current comment system, but we are starting to migrate to a brand new comment system that should not have this issue.
