### ISSUE TITLE
Donation Points:  Opt-in or Edit clickable but not functioning

### ISSUE THREAD

**Issue by Petra2241** [Nexus-Mods/web-issues#1618]
Attempting with Firefox or Edge on Windows, or Chrome on Mobile one cannot Opt-in a new mod or edit an existing one on the Donation Points page.

Edit: Safari on Mac with same result.

**Comment by Pickysaurus** [comment]
I cannot replicate this so I am going to assume it was temporary. Please let us know if the issue persists.

General tips: https://help.nexusmods.com/article/113-troubleshooting-website-issues
