### ISSUE TITLE
Updated mods do not always show in search

### ISSUE THREAD

**Issue by LenaWolf** [Nexus-Mods/web-issues#1620]
## Your username/username(s) affected
LenaWolfBravil (Nexus login)

## Bug/error being reported:
Sometimes when I update one of my mods for Oblivion, it does not show in the search when you sort by last updated. I cannot say why or under which circumstances, but if an update is missed like that, it never shows in this search until the next update, which again may or may not show. The mod itself does have the correct date for "last updated", and all the files are there, it seems it's just the search that fails. I don't know if this is specific to Oblivion, I don't have mods for other games. 

For example, look at my mod TWMP Southern Alliance: https://www.nexusmods.com/oblivion/mods/51795. Updated yesterday, yet it doesn't show up in search.

## Steps to reproduce:
Click Explore All Mods under Oblivion or even under all games, sort by Last Updated, scroll, scroll, scroll... My mod does not appear, even though the most recent update was 21 November 2022.

**Comment by Happybara24** [comment]
This problem has been reproduced and will be addressed. Thanks!

**Comment by Pickysaurus** [comment]
This should be fixed now.
