### ISSUE TITLE
Can't login on nexus or vortex from Brazil/São Paulo.

### ISSUE THREAD

**Issue by EwerthonDev** [Nexus-Mods/web-issues#1621]
## Username:
mishijima

## Bug/error being reported:
Can't login on nexus and can't login on vortex, it gives me SSL handshake failed Error code 525, i'm trying to login from Brazil/São Paulo

## Steps to reproduce:
1.  Just click on login button

## Expected result:
A normal login.

## Actual result:
https://i.imgur.com/VLxuu3z.png

**Comment by BigBizkit** [comment]
Sorry to hear that - does this issue persist or were you since able to log in?

**Comment by EwerthonDev** [comment]
Login is working now, i think it's just was a sudden server error.

(idk how to mark this issue as finished or done lmao)
