### ISSUE TITLE
Cyberpunk Collection pages on the website show the collection as "This page doesn't exist" once I have added them to Vortex.

### ISSUE THREAD

**Issue by malaclypse2** [Nexus-Mods/web-issues#1623]
## Your username/username(s) affected
mal2

## Bug/error being reported:
For Cyberpunk mod collections, I cannot return to the Collection page on Nexus once they are installed. For example, https://next.nexusmods.com/cyberpunk2077/collections/otqwui 

## Steps to reproduce:
Go to https://next.nexusmods.com/cyberpunk2077/collections/otqwui and install the collection via Vortex. When I try to return to that page, it thinks for a little while, then eventually get a message saying:

> Sorry!
> This page doesn't exist
> The page you were looking for could have been removed or may not be published yet.

While the page is trying to load information about the collection, I can see and click on the link labeled "Comments", (which leads to https://forums.nexusmods.com/index.php?/topic/11977728-cortunapunk-1-6-1/ in this case). That link all appears to be correct.

I have had this same issue crop up with multiple Collections.

## Expected result:
I expected to be able to return to the Collection page after installing the Collection.

## Actual result:
After installing the Collection, I get an error message instead of the Collection page.

Note - There's an older closed bug report with similar symptoms, here: https://github.com/Nexus-Mods/web-issues/issues/1598. I'm not sure if this is actually a regression, or a new issue with a similar sounding symptom.

**Comment by malaclypse2** [comment]
Sorry, a few further notes. 

Disabling my ad blocker and resetting cookies and other saved data in the browser didn't change the behavior I'm seeing. 

When logged out, I could visit the Collection page, but was presented with an adult content warning, and prompted to log in to see the page. Once logged in, it went back to the loading animation, followed by the "This page doesn't exist" error.

This is happening in Firefox. I haven't tried another browser yet.

**Comment by Pickysaurus** [comment]
This is an issue with Firefox causing the website to crash. We're looking into it. For now, you can use a different browser to access the site.
