### ISSUE TITLE
Files for unpublished mods, no longer appear on the "files" page or "files" tab

### ISSUE THREAD

**Issue by nightmarezone** [Nexus-Mods/web-issues#1624]
## Your username/username(s) affected
Nightmarezone

## Bug/error being reported:
I'm uploading a new mod. Normally, I can view the files after they are uploaded to enter descriptions and move them to different subfolders, and I can view them on the mod page preview. Today, I found I can't view them.  When I enter the mod page preview, the "Files" tab number says there are files, but when I open the tab there is nothing in there. 

Edit: After some time, the files DO appear. But if you want to move them to a sub folder, it's impossible. For example,  I have a patch I accidently uploaded as a main file. So I edit the file, and select "optional". It seems to move to the optional subfolder. But as soon as I save changes, it's back in the Main Files. Even after waiting 3 hours, the changes have not taken any effect.

## Steps to reproduce:
"Upload" as usual. I tried starting over and still no dice. Below I did a "test mod".

![00Problem1](https://user-images.githubusercontent.com/119600095/205061499-637c48f7-572a-423a-a52e-5dbd61c23492.png)
![00Problem3](https://user-images.githubusercontent.com/119600095/205061509-0dabad48-ebd8-4189-b606-7cf6c65ed556.png)

**Comment by Pickysaurus** [comment]
This is a site-wide issue with the cache on the site. The files are being uploaded but it takes several hours for the changes to show up correctly.

**Comment by Pickysaurus** [comment]
This should now be resolved.

**Comment by nightmarezone** [comment]
Thank you for keeping me updated, and for your(and nexus team's) hard work
