### ISSUE TITLE
Enhancement: Auto-submit uploads

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#163]
Is it possible to allow mod uploads to auto-finish once the file is uploaded? A bit like how youtube handles videos?
Waiting for uploads is so 2010 :P

**Comment by iamtiz** [comment]
Do you mean auto-publishing the mod after the file upload has completed?

**Comment by Pickysaurus** [comment]
Yeah for large files I leave the browser idle while it uploads, if it could save and be available after the upload is done that would be convenient but not essential
