### ISSUE TITLE
Download is corrupted when using automated/main download

### ISSUE THREAD

**Issue by zhongjiedong** [Nexus-Mods/web-issues#1630]
## Your username/username(s) affected
[HellLizard](https://www.nexusmods.com/skyrimspecialedition/users/696611)

## Bug/error being reported:
Main download of the following mod is intermittently serving a corrupted 600MB file

https://www.nexusmods.com/skyrimspecialedition/mods/23006

## Steps to reproduce:

Click download on main file, sometimes it will start a download for a 600MB file instead of the full 5.4GB one

## Expected result:
Uncorrupted 5.4GB file downloaded

## Actual result:
600MB corrupted file received.

**Comment by Pickysaurus** [comment]
We've had no further reports of this so it's likely to be an issue with your connection: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
