### ISSUE TITLE
Notifications missing for certain comments (replies) on mods

### ISSUE THREAD

**Issue by suamor** [Nexus-Mods/web-issues#1631]
## Your username/username(s) affected
ssuamier

## Bug/error being reported:
I do not receive Notification for replies on comments on mods in the "post" view. 
There is no option to switch "on" or "off" replies on my comments on mods "post" view.
There are only 2 options available for comments:

- on "my" mods and comments
- on mods I'm tracking.

A third option is missing for replies on "my" comments (independently of tracking).
Comments I created could still receive notifications (I have not checked this).

This option is extremely important. There are way too many mods where I add comments so I loose track if someone replies. I noticed this problem recently when I expected replies to a comment from me and these were given actually more than a week ago.

Summarized:
Replies on comments I added my own reply could still receive notifications
Replies on comments from other users do not receive notifications.

## Steps to reproduce:
Reply on a comment (from a mod "post" view).
Wait for another user to reply on the same comment.
Check notifications
Check reply in post view (this part is hard for replies to older comments several weeks old)

### Example:
https://www.nexusmods.com/skyrimspecialedition/mods/77779?tab=posts&jump_to_comment=119521328

This notification type could still work:
https://www.nexusmods.com/skyrimspecialedition/mods/79044/?tab=posts&jump_to_comment=118286838

## Expected result:
Notifications are shown on replies to my replies from another users comment in the notification tab (bell symbol).
Alternative:
There is a way to track all my comments and replies I give to mods in view 'posts', for example:
https://www.nexusmods.com/mods/newrecently
(I see here unrelated activity for all mods (new and updated), not only the mods I track (updated, new comments, new replies))

## Actual result:
No notification appears. Own comments or replies are not tracked anywhere.

**Comment by Pickysaurus** [comment]
We do not currently send notifications for comment replies unless you are either the mod page owner/team member or you are the person who started the thread. Replying to someone else's "parent" comment means you won't get any notifications.
