### ISSUE TITLE
Cannot post the word "changedEnvironment" because Nexus keeps changing it to "changedEnvirjavascript-event-stripped"

### ISSUE THREAD

**Issue by Glanzer-modder** [Nexus-Mods/web-issues#1632]
## Your username/username(s) affected
Glanzer

## Bug/error being reported:

I cannot post the word "changedEnvironment" because Nexus keeps changing it to "changedEnvirjavascript-event-stripped" in the post. This prevents me from posting a code snippet to fix a problem in a papyrus script.

See my posts with this problem here: https://www.nexusmods.com/skyrimspecialedition/mods/18922/?tab=posts&jump_to_comment=119780893

**Comment by Pickysaurus** [comment]
Duplicate of https://github.com/Nexus-Mods/web-issues/issues/1591
