### ISSUE TITLE
Can't Log In

### ISSUE THREAD

**Issue by Kazurhix** [Nexus-Mods/web-issues#1634]
## Your username/username(s) affected

Kazurhix
## Bug/error being reported:

If I 'right click' and 'open in a new tab' either the 'Log In' or 'Register' links it'll tell me I'm already signed in, but every other page on the nexus acts like I'm logged out, and as a result I can't download any mods.
## Steps to reproduce:

I had been browsing and downloading mods from the Wither 3, Skyrim SE, Fallout 4, & RDR2 parts of the nexus on this PC, with this OS, on this browser, with the same extensions for years, all without having trouble logging in.
## Actual result:

The main site and every mod page I've tried thinks I'm logged out & I can't download any mods because of it.

**Comment by Pickysaurus** [comment]
Please try clearing your cookies or fully logging out and back in. This is likely caused by some bad data saved in your browser.

**Comment by Kazurhix** [comment]
Thank you. Clearing out cookies fixed it & signing back in seems to have fixed it.
