### ISSUE TITLE
Nexus Mods \ Tracking centre \ Comments

### ISSUE THREAD

**Issue by TeraLogin** [Nexus-Mods/web-issues#1637]
Tracking centre  \ Comments keeps tracking my mods which I have deleted myself. When I click on them it says "Not found". What's the point of this?
Tracking centre  \ Comments keeps showing to me the old names of my mods which I have renamed myself.
that is pretty annoying. do something.

**Comment by Pickysaurus** [comment]
This tracker is for bugs. You can make suggestions here: https://feedback.nexusmods.com/?tags=tracking-notifications&view=most-wanted
