### ISSUE TITLE
Refine results filter is not applied and not saved between visits

### ISSUE THREAD

**Issue by comiluv** [Nexus-Mods/web-issues#1639]
## Your username/username(s) affected
unblest

## Bug/error being reported:
1. Refine results is not being applied
2. Refine results checkboxes and Refine with tags is not saved after leaving website

## Steps to reproduce:
1. Visit https://www.nexusmods.com/skyrimspecialedition/mods/
2. Click-expand Refine results
3. Uncheck Translation
4. In the text box under "Tags must not include", input Translation
5. Click APPLY FILTERS
6. See bug 1
7. Close the open tab with nexusmods.com/skyrimspecialedition/mods/
8. Open a new tab and visit https://www.nexusmods.com/skyrimspecialedition/mods/
9. Click-expand Refine results
10. See bug 2

## Expected result:
1. Mods that have translation tag are filtered out and not visible
2. Refine results checkboxes and other input are saved between visits

## Actual result:
1. Filter is not applied
2. Refine results details are not saved

## Screenshot/Notes:
Before changing options in Refine results
<img width="973" alt="화면 캡처 2023-01-16 072532" src="https://user-images.githubusercontent.com/19642705/212570504-2a350cf8-a0ab-4fe4-a30a-2247205e8002.png">

After unchecking Skyrim VR, Skyrim VR Required, and Translations, then putting Translations tag in the field to filter the result by tag, then hitting APPLY FILTERS. Notice translation mods are not filtered.
<img width="955" alt="화면 캡처 2023-01-16 072616" src="https://user-images.githubusercontent.com/19642705/212570570-7a36bbb0-7eca-4b28-af72-4a29b2a1831f.png">

Example mod in the screenshot (https://www.nexusmods.com/skyrimspecialedition/mods/82804) is a translation mod, also has Translation tag set in its mod page but it's not filtered.
<img width="978" alt="화면 캡처 2023-01-16 072654" src="https://user-images.githubusercontent.com/19642705/212570642-4a85fffe-7328-448a-b2d9-3511e3254f99.png">

If I close the tab in the browser and open a new tab and open https://www.nexusmods.com/skyrimspecialedition/mods/, and click on Refine results, options I chose in Refine results are reset to its original state. No screenshot because it's identical to the first screenshot before making any changes.

**Comment by Pickysaurus** [comment]
1. Might be a bug.
2. Is intended functionality. The advanced search let's you refine your current query but doesn't change any global preferences.

**Comment by comiluv** [comment]
Global preference filter is not applied as well, as I have Translation and Skyrim VR Required tags in Currently blocked tags but I still see translation mods and VR mods when I open https://www.nexusmods.com/skyrimspecialedition/
