### ISSUE TITLE
Endorsement reminder for mods I've never downloaded

### ISSUE THREAD

**Issue by smithzac** [Nexus-Mods/web-issues#1640]
## Your username/username(s) affected
ZacDorkus

## Bug/error being reported:
Endorsement reminder shown with a list of mods I've never downloaded.

![Screenshot 2023-01-18 211541](https://user-images.githubusercontent.com/95295702/213297456-24f7ae14-d280-4d06-9dc8-117f247f2f97.png)

Clicking the 'Endorse' button on one of these resulted in:

'Error
You have not downloaded this file so you cannot rate it.'

![Screenshot 2023-01-18 211642](https://user-images.githubusercontent.com/95295702/213297469-e140623e-48ae-4ad1-89b2-bad50de3ccdf.png)

Double checking against my download history:

![Screenshot 2023-01-18 212323](https://user-images.githubusercontent.com/95295702/213298004-a9b42825-6209-420c-ba12-59a900919240.png)

**Biggest concern is that this is a list of mods from another user. Otherwise not really a major issue.** 

## Steps to reproduce:
N/a. Opened a modpage (https://www.nexusmods.com/skyrimspecialedition/mods/82794) and received Endorsement reminder popup. 

## Expected result:
Reminder for mods I've downloaded 

## Actual result:
Reminder for mods I've not downloaded.

**Comment by Pickysaurus** [comment]
This is a known issue. The reminder pop-up is planned to be rebuilt at some point. 

You can disable the reminder in your settings or just abstain from the mods it won't let you rate to remove them from the list.

**Comment by Quicksilver-500** [comment]
Just happened to me today as well, I've never seen this bug before since joining the site in 2014. Here are the mods that were suggested that I endorse, I've never downloaded a single one of them.

![image](https://user-images.githubusercontent.com/123167796/213686617-5d66caa0-d53a-46d5-8a52-c984ce887a75.png)

**Comment by TheGhostHybrid** [comment]
Ah, glad to know I’m not alone in this! Sorry for creating a duplicate issue ^^;

**Comment by jakobharder** [comment]
Endorsements have tanked for the last 2 weeks for many mods.
I assume this is a widespread bug.

**Comment by Pickysaurus** [comment]
This should now be fixed next time your endorsement reminder appears.

**Comment by auddie2015** [comment]
This has been happening to me the last week or so. Even ones I redid show up again. Not a big deal. Just letting you know.
