### ISSUE TITLE
Forums sorted by last posting time look weird

### ISSUE THREAD

**Issue by Zaflis** [Nexus-Mods/web-issues#1641]
## Bug/error being reported:
In the website nexusmods.com, when a mod has Forum tab and you click on "Last post" for sorting by latest, they are not actually sorted by date. There are posts from 2022 and then 2023 somewhere in the middle, not top or bottom as expected.

## Steps to reproduce:
1. For example open this mod forum:
https://www.nexusmods.com/valheim/mods/850?tab=forum
2. Click "Last post" header.

## Expected result:
Expected messages ordered by last post time.

## Actual result:
Illogical order happens.

![weird_order](https://user-images.githubusercontent.com/1862429/213871534-c4d9f7a4-ecf0-45b9-9b16-185028c89d92.png)

**Comment by Zaflis** [comment]
If i'm looking that right it seems dates are compared like strings.

**Comment by Pickysaurus** [comment]
This isn't likely to get fixed so I'm going to close the issue. I've noted it internally for when we rebuild mod pages: backend/nexusmods/-/issues/314
