### ISSUE TITLE
Site slow to load/crashes to Gateway timeout

### ISSUE THREAD

**Issue by irondukester** [Nexus-Mods/web-issues#1642]
## Your username/username(s) affected
Irondukester

## Bug/error being reported:
504:gateway 

## Steps to reproduce:
Opened Nexus Mods
Searched Mod Categories
Searched Clothing and Accessories
Crashed to Gateway timeout

Really happens randomly as I try to open pages...super slow site now.  Never had issues like this prior to the site maintenance/upgrade.
Tried on my laptop and still get the same issues.  Even used a different IP connection to rule out my internet and still have the issue.  

## Expected result:
Well, I would hope the site would load a little faster and not crash on me.  

## Actual result:
Page crashes to gateway timeout page code 504.  Shows a cloudflare page.

![Screenshot 2023-01-22 125105](https://user-images.githubusercontent.com/123321712/213931683-5afb0068-8a0b-42ce-a32d-73d732013ea3.png)

**Comment by Pickysaurus** [comment]
This was a temporary issue during the weekend.
