### ISSUE TITLE
Browser freezing when viewing a giant Bug report on a mod

### ISSUE THREAD

**Issue by EricBenjamin14** [Nexus-Mods/web-issues#1644]
## Your username/username(s) affected
Scorchfrost

## Bug/error being reported:
When submitting a Bug on a mod, there's no text limit. I posted a crash log for Skyrim that was so big that it made my browser freeze up whenever I would open my own bug report.

## Steps to reproduce:
1. Go to a mod (I experienced this on https://www.nexusmods.com/skyrimspecialedition/mods/67003)
2. Go to the Bugs tab
3. Press Report a bug
4. Copy an extremely large text into the 'Report' field (I've attached the crash log that I copied in) [WolfskulLCaveCrashLopg.txt](https://github.com/Nexus-Mods/web-issues/files/10515237/WolfskulLCaveCrashLopg.txt)
5. Add a title and submit the bug
6. Refresh and open the bug you submitted, your browser will start freezing (at least mine did -- Google Chrome)

## Expected result:
Either there would be a text limit for bug reports, or my browser would be able to handle it

## Actual result:
My browser was very much not able to handle it

**Comment by Pickysaurus** [comment]
There's not much we can do about this as-is. The page is rendering the post in-line which causes the freeze. The entire bug report feature on mod pages will eventually be replaced by the system in use for Collections so it may just be a case of waiting for that.

**Comment by Pickysaurus** [comment]
This isn't something that will be fixed in the current bug report system for mods, but the new bug reports system currently in use for collections has a character limit and will (soon) support attachments for log files to avoid the need for long pastes. 

This new system will be used for mods too in the future.
