### ISSUE TITLE
Mod disappears from all search results after renaming

### ISSUE THREAD

**Issue by LenaWolf** [Nexus-Mods/web-issues#1646]
## Your username/username(s) affected

LenaWolfBravil

## Bug/error being reported:

I uploaded a mod for Dragon's Dogma and published it, everything was fine. Then I decided to rename it - change the mod name with Manage->Mod details. The mod itself can still be found if you go to the page directly, it is not blocked or hidden. However, it no longer appears in any search results and also not under Mods->Recent Activity from the top ribbon.

Mod page: https://www.nexusmods.com/dragonsdogma/mods/820

**Comment by Pickysaurus** [comment]
![Screenshot_20230203-221231](https://user-images.githubusercontent.com/31670524/216720810-5a438a5b-9c36-4d41-a7ad-7665042bc648.png)

Seems to be there for me. The site has a cache so it can take several minutes for changes to filter through
