### ISSUE TITLE
Download History Vanished

### ISSUE THREAD

**Issue by LeoTianPro** [Nexus-Mods/web-issues#1648]
## Your username/username(s) affected

Titanlbr520
## Bug/error being reported:

While venturing, I noticed that all of the update status indicators above the mods I had downloaded disappeared. After clearing cache, switching browser, signing out and back in, nothing appears on my download history.

**Comment by Pickysaurus** [comment]
This is a temporary error that we're aware of. It should re-appear after 1-2 hours.
