### ISSUE TITLE
Modpage says "not opted in rewards program" when opposite is true?

### ISSUE THREAD

**Issue by veopikke** [Nexus-Mods/web-issues#1649]
## Your username/username(s) affected
veopikke

## Bug/error being reported:
Every single mod that I have public right now has "**This mod is currently not opted in to our mod rewards program**" written in the ABOUT THE MOD section, even though I have opted all of them in previously. Strangely enough, when I click **Opt-in**, it says that I already have opted the mod in and am receiving 100% of the revenue.
I do hope that this is purely a visual bug, and that it won't affect my DP wallet. I currently have 8113 DP in the wallet and 6077 pending (noted for reference if anything happens to them)

## Actual result:

**[https://imgur.com/a/hY2H3se](https://imgur.com/a/hY2H3se)**

**Comment by SkyrimSloot** [comment]
Also having the same issue, although I think it's just a visual bug, since last night i've had 30 more downloads, and when I click opt-in, it takes me to the opted in mods screen and the new downloads are reflected on it.

**Comment by veopikke** [comment]
[Now it's okay again?](https://imgur.com/ODNFCNN)
