### ISSUE TITLE
Consistent Error on uploading large files

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#165]
I am still getting errors with large files. I have shared a number of screenshots with SirSalami via Discord.
Most recently I got this:
`63 fileProgress [object Object]

 HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://rd.nexusmods.com/Uploads?File`

The files I have been uploading to replicate this issue are >2gb and upload without issue on the old site.

**Comment by verenion** [comment]
Is this still an issue?
