### ISSUE TITLE
The [code] tag in BBCODE functions inconsistantly between the forums and the posts tab for mods - Syntax highlighting breaks Posts

### ISSUE THREAD

**Issue by LeakingAmps** [Nexus-Mods/web-issues#1651]
## Your username/username(s) affected
fwyrl

## Bug/error being reported:
While posting on the NexusMods.com forums, using the [code] block does not display the same in the posts tab under mods as it does in the forums, for a post with XML (such as below)

`<set xpath="/items/item[@name='vehicle4x4TruckPlaceable']/effect_group/passive_effect[@name='DegradationMax'][@value='7500']@value">3000</set>`

## Steps to reproduce:
Try and post this on the posts tab of a mod (this was specifically in a 7 days to die mod, but afaik, the rendering is the same across nexus):

`Normal Text

[code]<set xpath="/items/item[@name='vehicle4x4TruckPlaceable']/effect_group/passive_effect[@name='DegradationMax'][@value='7500']@value">3000</set>[code]

Normal Text`

The post in question is on this mod ( https://www.nexusmods.com/7daystodie/mods/755?tab=posts&BH=28 )

There is a workaround, shown in my post there, where adding a space after the ''<'' prevents the code block from breaking the display on the Posts tab, presumably because it disables syntax highlighting.

## Expected result:
Given that posts can be exclusively posted and read from either platform, I'd expect posts to render the same on both (preferably the syntax highlighting of the forums would come to the posts tab).

## Actual result:
In the view that the Posts tab has, it will render as 
`Normal Text

3000

Normal Text`

While in the Forums, it'll render as the full post, complete with syntax highlighting on the section in the code block.

**Comment by Pickysaurus** [comment]
This will be fixed by our new comments system which will use Markdown instead of BBCode.
