### ISSUE TITLE
Can't Buy Premium

### ISSUE THREAD

**Issue by Raxonn** [Nexus-Mods/web-issues#1652]
Wraith979

## Bug/error being reported:
Unable to subscribe to premium.

## Expected result:
Successful payment.

## Actual result:
Error Message: Unfortunately there was an error while processing your payment: Authentication Required. (Transaction ID: 82h2z2ma).
I have tried with two separate bank cards and was unsuccessful, and I have checked with my bank.

**Comment by Pickysaurus** [comment]
I'm afraid this isn't an error on our end so we can't help you with it. "Authentication Required." means your payment provider is blocking it. Please try contacting them for further advice.
