### ISSUE TITLE
Unable to pay for premium

### ISSUE THREAD

**Issue by Ishikudeska** [Nexus-Mods/web-issues#1653]
FUUCLK

## Bug/error being reported:
trying to use my debit to buy premium

## Steps to reproduce:
try buying premium with you debit

## Expected result:
successful buying of premium

## Actual result:
declination of card

**Comment by Pickysaurus** [comment]
I'm afraid we have no control over credit/debit card validation. This is a communication between BrainTree and your bank. I would suggest making sure your card details are correct and if it still fails, you may want to contact your payment provider. 

Thanks for supporting our community!
