### ISSUE TITLE
Vortex Mod Manager results in 5/15FPS When downloading new mod.

### ISSUE THREAD

**Issue by Scarundy** [Nexus-Mods/web-issues#1654]
Your username/username(s) affected
Scarundy

Bug/error being reported:
Every time I download a new mod, Skyrim(SE) Becomes unplayable. Frames dropping to 15FPS or even less.

Optimally an ordered list with the steps needed to reproduce the bug

Example:
1. Download any mod
2. Download with Vortex and be sure to deploy
3. Open SkyrimSE and see results
-->

Expected result:
Enjoy SkyrimSE with my new mod(s) Installed

Actual result:
Open up a save and get blasted with framedrops, Almost impossible for me to even close the game!

FIX:
Updating my (Nvidia) graphics drivers after installing a mod. Very tedious.

ARGUMENTS:
Yes, my vortex is up to date, Yes. I tried the game without ENB/BethINI or any other tools installed. Yes. I sent an email to nvidia before finding out Vortex was the culprit and they were as confused as I am. Yes. I tried other driver versions.

Conclusion:
Vortex is at fault. Please find a fix, and update.

**Comment by Pickysaurus** [comment]
Please report Vortex problems in the correct repo https://github.com/Nexus-Mods/Vortex/issues/new/choose

(You can also send feedback via the app itself).
