### ISSUE TITLE
Vortex Collection file upload size cap: Aws::S3::Errors::NotFound

### ISSUE THREAD

**Issue by bongodoctor** [Nexus-Mods/web-issues#1655]
bongodoctor

Upload a collection which is larger than 3GB in size including bundled files

Here is explanation from TanninOne:

This is a server error. The log contains additional information:

Wed, 15 Mar 2023 12:44:53 GMT - debug: uploading file targetUrl=https://nexus-collections-temp.nexusmods.com/uploads/..., dataSize=3045797073
Wed, 15 Mar 2023 12:44:53 GMT - debug: upload complete targetUrl=https://nexus-collections-temp.nexusmods.com/uploads/..., dataSize=3045797073, statusCode=413, elapsed=82
Wed, 15 Mar 2023 12:45:10 GMT - warn: error notification message=The server rejected this collection
The status code 413 means "Content Too Large"

So, as you suspected, this is due to the collection size (3GB in this case). The server outright refuses the upload instantly, implying there is a limit set on the server side.
I'm not aware that there is an (intentional) cap though, you might want to report this to the website (https://github.com/Nexus-Mods/web-issues/issues)

**Comment by Pickysaurus** [comment]
Please try again now, we've reversed the recent change to the Collection system which may have caused this.

**Comment by bongodoctor** [comment]
Will do :)

**Comment by bongodoctor** [comment]
Still getting the same error - will try again later :)

**Comment by mrmason** [comment]
Please can you provide the logs you're getting from vortex ?

**Comment by bongodoctor** [comment]
Ok just tried again and it worked this time :)
