### ISSUE TITLE
I cannot download mod file past 10mb with WIFI

### ISSUE THREAD

**Issue by rubyr47** [Nexus-Mods/web-issues#1657]
Username : rubyr47

I cannot download mod file data past 10 mb with neither MO2, Vortex, or manual download, it's just error for some reason. im using WIFI 

But when i use my mobile data ( hotspot ), i can download mod file.

how to fix this?

**Comment by Pickysaurus** [comment]
Please see our help article here https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

**Comment by rubyr47** [comment]
i read the article and follow it before asking, but its not working

" Downloads don't start: You should consult our "[Troubleshooting website issues](https://help.nexusmods.com/article/113-troubleshooting-website-issues)" page. This is normally caused by a browser addon or privacy settings. "

Then i click the link 

![image](https://user-images.githubusercontent.com/77791473/227822606-19869d17-d2b2-4c3f-84e5-10cfdbe20955.png)
