### ISSUE TITLE
Authorize is misspelled as authorise when linking account to Vortex

### ISSUE THREAD

**Issue by Mythical-Atlas** [Nexus-Mods/web-issues#1660]
## Your username/username(s) affected
none2012

## Bug/error being reported:
When I linked my Nexus account to Vortex Mod Manager, it had me log in to the website. When I logged in, it had me click a button labelled "authorise," which should be spelled "authorize."

## Steps to reproduce:
1. Launch Vortex Mod Manager for the first time.
2. Attempt to download a mod on the Nexus website.
3. Follow the link to Nexus to log in and authorize the account.
4. See button.

## Expected result:
Authorize

## Actual result:
![image](https://user-images.githubusercontent.com/11390837/231641909-7a692521-e804-440d-a489-20f839458945.png)

**Comment by halgari** [comment]
Authorise is the correct spelling used in en-GB dialects, Authorize is the en-US spelling, Nexus Mods is based in the UK so I'd label this as "not a bug"

**Comment by Pickysaurus** [comment]
This is the correct spelling in English UK.
