### ISSUE TITLE
Muted ad makes sudden sounds

### ISSUE THREAD

**Issue by WeizhaoT** [Nexus-Mods/web-issues#1662]
## Your username/username(s) affected
ALTAIR1056

## Bug/error being reported:
I muted the ad and my web browser (Google Chrome) keeps it muted whenever I open a new Nexus page. 

When I have a Nexus mod page in the background, my computer sometimes makes a sound (part of some video) that lasts no longer than 0.5s. Though the sound was always short, it gave me shocks because I wasn't expecting it. 

I am 100% sure it's coming from Nexus ads. It never happened if I don't open the pages. Also, nothing else on the web page makes sounds. 

Possibly, when an ad is chosen to be played in the loop of ads, there is a race condition of playing and muting. The race condition is not completely handled, such that the ad video may be played before being muted. 

## Steps to reproduce:
Just leave a mod page in the background, max your volume and wait. 

## Expected result:
After I mute the ad, nothing is heard no matter how long I keep Nexus pages open. 

## Actual result:
I hear sudden bursts of noises from the ads that shocked me.

**Comment by Pickysaurus** [comment]
To report bad adverts, please see this help page: https://help.nexusmods.com/article/100-how-to-report-bad-or-inappropriate-ads
