### ISSUE TITLE
Mod Version Bug

### ISSUE THREAD

**Issue by Guran-Gravity** [Nexus-Mods/web-issues#1663]
## Your username/username(s) affected

GuranGravity
## Bug/error being reported:

Mod version is not reflected correctly.
## Link to the affected mod:
https://www.nexusmods.com/skyrimspecialedition/mods/16830?tab=files
https://www.nexusmods.com/skyrimspecialedition/mods/33474?tab=files

**Comment by Demorphic** [comment]
Can you please provide more information and fill in all relevant fields?
