### ISSUE TITLE
Search in topic is not working in any mod's forum thread

### ISSUE THREAD

**Issue by JoaquinSuez** [Nexus-Mods/web-issues#1665]
## Bug/error being reported:
Forum search in topic not working correctly in any mod's forum thread

## Steps to reproduce:
Go to a mod's forum thread ~~topic on https://forums.nexusmods.com/~~, type something to search for, click the magnifying glass to seach "This topic".

## Actual result:
The search redirects to: https://forums.nexusmods.com/app=core&module=search&do=search&fromMainBar=1

Same as:
https://github.com/Nexus-Mods/web-issues/issues/1059

**Comment by Pickysaurus** [comment]
Can you be specific as to which topic you were trying to search? There is a timeout on the search which you might be hitting in a large thread.

**Comment by JoaquinSuez** [comment]
Apparently this only happens in the forum threads of the mods no matter the size.
https://forums.nexusmods.com/index.php?showtopic=12674445
https://forums.nexusmods.com/index.php?showtopic=12902901

It doesn't happen in regular forum threads.
https://forums.nexusmods.com/index.php?/topic/6582236-simple-manual-load-ordering-plz/

**Comment by JoaquinSuez** [comment]
> Seems to be working here. 

Are you searching a [mod's forum thread](https://forum.nexusmods.com/index.php?showtopic=3410725)? It only happens in those specific threads, regular ones work just fine

>What was the specific search term?

Just about any term. I remeber using 'compatibility' and 'thanks' amongst others.
>

I have this problem in both my pc and the computer at work. I live in Argentina btw, maybe it's a regional thing? I don't think it's a timeout thing as it happens from the first search. 

https://i.imgur.com/iYIbZHy.png

**Comment by Pickysaurus** [comment]
Here's a screenshot of the results page I'm seeing: 
![image](https://github.com/Nexus-Mods/web-issues/assets/31670524/6834b719-af33-47eb-bc0d-3e46c63b616e)
