### ISSUE TITLE
Strange error when cropping header file for a new mod page

### ISSUE THREAD

**Issue by TheRealElianora** [Nexus-Mods/web-issues#167]
Started to add a new mod. Made through the first section. On Media part, I added a header image by dragging and dropping, it uploaded it, but when I pressed CROP at the bottom of screen, this overlay popped up and took over the entire screen. Couldn't find anything related on the issue tracker.

![2017-10-20_042635](https://user-images.githubusercontent.com/26447310/31801215-316df474-b54f-11e7-99f8-bd42c4c9d1c3.png)

I am using Chrome with a few security / ad extensions like JavaScript popup blocked and uBlock, but disabling them didn't do anything.

**Comment by verenion** [comment]
Assigned PT#152139773

**Comment by TheRealElianora** [comment]
The only way I was able to add a header to my mod page was to add an image that was exactly 1400*400

**Comment by verenion** [comment]
I've pushed some changes to RD to solve this, so this should be resolved. If you could try again and let me know that would be great.
