### ISSUE TITLE
All Time does not work correctly for Fallout 4

### ISSUE THREAD

**Issue by Kashrlyyk** [Nexus-Mods/web-issues#1671]
## Your username/username(s) affected
Kashrlyyk

## Bug/error being reported:
When I selected ALL TIME in the "New mods this week for FALLOUT 4" screen I got LESS
results than selecting "1 YEAR"!

For Fallout 4 I get 112 results for ALL TIME and 6726 results for 1 YEAR!
On the Cyberpunk 2077 page it works as expected!

## Steps to reproduce:

Optimally an ordered list with the steps needed to reproduce the bug
STEP 1 Go to New mods this week for FALLOUT 4 
STEP 2 Select All Time 
STEP 3 Select 1 Year!
STEP 4 Compare

## Expected result:
More hits for ALL TIME than 1 Year

## Actual result:
Take a WILD guess!

**Comment by Pickysaurus** [comment]
Your replication steps were not entirely clear, are you starting here?
