### ISSUE TITLE
Uploading files stucks on "Your upload is being processed" for some files

### ISSUE THREAD

**Issue by lilebonymace** [Nexus-Mods/web-issues#1672]
## Your username/username(s) affected
lilebonymace

## Bug/error being reported:
During today i have been trying to upload a new version of my mod and it always stucks on "Your upload is being processed" forever. I've tried renaming the file, repacking it in the same and different format. Tried in both Firefox (114.0.1) and Chrome (114.0.5735.133).
Moreover, not only it doesn't want to upload the new version, it also refuses to upload older versions of my mod, which were already uploaded to nexus earlier. However, some other files are getting uploaded (and do that in a very short time as usual). The result is the same with any file settings and it doesn't matter to which page i upload the file.
[Here](https://mega.nz/folder/kx8z0BRI#7VpIbD2maVOaRBVKiIad6A) i uploaded both files that stuck (the first was already successfully uploaded to nexus earlier) and files that don't stuck.

## Steps to reproduce:
1. the mod page > Manage > Files (i tried to upload files to [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/27962) mostly but the result is the same for other my mods)
2. click "Or browse for files" button on the "Add new file" form
3. choose [a file](https://mega.nz/folder/kx8z0BRI#7VpIbD2maVOaRBVKiIad6A)

## Expected result:
The file is getting uploaded in a reasonable time.

## Actual result:
It stucks on "Your upload is being processed" forever.

![изображение](https://github.com/Nexus-Mods/web-issues/assets/65489649/9cd0c35a-bf1b-4a5d-ac81-1d86471388dc)

I've also noticed CORS errors in dev tools

![изображение](https://github.com/Nexus-Mods/web-issues/assets/65489649/75a9d92a-e452-4a7f-a101-369a78260e89)

**Comment by notsafeadults64** [comment]
I, too, am experiencing this while attempting to upload files.

**Comment by Pickysaurus** [comment]
Please can you check this thread if you're still having this problem: https://forums.nexusmods.com/index.php?/topic/12976329-stuck-on-your-upload-is-being-processed-june-2023/
