### ISSUE TITLE
Unable to upload mod updates

### ISSUE THREAD

**Issue by notsafeadults64** [Nexus-Mods/web-issues#1673]
## Your username/username(s) affected
notsafeforadults64

## Bug/error being reported:
Unsuccessful new mod version upload.  File appears to upload properly as the status bar fills up quickly.  Then it hangs on the 'file is being processed' spinner.  

Was able to previously upload files without issue earlier in the day.

## Steps to reproduce:
1. the mod page > Manage > Files (i tried to upload files to [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/88287) mostly but the result is the same for other my mods)
2. click "Or browse for files" button on the "Add new file" form
3. choose file

## Expected result:
Successful file upload.

## Actual result:
It hangs on "Your upload is being processed" without progress.

Tons of CORS errors in dev tools

**Comment by Pickysaurus** [comment]
Please can you check this thread if you're still having this problem: https://forums.nexusmods.com/index.php?/topic/12976329-stuck-on-your-upload-is-being-processed-june-2023/
