### ISSUE TITLE
Manifest not loading the past few days.

### ISSUE THREAD

**Issue by Tommack63** [Nexus-Mods/web-issues#1674]
## Bug/error being reported:

Will not load manifest since last Vortex update... nor DL a new copy. 

## Steps to reproduce:
Launch Vortex

### Example:
Here's the log contains mostly warnings about mods which are not on Nexus anymore, that's where any latency is. 

## Expected result:
Figure out why manifest will not download...

**Comment by Pickysaurus** [comment]
This tracker is not for issues with Vortex
