### ISSUE TITLE
Unable to download 7-10GB file

### ISSUE THREAD

**Issue by BeholdAdam** [Nexus-Mods/web-issues#1677]
## Your username/username(s) affected
adamsetzler

## Bug/error being reported:
large files not successfully completing

## Steps to reproduce:
Attempt to download https://www.nexusmods.com/skyrimspecialedition/mods/38775?tab=files&file_id=209523

## Expected result:
file downloads

## Actual result:
file does not even begin to download in a browser
in a mod manager or through Wabbajack, the file exhibits normal download behavior but then stops at 100% and never completes
seems to be the same as issue #1012
ping files.nexus-cdn.com produces:
Pinging files.nexus-cdn.com [89.187.185.168] with 32 bytes of data:
Reply from 89.187.185.168: bytes=32 time=73ms TTL=49
Reply from 89.187.185.168: bytes=32 time=71ms TTL=49
Reply from 89.187.185.168: bytes=32 time=71ms TTL=49
Reply from 89.187.185.168: bytes=32 time=69ms TTL=49

Ping statistics for 89.187.185.168:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 69ms, Maximum = 73ms, Average = 71ms

**Comment by Pickysaurus** [comment]
As noted when raising an issue, we need you to follow the troubleshooting here for download problems: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

**Comment by BeholdAdam** [comment]
> As noted when raising an issue, we need you to follow the troubleshooting here for download problems: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

I did, nothing helped
