### ISSUE TITLE
Unable to download large file

### ISSUE THREAD

**Issue by BeholdAdam** [Nexus-Mods/web-issues#1678]
Country: USA

Internet Service Provider (ISP): GCI

Average Download Speed (non-Nexus downloads): 10MB/s 

Download tests:

    Amsterdam: 10.3MB/s
    Prague: 12.5MB/s
    LA: 49.6MB/s
    Chicago: 32.9MB/s
    Miami: 28.2MB/s
    Premium CDN: 22.4MB/s

Download links: 

    Large File: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=1000178176&game_id=110

THE LARGE FILE DID NOT EVEN START DOWNLOADING

    Small File: https://cf-files.nexusmods.com/cdn/1704/1137/Ordinator%209.31.0-1137-9-31-0-1635693140.zip?md5=8BN4sv7UR7fEWOGOoy92hg&expires=1688644933&user_id=171042648&rip=66.223.174.14

TraceRoute results: 

Tracing route to files.nexus-cdn.com [89.187.185.168]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  192.168.0.1
  2     *        *        *     Request timed out.
  3     9 ms     7 ms     8 ms  10.128.9.17
  4     7 ms     7 ms     7 ms  10.128.14.13
  5     7 ms     6 ms     7 ms  10.128.17.225
  6    12 ms     9 ms     9 ms  10.128.137.54
  7    25 ms    24 ms    25 ms  10.128.4.129
  8     *        *        *     Request timed out.
  9     *       49 ms    49 ms  10.128.4.165
 10     *       43 ms    45 ms  10.128.4.182
 11     *        *       48 ms  10.128.0.133
 12    48 ms    51 ms    49 ms  be-114-pe11.seattle.wa.ibone.comcast.net [50.248.117.237]
 13    49 ms    48 ms    49 ms  be-2111-cs01.seattle.wa.ibone.comcast.net [96.110.32.225]
 14    47 ms    48 ms    48 ms  be-1112-cr12.seattle.wa.ibone.comcast.net [96.110.47.182]
 15    58 ms    59 ms    59 ms  be-304-cr12.portland.or.ibone.comcast.net [96.110.38.46]
 16    57 ms    58 ms    58 ms  be-1212-cs02.portland.or.ibone.comcast.net [96.110.46.229]
 17    51 ms    52 ms    51 ms  be-1211-cr11.portland.or.ibone.comcast.net [96.110.46.226]
 18    62 ms    60 ms    62 ms  be-302-cr13.sunnyvale.ca.ibone.comcast.net [96.110.36.125]
 19    63 ms    61 ms    61 ms  be-1213-cs02.sunnyvale.ca.ibone.comcast.net [96.110.46.21]
 20    68 ms    68 ms    68 ms  be-1212-cr12.sunnyvale.ca.ibone.comcast.net [96.110.46.18]
 21    68 ms    67 ms    72 ms  be-303-cr12.9greatoaks.ca.ibone.comcast.net [96.110.37.178]
 22    69 ms    69 ms    71 ms  be-1112-cs01.9greatoaks.ca.ibone.comcast.net [68.86.166.133]
 23    63 ms    61 ms    61 ms  be-1111-cr11.9greatoaks.ca.ibone.comcast.net [68.86.166.130]
 24    74 ms    74 ms    74 ms  be-304-cr11.losangeles.ca.ibone.comcast.net [96.110.36.157]
 25    67 ms    68 ms    70 ms  be-1411-cs04.losangeles.ca.ibone.comcast.net [96.110.45.185]
 26    74 ms    74 ms    74 ms  be-2411-pe11.losangeles.ca.ibone.comcast.net [96.110.33.14]
 27    68 ms    68 ms    68 ms  66.208.216.74
 28     *        *        *     Request timed out.
 29    70 ms    71 ms    69 ms  unn-89-187-185-168.cdn77.com [89.187.185.168]

**Comment by Pickysaurus** [comment]
Please post your results on the forums, as advised in the help article.
