### ISSUE TITLE
Editing mod permissions does not have option about paid mods

### ISSUE THREAD

**Issue by TheRealElianora** [Nexus-Mods/web-issues#168]
When making edits to mod page's permission details, the option to comment about allowing or disallowing use for paid mods is not available, resulting in it automatically showing as being allowed.

![screenshot_20171021-052001](https://user-images.githubusercontent.com/26447310/31847152-c759c046-b61f-11e7-921f-54cd319efcd9.jpg)

**Comment by mrmason** [comment]
Assigned `PT#152191849`

**Comment by mrmason** [comment]
This should be fixed.
