### ISSUE TITLE
Download just dosen't start

### ISSUE THREAD

**Issue by SlyPunk1755** [Nexus-Mods/web-issues#1680]
SlyPunk1755

## Steps to reproduce:
I just press the button to download and nothing happens. If download in MO2 this error message appear: Connection times out(99)

### Example: These mods wont download
![Screenshot (115)](https://github.com/Nexus-Mods/web-issues/assets/139257646/9e7a7bb0-417d-4506-9418-b90db13905b3)
1. [Step 1](https://www.nexusmods.com/newvegas/mods/71404?tab=files)
2. [Step 2](https://www.nexusmods.com/newvegas/mods/43135?tab=description)
[3. [Step 3](https://www.nexusmods.com/newvegas/mods/51664)-->

## Expected result:
<!-- The mod to starts downloading

## Actual result:
Nothing starts or stuck at 0.0 mb

**Comment by Pickysaurus** [comment]
Please see https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
