### ISSUE TITLE
ELDEN RING THE CONVERGENCE MALIKET BUG

### ISSUE THREAD

**Issue by crimsonnight2025** [Nexus-Mods/web-issues#1681]
## Bug/error being reported:
<After killing Maliketh, i wont get any rewards or progression... Despite the boss making the "Thanos snap animation" which turns to dust or w/e , the healthbar remains visible (with 0 health) and im stuck in the arena alone... Anyone encountered such a problem?
i also tried jumping of the figthing arena after killing him and nothing give a result :( please help !!!!
>

**Comment by Pickysaurus** [comment]
This tracker is not for mod or game issues
