### ISSUE TITLE
Updates list closes randomly

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#170]
It's also mentioned here https://forums.nexusmods.com/index.php?/topic/5964518-help-us-test-the-new-nexus-mods-design/?p=54544028

I've had the thing close on it's own and it will also close instantly if you stray off it for a fraction of a second, if you have a lot of updates it's a nightmare trying to get to all of them.

**Comment by iamtiz** [comment]
assigned #155431682

**Comment by iamtiz** [comment]
This issue happens when removing the last notification at the bottom. When it disappears, the mouse could be outside the now smaller list. We added a bit of delay before the removal, hopefully that's going to help

**Comment by JimUKNexus** [comment]
I had a lot earlier and it was still a pain, it's OK if you only have a few and click "Updates" rather than just mouse over, clicking makes it stay open. If you have a lot then it gets awkward, the load more takes you very close to the bottom edge and the possibility of losing it because after clicking "Load more" it becomes prone to closing even if you clicked updates to open it in the first place.  Maybe an updates tab like Twitter has would be better? or as Facebook does, clicking notifications opens a small number in a list as here but clicking on see all opens them on a new page.

**Comment by iamtiz** [comment]
We are definitely going to add a new notification area on the site, likely in the near future.

**Comment by iamtiz** [comment]
(Closing this for now)
