### ISSUE TITLE
Tags not showing at all if author doesn't allow user tagging

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#172]
On this mod: https://rd.nexusmods.com/skyrim/mods/83837 and a few others, the author has it marked to not allow user tagging. 

But that means that tags don't show up at all. 

https://cdn.discordapp.com/attachments/232170227734020097/371790724259381248/unknown.png No tags! 

Tags should still show even if users can't add them. (in fact, it'd be nice to be able to view all the tags including the ones the author has marked as "ignored", without being able to click the "add tags") button. 

Incidentally this mod is marked as blocked https://cdn.discordapp.com/attachments/232170227734020097/372009292917768192/unknown.png but of course I have no way of verifying if that's correct.

**Comment by iamtiz** [comment]
Assigned task #152198658

**Comment by iamtiz** [comment]
Fixed
