### ISSUE TITLE
Donation popup doesn't occur when endorsing

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#173]
On the old site when I endorse this mod I get a donation popup (doesn't matter what page I endorse it on, I can do it from the https://www.nexusmods.com/skyrim/mods/87383?, from downloads history, etc). I confirmed by un-endorsing and re-endorsing a few times, each time I re-endorsed I got the popup. 

On the new site it doesn't matter where I am history page, mod page, etc. if I endorse it I don't get any popup. 

I tried a few other mods and never saw a popup but since the popup depends on mod author settings it may be that it just wasn't set up. I didn't bother to confirm all of them on the old site as well.

**Comment by mrmason** [comment]
This should now be working correctly.
