### ISSUE TITLE
Modpage description differences between editor and final display

### ISSUE THREAD

**Issue by DaXmAn** [Nexus-Mods/web-issues#174]
There is a huge difference in BB editor and final result on a mod page.
For example in BB editor lists do not have bullet points and are without bottom margin (10px)
It would be great to have the same CSS layout in BB editor and final page.

**Comment by mrmason** [comment]
Please can you give us an example mod page that you're looking at so we can get a better idea of what's not looking correct?

**Comment by TechAngel85** [comment]
I have noticed some differences as well. Mainly in styling as @DaXmAn points out. The spacing of elements is different (though I like the new styling, it isn't reflected when editing).

Also, the BBCode "[line]" does not parse into a horizontal rule (https://www.w3schools.com/tags/tag_hr.asp) as it should.

Please see RWT as an example: https://rd.nexusmods.com/skyrimspecialedition/mods/2182

**Comment by DaXmAn** [comment]
old layout: https://www.nexusmods.com/fallout4/mods/27172/?
new layout: https://rd.nexusmods.com/fallout4/mods/27172
