### ISSUE TITLE
Can't access unpublished files

### ISSUE THREAD

**Issue by RoyBatty64** [Nexus-Mods/web-issues#179]
In addition to not being able to access co-authored files, I also cannot access unpublished files from my user page.

**Comment by verenion** [comment]
Can you provide a link to the mod files you are trying to access, for both co-authored and unpublished?

**Comment by RoyBatty64** [comment]
https://www.nexusmods.com/newvegas/mods/57683/?
https://www.nexusmods.com/newvegas/mods/38719/?
https://www.nexusmods.com/newvegas/mods/39981/?
https://www.nexusmods.com/newvegas/mods/45652/?
https://www.nexusmods.com/newvegas/mods/62839/?
https://www.nexusmods.com/newvegas/mods/63139/?
https://www.nexusmods.com/newvegas/mods/61723/?
https://www.nexusmods.com/newvegas/mods/58982/?
https://www.nexusmods.com/newvegas/mods/47285/?
https://www.nexusmods.com/newvegas/mods/47746/?

**Comment by mrmason** [comment]
@RoyBatty64 - Are you seeing this problem on the current website - or on the redesign - or both ?

**Comment by RoyBatty64** [comment]
The new site. Seems it's fixed now.
