### ISSUE TITLE
Excessive Number of tags

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#18]
For files with a lot of tags they take up way too much space. 
![unknown](https://user-images.githubusercontent.com/31670524/30081201-27944eb0-927e-11e7-836b-cfc4324dd140.png)

**Comment by Gribbleshnibit8** [comment]
`@media screen and (max-width: 1280px) {
    ul.tags {
            max-height: 30px;
    overflow-y: hidden;
    }
}

@media screen and (min-width: 1280px) {
    ul.tags {
            max-height: 60px;
    overflow-y: hidden;
    }
}`

This will limit the tag list to 2 lines on desktop and 1 line on mobile or small screen devices. Still keeps the add tag button so people can see all of them easily.
![image](https://user-images.githubusercontent.com/5009427/30081943-aa6b94a4-924e-11e7-9ce0-ebe722eff2d0.png)
![image](https://user-images.githubusercontent.com/5009427/30081963-bd5f2a94-924e-11e7-8389-d90314aba84a.png)

**Comment by verenion** [comment]
Assigned PT#150890163.

**Comment by verenion** [comment]
Fix has been pushed.
