### ISSUE TITLE
Latin extended characters.

### ISSUE THREAD

**Issue by nazg2001** [Nexus-Mods/web-issues#180]
After changing the description of a modification written in language that using Latin extended characters, instead of those characters “artefacts” appear. You need to save the description on the old version of the layout so that the characters return on the new. It concerns Polish for sure, I do not know how with French, German or other languages using extended Latin characters.

**Comment by mrmason** [comment]
Can you please link to the mod in question - and if possible provide the text you're entering on here so we can attempt it ourselves ?

**Comment by nazg2001** [comment]
Sure. Here are two examples:
https://rd.nexusmods.com/skyrimspecialedition/mods/12958 (text: https://pastebin.com/K4Y3U5ZA)
https://rd.nexusmods.com/skyrimspecialedition/mods/12400 (text: https://pastebin.com/jUeWpRaL)

Any text that contains Polish characters (at least those that I edited myself) has the same problem.

**Comment by mrmason** [comment]
Assigned `PT#152249340`

**Comment by verenion** [comment]
This issue should have been resolved last week.
