### ISSUE TITLE
Downloads are broken

### ISSUE THREAD

**Issue by RaveMan84** [Nexus-Mods/web-issues#181]
Looks like sever not loading files correctly. When you download archive its can`t open.

**Comment by mrmason** [comment]
Please provide any mod you're seeing this on and give us some information on which file it is you're downloading and from which source ( CDN / file server ).

**Comment by Bouboule201288** [comment]
I confirm this for me, many users like me can't download with NMM or worst manually.
https://rd.nexusmods.com/skyrim/mods/78347?
https://rd.nexusmods.com/skyrimspecialedition/mods/10483/?

All my upload from september and october can be downloaded manually when users are lucky and some time NMM doesn't recognize plugins.

**Comment by Thallassa** [comment]
I can download both these mods both manually and with Vortex, from both CDN and premium servers. 

Many people report getting empty files from mods where the file (recent mod or recent mod update) is less than 24 hours old. I always suggest that they wait until the files are fully propagated to the server. I have never personally experienced this error, however.

**Comment by Bouboule201288** [comment]
Hi Thallassa, Can you download the patch Vigilant or the mod for testers with nmm?

**Comment by Thallassa** [comment]
Not sure I understand the question but I don't experience this problem with any mod, including Vigilant.

**Comment by mrmason** [comment]
When you say you can't download the files - what error are you getting?
 - does the download never start?
 - is it a 403 error?
 - Are you using the CDN ?

**Comment by Bouboule201288** [comment]
In fact, when the download is completed on NMM, the sentence "can't be added" appear and the status is "incomplete", and yes, the fileserver is "CDN".

**Comment by lollie145874** [comment]
I am using very old NMM version 0.56.1 and cannot download from premium servers using mod manager. CDN works fine, and manual downloads work from all servers. 
Old site never asks which server to use for NMM downloads, and always uses CDN so this may not be a new site bug, but rather an issue that is just being exposed on the new site.

**Comment by mrmason** [comment]
We can't replicate this - I'm going to close this unless someone can provide any more information / step by step with error messages.
