### ISSUE TITLE
Download preferences not selecting preferred server

### ISSUE THREAD

**Issue by phalen78** [Nexus-Mods/web-issues#184]
Hi.  I am a premium (lifetime) member, and I have my download preference set to Europe #1.

When i download any files with the mod manager it uses only CDN.  I understand that i have unrestricted access from CDN as well, but what is the point of having a preference if you insist on using only CDN?

**Comment by mrmason** [comment]
There are separate settings for download preferences for NMM and from the website.

If you're downloading via the CDN in NMM then you should be able to edit the preferences in the application to choose another location.

**Comment by phalen78** [comment]
Yes, thing is, both NMM and website preferences are on Europe.  the website is putting me on CDN

**Comment by phalen78** [comment]
Hi, I am still not able to get my NMM and Nexus to download from EU Premium. It keeps putting it on CDN.
![image](https://user-images.githubusercontent.com/33064042/32133384-1610bcd2-bbd7-11e7-8955-afd5bba1a066.png)

I have tried the download fix/tweaks for chrome, but that does not help either. please look at this again.

**Comment by mrmason** [comment]
Can you take a look in your download history for that download and check to see what the full URL was when that file was downloaded ?

**Comment by phalen78** [comment]
i am not sure where to look for this info - but here is the download history on nexus site (and nmm on left):
![image](https://user-images.githubusercontent.com/33064042/32134352-0e19d422-bbec-11e7-838e-4001f291cdb4.png)

it does not show a download location. if i click on the log view this is what i get:
![image](https://user-images.githubusercontent.com/33064042/32134357-2a80cd96-bbec-11e7-93db-e105df0ec59b.png)
