### ISSUE TITLE
Search function seems broken

### ISSUE THREAD

**Issue by Gloweye** [Nexus-Mods/web-issues#185]
On main page, I search for Inigo. 

It says 9 mods found, and shows 8, omitting the follower himself.

Since the mod name is spelled in capital letters, I tried that, but no difference.

(Also, seems really slow. But im not sure if that's an issue to report here)
![nexus search bug](https://user-images.githubusercontent.com/17139883/31952809-c9ec8392-b8e1-11e7-815a-8465140311a9.png)

Also, some rather unrelated results seem to appear.

**Comment by mrmason** [comment]
If you visit the authors file page - https://rd.nexusmods.com/skyrim/users/7465756?tab=user+files

Does it say the file is being blocked in your search results ?

If so - can you check your blocked tags against the tags in the mod ?

**Comment by Gloweye** [comment]
It shows it there, but I can't see anything about anything being blocked. A Ctrl+F sees only one occurence of the word, but that's to block the author.

I thought it might be behind those filtered results that the page claims - Found 9 results. 47488 have been filtered out. That seems a lot tho. Is 47488 just the total amount of mods for Skyrim ?

Filtered out seems a bit hostile, but I cant seem to see any filters. Expanding that bar shows the old tags/attributes, but I have nothing set in Category, and for attributes I have all set except for "Has Images", "Adult Files only" and "NMM Compatible"

For comparison, the same search on the old version gives 5 results, including the mod itself.

**Comment by mrmason** [comment]
Do you have anything blocked here?

https://rd.nexusmods.com/users/myaccount?tab=content+blocking

I have nothing blocked, and when I do a global search for `Inigo` on the Skyrim site - I get 15 results. I've asked a few other people and they see the same thing.

**Comment by Gloweye** [comment]
Turns out I had Translations blocked.

Now, I get "found 1 results", I see 14, including translated versions, but the original is still not there.

**Comment by mrmason** [comment]
Can you provide me with your user id so I can take a look in the database and see if I can spot anything strange going on ?

**Comment by Gloweye** [comment]
Going to my profile is:

https://www.nexusmods.com/skyrim/users/7954794/?

I assume 7954794's the user ID ?

**Comment by The4ntichris** [comment]
I've experimented a bit with the FO4 Chinese Assault Rifle (https://rd.nexusmods.com/fallout4/mods/13283) where I got the same weird behaviour and I remember having had trouble with Inigo as well.

The AR gets excluded from my search results while blocking the 'Not lore-friendly' tag.
The mod apparently has 'Lore-friendly' in its tags so it should not be affected.
It seems like tags are being confused?...

**Comment by Gloweye** [comment]
Only block I have left is "Saved Games", which has a score of 0 for Inigo. That shouldn't be able to be it.

**Comment by Thallassa** [comment]
I am also not seeing Inigo on search and none of my tags match the ones on the mod. 

It could be an issue with lore friendly/not-lore-friendly tag behavior specifically. I also have "not lore friendly" blocked.  

May also be related to #77 but that seemed to have been resolved (permazone shows both results now).

**Comment by mrmason** [comment]
Thanks Guys - we are looking into this one. It's possibly related to #77 and I think to #138.

**Comment by unixwitch** [comment]
I ran into this problem as well; unblocking the "translation" tag in my preferences has fixed it, but I don't remember blocking that tag in the first place.

Noticed with at least two Skyrim SE mods: [Alternate Start](https://rd.nexusmods.com/skyrimspecialedition/mods/272) and [ApachiiSkyHair SSE](https://rd.nexusmods.com/skyrimspecialedition/mods/2014), neither of which seem to have the "translation" tag to begin with.

**Comment by Eolhin** [comment]
I have a very similar problem, only to the best of my ability to tell (using the search feature in the new layout) removing all tags from 'Refine with tags', removing all checks from 'Refine by category', and from 'Attributes' (I have to clear the checks manually, as 'clear selection' does not remove the checks, and in fact brings them back if they have already been cleared) and applying those settings does not result in the main Inigo mod showing up in a search.  The checks that keep returning to 'Attributes' are the settings I had on the old layout, and Inigo DOES come up in a search with those attributes active on the old system.  Unlike others here, for me removing all filtering tags (there are none by default, only 'Attributes', and I removed those as well) does not allow Inigo to come up in a search.  This seems to be the case for both the Oldrim Inigo, and the SE Inigo.

It probably doesn't matter, but I use Chrome.

**Comment by solonlost** [comment]
I've just had this problem with westtek optics. A search for "Westtek" turns up all the addons, but not the main mod itself.

**Comment by mrmason** [comment]
We're still looking into this one - it looks like it's to do with tags causing strange behaviour in search results - We've assigned `PT#152408335` to track it internally.

**Comment by TheRealElianora** [comment]
If a user is blocking Translations tag, the system blocks any mod with ANY languages tagged. So if a mod has the tag "English" on it, it will disappear from users that have Translations blocked, even if the user doesn't have English tag blocked.

**Comment by Eolhin** [comment]
I did have the translations tag blocked in the old layout, and that seemed to automatically transfer to the new layout as the translation Attribute checked under refine results, but I unchecked all of the pre-checked Attributes, and made sure there were no tags listed at all in my search parameters, and I still have the problem.  Also, if I use the 'clear selection' link under Attributes, it puts all of those check-marks back in, as if, for me, having those checked is the default.  It doesn't matter how often I change them, every time I go back to search they are right back again.  Also, it is not filtering out the actual translations of the mod, only the primary mod, almost like what that Attribute blocks is somehow reversed from what it should be, allowing the translations, but not the base mod.

**Comment by mrmason** [comment]
We've pushed some fixes today - can you please take a look from your perspective and see if you're still seeing anything strange ?

**Comment by Gloweye** [comment]
For me right now, showing up as expected.

**Comment by Thallassa** [comment]
I tested a few of the issues people had seen and everything is showing up. In addition the notice that you've blocked a mod on the mod author page seems to be accurate to the tags I actually have blocked, now. 

I also asked a few other people test the issues they'd had and it's working correctly for them. 

Some people are getting a database error when trying to access nexus and can't test at the moment. 

I think if we do find new issues in search it won't necessarily be related to this issue. This primary issue seems to be fixed *fingers crossed*.

**Comment by mrmason** [comment]
Sorry, we were spinning up some more capacity for the environment which caused the database errors. Should all be sorted now. 

I'm going to close this for now - all the scenarios I've tested seem to be working. Please open a new bug report if you find anything else.

**Comment by Eolhin** [comment]
The main mod under a search is showing up correctly now, but the rest of the problems I was having with the Attributes section are still there, though one has reversed polarity.  I guess I will start a new bug report for that.

**Comment by metro3** [comment]
mrmanson the order function for desc/asc doesn't work right for the new website
