### ISSUE TITLE
Can't log in on 240p screen

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#187]
Ok I know this is probably smaller than you really intend to support... but it is a bug! 

Phone resolution:  240*432
Android version: 7.0
Browser: Chrome

Steps to reproduce:

- Get a really tiny phone
- Go to nexus
- Click on 'menu' button at top right
- Click on login. 
- Keyboard pops up, and I can type my username, but have no way of selecting the password box because the username and password box are not visible. 

I believe the username and password box are off the left side of the screen. you can kind of see the greyed out area and x that should be in the center of the screen. 

https://photos.app.goo.gl/smUsyWgmTtwpQAHO2

Since the ads are 2/3 of the screen at this size I don't think I can use the site on this device without logging in :P

**Comment by verenion** [comment]
The login button should be closing the side navigation, so fixing that should resolve this issue.

**Comment by verenion** [comment]
Assigned PT#152271713

**Comment by verenion** [comment]
This issue should be resolved now.
