### ISSUE TITLE
SidebarGallery Disappears on smaller screen size

### ISSUE THREAD

**Issue by KOD83** [Nexus-Mods/web-issues#188]
When the screen width is smaller than 480px the gallery scroller below the mod stats on a mods page disappears for me. The CSS is setting #sidebargallery to display:none when it hits this size.

When viewing the site on a phone (Galaxy s7) the only way to see the gallery carousel is to flip the phone into landscape mode which is inconvenient.

This issue can be seen by resizing the browser window or visiting the new redesign on a phone.

![screen shot 2017-10-24 at 17 37 51](https://user-images.githubusercontent.com/33066430/31956075-4097db36-b8e2-11e7-8ecb-ece94f78b9d0.png)
![screen shot 2017-10-24 at 17 35 18](https://user-images.githubusercontent.com/33066430/31956077-40c07122-b8e2-11e7-8073-fc5f27d244dc.png)

**Comment by mrmason** [comment]
This is intentional - at 480px wide there isn't really enough room to display a scrolling gallery, and you can choose images just below to browse the images.

If anyone comes up with something that works there then we'd look into implementing it, otherwise we won't be fixing this.
