### ISSUE TITLE
Manual download problem if donation requested

### ISSUE THREAD

**Issue by ChillyWillyGuru** [Nexus-Mods/web-issues#189]
When a mod asks for a donation, you get a page with two choices on clicking manual download: donate and go premium. The third choice of starting the download is missing. A prime example: A Matter of Time.
https://rd.nexusmods.com/skyrim/mods/44091?

EDIT: I came across another mod that asks for a donation, and this one automatically started the download when I clicked manual download. For some reason, just A Matter of Time is not auto-starting.

EDIT: Another mod that won't manually download - this one shows a completely blank page when you click manual download!
https://rd.nexusmods.com/skyrim/mods/86630?

Note - I have all scripts enabled on the nexus, and uBlock disabled on nexus.

**Comment by Thallassa** [comment]
The first one has a *requirements* popup, that's why you have to click the download button. 

The second one works for me.

**Comment by ChillyWillyGuru** [comment]
Okay, the second mod is working now for me. Earlier, it was completely blank. The first still is just as described. I click on manual download and it takes me to the screen where it asks for a donation or go premium. Nothing else happens - no pop up, no auto-start downloading, no options to do anything but donate or go premium. All scripts enabled, and uBlock disabled, so it shouldn't be suppressing anything.

**Comment by Thallassa** [comment]
It looks like this. https://imgur.com/a/AtJ9Y

**Comment by verenion** [comment]
Can you provide a screenshot of the issue you are having, as I cannot replicate this issue.

**Comment by ChillyWillyGuru** [comment]
Yes, and I see what the problem is, but don't know why it does it. Look at my snapshot from the latest Firefox: https://imgur.com/a/UN2jX

The donation box is higher than it should be, covering the download box.

**Comment by Thallassa** [comment]
Manual downloads always open as a pop-up for me. You must have firefox set up to open them in a new tab instead? That's definitely an option in Firefox, although I forget how it is set.

**Comment by ChillyWillyGuru** [comment]
I've tried disabling the popup control in the prefs... no dice. I found a popup related variable in the config that people recommend changing from the default if you don't get popups... still opens in a tab. What kind of web object is the download popup? Is it a floating panel or what? I need more info on what it is in order to google any more settings to try.

**Comment by ChillyWillyGuru** [comment]
By the way, the old format site DOES do the popups right - it's only the new format that opens the popup in a new tab. That may help narrow down the issue - something changed in the way the popups are done that makes Firefox open them in a new tab instead of the current tab. I've since seen the same thing on other mods, like the JIP LN plugin on the NV nexus - has the same exact problem with the donation panel covering the download panel because it's in a tab, not a popup. So all the nexus sections have this issue.

**Comment by ChillyWillyGuru** [comment]
Just tried this in Pale Moon... same problem. The donation panel covers the download section so that it isn't visible, like in the image posted earlier. So Firefox and Pale Moon both have this issue.

**Comment by iamtiz** [comment]
Hi, is this still an issue for you?
