### ISSUE TITLE
Search: Refine view search bar keep effacing parameter's fields

### ISSUE THREAD

**Issue by Marie-EveBenoit** [Nexus-Mods/web-issues#190]
Issue: When I search for a mod with refine results , the search parameter bar (ex: filename contains) erase the field content on enter. 

Why it's an issue: Sometimes you try a few combinaisons of words to search mods, it's nice to not have to rewrite all of it everytime. Also, it helps to see if you made an error in a word (Ex: I was searching for revenge of the enemies 2016 and I kept writing it with 2 n, but couldn't see my error because the field was always emptied after hitting enter).

**Comment by iamtiz** [comment]
Assigned #156011565

**Comment by iamtiz** [comment]
Fixed
