### ISSUE TITLE
Some popup functionality can be used on hidden mods

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#191]
The popup widgets can be used on hidden mod pages, such as the following links:

https://rd.nexusmods.com/Core/Libs/Common/Widgets/ModTaggingPopUp?mod_id=11306&game_id=1151

https://rd.nexusmods.com/Core/Libs/Common/Widgets/EndorsersPopUp?game_id=1151&object_id=11306&object_type=1

The download popup can be used as well, but you would have to know the file ID for it (not the mod ID).

**Comment by mrmason** [comment]
Assigned `PT#152249077`

**Comment by iamtiz** [comment]
Fixed
