### ISSUE TITLE
Enhancement: Search parameters fields too low in refine result view

### ISSUE THREAD

**Issue by Marie-EveBenoit** [Nexus-Mods/web-issues#192]
Issue: The search parameters fields are kind of low in the refine result view. It's the first thing needed when searching. 

It would also be very nice if, at lest, the Name contains field was always visible. It's almost always used but you need to expand the refine result view.

All of this is worst on small screen. (lot more of scrolling because the refine view is big)

**Comment by mrmason** [comment]
This is one of the features that grew massively after the layout was made - we are aware this needs improving and once things settle we will revisit this.

**Comment by Marie-EveBenoit** [comment]
Okidoki, Continue the great work :) !
