### ISSUE TITLE
New search bug with Tag filters

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#194]
Immediately after Wuked said he pushed some search optimizations... 

1. I went to skyrim > browse all mods
2. I selected tag Lore-Friendly
3. The page loaded (it was a bit faster!) 
4. It said at the top "0 results" (should be maybe 10s of thousands), displayed one page of results, with no pagination or page options. 

https://cdn.discordapp.com/attachments/232170227734020097/372456837582159873/unknown.png

The issue only occurs when using tags to filter (either "must have tag" or "must not have tag"). Categories, attributes, file/author name, and the sliders all work fine.

**Comment by Rrrafau** [comment]
Assigned #152272798

**Comment by Thallassa** [comment]
I can no longer replicate this bug.

**Comment by mrmason** [comment]
I think this one has been fixed due to related other fixes - please let us know if you're still seeing it.
