### ISSUE TITLE
Back button takes user back to start of list

### ISSUE THREAD

**Issue by Kitsudragon** [Nexus-Mods/web-issues#195]
It's a little frustrating when working with multi-page lists. When I open a selection, then tap the back button, I generally expect to get back to the page I had just left. If I was on page 5 of a list, I'd expect to still be on page 5.

Instead, tapping the back button once puts me on page 1, no matter where in the list I am.

**Comment by Rrrafau** [comment]
Can confirm this is happening on mod lists https://rd.nexusmods.com/mods/popular/?nav=1&page_size=20

Assigned #152272625

**Comment by mrmason** [comment]
This is fixed, but it looks like there is a new issue related - #278
