### ISSUE TITLE
Changelog Order

### ISSUE THREAD

**Issue by GioGr** [Nexus-Mods/web-issues#196]
this issue is both at the old and new site
at changelog sometimes the authors name the updates that way that the latest ones are not on top.
could it be that the order is by default the time it was added? so the latest one is always on top? 
and then maybe gives us the option to move them up and down

thanks :)

**Comment by Thallassa** [comment]
To clarify on this issue:

This occurs on the old site too, what happens is that it is sorting, say 3.10 before 3.03, because 1 goes before 3. The changelog doesn't respect correct semantic versioning.

**Comment by iamtiz** [comment]
Assigned #155942322

**Comment by iamtiz** [comment]
Fixed
