### ISSUE TITLE
Can't Change Profile Avatar

### ISSUE THREAD

**Issue by HomegrownWookie** [Nexus-Mods/web-issues#197]
Not much other than what the title says. When I go to my profile and click "Change Your Avatar" it redirects me to a page on the forums saying I don't have access to do that. Here is the redirect link: https://forums.nexusmods.com/index.php?app=members&module=profile&section=photo

**Comment by rscottexe** [comment]
This normally happens because you're not logged in on the forums. The site should automatically log you in to the forums when you log in to the site, depending on your cookie settings.

Check you're logged in on the forums.

**Comment by alfx3** [comment]
URL: https://rd.nexusmods.com/users/myaccount
Bug/error being reported: Trying to change NexusMods Avatar redirects to NexusMods Forums where you're supposed to update your picture. But changing the avatar only affect the forums profile picture, not the NexusMods Avatar as well. Even if logged in in the forums the Change Your Avatar button would keep redirecting to the Nexus Forums profile pic editing page.
Steps to reproduce: Click Change Your Avatar.
Expected result: NexusMods Avatar should update.
Actual result: NexusMods Avatar is still the old one.

**Comment by mrmason** [comment]
Assigned `PT#152432968`

**Comment by iamtiz** [comment]
This should now be fixed (just allow a few minutes for the avatar change to be reflected on the site)
