### ISSUE TITLE
Unable to use '+' symbol in comments

### ISSUE THREAD

**Issue by mrmason** [Nexus-Mods/web-issues#2]
It gets stripped out on submit - also might be a problem on other inputs

**Comment by mrmason** [comment]
Assigned `PT#150667558`

**Comment by LadyMilla** [comment]
I also tried various special characters. For example, I added the following characters to a comment:
:.;,_-#&@{}<>%/=()~$ßŁ€[]\'"!
Everything after '#' was stripped.

Apparently, typing '&' triggers the removal of everything that follows the '&' symbol (plus the '&' itself). All the other symbols are displayed correctly.

**Comment by verenion** [comment]
Fix for this has been pushed.

**Comment by LadyMilla** [comment]
The '&' symbol still causes the editor to forget everything you typed after the '&' character and the '&' character itself. The full text is still visible in the editor. Enclosing & between single quotation marks ('&') prevents this glitch from truncating the displayed text.
