### ISSUE TITLE
Clicking "# comments" doesnt work 

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#20]
When you click on where it says # Comments at the bottom of a mod tile on the "Manage Your Mods" page it no longer takes you directly to the comments tab of that mod and just reloads the page
This was core functionality of the manage mods page for me, as it is what I would use to easily check comments on all my mods each day. 

Picture of the link in question. https://www.dropbox.com/s/fqds1sd7fjj8vxt/Screenshot%202017-09-06%2012.45.58.png?dl=0

This is old functionality from the previous version of the site.
The fact that you can still click on it even though it doesnt work lead me to believe this is a bug and not just something that has been removed.

**Comment by verenion** [comment]
Assigned PT#150842756

I've pushed a fix for this.

**Comment by Nazenn** [comment]
Confirmed working consistantly. Thank you very much. 
(And thank you to whoever added the game listing on that page as well recently!)
