### ISSUE TITLE
Mod Page doesn't get updated.

### ISSUE THREAD

**Issue by BiRaitBec** [Nexus-Mods/web-issues#200]
Url: https://rd.nexusmods.com/fallout4/mods/23556

Bug/error: Mod page doesn't update whenever i edit description, making it not visible in the updated mods search filter. This doesn't happen when people upload images or i upload files.

Expected result: Mod page should be visible as updated when i edit description.

Actual result: Not visible when i edit description.

**Comment by Rrrafau** [comment]
Can anyone else replicate this? I've just tried and my mod description updated just fine and the mod was listed in "updated" tab.

**Comment by BiRaitBec** [comment]
So i still have that problem, i've asked an admin of the nexus and he's trying to help me. 


I think it should be something to do with spoiler tags.

**Comment by verenion** [comment]
Is this still happening, or did an admin help with this?
