### ISSUE TITLE
Broken Site for Fallout 4/File not found in our database/Manager Downloads Broken

### ISSUE THREAD

**Issue by BiRaitBec** [Nexus-Mods/web-issues#201]
Error 1: Broken site for fallout 4.

This is the bug: http://prntscr.com/h1oqt2 

Tough with the new layout i can see it well. 

Bugged old layout Url: https://www.nexusmods.com/fallout4/mods/23556/?
Working new layout Url: https://rd.nexusmods.com/fallout4/mods/23556?

 - This visual text structure bug seems happening only on the old layout and only on fallout 4 pages.  

Error 2: Nexus mod manager not working anymore.

 - Nexus Mod Manager can't download or install files in both old and new layouts since the error 1 has started happearing in nexus site. They should be linked somehow.

**Comment by Bazmodin** [comment]
Noticed this just start happening with Fallout 4 mod pages.  When attempting to download a mod through the new layout with NMM I get an "unable to finish download" error with status 'Incomplete'.  The hamster for the Fallout 4 DB might have died.

**Comment by BiRaitBec** [comment]
Eh it's impossible, i've seen this kind of error in text format structure in many other sites. I don't mind of course to use the new layout for a while, but i hope they can get everything to work soon.

**Comment by Axtoned** [comment]
Same thing is happening to me. I guess this is a confirmed bug for now. Let's be patient and wait for them to fix it.

I'm also getting the "Not found on database" and not being able to download mods from the new site. 

Patience.

**Comment by BiRaitBec** [comment]
Let's hope they can put the database back, otherwise we can litterally forget any nexus mod manager download for fallout 4, that is the most critical thing. Cause even doing a new one i guess it won't be enough.

**Comment by BiRaitBec** [comment]
The problem with nexus mod manager downloads seems to be for all games, not just fallout 4.

**Comment by BiRaitBec** [comment]
Solved i guess, didnt test the mod manager download but the site works again,.

**Comment by mrmason** [comment]
There was an error caused by some submitted data at `10/25/2017 @ 5:03am (UTC)` - it took us a bit of time to track it down and we fixed it around `10/25/2017 @ 10:00am (UTC)` - please report any problems you see regarding this after this time :)
