### ISSUE TITLE
Download "Incomplete" Instantly.

### ISSUE THREAD

**Issue by antrys** [Nexus-Mods/web-issues#202]
Using NMM 63.14
Trying to get main file from https://rd.nexusmods.com/fallout4/mods/15466?tab=files
Expected Result: File downloads in NMM
Actual Result:
Download gets passed to NMM, and it tries to download but instantly fails with the following error:

Error: http://filedelivery.nexusmods.com/2154/Vivid Weathers-15466-1-32.zip?fid=77485&ttl=1508934969&ri=8192&rs=8192&setec=2765e7802c67139e8731a4ec3f488c40 , unable to finish the download.

Addendum: Disk has 23GB free, so that's not it.
Downloads worked fine off the old site earlier today, but the old site seems broken right now so I tried the new one and got this problem.

**Comment by YesThisIsBob** [comment]
Getting the same issue with various FO4 mods right now. Seems to be a general thing.

**Comment by verenion** [comment]
Duplicate #201
