### ISSUE TITLE
“View Download History” no longer shows required mods.

### ISSUE THREAD

**Issue by davethegamer** [Nexus-Mods/web-issues#205]
On the old site design clicking “View Download History” would show the author if the user downloaded the required mods along with the mod you uploaded. This was immensely useful when dealing with big reports and figuring out of the issue was based purely off of user error.

**Comment by rscottexe** [comment]
To clarify for the programmers, this is on comments on file pages.

**Comment by Thallassa** [comment]
For reference, the modal on old site and on new site: https://imgur.com/a/ghYGQ

The new site modal is also not wide enough, the text is forced onto two lines (1080p browser full screen).

**Comment by verenion** [comment]
Assigned PT#152344391

**Comment by iamtiz** [comment]
Fixed
