### ISSUE TITLE
Error: Tag not found.

### ISSUE THREAD

**Issue by ogrotten** [Nexus-Mods/web-issues#206]
On `My Account` page, under `Currently Blocked Tags` I have 2 "phantom tags" https://imgur.com/1VScMhq

When I click them to delete I get  https://imgur.com/VyrNRQ2

The HTML element: `<a class="toggle-tag-blocking" id="tag--element" data-tag-id="" data-parent-id="" data-action-block="0">`

The selector: `#tag--element`  << I suspect this is why it can't be deleted as there's no `id` number here between the dashes like other tags.

**Comment by iamtiz** [comment]
Hi, what is your user name (or user id) on the Nexus?

**Comment by ogrotten** [comment]
@iamtiz `monsto`

What are you, banning me now? (=

**Comment by iamtiz** [comment]
They should have gone now :)
