### ISSUE TITLE
Mod pages redirects to an add

### ISSUE THREAD

**Issue by PhoenixSprite** [Nexus-Mods/web-issues#209]
Whenever a mod's page is clicked to download, view images from the mod or other files, no matter where you click on the page, you are redirected to a new tab with an add. Specifically, an add to buy tickets to the league of legends championship.

**Comment by davethegamer** [comment]
Yeah they’re aware of it, it’s their ad provider. They said they will fix it soon.

Dark (Official Nexus Discord Moderator): Yeah, that's a very fooking annoying issue our ad provider has introduced, Hopefully they'll sort it when they wake up.

**Comment by verenion** [comment]
Duplicate of #203

**Comment by verenion** [comment]
This should be resolved now.
