### ISSUE TITLE
Sort by endorsements not sorting correctly

### ISSUE THREAD

**Issue by steve-40** [Nexus-Mods/web-issues#21]
https://rd.nexusmods.com/fallout4/media/popularalltime/?page_size=16&nav=1

On the "Popular (All Time)" page for Fallout 4, I selected to sort by endorsements (desc) but it is not sorting correctly. Most mods appearing on the first page have only 200-600 endorsements, which is clearly wrong.

https://s26.postimg.org/r9svp6ymx/Capture.png

Update: if I sort by endorsements (ascending), then click on the last page# (4755), it is blank with no mods showing. If I then click the < button to step backwards through the pages, they are also completely blank with no mods appearing.

https://s26.postimg.org/xky35lzvd/Capture.png

**Comment by Rrrafau** [comment]
I think the sorting works fine, you are sorting media not mods so there will be considerably less endorsements.

2nd problem with pagination is indeed an issue and it has been already reported.

**Comment by verenion** [comment]
Second issue is a known issue. Assigned PT#150890740.
