### ISSUE TITLE
Empty reason for user ban causes dislocated 'unblock' button

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#210]
![image](https://user-images.githubusercontent.com/7034795/32011509-3ef7d0dc-b9b5-11e7-82d5-10a84e3ab989.png)

When keeping the optional "reason for ban" field empty when banning a user, the 'unlock' button is shifted to the left.

**Comment by verenion** [comment]
Can you submit the steps to replicate this issue?

**Comment by ousnius** [comment]
1. Go to a mod page you are the author of.
2. Go to the comments section and block a user from all your files.
3. Keep the text field for the block reason empty and hit submit.
4. Go to your content blocking settings and you will see the dislocated "Unblock" button: https://rd.nexusmods.com/users/myaccount?tab=content+blocking

**Comment by verenion** [comment]
Assigned PT#152353726

**Comment by verenion** [comment]
Fix has been pushed.
