### ISSUE TITLE
Mod LOGS forces extraneous click

### ISSUE THREAD

**Issue by neokio** [Nexus-Mods/web-issues#211]
Analytics will undoubtedly confirm this, but my theory is that users view Change Logs 20x more often than the Activity Log. However when clicking "Logs", the Change Log accordion is closed by default, forcing me to click again. Extraneous clicks for common tasks = fly in my soup = bad UI.

I suggest either ...
1. Open the change log accordion after clicking Logs by default, or
2. Store the "last opened log accordion" user preference GLOBALLY (in the DB / session / cookie / HTML5 web storage / whatever).

**Comment by iamtiz** [comment]
This will be part of #88
