### ISSUE TITLE
Using search bar without specifying game, then specifying game, removes search keyword

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#214]
I went to the front page, searched for "witcher" in the search bar, it showed mods from all games with the keyword "witcher" as expected. 

When I then used the dropdown filter to restrict it to "skyrim" it forgot my keyword (now showed *all* skyrim mods). I'd expect it to remember that I was searching for mods with keyword "witcher". 

Using the other dropdowns/filters does not cause any issue. 

Issue initially reported by pacfish [here](https://forums.nexusmods.com/index.php?/topic/6098753-new-nexus-mods-design-launched/?p=54678793). I'm going through his others to see if there's any merit to them as well (mostly not).

**Comment by mrmason** [comment]
Assigned `PT#152292923`

**Comment by mrmason** [comment]
This should be fixed now
