### ISSUE TITLE
Different contents within video-page tab

### ISSUE THREAD

**Issue by LetstryagainOnNexus** [Nexus-Mods/web-issues#215]
page:
https://www.nexusmods.com/skyrim/mods/87248/?tab=7&navtag=https%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodvideo%2F%3Fvtype%3D1%26id%3D87248&pUp=1

contents are:
....TITLE with link
upload date
[video]
UNENDORSE [button]
...comments

https://rd.nexusmods.com/skyrim/mods/87248?tab=videos&BH=0
contents are: [video]

**Comment by mrmason** [comment]
We've assigned `PT#152292990` to discuss this.

I don't think we will be displaying the entire description on each video tile as this is shown when the video is expanded - but I think we probably need to display the title.

**Comment by LetstryagainOnNexus** [comment]
Thanks for your answer, 
I think title working as a link to the video page is really needed in order to get to the author of the video.
Thanks for your work on OUR Nexus :D
