### ISSUE TITLE
[POSTS] Comments and Replies are difficult to differentiate

### ISSUE THREAD

**Issue by neokio** [Nexus-Mods/web-issues#216]
In the previous design, replies to comments were left-indented ~100px from the original post, making it very easy for me to accomplish my most common goals within the feature:
- To scan the comments for interesting topics
- To see if something I'm about to post has already been mentioned

Whitespace makes content readable. That's just Design 101. However in the current design, my eyes are drowning in colored blocks within slightly different colored blocks within bordered blocks containing more blocks, all with inconsistent and very tight left padding. The arrangement and alignment of post content has a spatial density that significantly reduces legibility, and is entirely ineffective at splitting comments from replies.

Consider the following example:
![nexus posts](https://user-images.githubusercontent.com/146623/32017077-aad1c8d4-b993-11e7-9928-88182a72bbe8.png)

My suggestion would be to add, at very least, the following CSS ...

```css
.comments>ol>li ol>li,
.comments>ol>li ol>li:last-of-type {
	margin: 0 15px 0 65px;
}
```
... to indent replies 65px (width of the original post's user icon + 15px padding) like so:

![nexus posts suggestion](https://user-images.githubusercontent.com/146623/32017752-b900e4ec-b995-11e7-8611-ac2085df7034.png)

I could offer a dozen more suggestions for legibility and usability, but this single change will provide the greatest immediate improvement.

**Comment by Thallassa** [comment]
This is something for the UX designer to look at. I agree that bigger indentation would be helpful. 

In addition I sent this to SirSalami on discord earlier, but it fits here so I will add it. 

to be specific I think what people want is subsequent comments to indent further. Right now all comments indent to the same level, but if the third comment got another indentation tab and the fourth another, I think it'd be more like the old site. After maybe 3 or  4 indents no further indentation tho

**Comment by mrmason** [comment]
Thanks for the suggestions - We've been discussing this internally and we do have a task open that should improve this very soon -`PT#152292659`

**Comment by neokio** [comment]
@Thallassa If the plan is to add multiple levels of indentation, I'd strongly recommend a massive overhaul of the design, including moving the `REPLY` button to the bottom of the individual comment thread. Otherwise it will be painfully common (especially on long threads) for people to click the closest `REPLY` button, unintentionally replying to the last reply (cascading indentation), rather than to the original topic as a whole.

The consensus on hierarchical structures is that threaded discussions are ultimately too complex for the average user. I'm unable to find my favorite post on the subject (ironic!), but here's a runner up: https://blog.codinghorror.com/web-discussions-flat-by-design/

**Comment by mrmason** [comment]
We've pushed some changes to this - hopefully it should be a bit better.

There is still an outstanding bug with sticky and admin comments - #227
