### ISSUE TITLE
BBCode [heading] doesn't add line anymore and changes font

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#219]
The BBCode for [heading] used to add a horizontal line across the mod page description on the old site. This line is missing on the new site and the font gets changed to the all upper-case one of the redesign.

[heading]Description:[/heading]
https://www.nexusmods.com/skyrimspecialedition/mods/4089
https://rd.nexusmods.com/skyrimspecialedition/mods/4089

**Comment by verenion** [comment]
I've submitted this question to the team to discuss.

**Comment by verenion** [comment]
As this is a design choice, it isn't something we are likely to change now. We will keep this in mind going forward, but I will close this issue to clean up github.
