### ISSUE TITLE
Not all mods showing on mod authors profile

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#22]
Example:
Profile on the new site: https://rd.nexusmods.com/skyrim/users/5197798/?tb=mods&pUp=1&tab=user+files
Profile on the old: http://www.nexusmods.com/skyrim/users/5197798/?tb=mods&pUp=1

None of those mods that are missing are hidden or unavailable in any way, they just aren't showing up. Noticed this on a couple of other profiles, and on my own Unique Zephyr isnt showing up (and I have not changed or set any settings that should stop it, its set the same as all my other mods), but this is one of the more extreme examples where multiple mods are missing from a profile for no apparent reason.

**Comment by iamtiz** [comment]
Hello. I can see your Unique Zephyr mod in your profile page at https://rd.nexusmods.com/skyrim/users/11835658?tab=files. Is it not displayed for you, then? I can see 10 Skyrim mods there in total, and 4 more Skyrim SE mods can be viewed changing the game selection.

**Comment by Nazenn** [comment]
I see only 9 mods on my page despite the tally saying ten. And only seven on the authors page linked. Image:
https://www.dropbox.com/s/s5add21nf2zfg2u/Screenshot%202017-09-06%2020.20.53.png?dl=0

I do see all 4 on the SSE side though.

**Comment by steve-40** [comment]
It's working for me, I can see 10 Skyrim mods, 1 FO3, 5 FO4, 1 FNV and 2 SSE on both the new and old sites. Using Firefox as my browser.

**Comment by mrmason** [comment]
Hi @Nazenn, Can you please let us know if you have any blocked tags in your account preferences ?

**Comment by Nazenn** [comment]
Its definitely something to do with tags,
I had Anime, Skimpy, Translation, and Not Lore Friendly blocked. Removing those filters did make it so I can view Unique Zephyr on my profile again however that mod doesn't have any of those specific tags attached to the file so I'm not sure why it was being removed. The same goes for the mods that were missing from the other authors profile I mentioned, they didn't have those tags. 
(And yes it was Not Lore friendly, and not Lore Friendly, that I had blocked, as all my mods have lore friendly tags and if that was blocked it would have been a bigger issue)

I don't think tag blocking should stop mods from showing up on author profiles regardless, only blocking them via search. 
Hiding mods from an authors profile makes it more hard to see exactly what that author works on for potential collaboration and sometimes tags can be abused by users which makes it harder to detect if mods are so much harder to find in relation to an author.

**Comment by Thallassa** [comment]
I can confirm Nazenn's bug. I currently have cheating, bodyslide preset, anime, extreme violence/gore, mlp, not lore-friendly, saved games, translation, nsfw, nudity, sexy/skimpy blocked. None of these tags match what's on Unique Zephyr, but I cannot see it on Nazenn's author page. I can see the other nine mods. 

I think the difference between Unique Zephyr and the other mods is that Unique Zephyr has had the tag "not lore friendly" _rejected_ by the mod author. I think that somehow this is counting towards the block. 

I also agree with Nazenn that it should work the same way as the old site - all mods are shown regardless of tag blocking.

**Comment by ousnius** [comment]
Agreed that when you already click on an author's profile, it should show all of his mods regardless of blocked content (except for adult unless enabled).

**Comment by Thallassa** [comment]
Ok I see a fix: http://i.imgur.com/pfK2VqN.png

Unfortunately the mods it's noting as blocked should _not_ be blocked. 

For example here's the first one in that screenshot, all of its tags: http://i.imgur.com/kbzYCbO.png

My content blocking settings are as before: http://i.imgur.com/m2UZnao.png

Should this bug be closed/marked as in progress and a new post made for this issue? (which is related but separate).

**Comment by verenion** [comment]
Assigned PT#151086280

**Comment by mrmason** [comment]
We're still working on this one - there is a problem when adding/removing tags not correctly being purged from the cache.

**Comment by mrmason** [comment]
We've pushed some fixes towards this and are testing it internally - please can you take a look on your end and see if it's working as you'd expect ?

**Comment by ousnius** [comment]
It works fine for me with Nazenn's links and with my profile's different list of files.
