### ISSUE TITLE
Emoticons don't work even if Box is Ticked

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#220]
On any Nexus New Format mod page, entering the emoticons we have been using for years doesn't work. Examples I tried tonight include :D, :woot:, :laugh:, :sad:.

Once submitted, the editor is stripping the emoticons from the posted text.

**Comment by verenion** [comment]
Assigned PT#152346055

**Comment by verenion** [comment]
Push has been pushed for this.
