### ISSUE TITLE
Searching - If search is invalid, search box returns to default

### ISSUE THREAD

**Issue by DonQuixoteIII** [Nexus-Mods/web-issues#221]
Let's say I search by author, and misspell, getting no results.  The search box resets to blank, type mods.

What I would expect to see is the search box with my original search variables still visible until I clear them.

**Comment by mrmason** [comment]
Assigned `PT#152311431`

**Comment by mrmason** [comment]
This has been implemented.

**Comment by DonQuixoteIII** [comment]
Thank you.
