### ISSUE TITLE
Unable to delete videos 

### ISSUE THREAD

**Issue by Feradiera** [Nexus-Mods/web-issues#223]
Like the title says, I cannot delete videos I have uploaded on my mod page. I have tried from several different places to delete it, the page asks if I am sure, I click yes/okay, but the video is still there after refreshing.

**Comment by mrmason** [comment]
Please can you provide us with a link to the mod this is happening with ?

**Comment by Feradiera** [comment]
sorry, here you go: https://rd.nexusmods.com/witcher3/mods/498

**Comment by mrmason** [comment]
Assigned `PT#152311387`

**Comment by iamtiz** [comment]
Fixed
