### ISSUE TITLE
Image thumbnails do no display during initial page composition 

### ISSUE THREAD

**Issue by mlandstreet** [Nexus-Mods/web-issues#225]
You get a placeholder for the image thumbnails on the mobile site until you view the images. This makes it very difficult to select which images you want to view.

**Comment by mrmason** [comment]
Hey, please can you provide the steps to produce this and/or a screenshot to show us what you're seeing ?

**Comment by mlandstreet** [comment]
It will be a little while but yes I will. 
Sent from my 4G Android Device


-------- Original Message --------

**Comment by mlandstreet** [comment]
On a mod page in the mobile site (I was in Skyrim SE) select images from the dropdown and it shows nexus logo placeholders for the thumbnails. If I select an image to view, the image viewer tool launche's and I can see images. When I exit the image viewer tool the thumbnails are properly populated. I have a screen shot but have no clue how to attach it to this message from my Android mobile.

**Comment by mlandstreet** [comment]
Refreshing the page takes you to the description page where the process repeats. I am using the default Samsung (Chrome based) browser.

**Comment by mrmason** [comment]
I'm afraid I'm not seeing this on any device I've tested with.

The way we're doing things is that the nexus logo is behind every image - so that if an image fails to load then you'll see the nexus logo.

So if you're seeing the nexus logo, it's actually just the background of where the image should be. 

Are you testing this on wifi or mobile network ? Have you tried it on the opposite of this ?

I'll ask some more people to test as well.

**Comment by Thallassa** [comment]
I think android data saver feature can cause this.

**Comment by mlandstreet** [comment]
I have that turned off. I am on an old unlimited data plan from before restrictions. 
Sent from my 4G Android Device


-------- Original Message --------

**Comment by mrmason** [comment]
Do you have any other mobile devices you can compare with ? We've had around 10 people test this on their end and so far can't replicate the problem.

Also, possibly - could you try another browser on your phone just to see if it makes a difference ?

**Comment by mlandstreet** [comment]
I will try a different browser and try this on Wifi as well once I get home and get settled. It may be 2 or 3 hours before I will be able to get to it
Sent from my 4G Android Device


-------- Original Message --------

**Comment by mlandstreet** [comment]
On my Samsung Galaxy Note 4 (Marshmallow) using the latest "Samsung Internet" Chrome based browser the images do not show up until after one is accessed even on my 130 Mb/sec WiFi, The images do, however, show up when using FireFox.

On my Galaxy Note 10.1 (2012) with Android 4.1 using the default Samsung Browser the preview images, which I did not even know existed on mobile until I saw them on this device, on the description page show up. However choosing images in the dropdown renders a static version of the gear and the images nor their frames or data ever appear,

Let me know if you need more information or I need to test further.

Thanks,
Mason
