### ISSUE TITLE
Going to the next page on mod comments doesn't scroll up.

### ISSUE THREAD

**Issue by restcoser** [Nexus-Mods/web-issues#228]
On the old design, when clicking the next page of comments, it would start over from the top. 
In the new design, it doesn't seem to do this (but it does scroll up for opening the next page of mods)

So if I want to read the comments I have to:
1.Read the comments of the 1st page
2.Click the 2nd page-button
3.Scroll up manually to view the first comments of the 2nd page...
and so on.

With the old design, step 3 is not required.

**Comment by GrantSP** [comment]
TBH this behaviour was evident in the old design too. (Windows 10 with Chrome)
Checking this on another browser (Edge) the old design did indeed refresh the page to the top so it is clearly a browser specific error.
Now regardless of the browser it does as the OP details.
I'd regard this not as an "Enhancement" but rather a bug.

**Comment by iamtiz** [comment]
fixed
