### ISSUE TITLE
Gift Supporter Status

### ISSUE THREAD

**Issue by Kiyozz** [Nexus-Mods/web-issues#229]
URL: https://rd.nexusmods.com/users/myaccount#TODO-donation-popup
Bug/error being reported: `BBoC-1509047537.js:2474 Uncaught TypeError: Cannot read property 'ImportFrom' of undefined
    at BBoC-1509047537.js:2474`
Steps to reproduce: Go to profile, click on "gift supporter status"
Expected result: I don't know
Actual result: Nothing

**Comment by verenion** [comment]
Assigned PT#152349805

**Comment by verenion** [comment]
This button has been removed, as it was left over from the design.
