### ISSUE TITLE
Page scroll on opening an issue on the bug tracker

### ISSUE THREAD

**Issue by shadeMe** [Nexus-Mods/web-issues#23]
URL: All "Bugs" tabs (example: https://rd.nexusmods.com/oblivion/mods/36370/?tab=bugs)
Bug/error being reported: On opening an issue for the first time, the vertical scroll of the page randomly changes. Subsequent activations don;t have this issue.
Steps to reproduce: Click on any of the items in the "Bugs" tab after the page is loaded for the first time.
Expected result: I believe the intention is to scroll to the first post of the issue should it fall outside the viewport.
Actual result: Vertical scroll overshoot.

**Comment by verenion** [comment]
Assigned PT#150847789.

Fix has been pushed.
