### ISSUE TITLE
endless load screen 

### ISSUE THREAD

**Issue by Norstaera** [Nexus-Mods/web-issues#230]
URL:  https://rd.nexusmods.com/dragonage/mods/4772?tab=files (any mod, really)
Bug/error being reported:  Only happens in Internet Explorer, not Edge, Chrome, or Mozilla. I go to a mod, but when I want to leave the description tab for files, images, posts, etc. I only see the loading screen icon unless I manually refresh the page.
Expected result: immediately go to new tab
Actual result:  have to to do manual refresh to see new tab

**Comment by verenion** [comment]
Assigned PT#152346733

**Comment by verenion** [comment]
This issue should be resolved.
