### ISSUE TITLE
Images cut off on new website design, ruins image for certain mods. 

### ISSUE THREAD

**Issue by TwistedChance** [Nexus-Mods/web-issues#231]
URL: https://rd.nexusmods.com/fallout4/mods/27551
Bug/error being reported: When click on image to show zoomed in, the shitty image montage bar cuts off the bottom 1/4th of image which happens to contain the part of image I am interested in for this particular mod. 
Steps to reproduce: Go to link, click images and click on first image and watch as you cant see the UI part of this UI mod in zoomed in image because the shitty image slideshow below overlaps it.
Expected result: Main image should resize so the shitty image slideshow bar doesn't block part of image.
Actual result: Shitty Image slideshow sits directly ontop of the main image causing entire bottom 1/4th of image to be blocked. Which makes it impossible to see the UI part of this particular mod encountered error on.

**Comment by iamtiz** [comment]
There's a button on the bottom-left of the screen which toggles off or on the preview bar
