### ISSUE TITLE
[Request] Bring back "Files that require this file"

### ISSUE THREAD

**Issue by janowitzivo** [Nexus-Mods/web-issues#233]
[image](https://i.imgur.com/16grfKK.jpg)
X-post from [reddit](https://www.reddit.com/r/skyrimmods/comments/792i9g/can_you_find_other_mods_that_use_the_mod_that/)

Would help to see what mods for example are supported by FISS/have patches for it.

**Comment by verenion** [comment]
Assigned PT#152349049

**Comment by StochasticTinkr** [comment]
I was just about to request this.

Idea for the feature: Include some quick stats before I click on the icon: "Requires 3. Required by 55" etc... Shorthand would be nice.

**Comment by iamtiz** [comment]
Fixed, we added the "Files that require this file" list to the Requirements expander in the mod page
