### ISSUE TITLE
[REQUEST] Make dropdowns use theme colors

### ISSUE THREAD

**Issue by mouse0270** [Nexus-Mods/web-issues#234]
So if you are browsing mods, the "Select" dropdowns on pages show the default blue color instead of the theme color of the site (e.g. green for Fallout 4). It would be nice for this all to flow and show the same theme color. 

It's a small tweak that can be done in CSS alone rather quickly, so I thought I would bring it your attention.

**Comment by iamtiz** [comment]
assigned #155431702

**Comment by iamtiz** [comment]
fixed
