### ISSUE TITLE
Add short Mod Description on Mouse-over

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/web-issues#235]
On the main page of a game the hot files are completely missing a description forcing users to actually visit the mod page just to understand what it is about wasting a lot of time. This applies also to the mod browsing section where the description is indeed present but cut very short by the fading out and more often than not it isn't even enough to finish the sentence. This is a major step back from the old site where one could browse hundreds of mods very quickly without having to open the mod page just to see what it is about. The faded description is welcome and a huge help for mobile users but if you are browsing for mods you are typically on your computer and not being able to just read the complete short description is very frustrating. This seemingly little detail is just enough to not consider using the new leyout.

**Comment by Eolhin** [comment]
I agree, a mod description on mouse-over is really needed.

**Comment by Greg-Nexus** [comment]
This suggestion is being closed and moved to our Feedback tracker: https://feedback.nexusmods.com/posts/23/add-more-information-to-hot-mods
