### ISSUE TITLE
track author not reporting for image set

### ISSUE THREAD

**Issue by rth119** [Nexus-Mods/web-issues#236]
https://rd.nexusmods.com/skyrim/images/681773
used new site to post this image set but for some reason did not report to track author and never showed up on friends updates.  don't know if this is happening to others or if this was just a one time fluke.  
thank you

**Comment by verenion** [comment]
Is this still happening for you? We have made a lot of changes since you posted this.

**Comment by rth119** [comment]
No not any longer.  I think it was just that one time.  Thanks for contacting.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
