### ISSUE TITLE
Time Range Filter resets if you open next results page.

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/web-issues#237]
In the browse mods page if you select a specific time range through the Date Picker, so that you receive enough results for multiple pages, and procede to select one of the other pages, either by clicking the > button or selecting a specific number, the page will load and then tell you no results where found. Inspecting the time range filter it will show a range between only the years you selected and not the dates. If you re-select the dates the site will actually show the correct results of the second or third or whatever index of result page you were trying to access. Basically the time range filter gets reset after you change result page.

**Comment by verenion** [comment]
Assigned PT#152392057

**Comment by mrmason** [comment]
We've pushed a fix for this.
