### ISSUE TITLE
Description section erroneously parse some characters as smileys.

### ISSUE THREAD

**Issue by Fhaarkas** [Nexus-Mods/web-issues#239]
Bug: Description section erroneously parse some characters as smileys.

Steps to reproduce: Have a "\D" string somewhere in the body. Eg. "Skyrim\Data\Meshes"
Expected result: "\D" not turned into smiley.
Actual result: "\D" turned into smiley. :)

Screenshot:
![screenshot 131](https://user-images.githubusercontent.com/10703185/32115723-7e1525f0-bb7a-11e7-9533-bc4bead0b2f5.PNG)

**Comment by alfx3** [comment]
URL: https://rd.nexusmods.com/skyrim/mods/86946
Bug/error being reported: smileys are improperly used in mod text.
Steps to reproduce: write `"D` in a mod long description.
Expected result: `"DOWNLOAD WITH MANAGER"` properly displayed.
Actual result: `"DOWNLOAD WITH MANAGER"` first D turned into a smile.

**Comment by verenion** [comment]
This was related to another issue that was fixed. Should be resolved now.
