### ISSUE TITLE
Can't enter version number bugs were fixed in.

### ISSUE THREAD

**Issue by Reaperrz** [Nexus-Mods/web-issues#24]
Bug/error being reported:
When picking options from the "Change status" menu for listed bugs, the version field is not accessible until confirming and then re-opening the menu again.

Steps to reproduce:
Simply click on "Change status" for a bug, select "Fixed" and you can't enter anything into the version number field.

Expected result:
Actually being able to enter the number.

Actual result:
Fuck-all. :D

**Comment by Pickysaurus** [comment]
I have replicated this, I have to set a new status, then update it again to add a fixed version number.

**Comment by iamtiz** [comment]
Assigned PT #151002292

**Comment by iamtiz** [comment]
This should now be fixed
