### ISSUE TITLE
Missing way to approve all user images at once

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#240]
On the old site, the user images tab of your mod pages let you approve all pending user images at once, so that you don't have to click them manually one by one.

On the new site, this feature currently seems to be missing.
https://rd.nexusmods.com/fallout4/mods/edit/?step=media&id=MOD_ID_HERE&game_id=1151

**Comment by verenion** [comment]
Assigned PT#152399611

**Comment by iamtiz** [comment]
Added a button to approve all images
