### ISSUE TITLE
wrong file size shown in some cases

### ISSUE THREAD

**Issue by Hilli1** [Nexus-Mods/web-issues#241]
The shown file size in the main window is wrong sometimes. I assume the file size from the first uploaded file is shown, not from the main file as it should. 

Example: https://rd.nexusmods.com/skyrimspecialedition/mods/12928? 
The shown file size here is 1 kb like the optional file which I uploaded first. However the right number is 5,9Mb in this case.

**Comment by verenion** [comment]
This seems to be showing correctly for me.

**Comment by Hilli1** [comment]
Browse the files and you will see on the main page next to endorsements and downloads the filesize. In the example above you see there 1kb and not 5,9mb.

Next example:
https://rd.nexusmods.com/skyrimspecialedition/mods/12930?

main file size: 4.0mb
optional file size: 1kb

shown file size on main page: 1.3mb

**Comment by Thallassa** [comment]
I can replicate this. 

In search:

![image](https://user-images.githubusercontent.com/11600099/32182462-2298253e-bd6d-11e7-82c3-4c2dab067870.png)

actual file sizes:

![image](https://user-images.githubusercontent.com/11600099/32182514-41039bfc-bd6d-11e7-9a6e-e2b3b0494b1e.png)

**Comment by Hilli1** [comment]
Thank you Thallassa. That's what I tried to explain.

**Comment by verenion** [comment]
Assigned PT#152917980

**Comment by Rrrafau** [comment]
We'll probably need to wait until we fully transition to the new redesign so people are no longer able to upload files from the legacy site as this might be a problem with the old system.

**Comment by iamtiz** [comment]
fixed
