### ISSUE TITLE
Missing feature: the personal tag blocking is not available on the new site from the mod filters.

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/web-issues#242]
Bug/error being reported: Missing the tag blocking link directly from the mod file filters section
Steps to reproduce: open a game, go to files, under filters on the new site or in the right column on the old site, the old has a link to personal content filters, while the new site does not.
Expected result: it may be nice to add it back in right under the filter by sliders or the refine with tags section.

**Comment by Thallassa** [comment]
Since it's even easier to get to from the profile I'm not sure there's an advantage in cluttering up search with this.
