### ISSUE TITLE
Adding custom mod requirements doesn't save.

### ISSUE THREAD

**Issue by Saavaas** [Nexus-Mods/web-issues#243]
Bug/error being reported: When trying to add a mod as a requirement it does not save it, the old layout does properly add it.

Steps to reproduce: 
-On your mod go to Manage > Requirements
-Enter a mod under "Required mods on the Nexus" and add it
-Click save at the bottom
-Click view mod page to see result

Expected result: Mod is added to the "Requirements and installation" section

Actual result: Mod isn't added, unless you use the old site

Extra info: After adding the mod using the old site, if you try to add another mod using the new site, it will actually remove the required mods added previously.

**Comment by iamtiz** [comment]
Assigned #152400335

**Comment by iamtiz** [comment]
This is now fixed
