### ISSUE TITLE
Mod Manage Tool

### ISSUE THREAD

**Issue by NexBeth** [Nexus-Mods/web-issues#244]
The old Skyrim Mod Pages has an option in the Admin area of their page which allows the page to  "duplicate to SSE".  This is absent in the new mod author webpage which now has a Manage dropdown menu but no option to duplicate the page over to Skyrim SE.  Very much needed when republishing skyrim mods over to the SSE version.

**Comment by iamtiz** [comment]
Assigned #154248533

**Comment by iamtiz** [comment]
Hi, we have just added back this functionality

**Comment by NexBeth** [comment]
Where is the feature located?

**Comment by iamtiz** [comment]
At https://www.nexusmods.com/skyrim/users/myaccount?tab=files you can either duplicate all of your files or one at the time, using the link in each mod tile (on the right side of each tile)

![screenshot-2018-1-29 my nexus account at skyrim nexus - mods and community](https://user-images.githubusercontent.com/3407947/35510758-4e3c79c6-04f1-11e8-9edd-e2e6a518a24d.png)
 
![screenshot-2018-1-29 my nexus account at skyrim nexus - mods and community 1](https://user-images.githubusercontent.com/3407947/35510808-7acfa35a-04f1-11e8-956d-d925c8e1667c.png)
