### ISSUE TITLE
Cannot print

### ISSUE THREAD

**Issue by bhorton22** [Nexus-Mods/web-issues#245]
Bug/error being reported: I usually save a printout of the web page of any mod I download. That way when I load it I have a description of what is needed, what the mod does and any restrictions the author had on the mod (sometimes it can be a while before I load a mod in a play through and the mod has gone from the nexus). In the new format, using either Firefox or Chrome you cannot print the web page to any Microsoft product (you can with the old format).
Steps to reproduce: In Chrome or Firefox click print and print the web page to Onenote or Word. The output is just the first page.
Expected result: Should get the full web page
Actual result:Just get the first page.

**Comment by Pickysaurus** [comment]
If you're using Windows 10's edge I think the annotate option will save the entire page. Or even snipping tool has similar functionality

**Comment by verenion** [comment]
As far as I can see, the RD site behaves in a similar way when printed to the old site and neither are something we are probably going to support. Will put an issue in the icebox to maybe look at this in the future.
