### ISSUE TITLE
Suggestion: User Images for mod images support tag like voting

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/web-issues#247]
Bug/error being reported: A suggestion instead of a bug.
With the new automatic use of user images for the preview when a mod doesn't have its own image, I feel that there should be a way to mark images (similar to how tags work) as inappropriate. I have found a few mods that have a nude character in the image, but the mod doesn't have anything to do with nudity.

**Comment by iamtiz** [comment]
Assigned #155936767
