### ISSUE TITLE
can't see the exact number of downloads when number of downloads exceeds 1.000

### ISSUE THREAD

**Issue by Hilli1** [Nexus-Mods/web-issues#248]
Can't see the exact number of downloads on my mod page when the number exceeds 1,000 downloads.

Example: https://rd.nexusmods.com/skyrimspecialedition/mods/11559?

old page: 2,872 Unique D/Ls and 5,671 Total D/Ls 

new page: Unique DLs 2.9k and Total DLs 5.7k

**Comment by mrmason** [comment]
Duplicate of #199
