### ISSUE TITLE
Read notifications

### ISSUE THREAD

**Issue by zwazo** [Nexus-Mods/web-issues#249]
I understand you made it this way (more generic) due to the color that change depending on which game space you are, but the greyed text on grey background is not friendly to me ... almost impossible to read without touching the screen with my nose.

Would you mind to :
- not opacify the whole bloc , only the image
- change the link color for something more greyish

Or use different a background to give more contrast ?

**Comment by yggdrasil75** [comment]
Is this on the new site or the old site? If it is on the old site then I recommend trying the new site.

**Comment by zwazo** [comment]
On ne new site

**Comment by iamtiz** [comment]
assigned #155431732
