### ISSUE TITLE
The file options under the "Edit details" option are not working.

### ISSUE THREAD

**Issue by Reaperrz** [Nexus-Mods/web-issues#25]
Bug/error being reported:
I set it so my files would not have the "Download with manager" button, but it kept resetting and appearing nonetheless. I don't think it worked even when uploading a new file, but I'm not 100% sure of that.

Steps to reproduce:
Just hover over Manage and then "Edit details" on a file. Setting the Download with manager setting or the show file requirements option does not do anything.

Expected result:
To actually remove the Download with manager button and to show file requirements on download.

Actual result:
Diddly-fucking-squat. :D

**Comment by Rrrafau** [comment]
assigned #151003976

**Comment by iamtiz** [comment]
Fixed. Reopen in case there are still issues.
