### ISSUE TITLE
User Files Tab does not show any files

### ISSUE THREAD

**Issue by necropola** [Nexus-Mods/web-issues#252]
Steps to reproduce: https://rd.nexusmods.com/skyrimspecialedition/users/1046420?tab=user+files
Expected result: There should be 18 files
Actual result: There are none

Obviously the "Game" dropdown isn't properly  initialized. It was showing "Skyrim Special Edition", but the filter was thinking something else ... After explicitly selecting a game, the files did show up.

**Comment by Fhaarkas** [comment]
Clicking your link brings me to SSE page with 15 files displayed (correct).

Loading [this link](https://rd.nexusmods.com/users/1046420?tab=user+files) brings me to the general page with all 18 files displayed.

I'm on Firefox 57.

**Comment by necropola** [comment]
It seems that it sometimes works and sometimes just not. Try in a fresh session (cleared cache) and try it a few times.

**Comment by mrmason** [comment]
Can you provide a screenshot of what you're seeing please when it doesn't work ?

**Comment by necropola** [comment]
I fail to make it happen again. Maybe it's not a bug in the frontend but was a problem in the backend, i. e. XHR running into a timeout. I remember seeing the spinning gear for a while when it didn't return any records.

**Comment by mrmason** [comment]
It sounds like there was a timeout problem before - which is very possible as we're still working on the search system. Hopefully this won't be a problem going forward.

The site was slow earlier due to an incoming DDoS attack - it should be back to normal now.
