### ISSUE TITLE
Users Can't Delete Their Own Erroneous or Redundant Posts

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#257]
Bug/error being reported: Users are unable to delete their own posts or replies from a mod forum
Steps to reproduce: Try to delete an erroneous or duplicate post or reply you have made on a forum page
Expected result: There is a Delete button or link and the post/reply disappears
Actual result: There is no "Delete" functionality for users- only for mod authors

**Comment by rscottexe** [comment]
This is neither missing functionality or a bug.

This functionality does not exist on the current site, so it won't exist on RD either. Please only report missing issues from the previous site or actual bugs.

Thank you.

**Comment by Vyxenne** [comment]
Firstly, nowhere that I can find does it say not to post problems if they already exist in the old system.
Secondly, what is the point of a new design if the intent from the very beginning is to explicitly avoid improving upon existing functionality by shutting out any such requests?
And lastly, at least a third of the open issues are enhancement requests. Why would you close my issue out of hand instead of converting it to an enhancement request using whatever functionality with which you so easily applied the INVALID label to it?

**Comment by rscottexe** [comment]
This is a bug tracker, which specifically says this system is for bugs. Similarly, the news post said this:

> Right now, for the initial launch, we're only interested in ensuring we're providing the same or similar functionality as the current site. You will find we've added some minor changes and updates in functionality we think might help you while browsing the site, but what we're mainly interested in right now is in comparing the functionality on the old site to the functionality on the new site and ensuring it works as well as or better than it did before. Similarly, we want to make sure we have not missed any functionality out that is currently available on Nexus Mods. These are the two main things we'd like to know most about and what will help us.

It also said this:

> Please only use GitHub to report bugs or inform us of missing functionality compared to the current site. Please don't use it to ask for new features or things that don't exist on the current site. We'll try and keep the issue tracker as clean as possible, so some issues may be removed if they are not relevant to the redesign at this time. Thank you for your understanding.

So it was definitely said in several locations.

I have closed this issue rather than making it an "Enhancement" because this isn't a feature we plan to implement and I do not want the programmers getting confused and thinking it is. We willfully do not allow users to delete posts they've made from the site out of conscious design.

If you need a post moved, deleted or otherwise please use the report functionality and a moderator will action your request if appropriate.

Thank you.

**Comment by Vyxenne** [comment]
I apologize for not seeing the article you quoted. Based on that, I just closed some other issues I had opened because they also exist in the old systrem.

I'm sure you'll let us know when and how we can provide feedback/feature requests for the new system since it is being designed to mimic the old system, warts and all. Thanks.
