### ISSUE TITLE
Suggestion for site - compatible game version

### ISSUE THREAD

**Issue by ErusPrime** [Nexus-Mods/web-issues#258]
Nexus Mods is great but it's missing a few things that make it the best. There should be a searchable way to eliminate deprecated or outdated mods by having a field for the game version it's compatible with. As an extension to that, the primary compatibility could be set by the author but have additional compatibility tags as set by the author or users who are playing on a specific version. I would suggest making this a required field to help reduce problems that arise from mods that just stop being developed.

**Comment by Vijabei** [comment]
Also reporting outdated mods should be possible and translations should be removable by the main mod author (until uploading a new version by translator). Deleting the mod after a period of time with the chance to keep the mod up for the author, when replying to an information mail about upcomming deletion.

=)

**Comment by iamtiz** [comment]
This will be added later when we overhaul mods, but not as a matter of priority

**Comment by Interinactive** [comment]
+1

MGS: The Phantom Pain, Kingdom Come and GTAV are prime examples of games that would benefit from this.

Using MGS as the example - most of the bigger 'top' mods aren't compatible with the latest game version, and you have to go through descriptions, bug reports etc to see if it'll work anyway. A cleaner way to browse for usable mods would be to add such a feature. Modders could add a version and then a filter could be used to browse through those versions.
