### ISSUE TITLE
missing feature: The Image for the mod being referenced in a notification does not show.

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/web-issues#259]
Bug/error being reported: From GOLDENTRIANGLES via Discord: the image for the mod being referenced in a notification does not show on the new site, while I personally don't care either way, GOLDENTRIANGLES believes that the feature should remain.

**Comment by iamtiz** [comment]
Hi, could you provide a couple of examples of such notifications? They should contain the mod image
