### ISSUE TITLE
Mod Names Inappropriately Forced to All Upper Case

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#260]
Bug/error being reported:Mod Names are being forced to all upper case
Steps to reproduce:Visit any mod page in old and new format
Expected result:Mod name capitalization should be as mod author intended
Actual result:Mod names entered as mixed case are being forced to upper case
See Old Format vs. New Format attachments- Mod author made a play on words when he named his mod "Flower Girls SE x" but the RD format has destroyed his wordplay by forcing it to appear as "FLOWER GIRLS SE X."

![fg banner-oldformat](https://user-images.githubusercontent.com/33111596/32139742-419df5f4-bc18-11e7-8d02-76ce6d488549.png)
![fg banner-newformat](https://user-images.githubusercontent.com/33111596/32139744-45370692-bc18-11e7-8f54-302292b657f2.png)

**Comment by verenion** [comment]
This isn't a bug, but a conscious design decision.
