### ISSUE TITLE
Cannot vote for the file of the month on the new site.

### ISSUE THREAD

**Issue by WDoubleYouW** [Nexus-Mods/web-issues#262]
Bug/error being reported: You cannot vote for a file of the month on the new site.
Steps to reproduce: Visit a mod page such as SkyUI https://rd.nexusmods.com/skyrimspecialedition/mods/12604
Expected result: There should be a button, used to be near the Endorse button, to vote for this file as file of the month.
Actual result: No such button exists, and the functionality is missing.

**Comment by Thallassa** [comment]
Can confirm, the vote button used to be there but it's disappeared now.

**Comment by verenion** [comment]
Assigned PT#152395590

**Comment by Thallassa** [comment]
Ok I think I did something stupid. I can see the vote button again now o.O

**Comment by WDoubleYouW** [comment]
After using the new site more, I think this is intentional. SkyUI, the mod I posted, had already been file of the month, so you can't vote for it. I had looked at a mod that I had not downloaded, and typically the vote button was there on the old site. I now see that you cannot see the vote button until you have downloaded it. And naturally, I had little reason to look at the page of a mod I had already downloaded, until on a hunch I checked just now, and it was there for a mod I had downloaded but never voted for.

**Comment by WDoubleYouW** [comment]
This is fixed and improved now, so it can be closed.
