### ISSUE TITLE
Manage mod page header does not change on navigation

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#263]
Bug/error being reported: Manage mod page header does not change on navigation
Steps to reproduce:
1. From mod page manage menu open manage page (for example documentation)
2. Click on other tab/bullet (for example Media)

Expected result: Edit Slots Slots SLOTS: Media
Actual result: Edit Slots Slots SLOTS: Documentation 

![nexuserror2](https://user-images.githubusercontent.com/33193255/32174957-01400fa4-bd8c-11e7-8d36-e5422487a9d2.png)

**Comment by verenion** [comment]
I've checked these tabs and they seem to be working correctly. I don't understand you expected results and actual results though. Could you provide more information?

**Comment by Zur13** [comment]
I've attached screenshot which shows that Manage files tab is currently selected but the header shows "EDIT SLOTS SLOTS SLOTS: MEDIA"

**Comment by verenion** [comment]
Ah, I see this now.

Assigned PT#152404088

**Comment by verenion** [comment]
Fix has been pushed.
