### ISSUE TITLE
This is a new version of an existing file flag removes previous version

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#264]
Bug/error being reported: This is a new version of an existing file flag removes previous version
Steps to reproduce: 
1. From mod Manage menu go to Manage files page
2. Prepare file upload and check "This is a new version of an existing file (optional)" checkbox
3. Click SAVE FILE button

Expected result: previous version placed under Old versions category
Actual result: previous version removed completely

Old site gives an option to remove or to place under Old versions.

**Comment by iamtiz** [comment]
fixed a while ago
