### ISSUE TITLE
Posts page manage menu items too small

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#265]
Bug/error being reported: Posts page manage menu items too small and easy to miss click 
Steps to reproduce:
Expected result: Highlight menu item under mouse cursor or add more vertical space between menu items
Actual result:

There was no such problem on old site because post controls was not grouped in menu.

**Comment by iamtiz** [comment]
assigned #155431755

**Comment by wills661** [comment]
Have found my account but still cannot sign in to the game. I have tried to make a new account with Nexus using my original account But nexus just says that account is already taken, There is noway that they will listen when i try to tell them it is my Account. any help would be much appreciated.

**Comment by iamtiz** [comment]
Fixed
