### ISSUE TITLE
Edit post link should be placed near other post control buttons

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#266]
Bug/error being reported: "Edit post" link should be placed near other post control buttons like Manage, Report, Reply
Steps to reproduce:
Expected result: "Edit post" link should be a button near other post control buttons like Manage, Report, Reply
Actual result: "Edit post" link placed under the post text and it hardly visible

**Comment by iamtiz** [comment]
Assigned #161626166

**Comment by iamtiz** [comment]
Done
