### ISSUE TITLE
It is not possible to filter/sort bug reports

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#268]
Bug/error being reported: It is not possible to filter/sort bug reports
Steps to reproduce:
Expected result: Filter out/sort bug reports from all pages
Actual result: No way to sort/filter bug reports from all pages

Old site allowed to filter bug reports by type and by priority and allowed bug reports sorting, new site allows only to sort bug reports on current page (it is a problem when you have more than one page with bug reports).
Browser Firefox 56.0.2 x64

**Comment by Thallassa** [comment]
#94
