### ISSUE TITLE
Deleted comments still counted

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#27]
URL: https://rd.nexusmods.com/fallout4/mods/23700?tab=posts

All comments deleted, but still show in the post  count.

**Comment by mrmason** [comment]
This is due to caching - the post counts only get refreshed every few minutes - so they aren't live. 

I'll assign a job to try and bust the cache when posts are deleted.

`PT#150851018`

**Comment by PoorlyAged** [comment]
Here is a little insight.  URL: https://rd.nexusmods.com/fallout4/mods/23481?tab=posts

The posts tab says (8), gut the header says 11 comments.  The eight is correct.

**Comment by iamtiz** [comment]
This is now fixed, and the behaviour should be the same as the live website
