### ISSUE TITLE
Documentation - Changelog Link to Example Broken

### ISSUE THREAD

**Issue by TechAngel85** [Nexus-Mods/web-issues#271]
The link to the example changelog (when editing documentation) is broken. It simply links to the top of the current page.

**Comment by verenion** [comment]
Have you got any sort of javascript blocker enabled? Is javascript enabled?

That link should open a popup showing you the readme in a modal window.

**Comment by TechAngel85** [comment]
I do not. I've tested it using the latest version of Firefox and Chrome. uBlock and HTTPS Everywhere are disabled in FF for Nexus. The resulting link is: https://rd.nexusmods.com/skyrimspecialedition/mods/edit/?id=11583&game_id=1704&step=docs#

**Comment by TechAngel85** [comment]
@Zur13 Same result. No popup. I have the same version of FF. Only difference is I'm on Windows 7. I've now tested it for IE, Chrome, and FF. None of them are producing a popup when clicking the link. The link just takes me to the top of the page as if it's an anchor.

I don't have any background software running that prevents popups nor javascript from running. I have the latest version of Java installed. Using MSE as my antivirus.

**Comment by TechAngel85** [comment]
I've examined it in Inspector and the link is just an anchor on my end:
`<a href="#">nicely formatted Changelog</a>`

**Comment by Zur13** [comment]
Sorry, I've thought about Readme example for some reason.
Yes, I can confirm changelog example link is broken Firefox 56.0.2 x64 Windows 10.
Link to readme example looks fine and works as it should:

`<a href="/Core/Libs/Common/Widgets/ReadmeExample" class="popup-btn-ajax">good example</a>`

And link to changelog example looks like page anchor 

`<a href="#">nicely formatted Changelog</a>`

**Comment by mrmason** [comment]
Assigned `PT#152432310`

**Comment by verenion** [comment]
We have removed this link, as it was a remnant from the design.
