### ISSUE TITLE
"Remove download with manager" option not working.

### ISSUE THREAD

**Issue by ModdedMeghan** [Nexus-Mods/web-issues#274]
Bug/error being reported: The remove download with manager option doesn't work.

Steps to reproduce: Tick the "remove download with manager" option in the file options for a mod and click save at the bottom of the page

Expected result: The download w/manager button will be removed.

Actual result: It remains

Reverting to the old layout and removing the download w/manager button seems to work just fine still.

**Comment by mrmason** [comment]
Assigned `PT#152432201`

**Comment by iamtiz** [comment]
Hi, I'm not able to reproduce the issue. Which one is the affected mod?

**Comment by ModdedMeghan** [comment]
I had it happen on these mods
https://rd.nexusmods.com/fallout4/mods/27602
https://rd.nexusmods.com/fallout4/mods/27554/?

It's probably worth mentioning this didn't happen on the initial upload as I only tried to remove the download with manager button a couple days later when it suddenly occurred to me it didn't really make sense for a modder's resource to have one.

Also I'm using Firefox. Don't know if that actually matters or not but I thought I would mention it in case.

**Comment by iamtiz** [comment]
Fixed
