### ISSUE TITLE
Using Twitter Button in WYSIWG Editor Displays Generated BBCode Instead

### ISSUE THREAD

**Issue by PurpleDerpleOMG** [Nexus-Mods/web-issues#275]
Bug/error being reported: Using the Twitter Button in the WYSIWG Editor displays the generated BBCode on the page
Steps to reproduce: 

1. From User Profile page, click on "Edit My Profile" 
2. Click "Edit my About Me page" button in the Profile Settings tab
3. Click Twitter icon button in WYSIWYG editor, and enter a Twitter username in the dialogue box.
4. Click on "Okay" to close the dialogue box then on "Finish & Save" to close the WYSIWYG editor
5. Return to profile using the new design.

Expected result: Username text with "@" prefix linked to Twitter profile

Actual result: BBCode for the Twitter link will be displayed in the text (works properly in old layout)

**Comment by mrmason** [comment]
Assigned `PT#152432222`

**Comment by verenion** [comment]
Fix has been pushed.
