### ISSUE TITLE
Suggestion: Hide NSFW thumbnails if you are not logged in

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/web-issues#276]
Bug/error being reported: NSFW mods thumbnails showing even if I'm not logged in
Steps to reproduce: Visit a game-specific page (in my case Skyrim SE)
Expected result: Hidden NSFW thumbnails if not logged in (and if NSFW mods are toggled in)
Actual result: NSFW mods thumbnails showing even if I'm not logged in

I know, there's always that one guy that wants to hide NSFW images but I want to be free to visit the website even when I'm surrounded by people watching in my laptop screen. It would be nice having a toggle in the top bar too so that I can show/hide NSFW content on will

**Comment by mrmason** [comment]
To the best of our knowledge the settings are the same on both sites.

Comparing

https://www.nexusmods.com/skyrimspecialedition/images/view/?
to
https://rd.nexusmods.com/skyrimspecialedition/images/

as a non logged in user yields the same results.

I can understand that people may want a NSFW toggle - it's something we've discussed but it's non-trivial.
