### ISSUE TITLE
Pressing 'back' on a paginated page takes you to the same page.

### ISSUE THREAD

**Issue by mrmason** [Nexus-Mods/web-issues#278]
1) Goto https://rd.nexusmods.com/mods/popular/?nav=1&page_size=20
2) Click '3' from pagination
3) Click 'back' in browser

It just re-loads page 3 - I'd expect it to load page 1

**Comment by mrmason** [comment]
Assigned `#152394168`

**Comment by Pickysaurus** [comment]
We're unlikely to fix this (if it's still an issue).
