### ISSUE TITLE
Browse all mods page does not remember last used sort criteria

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#279]
Bug/error being reported: Browse all mods page does not remember last used sort criteria
Steps to reproduce:
1. Go to mods list using menu MODS->Browse all mods
2. Select Endorsements in Sort By combo box
3. Once again go to mods list using menu MODS->Browse all mods

Expected result: Mods list is sorted by Endorsements
Actual result: Mods list is sorted by Date published

Old site preserve previous mods sorting selection when revisited.

**Comment by mrmason** [comment]
If I goto https://www.nexusmods.com/games/mods/searchresults/? and change the sort method - then I goto another page and then go back to that page again ( files > browse files ) the filters are not persistent. 

Is there somewhere I'm missing that has persistent filters on the current site ?

**Comment by Zur13** [comment]
Oh, my bad. I thought second sorting option by endorsements on old site was selected after page reopen because I've selected it before.

In this case the new site should also sort mods by Endorsements by default.

**Comment by mrmason** [comment]
If you check this page - https://rd.nexusmods.com/users/myaccount

You should be able to set your preference for the search results.
