### ISSUE TITLE
Wrong tooltips for certain buttons

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#28]
The buttons on images that let you approve, delete, crop the images and more show two types of tooltips, one of which is wrong. There are probably more buttons all over the site that share the same symptoms (?).

**2 on the image:**
One type of tooltip appears when you hover your mouse over the tick or cross symbols, which says "Tick" or "Cross". These shouldn't exist.

**1 on the image:**
The other, correct type of tooltip appears when you hover your mouse over the button area behind the symbols. This one should always appear.

![Missing Tooltips](https://i.imgur.com/BJ2SOoa.png)

**Comment by ousnius** [comment]
Additionally, I just realized by looking at the screenshot again, the delete button should probably not be inside of the image when approving user images for mod pages.

**Comment by iamtiz** [comment]
Assigned task #151051019

**Comment by iamtiz** [comment]
Fixed the tooltips
