### ISSUE TITLE
Documentation and Permissions tab radio buttons empty while those tabs have content

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#281]
Bug/error being reported: Documentation and Permissions tab radio buttons empty while those tabs had mod content on Edit mod screen
Steps to reproduce:
1. Edit mod which has some changelog entries and custom permissions using menu command Manage->Mod details

Expected result: Tab bullets for Documentation and Permissions filled white because both tabs have content
Actual result: Tab bullets are not filled and shown inactive

Documentation tab shown inactive
![nexuserror4](https://user-images.githubusercontent.com/33193255/32179854-1bfe7efe-bd99-11e7-852e-e8cdee258afc.png)

But it has some changelog entries
![nexuserror5](https://user-images.githubusercontent.com/33193255/32179915-3e43b45c-bd99-11e7-8bde-e4bece5dda31.png)

**Comment by mrmason** [comment]
Assigned `PT#152409316`

**Comment by giftfish** [comment]
I can verify this. Seems to happen with Media, as well. 

To be clear, the buttons will be filled IF you access from Manage directly. It's crossing between categories once inside the Manage interface that creates the problem.

**Comment by verenion** [comment]
I can't seem to replicate this. If I click Manage>Permissions, the radio tabs are correct, and if I edit something and click on another tab, the radio buttons are still correct. Am I missing something?

**Comment by Zur13** [comment]
Documentation tab seems to be fixed recently at least I could not reproduce it again. But the Permissions tab is still broken:

It is displayed inactive:
![nexuserror9_1](https://user-images.githubusercontent.com/33193255/32453366-a7c76eec-c324-11e7-9b9a-261f5b43d080.png)

But there is custom permissions set:
![nexuserror9_2](https://user-images.githubusercontent.com/33193255/32453380-b3d5938a-c324-11e7-8ae3-43ea051ba75d.png)

**Comment by verenion** [comment]
Assigned PT#152633511

**Comment by iamtiz** [comment]
Fixed

**Comment by giftfish** [comment]
Definitely fixed. Thanks!
