### ISSUE TITLE
User uploaded images to mod page: Crop, edit, and make banner buttons visible

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#282]
Bug/error being reported: On images you have uploaded to a mod page, the crop, edit, and make banner buttons are visible. 

When you click on "edit image title" you get "You do not have the required permissions to perform this action."

When you click on "crop" or "make banner", you get an "access denied" error. 

(PS the access denied error is full screen width, similar to #238). 

Clicking on "remove this image" works as expected. 

![image](https://user-images.githubusercontent.com/11600099/32185264-0f981ffe-bd75-11e7-8ae0-d042a7a019b9.png)

Steps to reproduce: Upload an image to any mod you don't own. Several people reported this in the forums already but no one bothered to submit an issue yet. 

On the old site none of these buttons appear - in fact, you don't even have the ability to delete the image like you can on the new site.

**Comment by mrmason** [comment]
Assigned `PT#152410672`

**Comment by iamtiz** [comment]
Fixed. Users are now able to edit the images' names and cropping their thumbnail, as well as deleting them. Only mod authors are allowed to perform other operations.
