### ISSUE TITLE
UI/UX Suggestion: Decrease banner size from 360p full-size to 260p. 

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#286]
Ok I promised to wait on these, but if my math is right this is a relatively small change that would actually help quite a bit in terms of the most common complaint about the website's appearance. (Of course I am underestimating how long it will take to test this change on different screen sizes, if there is no time now just file this issue for later). 

Currently when viewed at maximum website size, the mods banner image is a whopping 360p. This is a big increase from the old site which had it at a tiny 177p. 137p worth of this banner are covered up by useful information, the remaining 223 p (20% of the screen height!) are basically unused. 

This is further exacerbated by the fact that:

- Most mod authors cropped their banner images to exactly the old dimensions (960x177). Many of them look already blurry and ugly even at those dimensions (due to cropping a low resolution image down too much). When increased to 1400x360p they look even worse. 

- The ads also more than doubled in size from 90p tall to 250 p tall. This means that half the screen or more is taken up by just... emptiness. 

- *If* I did my math right the new dimensions should be approximately 1400x260p to keep the same ratios as the old 960x177p banner images. 

I'm not certain how these numbers look at different breakpoints or on mobile. I decided to do my testing at 1080p fullscreen since that is the most common size used among gamers. 

If you personally ask me, making the banner just the same size that is used for the information overlaid on it (137p or so) would work perfectly. However, even just decreasing it by ~100 px would give back a lot of screen real estate and let people "get to the important info with less scrolling" which is the most common complaint in the forum thread by an order of magnitude, as well as hopefully mitigate the worst issues of bad cropping/resizing of pre-made banner images by mod authors. 

Thank you :)

**Comment by sevencardz** [comment]
I have to agree with Thallassa on the banner image - it doesn't even match what's shown in the WYSIWYG editor. Even with a high-quality image, I can't seem to get a good crop without being subjected to attack of the upscaling.

Another suggestion to save on web page real estate would be to turn the "Tags" banner area into a collapsible area or move it somewhere else (like the very bottom of the page). If the user has already found the mod, I'm not sure why the user would absolutely need to know what tags it has unless they are browsing for similar mods, hence my suggestion for putting tags at the bottom (like an appendix).

Thank you for all the hard work Nexus staff!
