### ISSUE TITLE
Locked comments can be replied to

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#287]
Bug/error being reported: Comments on mod pages that are locked still let you reply to them.
Steps to reproduce: Go to a mod page that has a locked sticky comment and reply to it.
Expected result: You shouldn't be able to reply to locked comment.
Actual result: You can reply to locked comments.

Example:
https://rd.nexusmods.com/skyrimspecialedition/mods/13059?tab=posts

**Comment by ousnius** [comment]
On the old site, the very same comment appears as locked and can't be replied to. On the new site, it still lets me choose "Lock post" (instead of "Unlock post") and reply to it.

**Comment by iamtiz** [comment]
Assigned #152335904

**Comment by iamtiz** [comment]
Fixed
