### ISSUE TITLE
Uploading is a lot slower in RD site

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#288]
Bug/error being reported: When uploading files to RD it takes almost twice as long as classic.
Steps to reproduce: Upload file to classic site, then upload same file on RD site
Expected result: Equal(ish) upload times
Actual result: RD site takes 2-3 times longer

Example - https://rd.nexusmods.com/skyrimspecialedition/mods/11802?
Main file 2.7 - 2gb in size - Old site upload 20-30mins
Low Res textures - 1.2gb - New site, still not done at almost 2 hours since upload started.

This coupled with the janky saving of new files in RD means I'm still not using it for file uploads as I don't feel it can be trusted.

**Comment by mrmason** [comment]
I suspect if you watch your network console in your browser you'll be seeing lots of failed requests.

This is almost certainly to do with cloud flare settings - we need to write some new rules for the new upload paths - I'll let you know when we've implemented them.

**Comment by Pickysaurus** [comment]
Thanks for the quick reply MrMason :) Just uploading 2.1gb texture back via the old site as we speak, I expect it to take 30-40mins.

**Comment by mrmason** [comment]
This should now be the same speed as the live website.
