### ISSUE TITLE
Can't use "." in search query

### ISSUE THREAD

**Issue by Tywele** [Nexus-Mods/web-issues#29]
Bug/error being reported: When I try to search for something that contains a "." character in my search query it doesn't work.
Steps to reproduce: Type something into the search bar with a "." character. For example "Horizon v1.1" in the Fallout 4 Nexus
Expected result: site gets searched for "Horizon v1.1"
Actual result: site gets searched for "Horizon v11"

**Comment by verenion** [comment]
Assigned PT#150855519

**Comment by verenion** [comment]
Fix has been pushed.
