### ISSUE TITLE
Forum Edit Function Opens Last Reply Edited Text Instead of Current Reply's Text

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#290]
Bug/error being reported:Pressing the Edit Post link sometimes populates the edit-text field with a different post than the one that contains the Edit Post link I pressed. This occurs after I have edited one or more replies and then try to edit another reply
Steps to reproduce:Edit several of your own replies in a row ending with pressing "Submit." Eventually after 2 or 3 edits the wrong reply's text will be displayed in the Editing window when you press Edit.
Expected result:Pressing the Edit link within a reply populates the Editing Window with that reply's text
Actual result:Pressing the Edit link within a reply sometimes populates the Editing Window with the text of the previous reply you edited
This is a new bug which first occurred for me at approximately 0530 GMT on October 31, 2017. At the same time, the previous long-standing bug in old and new versions where pressing Submit did not refresh the reply text, requiring the user to manually press her browser's Refresh Page button to force the just-submitted text to display properly, miraculously disappeared- all my edits tonight were quickly refreshed and properly displayed after I pressed Submit... for the first time in years,

**Comment by Rrrafau** [comment]
@Vyxenne I wasn't able replicating it. Just take make sure, when you're saying "forum", you are actually talking about the forum UI on the nexus site, e.g. https://rd.nexusmods.com/skyrim/mods/11811?tab=forum and not our IP Board forum?

**Comment by Rrrafau** [comment]
Can anyone else replicate this issue? I haven't had much luck.

**Comment by Rrrafau** [comment]
To make sure we're talking about the same thing, you are talking about the forum ui on rd, e.g. https://rd.nexusmods.com/fallout4/mods/27280?tab=forum and not our IP.Board forum?

**Comment by Vyxenne** [comment]
I was on the SkyUI or Bodyslide mod post page, Skyrim Special Edition, new format with "rd" in front of the actual url. Can't provide link because I'm not on my computer right now. 


Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone
-------- Original message --------From: Rafal <notifications@github.com> Date: 11/1/17  08:25  (GMT-06:00) To: Nexus-Mods/web-issues <web-issues@noreply.github.com> Cc: Vyxenne <angielabelle@bellsouth.net>, Mention <mention@noreply.github.com> Subject: Re: [Nexus-Mods/web-issues] Forum Edit Function Opens Last Reply
  Edited Text Instead of Current Reply's Text (#290) 
To make sure we're talking about the same thing, you are talking about the forum ui on rd, e.g. https://rd.nexusmods.com/fallout4/mods/27280?tab=forum and not our IP.Board forum?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nexus-Mods/web-issues","title":"Nexus-Mods/web-issues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Nexus-Mods/web-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Rrrafau in #290: To make sure we're talking about the same thing, you are talking about the forum ui on rd, e.g. https://rd.nexusmods.com/fallout4/mods/27280?tab=forum and not our IP.Board forum?"}],"action":{"name":"View Issue","url":"https://github.com/Nexus-Mods/web-issues/issues/290#issuecomment-341105146"}}}

**Comment by Vyxenne** [comment]
It may have occurred like this: I cancelled out of an edit on Reply A and opened a new Edit window on Reply B but the text in the Edit window was that of Reply A. In other words, cancelling out of the preceding Edit may have "tricked" the software.
