### ISSUE TITLE
Gallery view bottom bar

### ISSUE THREAD

**Issue by dmitrich63** [Nexus-Mods/web-issues#291]
Bug/error being reported: Somewhy I'm only able to change displayed image using keyboard and on-screen arrows, but not by clicking other images in the bottom bar.
Steps to reproduce: Open any mod page, click on any image presented, try to change displayed image by clicking on previews in the bottom bar. Bugged in Chrome 61.0.3163.100 and 62.0.3202.75. Works fine in Edge 40.15063.674.0 and IE 11.674.15063.0.
Expected result: Displayed image changes from old to the one you've clicked.
Actual result: Nothing?

**Comment by mrmason** [comment]
Which mod are you seeing this on - or is it all mods ?

**Comment by dmitrich63** [comment]
All mods for different games, but while using Chrome only. Don't know what's about Firefox, Opera or Safari. Tried it in Chrome's incognito, too - not working.

**Comment by mrmason** [comment]
We're struggling to reproduce this on any combination of devices. Can you check the browser console and see if any errors are being reported ?

**Comment by dmitrich63** [comment]
No errors in console, only these two lines:
`CDMADS::Sic Parvis Magna::Version: 16.5.3
CDMADS: No Skin`
BTW, found something myself. In Chrome, element
'div.lg-thumb-outer'
never changes, but in IE, when I drag elements in that bar, it changes to
'lg-thumb-outer lg-grabbing lg-dragging'
Stationary in IE this element is marked as
'lg-thumb-outer lg-grab'
But in Chrome, it's always only
'lg-thumb-outer' w/o any additions no matter what I'm trying to do. Checked in both normal with no extensions and incognito modes.

**Comment by iamtiz** [comment]
Is this still happening for you?

**Comment by dmitrich63** [comment]
It is, actually! But mouse wheel, keyboard buttons and interface arrows on left and right sides of the screen work just fine, so I just got used to it.

**Comment by iamtiz** [comment]
Are you using any extensions or plugins? We still can't replicate the problem using Chrome (64)
