### ISSUE TITLE
'View as Plain Text' option returns 403 error

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#292]
Bug/error being reported: Trying to use the "View as Plain Text" option found in a file's document tab results in a 403 error.

Affected url: https://rd.nexusmods.com/fallout4/mods/40?tab=docs

Steps to reproduce: Access the 'document' tab of a file. Click "View as Plain Text" option.

Expected result: A new browser tab opening displaying the appropriate text file.

Actual result: https://i.imgur.com/MCP6oxZ.png

**Comment by Rrrafau** [comment]
Assigned #152469940

**Comment by iamtiz** [comment]
Fixed
