### ISSUE TITLE
Oblivion Nexus>Mods>Mod Categories gives HTTP 500 error

### ISSUE THREAD

**Issue by iamnotstanley** [Nexus-Mods/web-issues#293]
Bug/error being reported: Oblivion Nexus>Mods>Mod Categories gives HTTP 500 error, while the Skyrim one working. Tried with the latest Chrome Stable, MS Edge Stable and Firefox Nightly.
Steps to reproduce:
- Click here: [https://rd.nexusmods.com/oblivion/mods/categories/](https://rd.nexusmods.com/oblivion/mods/categories/)
- or go to the new Nexus layout > Oblivion subsite > _Mods_ > _Mod Categories_.
Expected result: [This site (Skyrim Nexus)](https://rd.nexusmods.com/skyrim/mods/categories) but with in the Oblivion subsite.
Actual result: ![Screenshot](https://user-images.githubusercontent.com/16244188/32232449-5a08073c-be58-11e7-8f6c-b321adaa40c4.png)

**Comment by mrmason** [comment]
Thanks - solved!
