### ISSUE TITLE
Mod view: uploader's name and link missing

### ISSUE THREAD

**Issue by TamaraUK** [Nexus-Mods/web-issues#295]
Bug/error being reported: Mod view: uploader's name and link missing
Steps to reproduce: Open Mod view
Expected result: see uploader's name and link to uploader's page 
Actual result: uploader's name and link missing

![mod view comparison](https://user-images.githubusercontent.com/33264727/32242887-ceeb2c1a-be6b-11e7-8945-4491e5720ccd.jpg)

**Comment by Thallassa** [comment]
It's right there. In your screenshot. 

I agree that section of the page could stand to be reworked a bit, but since this isn't a bug or a missing feature it's going to have to wait.

**Comment by mrmason** [comment]
This design has been through a focus group of users over a period or a number of months and decisions have been made - as @Thallassa says - it's not perfect and we fully understand that some people don't agree with the new layout and we are open to discussion at some point - but this kind of thing is a matter of opinion/preference and there is no missing functionality here.

I think we'll have to do it over some other medium than Github when we're ready - so I'm going to close this and #294 for now.
