### ISSUE TITLE
Update update / notification red 'x' missing in corner

### ISSUE THREAD

**Issue by TamaraUK** [Nexus-Mods/web-issues#296]
Bug/error being reported: Update notification is missing the red 'x' in the upper right corner to delete the notice
Steps to reproduce: Open the notification / update drop down menu no update notices have the red 'x'
Expected result: See the red 'x' in the upper right corner
Actual result: the red 'x' is missing

![update notification](https://user-images.githubusercontent.com/33264727/32243170-8b020158-be6c-11e7-8c20-4878396f809c.jpg)

**Comment by iamtiz** [comment]
Hi, the 'remove' links in the new layout are serving the same purpose as the red 'x's in the old one
