### ISSUE TITLE
Report an ad bug

### ISSUE THREAD

**Issue by Arrow2thekn33** [Nexus-Mods/web-issues#298]
Bug/error being reported:  The item you are trying to report could not be found
Steps to reproduce: Click on "report an ad" on any ad
Expected result: page to report ad
Actual result: Error "The item you are trying to report could not be found"

**Comment by Rrrafau** [comment]
assigned #152469988

**Comment by mrmason** [comment]
This was also a duplicate of `PT#152274710`
