### ISSUE TITLE
not all mods accessible via 'Manage my Mods'

### ISSUE THREAD

**Issue by kinlochhold** [Nexus-Mods/web-issues#299]
URL: https://rd.nexusmods.com/dragonage/users/myaccount?tab=files
Bug/error being reported: Only one page of mods (the 20 mods visible to non-premium accounts) are accessible via the 'My Nexus Files' tab in 'My Nexus Account'. i.e. the 'Manage my mods' link in Activity. (I have 80 mods for Dragon Age: Origins, and can only 'see' that small number.) 
Steps to reproduce: n/a
Expected result: That all my uploads would be accessible from that link, as they are on old!Nexus.
Actual result: I can only access 20 mods. (The most recent uploads?) There is no link to a second page of 20.

 Username on the Nexus: theskymoves
 Link to the affected mod/image:
- [annotated screencap of issue](https://staticdelivery.nexusmods.com/images/140/1926794-1509545957.jpg)
- [annotated screencap of old site behaviour](https://staticdelivery.nexusmods.com/images/140/1926794-1509546107.jpg)

**Comment by mrmason** [comment]
Can you let me know if this only happens under certain pages - or all the time ?

For example is it the same here ?

https://rd.nexusmods.com/users/myaccount?tab=files

**Comment by kinlochhold** [comment]
It's all the time, and the same at that link.

**Comment by verenion** [comment]
Is still happening, I've just tried to replicate this on my account and cannot seem to do it. We have done some work on the pagination system, so that may have resolved this issue

**Comment by kinlochhold** [comment]
It is still broken on my end. 

One page of mods, no pagination links -> [thusly](https://forums.nexusmods.com/index.php?/topic/5964518-help-us-test-the-new-nexus-mods-design/page-25#entry55251668).
