### ISSUE TITLE
User Profile and Settings Issues

### ISSUE THREAD

**Issue by NexusThandal** [Nexus-Mods/web-issues#30]
[Copy-Pasted from the Forums.]

Getting used to it, but already have three notes about user stuff:

1.  Under Settings in the user's profile, the **Yes/No radio buttons don't function with FF.**
(Work fine with Chrome and Edge, but dead with FF.  I do use ABP, but otherwise straight FF.)

2.  Under Mods ==> Manage My mods, would be nice if there were some indication of WHICH GAME a given mod is for (e.g. even with my own stuff I don't always remember whether something was for DAO, or DA2.)

3.  Hovering over my avatar brings up the pencil icon and the "Change my avatar photo" message. 
But actually clicking on it brings up the auto-generated error message:  "Sorry, you don't have permission for that!"

Thanks!

**Comment by verenion** [comment]
2 has already been implemented.

Assigned PT#150877494 and PT#150877494

**Comment by iamtiz** [comment]
I cannot replicate the first issue in FF 55.0.3 for Windows. Do we have any detail about the user browser version / OS?

**Comment by iamtiz** [comment]
As for issue number 3, it happens when a user is logged in on RD but not on the Forums, I think. There may be a problem with the shared login.

**Comment by verenion** [comment]
1 and 2 should be resolved. 3 has another task already here : #63
