### ISSUE TITLE
Mod page activity log entry placed under wrong group

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#300]
Bug/error being reported: Mod page activity log entry placed under wrong group
Steps to reproduce:
Expected result: All November log entries placed under November group
Actual result: One of November log entries placed under October group

Screenshot was taken just now on the 1-st of November.
![nexuserror6](https://user-images.githubusercontent.com/33193255/32281258-fcd05e64-bf26-11e7-8ef7-0cf8bb5eb4d2.png)

**Comment by verenion** [comment]
I can't seem to replicate this. Can you provide a link of where this is occurring? It looks like it might be related to timezones.

**Comment by Zur13** [comment]
This happens on my mod
https://rd.nexusmods.com/witcher3/mods/496/?tab=logs&issue_id=355663

Today it looks like even more weird because i should click Load more items button several times. Big screenshot:
![nexuserror8](https://user-images.githubusercontent.com/33193255/32440184-bc73651e-c2fa-11e7-9ba5-4e4a13efcccf.png)


P.S. The URL parameter &issue_id=355663 seems like another bug to me

**Comment by Zur13** [comment]
This bug is still there. I've changed Timezone in my profile to GMT+10:00 hours and this is what I've got:

![nexuserror8_3_1](https://user-images.githubusercontent.com/33193255/33513656-b6daa7f2-d74f-11e7-80c3-20e14c4148d8.png)

**Comment by iamtiz** [comment]
Is this still an issue for you?

**Comment by Zur13** [comment]
Yes the issue is still there
![nexuserror8_4](https://user-images.githubusercontent.com/33193255/36780385-8a7f12da-1c7b-11e8-8f9e-b38d27ae00ab.png)

Activity log dividers does not respect user timezone settings while action timestamps does.

**Comment by iamtiz** [comment]
assigned #155584198

**Comment by iamtiz** [comment]
this should be fixed now
