### ISSUE TITLE
Add the website to the HSTS preload list

### ISSUE THREAD

**Issue by ExE-Boss** [Nexus-Mods/web-issues#301]
The [HTTP Strict Transport Security (HSTS) preload list](https://hstspreload.org) is a list of websites that is used by modern major browsers to know which websites are to be loaded only over HTTPS.

[Testing the Nexus website with the HSTS preload list submission form](https://hstspreload.org/?domain=nexusmods.com) displays the following list of issues that need to be resolved before the Nexus website can be added to the HSTS preload list:

---

- **Error: No HSTS header**
  Response error: No HSTS header is present on the response.
- **Error: HTTP redirects to www first**
  `http://nexusmods.com` (HTTP) should immediately redirect to `https://nexusmods.com` (HTTPS) before adding the www subdomain. Right now, the first redirect is to `https://www.nexusmods.com/`. The extra redirect is required to ensure that any browser which supports HSTS will record the HSTS entry for the top level domain, not just the subdomain.

## Blocked by:
- #334

**Comment by mrmason** [comment]
We've got a few things we need to change in the background to reach HSTS compliance. We're getting there though.

**Comment by ExE-Boss** [comment]
@iamtiz [According to the HSTS preload list submission form](https://hstspreload.org/?domain=nexusmods.com), the website still doesn’s send the HSTS header.
