### ISSUE TITLE
UI: Required mods should open in new tab.

### ISSUE THREAD

**Issue by antrys** [Nexus-Mods/web-issues#302]
**Bug/error being reported:** When downloading a mod that has requirements (Requires other mods), the link for the required mod opens in the same window. This causes a lot of back-tracking and is particularly annoying if there are multiple other-mods required.
![nexusdltab](https://user-images.githubusercontent.com/13042832/32292463-a98aaeea-bf16-11e7-9497-250d1841d3f6.jpg)

**Steps to reproduce:**Click NMM download link on a mod with requirements and get the D/L popup.
**Expected result:** Clicking on link should open new Nexus page in a new tab.
**Actual result:** Open in current window, breaking workflow.

**Comment by mrmason** [comment]
Although I am personally against this as it removes the ability for you to choose to have it open a tab ( middle click ) or follow ( normal link ) - it does have this behaviour on the old site, so we will restore it so that it automatically opens in a new window/tab.  Assigned `PT#152512868`

**Comment by mrmason** [comment]
This has been done.
