### ISSUE TITLE
Notifications can be shown game-specific, but clearing is not game-specific. 

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#303]
I didn't see an existing github issue for this and I can't even confirm if it's still happening.... but I'm going to let you know anyways. 

Issue is from [this comment](https://forums.nexusmods.com/index.php?/topic/6098753-new-nexus-mods-design-launched/?p=54685798). I cannot replicate it myself - I didn't have this setting on. (related issue: the notifications from other games are still showing up in the updates bar even though I just set this setting and am on skyrim site). 

Error description: "In my account settings, I set my notifications to be game specific and in the old site whenever I clear all notifs it only clears on that specific game but now with the redesign, if I clear all notifs, all notifications are cleared in all games."

My apologies if this turns out to have been reported/fixed already or if it's not actually a bug.

**Comment by iamtiz** [comment]
assigned PT #152918532

**Comment by iamtiz** [comment]
Fixed
