### ISSUE TITLE
Notification Drop-Down Closes When Any Notification Is Deleted

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#304]
Bug/error being reported: The Notification Drop-Down closes when I delete a notification even though there are still one or more unread notifications. Old system does not do this.
Steps to reproduce: 1. Have multiple notifications. 2. Click the link in one of them to read the content that generated the notification. 3. Re-open ("Updates") Notification Drop-Down. 4. Delete the (grayed-out) notification for the content that you just read, leaving several unread notifications still active. 5. "Updates" box closes inappropriately.
Expected result: Notification Drop-down remains open when any notification is removed while there are remaining notifications. The old system behaves this way.
Actual result: Notification drop-down closes when any single notification is deleted even though there are other notifications.

**Comment by RavenMind** [comment]
I would like to add to this issue:
Right-clicking a notification, then selecting Open in a New Tab causes the notification drop-down to close, even if a notification is still moused over.
