### ISSUE TITLE
Feed preferences is missing the option to set default feed

### ISSUE THREAD

**Issue by Fhaarkas** [Nexus-Mods/web-issues#305]
*Issue:*
The new site is missing the option to set default homepage feed

*Attachment:*
Old site
![006](https://user-images.githubusercontent.com/10703185/32308312-32654da2-bfc0-11e7-8f39-0babbe92cddd.PNG)

New site
![007](https://user-images.githubusercontent.com/10703185/32308322-3d6ba4da-bfc0-11e7-95cc-831ff31addc0.PNG)

**Comment by Rrrafau** [comment]
I've added 3 new fields to homepage feeds preferences where you can set default tabs for each section of the site (mods, media and news). This should now be resolved.
