### ISSUE TITLE
Improper nesting of div.form-section elements in the account settings page

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#306]
URL: https://rd.nexusmods.com/skyrim/users/myaccount?tab=preferences

The .form-section elements for the "Notifications", "Search Preferences", and "Homepage feeds" sections are improperly nested inside of the .form-section element for the "Global preferences" section. This does not cause any visible issues in the Nexus site; it becomes evident when trying to reskin the site using Stylish or similar browser functionality.

If you view the source code of the page in Firefox and scroll down to around line 1400, you will see that the closing form tag and section tag are highlighted in red, indicating improper nesting. Screenshot of that attached ("nexus markup error.png").

![nexus markup error](https://user-images.githubusercontent.com/831497/32309436-015dc59e-bf62-11e7-980e-c0941c031055.png)

The error itself is here ("nexus markup error site.png"). Where you see a highlighted closing DIV tag, there should be two.

![nexus markup error site](https://user-images.githubusercontent.com/831497/32309476-3d249ab2-bf62-11e7-8c01-2e45ae1868c1.png)

**Comment by mrmason** [comment]
Thanks - this should be fixed - `#152514638`
