### ISSUE TITLE
Forums tab shows wrong view count and last post date

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#307]
Example (NSFW):
https://rd.nexusmods.com/skyrimspecialedition/mods/13207?tab=forum

**Comment by ousnius** [comment]
![image](https://user-images.githubusercontent.com/7034795/32344566-9bff99f6-c007-11e7-8795-b277a40e3134.png)

**Comment by verenion** [comment]
Assigned PT#152592191

**Comment by verenion** [comment]
Fix should be fixed;
