### ISSUE TITLE
"Updates" tab on home page won't clear.

### ISSUE THREAD

**Issue by Kainschylde** [Nexus-Mods/web-issues#308]
Bug/error being reported: When I log onto the Nexus home page (https://rd.nexusmods.com/fallout4) my "Updates" tabe has 1 notification. When I go to that tab to check the notification it says I have none yet the "1" flag over the tab won't go away.
Steps to reproduce: Just log onto the site.
Expected result: Flag on "updates" tab to clear when no new updates are available.
Actual result: Flag remains despite clearing notifications.

![notification bar](https://user-images.githubusercontent.com/33329789/32345313-09f4445c-bfc7-11e7-908f-281fdd6dd2b4.jpg)

![no updates](https://user-images.githubusercontent.com/33329789/32345312-09dbec86-bfc7-11e7-9b4f-d3e8dacb06ae.jpg)

**Comment by iamtiz** [comment]
Assigned #153006963

**Comment by iamtiz** [comment]
This should now be fixed
