### ISSUE TITLE
Comment tracking link is missing

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#31]
The page normally found at http://www.nexusmods.com/skyrimspecialedition/users/trackcomments/ seems to have no equivalent on the new site. I could just be blind, but I've been looking all over for it and can't find it. It's not super important or anything, but it is a very nice convenience to have.

**Comment by verenion** [comment]
Assigned #150877522

**Comment by mrmason** [comment]
This is already assigned to `PT#150849564` @iamtiz is working on it.

**Comment by iamtiz** [comment]
Hi, we somehow missed that feature while porting the website. It's now back, though, and you can find it as a new tab in your Tracking Centre, after Mod and Author tracking.

E.g. https://rd.nexusmods.com/mods/trackingcentre?tab=comments

**Comment by Arthmoor** [comment]
Thanks, though it doesn't seem to work. I get this error when using that link:

"You haven't uploaded any files to this site yet, or none of the files you have uploaded have comments enabled."

**Comment by iamtiz** [comment]
I found and fixed a bug that happened when browing the tracking centre while in a specific game (in contrast to browsing it from the Nexus Homepage). Is the comment tracking tab showing the expected results for you, now?

**Comment by Arthmoor** [comment]
Yes, everything seems to be showing up as expected now. Thanks.
