### ISSUE TITLE
Can't tag mod before publishing it

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#310]
Steps to reproduce: Create a new mod page, but don't publish it yet.
Expected result: On the old site, it was possible to tag a mod before publishing it.
Actual result: On the new site, this isn't possible anymore. You can view the tags that exist from Oldrim mod page duplication, but not edit them in any way before you publish the mod.

**Comment by ousnius** [comment]
Note: I'm the co-author/moderator of the mod page, in the case that matters.

**Comment by ousnius** [comment]
User tagging is off, but on the old site I could still tag as the author or moderator. That isn't the case on the new site.

**Comment by mrmason** [comment]
Assigned `PT#152632899`

**Comment by iamtiz** [comment]
This is now fixed
