### ISSUE TITLE
Optimization pass needed

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#311]
An optimization pass is needed for these reasons:

- Both mod thumbnails and news thumbnails aren't optimized. Some thumbnails come in at between 0.3 and 0.5 MB each. PNGs are the worst offenders. The front page typically weighs in at 6+ MB.

- There's a single JavaScript file named "BBoC-{timestamp}.js" that's a whopping 363 KB, despite having been minified. This file should be split into more files and each file loaded only when needed.

- Finally, forums.nexusmods.com has always been slow and the performance of that server now impacts the main website. Loading my avatar just for the header menu took 852 ms! On any comments page, each forums-hosted avatar and emoticon loads in 500-900 ms.

Browser caching helps, but you can't count on caching to be enabled or not cleared. Enabled, the slowness reported by users generally occurs on a first visit, which is not a great first impression.

**Comment by mrmason** [comment]
- We've recently rebuilt all of the PNG thumbnails so they are smaller now, but some are still almost 100kb. We've got some other plans to improve this later.

- The JS is large but it helps cache it at the edge CDN servers if it's all one file - it's not ideal but we don't have any urgent plans to change it

- Those files should be a bit quicker now.
