### ISSUE TITLE
Hot Mods stats missing

### ISSUE THREAD

**Issue by NexBeth** [Nexus-Mods/web-issues#312]
All but the 2nd row of hot mods have mod stats displayed # dls, # endorsements), even non-hot mods have this displayed.  Needs to be added to the 2nd row of Hot Mods.

**Comment by Greg-Nexus** [comment]
This suggestion is being closed and moved to our Feedback tracker: https://feedback.nexusmods.com/posts/23/add-more-information-to-hot-mods
