### ISSUE TITLE
Wrong icon or label for "includes assets from other authors" permission

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#313]
The following permission has the wrong icon or label:

> **Does your file contain assets used from other authors (that you have permission to use) that can't be redistributed without permission?**
> Option selected: No

The icon is a green check mark; however, the label and label description are:
> **Includes assets from other authors**
> All the assets in this file belong to the author, or are from free-to-use modder's resources

**Comment by iamtiz** [comment]
Assigned PT #152966502

**Comment by iamtiz** [comment]
Fixed: we reworded the label
