### ISSUE TITLE
Adding custom permission information to a box has a character limit

### ISSUE THREAD

**Issue by TheRealElianora** [Nexus-Mods/web-issues#314]
Missing feature being reported: Mod page permission text limit

Steps to reproduce: 
1. Add new mod page
2. Go to Permission editing tab
3. Add a long, detailed description of permissions
4. Observe not being able to type into the box after a while 

![image](https://user-images.githubusercontent.com/26447310/32384218-da9f411e-c0c2-11e7-9a2b-6385306d6351.png)

Expected result: Being able to be specific about permissions, translation instructions, information for people doing conversions, etc.

Actual result: No can has long permission info :|

**Comment by verenion** [comment]
Assigned PT#152594598

**Comment by verenion** [comment]
This should be resolved.
