### ISSUE TITLE
mobile device functionalty

### ISSUE THREAD

**Issue by Invaser** [Nexus-Mods/web-issues#316]
Bug/error being reported: touchscreen zoom function not working
Steps to reproduce: Samsung 7 inch tablet, android os, chrome browser.... 
Expected result: touchscreen functionality identical to old website
Actual result:

**Comment by mrmason** [comment]
I'm not sure what you mean - can you provide any more information ? The entire layout is responsive, so zooming should be minimal, but it still work in some places ?

**Comment by Invaser** [comment]
Hey Mr. Mason
On the old layout, zooming in on any part in every aspect of every page is done very easily using the standard touchscreen zoom. Thumb and index finger together as if pinching something then unpinching which results in zooming in. Spreading these same two fingers results in zooming out. Standard tablet zoom function. This standard tablet touchscreen function is simply gone from the new layout. I can't zoom in and then zoom out.  I hope that clarifies. Hey thanks for the prompt attention, you folks at the Nexus are awesome.

**Comment by Invaser** [comment]
edit : closing the thumb and index fingers results in zooming out, sorry.

**Comment by verenion** [comment]
Zooming seems to work fine for our phones. As the design is responsive, you shouldn't need to manually zoom in anyway. What device are you using?

**Comment by Invaser** [comment]
I am not using a phone, this is Samsung Galaxy Tab S with latest android os and chrome browser. I have the 7inch  screen and also the 10 inch screen. Both tablets are exceptionally well suited to browsing websites as you can zoom in to read/view better. That is, except for the new nexus layout. These are tablets not phones. Frankly, I do enjoy surfing  the Web by tablet rather than sitting at the PC desk. Sit here in my Lazy Boy chair, downloading mods to my content, transferring the mods to my PC whenever I want to. The new layout has been relagated to scrolling only on tablets. I do hope this issue can be replicated by somebody there and full tablet touchscreen functionality restored. The Tab S is unbelievable functional for browsing and downloading from the Nexus. Thanks...

**Comment by verenion** [comment]
As far as I can see, the site works normally on every device I've tested - mobile and tablet. We don't have to ability to test it on a Samsung Galaxy Tab S though. I will keep this open as a suggestion for us to look into later on.

**Comment by BetaVirus** [comment]
I can confirm that the zoom does not work with the new layout on the Moto Z2 force (Chrome browser). The page will auto resize based on of you have portrait or landscape, but you can not zoom in or out. 
Also the mod page only show mode per row and is so large for the pic that i can only see two mod before it have to scroll down. The News page only show 2 per row and is large enough that i can only see 4 news panes.

If i choose the option to show desktop version of the page; zoom works fine. thought the mod page still only shows one mod per row, it is not so large and i can see at least 7 mods list in portrait mode and 3 with landscape 

NOTE 1:  There is no option to switch view type in mobile mode; but If you switch to desktop mod and then change you view option from list mod to tile mode and then switch back i can see a smaller list of mods 2 per row and 4 mods before scrolling; But I still can not zoom in or out.
If i change it to large tile mode and then switch back to mobile mode; it is just awful and large, one mod show before you have to scroll and still no zoom functions.

**Comment by BetaVirus** [comment]
If Invaser he has the Galexy Tab S3 it have the same OS and Browser.

**Comment by BetaVirus** [comment]
If Invaser he has the Galaxy Tab S3 it has the same OS and Browser.
==================================================
I did some more testing with a LG G Pad 8.3 tablet with (Chrome 62.0.3202.84 Android 6.0).

On this unit i have no zoom ability with the new layout BUT in landscape mode it show the view change option on the mod list, but in portrait mode it does not. 
1.) In portrait mode list view, this tablet can see only one mod per row and two mods before scrolling is needed.
2.) In portrait mode tile view, I can see 2 mods per row, 4 mods before scrolling.
3.) In portrait mode Large tile view, I can see 1 more per row, 1.5 mods before scrolling.

Basicly the same as the Z2 Force except that I can actually see the view change option when in landscape mode while the Z2 force can not see a view change mode.
