### ISSUE TITLE
Minor inconsistency in the design of the mod details page

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#317]
Bug/error being reported:
![screenshot_2017-11-04_20-13-24](https://user-images.githubusercontent.com/12874678/32408691-040591d6-c19d-11e7-8638-0cf75a031cac.png)
![screenshot_2017-11-04_20-13-17](https://user-images.githubusercontent.com/12874678/32408692-042effb2-c19d-11e7-8854-158df4b7d44c.png)

Steps to reproduce: Go to a mod page you own and open the "mod details" page.
Expected result: The darker (selected) box should entirely cover the lighter (unselected) box.
Actual result: Image is self descriptive

**Comment by verenion** [comment]
Assigned PT#152597954

**Comment by verenion** [comment]
Fixed.
