### ISSUE TITLE
Notifications not refreshing

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#318]
Bug/error being reported: 
When leaving a page idle the notifications will not refresh properly on clicking the button after a while. 

Steps to reproduce:
Load a page and leave it open for 30mins+ then click the notifications (Updates) button. I will show the gear but not load anything new. Refreshing the page with F5 seems to fix this.

Expected result: Notifications update each time the Updates button is pressed
Actual result: No update until reloading the page.

**Comment by iamtiz** [comment]
Hi, real-time notifications are only sent to premium members, but only retrieved when loading a new page for all other users (both in the new and old websites)
