### ISSUE TITLE
Focus text box when renaming an image

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#319]
When renaming a mod page image on the site (clicking the pencil button), the text box isn't focused by default, so you have to click it.

It would be more comfortable if the text box was focused by default, especially when renaming a lot of images.

**Comment by ousnius** [comment]
It's possible the same thing needs to be done for other text box popups on the site.

**Comment by iamtiz** [comment]
assigned #154248818

**Comment by iamtiz** [comment]
Done
