### ISSUE TITLE
Nested Spoiler Tags on Description page

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#32]
On the old site, when opening a spoiler than containers other spoilers (nested) the sub-spoilers would stay closed until your click them.

In the new site, clicking the parent spoiler reveals all children spoilers too.

This can be replicated with the 'Technical Information' spoiler found on my mod page.
New site: https://rd.nexusmods.com/skyrimspecialedition/mods/11802/?
Old Site: https://www.nexusmods.com/skyrimspecialedition/mods/11802/?

**Comment by verenion** [comment]
Assigned PT#150920535

**Comment by verenion** [comment]
Fix has been pushed
