### ISSUE TITLE
Translations should be verifyable

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#320]
Just like images or videos, it should be possible to accept or deny translation mods to appear in the translations list at the top of your mod pages. This can be a static list of all translations linked towards your mod, but like videos you can turn off/on individual entries.

Always having all linked translations visible on mod pages in any place is something I personally don't want people to be able to do, especially as this type of stuff and translations in general are often misused.

**Comment by Pickysaurus** [comment]
+1

**Comment by rscottexe** [comment]
Not a bug, it's a feature request.

Please stick to bugs. We'll handle feature requests at a later date but right now, you're wasting our time posting feature requests on our bug tracker.
