### ISSUE TITLE
Authors can't change tags unless tagging is open to users

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#321]
**Bug/error being reported:**  
If the mod author has tagging disabled *for users* the "Tag this Mod" button disappears from the Mod Description page for the author as well.

**Steps to reproduce:** 
Disable user tagging in Manage > Permissions. Visit the description page for your mod.

**Expected result:**
Authors should be able to change tags regardless of the settings they've specified for users.

**Actual result:**
Since there is no way to tag the mod from inside the "Manage" interface, this means there's no way for the author to modify tags, period -- unless they change the settings to make them editable by users.

**Comment by ousnius** [comment]
Same as #310 probably.

**Comment by giftfish** [comment]
This issue I'm reporting happens *after* publication.

They might be related, but they are not clearly the same thing.

**Comment by mrmason** [comment]
Assigned `PT#152632899`

**Comment by iamtiz** [comment]
Fixed

**Comment by giftfish** [comment]
Verified fixed.
