### ISSUE TITLE
Edit Media: Can't reorder thumbs

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#322]
**Bug/error being reported:**
If I attempt to go from Manage > Mod Details > Media, I cannot reorder image thumbnails in the gallery. Instead, a "no" symbol appears as I attempt to drag the thumb with the mouse. 

If I access the Media area directly, (Manage > Media), THEN changing the order of thumbnails works.

**Steps to reproduce:**
See above.

**Expected result:**
Thumbnails should be movable regardless of how the Edit:Media area is accessed.

Actual result:
Thumbnails are only movable when going from Manage > Media directly.

---

I expect this bug is related to #281. The site is not behaving in the same way when going from Manage > X, as it is when navigating WITHIN the Manage interface via the radio buttons.

**Comment by verenion** [comment]
We have changed the loading of these pages, so this issue should be resolved now.

**Comment by giftfish** [comment]
Verified fixed.
