### ISSUE TITLE
Image Gallery hidden button

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#323]
**Bug/error being reported:**
When choosing to hide the "filmstrip" at the bottom of the fullscreen image gallery, the button becomes hidden behind the "Report a Bug" button.

**Steps to reproduce:**
Click the button.

Before:
![gallery_before](https://user-images.githubusercontent.com/13645804/32415858-4f63d4e6-c1f5-11e7-9679-94dba3ff59f6.jpg)

After:
![gallery_bug](https://user-images.githubusercontent.com/13645804/32415860-5a8aba06-c1f5-11e7-822e-e23c6345f541.jpg)

**Expected result:**
The button should remain accessible.

**Actual result:**
The button is inaccessible, forcing the user to exit out of the full screen gallery to regain access to the button.

**Comment by verenion** [comment]
The Report Bug button will actually be removed shortly when the site is released properly.
