### ISSUE TITLE
Edit Media thumbnail drag/drop behavior

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#324]
**Bug/error being reported:**
The action of dragging/dropping a thumbnail in the Edit Media > Your Mod Images area results in opening the full screen gallery.

**Steps to reproduce:**
Drag and drop any thumbnail in Edit Media > Your Mod Images area.

**Expected result:**
Dragging and dropping shouldn't open the full screen gallery. The site should be able to tell the difference between a normal click to select, and click-drag-release behavior.

**Actual result:**
Dragging and dropping opens the full screen gallery for each thumb interacted with. This forces the author to continuously have to exit back out of the full screen gallery, as they move thumbnails around.

**Comment by ousnius** [comment]
I don't have the bug where it opens an image in fullscreen when dragging/dropping images. I'm on the latest Chrome.

**Comment by iamtiz** [comment]
This should be fixed with a patch sent this morning

**Comment by giftfish** [comment]
Verified fixed.
