### ISSUE TITLE
Unable to sort a file's bug reports by "last post" date

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#328]
Bug/error being reported:
Unable to sort a file's bug reports by "last post" date

Steps to reproduce:
Navigate to a mod's bug reports tab. Attempt to sort list by date by clicking the "last post" link at top of table.

Expected result:
Reports should be sorted by date of last post, after clicking the appropriate option.

Actual result:
Though the indicator implies that the sorting has occurred when clicked, the reports do not seem to be sorted by date as intended.

Example: https://rd.nexusmods.com/fallout4/mods/10737?tab=bugs&BH=3

[submitted by @DJ_Damo via discord]

**Comment by verenion** [comment]
Assigned PT#152632407

**Comment by verenion** [comment]
We have removed the column heading sorting, as we added the drop down sorting and filters recently.
