### ISSUE TITLE
Circumventing file upload waiting time

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#329]
Using the ```Core/Libs/Common/Widgets/DownloadPopUp``` widget and replacing the file ID manually, it's possible to download files while they're still in the process of being shared across servers or while still being checked for viruses.

(e.g. while it's still doing these)
```This file is currently being scanned for viruses.```
```The file is currently being uploaded to our file servers and it will be ready to be downloaded soon.```

I don't know if this is of any concern, but I figured it might be worth sharing.

**Comment by mrmason** [comment]
Assigned `PT#152632770`

**Comment by iamtiz** [comment]
fixed
