### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by darthbdaman** [Nexus-Mods/web-issues#33]
Creating lists within lists worked fine in descriptions previously. On the new site however, the formatting gets messed up, and the list isn't presented properly. The first sections of the list are read correctly, but after the first [/list] tag everything gets messed up

Example found here:

https://rd.nexusmods.com/skyrim/mods/83583

**Comment by verenion** [comment]
Assigned PT#150964074

**Comment by verenion** [comment]
Assigned PT#151002943

**Comment by verenion** [comment]
Fix has been pushed

**Comment by darthbdaman** [comment]
This is broken again. Example

https://www.nexusmods.com/newvegas/mods/64232/?
