### ISSUE TITLE
Delete mod confirmation message should contain the name of the mod

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#330]
Bug/error being reported: Delete mod confirmation message should contain the name of mod
Steps to reproduce: Click Delete this mod link on some mod card in My Nexus Files screen
Expected result: Confirmation dialog appear with name of the mod to remove
Actual result: There is no way to determine which mod remove you are confirming

User should be sure he is removing the right mod especially when there is so "scary" reminder about the impossibility to undo this action.

![nexuserror10](https://user-images.githubusercontent.com/33193255/32492946-b672df8a-c3c4-11e7-8b65-18169104b32d.png)

**Comment by iamtiz** [comment]
assigned #154662416

**Comment by iamtiz** [comment]
Done
