### ISSUE TITLE
Permissions settings of mods are missing option for topic creation

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#331]
The radio buttons (the entire grey box actually) of the ```Would you like users to create their own discussion topics?``` option for mod pages was missing for me after a mod page was duplicated from Oldrim to SSE.

It only decided to appear when I went to the old Nexus site and changed the setting to "No" over there. Before that, the option wasn't there on the redesign.

I don't know if this is related to mod page duplication or just a bug for all new mod pages.
Steps to reproduce: Duplicate (or make new?) mod page and go to the permissions settings.

![image](https://user-images.githubusercontent.com/7034795/32522700-ad14e952-c418-11e7-8a30-30c094143496.png)

**Comment by verenion** [comment]
On the old site, it always appears, only disabled when "No comments" or "single comment topic and no discussion..." is selected.  This seems to be working correctly to me, unless I am missing something?

**Comment by rscottexe** [comment]
Spoken with Verenion and it's an issue with AJAX loaded pages not showing the same information on pages. Reopening this issue, but it's a part of a much wider issue.

**Comment by verenion** [comment]
Assigned PT#152675041

**Comment by verenion** [comment]
A fix has been pushed for this.
