### ISSUE TITLE
Image Centre alignment 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#333]
Bug/error being reported: When using the forum to post, applying centre alignment works for text and images on the forum, but viewing the same post on the comments page shows texts aligned but images ignore the formatting.
Steps to reproduce:
![nexus](https://user-images.githubusercontent.com/31670524/32524372-48e7b8ac-c417-11e7-8464-1c34fb45f2cc.jpg)

Expected result: Central images
Actual result: Images aligned to the left

**Comment by verenion** [comment]
Assigned PT#152672001

**Comment by verenion** [comment]
Fix has been pushed.
