### ISSUE TITLE
Wiki has broken CSS, JS and other content in HTTPS

### ISSUE THREAD

**Issue by ExE-Boss** [Nexus-Mods/web-issues#334]
## Bug/error being reported:
Wiki has broken CSS, JS and other content in HTTPS

## Steps to reproduce:
1. Open the browser’s Developer Tools Network requests view (make sure that the HTTP cache is disabled when doing this)
2. Go to https://wiki.nexusmods.com/index.php/Main_Page
3. Compare the results with http://wiki.nexusmods.com/index.php/Main_Page

## Expected result:
The page and responses should be like http://wiki.nexusmods.com/index.php/Main_Page

## Actual result:
In HTTPS, most of the responses are [404 Not Found](https://developer.mozilla.org/docs/Web/HTTP/Status/404) instead of [200 OK](https://developer.mozilla.org/docs/Web/HTTP/Status/200).

## Blocks:
- #301

**Comment by Pickysaurus** [comment]
This should be fixed.
