### ISSUE TITLE
Adult content not showing in Chrome on redesign site

### ISSUE THREAD

**Issue by ShadeC4** [Nexus-Mods/web-issues#335]
Bug/error being reported: Adult content is not showing in Chrome on the new redesigned site and the option to show it won't save. unless you open the site in another browser and set it there.

Steps to reproduce: Clear Chrome's cache and/or cookies (only needed if you already have used Chrome for accessing the Nexus mods redesigned site) and then open the redesigned site in it. Go to your preferences page, select the show adult content option, refresh the page and look at the setting again. It'll be back to hidden.

Expected result: The setting is remembered and shows adult content across all Nexus sites without needing to set it in a browser other than Chrome.

Actual result: The setting is not remembered and adult content remains hidden unless you select it in a browser other than Chrome.

**Comment by verenion** [comment]
I have tried this in chrome and firefox and cannot replicate this issue. Clearing the browser cookies should log you out, so you shouldn't even be allowed to access that page.

Can you try this issue again and I will see if I can get anyone to replicate this issue.

**Comment by ShadeC4** [comment]
May as well close this as I can't reproduce it myself anymore. Weird... Whatever, temporary issue on the user's (my) end isn't so horrible. :) Sorry to have wasted your time.
