### ISSUE TITLE
Endorse button does not work in 'my download history' view

### ISSUE THREAD

**Issue by Norstaera** [Nexus-Mods/web-issues#336]
Bug/error being reported:  Went to my download history to look for particular file. Like the new layout, btw. Nice and clean. Anyway, saw that I hadn't endorsed a number of files and decided to do so. The endorse icon is clickable, but the endorsement doesn't change. I had to manually go to the mod and click endorse. When I went back to 'Download history' the endorsement icon correctly showed that I had indeed endorsed the mod.
Steps to reproduce:
Expected result:  If an icon is clickable, I expect it to do something.
Actual result:  Nothing.

The next buttons and page buttons aren't doing anything either.

**Comment by Rrrafau** [comment]
Anyone else can replicate this issue?

**Comment by Fhaarkas** [comment]
Just would like to confirm that it's working properly for me.

On Firefox 57b and Win10 1607

**Comment by Norstaera** [comment]
It isn't working for me in internet explorer.

**Comment by iamtiz** [comment]
fixed
