### ISSUE TITLE
Inconsistent file status between old and redesigned site

### ISSUE THREAD

**Issue by grc472** [Nexus-Mods/web-issues#337]
Bug/error being reported:
I was notified through tracking that the Unofficial Skyrim Survival Patch has a new version 2.1, so I went to download it (using the new redesigned site) and it told me that the file was still being uploaded to their server. I switched to the old site by changing the first token of the URL from "rd" to "www" and lo and behold the file is available for download. I switched back to "rd" and no, the file is not available yet. How is that possible? Aren't both sites using the same live data?
Steps to reproduce:
see above
Expected result:
same file status on both sites
Actual result:
one had the file available, the other did not

Whatever caused it seems to have been corrected.  I just checked before submitting this and the new site now has the right status.  I first noticed it early this morning, and the problem persisted for several hours.  I'm not sure when it got fixed.  Anyhow, I'm submitting this anyway just to let you know that it did happen and could possibly happen again for some other file.

**Comment by mrmason** [comment]
I've pushed a fix for this to allow downloads. `PT#152726731`

We need to remove the re-scan option, and change the tick to a question mark  - we will get that sorted - I've assigned `PT#152726992`

**Comment by iamtiz** [comment]
fixed
