### ISSUE TITLE
Emoticons not working in sticky posts

### ISSUE THREAD

**Issue by Hozsa** [Nexus-Mods/web-issues#338]
As I wrote in the Title
when post is sticky Emoticons not working in the new nexus layout tried to use :) and :smile:

How to reproduce:
Okay it's not only the sticky post it's any post what you edit afterwards. it occurs when you don't remember to check that use emoticon tab in first place when submiting post first time if you edit the post afterwards and check that tab it won't work.

**Comment by verenion** [comment]
Assigned PT#152846832

**Comment by verenion** [comment]
Fix for this has been pushed
