### ISSUE TITLE
mods 'missing' from new site

### ISSUE THREAD

**Issue by kinlochhold** [Nexus-Mods/web-issues#339]
Bug/error being reported: only **one** of my 80 mod uploads for Dragon Age Origins displays on the 'manage' page. My sole mod for Dragon Age 2 is absent from that area's 'manage' page.  **None** of them are showing in searches if I am logged in.
Steps to reproduce: 
Expected result: That my mods would be where that are supposed to be.
Actual result: See above.

**Comment by Di3sIrae** [comment]
I can confirm this on Skyrim page. Some newer mods are only displaying on the older site.
For me, 3 mods from Mihailmods are not showing in new version, but older ones are. Older site version displays all of them.

**Comment by verenion** [comment]
Can you provide links and screenshots to these issues.

**Comment by kinlochhold** [comment]
Other than the search not working for some (but not all) of my mods this particular issue is no longer applicable, and I am back to the older issue of only one page of mods being accessible on the 'Manage my mods' page (see issue #299).
