### ISSUE TITLE
WYSIWYG description editor issues

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#34]
1. The BBCode for **[size]** tags is displayed in the WYSIWYG editor instead of being, well, WYSIWYG.
2. Lists (both types) are always shown as **[*]** when you switch between source and preview. The information of what type of list it was isn't lost, but there is no visible difference between the two in WYSIWYG. Newlines in lists seem to be missing sometimes as well.

![Size and lists](https://i.imgur.com/TKfPuCL.png)

3. The button at the top right of the editor that says **[BBCODE]** has its last character, the ] symbol, cut off and it appears below, inside of the editor (Chrome 61, no scaling, 1440p).

![BBCODE button](https://i.imgur.com/5wwlT0D.png)

**Comment by ousnius** [comment]
Some of the list issues may be related to https://github.com/Nexus-Mods/web-issues/issues/33 as well.

**Comment by verenion** [comment]
#2 should have been fixed by PT#150964074

**Comment by verenion** [comment]
Fix has been pushed
