### ISSUE TITLE
Incomplete mod does not shown anywhere

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#340]
Bug/error being reported: Incomplete mod does not shown anywhere
Steps to reproduce:  
1. From Manage My Mods page click Add A File button
2. Fill in the fields as on screenshot and click Next
![nexuserror12_1](https://user-images.githubusercontent.com/33193255/32672350-5d25fc32-c653-11e7-81bd-424b9e31db37.png)

3. From the second page just go back to the MODS->Manage my mods
![nexuserror12_2](https://user-images.githubusercontent.com/33193255/32672363-68288ee2-c653-11e7-8d11-7b54d98e9851.png)

![nexuserror12_3](https://user-images.githubusercontent.com/33193255/32672374-744f9594-c653-11e7-9efb-13808849f179.png)

Expected result: TestTestTest mod is shown on my mods page
Actual result: TestTestTest file is not shown and could not be found using search box

While trying to reproduce #289 I've tried to create TestTestTest mod for tests :)

File is already there and I could not create another file with that name again

![nexuserror12_4](https://user-images.githubusercontent.com/33193255/32672378-7afa18a6-c653-11e7-94e5-7d70f88c5681.png)

Edit: after ~15 min mod appeared on my mods tab. Probably caching issue because during this time I've done page reload several times for screenshots and I've checked My Mods page in another browser TestTestTest mod was not there.

**Comment by mrmason** [comment]
Assigned `PT#152797831`

**Comment by iamtiz** [comment]
Fixed
