### ISSUE TITLE
Minor Error on Mod pages

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#341]
Bug/error being reported:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://rd.nexusmods.com/contents/images/icons.svgicon-tick-blue

Steps to reproduce:
1.Load: https://rd.nexusmods.com/skyrimspecialedition/mods/11802 
2. Download any mod (if you've yet to download it, the error will not appear.)
3. Watch console as page loads.

Expected result:
Little tick icon in front of "You last downloaded a file from this mod on 24 Oct 2017 "

Actual result:
No icon and error in console.

**Comment by iamtiz** [comment]
Assigned PT #152798153

**Comment by iamtiz** [comment]
Fixed
