### ISSUE TITLE
'Hidden' does not show on Image page categories

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#343]
Bug/error being reported:
On image page, the category 'hidden' does not show on the selection bar

![image](https://user-images.githubusercontent.com/31666578/32685497-517ac64e-c647-11e7-8035-eeb6d979052c.png)

Steps to reproduce:
https://rd.nexusmods.com/fallout4/users/myaccount?tab=images

Expected result:
A check box to show only hidden images.

Actual result:
No checkbox available.

**Comment by iamtiz** [comment]
Fixed
