### ISSUE TITLE
Tags for searching not behaving logically and causing problems

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#344]
Bug/error being reported:  Tags for restricting searching results not behaving logically (even after the 11-10-2017 update), and refreshing the search page messing with Blocked content settings.

Steps to reproduce:  Requires having had tags selected under 'Blocked content' when the new layout was put into effect, I think.  See very detailed description below.

Expected result:  Some consistent logic to apply to how tags (both in 'Blocked content'/'Content Blocking', and those checked under Search Attributes) affect the search results, and interact with each other.  I would also NOT expect that refreshing a search page would cause old settings to propagate to 'Blocked content'/'Content Blocking.

Actual result:  Complex, illogical, and frustrating, detailed below as I can not find a way to state them simply.

I still (after the 11-10-2017 update) have something weird going on with filtering by blocked tags/attributes in both layouts now.

Okay, I am very confused.  The last update you did fixed the problem with the main file (such as Inigo) for the corresponding search not showing up.  Previously, I was getting the translations for Inigo, but not Inigo.  Now I am, with all blocked tags and Attributes cleared under both 'Refine results' and under the Content blocking section under my account, getting Inigo (which is good!) but not getting any of the translations.  I should be getting them, with all blocks cleared, shouldn't I?  I am also not getting them in the original layout now.

On the original layout (as of a few days ago), I would have certain things blocked under my 'Block Content' section of my preferences.  These, by default, don't show up in a search, but if I put the check in the box next to the same tag under Attributes when doing a search, this toggled it back, and allowed that to show up again for that search.  If I removed both the listing under 'Block Content' and the check mark under Attributes when searching, I also got everything showing up, as it should be.  Not any more.

Under the new layout, all of the blocked tags from under 'Block Content' in the old layout moved over and show up under 'Content Blocking'.  So far, so good.  But when I run a search, the results aren't what I would expect.  When I open the 'Refine results' section, all of the tags that I have marked under 'Content Blocking' are also showing up checked under Attributes.  At first, I figured that the Attributes section just now reflected the status of tags in the 'Content Blocking' section, but the results were different from what I would expect if that were the case.  All the translations for Inigo, for instance, are showing up when I have nothing blocked under 'Content Blocking' and have 'translation' checked under Attributes (which it does by default).  When I click 'Clear selection' at the top of Attributes (or 'clear filters' at the bottom, for that mater) it does not clear those checks.  If I manually uncheck them, and hit 'Clear selection' (or hit 'clear filters' at the bottom, or run a new search from a fresh page), it puts all those checks back in again.  So the Attributes section is, by default, always checked with the original content of the 'Content Blocking' section when the new layout was created (irrespective of what that content is now).  Fine, I went and removed all tags from the 'Content Blocking' section, in the hopes that that would return the Attributes section of 'Refine results' to a default of unchecked.  But that did not work.  Even with nothing in 'Content Blocking' at all, any new search, or hitting 'Clear selection' under the Attributes section of 'Refine results' still results in all of those same tags being checked under Attributes.  The search results do not reflect a consistent pattern though, in that a check in an Attribute does not always reverse the results of having that listed as a tag to block under 'Content Blocking'.

Using a search for 'Inigo' and the 'translation' tag as a test, here is an example of the results: 
(A (null) indicates that the 'translation' tag was NOT checked or included.)

(I made a table for this, but could not find a way to get the Preview here to see it properly without mangling it.  See attached for table format of testing.)
[New Nexus Issues Table.txt](https://github.com/Nexus-Mods/web-issues/files/1463587/New.Nexus.Issues.Table.txt)

Listed under 'Content Blocking':  (null)
Marked under Attributes of 'Refine results':  translation
Results of search:  translations included

Listed under 'Content Blocking':  (null)
Marked under Attributes of 'Refine results':  (null)
Results of search:  no translations included (This one, at least, really should have included them!)

Listed under 'Content Blocking':  translation
Marked under Attributes of 'Refine results':  translation
Results of search:  no translations included

Listed under 'Content Blocking':  translation
Marked under Attributes of 'Refine results':  (null)
Results of search:  no translations included

Any way you read that, those results are not logical, so something is wrong, as well as the check marks under the Attributes section of 'Refine results' neither resetting as might be expected, nor reflecting the status of that tag under 'Content Blocking'.  And now (I just noticed the new problem while writing all this up and re-checking the tests) the tags that I originally had under 'Blocked content' (old layout) and 'Content Blocking' (new layout) are returning all on their own.  After much confusion, I cleared all tags under 'Blocked content' (old layout)(and saved the changes) and 'Content Blocking' (new layout) and refreshed both pages to be sure they were cleared, then waited a while, and refreshed the pages again, no change.  Then I carefully, on the old layout search page, checked only the 'translation' Attribute, which took effect automatically.  Then I unchecked that, which also took effect automatically.  I refreshed 'Blocked content' and 'Content Blocking', and 'Translation' was magically back in both.  I removed it again, and cleared content on Attributes in the new layout (which makes all those check boxes be marked again), and refreshed both content blocking pages.  Nothing had come back.  Then I re-loaded the search page on the old layout, which also now makes all of those check boxes become marked in the old layout search attributes, and refreshed the content blocking pages.  Nothing had come back.   Then I manually unmarked all of the tags under Attributes on the search page (old layout), and refreshed the content blocking pages again, and now all of those tags are once again listed as blocked in both the old and new layout content blocking pages.  I may never escape from those tags again.  If I refresh the (old) search page again, with all the tags still blocked under content blocking, but not marked on the search page, they don't come back on the search page, other then the one tag that is not listed under content blocking, which is 'Include adult files'.  That one did re-mark itself. 

I have been using the Translation tag as an example, but the whole list of tags that are magically re-appearing in my content blocking sections when I refresh the page of the old-layout search are as follows:
Bodyslide Preset,  RaceMenu Preset,  Anime,  Extreme violence/gore,  Not Lore-Friendly,  Nudity,  Saved games,  Sexy/Skimpy,  Translation

I hope this has made the problem I am having at least translucent, if not clear.  And I hope I am not stuck with these tags forever.  I will clear them again before posting this.

**Comment by Eolhin** [comment]
Oh, and my name here is the same as my name on Nexus.

**Comment by iamtiz** [comment]
Hi, are you still experiencing these issues?

**Comment by Eolhin** [comment]
Yes, or some variation there of.

The settings I had for Currently blocked tags, and for Refine results/Attributes are still defaulting to the settings I had when the transition first occurred (when I use clear selection, it still puts the old settings back in, rather then removing them).  When I manually clear all settings from both of those (which should result in unfiltered content), and search for (for example) "Inigo" (which I KNOW has translation versions of it), I get "Found 5 results. 55195 have been filtered out. Currently filtering by: attributes."
And the translation versions have been filtered out.

If I then hit 'clear attributes', which results in all of the above-listed check boxes filling themselves back in, I get a simple 10 results, including some translations.

So the results are not exactly what they were before.  The results at least seem more consistent, in some ways.  But the Refine results/Attributes section is behaving as if nothing was marked when 10 of the check-boxes are marked, and clear selection also behaves as if those being marked are the default.  It is as if those boxes, which were my original default settings under Content Blocking, are visually stuck in the logically opposite state from what they should be, when cleared.  But the search behaves as if they were cleared, when they are marked.  All this is with every setting removed from Content Blocking.  

I haven't not tested enough yet to be sure it won't vary with time, but if logic has at least been restored to search results, then you just need to get 'clear selection' to actually clear those check boxes, and for them to behave as cleared when unchecked, and to apply when checked.  It is really hard to use any kind of decent logic when searching, when some (but not all) of the search refinement selections are the logical opposite of what shows on the screen.

**Comment by iamtiz** [comment]
Note: also see #533

**Comment by Eolhin** [comment]
Yep, that looks like it is at least related.  A section of the same problem.  Nice to know I am not the only one.  *wry smile*  I will track that then.

**Comment by Eolhin** [comment]
I am still having this problem.
