### ISSUE TITLE
Reply in bugs section has unnecessary citation

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#345]
Bug/error being reported: Reply in bugs section has unnecessary citation
Steps to reproduce:
I'm not sure but I believe I've used Move to bugs link on the old site to create this issue report from user post on POSTS tab on the old site.
Expected result: Normal reply text is shown
Actual result: Reply text contains additional data: "In response to post #39191335. Spoiler:  Show"

Old site has no citation:
![nexuserror13_1](https://user-images.githubusercontent.com/33193255/32690418-19638aa8-c6ff-11e7-8689-488a772aa919.png)

New site has citation on the same reply:
![nexuserror13_2](https://user-images.githubusercontent.com/33193255/32690420-25f485d8-c6ff-11e7-9c5b-55da8917af3b.png)

**Comment by iamtiz** [comment]
assigned #154171535

**Comment by iamtiz** [comment]
fixed
