### ISSUE TITLE
Switching Layout goes to Main Page

### ISSUE THREAD

**Issue by ipkh** [Nexus-Mods/web-issues#346]
Bug/error being reported: Switch to New Layout/Old Layout goes to main page not same page
Steps to reproduce: 
1. Visit mod via Mod Manager Link
Expected result:
I should be on the same page with the new or old laypout
Actual result:
I get sent back to the home page and have to re-navigate to the game and mod page I was already on.

**Comment by rscottexe** [comment]
Hi there,

This is intended functionality as some pages don't have a like-for-like URL that can easily be replaced/linked to.

It obviously will not be an issue when the new design is put officially live.

**Comment by ipkh** [comment]
Linking Back to the main mod page would be a start.  I understand that the pages don't line up neatly, but at some point a conversion has to be done to account for older links.
