### ISSUE TITLE
Uploader Error Blocks Possibility To Correct, Requires Starting Over

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#347]
Bug/error being reported:Uploader error does not provide any means to correct the error and requires starting over
Steps to reproduce:(1) Upload a file containing an ampersand "&" in the name. (2) Upload fails after pressing commit ("save") with 'illegal character in file name' error. (3) both the drag-n-drop target box and the 'browse for file' button do not reappear, making it impossible to try again even after correcting the entered file name in the file name box as well as the actual file name on my computer. (4) The only way to get the file uploaded is to forcibly exit the page by closing your browser tab because there is no "retry" function. (5) You must then re-navigate to the page and re-enter all the data about the file or mod as well as re-dragging the (corrected) file to the uploader target box.
Expected result:Upload file name error provides for retry without forcing user to crash out of the page and start over
Actual result:see above. Can't say it any plainer.

**Comment by mrmason** [comment]
Thanks - We will improve this as soon as we can - Assigned `PT#152801383`

**Comment by iamtiz** [comment]
Fixed
