### ISSUE TITLE
Gallery hide/show button hidden behind "Report Bug" button

### ISSUE THREAD

**Issue by nschwaia** [Nexus-Mods/web-issues#348]
Bug/error being reported: Hiding the gallery while viewing a screenshot moves the show/hide button behind "Report Bug" button.
Steps to reproduce: Click on an image in a gallery for a mod. Click the hide gallery button.
Expected result: Show/Hide button will be hidden behind the "Report Bug" button.
Actual result: As expected.
![capture1](https://user-images.githubusercontent.com/4010761/32695623-d61c8350-c715-11e7-8f0b-f7450a0cf176.PNG)
![capture2](https://user-images.githubusercontent.com/4010761/32695629-fad27704-c715-11e7-9015-2d0aa0d113cd.PNG)

Edit: It turns out it is still possible to click the show/hide button as a tiny bit does show over the "Report Bug" button. It was hard to see though.

**Comment by mrmason** [comment]
We will be removing the 'report bug' button very soon - so shouldn't be a problem for much longer :)

**Comment by verenion** [comment]
This should be resolved now.
