### ISSUE TITLE
Text does not preserve formatting across different views

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#35]
Likely related to #34 #33 and #32 but the text size and colour formatting are not persistent between the old site, the forums and the new site. 
![nexus](https://user-images.githubusercontent.com/31670524/30187497-c5bd91c4-9421-11e7-974a-88da5c1df0b8.jpg)

**Comment by Pickysaurus** [comment]
More than likely related to #14 too

**Comment by mrmason** [comment]
Can you please provide us with a link so we can see this in action ?

**Comment by Pickysaurus** [comment]
The page in the screenshots is https://rd.nexusmods.com/skyrimspecialedition/mods/11802/?tab=description&issue_id=331773
https://www.nexusmods.com/skyrimspecialedition/mods/11802/?
and
https://forums.nexusmods.com/index.php?showtopic=5934603

**Comment by verenion** [comment]
Assigned PT#151002943

**Comment by verenion** [comment]
Fix has been pushed
