### ISSUE TITLE
Re-cropping existing banners doesn't work

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#350]
There is a button "Crop" underneath already uploaded and cropped banner images in the Media section/editing step.

Clicking this button doesn't allow to me re-crop the current image, but shows an empty dialog instead:
![image](https://user-images.githubusercontent.com/7034795/32701836-eb107b0a-c7dc-11e7-99ff-8b90f9d4700b.png)

**Comment by ousnius** [comment]
The URL in the image doesn't exist on the server:
[https://staticdelivery.nexusmods.com/mods/1704/images/headers_uncropped/198.jpg?check=1510510061](https://staticdelivery.nexusmods.com/mods/1704/images/headers_uncropped/198.jpg?check=1510510061) (NSFW in case it does work in the future)

**Comment by iamtiz** [comment]
This should now be fixed
