### ISSUE TITLE
Previewing file contents with many files is laggy on Chrome

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#351]
The file content preview of archives with many files is laggy when scrolling in it. This is only the case for Chrome browsers.  No scrolling lag on Firefox or Edge. Additionally, there is a **huge** amount of RAM usage when you open ones with many files.

Example:
https://rd.nexusmods.com/skyrimspecialedition/mods/198 (NSFW)

Heavy example, +500 MB RAM usage in Chrome:
https://rd.nexusmods.com/skyrim/mods/25259 (NSFW)

**Comment by mrmason** [comment]
Hmm, that's not good - We will take a look at this at some point in the future

Assigned `PT#152797895`

**Comment by iamtiz** [comment]
The memory print issue should be fixed, and scrolling should also be fine

**Comment by ousnius** [comment]
@iamtiz is this live yet? I'm still getting the memory print and scrolling lag on the file linked above using Chrome. Bear in mind that the mod was updated with a main file that has way less singular files now - you have to use the one in "old files" for comparison.

**Comment by iamtiz** [comment]
It was live, but there's a new reworked version now live. This one should be definitely faster :)

**Comment by ousnius** [comment]
Thanks, works perfectly now.
