### ISSUE TITLE
Mods not showing on mod author profile

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#352]
On some mod author profiles some mods are not showing. This is not related to tag blocking (which is working as expected, with the little warning that the mod is blocked), or the mods being hidden. 

Artaios first noticed this on Friday but he didn't seem to have opened an issue, I just found another case so I'm opening the issue. 

Artaios' example: http://prntscr.com/h8pf4h

Anbeegod there https://rd.nexusmods.com/skyrim/users/32344400 - the number says he has 3 mods for both SSE and Classic, but only 2 mods are showing for each game. (We confirmed that hidden mods don't increment the number of mods and also don't show up). 

Spooknik is a better example. I literally just accessed one of his mods from rd hot files (proving that it's not being blocked anywhere on the site), but he's shown as not having any mods. https://rd.nexusmods.com/skyrim/users/42147570?tab=user+files

![image](https://user-images.githubusercontent.com/11600099/32703855-f32e9bc2-c7c9-11e7-8bee-7bb20291bc79.png)

**Comment by mrmason** [comment]
This looks like it's a bug that appears when

1) You have at least 1 tag blocked
2) The mods in the search results have 0 tags

If you load the page as non-logged in user, or if you have 0 tags blocked then the mods show. 
Alternatively if the mod has a tag, then it will also show in the results.

We've assigned `PT#152797664`

**Comment by mrmason** [comment]
This should be fixed.
