### ISSUE TITLE
Images - Categories Inconsistently displayed

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#354]
Bug/error being reported:

Images categories not displayed consistently

Steps to reproduce:

Home > Images > Manage My Images 
   Categories bar is not displayed

![image](https://user-images.githubusercontent.com/31666578/32740280-48a0ef32-c857-11e7-8182-3ead58ea6b17.png)

Home  > Fallout 4 > Images > Manage My Images 
   Categories bar is displayed

![image](https://user-images.githubusercontent.com/31666578/32740333-7fc348a2-c857-11e7-818b-210007eb88f6.png)

Expected result:

   Categories bar should be displayed for all images management screens

Actual result:

Categories bar displayed inconsistently.

**Comment by iamtiz** [comment]
Assigned PT #152799524

**Comment by iamtiz** [comment]
This is fixed.
Please note that the category filtering is only available when a game is selected, as games may have different sets of categories.
