### ISSUE TITLE
Can't report mods/images: category error

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#355]
Bug/error being reported:
![image](https://user-images.githubusercontent.com/11600099/32746236-f482bef4-c882-11e7-996a-17b990f336ee.png)

When reporting a mod or an image on rd, no matter which category is selected, you get the error that you have not selected a category. 

Elianora first noticed this bug, but asked me to write the ticket. 

Steps to reproduce: Click report, fill out a category + reason, click submit, get the "please choose a category" error. 

Reporting comments still works as that just forwards you to the forums.

**Comment by iamtiz** [comment]
Assigned #152842206

**Comment by iamtiz** [comment]
Fized
