### ISSUE TITLE
Links inside of BBCode lists are causing a line break

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#356]
When adding a link [url] inside of a BBCode list entry [*], there will be a line break that shouldn't exist.

Description:
![image](https://user-images.githubusercontent.com/7034795/32752819-ed2391ae-c8ca-11e7-96f6-6c2911300bbc.png)

Designer:
![image](https://user-images.githubusercontent.com/7034795/32752892-2aa67780-c8cb-11e7-9f15-6eabe2e4f710.png)

```
[list=1]
[*]Test link: [url=https://github.com/niftools/nifskope/releases]NifSkope[/url]﻿.
[/list]
```

**Comment by verenion** [comment]
Assigned PT#152840883
