### ISSUE TITLE
Favourites menu "scattered"

### ISSUE THREAD

**Issue by Starfis** [Nexus-Mods/web-issues#357]
Bug/error being reported: Favorites dropdown menu is "messed up" [Example picture](http://i.imgur.com/NRfL5RI.jpg).
Steps to reproduce: When I add a game which name would put it in the first row before my currently favourited games on that line, Fallout 4 and Mass Effect, like for example the [Darkest Dungeon](http://i.imgur.com/NRfL5RI.jpg), the empty spaces will show up. If I on the other hand I favourite a game which name starts on letters later in the alphabet than the current top row games like for example [XCOM](https://i.imgur.com/QvIpqwT.png) everything works fine. If the game gets sorted into the [second row](https://i.imgur.com/l8QtGBy.png) everything is fine and same goes for an [empty](http://i.imgur.com/2esJEf5.jpg) favourite place.

**Comment by Rrrafau** [comment]
Assigned #152917874

**Comment by mrmason** [comment]
This should be fixed.
