### ISSUE TITLE
Special characters in BBCode lists cause line breaks

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#360]
Using some sort of special characters within BBCode [list] causes line breaks.
Follow-up bug to #356.

Example characters are:
[
]
*

[list]
[*][Riften] It's a town.
[/list]

[list]
[*]It's a star! * This is after the star!
[/list]

**Comment by verenion** [comment]
Assigned PT#152920963

**Comment by verenion** [comment]
This issue should be resolved
