### ISSUE TITLE
Hitting Enter in the "Fixed in version" box of the bug report status window reloads the page

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#362]
Bug/error being reported:

Hitting "Enter" from the "Fixed in version" box in the bug report "change status" window unexpectedly reloads the page instead of simply changing the status. The status is not changed, as a result. Clicking "Submit" works as intended, however.

Steps to reproduce:

Take a bug report, change its status to fixed, enter anything in the "fixed in version" box, hit enter.

Expected result:

Update the status without reloading the page.

Actual result:

Reloads the page without updating the status.

**Comment by iamtiz** [comment]
Fixed
