### ISSUE TITLE
Current section dropmenu not updating correctly

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#364]
Bug/error being reported:

When I access eg the comment or bugs section of a mod I am tracking via a notification I received, the "Current section" (visible on the mobile design) item is not updated to "Comments" or "Bugs". Rather, it defaults to "Description".

![screenshot_2017-11-16_22-20-35](https://user-images.githubusercontent.com/12874678/32916475-7e0a1a32-cb1c-11e7-857e-c083a7e89ded.png)

**Comment by Rrrafau** [comment]
Assigned #152956554
