### ISSUE TITLE
"Clear Filters" on search results doesn't work

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#366]
Bug/error being reported:
The "clear filters" in the following screen shot doesn't work
![image](https://user-images.githubusercontent.com/31666578/32960211-f7ac8f4e-cb78-11e7-858e-725a06a50acf.png)

Steps to reproduce:
https://rd.nexusmods.com/newvegas/search/

Expected result:
I would expect that the Clear Filters would do just that

Actual result:
A clock and nothing else.

**Comment by Rrrafau** [comment]
Hi, trying to replicate the issue. Are you having trouble with a specific filter or does it happen every time?

**Comment by PoorlyAged** [comment]
First, you have to have something turned on in content blocking.  If you have no filters set, you probably won't see the message.  But you already knew that, right? Here is what my filtering looks like:

![image](https://user-images.githubusercontent.com/31666578/33076247-10f7d516-ce81-11e7-8cef-0d42d709194c.png)

Go Games > Fallout 4 > search on "fish"

I get:

![image](https://user-images.githubusercontent.com/31666578/33076359-68445da8-ce81-11e7-93e8-58e6dfeb22b4.png)

Now I want to see more so on the line that starts 

![image](https://user-images.githubusercontent.com/31666578/33076518-c90fe7f6-ce81-11e7-8da0-31f404b53906.png)


 I click this:

![image](https://user-images.githubusercontent.com/31666578/33076448-9ade5160-ce81-11e7-8688-e70b044d5577.png)

My expectation is that the filters will be cleared and the search re-driven.  But alas, I get a clock and nothing else.

**Comment by iamtiz** [comment]
assigned #153557453

**Comment by iamtiz** [comment]
fixed
