### ISSUE TITLE
Clicking "View new Layout" results in incorrect site switch

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#367]
Bug/error being reported:

Clicking "View new Layout"  takes you to the surround website:
![image](https://user-images.githubusercontent.com/31666578/32960843-4ae5ee38-cb7b-11e7-8be9-6ab457f23375.png)

Steps to reproduce:

Open old NexusMods site and click "View new layout" at top of screen

Expected result:
Go to the  new layout
Actual result:
taken to :http://us.battle.net/heroes/en/game/events/dragons-of-the-nexus?utm_source=Curse%20Gaming&utm_medium=Display&utm_content=23123671&utm_campaign=LQA_HoTS_L_Dragons_of_the_Nexus_Q4_2017_NA

**Comment by Rrrafau** [comment]
Very odd and I cannot replicate it myself. Could be the case that this was an ad that caused that.

**Comment by PoorlyAged** [comment]
I will accept that answer, as it doesn't happen where there are no ads (I just tested it again).  So the bug is somewhere else.  But that doesn't make it any less a  problem.

**Comment by dbrent1411** [comment]
I am having the same problem.  i cannot view mod details, like images or the files tab to download files either.  just reloads the page.

**Comment by PoorlyAged** [comment]
dbrent1411. are you being taken to a completely different web site?  If not, you do not have the same problem.  Please do not dilute my issue with misinformation.
