### ISSUE TITLE
"phantom" updates (notifications in navbar) bug

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#368]
Bug/error being reported:

Sometimes the site shows you have new updates, but then doesn't show the updates or shows fewer than the displayed number. 

Others have repeatedly mentioned this bug but refuse to provide details or open an issue, so I can say I'm not the only one experiencing a similar bug but I don't know if their issue is behaving similarly. 

This doesn't always happen, but here's what I saw today:

> have game-specific updates on
> go to skyrim site  https://rd.nexusmods.com/skyrim
> have two updates
> only one shows (and it's for skyrim, as intended). Clear it. 
> Try to figure out what the second update was 
> go to site-wide home page https://rd.nexusmods.com/ 
> see that it was an oblivion update

So in this case, it seems that the oblivion update was incrementing the counter even on the skyrim-specific site. 

However, on other days when I get updates the counter is totally accurate for each game individually, even when I have updates from multiple different games. In fact this is the first time I've seen this particular bug. 

ETA: I lied, I cleared the oblivion update but I still have a phantom update on  https://rd.nexusmods.com/skyrim. The counter is still 1 but the only update there has been greyed out/dealt with. 

Clearing all notifications cleared both the "real" greyed out update and the phantom one. 

I don't get many updates per day so it will be hard for me to reproduce this.

**Comment by iamtiz** [comment]
Assigned #153006963

**Comment by iamtiz** [comment]
This should now be fixed
