### ISSUE TITLE
Tiles not being shown correctly

### ISSUE THREAD

**Issue by lolzcalvin** [Nexus-Mods/web-issues#369]
Bug/error being reported: Tiles do not align to show 5 per row
Reason: Tiles' thumbnails having wrong widths (139.91 -> 151.19)
Example: https://i.imgur.com/DZbS0tD.png

**Comment by Rrrafau** [comment]
Cannot replicate. Are you viewing the site using default zoom and font size options in your browser? I went to a page with the mods displayed in your screenshot and they look fine on my end.

**Comment by lolzcalvin** [comment]
no zoom nor custom font size are applied. also, it happens occasionally, as in it will happen in one or two pages but not the rest. also apparently it's not the problem with width as the height changes too, be them shrinking or expanding, and the description is bold for every tile.

and yes, i'm still able to replicate it:
[https://i.imgur.com/pNTXHgg.png](url)

it seems like there was a similar but closed issue regarding to the tile view (#160). might as well mark my issue as a dupe

**Comment by iamtiz** [comment]
I was able to replicate the issue by visiting https://rd.nexusmods.com/fallout4/mods/categories/21/ and browsing a few pages back until "Bioshock Infinite Lighthouse" and "The British Consulate General" are displayed.

Assigned #153119673

**Comment by iamtiz** [comment]
fixed
