### ISSUE TITLE
Changing the order of search results should reset the viewed page

### ISSUE THREAD

**Issue by daolaf** [Nexus-Mods/web-issues#370]
Bug/error being reported: Changing the order of search results should reset the viewed page
Steps to reproduce: Search for a mod -> go to page 3 of search results -> change sort order 
Expected result: Changing the sort order should reset to page 1
Actual result: the search results are still on page 3 although this does not make sense

**Comment by Rrrafau** [comment]
Assigned #153046257

**Comment by iamtiz** [comment]
fixed
