### ISSUE TITLE
No files visible on mod pages with old files but no main file

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#371]
On an (unpublished, probably doesn't matter) mod page, when you have one old file, but no main file, the old file is invisible in both the files tab and the files editing step.

0 main files
1 old file
= no files visible (but the tab says 1)

It is still visible on the old site.

**Comment by iamtiz** [comment]
Assigned PT #153008007

**Comment by iamtiz** [comment]
Fixed
