### ISSUE TITLE
Problem with breadcrumb font size

### ISSUE THREAD

**Issue by Zoomah** [Nexus-Mods/web-issues#372]
The breadcrumb font has different heights on lowercase characters on the current font size.

Currently i use Firefox 57 64bit on Win 10 1709 64 bit

At the moment it looks like that:
https://puu.sh/ypEf6/24cb2bb0b0.png

Changing font sizes using em instead would help in that case... a font size of 0.9em for the breadcrumbs would fix the issue for example.

**Comment by Rrrafau** [comment]
Cannot replicate it. Are you viewing the site on default zoom and font size settings?

**Comment by Zoomah** [comment]
Its all default
Roboto Fontsize 12px looks weird on my end, as shown on the screenshot
