### ISSUE TITLE
Web Page Artifacts in Google Chrome

### ISSUE THREAD

**Issue by sevencardz** [Nexus-Mods/web-issues#373]
Bug/error being reported: Weird artifacts appear near banner in Google Chrome 62.0.3202.94
Steps to reproduce: Open following page in Google Chrome: https://rd.nexusmods.com/skyrimspecialedition/mods/13402
Expected result: No artifacting, no upscaling :)
Actual result: Black line artifacts appear and flicker when the mouse is moved near the menu.
![artifacting](https://user-images.githubusercontent.com/16785178/33054768-4af2d0e6-ce49-11e7-875a-045ce5bc25f4.png)

**Comment by Rrrafau** [comment]
Assigned #153046941

**Comment by Eolhin** [comment]
I have that in places as well, and all of the banners are grainy, out of focus, and seem to have been greatly enlarged.  Comparing old and new versions of one mod page, the image has been zoomed in on, with quite a bit cut off either end, so something seems to be going wrong with the image scaling.  I am using Chrome as well.

**Comment by sevencardz** [comment]
Just an update - the black line artifact issue appears to be fixed! Tested in Google Chrome 62.0.3202.94 and 63.0.3239.84. Thank you devs. :)
