### ISSUE TITLE
Forums link in mod description doesn't work

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#375]
The following link works in mod descriptions on the old site.
http://forums.nexusmods.com/index.php?showtopic=3605550

But it turns into this URL when viewing the description on the new site (the '?' is getting trimmed away).
http://forums.nexusmods.com/index.phpshowtopic=3605550

I assume this affects all links with a '?'.

**Comment by iamtiz** [comment]
Cannot replicate at the moment. Which mod gave you this issue? Did it happening while editing an existing description, or while writing a new one?

**Comment by ousnius** [comment]
The description was never edited or created with/after the redesign. It's on https://rd.nexusmods.com/fallout4/mods/15/ (NSFW), the link that says "click **here** for the mod list".

**Comment by iamtiz** [comment]
Assigned #153132116

**Comment by iamtiz** [comment]
fixed
