### ISSUE TITLE
Over-zealous Email protection

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#376]
Bug/error being reported: Using @ to prefix a name in changelog triggers Cloudflare email protection
Steps to reproduce:
https://rd.nexusmods.com/skyrim/mods/82482/?tab=files
On this page goto Logs > Changelog to see the actual log.
Then goto files and click the version number to see the error in the popout. 
Expected result: @Person displays are text
Actual result: Replaced with [email protected] and linked to https://rd.nexusmods.com/cdn-cgi/l/email-protection
![derp](https://user-images.githubusercontent.com/31670524/33147094-71b5dc16-cfbe-11e7-9e2f-c368f8da5c92.JPG)

**Comment by iamtiz** [comment]
Assigned #153116440

**Comment by Pickysaurus** [comment]
Did you ever fix this one @iamtiz I haven't seen it again for a while.
