### ISSUE TITLE
Tracking Centre, Authors

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#377]
Bug/error being reported: Got aware of this for the first time on 21 November 2017. Every page of tracked authors displays the same list as page 1 unless an author is removed. In this case the list on page 1 updates and the following pages display the same list of page 1 again. I am currently (due to the authors tab) tracking  85 authors. Page 1 shows the first ten authors, page 2, 3 etc. show the same, the first ten authors.
Steps to reproduce: Tracking Centre, Authors tab, page 1, 2 etc.
Expected result: Every page should show a different list - as it did before.
Actual result:
https://rd.nexusmods.com/mods/trackingcentre?tab=authors&BH=1
https://rd.nexusmods.com/mods/trackingcentre?tab=authors&BH=2
second link will take you to page 1 (for whatever reason).

If the links should not display what I mean, two screenies have been added.
Thank you guys for your work.

![tracking centre authors page 1](https://user-images.githubusercontent.com/31516762/33151459-7f8b3a60-cfd8-11e7-8100-3329e352f561.jpg)
![tracking centre authors page 2](https://user-images.githubusercontent.com/31516762/33151460-7fb018ee-cfd8-11e7-92f9-e6735a7a51b4.jpg)

**Comment by iamtiz** [comment]
Assigned #153113088

**Comment by iamtiz** [comment]
Fixed
