### ISSUE TITLE
[Feature request] Insert search parameters into URI

### ISSUE THREAD

**Issue by AndyScull** [Nexus-Mods/web-issues#378]
Hi, just a feature request
Could you make search choices saved in URI like it was in old search?
So heavily used searches could be saved as bookmarks in browser, I use it a lot with old search page

**Comment by JoopNL** [comment]
Yes, very surprised this wasn't the included. Please add! :)

**Comment by iamtiz** [comment]
We have now added a "shareable link" containing all parametres so that a search can be saved / shared / bookmarked. It's found in the advanced search panel
