### ISSUE TITLE
In Edit Mod Details, the NSFW guide link does nothing

### ISSUE THREAD

**Issue by ExE-Boss** [Nexus-Mods/web-issues#379]
## Bug/error being reported:
In **Edit Mod Details**, the NSFW guide link does nothing

## Steps to reproduce:
1. Go to an edit mod details page
2. Scroll down to the **Classification** field
3. Click on the NSFW guide link

## Expected result:
A dialog or something should open with the NSFW guide

## Actual result:
The viewport gets scrolled all the way to the top of the page and nothing else happens

**Comment by iamtiz** [comment]
Assigned #147854533

**Comment by cirion** [comment]
This also happens when adding a new mod. I noticed the same behavior for the "creating a useful mod page" link.

**Comment by iamtiz** [comment]
Fixed
