### ISSUE TITLE
Paypal donation pages can be in any language

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#38]
By default, Paypal donation buttons take you to Paypal in the language of the person you are donating to (not your own). This is suboptimal, as I can't read Russian and someone else might not be able to read German (and gets put off donating).

The fix is to add the following parameter to all Paypal donation button forms to force the language to English:
```html
<input type="hidden" name="lc" value="US">
```

**Comment by ousnius** [comment]
Du'Islingr suggested that, when a mod page is not set to "English" in its settings, then the Paypal donation buttons (on said page only) should not be forced to point to the English Paypal site.

**Comment by verenion** [comment]
Assigned PT#151004396

**Comment by verenion** [comment]
Snippet has been added to force language;
