### ISSUE TITLE
Search function shows results from different games

### ISSUE THREAD

**Issue by Aleirin** [Nexus-Mods/web-issues#381]
## Bug/error being reported:
When I search something, results from other games are also geting listed. Also results are a bit irrelevant.

## Steps to reproduce:
In https://www.nexusmods.com/fallout4/ url, search for bow keyword. It lists the results from other games too. This is just an example. Same thing happens with other keywords and under other game categories like https://www.nexusmods.com/skyrim/ for example.

## Expected result:
Listed search results only from selected game.

## Actual result:
Listed search results from all games.

**Comment by GlassDeviant** [comment]
Working with Aleirin, verified this issue.

**Comment by mrmason** [comment]
We're just currently trying to make search results faster and we've edited a few of the cache keys which must be causing this. 

Can you guys please confirm if you're only seeing this via the global search ( at the top of the page ) or if this is happening on the refine search results section as well ?

**Comment by mrmason** [comment]
Assigned `PT#153122222`

**Comment by GlassDeviant** [comment]
ok, testing again...

Searched for Companion on FNV site, got only NV companions.

Refined search with "Gameplay Effects and Changes".

Expected results: List of companion mods with the Gameplay Effects and Changes tag.

Actual results: Every FNV mod tagged with Gameplay Effects and Changes.

**Comment by GlassDeviant** [comment]
ok, it seems that if I try to search for something like gibberish, I will get all sorts of mods rather than ones for a specific game, sort of like how YouTube gives you a bunch of stuff you never searched for, but only when nexus can't find a clear match.

**Comment by mrmason** [comment]
Yeah, we're taking the Youtube approach to get you to go to as many random mods as possible ... ;)

We've found the cause of the problem and we should have a fix shortly.

**Comment by GlassDeviant** [comment]
Cheers

**Comment by GlassDeviant** [comment]
Just a thought, how about an optional setting for people who aren't really interested in seeing mods they weren't specifically looking for?

**Comment by mrmason** [comment]
This should now be fixed.
