### ISSUE TITLE
Chrome, Edge, Firefox All Logging me out when I leave the site... NO other site does this

### ISSUE THREAD

**Issue by Caerdic** [Nexus-Mods/web-issues#382]
## Bug/error being reported:
Chrome, Edge, Firefox All Logging me out when I leave the site... NO other site does this.... they ARE saving my Log in Info but not keeping me logged in when I close the browsers.

## Expected result:
Remain logged into Site

## Actual result:
Logged off site

**Comment by iamtiz** [comment]
Are you still experiencing this problem?
