### ISSUE TITLE
Block Author no longer works for Images

### ISSUE THREAD

**Issue by WickedWenchOfTheWest** [Nexus-Mods/web-issues#383]
## Bug/error being reported:
 I used to be able to block skimpy etc. image content simply by blocking authors. Since the implementation of the new site, my image area has been full of semi-naked, large-arsed, massively busty females..... While I don't, per se, have a problem with the existence of such material, I'm a straight female, and it's just not something I'm interested in seeing all over my Nexus front page. I'd be really appreciative if that particular block feature worked again.

**Comment by WickedWenchOfTheWest** [comment]
I used to be able to block skimpy etc. image content simply by blocking authors. Since the implementation of the new site, my image area has been full of semi-naked, large-arsed, massively busty females..... While I don't, as such, have a problem with the existence of such material, I'm a straight female, and it's just not something I'm interested in seeing all over my Nexus front page. I'd be really appreciative if that particular block feature worked again.

**Comment by iamtiz** [comment]
Assigned #153132026

**Comment by iamtiz** [comment]
Fixed
