### ISSUE TITLE
Question/Possible Bug -- Reply box resizing

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#384]
Just a quick check on this, so I'm not making an official report.

Is this intended?
![reply window](https://user-images.githubusercontent.com/13645804/33215962-a9371c08-d0e6-11e7-8031-449f07a8fb62.PNG)

Doesn't make much sense (to me) to allow resizing to extend the box past the content width. Height should be adjustable, width should not.

**Comment by iamtiz** [comment]
Assigned #153168561

**Comment by iamtiz** [comment]
fixed
