### ISSUE TITLE
Mod page not getting a thumbnail at all

### ISSUE THREAD

**Issue by TheRealElianora** [Nexus-Mods/web-issues#385]
## Steps to reproduce:

1. Start making new mod page (I did this on my Android phone)
2. Save Mod Details tab, move to Media tab
3. Add Images, select header, etc.
4. Complete making new mod page as usual
5. Publish file and observe it not showing up in the New Files feature on the old site front page.

## Actual result: Mod has no thumbnail image

--------

The problem here is that it's the first time I've had this particular issue. I've uploaded several mods and made new mod pages on the redesigned site and never encountered this "bug". The only thing I did differently was starting to make the mod page _on my phone_ (I was waiting on my game to do something and was unable to use the computer so I jumped onto Nexus to start the mod page with my phone). So I completed Step 1 (Mod Details) on my phone and saved it, then when the mod page was created, I finished it on the PC.

Here's I went to the old site and Image Management on there, reordered the first three images and cropped the first image and FINALLY managed to get it to show up 

![image](https://user-images.githubusercontent.com/26447310/33216112-30063490-d13b-11e7-97ae-003391beb49b.png)

On the new site it's still missing an image 

![image](https://user-images.githubusercontent.com/26447310/33216160-5e564092-d13b-11e7-9a7b-014079aa4d59.png)

As there is no way to actually "set mod thumbnail", I seem to be SoL to getting my mod show up as having an image. Reordering the images on the Media tab doesn't help, neither does changing the cropping of the first image.

**Comment by iamtiz** [comment]
Assigned #153171319

**Comment by iamtiz** [comment]
This should now be fixed.
