### ISSUE TITLE
Mods Short Description Invalid Characters

### ISSUE THREAD

**Issue by alfx3** [Nexus-Mods/web-issues#386]
Bug/error being reported:
The mods short description in the User Files page, and in possibly any page that makes use of mods short description, doesn't display special characters such as `'`.

Steps to reproduce:
1. Go to any page using mods short descriptions such as your profile User Files.
2. Find a short description displaying invalid characters.

Expected result:
`'` should be displayed.

Actual result:
`l&#39` is displayed.

**Comment by iamtiz** [comment]
Assigned #153168594

**Comment by iamtiz** [comment]
fixed
