### ISSUE TITLE
Images by mod users not displayed.

### ISSUE THREAD

**Issue by AtzaMan** [Nexus-Mods/web-issues#388]
## Bug/error being reported:
New layout pages. Nexus rd subdomain.
On a mod's images tab, when there is more than 1 page of mod author's images in the gallery, and mod users have uploaded personal images.

## Steps to reproduce:
1. Navigate to a mod page.
2. Click on the images tab.
2. Click on page 2 in the mod author's image gallery.
3. Click on the "Show items by" dropdown on the top right side.
4. Select the Mod users (xyz) dropdown
5. There are no image thumbnails displayed in the gallery, even though the Mod users dropdown has xyz items.

## Expected result:
On selecting the Mod users dropdown, gallery should display image thumbnails uploaded by Mod users.

## Actual result:
On selecting the Mod users dropdown, gallery produced no results.

**Comment by iamtiz** [comment]
Assigned #153206468

**Comment by iamtiz** [comment]
Fixed
