### ISSUE TITLE
Network stats are all set to 0

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#389]
## Bug/error being reported:
An image is worth a thousand words : ![screenshot_2017-11-27_21-44-26](https://user-images.githubusercontent.com/12874678/33288357-44f51df2-d3bc-11e7-955d-279a14b1ba07.png)

## Steps to reproduce:
Look at the footer on www.nexusmods.com

**Comment by iamtiz** [comment]
Hi, is this still happening for you? Stats are looking ok on our end

**Comment by ousnius** [comment]
Stats are currently fine for me.

![grafik](https://user-images.githubusercontent.com/7034795/33325441-90603dd0-d452-11e7-8aa7-4a0607ecac16.png)

**Comment by mrmason** [comment]
This sometimes happens when one of the cron jobs fails during a time of heavy DB load - I think when you posted this bug the DB was struggling due to all of the new traffic :)

**Comment by CreeperLava** [comment]
Well then, perfect. If only all bugs fixed themselves like this one :).
