### ISSUE TITLE
Missing "Tracked files" tab feature

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#39]
The old site had a tab "Tracked files" that showed comments on game's front pages, which is missing on the redesign.

The site news, file news, latest files, latest images/videos and friend activity tabs all exist in some form or another on the new site, but not said tracked files tab.

Recently, the comment tracking section for your own files was added back (https://rd.nexusmods.com/mods/trackingcentre?tab=comments), which allows for checking new comments. But the tab I'm referring to instead, allowed me to see what people were talking about on mods I have tracked that aren't mine.

This was great help for me, as I could very easily see issues, questions and have a feel of community for the mods I like, right on the front page.

**Comment by iamtiz** [comment]
Assigned task #151092146

**Comment by iamtiz** [comment]
We added a new 'Tracked content updates', with the same content as the current 'Tracked files'

**Comment by ousnius** [comment]
Thanks, I really used this tab a lot.

I just tried it out on mobile Chrome, but got an infinite loading cog.

**Comment by mrmason** [comment]
@ousnius - Are you still experiencing this infinite loading? If so, can you let us know if you're doing anything special to achieve it ? We're unable to replicate it.

**Comment by ousnius** [comment]
It doesn't happen anymore, no.
It used to happen on the non-game-specific index back then, probably due to some queries timing out.
