### ISSUE TITLE
BBCode issue: Nested lists no longer work

### ISSUE THREAD

**Issue by JustHereToReportABug** [Nexus-Mods/web-issues#390]
## Bug/error being reported:
Using nested `[list][/list]` tags in BBCode no longer works on the mod description pages.

## Steps to reproduce:
Create a new mod.
In the mod description, create nested lists in BBCode, like so:
```
[list]
[*]Peanut Butter
[*]Jelly
[*]Bread
[list]
[*]Multi-grain bread
[*]White bread
[*]Sourdough
[/list]
[*]Paper plates
[*]Napkins
[/list]
```

### Example:
Check out my mod's page (screenshots below), where the extra `[list]` tags are being displayed, instead of formatted lists.  
It works on the old site, but not on the new site: https://www.nexusmods.com/fallout4/mods/18946

## Expected result:
This is the OLD site:
![image](https://user-images.githubusercontent.com/32278202/33290852-e2fe9b52-d378-11e7-8d5f-683c4d0ba077.png)

## Actual result:
This is the NEW site:
![image](https://user-images.githubusercontent.com/32278202/33290817-c150c6ba-d378-11e7-9796-04bb926f1bc5.png)

**Comment by iamtiz** [comment]
Assigned #153207009

**Comment by iamtiz** [comment]
fixed
