### ISSUE TITLE
No Wordwrap on Windows 7 IE 11.0.96

### ISSUE THREAD

**Issue by Dheuster** [Nexus-Mods/web-issues#391]
## Bug/error being reported:

When I go to my bugs area and try to read the text, the text is not wrapping on IE 11.0.96 (I know it is old, but it is still the newest IE browser available for Windows 7 users). 

## Steps to reproduce:

USE IE 11
View any bug report link.

## Expected result:

Wordwrapping
## Actual result:

No Word Wrapping

Example page: 
https://www.nexusmods.com/fallout4/mods/26976/?tab=bugs
Click on "Only Dogmeat use vertibirds after 1.11"

**Comment by CreeperLava** [comment]
I'm probably going to say an evidence here, but why not switch to firefox or chrome ? IE is obsolete no matter how you look at it. Edge replaces it on Windows 10.

**Comment by Dheuster** [comment]
See https://www.w3counter.com/globalstats.php

Yes, IE is on its way out, but as long as Windows 7 holds the #1 platform title, I don't think it will be Okay to dismiss Windows 7's default browser.   I also don't have rendering problems with any other sites (Even Bethesda.net renders fine).

**Comment by iamtiz** [comment]
Assigned #153597787

**Comment by Ghostwalker71** [comment]
I am seeing the same issue with win7 IE 11. It seem to be sporadic depending on which tab is being viewed and seems to be more common when there is a reply to a thread post. Threads with images in the reply always seem to be effected.

**Comment by iamtiz** [comment]
This should be fixed

**Comment by Dheuster** [comment]
Nope. Still broke. I've attached a screen shot of what I see as of Feb 01. Notice the text goes off the screen and there is no scroll bar.
![ie11](https://user-images.githubusercontent.com/32681145/35714462-c0bbe4c2-079a-11e8-8825-43565a24d049.jpg)

**Comment by 1Richwizard** [comment]
I'm getting this too, but just in the bug report section of mods. It's been going on since the site redesign. Inconvenient, since I still use Windows 7 and IE as my default browser. However, I have Chrome as a backup and I can access mod bug reports with that until this is fixed.

**Comment by iamtiz** [comment]
This should really be fixed now
