### ISSUE TITLE
New design: button colours for some games too bright.

### ISSUE THREAD

**Issue by lordlethis** [Nexus-Mods/web-issues#393]
## Bug/error being reported:
For a number of games, the button colour is rather bright. 

## Steps to reproduce:
Open a game's Nexus site (e.g. Skyrim). Buttons (e.g. Search) are glaringly bright, drawing all attention to them and away from actual content. This is even worse when accessing a mod page.

The bright colour also makes things like the "New Today" counter very hard to read.

For contrast, Morrowind's Nexus site has a nice, dark button colour :-)

**Comment by lordlethis** [comment]
(Sorry - I accidentally hit return will writing the title, opening an issue with a useless title and no usable text, but it's edited now)

**Comment by Eolhin** [comment]
I have to agree, the button colors are so bright that they interfere with smooth reading, either of the buttons, or of the text on the rest of the page.  If you want a button to clearly be a button, without making it so bright it is distracting, all you have to do is round the edges of it, color it with a gradient, or 3D effect, or texture, and darken the color way down.  Then people can see it is a button, without it being an eye-sore.  In other words, look at the old layout, and make it more like that.  At the very least, darken all the colors.

**Comment by mrmason** [comment]
We've pushed some updates to this - does this look better now ?
