### ISSUE TITLE
Title of Mod behind the Number on "Most endorsed files"

### ISSUE THREAD

**Issue by Hofmann-Simon** [Nexus-Mods/web-issues#396]
## Bug/error being reported:
Title of Mod behind the Number on "Most endorsed files"

## Steps to reproduce:
Go to here:
https://rd.nexusmods.com/skyrimspecialedition/mods/topalltime/?adult=1

## Expected result:
"UNP Female Body Renewal - A female face and body replacer"
"face and" are behind the "1"

![unbenannt](https://user-images.githubusercontent.com/23562420/33340130-88651992-d47b-11e7-8f4c-b6a08467323c.png)

**Comment by mrmason** [comment]
This is actually intended behaviour - that's why the number is transparent. We can probably improve this further at a later date.

**Comment by iamtiz** [comment]
Fixed
