### ISSUE TITLE
Prerelease versions aren't allowed

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#398]
Saving a prerelease  [semantic version](https://semver.org/) like `1.7-beta` for a mod or file fails with this message:
![](https://user-images.githubusercontent.com/230581/33412300-7a77bd7a-d558-11e7-960e-07ae9a0ce408.png)

This only happens in the new design.

**Comment by TanninOne** [comment]
To add a bit of info:
Semantic versions allow pre-release labels added with a hyphen to the version number (a version with a label is always considered "older" than the corresponding version without a label).
It also allows "meta info" added with a plus sign, though that info is completely irrelevant to version precedence ("1.2.3+foo" is the same version as "1.2.3+bar"), it's basically a comment.

But: 1.7-beta is **not** a semantic version. semver always has three integers divided by dots, so it would have to be 1.7.0-beta or 1.0.7-beta or 0.1.7-beta, though the leading 0 already indicates it's a beta.

**Comment by Pathoschild** [comment]
You're right that X.Y instead of X.Y.0 doesn't conform to the spec, but it's a [common deviation](https://github.com/semver/semver/issues/237). It'd be great if you wanted to strictly enforce semantic versioning too, but I'd be happy just allowing hyphens. I don't think we need `+` build metadata, though.

**Comment by TanninOne** [comment]
The problem I have with leaving out the patch level is that having two numbers separated by dots looks (at least to people from many countries) like a decimal number so they may think that 1.2 is newer than 1.11.
Having three numbers at least gives people a hint that the dot is not intended to be a decimal separator.

**Comment by iamtiz** [comment]
Assigned #153314295

**Comment by iamtiz** [comment]
fixed

**Comment by Pathoschild** [comment]
Confirmed. Thanks!
