### ISSUE TITLE
Enhancement: Access to Advanced Search

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#399]
Right now, you have to do a "fake" search in order to get to the "Refine results" options ( for example, you cannot search right off the bat for words that are part of a mod's description).

Maybe you could add the Advanced Search option to the bottom of the "filter scroll-down" inside the Search field?

**Comment by rscottexe** [comment]
??? There was nowhere on the old site that let you search the description of a mod without going to the Mod browsing/advanced search page (the same page).

Click the "Mods" nav menu in the top navigation, just as you would have done on the old site. Now click "Refine results". More options will now appear, including the ability to search by description.

**Comment by LadyMilla** [comment]
The access to the "filter results" function as you described it is entirely counter-intuitive. When I want to browse, I browse. When I want to search, I look for a search function. On the old site, if you clicked on the Search link, you got the File search box with the "Advanced search" option at the bottom.

**Comment by LadyMilla** [comment]
Theoretical scenario:

Somebody wants to search for mods that support the "7B Bombshell" body. The person is smart enough to realize that probably only a fraction of the mod titles will actually indicate that specific body type so "Plan B" is to search for the "7B Bombshell" string in the descriptions.

Right now, instead of 
- clicking on the Search button, 
- selecting Advanced Search, and 
- entering the "7B Bombshell" string into the "Description contains..." input field, 
the user needs to figure out that in order to access the advanced search functions, they need to 
a) follow the Mod -> Browse all mods -> Filter results -> "Description contains..." path, or 
b) do a failed (or, rather, partially successful) search for "7B Bombshell", open the "Filter results" things, remove the applied "7B Bombshell" filter, enter the "7B Bombshell" string into the "Description contains..." field.

While on the old site:
![image](https://user-images.githubusercontent.com/31491675/33434026-38957628-d5de-11e7-81f6-b3bc62ad9fef.png)

**Comment by DarknessStorm** [comment]
the whole fckin design is a big BUG
