### ISSUE TITLE
Layout is just too big still. LOTS of wasted space.

### ISSUE THREAD

**Issue by BetaVirus** [Nexus-Mods/web-issues#401]
## Bug/error being reported:
None: Feature request
This was the #1 complaint about the new layout before you made it the default layout on Nexus. I looked on the bug reports list and did not see any report about this so I am making the request.

## Steps to reproduce:
Use new layout

## Expected result:
Clean and efficent page viewing

## Actual result:
Too much empty Space and fonts, button, images all to large.

**Comment by DarknessStorm** [comment]
the whole fckin design is a big BUG
