### ISSUE TITLE
Thumbnails with Adult Content in Mods of the Month

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#402]
## Bug/error being reported:
The tagging system doesn't extend to the thumbnails, from what I can tell.  And many of the thumbnails are very much NSFW.

In the old layout, the Mods of the Month were in a list format, without thumbnails, so it was never an issue there.  It is now.  In the Mods of the Month sections for Current, October, and September (just to start with) there are mods with thumbnails that are NSFW.  If I click on these, the actual mod is filtered, and the correct Adult Content warning comes up, but the thumbnails should be being filtered as well.  This would explain why the Mods of the Month can no longer be found on the front page of a game (which makes the whole concept rather pointless).  A simple solution would be to go back to having the Mods of the Month as a list, without thumbnails, if they can not be properly filtered for content.  Then the list could be put back on the front page.

## Steps to reproduce:
1. Step 1
Hide Adult Content
2. Step 2
Block all of the tags for SEXY/SKIMPY, NOT SAFE FOR WORK, NUDITY. (excuse the caps, that was copy/paste)
3. Step 3
Go to the Mods of the Month page.

## Expected result:
Not seeing adult content, even in thumbnails.

## Actual result:
Thumbnails with adult content.

I have screenshots, if you need them, but I was not sure if it was safe to post images of that sort here, even in this context.

**Comment by iamtiz** [comment]
Assigned #153314274

**Comment by iamtiz** [comment]
fixed
