### ISSUE TITLE
[URL] tag doesn't work

### ISSUE THREAD

**Issue by VictorDragonslayer** [Nexus-Mods/web-issues#403]
## Bug/error being reported:
[URL] tag in comments section doesn't work - it redirects you to current page.

## Steps to reproduce:
Create a post with [URL] tag and click the link.

### Example:
1. Created a post with [URL] tag [here](https://www.nexusmods.com/skyrim/mods/78109?tab=posts), its content: `[url="https://www.yandex.ru"]test[/url]`
2. Clicked the link from comments section (the link works correctly in the forum thread)

## Expected result:
Clicking the link should redirect you to https://www.yandex.ru

## Actual result:
You are redirected to https://www.nexusmods.com/skyrim/mods/78109?tab=posts

The issue was discovered on Firefox 56.0.1 64-bit (RU). Recreating it on IE 10 (version 10.0.9200.17028) yielded a bit differrent result: I was redirected from https://www.nexusmods.com/skyrim/mods/78109?tab=posts to https://www.nexusmods.com/skyrim/mods/ Testing on Yandex browser (version 17.10.0.2017) gave the same resulst as on Firefox (redirecting from https://www.nexusmods.com/skyrim/mods/78109?tab=posts to  https://www.nexusmods.com/skyrim/mods/78109?tab=posts).

**Comment by iamtiz** [comment]
Assigned #153313717

**Comment by iamtiz** [comment]
fixed
