### ISSUE TITLE
Sizing, contrast, and page space suggestions

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#404]
## Bug/error being reported:
It is quite hard to find what you want to read, on the pages as they are, and to read it once you find it.  I have a few constructive suggestions.

## Steps to reproduce:
1. Step 1
Open a browser and set it to full screen, or most of your screen.

2. Step 2
Look at a mod page, on Skyrim SE for example.  Go to the Posts tab.

## Expected result:
Being about to find the information I need at a glance, and read that information once I find it.

## Actual result:
Often, sore eyes and a headache.  (I am not using hyperbole or ridiculous drama, I am prone to migraines.)  The previous Nexus layout was dark and soothing.

I know, for various reasons, the new layout is here to stay, but is there any reason it can't have the sharp edges sanded down, and colors and format adjusted to make everyone happier?
##
Width:  I get it, the background image for a mod scales now, and it can get huge if the browser window is wide.  But I don't want the background image taking up half the page, so that no content is visible below.

Possible solutions:  Either restrict the scaling, so that the background image does not expand beyond a certain point to take up half the screen (and it gets all fuzzy, as it was not meant to be that size originally), or make it so that a user can minimize the background image, the Tags section, and the Thumbnails section.  If someone is coming back to a much loved mod to read comments, they don't need those elements, they want to see the comments.

##
Width 2:  The width of the text area is too large for comfortable reading.  The human eye does not want to track that far from one side to another for each line and it causes eye-strain.  

Possible solutions:  The maximum width of the text area should be restricted further.  There is a reason columns of text usually are not that wide.  Yes, the user can squash their browser window to force the text into a more comfortable column, but I, and most others, have other tabs open on other web sites that need the wider format.  (YouTube videos, for instance.)  Confining the width of the columns for text a bit more, along with being able to minimize overly-large and currently unneeded elements on a page would go a long way to calm the complaints about things being huge/over-sized.

##
Contrast:  Shades of Grey is good, I like shades of grey, but the background for much of the text (the replies, specifically) has gotten brighter then it was, which makes reading light text over that background harder, and more of a strain on the eyes.  Also, the light-grey utility bars going across the pages in various places are TOO light.  The contrast with the rest of the nice darker page is painful.  The buttons and banner with the custom colors for the various games have varying degrees of brightness.  The change in colors from game to game is good, but some of those colors are too bright, like the light periwinkle purple for Skyrim SE.  Highly distracting.  The blue for Skyrim is nice, but still a little too bright.

Possible solutions:  Just darken things down a bit all across the board.  There is a reason the contrast levels were set to where they were on the old layout.  It was comfortable on the eyes.

##
Overall:  If you adjusted the width and space taken up by those elements, as described, and darkened down some of the glaringly bright elements, I bet you a lot of the people complaining would meet you halfway, and be better able to accept the new layout.  Allowing categories of things to be minimized, along with reducing brightness, would go a long way to calm the complaints of things being unbearably cluttered, huge, and hard to read.

Hopefully my suggestions are of some help.
Eolhin

**Comment by mrmason** [comment]
We've made some changes to this. Hopefully it's better for you now ?
