### ISSUE TITLE
New count on Updates (Notifications) tab will not clear

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#405]
## Bug/error being reported:
When I look at my "Updates" tab (took me the longest time to figure out that is where all the alerts/notifications are hiding, many of which are not updates at all), the number of new ones does not clear, like it did before. So, for instance, it shows "8" for 8 new notifications, I look at the list, and close it. That used to clear the number of new notifications, but it no longer does so.

## Steps to reproduce:
1. Step 1
With a number showing for new notifications waiting, mouse over (or click on) the Updates tab.

2. Step 2
Click elsewhere to close tab.

3. Step 3
Refresh the page, just to be sure.

## Expected result:
The number of new notifications should go away after you have looked at the list (clear to 0).

## Actual result:
There is no change in the number of 'new' notifications showing on the Updates tab, even after waiting a bit and re-opening the page from scratch.  There is currently no way to tell whether I actually have new notifications, or not.

So in an effort to clear some of the "New" items from my list of notifications ("Updates", which most aren't), I went and viewed the pages that the links lead to... and that still does not clear the "New" items from my count of New under "Updates", nor does it grey out the link as it should once it has been seen.

At the very least, have the option to mark them as seen, so that you can get back to them later, but they don't hinder seeing actually NEW new notifications. There are many things I want to save for later when I do my next wave up updates (for instance), but don't want to deal with right away.

Oh, and I have the problem both with game-specific notifications on, and with it off.  The only thing that changes is the unclearable number.

**Comment by iamtiz** [comment]
Assigned #153557533

**Comment by iamtiz** [comment]
Fixed

**Comment by Eolhin** [comment]
The 'Fix' caused the opposite problem.  Now I don't get any 'New' notifications/Updates number at all.  And I have checked, there have been new Updates posted.  Do I need to post this as a new bug?
