### ISSUE TITLE
Files in moderation review may not be properly displayed as being in moderation review

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#406]
## Bug/error being reported:
I reported a stolen mod, and later checked the page to see what was going on with it. The mod page loaded mostly-normally, except that all tab contents except for Posts showed an orange banner saying that I wasn't allowed to access the content. There was no message explaining that the file was in moderation review, as there would have been on the old site.

Soon after, the mod became wholly inaccessible: accessing it yielded only an orange banner -- no surrounding page -- saying that the file couldn't be found.

Of course, I can't verify that the file ever _was_ in moderation review. It may instead have been deleted straightaway (it was a commonly-stolen mod), or it may have been in the process of being deleted. In any case, the content was still rendered inaccessible as it should be; the site just failed to display a useful explanation as to why.

## Expected result:
For consistency with the old site, no part of the mod page should render as normal; there should be only the error message, and the Posts tab should not be usable. Even if consistency with the old site isn't desired, the error message should still state that the file has been placed under moderation review.

## Actual result:
When the file is in moderation review (or at least, when I expected it to be), the mod page rendered as normal -- header, filename, and stats -- and only the contents of each individual tab on the page showed an error message, which gave me only a generic warning that I didn't have permission to access the content. Thankfully the file itself was still inaccessible.

**Comment by iamtiz** [comment]
Hi, can you provide the link to that mod?

**Comment by DavidJCobb** [comment]
It was this one.

https://rd.nexusmods.com/skyrim/mods/88190

**Comment by iamtiz** [comment]
Assigned #153597238

**Comment by iamtiz** [comment]
fixed
