### ISSUE TITLE
Author's name does not show after Mod name

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#407]
## Bug/error being reported:
The name of the author of a mod should show right after the name of the mod on the mod page.  It does not, and is hard to find.

## Steps to reproduce:
Look at a mod page.

## Expected result:
The name of the mod-author should be displayed right after the name of the mod, or right below it.
MOD NAME  by Author

## Actual result:
The name of the author is not anywhere close to the name of the mod, and is quite tiny.  Having it smaller, and fainter then the mod name is fine (that is how it was before), but it really does need to be right after the name of the mod.  A number of people have said they could not see the name of the mod author anywhere on the page.  (I found it, but only with searching.)  One should not have to search on the page for the name of the mod author.  This isn't about aesthetics.  Not having the author's name right after, or right under the mod name is just entirely unfair and insulting to mod authors.

**Comment by Norstaera** [comment]
While I don't consider it a bug, I agree that the author's name should be next to or directly above or below the mod name.
