### ISSUE TITLE
QOL Enhancement: Show 'download started message' when download starts

### ISSUE THREAD

**Issue by CzBuCHi** [Nexus-Mods/web-issues#408]
currently when im wanna download some mod, popup dialog is shown with message 'Your download should automatically begin within a few seconds.' Can this message be changed to 'Download in progress' or something, when nmm actually starts download?

**Comment by mrmason** [comment]
The way this works using the NMM:// protocol means this isn't possible at the moment - we may explore ways of doing this inside vortex at a later time.
