### ISSUE TITLE
going to next page when reading posts

### ISSUE THREAD

**Issue by Norstaera** [Nexus-Mods/web-issues#409]
## Bug/error being reported:
The [next page] button when reading posts goes to the next page but not the top of the posts. It goes in the middle or the bottom of the posts section. This means I hit next page and then am constantly scrolling up and down. It gets annoying very quickly. This occurs in both IE and Chrome.

If I want to avoid this, I have to go the the thread in the forums, not convenient when looking at/for a variety of mods.

Also, in IE (haven't tested elsewhere) clicking [Jump] or a page number doesn't do anything.

## Steps to reproduce:
1. Go to a mod.
2. Open the posts
3. click next page [>] - you may or may not go to the top of the next page posts
4. go to the last post on that page and click the next page [>] button at the bottom

## Expected result:
Every time you click next page you should go to the first entry on the new page

## Actual result:
goes to different post - almost as if it's trying to take you to the same physical spot on the web page instead of the first post. If that makes any sense.

**Comment by Eolhin** [comment]
I have that issue as well.  Going to the next page (or any page) usually takes me to the bottom of the next page.

I have Chrome, and the [Jump] and page number buttons work fine for me (other then arriving at the bottom of the page).

**Comment by iamtiz** [comment]
Does it happen on every mod, or just some of them?

**Comment by Eolhin** [comment]
Every mod, page, or thread that I have gone to the next page for so far, in the new format.  But!  Only using the page selector/next page function at the bottom of the page.  If I go to page 2/3/etc from the page selector at the top of the thread, that takes me to the top of the selected page.  And the one at the bottom takes me to the bottom of the selected page (or middle).    But in the normal course of reading, one would read from top to bottom, hit next page at the bottom, and expect to be deposited at the top of the next/selected page.  So the trick will be to get the page selections to take you to the top of the page, no mater whether you selected the page/next from the top selection area, or the bottom one.

**Comment by Norstaera** [comment]
The problem is not specific to any particular mod or group of mods as far as I can tell. I've scrolled posts for Skyrim and DA2 mods. Probably DAO and Skyrim SE, but I don't remember for sure.

**Comment by iamtiz** [comment]
Assigned #153403164

**Comment by iamtiz** [comment]
fixed
