### ISSUE TITLE
File corrupt on new site while fine on old

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#41]
https://rd.nexusmods.com/newvegas/mods/43815?tab=files

The Many Faces Goth_Punk file is fine on the old site but when downloaded through the new one gives this....
https://puu.sh/xvHaP/bdcc6aab4c.png

Please excuse the odd download location.

**Comment by Rrrafau** [comment]
Could have been a temporary issue as I am not able to replicate it anymore. Can you confirm that it's still happening for you?

**Comment by JimUKNexus** [comment]
I tested it again and the file from the RD is still corrupt whereas the one from the current site is fine. I also tried it one of my own and got the same thing, the RD was corrupt but fine on the current site.  https://rd.nexusmods.com/newvegas/mods/55156?tab=files

Win10
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by JimUKNexus** [comment]
Tried both Winrar and 7Zip with the same result.

**Comment by mrmason** [comment]
Can you give us the MD5 hashes of each of the files you've downloaded please ?

**Comment by JimUKNexus** [comment]
This is for my own file...
New site  D41D8CD98F00B204E9800998ECF8427E
Current BC7D0D739EDF658F11DD7A1C861AC9DF

Page https://rd.nexusmods.com/newvegas/mods/55156?tab=files
File name Precious Companion -55156-1-1.rar

**Comment by JimUKNexus** [comment]
https://www.dropbox.com/s/1678c5gjdv270qr/Precious%20Companion%20-55156-1-1%20%281%29.rar?dl=0 the broken file

**Comment by JimUKNexus** [comment]
This is odd, windows says the bad file is the right size, my checker disagrees https://puu.sh/xx4Ua/b71f4544ed.png

**Comment by JimUKNexus** [comment]
An update on this, it's only the CDN that is doing it, the premium servers are fine. This is the same on Chrome and Opera.

**Comment by mrmason** [comment]
So we did a bit of investigating and the main file server has doing something wrong and serving a blank file which was the `d41d8cd98f00b204e9800998ecf8427e` MD5 you could see. We've fixed that - so everything should be working now.

If the CDN is serving any blank files then it's because we've synced them from the main site as blank - hopefully this shouldn't be the case ( I just tested your file and got the valid file on every download ).
