### ISSUE TITLE
Moderate reply menu cut by the frame

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#410]
## Bug/error being reported:
Moderate and Moderate reply menus cut by the frame on the BUGS tab:

![nexuserror14](https://user-images.githubusercontent.com/33193255/33513567-cb8125e8-d74d-11e7-9874-8f9c2aa49481.png)

![nexuserror14_2](https://user-images.githubusercontent.com/33193255/33513586-0b1351a4-d74e-11e7-9283-30cb2ab7314f.png)

## Steps to reproduce:
1. Mouse over last reply to the issue report on the BUGS tab

## Expected result:
Full menu available

## Actual result:
Lower part of the menu is not visible

**Comment by iamtiz** [comment]
Assigned #153355610

**Comment by iamtiz** [comment]
fixed
