### ISSUE TITLE
Multiple sets of spoiler tags do not display correctly on mod site

### ISSUE THREAD

**Issue by GlassDeviant** [Nexus-Mods/web-issues#411]
## Bug/error being reported:
A post that looks fine in the forums, which uses multiple sets of spoiler tags, does not display correctly in the new mods website. It also does not display correctly in the OLD mods website, though the problem is consistent across both sites.

## Steps to reproduce:
Post something with three or more sets of spoiler tags with text before, within, between and after each set.

## Expected result:
All three sets of spoiler tags enclose the text that was put between each set, as in the forum site.

Forum post: https://forums.nexusmods.com/index.php?/topic/5446957-skyrim-skill-uncapper/page-38
The three sets of spoiler tags work just fine.

## Actual result:
New mods site: https://www.nexusmods.com/skyrimspecialedition/mods/8889?tab=posts
The third set of spoiler tags closes before the contents are (incorrectly) displayed.

Old mods site: https://old.nexusmods.com/skyrimspecialedition/mods/8889?tab=posts
Same as new site.

**Comment by GlassDeviant** [comment]
Having attempted to edit the post from the mod site side, rather than the forum side as I did before, I am absolutely baffled by the absolutely massive overuse of div tags. </facepalm>

**Comment by iamtiz** [comment]
Assigned #153437845

**Comment by GlassDeviant** [comment]
Some further info: This seems to only occur if the post contains quoting from another post. At one point I thought it may have been due to how I embedded spoiler tags in the quote, but changing it to simply embedding the entire post I was replying to in quotes did not fix it, nor did making a new reply to the original post (not to my reply but to the post I was replying to) and only typing after it did not either.

**Comment by iamtiz** [comment]
Hi, this should now be fixed
