### ISSUE TITLE
HTML tags appear on edit file description

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#414]
## Bug/error being reported:
HTML tags appear on edit file description

![nexuserror15](https://user-images.githubusercontent.com/33193255/33545055-a565fa48-d8e5-11e7-9e60-7a41f25ab74a.png)

## Steps to reproduce:
1. Go to Manage Files page of some mod, on mod page select MANAGE->Files
2. Edit file description so that it contains new lines and save changes
3. Edit same file description again

## Expected result:
No HTML markup

## Actual result:
New lines was replaced with HTML tag \<br />

**Comment by iamtiz** [comment]
Assigned #153357521

**Comment by iamtiz** [comment]
fixed
