### ISSUE TITLE
Two minor issues on mobile

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#415]
## Bug/error being reported:
- Clicking the notifications button selects the icon, even without a long press. It shouldn't select anything. 
- Blue background doesn't stretch on the entire settings box, unlike the other boxes.
![](https://i.imgur.com/Fl8MoM9.png)

**Comment by mrmason** [comment]
Fixed. `PT#153873350`

**Comment by CreeperLava** [comment]
Here's how it looks now. Is it intended that it displays on 2 lines ? https://i.imgur.com/KbFD0LI.png
