### ISSUE TITLE
Content Filters non-functional on main page

### ISSUE THREAD

**Issue by katzenpapst** [Nexus-Mods/web-issues#416]
## Bug/error being reported:
A tag filter I configured doesn't seem to affect the main page (In this case: https://www.nexusmods.com/fallout4)

## Steps to reproduce:
Block the tag "LOOKSMENU PRESET".
Visit the main page (within the current timeframe)

## Expected result:
This [fugly PoS](https://www.nexusmods.com/fallout4/mods/28311) being invisible

## Actual result:
This [fugly PoS](https://www.nexusmods.com/fallout4/mods/28311) being visible, despite being actually properly tagged as "LOOKSMENU PRESET"

**Comment by iamtiz** [comment]
Assigned #153403049

**Comment by iamtiz** [comment]
This should be fixed now
