### ISSUE TITLE
Upload file issues on the new website

### ISSUE THREAD

**Issue by EtaYorius** [Nexus-Mods/web-issues#417]
## Bug/error being reported:
I been having this issue were every time i try to upload an update to my mod i get a "Error, the file you uploaded could not been found" I been having this issue for a week, i can't upload anything! even tried firefox and IE without success, i get the same damn error every time and i need to upload an update for my mod!

## Steps to reproduce:
<!--
Just upload the file, the process completes but the file is not being uploaded.

### Example:
Upload file
Wait for the upload to finish
Click for "Save" and i get the Error,

## Expected result:
Just to upload a file.

## Actual result:
"Error, the file you uploaded could not been found"

Username etayorius on this Mod: https://www.nexusmods.com/skyrimspecialedition/mods/1104/?

**Comment by rscottexe** [comment]
Please provide a link to your file page. This is unrelated to the redesign but we can hopefully fix it for you none-the-less.

**Comment by EtaYorius** [comment]
This is the link to my mod:
https://www.nexusmods.com/skyrimspecialedition/mods/1104

Every time i upload my files and click "Save", i get the following error 

"Error
The file you uploaded couldn't be found."

I can't do anything at this point.

I'm sorry for posting this here, but i tried to ask for support site, i even got two open tickets but i'm just getting ignored for a week :(  Issue started right after the new Site Design

**Comment by mrmason** [comment]
If you're on discord - please can you message me directly I'm 'MrMason' on the Nexusmods Discord Server - https://discord.gg/tJDuqw5 - and I can help you debug this live.

**Comment by EtaYorius** [comment]
I tried to get into discord and for some reason it ways my email and username are already taken, but i don't recall ever registering there. Anyway, i tried to upload the exact same file with the filename as "TEST.7z" and even "TEST.rar" and it FINALLY allowed me to upload the file, but as soon as i set the filename as "SkyTEST - Realistic Animals and Predators 1_59 NOSM" and tried to upload it again, i got the same error... i think there is something going on with filename, maybe the name is too long? makes no sense, TEST.rar/TEST.zip uploads and save fine. I never had any issues with uploading files with similar filenames in the old site.

Anyway i uploaded the correct update through my cell phone, old site shows up in my mobile so i was able to upload it the same way as i used to in the old site.

**Comment by mrmason** [comment]
I can see the file `SkyTEST-RAP-NOSM.7z` and `SkyTEST-RealisticAnimals&Predators_NOSM.7z` uploaded yesterday a number of times from our end - the uploads look like they are completing correctly ( we're rebuilding the files correctly on our end ).

I suspect you're correct and there is a problem with the file name - we will investigate from our end.

**Comment by mrmason** [comment]
Assigned `PT#153438948`

**Comment by mrmason** [comment]
I've pushed some changes to do with the uploading of files and filenames - please can to let me know if you have any more issues ?
