### ISSUE TITLE
Green check mark (same icon for Virus scan and Mod already downloaded).

### ISSUE THREAD

**Issue by cranbers** [Nexus-Mods/web-issues#418]
## Bug/error being reported:
Green check mark for example on https://rd.nexusmods.com/skyrimspecialedition/mods/top/  that shows you downloaded this mod and its up to date:  is exactly the same as " SAFE to use" / virus scanned notification under mod files download.  Example: https://rd.nexusmods.com/skyrimspecialedition/mods/266?tab=files

This causes confusion unless you hover over the check box if its in fact saying mod is up to date that you have downloaded...  or it has been scanned and is virus free.

Can you add text to the Icon saying "Virus Free"  or something to differentiate..

**Comment by iamtiz** [comment]
Assigned #155431858

**Comment by iamtiz** [comment]
fixed
