### ISSUE TITLE
Search engine does not give all results.

### ISSUE THREAD

**Issue by wverlaan67** [Nexus-Mods/web-issues#419]
## Bug/error being reported:
Search engine does not give all results.

## Steps to reproduce:
Selected game:Skyrim special editon:
[MODS] -> {Browse all mods} -> {Refine results}
In {search parameters} -> {Filename contains} fill in "Bandolier" -> [Apply filters]

You now get 3 results (name of mod):
1)Bandolier - Tight-to-Male-Bare-Body Bandolier Option for Skyrim SE
2)Bandolier Vial Belt Bottle Color Replacer
3)Bandolier - Bags and Pouches Classic SPANISH

But this page should also have been included in the search results:
https://www.nexusmods.com/skyrimspecialedition/mods/2417/?
it's file name reads:Bandolier Bags and Pouches Classic SE.
The mods name : Bandolier - Bags and Pouches Classic.

**Comment by rscottexe** [comment]
I get 11 results when searching for "Bandolier" on SSE Nexus. Are you blocking tags? You can check here: https://www.nexusmods.com/users/myaccount?tab=content+blocking

**Comment by wverlaan67** [comment]
I am soooo sorry... I DID have blocking tags. My mistake.
