### ISSUE TITLE
Notification status (read / NOT READ) is missing

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#42]
Unlike the old site, the new site's notification history does not indicate if the user has read the notification:

For example:
https://rd.nexusmods.com/users/notificationhistory/17937844/
vs
http://www.nexusmods.com/games/admin/listwarnings/?show=notif&uid=17937844

**Comment by iamtiz** [comment]
Confirmed, working on it

**Comment by iamtiz** [comment]
Fixed
