### ISSUE TITLE
Uploads: Replace old version option does not work

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#420]
When uploading an updated file to a file entry, there is an option to select which version of the file the update replaces. On the old site, this automatically deletes the old version after the update is submitted. On the new version, despite selecting the option, the old file is moved into the "Old Files" section instead of being deleted.

**Comment by iamtiz** [comment]
Assigned task #153471995

**Comment by iamtiz** [comment]
Fixed
