### ISSUE TITLE
"Files" tab "Old Files" section is no longer sorted

### ISSUE THREAD

**Issue by Izen-san** [Nexus-Mods/web-issues#421]
## Bug/error being reported:

"Files" tab is divided into "Main Files" and "Old Files" sections.  Previous versions in "Old Files" used to be sorted in descending "upload date" or "version number" (which are typically equivalent) sequence, from latest to oldest.  This is no longer the case.  There does not appear to be any rationale to their listed sequence.

## Steps to reproduce:

1. Select a mod with multiple "old versions" (ex. "Merge Plugins" at [https://www.nexusmods.com/skyrim/mods/69905/?] or "JIP LN NVSE Plugin" at [https://rd.nexusmods.com/newvegas/mods/58277?].  
2. Select the "Files" tab.
3. Scroll down to the "Old Files" portion.

## Expected result:

List of files is sorted/organized by upload date or by version number.

## Actual result:

List of files is not organized in any apparent manner.  Original upload file is somewhere in the middle of the list.  Others are scattered randomly in the list sequence.

**Comment by iamtiz** [comment]
Hi, while the old file list was never ordered by date even in the legacy design (the sorting order is by file name, in fact), we mght look into it after more urgent bugs are fixed

![old file list](https://user-images.githubusercontent.com/3407947/33709355-03f348c6-db35-11e7-80ab-2de5f4cf5468.png)

**Comment by Pickysaurus** [comment]
There are now sort headers on the files page.
