### ISSUE TITLE
Font color for SSE New Today files is barely legible against background

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#422]
## Bug/error being reported:
The font color (purple text on grey background) for the files (that are in a list, not showing as tumbnails) on a number of pages for Skyrim SE is barely readable/not readable against the grey background.  

## Steps to reproduce:
Most notably file listings on:
https://www.nexusmods.com/skyrimspecialedition/mods/newtoday/
Go there.

## Expected result:
Being able to read the names of the files without difficulty.

## Actual result:
If you look really close, and zoom the page in, you might be able to make the names of the files out.
Here is an example:
https://imgur.com/itfXnvS

This problem might exist for other games as well, but I have only looked at three or four others and they were more legible, having text colors there that were brighter, or of a color that stood out better against grey.  Might I suggest not trying to use the game-color for the text in that area?  It does not provide enough contrast.

**Comment by iamtiz** [comment]
fixed
