### ISSUE TITLE
Long description not appearing on new site

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#423]
## Bug/error being reported:
Mod description is not appearing on the new site, but works on the old. Likely because the description is very long and full of formatting, I imagine.

## Steps to reproduce:
https://www.nexusmods.com/fallout4/mods/7307/?tab=description

## Expected result:
https://old.nexusmods.com/fallout4/mods/7307/?

## Actual result:
https://www.nexusmods.com/fallout4/mods/7307/?tab=description

**Comment by iamtiz** [comment]
Assigned #153550534

**Comment by iamtiz** [comment]
fixed
