### ISSUE TITLE
Unable to download new file from Files tab.

### ISSUE THREAD

**Issue by RavenMind** [Nexus-Mods/web-issues#425]
## Bug/error being reported:
Unable to download a file from the mod's Files tab that was uploaded more than 24 hours ago. No download button appears for the file. Site states the following under the file in question, "The file is currently being uploaded to our file servers and it will be ready to be downloaded soon."

## Other relevant information:
The Manual download button is present (the one in the ul.modactions element, id="action-manual"), and correctly triggers a manual download. NMM button in same location is missing, even though the author has enabled NMM downloading.

Downloading from the old site both manually works. [Link to old site page](https://old.nexusmods.com/oblivion/mods/45875/?tab=2&navtag=https%3A%2F%2Fold.nexusmods.com%2Foblivion%2Fajax%2Fmodfiles%2F%3Fid%3D45875&pUp=1).
Link on file name (on old site) is not present. Icon next to "Download Manually" link shows a gray clock, and when hovered over throws up a notice that the file is being scanned & download at own risk. (see screenshot). This notice is NOT given when downloading from the new site via the Manual Download button in ul.modactions.

## Steps to reproduce:

1. Navigate to https://www.nexusmods.com/oblivion/mods/45875/?tab=files
2. Under "Main Files", MigMaster v1.2 has no download button

## See attached screenshots of new site & old site.
![migmaster_newsite_1](https://user-images.githubusercontent.com/30495135/33801075-6348bbde-dd0c-11e7-995c-c4cbd0693b44.jpg)
![migmaster_oldsite](https://user-images.githubusercontent.com/30495135/33801076-63641e6a-dd0c-11e7-9f40-1ced144b16fa.jpg)

**Comment by mrmason** [comment]
This file was stuck at Virus Total awaiting a Virus Scan - this is normally done very quickly, but looks like they may have had an outage. I pushed it manually for you now.

**Comment by RavenMind** [comment]
Thank you!! :)
