### ISSUE TITLE
Preferred download location not being used

### ISSUE THREAD

**Issue by seancojr** [Nexus-Mods/web-issues#428]
## Bug/error being reported:
When downloading mods whether manually or via NMM, majojrity of the time the files are downloaded through the CDN. This is happening with the new design layout. I cannot confirm if the issue would exist with the old design layout.

## Steps to reproduce:

1. Visit a mod page
2. Select the Files tab
3. Select "Mod Manager Download" or "Manual Download"

## Expected result:
For files to download via my preferred location as set in my account preferences. I have chosen North America Premium because I have a lifetime premium membership to the Nexus site. I have also configured the mod manager to use the same file server. I am running Google Chrome v63.0.3239.84 and Nexus Mod Manager v0.63.14.

## Actual result:
Files are more often than not downloaded via the CDN servers.

## Screenshots
![nexus_download_pref](https://user-images.githubusercontent.com/212940/33903069-aa73d750-df3c-11e7-81ea-26c18e59da50.png)

![nexus_download_cdn](https://user-images.githubusercontent.com/212940/33903079-b36e6e9c-df3c-11e7-8e63-e803ef5b9fd7.png)

![nexus_mod_manager](https://user-images.githubusercontent.com/212940/33903084-b689b6a4-df3c-11e7-8b58-47da21dae81b.png)

**Comment by iamtiz** [comment]
Hi, what is your username (or user id) on the Nexus?

**Comment by Nebulous112** [comment]
I also have this issue. Username Nebulous112.

There are a few related issues...

1) Exactly as the above states. When I click download with manager, the popup shows that the file will be served by the CDN, even with preferences set in both Nexus settings and my mod manager (in my case Mod Organizer 32-bit).

2) Clicking any of the options on the right half of the popup (under Premium Benefits) doesn't do anything except close the window (the file is not downloaded).

3) When the popup box comes up, it registers the file as downloaded in your download history even if you do not proceed with the download (close the box).

Let me know if you want me to open these as separate issues...they all seem related, so I thought I would post them all at once.

**Comment by seancojr** [comment]
My username on the Nexus is Kedavix. I believe I can also reproduce the steps posted above by Nebulous112.

**Comment by seancojr** [comment]
I didn't mean to close the issue. The button placement was inconvenient. 😉

**Comment by iamtiz** [comment]
Assigned #153737929

**Comment by iamtiz** [comment]
Hi, could you try to download something from the site and let us know? We have put some checks server-side to help with the debugging. Hopefully they'll prove useful :)

**Comment by seancojr** [comment]
> Hi, could you try to download something from the site and let us know? We have put some checks server-side to help with the debugging. Hopefully they'll prove useful :)

Sure, I believe it is working now. Something has definitely changed. Please see the image attachment.

![nexus_download_premium](https://user-images.githubusercontent.com/212940/34174650-4995f9e4-e4bf-11e7-959f-87845a3ad2dc.png)

You would have to confirm for me if the North America Premium server is hosted in Canada. That is the fileserver that appears in the Download Manager pane of Nexus Mod Manager when I downloaded [Dawn of Skyrim (Director's Cut) for SSE](https://www.nexusmods.com/skyrimspecialedition/mods/9074).

**Comment by iamtiz** [comment]
Yes, that's the North America server :)
