### ISSUE TITLE
External sites can hotlink NSFW Nexus images (tagged as Adult)

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#430]
## Bug/error being reported:
- External sites can post hotlinked NSFW (Adult) Nexus images.

## Expected result:
An error message or a placeholder image.

## Actual result:
See this test blog:
https://nexus-test-blog.tumblr.com/

**Comment by mrmason** [comment]
All of these images are served via multiple CDNs - I'm not sure there is much we can do about this.

**Comment by LadyMilla** [comment]
As far as I know, CDNs can be configured to block access to certain content from external domains. At least, it is possible on Amazon CloudFront. Maybe it is something that can be discussed/checked with the CDN operators? I realize this is not a 'high priority' request, but hotlinking can be a source of annoyance.
