### ISSUE TITLE
RSS feed error

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#431]
## Bug/error being reported:

Error prevents proper delivery of certain RSS feeds when accessing them from the new site. The old site seems to display them correctly.

## Steps to reproduce:
Visit: https://www.nexusmods.com/skyrim/rss/updatedtoday

## Expected result:
Visit: https://old.nexusmods.com/skyrim/rss/updatedtoday
Also affected: https://www.nexusmods.com/newvegas/rss

## Actual result:
Screenshot of error: https://i.imgur.com/0Czqdpc.png
Pastebin of page as displayed in browser: https://pastebin.com/3xJmiESe
Pastebin of page source: https://pastebin.com/Tek5Vh81

**Comment by iamtiz** [comment]
Assigned #153626991

**Comment by iamtiz** [comment]
Looking at the pastebin, the error was caused by a `&ggt;` string in the generated XML.
I wasn't able to replicate the issue, however, even when processing the same file description (this one: https://www.nexusmods.com/skyrim/mods/79746)
