### ISSUE TITLE
Cannot disable donations for a file

### ISSUE THREAD

**Issue by sevencardz** [Nexus-Mods/web-issues#432]
Bug/error being reported:
Cannot disable donations for a file.

Steps to reproduce:
Navigate to a file's permissions details and try to disable donations, ensuring to hit save at the bottom of the page.

Expected result:
Options are saved and reflected as such, and donations are properly removed on the file page as appropriate to the options chosen.

Actual result:
Options still reflect that donations are enabled after disabling and clicking save. Donation option still appears on mod page.

Note:
These options still work when accessed from the old site.

Yes, this is the same bug SirSalami reported but in reverse. Don't forget to test both scenarios after you 'fix' it this time. ;)

**Comment by iamtiz** [comment]
Assigned #153663967

**Comment by iamtiz** [comment]
fixed
