### ISSUE TITLE
HTTP Error 500 when searching by Authors

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#434]
## Bug/error being reported:
Getting HTTP Error 500 when attempting to search Skyrim Nexus by mod author name.

## Steps to reproduce:

1.  Type in "napie" (without quotes) in the Search bar (Skyrim Nexus).
2.  Select Authors in the drop-down list to the right of the Search bar
3.  Wait for the page to load before HTTP Error 500 ends up plastered across my screen.

## Expected result:
Search results for mod author napie on Skyrim Nexus

## Actual result:
HTTP Error 500 with no further explanation as to why said error occurred.

**Comment by iamtiz** [comment]
assigned #154249071

**Comment by iamtiz** [comment]
fixed
