### ISSUE TITLE
Unable to create a topic / post on a file's forum

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#436]
## Bug/error being reported:
After ensuring that the appropriate options are selected in the file's permissions page, both authors and users are unable to create new topics within the file's forum tab.

## Steps to reproduce:
1. Visit a file page that has enabled it's forum tab, such as: https://www.nexusmods.com/skyrim/mods/63874/

2. Try to create a new topic / post.

## Expected result:
A button or option to create a new topic.

## Actual result:
No option to create a new post or topic. The following message is shown:

"No topics at this time
There are not any topics to comment on at this time. If you have permission you can start one. If the author has turned off topic creation then you will have to wait for the author to create topics to comment on."

**Comment by iamtiz** [comment]
Assigned #153701197

**Comment by iamtiz** [comment]
Fixed. There is a separate cache issue I'm going to check soon, so new topics will take a few minutes to appear in mod pages
