### ISSUE TITLE
Logs tab does not load

### ISSUE THREAD

**Issue by Nebulous112** [Nexus-Mods/web-issues#437]
## Bug/error being reported:
"Logs" menu item does not load and just has the spinning gear graphic. Reloading the page will load it immediately.

Using Windows 10, Chrome with Ublock Origin and a few other extensions. Logged in as a premium user (username Nebulous112).

## Steps to reproduce:
1. Go to a mod page. For example, [Even Better Quest Objectives](https://www.nexusmods.com/skyrim/mods/32695/?).
2. Click the Logs tab.
3. Notice that the page will not load, and the gear just spins.
4. When you are tired of waiting, reload the page and notice that the page comes up almost immediately.

## Expected result:
I expected the page would come up almost immediately - the same speed as other tabs.

## Actual result:
The page does not load at all until it is refreshed by the user.

**Comment by iamtiz** [comment]
Hi, this is a know issue, it's going to be fixed with the next patch we'll deploy

**Comment by iamtiz** [comment]
fixed
