### ISSUE TITLE
List items should display the date last updated, rather than date published

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#438]
## Bug/error being reported:
Arguably a bug, but I suspect it's an oversight by the original designer. Items displayed in search / browse listings are currently displaying the date the file was originally published, rather than the date last updated, as it is on the old site.

## Steps to reproduce:
View any file listing, such as this: https://rd.nexusmods.com/skyrim/mods/

## Expected result:
Each listing should display the date the file was last updated.

## Actual result:
Each listing displays simply the date the file was published.

**Comment by iamtiz** [comment]
We're now displaying both dates
