### ISSUE TITLE
Insig

### ISSUE THREAD

**Issue by skyrimplayer47** [Nexus-Mods/web-issues#439]
Inigo was glitching out after i arrived at langleys house. It was saying I started talking to him, but I dint press the button. It kept instantly going into talk mode whenever he got close to me, and he wouldn’t listen to what I was saying. I never finished the mission because he didn’t give me the key. Help.

**Comment by mrmason** [comment]
I'm not sure what you're reporting here, but I don't think it's a problem with the Nexus Mods website ? You'll want to report any bugs regarding a specific mod to the mod author.

**Comment by skyrimplayer47** [comment]
I just tried to say farewell but he didn’t leave, he is following me
