### ISSUE TITLE
Side-by-side images in descriptions

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#44]
On the old site, putting two images next to each other in a description would show them side-by-side instead of under another, which is what the redesign currently does.

This makes a few descriptions not look as intended, such as my following one with the bow ties:
Old: https://www.nexusmods.com/fallout4/mods/15768/
New: https://rd.nexusmods.com/fallout4/mods/15768

**Comment by ousnius** [comment]
Same problem here with mobile resolutions, as the amount of bow tie images I used doesn't necessarily fit on every screen side-by-side. However that would still be less of a probem than what it is right now, I think.

**Comment by Nazenn** [comment]
Some mod authors have designed descriptions entirely around side by side images, which is causing problems for a number of mod pages they create. Eg one of the more noticeable ones:
https://rd.nexusmods.com/skyrim/mods/24666/?
https://www.nexusmods.com/skyrim/mods/24666/?

**Comment by verenion** [comment]
As far as I am aware, we don't have any plans to alter this at the moment. I will keep it open as an improvement to look at at a later date.

**Comment by rscottexe** [comment]
We've actually reimplemented the side-by-side stuff, so images can now be placed next to each other, and two YouTube videos.

**Comment by Nazenn** [comment]
Much appreciated. Looks much better this way and unbreaks a lot of descriptions :)
