### ISSUE TITLE
"Manage my supporter images" link is incorrect

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#440]
The "Manage my supporter images" link in the menu bar at the top of the Nexus points to an incorrect link.

The current link is the following:
https://www.nexusmods.com/skyrim/users/myaccount?tab=supporterimages

The correct link would be the following, with a space between "supporter" and "images":
https://www.nexusmods.com/skyrim/users/myaccount?tab=supporter+images

**Comment by iamtiz** [comment]
Assigned #153737850

**Comment by iamtiz** [comment]
Fixed
