### ISSUE TITLE
Tracking Center issue

### ISSUE THREAD

**Issue by yen-mai** [Nexus-Mods/web-issues#442]
## Bug/error being reported:
Reproducing #217 with more detail (and coffee, probably too much coffee).
Excess pages shown in tracking center. I have 118 Skyrim SE mods tracked, should only have 6 pages of mods. Site shows 12 and every page after 6 reproduces page 6 contents. Site address seems to track the number of page changes, not the actual pages' locations. Entering the address of a "future" page (?BH=856 for example) returns to page 1 and removes filtering (game field, sort by field, etc.). Entering a larger number does the same. Two page button changes are then required to advance this number.

## Steps to reproduce:
1-Use most recent version of Firefox Quantum browser or Micosoft Edge browser. (Untested on other browsers.)
2-Log in. :)
3-From upper menu, select Mods menu, then Tracking Centre under My Activity.
4-Mods tab displays total number of mods. For me, 144 total means I shouldn't have more than 8 pages for all games. I track 118 Skyrim SE mods, which means only 6 pages should be shown when filtering by game.
5-Click around the page buttons a few (dozen) times for the ?BH= # to update.
6-Change that number to something lower. It will return to the referenced page it was on, not the page number. (Let ?BH=10 display page 3. If you are on ?BH=56 and you change 56 to 10, it will again display page 3 and increment from 10 after two page button clicks.)
7-Change that number to something past your click count. It will return to page 1, regardless of how high the number is and how many "future" numbers you change it to.
8-Click any page button and this number does not increment. Click any other page button, even the one just left, and the number increments.
9-Navigate to old.nexusmods.com > Files menu > Tracking Centre. These issues are not present. This is relevant only because this current issue also existed (still does) on rd.nexusmods.com, before it became www.nexusmods.com.

Tested on Firefox and Edge with adblockers on and off without a difference.

The same issues regarding page clicks and ?BH= # happens when I select browse all mods, though there does not seem to be trailing pages. (Checked on only one filter: Category - Crafting, sorry.)

## Expected result:
See correct count on mods tab when sorting (instead of total mods tracked # persisting upon filtering by game type), correct number of pages (no duplicating, trailing pages), and filters maintained through page changes. 

## Actual result:
The actual results were a successful reproduction of #217 and are documented here:
https://imgur.com/a/A9qGJ

It's WEIRD that filters are maintained when ?BH= # is manually changed to a cached page but not a "future" page. Either the filters are not working correctly (because these pages aren't functioning correctly, the filters find an error, and reset is protocol), or the filters ARE working correctly since it "looks" like you've gone to a different webpage, so they reset when out of bounds (higher # than physical pages). Which is still weird, because if you're on page 1 and increment the # by 1, it still resets filters when it shouldn't since there is a page 2. The same thing happens with filters on browsing all mods with a category selected. It is maintained if the ?BH= # is cached (actually clicked on a page button and that # was used), but not if it is "future". Then, ?BH= # isn't tracking the physical pages correctly (because of the trailing page issue, maybe?) or it was never meant to track physical pages, but it is some how affecting/interrupting things on these pages.

Edit 254151: I have too much time on my hands today. Simple question: why, when you return to a cached page, does ?BH=# not increment on the next page button click? Simple answer: ?BH=# stores this next click as the new reference location. Test any order of page clicks (I used 1-7 for simplicity). Page 1 is null, 2 is # 0, 3 is # 1, etc.. I then manually change # to 3 and expect it to load page 5 (it does). I click page 6 ( # remains 3), 7 (# increments to 4). Manual change # to 2 and page 4 loads, as expected. Manual change # to 3, expect to see page 5, but page 6 is loaded instead since the reference was replaced. idk why this happens, but it's a symptom, not the problem. So far, large numbers haven't broken anything for me. I don't know if does anything to site/page/traffick stats.

(There is no such thing as "too much coffee," fam.)

**Comment by iamtiz** [comment]
Assigned #153778713

**Comment by iamtiz** [comment]
fixed
