### ISSUE TITLE
Strange sort order for bug status

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#443]
When sorting by status on the mod bugs page, open bugs can be buried under pages of closed bugs. That makes it harder for the mod author to review what they need to fix, and harder for players to review known issues.

Current order:

1. new issue;
2. known issue;
3. being looked at;
4. fixed (closed);
5. duplicate (closed);
6. not a bug (closed);
7. won't fix (closed);
8. needs more info.

Proposed order (by actionability):

1. new issue;
2. needs more info;
3. being looked at;
4. known issue;
5. fixed (closed);
6. duplicate (closed);
7. not a bug (closed);
8. won't fix (closed).

**Comment by maxvollmer** [comment]
Wanted to add a ticket for exactly this, with exactly that suggested new order. So yeah, +1 from me.

**Comment by Greg-Nexus** [comment]
Closed: We haven't made this change for Mods yet, but are mid-development on a new re-worked Bug Report feature that will separate Open and Closed bugs. This will get ported over to Mods as soon as we are able to do so.
