### ISSUE TITLE
New Mods Being Displayed in Updated Category

### ISSUE THREAD

**Issue by ArtaiosGreybark** [Nexus-Mods/web-issues#444]
## Bug/error being reported:
Brand new mods are being displayed in the Updated category as well as in the New category.
![1](https://user-images.githubusercontent.com/24878945/34174621-e145fc8c-e4f9-11e7-9c4c-5ea160d29572.png)
![2](https://user-images.githubusercontent.com/24878945/34174643-ef35d15a-e4f9-11e7-9514-7ac568476da7.png)
![3](https://user-images.githubusercontent.com/24878945/34175160-bb292bd0-e4fb-11e7-8e32-f2daba0b78c0.png)

## Steps to reproduce:
Look at a mod in the New category and see if you can find it in Updated. It is likely that the mod will have only one single file upload. See screenshots for an example.

## Expected result:
Brand new mods that only ever had one file upload should not appear in the Updated category.

## Actual result:
Brand new mods with only one single file upload appear in both the New and Updated category.

**Comment by iamtiz** [comment]
assigned #155974001

**Comment by iamtiz** [comment]
Fixed
