### ISSUE TITLE
File deletion not indicated

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#445]
Clicking "Delete" does not deliver any confirmation or reaction.
Clicking it again for being sure finally results in doubled, tripled etc. posts on file and user's moderation history, although confirmation in this screen has not been delivered.

![binning files or images](https://user-images.githubusercontent.com/31516762/34184371-a73c5fec-e51f-11e7-95cc-7f2cf2ffa1ef.jpg)

**Comment by iamtiz** [comment]
Assigned #154016610

**Comment by iamtiz** [comment]
fixed
