### ISSUE TITLE
Manage comment dropdown appearing behind the buttons

### ISSUE THREAD

**Issue by phillnexus** [Nexus-Mods/web-issues#446]
![zindex](https://user-images.githubusercontent.com/17081405/34192708-d570606e-e5a3-11e7-854c-20b1c9a94501.png)
## Bug/error being reported:
Tile dropdowns are covered by gradient, therefore you cannot click any of the items in the dropdown list

## Steps to reproduce:
Hover over a '+' on a tile

**Steps to fix**
Set '.expandtile' to z-index 12, or rearrange all z-index elements in a way to bring these values down

Additionally - many child elements (here and elsewhere) have z-index values that aren't needed

**Comment by phillnexus** [comment]
I've also noticed buttons (on tile hover) and a few other things are covered by these transparent backgrounds/z-index values changing. There are also other things with incorrect z-index values, eg: button on the bottom of media

**Comment by allen-kennedy** [comment]
I've noticed the issue too, not only is the drop down menu blocked by the gradient, but on all hot files but the big top two, the lower 1/4th of the button you mouse over is blocked too. I'd upload a screenshot, however pu.ush doesn't capture mouse pointers, so it would be rather pointless.

**Comment by phillnexus** [comment]
It seems this is fixed now, yet the changes have caused more z-index issues, like in the commenting dropdown and the buttons on index pages (at the bottom of sections)

**Comment by iamtiz** [comment]
Assigned #154016908

**Comment by mrmason** [comment]
This should be fixed now. Please let us know if you see any other issues.
