### ISSUE TITLE
Images being squished

### ISSUE THREAD

**Issue by phillnexus** [Nexus-Mods/web-issues#447]
## Bug/error being reported:
I've noticed this on more than just one page. Images are being stretched/squished (as per the example).  See attached.

## Steps to reproduce:
Shrink site down to one of the smaller responsive breakpoints. To fix, remove the min-height. I can't tell why it's needed either, really.

If you want to keep the min-height, then add this property to the same image and it'll retain the size as well as the proper image aspect ratio:

object-fit: cover;

Along with an IE polyfill:

https://caniuse.com/#search=object-fit
https://github.com/bfred-it/object-fit-images/

It'll work for Edge img elements, but older version of IE will require the polyfill

![untitled-1](https://user-images.githubusercontent.com/17081405/34192913-f3aeb28c-e5a4-11e7-8832-12573b66036d.png)

**Comment by mrmason** [comment]
Thanks @phillnexus - This should be fixed now.
