### ISSUE TITLE
Empty areas around images in tiles

### ISSUE THREAD

**Issue by phillnexus** [Nexus-Mods/web-issues#448]
## Bug/error being reported:
My biggest pet peeve!

Images were designed to fill the width and heights of their containers. A lot of the time one image will, and the one/s directly beside it won't. It makes it look wonky, out of alignment, and tiles lose what should be their defined edges.

Here is an example of what I mean (it's a 2 frame GIF so you can easily see the difference):

https://i.imgur.com/Ghdh05M.gif

As of now, they don't fill the container

Removing the 'unset' width property, removing 'align-items: center' from the container and adding 'object-fit:cover' will make the images (of any ratio) fit the area while keeping the correct aspect ratio (along with any other considerations you need to make, particularly for IE as per my other report + responsive iterations).

This also works on news/media tile images and blends well with the new gradient-over-image style (no hard edges)

Alternatively you could apply this with background images to the width/height of the tile. Or not.

**Comment by mrmason** [comment]
Hey @phillnexus - This change has been made.
