### ISSUE TITLE
Premium Europe server 1 delivering Empty Files.

### ISSUE THREAD

**Issue by neiljwd** [Nexus-Mods/web-issues#450]
**## Bug/error being reported:**
I have a premium account (member neiljwd), and Files from Europe Server 1 are delivered empty, winzip/rar7zip cant open them.

**## Steps to reproduce:**
1: Go to a mod Eg: https://www.nexusmods.com/thesims4/mods/61?
2: Click files tab 
3: Click manual download.
-It will IMMEDIATELY start a d/l (from preferred server) oif this is Es1, the file will be empty.
4: If I click CDN or NA, It delivers a genuine mod file.
5:If I again click Europe Server 1, it is always Empty.

This is definitely happening reproducibly on Sims 4 files, and Im 99% certain it was happening last week when trying to pull Dragon Age: Inquisition mods.

(Ive not mentioned Europe server 2 it fails, but then works on subsequent tries intermittently)

**## Expected result:**
Get a working mod file/zip.

**## Actual result:**
Empty/unreadable zip file.

**Comment by Rod063** [comment]
same here trying to download Skyrim SE stuff

**Comment by iamtiz** [comment]
Hi, is this still happening for you?

**Comment by Rod063** [comment]
it happened another couple of times so far but atm everything seems to be all right
thank you
--
Inviato da myMail per Android Mercoledì, 03 Gennaio 2018, 10:18AM +01:00 da iamtiz  notifications@github.com :
