### ISSUE TITLE
Endorsement popup returned a second time; even after endorsing the mod in question.

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#451]
## Bug/error being reported:
I got the 'Endorsement reminder" popup.  Thought "Oh yeah".  Clicked endorse and went about my day. 

But today, I got the same popup for the same mod.  I thought "didn't I ..." clicked endorse and got a "you already endorsed this mod" message.  

## Steps to reproduce:
I quess:
1. Step 1 - download a mod
2. Step 2 - wait the appropriate number of days for the popup to appear
3. Step 3 - click Endorse and move on.
4. Step 4 - come back the next day for the repeated popup.
-->

## Expected result:
I was not expecting to get the popup twice, especially after I already endorsed the mod.  

## Actual result:
See Error being reported above.

**Comment by iamtiz** [comment]
Assigned PT #154017221

**Comment by iamtiz** [comment]
Hi, has this happened again recently? If so, which was the affected mod?

**Comment by PoorlyAged** [comment]
Since this error is the result on downloading mods, and I haven't downloaded any mods lately, It has not happened again.
