### ISSUE TITLE
Can't deny friend request outside of forums

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#453]
The user pages on the new site only let you send and accept friend requests, but you can't deny ones you have been sent. So the only way to deny a request is to go to the forums site.

https://www.nexusmods.com/users/<user_id>

**Comment by iamtiz** [comment]
Hi, if you go to your account settings and then to the 'Friends' tab, you should see a 'PENDING FRIENDS' section (https://rd.nexusmods.com/users/myaccount?tab=friends). You should have the option to remove friends requests there. Let us know if that's not happening in your case

![friends](https://user-images.githubusercontent.com/3407947/34515060-54c8e736-f068-11e7-8617-cd9219db3fb9.png)

**Comment by ousnius** [comment]
Ah, I haven't found that section before.

But still, any plans to add a decline button for a pending friend request to the specific user's page as well? (the link I put above)

Currently, you can send requests, accept requests and remove friends via a user's page, but you can't decline a pending request.

**Comment by iamtiz** [comment]
We'll look into that :)

**Comment by iamtiz** [comment]
assigned #154662507

**Comment by iamtiz** [comment]
We added a dropdown with both "accept" and "deny" option to user profile pages
