### ISSUE TITLE
Some mods not downloading to NMM

### ISSUE THREAD

**Issue by Lords32** [Nexus-Mods/web-issues#455]
## Bug/error being reported:
Some mods, two in question, are not downloading to NMM or giving me manual download files. The two mods are Platinum curie the return and Looks Menu Customization Compendium. Already contacted the mod authors to see if I can get some help.
## Steps to reproduce:
I don't really know using NMM download works for most mods but for these two it isn't.

## Expected result:
downloading these mods and using them

## Actual result:
Nexus says I downloaded them but they aren't in NMM anywhere
https://gyazo.com/46472126c97c3be66164ab808059341c

**Comment by iamtiz** [comment]
Hi, one the mods (Platinum Curie) seems to not have published files at the moment. Did you get any answers from its author? The second mod is looking in good order though, which one of the files wasn't working?

**Comment by brunoarchie** [comment]
Can't download them too. The download simply don't start. I'm having the same issue with some Skyrim mods.

**Comment by iamtiz** [comment]
@Lords32 is this still happening?

**Comment by Lords32** [comment]
Not to my knowledge I bought the premium and can use different servers to download mods. I haven’t really download many mods in a while.

Sent from XFINITY Connect App



------ Original Message ------
