### ISSUE TITLE
Only one page of files (20) is displayed on an author's files tab even if they have more.

### ISSUE THREAD

**Issue by keypuncher1** [Nexus-Mods/web-issues#456]
## Bug/error being reported:

When looking at the files tab of an author in the nexusmods skyrim site, only one page of files showing the first 20 appears (which specific ones depending on the sort), regardless of how many there are.

## Steps to reproduce:

Go to the following URL.  Files tab says there should be 77 mods for Skyrim, only 20 appear in a single page.

https://www.nexusmods.com/skyrim/users/37834630?tab=user+files&BH=1

Go to the user's page on the old site, there are 7 pages:

https://old.nexusmods.com/skyrim/users/37834630/?tb=mods&pUp=1

Changing the sort changes which 20 files are displayed.

## Expected result:

Multiple pages of files available for authors with more than 20 mods.

## Actual result:

Only one page of files available for authors with more than 20 mods.

**Comment by iamtiz** [comment]
Hi, is the pagination not appearing for you? Or is it there, but just with a single page?

![screenshot-2018-1-3 user mihailmods](https://user-images.githubusercontent.com/3407947/34515800-c7008554-f06b-11e7-955b-c2670182873b.png)

**Comment by keypuncher1** [comment]
Under Firefox 57.0.3 (64-bit) the pagination is not appearing.
Under IE11, the pagination is there but shows only a single page.
Under Chrome 63.0.3239.132, the pagination is there but shows only a single page.

**Comment by iamtiz** [comment]
What's your user name on the Nexus? Does viewing the website as a guest (not logged in) have the same issue?

**Comment by keypuncher1** [comment]
Username: keypuncher
No, viewing as guest shows pagination normally - hadn't actually checked that until you asked.
I reported this issue because someone else had mentioned on reddit that it happening to them also, and I checked and discovered I was having the same issue.

**Comment by iamtiz** [comment]
assigned #154435446

**Comment by iamtiz** [comment]
fixed
