### ISSUE TITLE
Image Share button "Manage" is unusable

### ISSUE THREAD

**Issue by Pixelhate** [Nexus-Mods/web-issues#457]
## Bug/error being reported:
 After uploading an image to the Image Share, the button "Manage" (Edit Image Information) is unusable and the text can't be corrected if needed-->

## Steps to reproduce:
1. Upload an image, make a description, publish.
2. Try to click the Manage button
## Expected result:
Having access to the description again to bring correction.
## Actual result:
Nothing happen.

**Comment by iamtiz** [comment]
Hi, is the issue still happening or you?

**Comment by Pixelhate** [comment]
Hi, the issue seemed fixed, thank you.

Envoyé: mercredi 3 janvier 2018 à 10:55
De: iamtiz <notifications@github.com>
À: Nexus-Mods/web-issues <web-issues@noreply.github.com>
Cc: Pixelhate <piha@gmx.com>, Author <author@noreply.github.com>
Objet: Re: [Nexus-Mods/web-issues] Image Share button "Manage" is unusable (#457)


Hi, is the issue still happening or you?

**Comment by Pixelhate** [comment]
The issue seemed fixed now, thank you.
