### ISSUE TITLE
Add doublepost prevention while posting comments

### ISSUE THREAD

**Issue by katzenpapst** [Nexus-Mods/web-issues#458]
While commenting a mod, there is no indication whatsoever to tell you whenever you clicked submit or not. There is no kind of flood protection either, so that the probability of accidentally doubleposting is quite high.

## Steps to reproduce:
Go to any mod and post a comment. Or answer to a comment.

## Expected result:
The submit button disappearing, or turning gray, maybe with a spinning gear symbol. In any way, the submit button should not be clickable until the page reloads to show the comment I wrote.

## Actual result:
No indication whatsoever that I clicked. Then, several seconds later, the page reloads.

**Comment by katzenpapst** [comment]
Correction: This only occurs sometimes.

I could reproduce it here right now: https://www.nexusmods.com/fallout4/mods/23660
First, I posted one regular comment. Here the loading indicator appeared.
Then, right away, I answered to that comment. NOW nothing happened and I ended up with a doublepost.

**Comment by iamtiz** [comment]
Assigned #154018043

**Comment by iamtiz** [comment]
fixed
