### ISSUE TITLE
Mod page status hidden from public view

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#459]
## Bug/error being reported:
When hiding a mod page from public view it currently takes about a minute before the page is indicated as being hidden while on the old page the status hidden is indicated immediately.
Further on, Moderation, Hide (no files) does not open a gap for adding a comment, that currently only works if selecting Manage, Set mod to hidden. See image below.

## Steps to reproduce:
Repeat: Unhide the mod on the new site and compare it with mod page on the old site.
Hide the mod page again, please, as no file has been uploaded yet.
This is the page on the new site
https://www.nexusmods.com/skyrimspecialedition/mods/12618
on the old site
https://old.nexusmods.com/skyrimspecialedition/mods/12618/?

![hiding mod from public view](https://user-images.githubusercontent.com/31516762/34360687-5aa0140a-ea63-11e7-9fcc-af6ffb092aff.jpg)

**Comment by iamtiz** [comment]
Assigned #154018060

**Comment by iamtiz** [comment]
fixed
