### ISSUE TITLE
Loading cogs have "..." characters spinning with them

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#46]
Just a small annoyance here.
The loading cogs on the site have a visible text content of "..." spinning around in circles.

This is due to the content of the element:
```html
<div class="loading-wheel" style="display:block;">...</div>
```
Should be:
```html
<div class="loading-wheel" style="display:block;"></div>
```

**Comment by Thallassa** [comment]
I think it's just in the "updates" one, the spinning wheel when it's loading mod filters doesn't have any noticeable dots.

**Comment by ousnius** [comment]
The "Updates" one uses a <div>, while the others that don't have the dots are prepended via the ::before CSS section.

**Comment by verenion** [comment]
Assigned PT#151000942

**Comment by verenion** [comment]
Fix has been pushed
