### ISSUE TITLE
Horrible Mod Post Page Lags

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#460]
## Bug/error being reported:
Mod Page now takes up to 90+ seconds after hitting "Submit" to actually Post on the forums, leading to massive double, triple, quadruple (I have actually seen up to 9 duplicates) posting all over the Nexus. Old version did not do that as persistently or egregiously.

## Steps to reproduce:
1. Post a comment on any mod page
2. Click Submit
3. Your toddlers will finish High School before the post is actually posted
4. Notice an error
5. Hit Edit
6. Correct your error
7. Hit Submit
8. After your newborn child hits puberty with still no repsonse of any kind whatsoever from Nexus, hit Submit again. And again. And again....
9. Watch in awe as Nexus steadfastly ignores all of your posting attempts
10. Smash head into desk as Nexus suddenly posts 1,362 copies of your post
11. Try in vain to find any way to delete 1,361 of them
12. Cry

## Expected result:
1. Nexus acknowledges the Submit button-press by disabling the Submit button and displaying a progress bar or spinny thing so at least we know it's trying, and so we can't hit Submit again on that post
2. Nexus actually posts Submitted user content in under 5 seconds. Example: 1-2 seconds like pretty much every other forum/blog in the world- even high-traffic ones like Reddit, Twitter, Facebook, etc.

## Actual result:
Please see Steps 1-12 above- Reserving duplicate input for the mod forums. >.<

**Comment by iamtiz** [comment]
Duplicate. #458

**Comment by iamtiz** [comment]
See #458
