### ISSUE TITLE
Moderation, mod/mod page binned, files gone

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#463]
Binning mod/mod page - files themselves displayed as 0 - have dissapeared.
I have not removed the files in "Edit attributes" etc. 

Due to the 500 character limit for giving reasons for a ban on the new site I turned to the according menu on the old site as there was a lot to be posted to make the decision  transparent.

After binning the mod and issueing the ban the files in Files tab have dissapeared on the new and old page.

https://old.nexusmods.com/newvegas/mods/64295?tab=files
https://rd.nexusmods.com/newvegas/mods/64295?tab=description

![mod removed files away](https://user-images.githubusercontent.com/31516762/34395525-2f5e9740-eb61-11e7-9ac0-db56e500e3f3.jpg)

**Comment by iamtiz** [comment]
Assigned #154018190

**Comment by iamtiz** [comment]
fixed
