### ISSUE TITLE
Incorrect links when arriving on the page from google

### ISSUE THREAD

**Issue by Zabraxa** [Nexus-Mods/web-issues#465]
## Bug/error being reported:

Coming from google, links can be incorrect. 

## Steps to reproduce:

Open google search for bleak enb fallout4

### Example:

![image](https://user-images.githubusercontent.com/34910254/34405988-d6751b8a-ebb6-11e7-9578-80f3595ab632.png)

![image](https://user-images.githubusercontent.com/34910254/34406012-fabd8838-ebb6-11e7-817b-92cd1d294384.png)

![image](https://user-images.githubusercontent.com/34910254/34406029-143d79c6-ebb7-11e7-93aa-3de1490fbb8a.png)

## Expected result:
Skyrim Mods are not shown under Fallout4

## Actual result:
A skyrim Mod is shown under Fallout 4

**Comment by iamtiz** [comment]
known issue
