### ISSUE TITLE
'+' icon on games and mods unusable

### ISSUE THREAD

**Issue by Kojote13678** [Nexus-Mods/web-issues#466]
## Bug/error being reported:
When hovering over the '+' icon found above games or mods (so that you can favourite them) you are unable to maneuver the mouse to click the second option,.

## Steps to reproduce:
Step 1: Move mouse over plus icon
Step 2: Attempt to select the second or lower option
Step 3: Fail to select second or lower option

## Expected result:
To be able to select the second or lower option

## Actual result:
The drop down menu falls out of focus and you are unable to select the second option

**Comment by Zyphlex** [comment]
I would like to add to this that the problem can be circumvented and most likely has to do with something CSS related.

**Doesn't work:**
When viewing the page normally on my browser, it does not work.

**Works:**
When opening the console and putting it on the right hand side, it does work. (Image for clarification)
![chrome_2017-12-29_17-14-44](https://user-images.githubusercontent.com/9112162/34441429-05304354-ecbc-11e7-9660-286012dd688b.png)

**Comment by phillnexus** [comment]
Duplicate

https://github.com/Nexus-Mods/web-issues/issues/446
