### ISSUE TITLE
File hidden, but not displayed as hidden immediately

### ISSUE THREAD

**Issue by zcul** [Nexus-Mods/web-issues#467]
File hidden on rd site has not been displayed as that for more than a minute after hiding it (no loading animation or anything like that). Old site: New status has been displayed immediately.
Happened here:
https://rd.nexusmods.com/skyrim/mods/29192
https://old.nexusmods.com/skyrim/mods/29192/?

**Comment by iamtiz** [comment]
Duplicate of #459

**Comment by iamtiz** [comment]
fixed
