### ISSUE TITLE
Can only see multiples of 20 mods

### ISSUE THREAD

**Issue by louissellers217** [Nexus-Mods/web-issues#469]
## https://rd.nexusmods.com/skyrimspecialedition/mods/categories/
Category states found 193 items but only displays 9 pages of 20 mods.  9x20 = 180   What happened to other 13?  This happens on all catagories

## Expected result:
Expected result would be 9 pages of 20 and a tenth page of 13

**Comment by iamtiz** [comment]
Hi, are you blocking any tags or authors?

**Comment by louissellers217** [comment]
no  the problem as this morning has been fixed but what I was seeing was
i.e. Animations found 77 mods which would require 3 pages of 20 and 1 page
of 17 but it was only showing 3 pages of 20.
