### ISSUE TITLE
Certain javascript function not currently working

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#47]
At some point just over an hour ago the update notification and the filter dropdown on the mod search page both stopped working. Ousnius says they're using a common javascript function. We both experienced the bug. I waited to report it in case it resolved itself but it is still not working. 

https://cdn.discordapp.com/attachments/232170227734020097/356841149555671040/unknown.png

**Comment by verenion** [comment]
Fix has been pushed.
