### ISSUE TITLE
Cannot manage media with large numbers of user images

### ISSUE THREAD

**Issue by Eolhin** [Nexus-Mods/web-issues#470]
## Bug/error being reported:
Thumbnails of images posted by the mod author are now on the same page with those posted by users of the mod in the area where the author can change the order of the images.
Manage --> Media
The reason this is a problem is that some mods have truly huge numbers of images posted by the users, and it seems to want to load all of them.

## Steps to reproduce:
The author of the Inigo mod recently added a holiday image to both the Inigo/SKYRIM Nexus page, and the Inigo/SKYRIM SPECIAL EDITION Nexus page.  He then went to move that image to the second position so that it could be clearly seen at a glance in the strip of images on the pages.

On the Skyrim SE Inigo page, that worked fine, as there are currently 378 images posted by users for that mod.
On the Skyrim Inigo page, however, the Manage --> Media section hung for a while trying to load, then crashed.  There are 2109 images posted by the users on that page.  After repeated tries, and repeated failures of the page to load to a point where it could be used to move the image, he gave up for a while.  Then he tried accessing the media management tools from the old layout, which does not try to load all of the user thumbnails, along with the author thumbnails, and that worked fine.

## Expected result:
Being able to move the order of the thumbnails (especially author thumbnails) around successfully, even if there are a lot of user-posted images.

## Actual result:
The page to manage the media in the new layout does not function if there are too many images to load/manage (usually in the user section of images).

Possible solutions:  
Initially load the media management page with only 20 thumbnails of each kind loaded, but the choice to expand it to more with a click.
or
Load the media management page with the section for user images collapsed, but the option to expand it again.
or
Have the management of the author images on a separate page from the management of the user images.

**Comment by iamtiz** [comment]
Pagination for user images has been added
