### ISSUE TITLE
Updates not showing.

### ISSUE THREAD

**Issue by JimmyRJump** [Nexus-Mods/web-issues#473]
## Bug/error being reported:
The "Updates" button shows there are updates but there's no new updates added in the roll-out list.  Not an error of showing there's updates when there aren't any.  Just the new update links not showing in the list.

Using Google Chrome, fully updated.

**Comment by ousnius** [comment]
Most likely same issue as #475 .

**Comment by iamtiz** [comment]
@JimmyRJump Is this still happening for you?

**Comment by mrmason** [comment]
Closing this - please let us know if you're still experiencing issues.

**Comment by JimmyRJump** [comment]
@iamtiz 
Apologies.  Was without internet (and of course email) from 21 January until 1 February.  Am back at old provder and old email is restored as of now.

No, I am no longer having the issue.  Notifications in the Update menu/panel seem to work properly.
