### ISSUE TITLE
Not getting notifications for my mods on SSE

### ISSUE THREAD

**Issue by Asaforg** [Nexus-Mods/web-issues#475]
None of the posts/submissions are showing up in my notifications from my mods on SSE. I have no issues with my Skyrim LE mods. I must keep checking the SSE mod pages to see if anything new has been posted or submitted for my approval.
 I have checked my settings and everything looks correct.

Here are links to my two mods in SSE:

https://www.nexusmods.com/skyrimspecialedition/mods/13870

https://www.nexusmods.com/skyrimspecialedition/mods/13499

**Comment by ousnius** [comment]
I've been having the same/similar issues the past few days with the CBBE SSE mod page. The number for the notification appears on the new and on the old site, but not the notification itself.

https://www.nexusmods.com/skyrimspecialedition/mods/198

**Comment by iamtiz** [comment]
Ok, there was an issue with mods having an apostrophe character in their title. You should receive notifications from now on
