### ISSUE TITLE
Use new skin as default not working anymore

### ISSUE THREAD

**Issue by alfx3** [Nexus-Mods/web-issues#477]
Up to like one-two weeks ago I had the new skin layout set by default, but now the old one is always enabled by default and I have to use rd.nexusmods.com. I think it'se a bug, unless it has been disabled by default. In that case an option would be useful in settings.

**Comment by ousnius** [comment]
They have a balancing system that divides people up into the old and new site, the new site was never the default for everyone (I think it was for a short time but that was a bug).
