### ISSUE TITLE
Badly overlapping comment moderation menu

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#478]
Instead of typing an explanation, here is the issue:

<img width="928" alt="badlyoverlappingmenu" src="https://user-images.githubusercontent.com/31491675/34491491-ea8ad778-efe3-11e7-9084-d3955ac26d08.PNG">

Browser: Chrome 63 (64-bit) (US)

**Comment by TheRealElianora** [comment]
Got this same thing on mod comments on my page and came to do a bug report but eh, Milla was faster.

![image](https://user-images.githubusercontent.com/26447310/34502260-61867328-f01b-11e7-83e1-5aea07a9703f.png)

**Comment by phillnexus** [comment]
There are z-index issues all over the site, unfortunately. It seems every time something is fixed, something else breaks. They should probably delete all values and start again from 0. It's a mess at the moment.

**Comment by iamtiz** [comment]
Assigned #154016908
