### ISSUE TITLE
File options not saved when uploading a mod file

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/web-issues#479]
## Bug/error being reported:
When uploading a mod file, the "_Inform downloaders of this mod's requirements before they attempt to download this file_" setting is ignored after save.

## Steps to reproduce:
1. Upload a new file for an existing mod. Tick "_Inform downloaders of this mod's requirements before they attempt to download this file_" and click save:  
   > ![](https://user-images.githubusercontent.com/230581/34508135-5b7d4e7c-f00a-11e7-9c91-2300089b42a1.png)
2. For the uploaded file, click _Manage > edit details_:  
   > ![](https://user-images.githubusercontent.com/230581/34508167-9973f564-f00a-11e7-8994-a02692f20a5b.png)

## Expected result:
The "_Inform downloaders of this mod's requirements before they attempt to download this file_" checkbox should be checked, since it was ticked when adding the file.

## Actual result:
The checkbox is not checked, regardless of whether it was ticked while uploading the file:
> ![](https://user-images.githubusercontent.com/230581/34508201-df4422ee-f00a-11e7-97f8-f535099c177d.png)

<sup>(Also, the "File options" label is misaligned.)</sup>
  
If you tick the box on the existing file and save again, it'll be remembered this time.

**Comment by iamtiz** [comment]
assigned #154130309

**Comment by iamtiz** [comment]
fixed
