### ISSUE TITLE
Switching to BBCode in editor scrolls the editor to the bottom

### ISSUE THREAD

**Issue by verenion** [Nexus-Mods/web-issues#48]
Every time you swap to BBC input the description is automatically scrolled down to the bottom of the description, regardless of where you are or were previously. Happens each time you swap between the modes, not just the first. Minor thing, but a big pain for larger descriptions.

See #35

**Comment by Pickysaurus** [comment]
I think this happens on the old site too

**Comment by iamtiz** [comment]
Yes, this is the behaviour of the library we are using
