### ISSUE TITLE
Consistency in user tabs 

### ISSUE THREAD

**Issue by MrTroubleMaker** [Nexus-Mods/web-issues#480]
## Bug/error being reported:
Most of the  tabs when viewing a user and your own page have dropdown lists for game, sort by, order and shown. The user video tab is missing "games list" also when selecting "show 80 items" it shows 8a0

See the attached pic

Thanks!

![image](https://user-images.githubusercontent.com/35054968/34509579-60fe04b8-f019-11e7-9e8d-5d34f2f66902.png)

This video tab issue is also present when looking at "My Nexus account" 

![image](https://user-images.githubusercontent.com/35054968/34509683-f5e79caa-f01a-11e7-89b8-f3a3b17fe4df.png)

**Comment by iamtiz** [comment]
assigned #154130342

**Comment by iamtiz** [comment]
fixed
