### ISSUE TITLE
Comment cards layout messed up

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#481]
## Bug/error being reported:
Weird spaces on the sides of the comment cards and some comment cards on the BUGS tab are not centered and shifted to the left

![nexuserror16_1](https://user-images.githubusercontent.com/33193255/34514404-f761a6a6-f075-11e7-8b4c-de4c01180f83.png)

Posts tab has the same layout issues

![nexuserror16_2](https://user-images.githubusercontent.com/33193255/34514409-fa2c4332-f075-11e7-8241-0c845192fcb4.png)

## Steps to reproduce:
It is everywhere on the site

## Expected result:
Comment cards take full width of the grey area

## Actual result:
Comment cards have less width and it's placement is broken

**Comment by iamtiz** [comment]
assigned #154130445

**Comment by mrmason** [comment]
This should be Fixed.

**Comment by Zur13** [comment]
Comment cards seems to be centered. But should not they be wider? Does those huge empty side spaces was made intentionally?
![nexuserror16_3](https://user-images.githubusercontent.com/33193255/34735225-6279dcb4-f577-11e7-82eb-700ed90cb00d.png)

**Comment by mrmason** [comment]
This is intention - to make reading large blocks of text easier.
