### ISSUE TITLE
Upload sometimes not possible

### ISSUE THREAD

**Issue by katzenpapst** [Nexus-Mods/web-issues#483]
## Bug/error being reported:
Just uploaded a new version of this mod:
https://www.nexusmods.com/fallout4/mods/28619
Afterwards, I wanted to upload an ESL version, but no matter what I do, I get this message:

"A file with that name and version already exists on the server. Please change either the file name or the version."

I tried changing the version, the name, the type, nothing works. 

Now suddenly it works. I *think* the problem is the real filename on my PC.

**Comment by iamtiz** [comment]
The real filename shouldn't matter, as a new one is given by our website appending the mod id and the version. 

This is the format we use: [given_file_name]-[mod_id]-[version].[extension], where given_file_name is the name you enter in the upload form. The extension is the only part of the original uploaded file we use

**Comment by iamtiz** [comment]
Has the proplem happened again, by the way?

**Comment by katzenpapst** [comment]
Haven't happened lately...

**Comment by iamtiz** [comment]
I'm closing the issue for now, then
