### ISSUE TITLE
Article area broken

### ISSUE THREAD

**Issue by phillnexus** [Nexus-Mods/web-issues#484]
## Steps to reproduce:
Go to https://www.nexusmods.com/fallout4/mods/21872?tab=articles

![image](https://user-images.githubusercontent.com/17081405/34544034-14dd3f70-f138-11e7-93a9-4efe77c9b577.png)

**Comment by phillnexus** [comment]
Also, on an unrelated note, I notice that some elements at full-width continue to shrink in various places. Comments, mod descriptions. Why not just drop the entire site down to the ~1200 width?

eg: https://i.imgur.com/XFdD8d3.png

This was what it was primarily design for and will work best, it'll also more closely mirror the older site. It's so much better for readability.

**Comment by rscottexe** [comment]
We can't go down to 1200px due to the ads, Phill, which was one of the requirements of the redesign. If we go down to 1200px, we need to find somewhere else for the 300x250 ad that isn't in that top ad area.

**Comment by phillnexus** [comment]
The redesign called for an MREC and a billboard, the production version of the site uses an MREC and a leaderboard

And since it's completely responsive, it's easy to solve

To accommodate an MREC + leaderboard at that size, it only needs to grow by less than 100px from the 1280 breakpoint (940px wrapper width). Which equates to a new wrapper width of 1048px (rather than 1400). This will allow both ads plus all the benefits that come with being closer to the old dimensions, being easier to read, easier to scan through and so on.

In fact, even at a smaller size, you can fit in an MREC and 2 leaderboards (almost 3, 3 would work with a little more height) as per the attached example. All while using far less space than the current iteration of the site. This also means it would work on sizes above this, and looking at the current size, the leaderboard is being cut out at 1300px (which is extremely early to be cutting an ad out)
![ads](https://user-images.githubusercontent.com/17081405/34559774-47181956-f197-11e7-88ad-de88d0aff5cf.jpg)

**Comment by rscottexe** [comment]
The specification changed while you were working on it, Phill, to accommodate a 300x250 and a 900x250. On top of that, the two ads cannot touch and need some padding between them so they can be differentiated from one another by the user, else they'll fall foul of the ad requirements in our contract.

**Comment by phillnexus** [comment]
I recognise the spec changed, my point was that bringing it up as a _requirement of the redesign_ was a moot point as it was a different ad config at the time. Between the two, there's now a difference of over 200px in width and almost the same amount in height, but the code never changed to accommodate the new spec.

The leaderboard (728x90) HTML/CSS is still labeled and sized for a billboard (970x250). Since the spec changed, there's now a huge waste of space at some sizes. For example - 1300px. There's almost 200px of vertical space being taken up for no reason. Vertical space is precious on any site containing ads.

With the suggested layout (mocked up in about 15 seconds, which unfortunately did not allow for padding), there's still a difference of ~350px between the sizes, there's a lot of room for padding. 1048px could simply become 1090px (rather than 1400). These are google ads right? You shouldn't need anywhere near as much clearance as is currently on the site.

If anything, they'd [take issue](https://i.imgur.com/VIByi32.jpg) with the waste of vertical space above the fold. Using Steam stats as a source for gamers (or you can check analytics...) - If you go to a game's mod index, then over 10% of Steam's users are only going to [see this](https://i.imgur.com/96QY5q8.png). Here's the [same thing](https://i.imgur.com/eDYW73W.jpg) with a smaller width - more content in view, more ads and all ads have padding. And one more time with [one ad](https://i.imgur.com/R5d1lJ9.jpg) as per the current site. And it still benefits those at 1080p/1440p. Tighter ads, less space wastage, more content in view.

Or the ad wrapper could be in a break-out box, slightly coming out from the sides. Or span the width.

At the moment there are multiple things out of alignment (buttons, content containers the grid) due to reducing the width of containers in the largest breakpoint, there's almost no point to having a grid. It looks like the media queries are randomly borrowing bits from smaller breakpoints. Going back to the redesign, another requirement was not to have the site end up like the existing site with a mashing of inconsistent rules and styles, yet these sort of changes bring it well onto that path. It affects every user on any page. Changing the width and ad placement (for the better, compared to what's currently there) makes everything easier to read and digest, it gives ads a more sensible layout, and it wouldn't affect dozens of objects on content pages.

I can't see how the width can be for the sake of ads when there are so many solutions at hand.

It's hard _not_ for me to care, but it's also free advice. ¯\_(ツ)_/¯

**Comment by rscottexe** [comment]
Hi Phill,

I made quite a few edits from my original response. Have you read them?

**Comment by rscottexe** [comment]
So, to clarify, the website NEEDs to accommodate a 300x250 and a 970x250 in the top-fold. While you might not be seeing those right now, that might be related to the ad provider having a hickup or there not actually being any ads to show to you right now, that is the default requirement.

**Comment by rscottexe** [comment]
In the office in the UK right now, this is what I'm seeing when logged out.

![capture](https://user-images.githubusercontent.com/17083726/34563253-d30c8b70-f149-11e7-8298-04612051727f.PNG)

It's these sizes that need to be accommodated in the top fold, and I'm not sure how we can reduce the width of the content area itself (or margins/padding) anymore while still accommodating those sizes.

**Comment by phillnexus** [comment]
I hadn't seen the changes until now (and have never come across a 970x250 on the site), but even still, 2 of the above suggestions would work with ads of varying sizes, and it would **_only_** need to occur at the highest width. Everything below that could collapse very neatly and you'd still be able to show more ads as you trickle down (and reap the benefits of having a smaller width for content).

I assume the changes I'm referring to (smaller width for content) are related to readability? With that assumption, the way I see it is that you could:

1. Change the site's max width (which solves the readability problem) and implement a breakout box ([like this](https://i.imgur.com/6DTXa4H.png)) - **it _only_ occurs** on the highest breakpoint (and only affects those who see ads). Once you're out of that ~1400px browser width, the ads would respond as per the layouts in previous comments, which will allow for more ads (still including the 970x250, up until the browser width is less than 970), more vertical space etc etc. It could also be styled in a way that makes it a little [more appealing](https://i.imgur.com/9FWghkU.png).

2. Or continue making changes to the wrappers/containers/widths here and there (that affects everybody regardless of site-support status, and only solves the readability issue in part)

I just don't know how far #2 is going to get you in the long run

For whatever it's worth, this was a suggestion early on, to allow people to opt-in to the highest width (or to opt-out if it were default)
