### ISSUE TITLE
The site keeps adding the \ symbol whenever I use brackets, apostrophe, or quotes when commenting/submitting bug reports

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#485]
## Bug/error being reported:
Site adds the \ symbol whenever I use brackets, apostrophe, or quotes when commenting/submitting bug reports.  This has been happening on the Skyrim Nexus site but could also be happening on the other sites too.

## Steps to reproduce:
1. Type in a comment under Posts or submit a bug report under Bugs using the above symbols.
2. Click Submit
3. Comments will have the \ added next to brackets, apostrophes, & quotes when used.

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
My comments/bug reports not being littered with the \ symbol

## Actual result:
My comments/bug reports being littered with the \ symbol when the above symbols are used in Posts/bug reports.

**Comment by iamtiz** [comment]
Assigned #154171443

**Comment by iamtiz** [comment]
fixed
