### ISSUE TITLE
Drop down menu of "Manage" button disappears to fast

### ISSUE THREAD

**Issue by Vijabei** [Nexus-Mods/web-issues#489]
## Bug/error being reported:
The drop down menu disappears/closes when I move from the button into direction of the options.

![manage](https://user-images.githubusercontent.com/3897414/34641879-ca0191a2-f30a-11e7-92ef-b348b5d7196a.png)

## Steps to reproduce:

1. Open any Modpage from your own Mod
2. Click onto the "Manage" button until the menu opens
3. Move with your mouse courser downwards =)

## Expected result:
Keep the menu open to select an option

## Actual result:
The drop down menu closes

## Setup:
Windows 10, Firefox  57.0.4 (64bit)
also tried: Edge and Chrome (same result)

## Reason:
Only the font of the button is activ while hover with the mouse courser. The new box appears directly under the background of the button. So there is a space between activation area and drop down area. When you leave the font to slow, you are leaving the activationa  rea before you reached the drop down menu.

## Solution(s):
1. Make the whole button active or increase the active area  (my preferred version)
or
2. Put in a delay of 1 or 2 seconds until it closes when not active
or
3. Move the drop down menu up directly to the font

## Work around:
1. Be fast wih your mouse
2. Use mouse wheel to  scroll down, that keeps it active

**Comment by iamtiz** [comment]
Hi, which mod(s) of yours are affected?

**Comment by iamtiz** [comment]
assigned #156011516

**Comment by iamtiz** [comment]
Hi, we are unable to replicate this issue. Is it still happening for you?

**Comment by Vijabei** [comment]
Hi, yes.

I will try to make a video of it. 

I just tested it with newest Firefox, Windows 10, an this MOD https://www.nexusmods.com/fallout4/mods/13884

**Comment by iamtiz** [comment]
Ah, yes, got it now

**Comment by iamtiz** [comment]
Fixed
