### ISSUE TITLE
Cannot rename images by pressing Enter

### ISSUE THREAD

**Issue by cirion** [Nexus-Mods/web-issues#49]
Not a huge problem, but it would be really nice if I could just press Enter after typing in a new image name to have it save. Instead it dismisses the rename window and reloads the page. Manually clicking on the "Submit" button works fine.

<img width="1077" alt="screen shot 2017-09-12 at 10 14 04 am" src="https://user-images.githubusercontent.com/321492/30339502-0ffc8ab2-97a4-11e7-89fe-63e3b8ba6e6e.png">

(I know this is new functionality, thanks for adding it! Really nice to be able to finally rename some old pictures.)

Using Firefox 55.0.3

**Comment by mrmason** [comment]
Assigned `PT##151041296`

This should be implemented now.
