### ISSUE TITLE
Inconsistent aspect ratio of the Morrowind image in games list

### ISSUE THREAD

**Issue by Contrathetix** [Nexus-Mods/web-issues#490]
## Bug/error being reported:
The list of games supported by Nexus features an image for each game. The images are laid out in a table-like form, and the dimensions of each image seem to have been adjusted to the same value to keep the table-like layout consistent (400x225 pixels for me, I do not know if it differs for others).

While other images in the list are 400x225 px, the image for Morrowind in the games list has a size of 640x300 px which makes its aspect ration wider than that of the other images. The Morrowind image is still scaled to fit the width of 400px allocated to each image in the list, so it ends up having more empty space below it than the other images because of the inconsistent aspect ratio.

Screenshot:
![nexus-mw-gamelist-bug](https://user-images.githubusercontent.com/16085353/34649209-107463b4-f3b3-11e7-9b8a-e6d8859e80c0.jpg)

The Morrowind image HTML turns up for me as the following (the dimensions are set in it by the website):
```
<img class="lazy game_cover" onerror="imgError(this,'https://rd.nexusmods.com/contents/images/games/cover_empty.png');" src="https://staticdelivery.nexusmods.com/images/games/cover_100.jpg?check=1515168536" alt="Morrowind" title="Morrowind (4697) " width="400" height="225">
```

The server serves the Morrowind image as a 640x300 pixels .jpg file for me (url):
* https://staticdelivery.nexusmods.com/images/games/cover_100.jpg?check=1515168536

For reference, the Oblivion and Skyrim images are served by the server as 400x225 pixels .jpg files (url):
* https://staticdelivery.nexusmods.com/images/games/cover_101.jpg?check=1515168536
* https://staticdelivery.nexusmods.com/images/games/cover_110.jpg?check=1515168536

## Steps to reproduce:
1. goto https://rd.nexusmods.com/games
2. find Morrowind in the list (should be visible without expanding)
3. observe the smaller height compared to nearby images

## Expected result:
The expected behaviour would be that each image has the same aspect ratio or dimensions. The intended one seems to be 400x225 for me, I do not know if it depends on desktop/window resolution.

## Actual result:
Other images are 400x225 pixels, the Morrowind one is 640x300 pixels. The Morrowind image ends up vertically shorter due to it being scaled to fit width.

## Other thoughts:
If something needs clarification or if there is anything missing, I can definitely try to offer more info on the issue (first time reporting a bug). Thank you!

**Comment by iamtiz** [comment]
assigned #154135007

**Comment by mrmason** [comment]
This has been fixed for new games being added, we will go back and fix the old images for all of the games with the wrong size tiles soon.

**Comment by Contrathetix** [comment]
Hi and sorry about the delay. All the images I could see in the list now display correctly, including the Morrowind image. Thank you very much for looking into it. I will close the issue now, too, should have done it ages ago but I forgot. :)
