### ISSUE TITLE
ELFX + Wearable Lanterns (black texture problems) 

### ISSUE THREAD

**Issue by BufoAlvarius** [Nexus-Mods/web-issues#491]
![screenshot103](https://user-images.githubusercontent.com/33851190/34705308-a091e76a-f510-11e7-8f64-4c0269ece746.png)
## Bug/error being reported:
<When using WL with ELFX some interior\exterior texture turn into black>

CFG i7 3770 k, 12 gb mem, GTX 1060 6gb
### Example:
1. Step 1
2. Step 2
3. Step 3
-->

**Comment by mrmason** [comment]
You might want to raise a bug report on the mod page - this is a bug tracker for website issues.
