### ISSUE TITLE
Cannot block users from imageshare comments.

### ISSUE THREAD

**Issue by JimUKNexus** [Nexus-Mods/web-issues#493]
You could do this on the old site and it was handy for dealing with loremongers, the only current option is to block PMs.

**Comment by iamtiz** [comment]
I'm afraid that the displaying of blocking options on images was an aesthetic bug on the old site, and such feature was never actually implemented for things other than mod pages. But we'll look into it in the future

**Comment by iamtiz** [comment]
Assigned #155654608

**Comment by iamtiz** [comment]
This is now done: authors are able to block users from images, supporter images and videos too
