### ISSUE TITLE
Randomly blocked tags

### ISSUE THREAD

**Issue by DuskDweller** [Nexus-Mods/web-issues#494]
## Bug/error being reported:
Tags being randomly blocked from search results.

## Steps to reproduce:
Go in your https://www.nexusmods.com/users/myaccount?tab=content+blocking tab and look for blocked tags you never decided to block.

## Expected result:
Show me the bewbs!

## Actual result:
Didn't show them.

![blockedtags](https://user-images.githubusercontent.com/7575288/34825754-037b66d4-f6d4-11e7-980e-3e4dc8d12ad9.png)

**Comment by adamelders** [comment]
Same here - I have "saved games", "translation", and "extreme violence/gore" blocked, when I don't remember blocking those. When I click on the tags to remove them (as instructed above), nothing happens.

Also, may be unrelated, I am getting the following errors in dev console when loading this settings page:

GET https://www.nexusmods.com/contents/Scripts/BBoC-1515678912.js net::ERR_TOO_MANY_REDIRECTS myaccount?tab=content+blocking:45

Uncaught ReferenceError: $ is not defined
    at myaccount?tab=content+blocking:48

**Comment by iamtiz** [comment]
Do these blocked tags still appear after being removed, or was it just a one-off episode?

**Comment by ksteven64** [comment]
I am also having this issue.  I never clicked these tags, but they are turned on.  When I click on a tag, it will turn red and show that is is blocked.  When I click on the tag again, I get the message:  "You are already blocking this tag".  The tag won't toggle.
