### ISSUE TITLE
THE ENTIRE CSS, AND OPTION TO REVERT BACK TO 1970-2017 style!!!!!

### ISSUE THREAD

**Issue by Feay** [Nexus-Mods/web-issues#495]
## Bug/error being reported:
WHITE text on LIGHT blue background, heeeellloooo mcfly contrasting colors need to be used, look at a color chart **please** for luma vs saturation of perceived color in HUMANS not googleAI. 
Material layout for IPHONES **force-ware** on to all devices including Desktops.
no way to revert to sensible UI design.
main navigation "button" expander is on the wrong side it should at least be on the LEFT.
****Poor** ui design choices**, all the mod's screen shoots in the search list have a gradient filter upon them washing out 2/3 of them.
Same as above but descriptions in white text are now 1/2 up these screen shots, combined with your force-ware css layout it makes reading the descriptions difficult.
Poor color choice scheme, battleship gray on more gray.
visual elements lack boarders.
the banner add is now 1 billion time more obnoxious as a square making dead space and stupid adds.
google ads.
**Worst possible** ways to display the: Files, articles, images....nav bar witch is now a confusing drop-down box with the same colors on everything making it very hard too find.
for the love go back to a sensible UI design or give PC users the options not to use an gold plated Iphone! 
----
The search is not giving proper results, typing in "Skyrim textures" has no results, BUT
there are texture mods for skyrim with skyrim in the title.

## Steps to reproduce:
go to https://www.nexusmods.com

## Expected result:
**I expect a revert to the old layout and an option for mac people to use the new one on their iMACs, and implement browser detection so that there will be a MOBILE vs DESKTOP view.**

## Actual result:
We are all in faith still.

**Comment by VictorDragonslayer** [comment]
I'm not a big fan of this redesign, but can tolerate it. If you *really* can't use the site in its current state, then use https://old.nexusmods.com/?
