### ISSUE TITLE
Manage bug report options behaviour unclear.

### ISSUE THREAD

**Issue by customtemplar** [Nexus-Mods/web-issues#497]
## Bug/error being reported:
Various options on the "Manage" drop down have unclear behavior. Namely close issue and make issue private.

## Steps to reproduce:
Use the above mentioned functions

## Expected result:
Using an above options would apply the relevant visual changes to the bug report upon use, making activation of the option clear.

## Actual result:
Using an above option results in no visual change to the bug report unless the page is manually refreshed, making it unclear if the option is functioning correctly.

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by iamtiz** [comment]
assigned #154282135

**Comment by iamtiz** [comment]
Hi, we are currently unable to reproduce this issue. Did it happen on a specific mod?

**Comment by customtemplar** [comment]
I only manage the mod I co-author, Wasteland Imports, so that is my only test point.

**Comment by iamtiz** [comment]
Is this problem still there for you?
