### ISSUE TITLE
Bug report status dialogue non-conventional behaviour

### ISSUE THREAD

**Issue by customtemplar** [Nexus-Mods/web-issues#499]
## Bug/error being reported:
When changing bug report status, clicking the submit button does not close the dialogue box. Convention is that a submit/okay button applies the user selected change then closes the box, the box only remains open if an error message is to be displayed or the requested action did not take place.

## Steps to reproduce:
1. Change bug report status
2. Click submit
3. Dialogue box remains open

## Expected result:
The dialogue box closes.

## Actual result:
The dialogue box remains open.

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by iamtiz** [comment]
assigned #154282135
