### ISSUE TITLE
Advanced Search, Return does not submit

### ISSUE THREAD

**Issue by soraphis** [Nexus-Mods/web-issues#5]
URL: http://www.nexusmods.com/skyrimspecialedition/mods/searchresults/
Steps to reproduce:
write something in the search fields, hit return -> nothing happens.
Expected result:
... hit return -> form is submitted

![image](https://user-images.githubusercontent.com/3066582/29889104-48aec64e-8dc3-11e7-9dd1-e22df2c9adc9.png)

_____
the problem:
the submit "button" is actually a `<a>` element with some js handlers. 

the fix:
replacing it with an `<button type="submit">submit</button>`
apply the js functions to the form "onSubmit" method (using event.preventDefault to stop the page reload)

**Comment by mrmason** [comment]
We're not going to fix this as the new website is so close.
