### ISSUE TITLE
Centered images in WYSIWYG editor

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#50]
The WYSIWYG editor's preview for mod page descriptions doesn't align images to the center of the page unless the image is currently highlighted. The final page has it centered correctly, just not the editor view.

```
FO4 CBBE, mod ID 15
[center][img]http://i.imgur.com/k2z0DwA.png[/img]
[size=5]The most customizable body mod available is back![/size][/center]
```

**Comment by Rrrafau** [comment]
assigned #151041791

**Comment by verenion** [comment]
Fix has been pushed
