### ISSUE TITLE
Chrome Issues

### ISSUE THREAD

**Issue by yazannimri** [Nexus-Mods/web-issues#500]
![5](https://user-images.githubusercontent.com/35376545/34883915-592fa870-f778-11e7-8534-9a7702b4f000.JPG)

![4](https://user-images.githubusercontent.com/35376545/34883909-557e9c36-f778-11e7-8537-5769703478a5.JPG)

![3](https://user-images.githubusercontent.com/35376545/34883905-52c7de12-f778-11e7-99bc-0993ac27e290.JPG)

![2](https://user-images.githubusercontent.com/35376545/34883904-50354d88-f778-11e7-9e6f-23c3d48bde7c.JPG)
## Expected result:

to work normally and be able to download mods
## Actual result:

website looks weird and download buttons dont work (download with manager or download manually)
![1](https://user-images.githubusercontent.com/35376545/34883903-4d26795a-f778-11e7-8db7-dde0910cec45.JPG)

**Comment by mrmason** [comment]
Are you blocking javascript ?

**Comment by yazannimri** [comment]
i shouldnt be i mean chrome was working fine on nexus then all the sudden it stopped working yesterday. i looked through the settings didnt find anything related to java. i have been using Firefox in the meantime but i just checked chrome and all the sudden it is working normal now after a full 24 hours of acting strange. any ideas what might have caused it to do that? i have used nexus over a year and this is the first time i have seen it do something like this

**Comment by mrmason** [comment]
We've rebuild the JS and CSS files so that everyone should be loading new ones. We'll keep an eye on it.
