### ISSUE TITLE
Mod bug tracker: "Allow users to submit bugs" is actually "Allow anyone to submit bugs"

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#502]
## Bug/error being reported:
The "Allow users to submit bugs" option for mods is actually an "allow anyone to submit bugs" option.

## Steps to reproduce:
Modify a mod's settings to set "Allow users to submit bug reports" to false.

## Expected result:
The bug tracker will remain publicly visible and usable to the mod author.

## Actual result:
The bug tracker disappears entirely. Existing bug reports are not deleted, but attempting to reply to them (e.g. in another open tab that hasn't been refreshed) yields a blank error message (just an orange box!). The bug tracker is therefore not usable to the mod author and not transparent to the public.

## Desired fix:
Allow mod authors to set bug tracker permissions in a more granular fashion. I don't know what others would be interested in, but I'd like to use the bug tracker as a public display of bugs that are known, verified or credible, and that I intend to address, while using my comment section for initial reports and triage; that way, users who want to know if there's a _definite problem_ have an uncluttered place to look.

Possible permission options could include:

Disabled
Private (visible only to authors)
Locked (visible to all, but only authors can submit)
Public (visible to all; open to all)

Failing that, the wording of the option should at least be clarified (e.g. "Enable the bug tracker: Yes/No").

**Comment by iamtiz** [comment]
Done, we added more options for the mod bug tracker
