### ISSUE TITLE
Publishing Functiopn Hangsd weith Spinny Gear Icon

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#505]
## Bug/error being reported:
After clicking "Publish" when uploading a new mod OR a new file to an existing mod, the system hangs with a spinning gear icon. Day before yesterday I left the machine in this state and it was still hung and spinny when I returned 11 minutes later. Clicking the little red X on the spinny gear icon closes it, then pressing Publish again results in "Your mod is already Published" or words to that effect.

**Comment by iamtiz** [comment]
assigned #154356558

**Comment by iamtiz** [comment]
fixed
