### ISSUE TITLE
can't download, neither from nmm or manual

### ISSUE THREAD

**Issue by anonymousfartmachine** [Nexus-Mods/web-issues#509]
Bug/error being reported: can't download, neither from nmm or manual
Steps to reproduce:
1. i tried nmm and it start at 1024kb/s for a few seconds after that it goes 1-6kb/s
2. manual is waaay the same, it goes 1-3kb/s
Expected result: i can download mods normally
Actual result: can't even dwonload a file that sized 4.8mb, it failed after few seconds

**Comment by kreyben** [comment]
Same issue here, can you fix these problem please?

**Comment by a1Rondog** [comment]
This happens to me on Skyrim and Fallout 4 Nexus downloads; some don't even trigger any d/l. Just nothing happening. Wish someone would look into it. The old web site never did this. And now there's no choice in going back, either.

**Comment by iamtiz** [comment]
@a1Rondog is the pop-up appearing for manual downloads?

**Comment by a1Rondog** [comment]
The pop-up for donations as well as the one to get premium service do pop up but that's it, no file download for either manual or Nexus installer. It's only on a few mods that this happens but as I have said, it occurs when trying both Skyrim and Fallout 4 Nexus web sites.

**Comment by iamtiz** [comment]
Can you give us a couple of examples of mods which are working, and a couple of mods which are not working for you?

**Comment by a1Rondog** [comment]
Not working: https://www.nexusmods.com/skyrimspecialedition/mods/5224?tab=files, none of the choices will start to download, whether by Nexus or manual; https://www.nexusmods.com/skyrimspecialedition/mods/12604?tab=files, the old file will d/l but won't work with my version of Skyrim and the new version won't start to d/l, again, in neither Nexus or manual attempts. Those are just a couple that I have come across. 

Some of the ones that have worked, having triggered the Nexus program to d/l and prep the install are: https://www.nexusmods.com/skyrimspecialedition/mods/659?tab=files, https://www.nexusmods.com/skyrimspecialedition/mods/4145?tab=files and many others. 

If you need more info just ask. I hope we can get this fixed and I will help as best as I am able. Thanks for your help, too.
Cheers.

**Comment by iamtiz** [comment]
Looks like there's a correlation with files having requirements.
Just to make sure: the download is not starting when you press the "download" button in the pop-up, under the requirement list?

![requirements pop up](https://user-images.githubusercontent.com/3407947/35503121-197b592e-04d7-11e8-93f9-c1deff452ac5.png)

**Comment by a1Rondog** [comment]
Let me clarify: When I click to download the file (in this case VIS 3.12.27) THIS pop-up comes up but the file does not open or start NMM to download the file I had clicked on. I already have the Unofficial Skyrim Special Edition Patch so I do NOT need to click on that. I have downloaded many files that have requirements (which I have already downloaded and installed) and there does not seem to be a problem with accomplishing the transaction with those files. 

I don't think this is the issue I am experiencing. But I'm no scholar, either lol I've been using this system for the last several years so I feel I am quite familiar with the basics of how it works but the behind-the-scenes of the actual transaction between file downloads is not my forte. 

Thanks for your continued help and please don't hesitate to query more for any needed examples. I'm more than happy to be of some assistance. Cheers

**Comment by rscottexe** [comment]
If you click that "Download" button it will download the file you want, not the requirement. Have you tried that?

**Comment by a1Rondog** [comment]
OMG, now I feel like a real dork. I just tried it with VIS sorting file I want and it seems to be working. I didn't even realize that on that pop-up it was for the FILE I'm attempting to d/l. I was thinking it was a short cut to d/l the required file. (face-palm, for sure)

Ok, that seems to clear things up and I'll try it on the other mods I have been unable to attain. Thanks so much for pointing out the obvious to me. And for not being a shmuck about it lol Cheers, man.
