### ISSUE TITLE
WYSIWYG editor not showing embedded videos

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#51]
Videos embedded using ```[youtube]``` don't show up in the preview of the description editor. They show on the final page and in the source BBCode.

If not the video, it should at least show the URL or attribute to edit or remove it properly (similar to the ```spoiler``` tag).

**Comment by Rrrafau** [comment]
assigned #151042007

**Comment by verenion** [comment]
Fix has been pushed
