### ISSUE TITLE
Manage Media - Your Mod Images - Drag n drop images up the page does not scroll upwards

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#511]
## Bug/error being reported:
Manage Media - Your Mod Images - Drag n drop images up the page does not scroll upwards. On old nexus if you have many images (several pages worth), any new images you upload typically get planted at the end of the list of image thumbnails. Then you would drag n drop the images individually up to its intended position among the other images.

## Steps to reproduce:
Upload new images for a mod with many images, try and drag n drop the newly uploaded image up the page in Google Chrome.

### Example:
https://www.nexusmods.com/skyrimspecialedition/mods/12649?tab=images
Mod with lots of images, introduce say another 7 examples of normal map variations on the diffuse map .. Then try to drag n drop them further up the list of images, so drag bottom image to top of page

## Expected result:
As you drag n drop upwards, there would be an invisible area your mouse enters near the top edge of your browser window which triggers the whole page to scroll downwards, enabling you to get your image to the top of the images

## Actual result:
No scrolling of the page occurs. So you have to drag n drop the image up a few rows which are visible and drop it there, then manually scroll the whole page a few more lines of images ... rinse and repeat until you get your image all the way up to where you want it positioned in the sequence of images.
Then do the whole proces for however many images you have uploaded = Sooo tedious compaired with the old site which had this nailed (well apart from the odd hiccup of exactly where the image stayed put which invariably was after an image you wanted it to be before)

**Comment by JimmyRJump** [comment]
I use the mouse-wheel to scroll up and down the upload page while "holding" the picture.  No problems going up when doing that.   I'm talking about adding pictures to the Media section using _Images---> Add An Image_.

I've never added so many images to a mod I needed to scroll in any direction to see the first or last image.

The link you added gives me a "you don't have permission to do that" error.

**Comment by m0lz** [comment]
@JimmyRJump The issue is not about using the mouse wheel, its about using Drag n Drop to do the same which worked fine on the old site with Chromium.

Some of us need to present a lot of images, are you saying we should all be like you and not add so many images ?. And if you have "never" added so many images as to need to scroll in any direction, how do you know that for you using the mouse wheel to scroll works with no problems?. White man speak with forked tongue.

The link I gave is to an adult page on Nexus. You need to be logged in there to see it, and have agreed to the site terms and conditions that you are old enough to be a member and see such pages.

**Comment by JimmyRJump** [comment]
@m0lz 
The error is a no permission error while I'm logged in alright, probably because the picture the link points at has either been taken down or you yourself have added some restrictions to it.

I have a Premium membership at The Nexus and I don't have any filters that block adult content.

I was meremy adding mu own info on the matter, so, no need to get all worked-up about it.  Have a nice life.

**Comment by m0lz** [comment]
My apologies, I thought I had linked the Images tab, but I had actually linked the (new site) media tab url while trying to drag n drop the image during editing the mods images .. I guess anyone looking into this issue would not be able to access my mod page at that level of editing because of access rights, so I have edited the link to be just at the images tab.

Thank you for pointing it out, and again my sincere apologies for being a bit snippy.

**Comment by wills661** [comment]
It is wonderful when a person knows he is a bit over the top with patrons at this web site It is just a Pity that there are no others that can admit their mistakes when dealing with there Bread an Butter.

**Comment by iamtiz** [comment]
Assigned #156011645

**Comment by iamtiz** [comment]
fixed
