### ISSUE TITLE
Mod Page - Images Tab - View Image : Only views images of one page of images

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#512]
## Bug/error being reported:
Unable to use the View Image tools (Left and right arrows < >) to scroll through the mods entire list of images from ALL PAGES on the Images Tab

## Steps to reproduce:
Look at the Images Tab of a mod, which has too many images to fit on one page
https://www.nexusmods.com/skyrimspecialedition/mods/12649?tab=images
That one currently has two pages of images.
Click the View Image so that the image broswer tools pop up
Click the right arrow repeatedly
To view ALL images, you will need to come out of the Image viewing tools, select the Second page on the images tab, then View an image from that page to continue scrolling through the rest of them.

## Expected result:
It would feel better if when you got to the last image on that page, and clicked the right > arrow again, then the first image of the second page would feed and all subsequent images

## Actual result:
You can only scroll through all the images on one page, and no further without changing page first. Whereas when you upload them they are all in one long list of images and kept in that sequence, so you would imagine that the viewing image tools may be able to access all images from all pages in that same order without having to step out of the viewer to change page.
Users may think they have reached the end of the images when there could be important images with relevant information they needed on the second page they may never realise are there.

**Comment by iamtiz** [comment]
Assigned #156011625

**Comment by iamtiz** [comment]
All author images are now displayed in the pop-up gallery, whatever the current pagination position is
