### ISSUE TITLE
My nexus account video tab

### ISSUE THREAD

**Issue by MrTroubleMaker** [Nexus-Mods/web-issues#513]
When looking at "my nexus account video tab" from the main url like 
https://www.nexusmods.com/users/myaccount?tab=videos&BH=0
it will show all the videos you have
![clipboard01-m](https://user-images.githubusercontent.com/35054968/35016755-0a0dc8b2-fae8-11e7-98af-dd5b6d1250f8.jpg)
If you use a link from a game page like 
https://www.nexusmods.com/fallout4/users/myaccount?tab=videos&BH=1
it will only show the videos you have for that game
![clipboard01-f](https://user-images.githubusercontent.com/35054968/35016806-427c82ec-fae8-11e7-99d1-90b4d715c80e.jpg)

To make "my nexus account video tab" consistent it should either show all the videos or have it like the user page version (and old page) where there is a games drop-down menu
![clipboard01-u](https://user-images.githubusercontent.com/35054968/35016908-a7d6c8c8-fae8-11e7-8cdf-17477799fb82.jpg)
![clipboard02-o](https://user-images.githubusercontent.com/35054968/35016910-aae03752-fae8-11e7-8234-f7ca9ba79f11.jpg)

Thanks!

**Comment by iamtiz** [comment]
assigned #154393345

**Comment by iamtiz** [comment]
fixed
