### ISSUE TITLE
Mod page incorrectly displaying "Some files not scanned"

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#515]
## Bug/error being reported:
Author AKSYON0V has reported that their mod page is incorrectly displaying the virus scan warning "Some files not scanned"

## Steps to reproduce:
Affected mod page:
https://www.nexusmods.com/skyrimspecialedition/mods/14670?tab=files

## Expected result:
As all of the files have been successfully scanned, the page should display the usual "Safe to use" status.

## Actual result:
File displays a warning: "Some files not scanned".
Screenshot: https://i.imgur.com/2o1UC8n.png

**Comment by rscottexe** [comment]
From what I can see, the files haven't been scanned because they are over 200mb and therefore cannot be scanned by VT. As such, "some files not scanned" would fit perfectly!

**Comment by SirSalami** [comment]
Oh jeez, it is right over the limit. Closing!
