### ISSUE TITLE
Enormous post height

### ISSUE THREAD

**Issue by VictorDragonslayer** [Nexus-Mods/web-issues#516]
## Bug/error being reported:
Comment posts got ~1 inch of empty space above and below the text. It hurts readability.

## Steps to reproduce:
Open any comment section.

### Example:
1. [Go here](https://www.nexusmods.com/skyrim/mods/68425/?tab=posts)
2. Look

## Expected result:
Post height is text height + 0.5 centimeter above and below.

## Actual result:
Post height is text height + 2-3 centimeters above and below.

**Comment by mrmason** [comment]
This should be fixed!
