### ISSUE TITLE
Endorsements given - Error?

### ISSUE THREAD

**Issue by AKSYON0V** [Nexus-Mods/web-issues#518]
## Bug/error being reported:
@Aksyonov Endorsements are not added to the count profile, they should be added? Endorsements in the mod are different from what the Endorsements counter profile on the website?

## Steps to reproduce:
I go to the profile but do not see Endorsements given, the counter is at zero.

### Example:
1. User added in my mod 15 Endorsements, 
2. the second day I added +5 Endorsements
3. the same second when you add Endorsements they should appear in my profile and be counted?

## Expected result:
Endorsements given - Endorsements given need to grow? Depending on how many Endorsements I received in my modifications, right?

## Actual result:

![1](https://user-images.githubusercontent.com/35535377/35140853-2be2562a-fd12-11e7-8469-de828d82e867.jpg)

**Comment by iamtiz** [comment]
Hi, the "Endorsements given" represents the number of endorsements that *you* give to other mods, not the endorsements you have received

**Comment by AKSYON0V** [comment]
Thanks for the explanation :)
