### ISSUE TITLE
Favorite Games (visual)

### ISSUE THREAD

**Issue by GioGr** [Nexus-Mods/web-issues#52]
the empty ones should not display or only one and rest hidden

and at main page if a game is favorite it should not display + again but a heart or -
but since its a submenu prob heart+small plus

**Comment by mrmason** [comment]
We tried this and it didn't look very good. It looks better when the empty tiles are there - remember there is lots of different layouts this has to work under. 

We will take a look at the + submenu and see if there is anything we can do to make it more obvious, but this won't be a priority :)
