### ISSUE TITLE
[img] tag doesn't show picture in comments section

### ISSUE THREAD

**Issue by VictorDragonslayer** [Nexus-Mods/web-issues#520]
## Bug/error being reported:
[img] tag doesn't show picture in comments section.

## Steps to reproduce:
Attach a picture to your comment with [img] tag.

### Example:
1. I made a post with [img] tag in Ordinator comments section
2. In the comments section the picture is represented by [img=https://i.imgur.com/AKSGYNN.png], while in the thread it is displayed properly

## Expected result:
![](https://i.imgur.com/xiScVfy.png)

## Actual result:
![](https://i.imgur.com/pzfCoWo.png)

**Comment by rscottexe** [comment]
You're using the wrong syntax. It should be [img]https://i.imgur.com/AKSGYNN.png[/img]

The forum takes both versions, where as the site only takes the above.
