### ISSUE TITLE
Keyword search doesn't use default sorting option.

### ISSUE THREAD

**Issue by Hallowiener** [Nexus-Mods/web-issues#522]
Bug/error being reported:
Keyword search doesn't use default sorting option.

Steps to reproduce:

1. Have default sorting option set to "By recent files" in https://www.nexusmods.com/users/myaccount
2. Search using the search box on the top of the web page.
3. Get a search filtered by most downloads instead. 

Expected result:
Search results should display results sorted by recent files.

Actual result:
Search results are instead displayed sorted by most downloaded. 

It seems the default sorting option only applies when you search by selecting on mod categories, not on keyword searches. If this an intentional feature, then we are missing the option to change preference of sorting order by keyword search.

**Comment by mrmason** [comment]
Hello,

Do you mean the quick search that appears straight away or when you do a full search and it loads a new page with search results ? If in doubt can you submit a screenshot ?

**Comment by Hallowiener** [comment]
The search that loads a new page with the search results. 
![image](https://user-images.githubusercontent.com/11741609/35198242-e1f244f4-feb9-11e7-93cb-9f3f2f9c3a70.png)
I input keywords to search in the search box highlighted red, the website gives me the search results at the bottom which are sorted by "Downloads" despite having the default sorting option set to "recent files".

**Comment by iamtiz** [comment]
Assigned #154599671

**Comment by iamtiz** [comment]
fixed
