### ISSUE TITLE
Too dark overlay (edit css)

### ISSUE THREAD

**Issue by CHADREX** [Nexus-Mods/web-issues#525]
I suggest using these styles:

ul.tiles li .fadeoff {
    pointer-events: none;
    width: 100%;
    height: 60px;
    position: absolute;
    bottom: 0;
    background: -webkit-linear-gradient(top,rgba(56,56,56,0) 0,rgba(56,56,56,0.5) 100%);
    background: linear-gradient(to bottom,rgba(56,56,56,0) 0,rgba(56,56,56,0.5) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00383838',endColorstr='#80383838',GradientType=0);
}

**Comment by mrmason** [comment]
Please can you provide an example of where you're looking and before/after screenshots - the easier you make it for me to pass this suggestion onto the designer the more likely they'll consider it ;)

**Comment by CHADREX** [comment]
Okay, here: https://imgur.com/a/r9j51
