### ISSUE TITLE
Preview is not showing correct files

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#526]
I clicked on preview on this mod https://www.nexusmods.com/skyrim/mods/88681?tab=files and was surprised to see it was an esp... and then another zip? inside the first? Arthmoor would *never* do such a silly thing, so I had to download it to check. 

![image](https://user-images.githubusercontent.com/11600099/35229642-e70a81b0-ff61-11e7-9a42-c7a3810b6849.png)

Upon downloading I discovered that the zip contained the expected esp, bsa, and txt, all top level. None of that silliness that nexus preview was showing. 

![image](https://user-images.githubusercontent.com/11600099/35229465-81888c9c-ff61-11e7-99bd-4bbb523f6632.png)

Not sure if one of the scripts blocked in the console is related. They all seem to be related to my adblock.

**Comment by iamtiz** [comment]
assigned #154527686

**Comment by iamtiz** [comment]
fixed
