### ISSUE TITLE
Tagged file appearing in searches for which that tag has been blocked.

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#527]
## Bug/error being reported:
As reported by Yoshi#9620 in the public Discord:
Tagged file(s) appearing in searches for which that tag has been blocked.

## Steps to reproduce:
1. Attempt to block the "CBBE Bodybase" tag associated with Skyrim Special Edition, by either blocking the tag via user preferences or by selecting the appropriate tag from the "Tags must not include" section of the refine results section of a file listing.

2. Search for the mod titled "Rogue Armour HD - CBBE BodySlide"

## Expected result:
This file should not be shown in such results, as it seemingly has been tagged with "CBBE Bodybase": 
https://www.nexusmods.com/skyrimspecialedition/mods/14311

## Actual result:
The file is inaccurately being displayed in such searches and this issue may be affecting other files and tags.

**Comment by iamtiz** [comment]
assigned #154559764

**Comment by iamtiz** [comment]
This has been fixed. Let us know if there are other files with this issue though

**Comment by TheRealElianora** [comment]
Fallout 4: BodySlide Presets tag. Files show up on the front page and new mod listing even when tag is blocked: 

![2018-02-04_175415](https://user-images.githubusercontent.com/26447310/35779377-b6491c9e-09d4-11e8-829c-9818c408b9d1.png)
![2018-02-04_175427](https://user-images.githubusercontent.com/26447310/35779378-b65f9bc2-09d4-11e8-9d8c-15fc5f75f8b0.png)
![2018-02-04_175448](https://user-images.githubusercontent.com/26447310/35779379-b6773390-09d4-11e8-9c92-ae48613c3e72.png)
