### ISSUE TITLE
Image preview bug on any mod page

### ISSUE THREAD

**Issue by cranedrop** [Nexus-Mods/web-issues#528]
## Bug/error being reported:
There's a report bug button blocking the gallery icon when you decide to maximize the image. Hence it's hard to bring up the image preview on the bottom. Images are being cut off at the bottom.

## Expected result:
Images are auto full screen on the page and the gallery icon removed like so,
![image](https://user-images.githubusercontent.com/20478353/35264905-654dff46-0059-11e8-8fc1-eef470cc20e7.png)

You can see the difference between this image and the next one.

## Actual result:

You can see some parts are being cut off
![image](https://user-images.githubusercontent.com/20478353/35264407-9bfaa17c-0057-11e8-8fb6-bf0cd8e2950a.png)

You can see that the gallery icon is hiding behind the report bug button when you pressed the icon and you can bring it up by that small pixel space
![gif](https://thumbs.gfycat.com/InferiorInsignificantAmericankestrel-size_restricted.gif)

**Comment by iamtiz** [comment]
assigned #154560000

**Comment by iamtiz** [comment]
fixed
