### ISSUE TITLE
Excessive line spacing on "About Me" text

### ISSUE THREAD

**Issue by customtemplar** [Nexus-Mods/web-issues#529]
## Bug/error being reported:
Excessive line spacing for "about me" text

## Steps to reproduce:
Edit your "about me" text on the forums with a line break between 2 lines of text. This will display as expected on the forum, but have excessive spacing on the Nexus. It's also surrounded by a lot of dead space. Heaven forbid I write a full paragraph or embed anything.

### Example:
https://puu.sh/z7Jcr/c0eeebf6e4.png

## Expected result:
1 line break

## Actual result:
a `<p>` tag block flanked by `<br>`s

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by iamtiz** [comment]
assigned #154560029

**Comment by iamtiz** [comment]
fixed
