### ISSUE TITLE
Cannot change status of bug report on posting a reply

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#53]
![nexus](https://user-images.githubusercontent.com/31670524/30352772-db39d5ac-9819-11e7-8a99-8e52c1577827.jpg)
As shown in the image, the drop-down box is not a feature on the new site.

**Comment by Rrrafau** [comment]
assigned #151041296

**Comment by verenion** [comment]
Fix has been pushed
