### ISSUE TITLE
Comments locked on mod page yet new posts can still be made

### ISSUE THREAD

**Issue by Mystyk1** [Nexus-Mods/web-issues#530]
I just got a notification that someone replied to a comment on one of my old mods, which I thought strange, as I had previously locked the comments (on the old design, if that makes any difference).
It's fine if going to the forum side of things. It's appropriately locked with no option to reply.

I didn't find a similar thread here.

## Bug/error being reported:
New comments still being allowed into a locked comment thread on my mod page.

## Steps to reproduce:
Reply to any comment left already, or post a new comment and it acts as if the thread is not locked.

## Expected result:
The option to reply, or even comment, shouldn't be there, or it should give an error about the thread being locked and not accepting any new replies.

## Actual result:
Posts still being accepted in a locked thread.

Username on the Nexus: star-mystyk
Link to the affected mod: https://rd.nexusmods.com/newvegas/mods/45717

**Comment by iamtiz** [comment]
assigned #154560085

**Comment by iamtiz** [comment]
fixed
