### ISSUE TITLE
Downloaded mods not showing as being downloaded on website

### ISSUE THREAD

**Issue by blackandwhite88** [Nexus-Mods/web-issues#531]
## Bug/error being reported:

All mods I have downloaded show up on the Nexus website as not being downloaded, negating my ability to endorse any mods that I have been using. 
## Expected result:

Ability to endorse mods that I have been using.
## Actual result:
Website claims "You haven't downloaded this mod yet"

**Comment by iamtiz** [comment]
Hi, are your donwloads listed in your history (at https://www.nexusmods.com/users/myaccount?tab=download+history), or are they missing from there, too?

**Comment by rscottexe** [comment]
Similarly, are you using a mod manager to download the mods, like Mod Organizer?

**Comment by blackandwhite88** [comment]
I’m using Nexus Mod Manager

Sent from Mail for Windows 10

**Comment by blackandwhite88** [comment]
Yes, I have many mods listed there. 


Sent from Mail for Windows 10

**Comment by iamtiz** [comment]
Are you able to endorse mods through the download history page, but not in the mod pages themselves, then?

**Comment by blackandwhite88** [comment]
YES! I am. I will do it that way from now on. Thanks. I still wonder why this isn’t working for me as it should, but at least now I have a way to endorse. Thanks again. 


Sent from Mail for Windows 10

**Comment by blackandwhite88** [comment]
Actually, now that I look, there are still a lot of mods missing from that list that I have installed. Something is still off. 


Sent from Mail for Windows 10

**Comment by iamtiz** [comment]
If you try to donwload again one of the files which are missing from your history, does it appear? 
(This is to check whether the issue is with some specific files, or more random/general)

**Comment by blackandwhite88** [comment]
It does not appear. 

Sent from Mail for Windows 10

**Comment by iamtiz** [comment]
It could be specific to certain files, then. Which ones where affected?

**Comment by blackandwhite88** [comment]
I have hundreds of mods installed for both skyrim, SSE and Fallout 4, but
only the ones from a few years ago are listed. I downloaded a new mod last
night and it didn't even register on the website as being downloaded, even
after using it for over an hour. It seems to me that perhaps somehow my
Nexus Mod Manager is no longer linked to the website.

**Comment by iamtiz** [comment]
We are still unable to reproduce this issue.

Is this your user profile? https://www.nexusmods.com/users/2515336

What browser version are you using?

Do manual downloads register correctly?

**Comment by blackandwhite88** [comment]
That is not my profile. I think that may be an old profile that I used to use and forgot my password, but now my user name is 88blackandwhite88. The issue may be stemming from here. 


Sent from Mail for Windows 10

**Comment by blackandwhite88** [comment]
I use Google Chrome as my default browser, and it seems that my manually downloaded mods are indeed showing up in my download history with the ability to endorse. 


Sent from Mail for Windows 10

**Comment by iamtiz** [comment]
Could you try to download a file with NMM, check whether appears in your download history, and report the findings here (including which file you downloaded and for which game)? Thanks

**Comment by rscottexe** [comment]
Also, log out of NMM and log back in again with your current account. If you have more than one account, it's more than possible you're logged in to NMM and downloading files through your old account you no longer use. Which would explain all of this.

**Comment by blackandwhite88** [comment]
Wow… I feel like a blundering idiot. 
That was exactly it. I’ve just signed out and back in to find out that all the mods I’ve downloaded for the past couple of years have been installed with the wrong NMM account. So I logged in with my current active account and deleted a particular mod -Campfire by Chesko for Skyrim Special Edition- downloaded it again, and reinstalled it. I am now able to click the “Endorse” button and everything is working as it should. 
Thank you very much for helping me figure this out.

Sent from Mail for Windows 10
