### ISSUE TITLE
Very slow downloads on Premium

### ISSUE THREAD

**Issue by seanbrownypoints** [Nexus-Mods/web-issues#534]
## Bug/error being reported:
Download speeds of 10-20 KBps when using NMM, manual downloading is similar speeds.

## Steps to reproduce:
 Tried a variety of mods downloaded, some large ,some small.

user name on nexus     **seanxx**
mods tried
mid size *50-100mb
https://www.nexusmods.com/skyrimspecialedition/mods/2182?tab=files
small
https://www.nexusmods.com/skyrimspecialedition/mods/10477?tab=files
very large
https://www.nexusmods.com/skyrimspecialedition/mods/10472?tab=files

 I am having  trouble downloading  mods for Skyrim sse. As a regular member I was getting 1KB/s inside  NMM and nothing at all via manual download. So i decided to become a premium member, that took things to 20KB.s inside  NMM and again  no luck with manual downloads. 
**Steps taken**
 Tried the 4 servers, i am in Indonesia so  all  had roughly same speed. 
Tried manual downloading in incognito mode and using VPN - no impact.
Cleared my cookies/starting NMM as admin
Uncheck and checked  associate NXM URLS.
background info- Chrome/win 10/internet speed outside of nexus fine(10Mbps)
**Ping info**
Pinging cds.n2x4r7s4.hwcdn.net [205.185.208.141] with 32 bytes of data:
Reply from 205.185.208.141: bytes=32 time=305ms TTL=50
Request timed out.
Request timed out.
Reply from 205.185.208.141: bytes=32 time=305ms TTL=50
Ping statistics for 205.185.208.141:
    Packets: Sent = 4, Received = 2, Lost = 2 (50% loss),
Approximate round trip times in milli-seconds:
    Minimum = 305ms, Maximum = 305ms, Average = 305ms

**Comment by seanbrownypoints** [comment]
I   found that going back to the outdated  nexus website and manually downloading worked  fine (1200kbps).  On the old website  downloading via NMM and the new  website both manual and NMM downloading is still  crawling and  20 kbps.

**Comment by iamtiz** [comment]
Are you still experiencing this issue?
