### ISSUE TITLE
Does it download wrong or i'm just bad

### ISSUE THREAD

**Issue by BloodTroller** [Nexus-Mods/web-issues#535]
1. I downloaded the Multiplayer Stardew Valley mod
2. I tried to install it with the help of youtube
3. I saw that it was different (It has no .json or manifest)
4. It has just a zip / exe file in a rar file in a rar file!
5. What do i do ?

Please Tell me !!!

**Comment by BloodTroller** [comment]
Please help

**Comment by iamtiz** [comment]
Hi, if it's a problem with a specific mod you should contact its author, unless the problem was with the website (e.g. a corrupted file). 

Is this the mod you are talking about? https://www.nexusmods.com/stardewvalley/mods/501/
