### ISSUE TITLE
Possible Incompatibility with Microsoft Edge

### ISSUE THREAD

**Issue by TheOneEyedOcelot** [Nexus-Mods/web-issues#539]
## Bug/error being reported:
All minor pull down menus, such as those that are used to sort search results and switch between mod author images and user submitted images, are invisible. Major pulldown menus, such as the Updates and Games menus, function as intended.

## Steps to reproduce:
The issue appears to be related to use of Microsoft Edge vs. other internet browsers. All pull down menus work as intended when the website is accessed through other browsers, including Internet Explorer and mobile browsers. To reproduce, access the Nexus website through Microsoft Edge. You should find that the menus do not appear, but you can still click on where the menu items are supposed to be and make use of them.

## Expected result:
When clicked, pull down menus would show their respective menu items.

## Actual result:

When clicked, pulldown menus do not appear, but can still be used.
![nexus bug report](https://user-images.githubusercontent.com/35900973/35486506-8caeeabc-0434-11e8-8f0e-3a6c75455f7b.png)

**Comment by rscottexe** [comment]
I can't reproduce this error in Edge on my computer. The drop-downs show, and work, for me using default Edge without any mods/plugins/extensions for the browser and no internet security suites installed.

**Comment by TheOneEyedOcelot** [comment]
That's odd. Clearly, I've got something up on my end, but I have no idea what. I don't have any plug ins or security suites installed on Edge at all.
