### ISSUE TITLE
User Profile - Friends Page - Images too big

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#54]
On your own Profile page, go to the friends tab

Most of these images are the restricted size graphics of your forum avatar

This page stretches them to be approximately double horizontal and vertical pixel size, so most of them being based on avatars become a blurry mess

Is the new Nexus Mods ( AND FORUMS ) going to allow Avatar Anims / Images to be this size ?, or do the anim / image size presentation of friends need to be made smaller ?

**Comment by verenion** [comment]
Assigned PT#151049727

**Comment by iamtiz** [comment]
Made the presentation tiles smaller
