### ISSUE TITLE
Website not responsive (as in not responding) on mobile device (android 8.1 chrome)

### ISSUE THREAD

**Issue by msegers** [Nexus-Mods/web-issues#541]
## Bug/error being reported:
I went to the homepage of the fallout4 nexus page. I couldn't scroll, zoom or click on anything.

## Steps to reproduce:
go to https://www.nexusmods.com/fallout4/ on a mobile device.

### Example:
basically above.
I used a xaomi redmi 4x with lineageOS 15.1 (Android 8.1 close to stock).

## Expected result:
A working website

## Actual result:
The opposite

**Comment by iamtiz** [comment]
I can't replicate this issue at the moment. Does it happen on the main game pages only, or in any page?

**Comment by msegers** [comment]
It seems to work now again for me, that's pretty weird.
