### ISSUE TITLE
Incorrect dropdown list of countries

### ISSUE THREAD

**Issue by GazdaPaja** [Nexus-Mods/web-issues#542]
## **URL**
https://forums.nexusmods.com/index.php?&app=core&module=usercp&tab=core
## Bug/error being reported:
The dropdown list of countries is located in User CP:  My control panel - Settings - Profile Settings - General Account Settings is incorrect/old. The incorrect country name is "Serbia and Montenegro" which no longer exists, since 2006, and has been dissolved into two separate countries: Republic of Serbia (Serbia in short) and Republic of Montenegro (Montenegro in short). Also, both countries now have their own national flag.
## Steps to reproduce:
1. Go to User CP
2. Under General Account Settings scroll down to the section "Country"
3. Select either Serbia  **or**  Montenegro in the dropdown list
## Expected result
Both countries positioned separately in alphabetical order. Montenegro under "M" letter, Serbia under "S" letter.
## Actual result:
Nonexistent country name "Serbia and Montenegro"

**Comment by iamtiz** [comment]
fixed
