### ISSUE TITLE
Cannot Change File Position in Mod Manage Files

### ISSUE THREAD

**Issue by alfx3** [Nexus-Mods/web-issues#543]
## Bug/error being reported:
The file position of the mod files cannot be changed in Manage Files, despite the cursor changes to move icon.

## Steps to reproduce:
1. Go to Manage Files of any mod of yours.
2. Try to change a file position by dragging the file header.

## Expected result:
The file should change position.

## Actual result:
The file position remains fixed and the cursor acts as the text was highlighted instead.

**Comment by iamtiz** [comment]
Hi, changing file position in a mod has never been possible (same as the old site), but you're right the cursor was misleading. We removed that, for now.
