### ISSUE TITLE
Issue when submitting a translation of a mod

### ISSUE THREAD

**Issue by jihan02** [Nexus-Mods/web-issues#544]
## Bug/error being reported:
When submitting the translation of a mod, we need to indicate the name of the original mod and we have to write the first 3 caracters of the original mod's name so that it can be selected.
It doesn't work if the the third caracter of the original mod is a quote '
Exemple of original mod's name that doesn't work : De'zicrah - Custom Orc Voice Follower SSE

## Steps to reproduce:
- Add a new mod
- check Translation
- write de or de' or de'zicrah into the field "Original file your mod is a translation of
" and nothing happens.

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
i expect to be able to select "De'zicrah - Custom Orc Voice Follower SSE" but nothing pops up.

## Actual result:
empty list when searching for de'

**Comment by iamtiz** [comment]
Assigned #154838452

**Comment by iamtiz** [comment]
fixed
