### ISSUE TITLE
Download PopUp Window Donation Pane Text Error  {"receiver_user_id": 1, "payer_user_id": 1}

### ISSUE THREAD

**Issue by TheGreenDragon** [Nexus-Mods/web-issues#545]
## Bug/error being reported:
In the popup window for all mods that allow donations across all Nexus sites for all games, there is additional text that I do not believe should be visible to the user. 

{"receiver_user_id": 1, "payer_user_id": 1}

Shows just above the Donation input box. 

## Steps to reproduce:
Attempt to download any mod that allows donations from any Nexus site.
https://www.nexusmods.com/skyrimspecialedition/mods/5795/?
https://www.nexusmods.com/fallout4/mods/29447/?

## Expected result:
Not see the text?

## Actual result:
{"receiver_user_id": 1, "payer_user_id": 1}
https://imgur.com/a/c08Pw

**Comment by mrmason** [comment]
Thanks - Assigned `PT#154869292` and fixed!
