### ISSUE TITLE
No longer recieve comment reply notifications

### ISSUE THREAD

**Issue by deathneko11** [Nexus-Mods/web-issues#546]
Nexus ID:  Deathneko11

I primarily browse the Skyrim mods on the Nexus, and a few weeks ago I stopped receiving notifications for replies to my comments on mod comments pages.

I have not changed anything in my Nexus settings or preferences, and cannot find this setting anymore to see if it got turned off.

**Comment by iamtiz** [comment]
Notifications on comments replies should appear if you have the "Comments on your files, images and videos" option active in your notification preferences at https://www.nexusmods.com/users/myaccount
Which you seem to have, so you should receive them in theory. Can you provide us with an example or two of replies which you weren't notified?
