### ISSUE TITLE
Caracter set doesn't show up properly in some cases

### ISSUE THREAD

**Issue by jihan02** [Nexus-Mods/web-issues#548]
## Bug/error being reported:
When parsing the file contents of a mod, i noticed that some caracters specific to a country don't appear properly.

## Steps to reproduce:
- Look at my translation : https://www.nexusmods.com/skyrimspecialedition/mods/5872?
- Tab : Files
- Option : Preview File contents, a  window pops up
- the first line should include the caracter "ê" (which is specific to french langage) 
  but it's replaced with �

-->

## Expected result:
Bête instead of B�te

## Actual result:
B�te

**Comment by iamtiz** [comment]
assigned #154917380

**Comment by iamtiz** [comment]
fixed
