### ISSUE TITLE
Updated Mods [Feature Request]

### ISSUE THREAD

**Issue by RoyBatty64** [Nexus-Mods/web-issues#549]
When visiting a game's main page, Updated Mods should be next to "New Today" and "New This Week" with a count just like them. Mod updates are just as important, if not more important than new releases for users to be made aware of. Not only does this drive traffic to older mod pages, but also keeps users informed of critical updates. Currently it's 2nd lowest priority over next to "random", please implement this.

**Comment by suamor** [comment]
For the time being I recommend to use
https://www.nexusmods.com/skyrimspecialedition/mods/trackingcentre
