### ISSUE TITLE
Technical Problems occurring while on New Layout

### ISSUE THREAD

**Issue by NevadatheHighElfbabe** [Nexus-Mods/web-issues#550]
Hello, while on the new layout, I
am getting a image cut off while I am trying to work view images on my phone
http://i.imgur.com/jmRZu2r.jpg
This makes it so that I can't see the image, like its too big, the page can't be adjusted.

�

Also videos are not showing up where I am asked to put one in, i had to use the Youtuber embed directly in the description
http://i.imgur.com/oMffHC4.jpg

�

While on the old nexus, the edit's youtube link works perfectly
http://i.imgur.com/YD9R7dW.jpg

�

Note that these problems are only working on the new layout. If you could help, I would appreciate it.

**Comment by iamtiz** [comment]
Hi, could you provide us with links to those images/videos?

**Comment by NevadatheHighElfbabe** [comment]
I sure can:
https://www.nexusmods.com/skyrim/supporterimages/8460
^the first pic (note this is in supporter's section so there is some nudity

https://www.nexusmods.com/skyrim/videos/9027
^2nd video link

https://old.nexusmods.com/skyrim/videos/9027/?
^ The same as the 2nd link, but its under the "old nexus"

**Comment by iamtiz** [comment]
Assigned #154957187 (video) and #154957220 (images)

**Comment by iamtiz** [comment]
fixed

**Comment by NevadatheHighElfbabe** [comment]
Thank you friendly humans! :)
