### ISSUE TITLE
Manual Download

### ISSUE THREAD

**Issue by jayde59** [Nexus-Mods/web-issues#551]
## Bug/error being reported:

Cannot download files from Nexus manually, no problems with NMM
## Steps to reproduce:
Click on manual download button.

## Expected result:
Download a file from the Nexus

## Actual result:
says it will start in a few seconds but nothing happens.

**Comment by rscottexe** [comment]
Is this happening for all files or just some files? Can you give me a link to a file where this is happening? Also, have you tried changing the download method in your preferences to open it in a separate page, rather than a pop-up?

**Comment by MYSTERlOUSGUY** [comment]
Got same problem while trying to download Vortex and 2 other mods so i guess it affects all files.
Normally there should be link a user can click and download without waiting but this kind of link doesnt exist.
