### ISSUE TITLE
Unban Request Page Doesn't Accept Long Passwords

### ISSUE THREAD

**Issue by Haravikk** [Nexus-Mods/web-issues#554]
## Bug/error being reported:
Titles says it all; my account was banned unjustly a little while ago and I have been trying to contact someone about it ever since, but no-one apparently monitors the guest support tickets for the site (so please do something about that too).

This specific issue is however that the Unban Request page will not accept a password that is valid for use when logging in. I suspect it's being cut off on this page, so there must be a mismatch somewhere between what is a valid password length between registration, password updates and the Unban Request page.

## Steps to reproduce:
1. Change an account's password to be as long as possible (mine was 50 characters long, randomly generated with a password manager).
2. Get it banned.
3. Attempt to send an Unban Request.

## Expected result:
The request should be sent using a valid username and password.

## Actual result:
The Unban Request is rejected as having invalid login details, even though the very same details are valid to login with (but not much use while an account is banned).

**Comment by iamtiz** [comment]
assigned #155120502

**Comment by iamtiz** [comment]
This should be fixed now

**Comment by Haravikk** [comment]
Thanks, I can confirm there is no error when submitting the request now, but there is no kind of confirmation so I'm unsure whether it was definitely submitted successfully.

Should I file a separate issue asking for a confirmation message?
