### ISSUE TITLE
Rolldown menu not working as expected on PC

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#555]
## Bug/error being reported:
I am speaking of this side menu :
![screenshot_2018-02-09_14-31-08](https://user-images.githubusercontent.com/12874678/36030048-fd475b40-0da5-11e8-8c34-bf755dd0d34a.png)
If I click for example on "Mods", the submenu briefly rolls down, then I am redirected to the /mods page. There is no way, on PC, to click on one of the submenus of the "Mods" menu (new recently, etc).

## Steps to reproduce:
1. Open the side menu on PC
2. Click on Mods

## Expected result:
The menu should roll down, and I shouldn't get redirected to another page before being able to click one of the submenus.

**Comment by iamtiz** [comment]
Assigned #155120617
