### ISSUE TITLE
Multiple clicks to vote tags up

### ISSUE THREAD

**Issue by BWBNexus** [Nexus-Mods/web-issues#556]
## Bug/error being reported:
Voting a tag up requires multiple clicks in most cases. 

1.  On any mod click "+TAG THIS MOD"
2.  On the "Suggest tags for this mod" page" Click a "+" on a tag to vote up.

## Expected result:

The tag count increases after clicking one time

## Actual result:

Usually multiple clicks are before the tag count increases.
I have never voted a tag down so I don't know if the behavior is the same for that

**Comment by iamtiz** [comment]
Hi, can you provide an example of a mod where this happened for you?
Also, which browser are you using?

**Comment by BWBNexus** [comment]
1. Microsoft Edge - Current
2. Different Bodies - CBBE BodySlide Presets ( Tried setting Nude tag - Author states only Nude version available)
3. The only thing browser wise that is different is I edited my host file to force strict search results in bing as follows: 204.79.197.220 www.bing.com

**Comment by iamtiz** [comment]
assigned #155256964

**Comment by iamtiz** [comment]
This should be  fixed
