### ISSUE TITLE
Mod falsely shows pending media

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#557]
The mod "BodySlide and Outfit Studio" for Oldrim on my "Files (others)" list says that there are 9 pending media left to approve, however when checking on the page, there is no image and video that hasn't been approved, ignored or deleted yet.

![image](https://user-images.githubusercontent.com/7034795/36073236-730cc6b6-0f2d-11e8-897c-a088c25fcd16.png)

https://www.nexusmods.com/skyrim/mods/49015 (NSFW)

**Comment by iamtiz** [comment]
Hi, did you notice this issue in the "Files (others)" tab only, or in "Files (mine)" too?

**Comment by iamtiz** [comment]
assigned #155121080

**Comment by ousnius** [comment]
Right now, it only happens with this one specific mod. None of the others in either tab have the issue, so I can't tell.

**Comment by iamtiz** [comment]
fixed
