### ISSUE TITLE
Opening topic inside a mod's forums tab should put topic_id into browser URL

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#558]
When I click on a topic entry in a mod page's forums tab to open it up, I expect the URL in the browser to change like the following (topic_id):

Before click: https://www.nexusmods.com/skyrim/mods/2666/?tab=forum (NSFW)
After click: https://www.nexusmods.com/skyrim/mods/2666/?tab=forum&topic_id=1024852 (NSFW)

This isn't happening, though, so the only way to directly link to a topic is to get the URL from the page's HTML source. This was supported on the old site.

**Comment by iamtiz** [comment]
assigned #155121125

**Comment by iamtiz** [comment]
fixed
