### ISSUE TITLE
Weird menu item when editing mod files

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#559]
![image](https://user-images.githubusercontent.com/7034795/36074747-a52db544-0f44-11e8-8a07-cd47999c2ca7.png)

When editing this specific file on the FO4 CBBE mod page https://www.nexusmods.com/fallout4/mods/15 (NSFW), the menu item for "Upload new version" includes part of the description text of the file for some reason.

![image](https://user-images.githubusercontent.com/7034795/36074756-e072174e-0f44-11e8-9849-dc4bf78d261b.png)

**Comment by iamtiz** [comment]
Assigned #155121195

**Comment by iamtiz** [comment]
fixed
