### ISSUE TITLE
Author blocking doesn't work on front page

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#56]
At the moment one of the trending mods is a NSFW pubic hairs mod, and Im sick of seeing a giant image of a naked womans privates every time I opened the Nexus home page, so I blocked the author. 
Despite the message appearing saying their files won't be shown any more, their mod is still appearing on my front page like it was previously.

I have confirmed that blocking the author DOES stop their files appearing on the hotfiles on the old website design, so this appears to be missing functionality.

Let me know if you need me to provide any more info.

**Comment by Rrrafau** [comment]
assigned #151087539

**Comment by Nazenn** [comment]
Additional info: As of this morning the mod isn't showing up any more. Yesterday I did refresh several times, and close firefox (which automatically wipes my cache/cookies) with no success. No idea if its working now due to something you did, or theres just a weird delay on it but thought I'd let you know. Ive also tested a new author and their block has gone through as well.

**Comment by mrmason** [comment]
This should hopefully be fixed - please let us know if you see any other issues.

**Comment by TheRealElianora** [comment]
This is still happening on Media. I have several screenarchers blocked but their work is still shown on Media section and on the front page where Media is.

(On old site I was able to block them entirely when viewing image share).
