### ISSUE TITLE
Offset with [center] tag in first line of mod page sticky comments

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#560]
![image](https://user-images.githubusercontent.com/7034795/36074789-94ac91c6-0f45-11e8-9f46-cb3404b6dae1.png)

The first line(s) in a sticky/locked comment on a mod page has a slight offset to the left instead of being properly centered with the [center] tag, due to the "Sticky" and/or "Locked" signs pushing it away.

It should be in the center like the other lines below.

**Comment by iamtiz** [comment]
assigned #155121262

**Comment by iamtiz** [comment]
fixed
