### ISSUE TITLE
Searches in new Web site design no longer return useful results

### ISSUE THREAD

**Issue by VulcanTourist** [Nexus-Mods/web-issues#562]
## Bug/error being reported:
Searches in new Web site design no longer return useful results

## Steps to reproduce:
Example: search for "Fores New Idles" in Skyrim mods.

## Expected result:
That search result should at least include the mod of that same name:
Fores New Idles in Skyrim - FNIS (https://www.nexusmods.com/skyrim/mods/11811/)

## Actual result:
What that search actually returns is just one erroneous result:
Enderal- Fores New Idles Patch - FNIS Patch (https://www.nexusmods.com/skyrim/mods/76979)

Attempting to use the new redesigned advanced search features returns the same erroneous result when the "filename" is specified as "Fores New Idles".  Searching for this exact string using Google's search engine returns the correct mod's page at NexusMods as the leading result.  The site's own search engine fails to provide the same useful result as Google (and presumably other external search engines).

The new site design apparently now makes no distinction between a mod's file name and its **title**?  That makes the search feature virtually useless.

I've tried repeatedly to attach a 62KB PNG screen capture of the search results, but "Something went really wrong, and we can't process that file."

**Comment by rscottexe** [comment]
Thank you for letting us know it's shameful, that's really helpful.

I get three results when I search for "Fores New Idles". Including, funnily enough, Fores New Idles.

Are you by any chance blocking tags, and if so, are you blocking one of the tags that Fores New Idles has specified. You can check your blocked tags here: https://www.nexusmods.com/users/myaccount?tab=content+blocking

**Comment by VulcanTourist** [comment]
I was in fact filtering a few tags: "Translation" and about half a dozen language tags.  I had long since forgotten doing it, but the original motivation was constantly seeing foreign-language versions of mods in the default most recent files display.  It makes no sense at all that filtering out those tags should block the actual English-language page that I expected to see when doing a specific search.

**Comment by VulcanTourist** [comment]
The FNIS author erroneously tagged the mod as both English and "Other Languages", even though the page is *only* in English and no other (at least no other visible to me).

**Comment by rscottexe** [comment]
Well I just tested those specific search terms, with those blocked tags, using the new site and the old site and they're returning exactly the same results. So, at least in this case, there's absolutely no difference between the old and new site search results.

If you want to provide us with some searches that are actually not working properly, we'll happily look into it and fix it! But right now, it's working how it was before.

**Comment by VulcanTourist** [comment]
Let me pivot and ask a couple questions:

1. What are the "Translation" and "Other Languages" and specific language tags meant to accomplish?  Are they meant to communicate that the *actual page* itself is presented in another or multiple languages, or are they meant to describe the *content* of the mod that the page describes?

2. Assuming that these tags ever accomplished for me what I believed they did - filtering actual pages in other languages from the default listings - do I still need those tags with the new site to prevent display of those irrelevant pages, or does the site now use another method to ensure language-appropriate listings?

**Comment by iamtiz** [comment]
1. Translations refers to the mod themselves, not to their description on the Nexus. Note that mods in English can be translations too, if the original mod was created in a different language.

2. The new site uses the same system as the old one, to apply language filters
