### ISSUE TITLE
Cannot suggest game after searching available game list from the "Add a Mod" page

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#563]
## Bug/error being reported:
From the "add a mod" page, users cannot access the "Add a new game" options after using the search options.

## Steps to reproduce:
1. Go to "add a mod": https://www.nexusmods.com/mods/add
2. Search for a game title under Choose a game, Start typing the game name to get started...

## Expected result:
The "Add a new game" options should available under the search box so that users can suggest new games to add.

## Actual result:
The "Add a new game" options are not available after searching existing games. 

Note: this still occurs even after clearing the search string

Note: if the search box contains a string that can't be found, the "add a new game" options become available

**Comment by iamtiz** [comment]
Assigned #155218009

**Comment by iamtiz** [comment]
fixed
