### ISSUE TITLE
I did not receive an email to confirm my account

### ISSUE THREAD

**Issue by Dektorx** [Nexus-Mods/web-issues#565]
## Bug/error being reported:
the message confirming my e-mail on the "nexusmods" page has not been sent to my inbox, so I can not use the site normally

## Expected result:
receiving a confirmation message

## Actual result:
I did not receive such a message

e-mail to which the message was to arrive is: paradek123@wp.pl

**Comment by SirSalami** [comment]
@Dektorx. Unfortunately there is no record of that email address being used to register any accounts with our site. If you continue to have issues with registration, please contact support@nexusmods.com with the username and email address you are using and we'll try and help if we can. Thank you!
