### ISSUE TITLE
Impossible to add videos to a file owned by another user when no current videos exist

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#567]
## Bug/error being reported:
Impossible to add videos to a file owned by another user when no current videos exist, as there is no corresponding 'video' tab to provide the appropriate option. This is the case even if the file's permissions have been set to allow videos from users. Additionally, there is no way to add videos via the "add media" button found at the top of a mod page.

## Steps to reproduce:
While on another users file page that currently has no videos, try to upload a video.
(Example page with no author submitted videos: https://www.nexusmods.com/skyrim/mods/63874)

## Expected result:
Successfully submit a video link to another user's file page.

## Actual result:
- There is no 'video' tab to provide the option to add a video.
- There is no option to submit a video link via the "add media" button at the top of the file page.

**Comment by iamtiz** [comment]
Mod videos can only be uploaded by the mod authors.
Other users can upload their videos in the video-share area, and then add the mods they are showcasing, however. The permission allowing videos from users refers to these video-share links.

**Comment by iamtiz** [comment]
We could provide a link and/or an explanation of how it works, though

**Comment by iamtiz** [comment]
Assigned #155288973

**Comment by ArtaiosGreybark** [comment]
Is this how this video got added, then?

https://www.nexusmods.com/skyrim/mods/89278?tab=videos&BH=0

**Comment by iamtiz** [comment]
Yes, it's a video from the video-share area

**Comment by iamtiz** [comment]
We added buttons/links to the proper place where video-share videos can be added
