### ISSUE TITLE
bug when update 'Mod details' section 'Classification' not updated

### ISSUE THREAD

**Issue by lubronbrons** [Nexus-Mods/web-issues#568]
URL: https://www.nexusmods.com/oblivion/mods/edit/?step=details&id=46495&game_id=101

Bug/error being reported:
in 'Mod details' section
upon hitting the 'Save' button
all attributes in section 'Classification' is not updated at all

Steps to reproduce:
1. login into Nexus in website mode, I use Chrome Version 64.0.3282.167 (Official Build) (64-bit)
2. click gear icon in top right
3. click tab 'FILES (MINE)'
4. click 'Mod details' (choose one mod)
5. go to bottom see section 'Classification'
6. uncheck option 'is not lore-friendly' and 'contains nudity'
7. click 'Save' (or Next) -- if we come back to this page again 'is not lore-friendly' and 'contains nudity' is NOT changed at all

Expected result:
option 'is not lore-friendly' and 'contains nudity' in 'Classification' section should be changed after user click 'Save' button

Actual result:
option 'is not lore-friendly' and 'contains nudity' in 'Classification' not modified even after 'Save' button clicked and give success notification about update

Username on the Nexus: lubronbrons

Link to the affected mod/image:
https://www.nexusmods.com/oblivion/mods/edit/?step=details&id=46495&game_id=101

**Comment by iamtiz** [comment]
Assigned #155280675

**Comment by iamtiz** [comment]
fixed
