### ISSUE TITLE
Typing & in a comment will truncate the displayed comment

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#57]
The '&' symbol still causes the comment editor not to display the text you typed after the '&' character and the '&' character itself. The full text is still visible in the editor when you open the comment to edit it. Enclosing & between single quotation marks ('&') prevents this glitch from truncating the displayed text.

The issue affects image and mod comments.

**Comment by verenion** [comment]
Assigned PT#151084839

**Comment by verenion** [comment]
Fix has been pushed
