### ISSUE TITLE
Query String in URL can link to mods from different games

### ISSUE THREAD

**Issue by AzureWind13** [Nexus-Mods/web-issues#571]
## Bug/error being reported:
The query string **selected_game** can link to mods from other games which can lead to confusion.

## Steps to reproduce:
1. Google _**skyrim spellbreaker replacer mod**_
2. Open the result that says **Spell Breaker Replacer at Skyrim Nexus - mods and community**

## Expected result:
Page of the Spell Breaker Replacer mod for Skyrim

## Actual result:
Page of the Spell Breaker Replacer mod for Skyrim (GID 110) as stated, but is actually for Oblivion (GID 101)

## Link to the affected mod/image:
Actual URL: https://www.nexusmods.com/skyrim/mods/21847/?tab=3&selected_game=101&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodimages%2F%3Fid%3D21847%26user%3D1%26gid%3D101

Shorter URL: https://www.nexusmods.com/skyrim/mods/21847/?selected_game=101
Screenshot: https://imgur.com/a/AL9R0
Another direct example: https://www.nexusmods.com/fallout4/mods/5296/?selected_game=101

The error might be on Google's side but still the query string produces quite confusing results.

## Username on the Nexus:
[AzureWind13](https://www.nexusmods.com/users/7675799)

**Comment by iamtiz** [comment]
Known issue
