### ISSUE TITLE
Can't block users from mod comments.

### ISSUE THREAD

**Issue by RoyBatty64** [Nexus-Mods/web-issues#572]
When I click on a user from a comment from the mod page (not my mod), I cannot block them. The page gives a popup that says "The user is not a mod author." I don't see what them being a mod author has to do with being able to block them or not? :D

**Comment by iamtiz** [comment]
assigned #155324075

**Comment by iamtiz** [comment]
Are you using the "Block user from this file" / "Block this user from all my files" options in the Manage menu found in comments (mod page, posts tab)? Or are you talking about the "Block" button found in a user's profile?

They are two separate features:
- The first one is used by mod authors (or co-authors) to prevent users from comment on their files.
- The second one allows users to hide specific mod authors from their search results

**Comment by RoyBatty64** [comment]
Odd, I used to be able to block users so I don't have to see their posts or get messages from them.

**Comment by rscottexe** [comment]
Sorry Roy, it's only ever been comments on your own files. You can't ban users unless they've commented on your files.
