### ISSUE TITLE
Untagged MOD Count

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#574]
## Bug/error being reported:
The old Nexus Mods had a count of the Untagged mods for any given game.  It does not seem to have been carried forward to the new product.

## Steps to reproduce:
Open the Mods categories and simply scan the list or read the headings.

## Expected result:
 I expected to find a counted of untagged (not categorized) mods.

## Actual result:
I cannot find a count of untagged (not categorized) mods

**Comment by iamtiz** [comment]
Assigned #155324405

**Comment by iamtiz** [comment]
We added the "mods with no tags" page back (https://www.nexusmods.com/mods/notags/)
