### ISSUE TITLE
Front page and downloads not working with Firefox Quantum browser

### ISSUE THREAD

**Issue by CypharXIII** [Nexus-Mods/web-issues#575]
## Bug/error being reported:
Game 'catalog' not showing up in Firefox Quantum whether you select the see all button or not. Plus cannot download mods from site using NMM link 

Was working before 18-02-18
Possible browser optimisation problem?

Note: Works with Microsoft edge browser

**Comment by ArtaiosGreybark** [comment]
Never had this issue with Firefox Quantum or not. Nor do I have it now. Working fine on the latest version.

**Comment by iamtiz** [comment]
@CypharXIII, we are unable to replicate this problem, is it still happening for you?

**Comment by CypharXIII** [comment]
I found the problem, Something to do with ublock. once deactivating it for the site, it worked.

Strange thing about this is that at my work place I have the same setup (except running on win7) but I don't log into my account and it works regardless.
