### ISSUE TITLE
Click on notification <_username> deleted an image about <_mod title> does nothing

### ISSUE THREAD

**Issue by Zur13** [Nexus-Mods/web-issues#576]
## Bug/error being reported:
Click on notification <_username> deleted an image about <_mod title> does nothing.

![nexuserror17_1](https://user-images.githubusercontent.com/33193255/36420028-57790e26-163c-11e8-8924-0d67fc3362de.png)

## Steps to reproduce:
Click on notification <_username> deleted an image about <_mod title>

## Expected result:
Open the location where the image was posted (mod images or user files etc.).

## Actual result:
Current page reloaded.

**Comment by iamtiz** [comment]
assigned #155359263

**Comment by iamtiz** [comment]
fixed
