### ISSUE TITLE
Unban Request Has No Confirmation

### ISSUE THREAD

**Issue by Haravikk** [Nexus-Mods/web-issues#577]
## Bug/error being reported:
Not sure if this is really a bug as such, but there is no confirmation when submitting an Unban request, meaning it isn't clear whether the request went through at all.

## Steps to reproduce:
Submit an Unban Request with valid user credentials

## Expected result:
Request should be sent with some kind of confirmation that it was received. Preferably both something on the page following submission, and with a confirmation e-mail.

## Actual result:
User is returned to the Unban Request form with nothing filled in, and no indication of whether the request was accepted either on the page itself, or via e-mail notification. This isn't much good as it will just lead to duplicate submissions (probably being held against users as a result), or no submission at all if the lack of confirmation in fact means one wasn't received at all.

**Comment by iamtiz** [comment]
assigned #155359241

**Comment by iamtiz** [comment]
This should now work as intended
