### ISSUE TITLE
Random things

### ISSUE THREAD

**Issue by phillnexus** [Nexus-Mods/web-issues#578]
1. First breadcrumb item is empty. First real breadcrumb has a slash to the left of it. All breadcrumbs use :after to display, yet are floated to the left. Shouldnt need to be floated at all. You can also use :last-of-type on the last list item to hide it if/when it appears on the right side of the link (by removing float)
2. If you set the 'were hiring' to position: absolute, put all the styles on the <a>, give it display:block, and add a style for the site logo (eg: .element + logo {margin-left: 10px}), the image will no longer make the #head element higher than it needs to be. At the moment it's about 10-12px bigger than usual and throws off vertical alignment.
3. 'Add media' hover text is grey, should be white
4. If .sideitems.side-tags gets padding-bottom: 15px (desktop), it won't look uneven
5. Giving nav#mobilenav #mobile-user ul li a width of 33.333333% will result in the columns not looking broken. But these buttons in general look a bit broken now, there are multiple padding values that aren't needed which are pushing things around a bit, and when 'fixed' the icon sizes go out of whack.

**Comment by iamtiz** [comment]
Hi Phill! 
(1) is a known issue we're going to fix soon (the first item being empty, that is). [PT #155360229]
(3) is also something I noticed in a few dropdowns and we're going to fix it as well. 
I'll leave the other points to @aodkitje to check and decide

**Comment by iamtiz** [comment]
1 and 3 are fixed

**Comment by phillnexus** [comment]
Nice

But .sideitems.side-tags should only have 15px when no tags are there, otherwise it doubles up when some are visible. A simpler solution might be to base it around the rule of only-of-type
