### ISSUE TITLE
Image viewer makes images off center, cut in half. Never centered

### ISSUE THREAD

**Issue by silvernirvash** [Nexus-Mods/web-issues#579]
## Actual result:

![nexusimages](https://user-images.githubusercontent.com/9453399/36495232-a11bd8bc-1702-11e8-9a04-00bae9988276.png)

**Comment by iamtiz** [comment]
Hi, could you provide a link to this mod?

**Comment by silvernirvash** [comment]
it's not exclusive to this mod, it's on every page where an image is viewable.

**Comment by iamtiz** [comment]
We cannot replicate this issue. What browser are you using, and at what resolution?

**Comment by iamtiz** [comment]
Do you have any zoom active on your browser?

**Comment by silvernirvash** [comment]
Not on the nexus, like I said my zooms at 100% meaning normal.
