### ISSUE TITLE
Game stopping on Xbox One when using spell

### ISSUE THREAD

**Issue by hjcoder18** [Nexus-Mods/web-issues#582]
## Bug/error being reported:
When using the spell to go to the house, it loads but once you are there the screen goes black and then the game stops. Found on Xbox one.

## Expected result:

I can go about and do whatever

## Actual result:

Screen is going black after using spell and then the game closes.

**Comment by hjcoder18** [comment]
This is happening when you don't even use the spell. It is just after it loads.

**Comment by iamtiz** [comment]
Hi, this is a tracker for bugs happening on the Nexus websites, it's not for any specific game issue
