### ISSUE TITLE
Text search not available any more

### ISSUE THREAD

**Issue by REALfore** [Nexus-Mods/web-issues#585]
## Bug/error being reported:
The text search inside description doesn't exist any more. Was very helpful for me, to find all mods that require FNIS. 

(Dependency isn't sufficient, since many mods don't properly set that correctly. And I don't think there isn't a dependency search anyway)

**Comment by rscottexe** [comment]
Hello Fore,

On this page: https://www.nexusmods.com/mods/ (or any game related similar page) click "Refine results". Description search is in there.

**Comment by REALfore** [comment]
Ooops. But can't that be made a little more obvious. For example somewhere more in the vicinity of the search button? Or a little more colorful. 

I know now, but others... ?

Thank you anyway.
