### ISSUE TITLE
Leaving www.nexusmods.com in tab idle, RAM usage as high as 2GB! memory leak?

### ISSUE THREAD

**Issue by fractalfederation** [Nexus-Mods/web-issues#588]
Windows 10 Pro 64 bit, Version: 1709, OS Build 16299.248
Using Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Go to a mod page, like: https://www.nexusmods.com/kingdomcomedeliverance/mods/325
Wait, time is 11:18PM EST
Memory usage @ 250MB
CPU bouncing between 4-25%, sometimes as high as 35%
Memory increasing by about 100-200KB/sec
Time is now 11:28 EST
Memory usage @ 316MB

It will keep going. I left it up while working on Creation Kit and then it's viewport and my Slack crashed.

**Comment by iamtiz** [comment]
We can't replicate this issue with the same set-up.
Was some ad being displayed at the time? 
Are you using any plugins or extensions?

**Comment by fractalfederation** [comment]
yesterday there was more javascript errors, now only one. I should've copied them. Seems fine now. I guess it was just a fluke.
