### ISSUE TITLE
Make updates list stay open

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#59]
I have a little usability request. While I like that the updates/notifications list automatically goes away when moving the cursor off of it, I feel like there should still be a way to keep it open if you want to.

Just so that you don't always have to be as careful as to what pixel to move your mouse to or not when checking out updates.

Maybe clicking on the "Updates" button can make it so it stays open until you click it (or any other part of the site) again?

**Comment by verenion** [comment]
Assigned PT#151121568

**Comment by verenion** [comment]
Change has been pushed
