### ISSUE TITLE
Not Loading Next Page

### ISSUE THREAD

**Issue by kaninhopp** [Nexus-Mods/web-issues#591]
## Bug/error being reported:
Next page not loading for Kingdom Come Mods

## Steps to reproduce:

go to https://www.nexusmods.com/kingdomcomedeliverance/mods/categories/6/ or any kingdom come mod page, click on the 2 for the next page...

## Example:

https://www.nexusmods.com/kingdomcomedeliverance/mods/categories/6/ > https://www.nexusmods.com/kingdomcomedeliverance/mods/categories/6/

## Expected result:
to open the next page

## Actual result:
nothing

**Comment by iamtiz** [comment]
Which browser are you using? Is the same in other games' pages?

**Comment by KingofDefiance** [comment]
i'm having this issue as well, in Chrome as well as Internet Explorer. I can't move to the next page, It registers my button press but won't load.

**Comment by iamtiz** [comment]
Is this only happening in that page?
