### ISSUE TITLE
Image Uploader Hangs Forever and/or Gives False or No Progress Indication

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#593]
![nexusimageuploadhang](https://user-images.githubusercontent.com/33111596/36935082-41acf4b6-1eb8-11e8-85ed-11dd543ad637.png)
![nexusmodsuploadfailmsg](https://user-images.githubusercontent.com/33111596/36935083-41bb3a4e-1eb8-11e8-8f4f-229c60afb3a5.png)

## Bug/error being reported:
The "User Images" upload process on mod pages does not give any/accurate, feedback on the progress of the upload.

## Steps to reproduce:
1. Select Images Tab on any Nexus mod page
2. Select "User Images" then "Add Images"
3. Drag-n-drop or Browse-n-click a/some local-machine image/s to upload
4. Watch as the progress bars do not move at all, or (sometimes) move 3/4 of the way and then freeze for an infinite amount of time- I have personally waited for 30 minutes for 3 images to upload and none of the 3 progress bars ever reached completion.
5. Give up in frustration and reload the page
6. Be astonished when you see that all your images actually uploaded, presumably 20 or 25 minutes before you finally rage-refreshed the page and despite the fact that NONE of the progress bars ever moved past 3/4.
## Expected result:
I expect the progress bars to show me some reasonable approximation of actual upload progress on each image, up to and including eventual 100% completion. The fact that they do not show any accurate or useful information at any time makes the process of uploading images exceptionally frustrating and infuriating.

## Actual result:
See step-by-step above. Not typing it again. This is a redundant question.

Thanks in advance for fixing this.

**Comment by Vyxenne** [comment]
![nexusimageuploadhang](https://user-images.githubusercontent.com/33111596/36935073-23e55482-1eb8-11e8-9c1d-cb6bf4a2fb6f.png)
![nexusmodsuploadfailmsg](https://user-images.githubusercontent.com/33111596/36935074-23f8affa-1eb8-11e8-971c-de09d3bbfb38.png)

**Comment by iamtiz** [comment]
assigned #157310709

**Comment by iamtiz** [comment]
Is anyone still having problems with the image uploader?
