### ISSUE TITLE
Admin function: Warning form closes without asking for confirmation if you click accidentally outside the form

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#594]
## Bug/error being reported:

As the title says, the form that is used for issuing informal/formal warnings from a comment's admin menu closes without asking for confirmation if you accidentally click outside the form. 

## Steps to reproduce:

1. Open the warning form from any comment's admin menu in any mod comment topic on the Nexus sites
2. Type a wall of text into the input fields.
3. Click outside the borders of the form.
4. Enjoy (when you open the form again, everything you typed is gone).

## Expected result:
- Either the form should not close at all or a warning should be displayed (Do you want to quit this form?).

## Actual result:
Loss of time and elevated blood pressure.

**Comment by iamtiz** [comment]
assigned #155697186

**Comment by iamtiz** [comment]
Fixed.
