### ISSUE TITLE
Possible to break page layout in comments section

### ISSUE THREAD

**Issue by Sathras** [Nexus-Mods/web-issues#595]
## Bug/error being reported:
Its possible to break the page layout with a list inside a spoiler:

## Steps to reproduce / Example:
```
[spoiler]
[*] Item 1
[*] Item 2
[*] Item 3
[/spoiler]
```

## Actual result:
[Example of broken page](https://www.nexusmods.com/skyrim/mods/72921/?tab=posts) as of 03/04/2018

**Comment by iamtiz** [comment]
Assigned #155697096

**Comment by iamtiz** [comment]
fixed
