### ISSUE TITLE
Main featured mods screenshots using inadequately optimized PNG-8, indexed palette causing substantially incorrect colors

### ISSUE THREAD

**Issue by chocmake** [Nexus-Mods/web-issues#596]
## Bug/error being reported:
The main screenshots of the Hot/Featured mods on games' front page have begun using PNG-8 (limited to a 256 color palette, but here far less) at some point for various featured mods, leading for all such affected thumbnails have non-accurate colors, some completely drained of correct colors in the subject due to the palette of the PNG-8 output being so limited it would seem to hit some sub-40KB filesize goal.

![example 1](https://user-images.githubusercontent.com/34178938/36972680-1e695dd8-20c4-11e8-983b-785624205181.png)

The raw PNG-8 version (35.8KB):

![png-8](https://user-images.githubusercontent.com/34178938/36973785-6def765e-20c8-11e8-9d3d-2fa416ba8d61.png)

Only *6* colors used in this PNG-8 version (!).

## Steps to reproduce:
Open game mod home pages such as [MGSV: The Phantom Pain](https://www.nexusmods.com/metalgearsolidvtpp/) and [The Witcher 3](https://www.nexusmods.com/witcher3/) as of 2018-03-05 to observe one of the two featured mods in each game page using PNG-8 and inaccurate colors ([MGR Cyborg Ninja](https://www.nexusmods.com/metalgearsolidvtpp/mods/601) mod and [Live Bestiary](https://www.nexusmods.com/witcher3/mods/2937) mod, respectively), unlike the other thumbnail which uses JPEG for accurate colors. 

## Expected result:
Mods should have thumbnails that accurately represent the colors of their main screenshots. Even PNG-8 can produce acceptable results with a greater number of colors in the palette, however this can increase the filesize over JPEG.

I'm not sure what is determining when the thumbnail generator should use PNG-8 but if it's some 'image sharpness-to-filesize' detection then it appears to be doing so without consideration for the accuracy of the color output.

For comparison here's a JPEG version of the same thumbnail saved using Photoshop's Save For Web:

Custom JPEG optimization (35.2KB):

![custom jpeg optimization](https://user-images.githubusercontent.com/34178938/36974018-40c29c82-20c9-11e8-983e-4c1d67a8d77d.jpg)

So low filesize JPEG is still achievable while retaining acceptable fidelity. Here actually smaller than the original PNG-8 output. 

## Actual result:
PNG-8 is being introduced for certain mod screenshots at the expense of substantially incorrect colors.

**Comment by iamtiz** [comment]
Assigned #155934698

**Comment by Pickysaurus** [comment]
We've changed our images system several times since the original report. Hopefully this is no longer an issue.
