### ISSUE TITLE
Can't stop tracking a hidden mod

### ISSUE THREAD

**Issue by Fixitman333** [Nexus-Mods/web-issues#597]
## Bug/error being reported:
Unable to stop tracking a mod that is hidden by the author, but update notifications continue.

## Steps to reproduce:
1. Track a mod
2. Author hides it
3. Author updates it, but leaves it hidden
3. Update notification received, but can't access it or stop tracking it

## Expected result:
I'd expect to be able to stop tracking a mod regardless of whether it is hidden or not. Getting update notifications for a mod that has been hidden for a very long time is frustrating. The mod that I want to stop receiving update notifications for is at https://www.nexusmods.com/skyrimspecialedition/mods/14493/ . It has been hidden for a about a month, and no longer interests me.

**Comment by iamtiz** [comment]
You should now be able to untrack hidden mods in your tracking centre
