### ISSUE TITLE
Nexus not starting up.

### ISSUE THREAD

**Issue by brhost01** [Nexus-Mods/web-issues#598]
Whenever i try to start up Nexus, it simply loads for 2 seconds and does nothing. This is really annoying as my games are now crashing, and I am unable to go onto Nexus to disable whichever mods are causing this.  Restarting, sleeping, or shutting down my computer doesn't help, and I'm unable to do anything to fix it. (by the way, incredibly frustrating that i have to make an account on some website to be able to report a bug, especially when it is a link on YOUR website) I have tried uninstalling and re-installing, which didnt do anything either. Please get back to me soon.

**Comment by iamtiz** [comment]
Is it Nexus Mod Manager you are having trouble with, or the Nexus websites?
