### ISSUE TITLE
Russian text turns into a bunch of question marks.

### ISSUE THREAD

**Issue by Sm-V-V** [Nexus-Mods/web-issues#599]
1) https://www.nexusmods.com/kingdomcomedeliverance/mods/397?tab=posts
2) I can't write a response to a post in Russian.
3) Steps:
- Press "Reply" button.
- Enter some text that contains Cyrillic characters.
- Press "Submit" button.
4) Correct text.
5) Bunch of question marks.

**Comment by iamtiz** [comment]
assigned #155850856

**Comment by iamtiz** [comment]
This is now fixed (only for new comments. Existing ones, like the example you posted, will have to be re-submitted in order to appear as it should)
