### ISSUE TITLE
Advanced Search, Selection field styling

### ISSUE THREAD

**Issue by soraphis** [Nexus-Mods/web-issues#6]
![image](https://user-images.githubusercontent.com/3066582/29889551-d4b3b432-8dc4-11e7-8911-cf2916364588.png)

changing this css rule, by adding the last two lines:

```diff
#right-col .sort-box .sort-options select {
    border: 1px solid black;
    background-color: #7C7C7C;
    font-size: 12px;
    padding: 5px;
    color: #E6E6E6;
+    width: 200px;
+    box-sizing: content-box;
}
```

results in this

![image](https://user-images.githubusercontent.com/3066582/29889663-4a37a2ae-8dc5-11e7-9110-136729e33c26.png)

**Comment by iamtiz** [comment]
Fixed
