### ISSUE TITLE
Nexus does not upload new file when version matches old file

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#601]
## Bug/error being reported:

When you try to upload a new file but enter an old version, Nexus will reupload the old file with that version and ignore the new file that you saved.

## Steps to reproduce:
1. Add a new file with a version number and set that file as an old version.
2. Add a new file with the same version number but a totally different file. Do not check "this is a new version of an existing file."
3. Click Save File.
4. Go to the Files page and download the new file.

## Expected result:

You receive an error that the file cannot be added with an existing version number and the file is not uploaded.

## Actual result:

Nexus reuploads an existing file associated with the matching version number, ignoring the new file you saved.

**Comment by fireundubh** [comment]
I tried uploading a new version of a file with the same version number. This time I checked "this is a new version of an existing file. Instead of uploading the new file, the old version was reuploaded.

**Comment by fireundubh** [comment]
I uploaded the same new file with a new version number. None of the above issues were reproduced. You seem to have an issue in your versioning system, where one of the above steps to reproduce gets the file into a bad state that seemingly forever corrupts that version number.

**Comment by iamtiz** [comment]
Assigned #155899996

**Comment by Digital-Sauce** [comment]
I just posted a mod and am having the same issues that fireundubh has described.

https://www.nexusmods.com/skyrimspecialedition/mods/15862/

Also, under "preview file contents" on the mod page, all of the right stuff is shown. Downloading the file gives a broken earlier version that was deleted. Uploading my updated mod to the server works fine.

Maybe the mod's .rar file is passing some sort of condition to skip overwrite when it shouldn't, either that or maybe it's been mistakenly left out of the use case.

**Comment by fireundubh** [comment]
This is still an issue 6 months later.

**Comment by iamtiz** [comment]
This should now be fixed
