### ISSUE TITLE
Need tag (in Morrowind section) for TamrielData

### ISSUE THREAD

**Issue by Darklocq** [Nexus-Mods/web-issues#604]
There's no tag authors or other users have for indicating either compatibility with or a dependency on TamrielData (the shared resource BSA of all the Tamriel Rebuilt and Project: Tamriel mods, including Skyrim: Home of the Nords and Province: Cyrodiil).

Ideally there would be both tags, the dependency one in the Requirements tags.

**Comment by SirSalami** [comment]
We've added a "Requires > Tamriel_Data" tag for Morrowind. Your help with tagging the appropriate files is appreciated. Thanks!
