### ISSUE TITLE
When you insert text while editing mod details, the page automatically scrolls down.

### ISSUE THREAD

**Issue by Sm-V-V** [Nexus-Mods/web-issues#605]
1) I edited the details of my mod and found that when I pasted the text to the top of the edit box, the page automatically scrolls down. I use Chrome for browsing.
2) Steps:
- Open mod for manage on "Mod details" tab.
- Add many lines in "Detailed description" text field.
- Ctrl-c some text and ctrl-v it somewhere in top of the field.
3) Page remains in place.
4) Page automatically scrolls to the bottom of the field.

**Comment by iamtiz** [comment]
assigned #155903188

**Comment by iamtiz** [comment]
Hi, unfortunately it looks like the issue is with the WYSIWYG editor we're using (http://wysibb.com/) and the latest versions of Chrome. We'll keep an eye for patches though

**Comment by Sm-V-V** [comment]
Ok, thanks!
