### ISSUE TITLE
Not necessarily NEW, I guess. Nothing Downloads.

### ISSUE THREAD

**Issue by iArgenti** [Nexus-Mods/web-issues#606]
## Bug/error being reported:
Nothing downloads, from the NMM, to manual selections. The pop up appears, and nothing happens. If I wait long enough I get an error alert stating the site is unresponsive.

## Expected result:
Mod downloads obscenely slowly due to MB cap, but I eventually get the mod, or the sites own downloader to install, then I go play my game.

## Actual result:
Nothing downloads ever, never even begins, and I get irritated.

**Comment by wills661** [comment]
This issue has been happening for a few months and no-one seems to want to Fix it

**Comment by iamtiz** [comment]
Hi, when did it start? Is is affecting all the games?

**Comment by blix** [comment]
I am having a similar issue. Clicking on the "NMM" or "Mod Manager Download" buttons used to cause Mod Organizer to download the mod, but this never works anymore and I can no-longer download mods through MO. I seem to remember there was a button to trigger the download before the modal was changed in the most recent re-skin of the site. Typically any download that is not triggered by a click is accompanied by a link/button that triggers the download manually to prevent compatibility problems.

**Comment by iamtiz** [comment]
We added an "emergency button" that can be used in case a download is not starting automatically
