### ISSUE TITLE
Mod Authors can't change active tags without "rejecting" them

### ISSUE THREAD

**Issue by giftfish** [Nexus-Mods/web-issues#607]
## Bug/error being reported:
Active tags cannot be disabled after enabling. They can only be "rejected".

## Steps to reproduce:
1. Click "Add this tag to your mod" (tag turns green)
2. Now, try to remove the same tag without it resulting in the tag turning red ("Reject this Tag"). You can't.

## Expected result:
Mod authors should be able to remove an active tag without explicitly rejecting it. Why? What if they mis-click, or the mod contents change, and that tag no longer applies?

In short, there needs to be 3 settings for a tag (and there indeed already is): active, inactive, and not available. By default, all tags are "inactive" (white). When they are activated they turn green. When not available, they are red. Yet, there is apparently no way to go from green > white, and not force green > red. I want to say this _used_to be possible, but it's not currently.

## Actual result:
Any active tag (green) an author wants to remove by default becomes "rejected" (red), rather than simply made "inactive" (white).

**Comment by iamtiz** [comment]
This is the intended behaviour

**Comment by giftfish** [comment]
Then, perhaps in the future there can be a discussion about changing this behavior. The restriction is unintuitive, for the exact reasons I stated above. This gives the user the impression that it's a bug and not by design.
