### ISSUE TITLE
Notifications - a request

### ISSUE THREAD

**Issue by Norstaera** [Nexus-Mods/web-issues#608]
I would like to be able to view all my updates in a page rather than always having to click 'Load more' to expand the dialog box when I have more than 5 notices. 

I am now tracking a number of mods, both for file updates and comments. What used to be an occasional inconvenience is now a constant irritation, especially if I jog my cursor and have to start scrolling all over again. I like the convenience of seeing how many updates I have on the tab itself. I would like the option of opening the dialog as I do currently or opening up an 'all notifications' page. A link in the dialog box, 'View all updates' next to 'Load more' would also be appreciated. 

Thank you.

**Comment by Eolhin** [comment]
I have to agree, that would be really handy.  I have a huge number of notifications.

**Comment by iamtiz** [comment]
We added a new "updates" page for notifications, reachable using the "See all" link at the bottom of the dropdown list
