### ISSUE TITLE
HTML-like tags aren't escaped; leak out of the description

### ISSUE THREAD

**Issue by 90Sigma** [Nexus-Mods/web-issues#609]
See: https://www.nexusmods.com/oblivion/mods/13879 for an example.

The user-created description for the mod includes the following text:
> Fixing these used to be hard, but with OBSE v0016 it can now be done easily at the console after deactivating the leveling mod by doing;
> setPCMajorSkillUps \<NN\>
> setPCTrainingSessionsUsed \<TT\>
> Where \<NN\> is the major skill advance count you want, and \<LL\> is the number of training sessions used you want. At this point you can save your game and continue using vanilla leveling.

[Note: Possible typo on LL - meant to be TT? Also escaping added for the purpose of this bug report.]

The problem is that \<NN\> and \<TT\> are not escaped, and so the browser is rendering these as HTML tags. I have not tried it, but it may be possible to include any HTML or script in a description and the browser will parse it accordingly.

As a minor secondary issue, the \<TT\> is 'leaking' out of the description into the HTML beyond, so the "Follow us", site links and network stats are also rendering in the same format as the description.

**Comment by iamtiz** [comment]
Fixed
