### ISSUE TITLE
The hidden mod message grows an extra tag each save

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#61]
This issue was present in the old site too. If you have your mod hidden from the public, the message you leave in place gains an extra </br> tag each time you edit the description

**Comment by mrmason** [comment]
Assigned `#151116181`

**Comment by Pickysaurus** [comment]
`</br>` was the tag. Didn't realise HTML formats in these comments xD

**Comment by Rrrafau** [comment]
Can you provide more details / steps to reproduce this issue? By "description" are you referring to mod description?

**Comment by Pickysaurus** [comment]
Sorry, looks like this is fixed in RD. It handles hidden files differently. I'll close this
