### ISSUE TITLE
[Feature Request] More Accessible Advanced Search

### ISSUE THREAD

**Issue by twizz0r** [Nexus-Mods/web-issues#610]
## Bug/error being reported:
Feature Request: More Accessible Advanced Search

The Mods search only returns result for mods titles, meaning you have to take extra steps if you want to search inside mod descriptions. 

Currently, the quickest way to get to the advanced search is to search for nothing and then refine results.

Better would be to list the advanced search in the search drop down (Mods, Images, Supporter Images...)

**Comment by Pickysaurus** [comment]
The current iteration of the search will be replaced at some point in the future with a new version where UX improvements like this will be considered.
