### ISSUE TITLE
Enhancement: Addition to the text on the Report form 

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#611]
The following text should be added below the current text on the 'Report' form accessible from the 'Description' tab of mods:

"**Warning! Do NOT use this tool to report bugs in mods or installation problems!** This function should only be used to report violations of our terms and policies. Bugs should be posted in the comment topic of the mod you have problems with. Mod authors do not see these reports and we do not forward bug reports to mod authors."

**Comment by iamtiz** [comment]
Assigned #156123105

**Comment by iamtiz** [comment]
Done.
