### ISSUE TITLE
Search function not returning some results in Fallout 4 view

### ISSUE THREAD

**Issue by Ethameshep** [Nexus-Mods/web-issues#612]
##Bug/error being reported:
      Searching does not display all results.

##Steps to reproduce:
      1. Go to https://www.nexusmods.com/fallout4
      2. Search for "Unofficial Fallout 4 Patch" in search bar

##Expected result:
      Top results should be https://www.nexusmods.com/fallout4/mods/4598/

##Actual result:
      Only four results are returned, none of which are the correct one.  This occurs only with Fallout 4 views AFAIK and with most searches I submit.

**Comment by LadyMilla** [comment]
Myself, I cannot replicate the issue. See:

<img width="963" alt="fallout4search" src="https://user-images.githubusercontent.com/31491675/37597906-071607fe-2b81-11e8-8669-f74eed46d830.PNG">

While it is true that the search returns only 4 results, the first one is the Unofficial Fallout 4 Patch (mod/4598/).

**Comment by Ethameshep** [comment]
This is the result I get regardless of browser:
![capture](https://user-images.githubusercontent.com/32421150/37626861-b83879fe-2b9f-11e8-8dbc-1093dc4e0f79.PNG)

However, when not logged in I get this result:
![screenshot-2018-3-19 fallout 4 nexus - mods and community](https://user-images.githubusercontent.com/32421150/37626999-68451f82-2ba0-11e8-937d-ba311a46b326.jpg)

I don't have any custom filters set.  This happens quite regularly for me.

**Comment by LadyMilla** [comment]
Apparently you do have some active filters, hence the '22937 have been filtered out' message. It seems one of the filtered categories is translations. Content blocking/filtering is configured at two places: 

- if you click on the gear icon next to your avatar, you'll get to the 'My Nexus account' page. The second tab is 'Content Blocking'. Make sure that no tag is selected. 
- on Fallout 4 Nexus, use Mods -> Browse all mods -> Refine results -> Clear Filters.

If the unofficial FO4 patch still fails to appear, you can also try to search for 'Arthmoor' in the Search field (select Authors from the small drop-down menu next to the Search button) to see if you are not blocking Arthmoor for some reason (accidentally). If you have already tried these options, then it's up to the devs to check if there is a stuck filter setting or some other glitch in the database.

**Comment by Ethameshep** [comment]
Thanks for the help.  Unfortunately, none of these methods worked.

**Comment by iamtiz** [comment]
@Ethameshep, looks like you're blocking the `XBone version available` tag, which is one of the tags associated with `Unofficial Fallout 4 Patch`, assuming this is your profile: https://www.nexusmods.com/users/10668242.

You should be able to unblock that tag by going to https://www.nexusmods.com/users/myaccount?tab=content+blocking and selecting "Fallout 4 tags" from the dropdown. 

Let us know if the issue is still there

![screenshot-2018-3-20 my nexus account at nexus mods and community](https://user-images.githubusercontent.com/3407947/37652633-08e52516-2c34-11e8-9636-8adc4ce62624.png)

**Comment by Ethameshep** [comment]
That fixed the issue.  I don't recall ever changing those settings so I thought they were default.  Thanks for the help.
