### ISSUE TITLE
Deleting Last "Update" Closes List Even With Unread "Updates" Remaining

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#614]
## Bug/error being reported:
With the "Updates" dropdown open and several unread "Updates" visible (they are not actually "Updates" but are instead Notifications that have been erroneously renamed "Updates" in the new system) deleting the last "Update" closes the "Updates" dropdown even though there are read and/or unread "Updates" remaining in the window.

## Steps to reproduce:
1. Click the "Updates" link to expose Read and Unread notifications (erroneously labeled "Updates")
2. Delete the last notification, whether it has been read or not, leaving other notifications untouched
3. The "Updates" dropdown inappropriately closes, forcing users to re-open it to deal with the remaining notifications- this happens whether the last notification, or any of the remaining notifications, is Read or Unread.

**Comment by iamtiz** [comment]
That's a known issue, we'll have a separate area for notifications in the future
