### ISSUE TITLE
File history milestone information often obscured by date in file statistics.

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#616]
## Bug/error being reported:
If file milestones such as new uploads correlate with high download counts, the detail that is shown when hovering over the graph may become obscured.

As reported by quicksilver Quicksilver500 on Discord.

## Steps to reproduce:
Visit any file stats page where a high download count is associated with a milestone that's noted in the stats graph. Hover mouse over the milestone and it may be obscured.

## Expected result:
Detail windows that pop up when hovering near the top of the stats graph should be organized in such a way that the text is not obscured.

## Actual result:
Details are obscured when hovering on files.
Example stats page (hover over the red milestones on the left of the graph): https://www.nexusmods.com/skyrim/mods/63874?tab=stats
Screenshot: https://i.imgur.com/msmosfY.png

**Comment by SirSalami** [comment]
Not a critical issue. If one "zooms in" or limits the scope of the graph tool, this is often resolved.

**Comment by iamtiz** [comment]
Assigned #156123448

**Comment by iamtiz** [comment]
fixed
