### ISSUE TITLE
Report A Bug feature auto-refers to wrong version.

### ISSUE THREAD

**Issue by glecas** [Nexus-Mods/web-issues#617]
## Bug/error being reported:
When issuing a but report, the website automatically assigns a version. And that version isn't correct, and cannot be changed either.

## Steps to reproduce:
Press the "Report a bug" button and complete the form.

### Example:
None of the versions are true:
https://i.imgur.com/ZhFMc9O.jpg

## Expected result:
I expected the version to be latest one according to the main modpage.

## Actual result:
The website auto assigns a version, and I (the mod creator) cannot change it.

**Comment by iamtiz** [comment]
Hi, which is the mod you are referring to?
The version displayed in the bug list indicates which is the last version the user has downloaded before reporting the issue
