### ISSUE TITLE
Link to "nicely formatted changelog" does not link to correct page

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#619]
On the changelog editing page, you can select the "large text box" method. When you select that method, a label appears above the text box. That label reads:

> Each update of your mod should include the version number, the things that were changed, and the date on which these occured. This will allow your users to track milestones and view what changes were made with each revision. Here's a good example of a [nicely formatted Changelog](https://www.nexusmods.com/kingdomcomedeliverance/mods/edit/?step=docs&id=3#) if you need a template to start from.

The "nicely formatted Changelog" link does not point to the right URL.

Separate but related text issues:

* The `c` in changelog should not be capitalized here.
* The text looks like old text from the old site. There is no date field, and the version number is required, or should be.

**Comment by iamtiz** [comment]
assigned #147854533

**Comment by iamtiz** [comment]
Removed link and obsolete text
