### ISSUE TITLE
Posting comments in the bug section doesn't do anything.

### ISSUE THREAD

**Issue by Reaperrz** [Nexus-Mods/web-issues#62]
URL: https://rd.nexusmods.com/witcher3/
(In case it could be specific, though I doubt it.)

Bug/error being reported:
Commenting in the bug reports sometimes yields an empty message which is not sent, [like this.](https://i.imgur.com/SfmDw8I.jpg)

Steps to reproduce:
Click reply on a bug report and simply type and send a comment. Sometimes it doesn't work.

Expected result:
To actually send the comment.

Actual result:
Fuck-all again. :)

**Comment by verenion** [comment]
Assigned PT#151119163

**Comment by verenion** [comment]
Fix has been pushed.
