### ISSUE TITLE
Changing file details clears add new file form

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#620]
## Summary
When you change the details of an existing file while already having populated the Add a New File form, the form is cleared when the existing file's details are saved.

## Steps to reproduce

1. Populate the Add a New File form.
2. Change a detail of an existing file and Save.

## Result

The form is cleared.

## Expected result

The form is not cleared.

**Comment by iamtiz** [comment]
Assigned #156125242

**Comment by iamtiz** [comment]
Done.
