### ISSUE TITLE
"Set as default" option for Add a New File form fields

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#621]
There should be a "set as default" button for each field in the Add a New File form, so that you don't have to repeatedly write the same text for every new file. When clicked, the current value of that field would be set as the default text until a new default is set. To clear the default, you'd set empty text as the default.

**Comment by Pickysaurus** [comment]
When you pick "Upload new version" from the file selector it pre-populates some of this data.
