### ISSUE TITLE
File type limiter allows restricted file types to be uploaded

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#622]
When you attempt to upload a ZIP file with a different extension, such as `.pak`, the current implementation of file type limits prevents the file from being uploaded.

When you attempt to upload a plain text file with the `.zip` extension, the current implementation of file type limits allows the file to be uploaded.

For games like _Kingdom Come: Deliverance_ where PAK files are just ZIP files with a different extension, limiting files by extension makes the system inflexible, and in terms of security risks, allowing any type of file to be uploaded as long as the extension matches in a list leaves room for improvement.

The system should check the signature of the binary to verify whether the file is an acceptable file type.

File extensions &ne; file types.

**Comment by mrmason** [comment]
This is on our roadmap but it's a long way away at the moment.

**Comment by Pickysaurus** [comment]
Due to the way mod managers currently work it is unlikely we'll be allowing anything other than ZIP/RAR/7z archives for the foreseeable future.
