### ISSUE TITLE
[code] tag does not preserve whitespace in comments

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#623]
When the `[code]` tag is used in comments, whitespace/indentation is not preserved.

Whitespace in editor:

![2018-03-20 05_10_53](https://user-images.githubusercontent.com/1261664/37653827-6eb8fa48-2bfd-11e8-8b3a-26d532cf3938.png)
No whitespace when rendered:

![2018-03-20 05_11_27](https://user-images.githubusercontent.com/1261664/37653833-736d6ba0-2bfd-11e8-87ec-fed82701a155.png)

Multiple spaces condensed to single spaces in source:

![2018-03-20 05_12_21](https://user-images.githubusercontent.com/1261664/37653838-7709777c-2bfd-11e8-9b03-176b9bd9ac2e.png)

I checked out the WysiBB source, but I didn't see anything that would be doing this. Dark0ne said he tested this issue in a mod page description and there was no issue. So, that narrows down the culprit a bit.

**Comment by iamtiz** [comment]
Hi, the WYSIWYG editor should now display [code] correctly. What mod is your example from?

**Comment by fireundubh** [comment]
My non-sticky post in the comments [here](https://www.nexusmods.com/kingdomcomedeliverance/mods/431?tab=posts).

Thanks. Looks fixed to me.

**Comment by fireundubh** [comment]
@iamtiz This is still an issue with tabs.

**Comment by fireundubh** [comment]
@iamtiz The `.wbbtag` class approach doesn't really get monospace right.

For example:
```
Lock Difficulty    Lockpicking Level    Internal Difficulty Range
---------------    -----------------    -------------------------
Very Hard          15 - 20              0.75 - 1.00
Hard               10 - 14              0.50 - 0.70
Easy               7 -  9               0.35 - 0.45
Very Easy          0 -  6               0.00 - 0.30
```

Renders as:

![2018-03-25 23_20_12](https://user-images.githubusercontent.com/1261664/37889833-1acdd22a-3083-11e8-9e0e-c8a30990bc06.png)
