### ISSUE TITLE
Newline added at wrong position in BBCode

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#625]
When you add a newline in a list item (with `Shift+Enter`) using the rich BBCode editor, the newline is added at the wrong position in BBCode.

```
[list]
[*] [size=3][b]Clinch Master I[/b]: The description states the perk increases the overpower chance by 1/3 (33.333%), but the perk actually increases the overpower chance by 40%. The description was changed to reflect the actual effect.

[/size]
[*] [size=3][b]Heavy Swing I:[/b] In game version 1.3, the damage increase was reduced from 20% (1.2) to 3% (1.03). The intended change was likely to increase damage to 30%. More Perks v1.4.1 changes the damage increase back to 20%.[/size]
[/list]
```

A newline should be added after the `[/size]` tag, not before.

I don't think this issue is limited to `[list]` items, but this is where I see the issue more often.

**Comment by iamtiz** [comment]
Looks like it's an issue with the BBCode editor we are using (http://wysibb.com/demo/). We'll see if we can find a workaround
