### ISSUE TITLE
Newlines removed by BBCode editor when switching rich/raw contexts

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#626]
When a newline is added with `Enter` or `Shift+Enter` in the raw BBCode editor, switching to the rich BBCode editor and back again removes the newline that was added.

**Comment by iamtiz** [comment]
Do you mean at the end of the text, or anywhere?

**Comment by fireundubh** [comment]
Looks like the issue just affects list items, but I'm not 100% on that.

Newlines after newlines outside of lists works. Newlines after non-list strings works.

**Comment by iamtiz** [comment]
Looks like this is also an issue with the BBCode editor itself
