### ISSUE TITLE
Nudity getting through the filter

### ISSUE THREAD

**Issue by opusGlass** [Nexus-Mods/web-issues#627]
## Bug/error being reported:
Nudity is appearing on the front page of Skyrim despite me having it filtered and the content being appropriately flagged.

Includes multiple files and images by multiple authors. I've never noticed this occurring before today. All files have the Nudity tag as well as the Sexy/Skimpy tag which are both filtered in my preferences. My nexus username is opusGlass.

**Comment by iamtiz** [comment]
Hi, could you give us a couple of examples of such mods appearing in the Skyrim front page?

**Comment by opusGlass** [comment]
Currently it's only this mod: https://www.nexusmods.com/skyrim/mods/90283
Last night it was also two other mods that are no longer visible for me under New Files, one by the same author: https://www.nexusmods.com/skyrim/mods/90284
And another by a different author that I can't find anymore because I don't know the name / author name. It showed a dark-skinned woman laying prone.
There was also a nude image under New Images from the same author as the two I linked above.

**Comment by Sakr3d** [comment]
This is also happening for me as well.

![blockedtags](https://user-images.githubusercontent.com/37714077/37850901-e378ae46-2eaa-11e8-921e-f0a4746452c6.PNG)

But this occurs on the Mod of the month page.
https://www.nexusmods.com/skyrim/mods/motm/

**Comment by sonic65101** [comment]
I am noticing the same bug as opusGlass, with the mod being (https://www.nexusmods.com/skyrim/mods/90387) appearing on the front page despite the "Nudity" and "Bodyslide Preset" tags being blocked.

**Comment by opusGlass** [comment]
Can confirm that the same mod mentioned by sonic65101 is appearing on my front page.

**Comment by Pickysaurus** [comment]
This should be resolved.
