### ISSUE TITLE
"Move to bugs" unsorted result + keeps original

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#628]
## Bug/error being reported:

"Move to bugs" option doesn't copy dates of the replies thus the resulting replies list is sorted randomly (they are all of the same date aka original post's date)

## Steps to reproduce:

Manage ->Move to bugs
1. [x] Include replies

## Expected result:

Original post with all its replies gets MOVED to bugs section (replies order: same as original)

## Actual result:

Original post with all its replies gets COPIED to bugs section (replies order: unsorted/random)

**Comment by iamtiz** [comment]
To remove the comment and its replies, you have to check the "Set this comment as hidden" box.

**Comment by iamtiz** [comment]
assigned #156226006

**Comment by iamtiz** [comment]
New reports copied from comments should be sorted now
