### ISSUE TITLE
Download to Vortex instead of NMM for NMM game

### ISSUE THREAD

**Issue by Cryzeteur** [Nexus-Mods/web-issues#630]
## Bug/error being reported:
Downloaded https://www.nexusmods.com/fallout4/mods/20137
by clicking on NMM download. Mod downloaded to Vortex.
FO4 was managed by NMM not Vortex.

## Expected result:
 Since FO4 was not being managed by Vortex, I expected NMM to manage it. 

## Actual result:
 Vortex manages all your games once you set it up.

**Comment by iamtiz** [comment]
That's the expected behaviour: all "manager" links are using the same `nxm://` protocol. You can change the default program to be used for them in your browser setting.
