### ISSUE TITLE
Display more information about files to be replaced

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#632]
In the dropdown menu for selecting a file to be replaced, there isn't enough information to distinguish between files that have the same name. The dropdown menu should show version numbers and file names.

![2018-03-25 10_29_21](https://user-images.githubusercontent.com/1261664/37878018-97d4aab2-3017-11e8-8439-28b154060517.png)

**Comment by iamtiz** [comment]
assigned #156266044

**Comment by iamtiz** [comment]
done
