### ISSUE TITLE
Not receiving notifications of tracked authors/images.

### ISSUE THREAD

**Issue by kestrelhawk55** [Nexus-Mods/web-issues#634]
I, and others, are _not_ receiving notifications for tracked authors of images. We _are_ receiving notifications of mods followed. Please see post on Nexus: https://forums.nexusmods.com/index.php?/tracker/issue-69866-not-getting-tracked-notificatio

I also saw a post that someone else started, that questions the same thing. This has been going on for a few days now.

Could someone please address asap?

**Comment by iamtiz** [comment]
This should be fixed

**Comment by kestrelhawk55** [comment]
Thank You!! :D
