### ISSUE TITLE
Download broken for Nerida follower mod - skyrim/mods/75799

### ISSUE THREAD

**Issue by RobAnybody89** [Nexus-Mods/web-issues#635]
## Bug/error being reported:
Download fails for both mod manager download and manual download. However, files can be seen in the preview files content window.

## Steps to reproduce:
Select either download through mod manager (I am using mod organiser) or the manual download option as both fail.

## Expected result:
Either download direct through mod organiser or to be able to manually download the file.

## Actual result:
Mod Organizer shows the file as being 0KB in size and fails, while manual download shows:
ERRONEOUS ERROR!
This error is so weird we don't have an explanation for it...
Yup.
URL: (http://www.nexusmods.com/Static/CDN-404?s=http%3A%2F%2Ffiledelivery.nexusmods.com%2F110%2FNerida%20-%20Custom%20Voice%20Rogue%20Follower-75799-1-20.zip%3Ffid%3D1000248754%26ttl%3D1522058160%26ri%3D8192%26rs%3D8192%26setec%3D2de9054c98c16a596d20a3ce8022173c)

**Comment by SirSalami** [comment]
This issue should now be resolved for this file. If it does continue, please again provide us the error that you may be receiving so that we can look into it further. Thanks!
