### ISSUE TITLE
Not getting notifications for tracked content

### ISSUE THREAD

**Issue by conspiracydawg** [Nexus-Mods/web-issues#636]
Bug/error being reported:
For the past few days, I haven't been getting notifications for mods and images uploaded by the authors I'm tracking. I still get notifications for comments and replies, but not for content uploaded. I've checked my settings and made sure they're set appropriately, but no dice.

**Comment by iamtiz** [comment]
Hi, this issue should have been fixed a few hours ago. Do you have any examples at hand of images you were not being notified about?
