### ISSUE TITLE
The whole posts section of a mod corrupted by one comment that doesn't load

### ISSUE THREAD

**Issue by GePalladium** [Nexus-Mods/web-issues#637]
## Bug/error being reported:
There is a problem on a mod page, in posts section: 
One user comment doesn't load correctly and as result there is no styles, the whole comment section is now concerned.

## Steps to reproduce:
Please, Just see by yourself:
https://www.nexusmods.com/newvegas/mods/56270/?tab=posts&jump_to_comment=58706971
Look at the bottom of all the pages. This same message over and over.

Thank you in advance.

**Comment by iamtiz** [comment]
fixed

**Comment by GePalladium** [comment]
Thank you
