### ISSUE TITLE
Download broken on Nerida - Custom Voice Rogue Follower skyrim/mods/75799

### ISSUE THREAD

**Issue by RobAnybody89** [Nexus-Mods/web-issues#638]
## Bug/error being reported:
Unable to download latest file through either a mod manager or manually. 

Also, looking at the posts tab shows this issue has been present since at least the 4th of October 2017, with the mod author commenting on the 29th of October "Sorry about that, but there's nothing I can do. Downloads are handled by the Nexus, I just upload the files. Only thing you can try is to manually download the mod or try a different browser or something "

## Steps to reproduce:
Select either download through Mod Manager or Manual Download as both fail. Note: files can be seen in the preview files option.

## Expected result:
To be able to download the file.

## Actual result:
Attempting to download through Mod Organizer: Shows the file to be 0KB in size and then fails pausing the download.

Attempting to download manually: 
ERRONEOUS ERROR!
This error is so weird we don't have an explanation for it...
Yup.
http://www.nexusmods.com/Static/CDN-404?s=http%3A%2F%2Ffiledelivery.nexusmods.com%2F110%2FNerida%20-%20Custom%20Voice%20Rogue%20Follower-75799-1-20.zip%3Ffid%3D1000248754%26ttl%3D1522145036%26ri%3D8192%26rs%3D8192%26setec%3D0bab36d0c6681c962472cca2b7eb73e2

**Comment by mrmason** [comment]
Hello,

I have purged the CDN for this file to see if that helps. We have downloaded it correctly internally from all locations and it seems to be working as expected:

```
				$ ls -lahS | grep 'Nerida'
				Nerida - Custom Voice Rogue Follower-75799-1-20 (1).zip
				Nerida - Custom Voice Rogue Follower-75799-1-20 (2).zip
				Nerida - Custom Voice Rogue Follower-75799-1-20 (3).zip
				Nerida - Custom Voice Rogue Follower-75799-1-20.zip

$ md5 Nerida*
MD5 (Nerida - Custom Voice Rogue Follower-75799-1-20 (1).zip) = 6724086507868b971ff480352e44fb94
MD5 (Nerida - Custom Voice Rogue Follower-75799-1-20 (2).zip) = 6724086507868b971ff480352e44fb94
MD5 (Nerida - Custom Voice Rogue Follower-75799-1-20 (3).zip) = 6724086507868b971ff480352e44fb94
MD5 (Nerida - Custom Voice Rogue Follower-75799-1-20.zip) = 6724086507868b971ff480352e44fb94
```

If you're still having problems please can you provide the IP you get when you type `ping filedelivery.nexusmods.com` in your console/cmd ?

**Comment by RobAnybody89** [comment]
Hello Tom,

I've just retried downloading the file and can confirm both the mod manager
and manual downloads are working so you can go ahead and close the ticket.

Thank you very much for your work.

Regards, Robert

**Comment by mrmason** [comment]
Great - thanks!
