### ISSUE TITLE
Passwords with high ANSI characters

### ISSUE THREAD

**Issue by nalyDylan** [Nexus-Mods/web-issues#639]
## Bug/error being reported:
Using passwords with high ANSI characters work when logging in at the forums, but you cannot login through NMM or into nexusmods.com

the exact password I tried (auto-generated by my password manager) was: ãësÉíîÄwØÒèÝX¶þÝþ
I've since changed the password. it's probably that paragraph character, but it should all be ANSI so no multi-byte characters or other weirdness

## Expected result:
logging in

## Actual result:
not logging in

**Comment by nalyDylan** [comment]
oh whoops, ASCII should be ANSI, wrong acronym.

can't edit the OP though

**Comment by iamtiz** [comment]
We changed the way we deal with passwords on the site a couple of months ago. The issue should be fixed
