### ISSUE TITLE
Uploading Large Files Lockup

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#64]
Hi,
On the RD site if I upload my full mod file (2.1GB) it will complete but on clicking save I get the spinning cog of doom forever. In some cases the file has properly uploaded and will appear on the main page, in others it'll lose everything to leave the page.
I've rolled back the classic site for upload (although this has some annoying quirks of it's own). ]

This issue does not occur when uploading smaller mod files.

**Comment by mrmason** [comment]
I know this might be a bit time consuming - but please can you give this a try again with your console open in chrome/firefox and see what messages / requests you're seeing when it breaks ?

**Comment by mrmason** [comment]
Closing for now - please let us know what's going on in the console/network tab if you have the chance.
