### ISSUE TITLE
"Move to forum" option suggestion

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#640]
There could be "Move to forum" option similar to current "Move to bugs", that would move single comment with all it's replies to FORUM tab (assuming that you have it enabled). 

It would be very useful for me because I like sorting features requests in separate topics.

**Comment by Pickysaurus** [comment]
This issue has been closed due to inactivity. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
