### ISSUE TITLE
Recognized Mod Author notification won't let me check box

### ISSUE THREAD

**Issue by RSK-Apocalypto** [Nexus-Mods/web-issues#641]
Bug/error being reported:
So I logged onto the Nexus today and got a notification saying I am now a recognized mod author with over 1,000 downloads across my uploaded mods.  This notification was issued March 29, 2018 by Site Bot.  Below the message it says to check the box to confirm I have read the message, but no matter what I do I cannot check it.  I have tried on Google Chrome, Safari, FireFox, Microsoft Edge, and Internet Explorer and none of them work.  I cannot access anything on the Nexus without the notification reappearing.  

Steps to reproduce:
1. Attain 1000 downloads across mods.
2. Log in to account.

Expected result:
Checking the box and continuing on to the site.

Actual result:
Box is uncheckable.

Username: TheStonedDerp
Premium member

**Comment by iamtiz** [comment]
It should be fixed now

**Comment by RSK-Apocalypto** [comment]
Thank you!!!
