### ISSUE TITLE
Cant Endorse Files

### ISSUE THREAD

**Issue by einResu** [Nexus-Mods/web-issues#642]
It says I have to download the file, but I DID. how can i endorse the mod now??

https://www.nexusmods.com/legendofgrimrock2/mods/90?tab=description

**Comment by iamtiz** [comment]
Is the mod listed in your download history here https://www.nexusmods.com/legendofgrimrock2/users/myaccount?tab=download+history ?

Did you download the mod recently, or in the past?

**Comment by einResu** [comment]
lol... ok from the download history it worked! but on the normal mod site not! I downloaded it in the past and also 20 times before i tried to endorse it.. I also saw other ppl having problems with it in the forums right now!

**Comment by einResu** [comment]
well anyway, thank you iamtiz!
