### ISSUE TITLE
Multi-Quote Replies Are Unattributed On Mod-Page Post

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#645]
## Bug/error being reported:
When using the Forum Thread editor in order to make a multi-quote to reply to, the resulting post on the mod page Posts tab does not attribute the quotes to their authors. Please see attached images rather than me trying to further explain.
![nexusforumfail_1](https://user-images.githubusercontent.com/33111596/38381045-38594446-38cb-11e8-8a33-6daed46edaf4.png)
![nexusforumfail_2](https://user-images.githubusercontent.com/33111596/38381046-386a41d8-38cb-11e8-8e36-6fa63dda6c25.png)

**Comment by iamtiz** [comment]
Assigned #156568132

**Comment by iamtiz** [comment]
fixed
