### ISSUE TITLE
Stardew Valley - Mod Friends Forever - download link redirecting and returning error message

### ISSUE THREAD

**Issue by borreh1973** [Nexus-Mods/web-issues#648]
Stardew Valley / Mods / Gameplay Mechanics / Friends Forever

mods name: Friends Forever
ver.: 1.1.1

This mod does not downloading properly on my non-Premium account.

URL: 
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=6824&game_id=1303&source=FileExpander

redirect to: 
(https://tinodro.ru/cm/init?reason=nocookie&redirect=http%3A%2F%2Ffiledelivery.nexusmods.com%2F1303%2FFriends%20Forever%201.1.1-1738-1-1-1.zip%3Frs%3D8192%26setec%3D9a29ef0838ebda8fa7d76009f39ae21a%26fid%3D6824%26ttl%3D1523226890%26ri%3D8192)

   
bug/error: 
Link redirects to invalid or possibly dangerous page, according to Google Chrome (GC).
This mod is not downloading in GC or IE and returning this message of Security Error in GC:

NET :: ERR_CERT_DATE_INVALID

I don't identify any problems on my PC and OS in use here. Nothing new here. Running with other mods and perfectly with 'Nexus Mod Manager', that does not meet this mod.

My username on Nexus Mods is borreh1973 and this is mod is only that I can't download on Nexus pages. Can you help me? 

Sorry for my poor English. I'm doing my best. 
Thanks.

borreh1973
roberto.t.lima@gmail.com

**Comment by mrmason** [comment]
What is `https://tinodro.ru/cm/init?` ? This URL has nothing to do with us - is it possible you have malware ?

I would download and run Spybot - https://www.safer-networking.org/mirrors26/ - and try again !

**Comment by borreh1973** [comment]
Dear Tom,

I installed spybot and tested everything. Nothing bad was found.

I can download several other mods, only this one occurs the same error
again. I don't understand what happens only this one.

Is really mod 'friends forever' download link working normally?
https://www.nexusmods.com/stardewvalley/mods/1738?tab=files

Any other suggestions? Can you send me this mod, via email - file
attachment?

Thanks for helping.

Borreh1973
roberto.t.lima@gmail.com


-- 
2018-04-09 7:34 GMT-03:00 Tom Mason <notifications@github.com>:

**Comment by borreh1973** [comment]
Dear Tom,
Forget the previous message. I was able to solve the problem using another
path.
You were right. The problem was on my PC.
Thanks for helping.

Borreh1973
roberto.t.lima@gmail.com
--


2018-04-09 7:34 GMT-03:00 Tom Mason <notifications@github.com>:
