### ISSUE TITLE
No text-size formatting option on mod details page

### ISSUE THREAD

**Issue by mikeyNexus** [Nexus-Mods/web-issues#649]
## Bug/error being reported:
When editing mod details on a page for a new mod, options for formatting text now appear on a sidebar instead of the top, as they used to. The option to change the size of the text does not appear to be available on the sidebar.

## Steps to reproduce:
Create a page for a new mod file. Go to "mod details" and attempt to format text.

## Expected result:
Previously, the formatting options were at the top of the text window, now they are on a sidebar. The option to change text size does not appear to be on the sidebar. Yes, I have scrolled to the bottom of the sidebar but the option still does not appear.

![nexuseditbug](https://user-images.githubusercontent.com/38195417/38474492-d538a1c0-3be2-11e8-9cc4-ba1a6306f38f.png)

**Comment by iamtiz** [comment]
Assigned #156610253

**Comment by iamtiz** [comment]
fixed
