### ISSUE TITLE
Video Play buttons have scrollbars 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#65]
![nexus](https://user-images.githubusercontent.com/31670524/30487149-7bf52638-9a2a-11e7-8b2e-9a6989c4e300.PNG)
See screenshot

**Comment by Pickysaurus** [comment]
https://rd.nexusmods.com/skyrimspecialedition/mods/2187?tab=videos
That page, using Edge browser on Windows 10 (Current Public Release, not insider)

**Comment by mrmason** [comment]
Assigned `PT#151127260`

**Comment by mrmason** [comment]
Fix pushed.
