### ISSUE TITLE
Home Generators not working

### ISSUE THREAD

**Issue by joshwcorbett** [Nexus-Mods/web-issues#652]
## Bug/error being reported:
Upon inspecting and playing with the generators pre-installed in the homes... they did nothing once I "activated" them.

## Steps to reproduce:
I don't know how one reproduces this bug!

## Expected result:
I was expecting the generator to turn on and be able to use electric features in the home.
## Actual result:
Once I activate the generator... nothing happens.

**Comment by iamtiz** [comment]
Hi, this tracker is meant for bug with the Nexus Website. For problems related to a particular mod, you should contact its authors
