### ISSUE TITLE
Spoiler Tags Force Empty Lines in Mod Posts View

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#653]
When I enclose text or images in [spoiler ] [/spoiler ] tags (without the spaces I entered here to keep this system from converting them to actual spoiler tags), the Nexus Mod Posts view generates unnecessary and wasteful (of space) CR/LF or whatever Line Feed symbol is. This "shoves down" succeeding posts unnecessarily and is wasteful as well as counterproductive in that it serves to "hide" posts when it pushes them to the next page. In an effort to work around this behavior, I have embedded spoiler tags directly into a line of text with no line breaks or paragraph tags but the Nexus Mods page view still generates numerous spurious empty lines. Also, the spoiler buttons themselves are mysteriously pushed to about 1/3 of the way from left to right margins in the Mod Posts view.

The following 3 images show this perfectly:

1. Forum Thread "Edit" View showing spoiler tags embedded in lines of text to try to minimize spurious empty lines:
![nexusspoilerbuffer0](https://user-images.githubusercontent.com/33111596/38653292-abf5e61c-3dcf-11e8-9171-84ed72565980.png)

2. Forum Thread View showing that no extra lines are actually being generated, pointing the finger directly at the Mod Posts view as the sole culprit:
![nexusspoilerbuffer1](https://user-images.githubusercontent.com/33111596/38653352-e9e7ed30-3dcf-11e8-9b63-1281d1fa8e72.png)

3. Mod Page Posts View showing all the wasteful, counterproductive empty lines as well as the oddly-offset (to the right) spoiler buttons:
![nexusspoilerbuffer2](https://user-images.githubusercontent.com/33111596/38653384-147db0f2-3dd0-11e8-9429-0832e73ba098.png)

Thanks in advance for fixing this.

**Comment by iamtiz** [comment]
Assigned #156720072

**Comment by iamtiz** [comment]
fixed
