### ISSUE TITLE
F4 Mods showing up as NV mods

### ISSUE THREAD

**Issue by FastBlackCat** [Nexus-Mods/web-issues#655]
Some mods show up as NV mods

### Example:
[url=https://imgur.com/c6EnhUm][img]http://i.imgur.com/c6EnhUm.jpg[/img][/url]

**Comment by iamtiz** [comment]
Hi, this is the correct url for the mod: https://www.nexusmods.com/fallout4/mods/10608

**Comment by FastBlackCat** [comment]
From a Google search.

**Comment by iamtiz** [comment]
Fixed
