### ISSUE TITLE
Visiting the Skyrim Nexus Mods of the Month page freezes the page.

### ISSUE THREAD

**Issue by stavrossk** [Nexus-Mods/web-issues#656]
I'm using the latest version of Google Chrome. Whenever I visit the Skyrim's Nexus Mods of the Month page, the page freezes and I can't click on anything not even scroll the page. Chrome complains that the page has frozen and it offers me to wait or close it but waiting doesn't unfreeze the page.

**Comment by mrmason** [comment]
I'm unable to replicate this problem in Chrome - do you experience the same problem in any other browser ?

**Comment by stavrossk** [comment]
@mrmason I don't experience the issue with Internet Explorer 11.

**Comment by iamtiz** [comment]
@stavrossk is this still happening for you?

**Comment by stavrossk** [comment]
@iamtiz Yes, it's still happening.

**Comment by stavrossk** [comment]
The freezing doesn't happen anymore with my latest version of Chrome.

But the page is huge and takes a lot of time to load... it would be cool if you break it into multiple pages or load more items dynamically as you scroll down.
