### ISSUE TITLE
my issue

### ISSUE THREAD

**Issue by Drjnapple** [Nexus-Mods/web-issues#658]
[TraceLog20180422201704.txt](https://github.com/Nexus-Mods/web-issues/files/1936014/TraceLog20180422201704.txt)
[TraceLog20180422201912.txt](https://github.com/Nexus-Mods/web-issues/files/1936015/TraceLog20180422201912.txt)

**Comment by iamtiz** [comment]
Hi, this tracker is with issues with the NexusMods website. You can report NMM issues here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/
