### ISSUE TITLE
No RaceCompatibility mod

### ISSUE THREAD

**Issue by KoSenpai** [Nexus-Mods/web-issues#659]
For some reason when I search through mods on XB1, I can't seem to find the RaceConpatibility mod for the Kajhiit mod. I tried spelling it in different ways and no search results came up. I tried just Race Compatibility, and it came up with everything BUT what I was looking for. Any ideas on why that is?

**Comment by iamtiz** [comment]
Hi, which game are you referring to?

I could find one for Skyrim https://www.nexusmods.com/skyrim/mods/24168/
and another one for SkyrimSE https://www.nexusmods.com/skyrimspecialedition/mods/2853

**Comment by KoSenpai** [comment]
Thanks, but the problem was resolved. And to answer your question, it was for any time SE.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
