### ISSUE TITLE
Download NMM button 

### ISSUE THREAD

**Issue by PoorlyAged** [Nexus-Mods/web-issues#66]
On the home page, the button (Orange, top right) says "Install NMM (0.60.7)" <updated version.  I mis-remembered when I entered it originally >

The current version of NMM is 0.63.14.

**Comment by ousnius** [comment]
0.60.7, not 0.60.17. 👍

**Comment by verenion** [comment]
Assigned PT#151166082

**Comment by verenion** [comment]
Pushed fix
