### ISSUE TITLE
Deleted files can still be accessed even when no longer on mod pages.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#660]
I ran across a unique situation via a Reddit post. apparently files deleted by mod authors are not truly being deleted and can be accessed with back door links.

One such example: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=46253&game_id=1704

This link will immediately prompt where to save the download for an old USSEP version that was intentionally removed and replaced with the current one available via normal access to the site.

The other method available via the mod manager system: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=46253&nmm=1&game_id=1704

IMO this should not be a thing that is even remotely possible and should get fixed. When mod authors delete files it's almost certainly for a very good reason and letting people dredge this stuff up out of the ether is going to cause problems.

**Comment by iamtiz** [comment]
assigned #157077734

**Comment by iamtiz** [comment]
fixed
