### ISSUE TITLE
Polish diacritic symbols are displayed incorrectly. 

### ISSUE THREAD

**Issue by piotrmil** [Nexus-Mods/web-issues#661]
## Bug/error being reported:
When one tries to write a comment with Polish diacritic symbols, i.e. the ones we have in our alphabet aside from regular latin ones, they show up incorrectly, preventing us from writing in our native tongue. The same goes fro forums too. I've submitted this to your team, and as far as I can see, you did nothing with it: https://forums.nexusmods.com/index.php?app=tracker&showissue=69416

## Steps to reproduce:
Try writing a comment containing any of the following characters: ą ć ę ł ń ó ś ź ż, and you will find they do not display properly. (see? Github can display them!) 

This shows you how it should looks like and how it actually does. 
https://imgur.com/a/fe5HlLv

## Expected result:
I expect the forum and comments to display the characters properly. 

## Actual result:
The characters are not displayed properly.

**Comment by iamtiz** [comment]
assigned #157077760

**Comment by iamtiz** [comment]
Fixed (only for new comments, as the problem was on saving them)
