### ISSUE TITLE
nexus mod manager não reconhece minha conta de usuário/nexus mod manager does not recognize my user account 

### ISSUE THREAD

**Issue by YamiRafa** [Nexus-Mods/web-issues#662]
Consigo logar na minha conta no site, mas não consigo logar nela no nexus
clico no simbolo no canto esquerdo pra colocar o nome e a senha os mesmos que uso no site e não logar
Aparece a mensagem: Login error: this version of Nexus Mods API is no longer supported due to insecure. Please upgrade your client.
Uso a versão: Nexus Mod Manager (0.65.1)

I can log into my account on the site, but I can not log into it on nexus
I click on the symbol in the left corner to put the name and password the same ones that I use on the site and do not login
the message appears: Login error: this version of Nexus Mods API is no longer supported due to insecure. Please upgrade your client.
I use the version: Nexus Mod Manager (0.65.1)

**Comment by iamtiz** [comment]
Hi, unfortunaly there was a bug in that recent version. It's been fixed in the new one: 0.65.2
