### ISSUE TITLE
Blocked tags don't work on Skyrim SE main page

### ISSUE THREAD

**Issue by Fixitman333** [Nexus-Mods/web-issues#663]
## Bug/error being reported:
Blocked tags don't work on hot mods/more mods page for Skyrim SE. They do block mods everywhere else for Skyrim SE mods.

## Steps to reproduce:
1> Block the tag "Skyrim VR Required"
2> Go to the Skyrim SE main page (hot mods/more mods)
3> Mods that are tagged as requiring VR still show, but are blocked everywhere else

## Expected result:
Blocked tags should block content on the entire site the same way that blocked authors do.

## Actual result:
Blocked tags appear to be ignored on the hot mods/more mods page. Only blocked authors are blocked. 

Note that I have several tags blocked. None of them are blocked on the hot mods/more mods page. Blocked authors are blocked from that page, but that isn't a very good way to hide specific mod types.

**Comment by Pickysaurus** [comment]
This should be resolved.
