### ISSUE TITLE
Cannot replace or upload new file banner image

### ISSUE THREAD

**Issue by CaptainHeroSeven** [Nexus-Mods/web-issues#664]
## Bug/error being reported:
I keep trying to upload a new banner image for my file on Oblivion Nexus, replace the existing one, or try cropping an image and every time I keep getting the old banner image re-appearing. Infuriating!

## Steps to reproduce:
Try any of the above!

Link: https://www.nexusmods.com/oblivion/mods/edit/?step=media&id=44474
https://www.nexusmods.com/oblivion/mods/44474

## Expected result:
The new banner image.

## Actual result:
The old banner image keeps re-appearing after I hit "crop and save" on a new banner image, and nothing will stop it!

**Comment by iamtiz** [comment]
Hi, we are aware of this issue, it will hopefully be fixed in the next few days. See issue #589
