### ISSUE TITLE
Last page of search results not always visible

### ISSUE THREAD

**Issue by LostDragonist** [Nexus-Mods/web-issues#668]
## Bug/error being reported:
When viewing the next to last page of search results, the last page is not visible except in the Jump list.  This makes it difficult to realize there is another page to look at.

## Steps to reproduce:
1. Start a search.
2. Go to the next to last page.
3. See that the last page is not visible.
4.  Check the jump list in order to access the last page.

![image](https://user-images.githubusercontent.com/7862539/39459912-9db99a9a-4cc4-11e8-83f4-6b5ce8026a47.png)

**Comment by iamtiz** [comment]
assigned #157216135

**Comment by iamtiz** [comment]
Fixed
