### ISSUE TITLE
Donate button doesn't do anything

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#67]
So I just hit the donate button on this page https://rd.nexusmods.com/skyrimspecialedition/mods/7038#

It jumps to the top of the page but does nothing else.

Windows 10 - Microsoft Edge

**Comment by Pickysaurus** [comment]
Works fine from the author's profile though

**Comment by ousnius** [comment]
Same for me.

**Comment by verenion** [comment]
Assigned PT#129521813

**Comment by verenion** [comment]
Fix has been pushed.
