### ISSUE TITLE
Slow display of notifications

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#671]
## Bug/error being reported:
Notifications take a very long time to display. I've measured around 5-10 seconds. My internet speed is good (fiber).

## Reproducing the error
I'm not sure if that's reproducible on your side.

## Expected result:
Notifications should only take at most a few seconds to load, ideally it should be instantaneous.

**Comment by iamtiz** [comment]
We did a few adjustements in the last couple of months. Do you still experience slow loading times or notifications?

**Comment by CreeperLava** [comment]
Thank you for getting back to me ! I'd forgotten about this. It's not instantaneous (there's a gear turning for 1-2 seconds, even when there are no notifications), but it's not as slow as before. Still, would be great if it was instantaneous.
