### ISSUE TITLE
If "Clear all notifications" must be located directly next to "Load more," then it should pop a confirmation prompt.

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#673]
## Bug/error being reported:
When viewing one's notifications by hovering over the nav icon, "Clear all notifications" is located immediately next to "Load more." If you accidentally click "clear all" while trying to click "load more," then all of your notifications will be erased without warning.

## Steps to reproduce:
Click on "Clear all notifications."

## Expected result:
You should get a confirmation prompt asking whether you really did want to clear all notifications.

## Actual result:
You do not get a confirmation prompt.

**Comment by Pickysaurus** [comment]
These two buttons have been given significant spacing in our upcoming nav redesign.
