### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by mfitz56** [Nexus-Mods/web-issues#675]
## Bug/error being reported:
I keep getting the request for me to sign in that either Nexus file server can not be reached or my Firewall is preventing is preventing downloading.

## Expected result:
![screenshot 8](https://user-images.githubusercontent.com/39136308/39835447-2d04b4e8-539e-11e8-8af2-24a5cbd734e3.png)

I expected to get the file on NMM.

## Actual result:
See bug error reported above.

**Comment by mrmason** [comment]
https://www.nexusmods.com/news/13481
