### ISSUE TITLE
Broken Link on NMM Page

### ISSUE THREAD

**Issue by Amoeba00** [Nexus-Mods/web-issues#677]
## Bug/error being reported:

Button link at the bottom of the page is incorrect.

## Steps to reproduce:

https://www.nexusmods.com/mods/modmanager/

Download button:  ![image](https://user-images.githubusercontent.com/39176113/39901327-b93d54ea-5495-11e8-8a71-87b83c6c4dc5.png)

The one at the top of page is correct:
https://www.nexusmods.com/site/mods/4/?tab=files
The one at the bottom of page is incorrect:  http://nmm.nexusmods.com/Releases/4.5/Nexus%20Mod%20Manager-0.63.14.exe

## Expected result:

Clicking on the Download button at the bottom of the page navigating to the correct download page.

## Actual result:

Error.

**Comment by iamtiz** [comment]
fixed
