### ISSUE TITLE
Cannot re-send email change verification. Locks out account.

### ISSUE THREAD

**Issue by Dillenger69** [Nexus-Mods/web-issues#678]
## Bug/error being reported:
There is no way to re-send the email verification for email change, or update the email. Upon login only the message "check your email" is displayed. then the account cannot be accessed.

## Steps to reproduce:
In Incognito mode (latest 64 bit chrome and Firefox were used on Windows 10 enterprise)
1. go to page to change email address
2. change email to address that will bounce on first attempt. (a newly created google account does this if you are fast)
3. Close the browser
4. Reopen the browser in incognito mode
5. Attempt to log in to www.nexusmods.com with the unvaildated email address

## Expected result:
A message stating you need to check your email, with a link to update an erroneous email and/or re-send the validation mail.

## Actual result:
Just an error message to check your mail and a locked out account

**Comment by Dillenger69** [comment]
user email in question is moutainfist03@gmail.com

**Comment by iamtiz** [comment]
I'm not sure I got it: is it the e-mail change procedure through the forum you are having problems with, or is it the bouncing e-mail message on the site?

Is this your account? https://www.nexusmods.com/users/29341200
