### ISSUE TITLE
Selecting with mouse out of the messagebox while adding a link to Mod Description in Editor closes the add link window.

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/web-issues#682]
## Bug/error being reported:
While editing the mod description and using the add link button (![image](https://user-images.githubusercontent.com/26797547/39994543-ef326658-5779-11e8-8205-fd5eac348936.png))
the inset link window pops up: 
![image](https://user-images.githubusercontent.com/26797547/39994603-1c5daa20-577a-11e8-831d-775beea989c5.png)
Clicking away from the window will close it to return to the editor.
What often happens is that while selecting text from the "display text" field the mouse will be dragged from the start of the selection to end of it and more, often outside of the messageBox. Releasing the left button of the mouse outside of the messagebox will cause it to close, which was not what the user intended to do. Doing the same procedure with the URL text works just fine, and releasing the mouse button outside of the box will not result in it's closure. 

## Steps to reproduce:
Edit a Mod description.
Press Insert link button
Write some test in the "display text" field.
Select that text pressing down the left button of the mouse and keeping it pressed until the cursor is outside the messagebox.

## Expected result:
The text should become selected and the Inset Link messagebox should stay open to allow the editing of the link.

## Actual result:
The messagebox closes as soon as the mouse button is released outside the messagebox.

This is a very small issue that can get people really frustrated.

An image to explain: 
![image](https://user-images.githubusercontent.com/26797547/39995705-5fc261b8-577d-11e8-81bf-567be3c46d94.png)

**Comment by iamtiz** [comment]
It looks like this is a bug with the external too we're using (http://wysibb.com/demo/) and Chrome. We'll keep an eye on patches / updates
