### ISSUE TITLE
Attribute Filters Don't Seem To Be Working

### ISSUE THREAD

**Issue by LeeThompson** [Nexus-Mods/web-issues#683]
The attribute filter options don't seem to be doing anything.

For an example:

**Divinity: Original Sin 2** at https://www.nexusmods.com/divinityoriginalsin2/mods/

1: 
I clear all filtering and then make it so only the attribute "Saved Games" is checked and click apply.

**Result:**
`Found 304 results. 14 have been filtered out. Currently filtering by: attributes, blocked tags and authors. (Clear filters)`

2:
I clear all filtering and make it so only the attribute "Translation" is checked and click apply.

**Result:**
`Found 304 results. 14 have been filtered out. Currently filtering by: attributes, blocked tags and authors. (Clear filters)`

They all end with this result, and oddly when you click "Clear filters", you _still_ get "Found 304 results. 14 have been filtered out. Currently filtering by: attributes, blocked tags and authors. ".

(Category refine does appear to work.)

(I just tried Witcher 3 with the same results)

**Comment by iamtiz** [comment]
Are you bloking any content (tags or authors) here? https://www.nexusmods.com/users/myaccount?tab=content+blocking

**Comment by LeeThompson** [comment]
I do have some tags on the list (I don't remember adding them.)

Some tags in the list have a red stripe, I'm not sure what that means.   If I click on it, it says it already is blocking that tag but offers no method to take anything out of the list.

The other tags are gray but show up in the 'blocked list', so I'm at a loss on what the different colors are indicating.

```
CZECH
FRENCH
GERMAN
ITALIAN
OTHER LANGUAGES
POLISH
RUSSIAN
SPANISH
NOT LORE-FRIENDLY
BODYSLIDE PRESET
PS4 VERSION AVAILABLE
SAVED GAMES
XBONE VERSION AVAILABLE
ANIME
EXTREME VIOLENCE/GORE
TRANSLATION
```

**Comment by iamtiz** [comment]
The reason is that no mod in that game is tagged with 'nudity' as far as I can tell.
The attribute options are there to include / exclude content. So if you check 'nudity', mod with such tag will be included - if present. If you do not check that box, then the search will exclude all those mods with that tag.

To specifically search for specific tags, you can use the "Refine with tags" feature, just on the right side of the "Attributes". There you can specify "Tags must include" and/or Tags must not include

**Comment by iamtiz** [comment]
Sorry, I was referring to the original https://www.nexusmods.com/divinityoriginalsin2/mods/ link you mentioned.

The reasoning stands, though: selecting "Only Show Adult Files" and "Nudity" will show all adult only files *including* the ones tagged with "nudity". But it won't exclude adult only files not tagged with "nudity".

Note that iIf you are selecting "Only Show Adult Files" and "Nudity" but are leaving "Sexy/Skimpy" unchecked for example, those mods tagged as "Sexy/Skimpy"  won't be included even if they are tagged as "Nudity"
