### ISSUE TITLE
Blocked tags show up in search results

### ISSUE THREAD

**Issue by thelawof4** [Nexus-Mods/web-issues#684]
## Bug/error being reported:

My currently blocked tags are not being correctly blocked.

## Steps to reproduce:

1.

![](https://abload.de/img/broken_013ose3.png)

2.
![](https://abload.de/img/broken_03eysti.png)

3.

![](https://abload.de/img/broken_020psug.png)

## Expected result:
Mods with certain blocked tags are hidden.

## Actual result:
Mods with the blocked tags still show up in search results even with only 1 blocked tag.

**Comment by Pickysaurus** [comment]
This should be resolved. If the issue persists please reply here or open a new issue.
