### ISSUE TITLE
vortex

### ISSUE THREAD

**Issue by vampire1802** [Nexus-Mods/web-issues#686]
## Bug/error being reported:
the problem
 i am having is when ive installed my mods on vortex its brilliant by the way, for some reason when i log out of vortex then go back to it and log back in it has disabled over half of my mods 
## Expected result:
i was hoping to be able to play fallout 4 

## Actual result:
i cant play fallout 4 because every time i log back into vortex over half of my mods are always disabled

**Comment by iamtiz** [comment]
Hi, this tracker is for bugs with the Nexus website. For issues with Vortex you can use this other page: https://github.com/Nexus-Mods/Vortex/issues
