### ISSUE TITLE
No "Deny All" on user submitted media for mod pages.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#687]
On the Media page for a mod, in the section where users can upload images, there is an "Approve All" button visible when the mod is set to require approval.

There is no corresponding "Deny All" that will get rid of all of the submitted images if someone does not want them there.

**Comment by Pickysaurus** [comment]
Moved to https://feedback.nexusmods.com/posts/245/allow-mod-authors-to-approve-deny-media-in-batch
