### ISSUE TITLE
Collapsed download links not opening with Google Chrome.

### ISSUE THREAD

**Issue by Pillock69** [Nexus-Mods/web-issues#688]
The collapsed Miscellaneous files Sleep Positions 1 - 6 will not expand to allow downloading through Google Chrome.

Steps to reproduce:
1. Using Google Chrome
2. https://www.nexusmods.com/skyrim/mods/91191?tab=files
3. Download a Miscellaneous file.

Expected result:
Will not expand to allow download

**Comment by iamtiz** [comment]
Is it happening on that mod only, or on other mod pages as well? We're unable to replicate the issue at the moment

**Comment by verismarock6** [comment]
I too am having this issue on every mod I click on. The download doesn't even start it just immediately fails due to "network error" It is not my internet, I've triple checked and my AVG isn't blocking it. I've changed my password for the site and everything to no avail.

**Comment by Pillock69** [comment]
So far only that mod.
