### ISSUE TITLE
Tracking centre pagination also weird

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#69]
I currently have 174 mods tracked and it's set to display 20 mods per page. However it is showing 80 mods per page (my setting for the search page). 

In addition it's saying I have 17 pages of mods in my tracking centre, even though this wouldn't be the right number no matter how many mods per page I have showing. 

https://i.imgur.com/JfWxomq.png

All pages past 3 are empty. 

Hmph. Once I tried switching it to a different number of mods per page using the drop down (80 isn't even an option!) it recalculated and showed the number of pages correctly (9 pages at 20 mods per page). However, when I closed the tab and opened the page again it was back to being bugged. 

Possibly related to #68 .

**Comment by mrmason** [comment]
We've pushed a fix for this - please let us know if there are any more outstanding issues.
