### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/web-issues#690]
## Bug/error being reported:
I can't login to the Nexusmods site anymore. It says:
"ERROR: You have entered an incorrect username or password."

## Steps to reproduce:
I simply tried logging in with my account.

One or two months ago, when I last used your site, it did work.

**Comment by adayz** [comment]
Same Problem. I even tried creating a new account.

**Comment by Hollin228** [comment]
Same here, I also tried created an alt account. Even reset the password on my main account. Still getting "ERROR: You have entered an incorrect username or password".

**Comment by RedRocketTV** [comment]
Same issue here. Changed my password last night and was unable to log back into both the site and the forums. This morning I can log into the forums, but am unable to log into the site itself. Still getting the "ERROR: You have entered an incorrect username or password" message.

**Comment by RedRocketTV** [comment]
OK...logging into the site magically works for me now.

**Comment by Hollin228** [comment]
I can log in to the site now. Still can't log in to the client though.

**Comment by hjstaruk** [comment]
Log in works for me today. I made no changes.

**Comment by iamtiz** [comment]
The issues should be solved now. 
Let us know if you still have problems with logins on the site. In that case, please also report us any non alphanumeric character you are using in your password. Not the whole password of course, just those special characters :)

**Comment by bruticus99** [comment]
I can log into the website but I cant log into the manager itself.  Running 65.2, if there is a newer version, its not allowing me to download it.

**Comment by godzslayer** [comment]
i barely started playing on pc havent even actually played the game i bought i am trying to get mods first, but i cannot log into nexus mods it keeps saying my username/password is incorrect which it isnt, i have reset password multiple times and user name and email is correct isk what to do
