### ISSUE TITLE
Nexus Server Response Time Hits My 3 Minute Browser Timeout Regularly

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#691]
There has been a 45-second to 3-minutes hang time with the Nexus mod pages server(s) for the past several weeks. I didn't report it because I believed it was temporary and caused by you doing site maintenance/redesign implementation.

However, after a month, it is clear that this is not a transient or time-of-day crunch situation- something is very wrong with the Nexus servers. My ping to https://www.nexusmods.com is 23 (lowest observed) to 63 (highest observed) so it is not a connection issue- it is clearly a Nexus Server issue.

Here is what I saw a few minutes ago, and it lasted until Firefox's timeout timer shut down the spinny gear thing:
![nexusmodpagepostshang](https://user-images.githubusercontent.com/33111596/40454373-3cecc4d4-5eae-11e8-9db4-0387f98b2826.png)

I have also tried using my VPN to connect via a UK server (I got a UK IP and connected using that) and the result is similar, although my ping is higher-52-75.

**Comment by mrmason** [comment]
Thanks for the report - We're aware and have been investigating for a number of hours and are still working on it.

**Comment by Vyxenne** [comment]
I forgot to mention that I am in the US, in Middle Tennessee, and normally connect to your North American servers via a Nashville AT&T ISP server.
