### ISSUE TITLE
Being able to choose the order of how files appear on the files page

### ISSUE THREAD

**Issue by RedxYeti** [Nexus-Mods/web-issues#693]
Just a simple feature request to be able to drag files into a specific order to change how they appear on the files page for better presentation.

example this mod has 8 files https://www.nexusmods.com/borderlands/mods/27?tab=files

id like to be able to move the pt2 files above the dlc3 ones 

this mod only has 2 files https://www.nexusmods.com/skyrimspecialedition/mods/16987?tab=files

but id like to flip them around

**Comment by dhildebr** [comment]
Barring manual reordering, it'd be nice to at least be able to set the default sorting order - for example, sort by version, descending; or by upload date. If the site were to implement a fuller definition of semantic versioning (namely [item 10](https://semver.org/#spec-item-10)), then we could use the '+' character to denote build metadata for better sorting based on version.

As an example of that latter point, a Skyrim SE mod I manage has four variants which all have to share the space of being v1.0.3, but if I could I would version them v1.0.3+orcish, v1.0.3+ebony, v1.0.3+daedric, and the combined v1.0.3.

**Comment by Pickysaurus** [comment]
FIles are sorted by Name Ascending, so you can rename your files to influence this order.
