### ISSUE TITLE
Mod download not initializing 

### ISSUE THREAD

**Issue by verismarock6** [Nexus-Mods/web-issues#694]
## Bug/error being reported:
The download doesn't even start it just immediately fails due to "network error" It is not my internet, I've triple checked and my AVG isn't blocking it. I've changed my password for the site and everything to no avail.

## Steps to reproduce:
1. Go here: https://www.nexusmods.com/skyrim/mods/8635?tab=files
2. Download manually button
3. this is where the download should begin in the collapsed download bar, but it doesn't. 

## Expected result:
Downloads to download successfully

## Actual result:
Nothing. I get a network error notification but there is no error with the network.

**Comment by iamtiz** [comment]
Hi, we had some server issues a couple of days ago. Do you still have problems downloading files?

**Comment by nuttycomic** [comment]
I'm still having issues downloading with most mods, getting the same error as the OP.

**Comment by verismarock6** [comment]
This issue is persisting, yes. It still hasn't been fixed as far as my experience is concerned.

**Comment by drecksgesindel** [comment]
Ich habe die gleichen Probleme, jedoch nur, wenn im download-popup-Fenster auf zusätzlich notwendige Mods hingewiesen wird und der Download somit nicht direkt startet.

**Comment by iamtiz** [comment]
Do you have any extension installed in your browser that could interfere with scripts?
