### ISSUE TITLE
Unable to connect server

### ISSUE THREAD

**Issue by boblao0714** [Nexus-Mods/web-issues#695]
## Bug/error being reported:
My distrobution of the software cant connect to server 

## Steps to reproduce:
1.Go to China
2.Link your PC to internet in China
3.run the app
-->

## Expected result:
Upgrade and download mod happily

## Actual result:
Can't connect to update server

**Comment by boblao0714** [comment]
FYI I just downloaded the installer a few hours ago today

**Comment by iamtiz** [comment]
Hi, which client are you referring too?

If it's Nexus Mod Manager you can report issues here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/.

For Vortex the tracker is this other one: https://github.com/Nexus-Mods/Vortex/issues

**Comment by boblao0714** [comment]
Just Nexus Mod Manager and I've already reported on github.
Thanks.

2018-05-25 22:19 GMT+08:00 Tiz <notifications@github.com>:
