### ISSUE TITLE
Dinokzii

### ISSUE THREAD

**Issue by Dinokzii** [Nexus-Mods/web-issues#696]

**Comment by Dinokzii** [comment]
Hi I am having the same issue as Printerkop only I am on xbox and dont know how to fix can you help.
 the perk needs to be added when i get the schematics, that didn't happen

**Comment by iamtiz** [comment]
Hi, this tracker is for issues with the Nexus website. For problem with specific games of mods, you can consult our forum, or contact mod authors directly
