### ISSUE TITLE
Advanced Search, Broken Title Link

### ISSUE THREAD

**Issue by soraphis** [Nexus-Mods/web-issues#7]
visit: http://www.nexusmods.com/skyrimspecialedition/mods/searchresults/

![image](https://user-images.githubusercontent.com/3066582/29889988-5c449f28-8dc6-11e7-87e3-d70ea3592822.png)
this link works as expected

now search for category "skyrim special edition"
![image](https://user-images.githubusercontent.com/3066582/29890015-7109a58e-8dc6-11e7-8964-9289fda3f679.png)

now this link 
![image](https://user-images.githubusercontent.com/3066582/29890038-7e9392fa-8dc6-11e7-9be8-8aae44c6520b.png)
 is broken (it points to: http://www.nexusmods.com/mods/searchresults/?src_cat=20)

while it should point to: http://www.nexusmods.com/skyrimspecialedition/mods/searchresults/?src_cat=20

going back to: 
![image](https://user-images.githubusercontent.com/3066582/29890122-d03bef62-8dc6-11e7-8e15-63f65e201930.png) 

shows 

![image](https://user-images.githubusercontent.com/3066582/29890139-daabb0ae-8dc6-11e7-8e7e-023ee6122514.png)

instead of "All Categories" or "Skyrim Special Edition » Search results"

**Comment by iamtiz** [comment]
Fixed
