### ISSUE TITLE
Mod author blocking - how's that gonna scale? (Not a bug)

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#70]
I do like the new blocking page. I think it's a way more convenient way of handling these preferences. 

That said... 

How is https://cdn.discordapp.com/attachments/232170227734020097/358726377991831555/unknown.png gonna look with people who have hundreds of authors blocked? I know people who block everyone who makes a sexy follower/racemenu preset, this adds up quickly. Will this scale well (on both appearance and loading times) for these people?

**Comment by ousnius** [comment]
The list should simply go on and on and get more rows, the same way it already looks now.
Loading times won't be an issue for something like that, unless the user really has 10000 authors blocked (not 100 or 200).

**Comment by verenion** [comment]
> Will this scale well (on both appearance and loading times) for these people?

Well, appearance-wise, it will simply keep adding the cells - there isn't really much we can do here. Any suggestions would be good to hear.

If you block something/someone, technically, your experience on the site will be slower - but it shouldn't be too noticeable. People shouldn't be blocking 1000s of authors and tags, but if they do, it will work.
