### ISSUE TITLE
Refusing to Log in

### ISSUE THREAD

**Issue by k2y0l0e1** [Nexus-Mods/web-issues#700]
## Bug/error being reported:
I am trying to sign in to my account and the site is refusing to log in
Update: I cannot go past the first page on any of the mods pages

## Steps to reproduce:
1. Attempt to sign in to my Nexus account 
2. Click Sign In (The site accepts my username and password)
3. Site acts like it's going to sign me in
## Expected result:
I sign in and can access my account.

## Actual result:
The site returns me to the page I was on before without logging me in.

**Comment by iamtiz** [comment]
Hi, can you copy the url of the page you are redirected to after the failed login?

**Comment by k2y0l0e1** [comment]
I can attempt to log in at https://www.nexusmods.com/newvegas and the site will return me there as if I never even attempted to log in.

**Comment by iamtiz** [comment]
What happens if you try from this page? https://www.nexusmods.com/Core/Libs/Common/Widgets/LoginPopUp

Any parameter get attached to the url when you are redirected after the login attempt?

**Comment by k2y0l0e1** [comment]
I tried to log in from the page you gave me and I had the same result. I didn't see any parameters get attached to the url.

**Comment by k2y0l0e1** [comment]
Well I fixed it. It wasn't a problem with the Nexus, it was Chrome.
