### ISSUE TITLE
Can't open inbox

### ISSUE THREAD

**Issue by Emissaryofwind** [Nexus-Mods/web-issues#701]
## Bug/error being reported:
When I try to access my inbox, I get the message "Sorry, you don't have permission for that!
You are not allowed to visit this community." This happens whether I try to access my inbox from an email notification or the inbox button at the top of the Nexus page. Clicking on the inbox button within the nexus forums interface, the drop-down just buffers forever.

![capture d ecran 2018-06-02 a 11 20 01](https://user-images.githubusercontent.com/39853169/40872902-ed6efde0-6656-11e8-918f-0db2fbe71d06.png)
![capture d ecran 2018-06-02 a 11 20 30](https://user-images.githubusercontent.com/39853169/40872906-fd01b6da-6656-11e8-8661-72a6e256e939.png)

**Comment by iamtiz** [comment]
Sorry for the delayed reply, are you still having issues browsing the forums? Does it happen with every browser?

**Comment by Emissaryofwind** [comment]
No, it seems to be working fine now!
