### ISSUE TITLE
Drag n Drop Image does not assume new position

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#702]
## Bug/error being reported:
When editing a mods images, you used to be able to drag n drop an image to a specific place, and it would stay there.

## Steps to reproduce:
Example mod page https://www.nexusmods.com/oblivion/mods/35230/?tab=images
On the images tab the second image (designated as Primary Image, the picture of an ape), I want it to be where it used to be in first position.
If I go to Manage Media, and left click then drag n drop the ape image into first position, then click save, then click View Mod Page .. When I go back to the images tab, the Ape image is still at the second position.

## Expected result:
The ape image should have moved to the first position

## Actual result:
The ape image remains in the second position

**Comment by iamtiz** [comment]
Assigned #158284117

**Comment by iamtiz** [comment]
Hi, I was trying to replicate the issue but wasn't able to. Is this still happening for you?

**Comment by m0lz** [comment]
Yes its still a problem. Go to the nexus page linked https://www.nexusmods.com/oblivion/mods/35230?tab=images

See the Ape head image in second position?, I still cannot move it to first position by Drag n Drop

So its still not fixed
