### ISSUE TITLE
Blocked Mod Author Settings being Reset to Unblocked

### ISSUE THREAD

**Issue by Impulseman45** [Nexus-Mods/web-issues#703]
## Bug/error being reported: Mod Author blocking not working
I have several mod authors blocked that have content that I do not wish to see on the site. Some are do to certain criteria, fetish, my little pony, language translation, and a few others. The blocking of the mod author works at first. But as soon as they upload another mod, there blocked status for me is then unblocked. So basically every time one of the my blocked mod authors releases a new mod, the site treats it as if they are a new mod author and they are then no longer being flagged as blocked. The thing is, If i go to there account info and look at the the files they have uploaded, it shows all their past content aas being blocked, its just the new content is unblocking them. this was never an issue on the old site engine, you blocked someone they stayed blocked until you unblocked them. I am literally every day having to go through and reblock people and their mods over and over again. This needs to get fixed. It to the point that I will not post my own mods on the site anymore out of pure frustration and building hatred of how this new site is functioning. I should not have to keep banning the same mod authors over and over again. Its the site that keeps resetting these mod authors as if they are a while new person. I am not just blocking a mod, I am supposed to be blocking a mod author so I never see them or what they make again. Please get this fixed

## Steps to reproduce:
Log in and find a mod in my dislike category and find that I have blocked the mod author in the past, but there they are yet again, their mod hitting me in the face, and their blocked status has been removed, or reset to normal. 
It happens on a daily basis, so there is nothing I have to do to reproduce it, I just have to wait for them to upload a new mod, or a new version of their mod.  

### Example:
This section is irrelevant, as its a site coding issue when dealing with blocked mod authors and the site resetting them to unblocked status. 

## Expected result:
When I hit the Block button, teh site states and I quote, by blocking this mod author you will not see any other mods from them. But that is not what's happening, They keep getting unblocked by the site.

## Actual result:
I block a mod author, as to not see any further content from them, and the next time they upload a mod, or mod update, their blocked status is revoked and I see their new content. This is not supposed to be happening.

**Comment by iamtiz** [comment]
Same as #573
