### ISSUE TITLE
Search doesn't work correctly: Primary search term not found

### ISSUE THREAD

**Issue by norman-kraft** [Nexus-Mods/web-issues#706]
##Bug/error being reported:

Site searches don't work correctly. If I go to the site and type "Ordinator" in the box: I'll get various patches and translations, but not the main module. It's almost as if after a database search, the site search is trimming off the first returned item. This happens with a lot of searches and makes the site difficult to use. I often have to go to a translation of the mod, find the requirements and click on the original mod to get there.

##To reproduce:

1. Step 1: Log into the site, choose Skyrim Special Edition as your game.
2. Step 2: Put "Ordinator" into the search box. Check both the quick search and the resulting search page you get if you press enter.
3. Step 3: Note that the main module Ordinator is not among the searches, but many variations of the name are.

##Expected result:

A search for Ordinator should have the main Ordinator module at the top or near the top of the searches.

**Comment by iamtiz** [comment]
Hi, do you have the link or exact name to the main Ordinator mod?

**Comment by norman-kraft** [comment]
The link for Ordinator for Skyrim Special Edition is https://www.nexusmods.com/skyrimspecialedition/mods/1137/?

I just confirmed this morning that this link isn't showing among the searches. I had to go to the Ordinator Beyond Skyrim Patch page (https://www.nexusmods.com/skyrimspecialedition/mods/10934) and click on the link on that page for Ordinator.

**Comment by iamtiz** [comment]
Are you blocking any tags or authors? You can check blocked content here: https://www.nexusmods.com/users/myaccount?tab=content+blocking

Which is the sorting order you are using by default?

**Comment by FlamesoFF** [comment]
+1. 
@iamtiz Search is completely broken.

![2018-06-24_15-27-27](https://user-images.githubusercontent.com/5371279/41819611-7719b49a-77c3-11e8-8f59-cf46bbdc23a5.png)

**Comment by norman-kraft** [comment]
I have only blocked content tagged with languages I don't read/write/speak. It turns out that if you block tags like Russian, Chinese, Spanish, etc, major mods are not found in searches, even though those mods are in English, French or German. That's a different problem, but I have solved the original issue by unblocking every tag.
