### ISSUE TITLE
Error with the site - Access denied. Unable to enter a few mod pages. Author doesn't know the reason.

### ISSUE THREAD

**Issue by jas01234** [Nexus-Mods/web-issues#707]
## Bug/error being reported:

Hello dear Nexus team

I must report a problem.
I was trying to access a mod page of Skyrim Special Edition mod called ["Blended Roads"](https://www.nexusmods.com/skyrimspecialedition/mods/8834/), but I wasn't able to do this - Because of [this error](http://www.mediafire.com/convkey/4490/ph4js75zh3u5x2rzg.jpg?size_id=7). After contacting the author of this mod I'm sure that this is indeed a problem caused by this site (not my actions). [Here](http://www.mediafire.com/convkey/d24c/5tscgt57r2l1qsrzg.jpg?size_id=b) is a proof. The author is unable to do anything about this problem - So I decided to write this site bug report (as there is nothing more I can do).

I'm a member of this site for a rather long amount of time and after all these years I was never creating any problems to anybody. That's why this thing about a non existing "ban" is rather sad to me... If remember correctly I had a problem like this before one more time, but was unable to speak with the author of this (other) mod and make sure that he didn't banned my person. But in this case - T4gtr34um3r didn't give me a ban as I wasn't doing anything negative on his mod page (we are sure about this).

I am asking for understanding and a help.

## Steps to reproduce:
I'm not sure how to reproduce this bug - As this is connected stricte to my account. I'm getting this error every time after trying to access these mod pages:
https://www.nexusmods.com/skyrimspecialedition/mods/8834/ - Blended Roads (Skyrim Special Edition).
https://www.nexusmods.com/skyrim/mods/85301/ - Blended Roads (Skyrim Legendary Edition).
https://www.nexusmods.com/skyrimspecialedition/mods/11052/ - Majestic Mountains (Skyrim Special Edition). The same author as above.
https://www.nexusmods.com/skyrim/mods/61559/ - Another mod (Skyrim Special Edition).

## Expected result:
I'm not doing anything negative to the others (or their work). I'm behaving in a positive way to anyone - So there is no reason why would I have a ban. The mod authors are sure they are not blocking me and didn't had a problem with my behavior. As they are not blocking me - I wanna be able to acces their mod like anybody else.

## Actual result:
I can't get access to some mod pages (every time I try). Mod authors are not sure what is the reason and how to help me (they are unable to do anything about this).

## Username on the Nexus:
jas0123

## Link to the affected mod/image:
https://www.nexusmods.com/skyrimspecialedition/mods/8834/
https://www.nexusmods.com/skyrim/mods/85301/
https://www.nexusmods.com/skyrimspecialedition/mods/11052/
https://www.nexusmods.com/skyrim/mods/61559/
*There may be more. For now I had a problem with these pages.

**Comment by iamtiz** [comment]
Hi, I did some checks, and found out you have been blocked by the author of https://www.nexusmods.com/skyrim/mods/61559/, and also by one of the team members of the other mods (not the uploader T4gtr34um3r, in this case, but one of the other team members). You should try and ask them to unblock you

**Comment by jas01234** [comment]
Hello iamtiz
Thank you very much for figuring this thing out.

Unfortunately I have completly no idea who they are and why they would block me. I tought this mod was created just by T4gtr34um3r. Can I ask you who are the other people? I would like to contact them, but there is no way for me to check who are the other team members of Blended Roads - As I can't use the official page of this mod.

**Comment by iamtiz** [comment]
You can still ask T4gtr34um3r who their team members are :)
