### ISSUE TITLE
Button Manage does not work properly

### ISSUE THREAD

**Issue by Patriot99** [Nexus-Mods/web-issues#708]
Hi,
When I go to the page of my translation and I want to edit the translation by clicking the button, Manage shows all the options, but when I want to choose one option from the list, the whole list of options disappears and I have to click several times for the Manage button to show its options and then click the PPM on this button the list of options has not disappeared and then select all options while holding the LPM and when I find the options, I can click to open the edition of your translation. This is inconvenient and should be displayed normally, not disappear when you want to select options from the list.
Video:
https://vimeo.com/274652633
Password:
 test1

**Comment by iamtiz** [comment]
It's an issue with the buttons and icons not fitting in the page. We'll fix it ASAP

**Comment by iamtiz** [comment]
It should be working now

**Comment by Patriot99** [comment]
Yes, it works now
Subject to closing.
