### ISSUE TITLE
Can't download NMM version

### ISSUE THREAD

**Issue by Chicarron** [Nexus-Mods/web-issues#709]
## Bug/error being reported:

When i try to download de current version of NMM it doesn't work (my installed NMM version is 0.63.9); i click the tab but nothing happens (the download doesn't start). I either can use NMM for downloading mods (only manual downloads work), when i try this, NMM ask me for login ("Cannot reach the Nexus login server. Either your firewall is blocking NMM or the login server is down"). I try login in that window but it gives the message "Cannot reach the Nexus login server".
## Steps to reproduce:
1. i do login, 
2. click the "install NMM (0.65.2)" tab on the top of the page, it takes me to the "download/download legacy" page
3. i click "download win 10,...", it takes me to the downloading "Main File" page,
4. i click "Manual Download", it opens the emergent window "Your download should automatically begin within a few seconds", nothing happens,
5. i click "Download" tab, nothing happens.  

## Expected result:

Downloading the current version of NMM
## Actual result:

Download doesn't happen.

**Comment by Pickysaurus** [comment]
Cant replicate this - works fine.
