### ISSUE TITLE
Load more buttons do not load more (minor)

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#71]
![nexys](https://user-images.githubusercontent.com/31670524/30516289-8e3d05a0-9b32-11e7-9123-971e44192978.PNG)
The 'load more' buttons at the bottom of various listing (such as latest/popular 30 days/etc) do not actually load more. They redirect you to what feels like the fallback version of the listing with individual pages.

**Comment by mrmason** [comment]
This is how it's supposed to be - it takes you to a full search, not really a fall back.

Happy to hear any suggestions on what to change the text to if anyone can come up with something better.
