### ISSUE TITLE
Removing updates entries closes the updates list

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#710]
## Bug/error being reported:
Clicking "Remove" for an entry in the updates list closes the list. This started happening after a change to the way the updates list has to be opened that seemed to have gone live today.

## Steps to reproduce:
Click "Updates" at the top of the site, click "Remove" on an entry.

## Expected result:
Keep updates list opened.

## Actual result:
Updates list closes.

**Comment by Asaforg** [comment]
Also, hovering over the Updates tab no longer opens it. It must be clicked now for some reason and clicking "load more" also closes the list.

**Comment by rscottexe** [comment]
We've changed the update button to a click-action as it was too easy to hover over the tab and thus reset your update counter.

The other things mentioned are definitely bugs and will be fixed.

**Comment by Asaforg** [comment]
Thank you for the update! :)

**Comment by iamtiz** [comment]
Fixed
