### ISSUE TITLE
Mod manager denies login

### ISSUE THREAD

**Issue by bruticus99** [Nexus-Mods/web-issues#711]
## Bug/error being reported:
i can log into the website with no problem but the actual manager will not accept my log in. 

## Expected result:

Log in to the manager.

**Comment by Freso** [comment]
What version of NMM are you using? Did you verify that the username/password is correct?

**Comment by bruticus99** [comment]
It must have got patched cause it works fine now with the newest version.  I tried to update a few times before but it would only allow me to dl the older version.  Think it was 65.2???? But not sure.  Thank you.
