### ISSUE TITLE
Unable to upload superceding file; 'Preview File Contents' does not work right

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#712]
## Bug/error being reported:
After rebuilding all meshes to fix some reported clipping, I uploaded version 2.0 of my Minidresses & Lingerie-SSE-7771-2.0 mod Main File a few days ago. Almost immediately, a user reported an issue with it ("missing textures") so after checking my local copy of the file, which was perfect and worked fine in my game, I shrugged and figured "corrupted upload" and re-uploaded it, still as version 2.0. I ticked "this is the latest version of this file" and also "remove old file when upload is complete" or words to that effect. Then another user reported that one of the textures subfolders was out of place, causing the textures not to be found. So I rechecked my local copy of the uploaded archive, and did NOT find the out of place folder. I then used the Nexus "preview file contents" function to view the uploaded archive, and the folder was correct in that view as well. So I advised my users to please re-download the file and closed the issue. This morning, I got a PM from a user who stated that the Nexus "Preview File Contents" function did in fact show the folder in the correct position, but when he downloaded the file it was out of place! How is this even possible? In a last-ditch effort to overcome what seems to be Nexus's buggy behavior, I deleted my Main file and then re-re-re-re-uploaded it as Version 2.0a. It is unknown whether or not this will be sufficient to overcome Nexus's refusal to correctly serve the latest uploaded file to users.
## Steps to reproduce:
Upload a file. Now change the file in some small way (just so that you can identify which file is which) and re-upload it under the same version number, ticking "latest version" and "remove old" as detailed above.. Now view it in the "Preview File Contents" function and verify that it is, indeed, the latest, changed file. Now download it and confirm that the downloaded file is NOT the latest file but is the first, corrupted, file instead and does not match the "Preview File Contents" view OR the superceding file you uploaded.

This bug really needs to be fixed, since uploading and hosting files is the core function of the Nexus. Thx.

**Comment by iamtiz** [comment]
Same issue as #601
