### ISSUE TITLE
Recaptcha Vs VPN

### ISSUE THREAD

**Issue by blonks** [Nexus-Mods/web-issues#714]
## Bug/error being reported:
 Logging into Nexus site no longer works with a VPN

## Steps to reproduce:
Attempt to Login

## Expected result:
A website login compliant with GDPR privacy requirements.

## Actual result:
Privacy invasion/Data theft by Google via Recaptcha tracking protocols

**Comment by iamtiz** [comment]
Hi, we also have a different captcha system that is used when Google is blocked. Is it not working for you?

**Comment by blonks** [comment]
"Logging into Nexus site no longer works with a VPN"=Original issue."Logging into Nexus site no longer works with a VPN"=Current issue Resolution:Refer to standard web use policy: "do not interact with user unfriendly/corporate spiv operated websites". =Resolved.    30.07.2018, 13:51, "Tiz" <notifications@github.com>:Hi, we also have a different captcha system that is used when Google is blocked. Is it not working for you?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by iamtiz** [comment]
We have 2 different captcha system: Google ReCaptcha is the default, and failing that, a non-Google locally generated Captcha is shown. If you are blocking Google, the second one should be showing. Is it?

**Comment by blonks** [comment]
The Google captcha is always locked in an non functioning 'opening page'. No cars/shop fronts. No alternative captcha. Same thing other web sites with the Google captcha. Thats not the point. Signing in to a web site is just that: SIGNING IN. Not doing ridiculous jump through the hoops because the 'security' ideas on a site are so default, a piece of shit programme from data thieves is used because its cheap and easy. Lowest Common Denominator stuff.Please do not continue this. I'm not interested in the Nexus site anymore. Its gone corporate, end of story. The situation is called a floruit. Look it up. Its when the smart money leaves.13.08.2018, 09:57, "Tiz" <notifications@github.com>:We have 2 different captcha system: Google ReCaptcha is the default, and failing that, a non-Google locally generated Captcha is shown. If you are blocking Google, the second one should be showing. Is it?

**Comment by blonks** [comment]
I identified the problem with the Nexus last night from the sequence used to attempt to buy rail tickets on another site used regularly until 6 months ago, when for unknown reasons then (introduction  of Google captcha) it stopped working permanently at 'sign in' stage.Sequence1. Choose tickets2. press 'Buy'3. Google captcha4. Google captcha success5. login in to Account6. Account login failure 'incorrect acc name/password not recognised'7. Try website's  'Password forgotten' process, new random password generated by the website sent to my email8. Go to email, find message from website (ie correct web address known to site) copy new random password, return to website.9. press' Buy' a second time10. Google captcha11. Google captcha success12. login in to Account13. Account login failure 'incorrect acc name/password not recognised'The site has demonstrated it has the correct account details stored, by sending the new password to the right email address. The password is also correct because the site sent it. What's the elephant in the room?The VPN, not accepting cookies? No.  Both were present in my security profile 6 months ago when I was still able to buy tickets from this website.What changed 6 months ago on this and the Nexus website?Google CaptchaWhy it is difficult to replicate this issue presumably, is because I virtually NEVER do not use a VPN. Hence when Google Captcha contacts Google to 'authenticate'  the IP address, and neither the VPN nor the actual IP address are 'authenticatable'; Google has no info on me- I run a best possible anonymous internet profile. In the above case, Google presumably sends data to the website to recommend refusing 'login' and the site automatically accedes.The problem with the Nexus site use of Google captcha is probably related, except the login/captcha sequence is reversed, but the result is still the same.Solution: 'professional' website designers/security should not be paying Google to buy a POS so called 'security' app which is in fact is in fact nothing more than a covert data mining process, which the dumb ass website owners PAY Google to perform.14.08.2018, 13:16, "Tiz" <notifications@github.com>:Closed #714.
