### ISSUE TITLE
Code tags not working properly

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#715]
## Bug/error being reported:
The purpose of [ code ] (without the spaces) tags is supposed to be to display user input exactly as entered. This includes tabs and other forms of indentation. However, Nexus Mod Posts pages [ code ] tags are not doing that- all they are doing is changing the font face to Times New Roman while ignoring Tabs and other forms of indentation (e.g. multiple leading spaces).

It is possible that the full-function editor for the actual Forum Thread would display entered code correctly including any indentations, however, using that editor results in chopped-up, disconnected issue tracking- all the posts on an issue are disconnected and distant from each other, and those antecedents that are shown are under [ Spoiler ] tags- all of which impairs comprehension and cohesion while at the same time requiring much more work on the part of the author and any readers in order to figure out what is going on. That's why most of us do not use the Nexus Forum Threads for mods.

Please see the attached screenshots, which graphically illustrate the problem better than I could possibly describe it..
The Code as entered:
![nexuscodeasentered](https://user-images.githubusercontent.com/33111596/41508510-93ea9eda-720b-11e8-90eb-b8daa2f9d17e.png)

The Code as displayed after pressing Submit:
![nexuscodeasdisplayed](https://user-images.githubusercontent.com/33111596/41508513-ac05a5aa-720b-11e8-8604-3172444df2f4.png)

## Steps to reproduce:
1. Copy some xml code from an actual xml file.
2. Paste it into a Nexus Mods "Posts" page Reply (or New Comment) between [ code ] [ /code ] tags
3. Confirm that the indentations, which convey hierarchical information in xml files, are intact
4. Press Submit
5. Notice that the indentations have vanished despite the [ code ] tags, rendering the posted information impossible for a user to simply copy and paste into her xml file and rendering the displayed information much harder to understand since it no longer contains its hierarchical indicators, i.e. the indentations..

**Comment by iamtiz** [comment]
assigned #159847960

**Comment by iamtiz** [comment]
Fixed
