### ISSUE TITLE
Files in "Preview file contents" located in the wrong directory

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#716]
## Bug/error being reported:
The source script files (in the "source\scripts" folder) of the following mod show in the wrong place:
https://www.nexusmods.com/skyrimspecialedition/mods/18045?tab=files

Possibly has something to do with the fact that there are two folders called "scripts".
source\scripts
and
scripts

## Steps to reproduce:
Click "Preview file contents".

## Expected result:
The *.psc files should appear under source\scripts, not in the root.

## Actual result:
The *.psc files appear in the root directory.

**Comment by scjohnson1981** [comment]
Can confirm this issue.  Rayne by LogicZinc has her meshes/textures showing in the root directory when in fact they're in the Data meshes/textures directories like they should.  Please fix your broken website Nexus.

**Comment by iamtiz** [comment]
assigned #159399484

**Comment by iamtiz** [comment]
Fixed
