### ISSUE TITLE
Accordions in Description tab stops working after going to Images tab

### ISSUE THREAD

**Issue by dguan4** [Nexus-Mods/web-issues#717]
## Bug/error being reported:
After viewing images tab, the accordions in the description tab doesn't work anymore.

## Steps to reproduce:
1. Go to any mod page (i.e. https://www.nexusmods.com/skyrimspecialedition/mods/2347?tab=description)
2. Verify accordions work properly (Requirements, Changelog, etc)
3. Switch to images tab
4. Go back to description tab
5. Accordions don't toggle anymore.

## Expected result:
Accordions to work after looking at images

## Actual result:
Accordions stop working after looking at images

# Notes 
Every other tab seems to works fine with these accordions besides the images tab

**Comment by iamtiz** [comment]
assigned #159399508

**Comment by iamtiz** [comment]
Fixed
