### ISSUE TITLE
Infinite upload loop

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#718]
## Bug/error being reported:
Mod uploads getting stuck in an infinite uploading loop.

## Expected result:
File is available for download.

## Actual result:
"The file is currently being uploaded to our file servers and it will be ready to be downloaded soon."  This after nearly 2 hours of waiting/going to other sites to check e-mail/catch up on current events/etc.  The Nexus uploader/virus scan is broken & has been for quite some time.  It's slower than molasses & really needs to be fixed/brought up to modern standards.

**Comment by iamtiz** [comment]
Hi, do you still have this issue?
