### ISSUE TITLE
Old download history disappeared after downloading NMM

### ISSUE THREAD

**Issue by thingaloo** [Nexus-Mods/web-issues#719]
## Bug/error being reported:

I just logged in after several years of inactivity, and found my download history still intact. Upon downloading the Nexus Mod Manager, however, the NMM itself became the only entry in the download history.

## Steps to reproduce:

1. Download files on Nexusmods before the release of NMM
2. Download NMM

## Expected result:

NMM should become the newest entry in the list on the Download History page.

## Actual result:

NMM becomes the ONLY entry on that list.

**Comment by thingaloo** [comment]
I should add that my tracking list is also now empty, although I didn't check that one before installing NMM

**Comment by iamtiz** [comment]
Hi, is this the url you are using to display your download history? https://www.nexusmods.com/users/myaccount?tab=download+history
