### ISSUE TITLE
easier message monitoring (not a bug)

### ISSUE THREAD

**Issue by ReaperTai** [Nexus-Mods/web-issues#72]
in the current version there is a last message posted and a quick link directly to the messages from the manage my/allowed files page (https://imgur.com/a/dXmEC) that is missing from the new site.  this means that if monitoring multiple mods you have to actually open each mod...goto messages...look if something new...goto next mod and rinse and repeat for each mod you monitor.  I monitor like 15 mods everyday while at work and the old system is much better for this.  can just open the page for my/allowed mods and see immediately if new messages then hop directly to the messages.  refresh the screen every so often to see if any new by time.

on a side note there is no pending images notification as well to know if anybody added pics to be accepted/deleted.

Edit: looking more I noticed the little grey messages link at bottom but still no way to know if any new ones.

**Comment by iamtiz** [comment]
Hi, not sure where you can see if there are new comments on your file in the current website. Excluding the notifications, of course.

**Comment by iamtiz** [comment]
Assigned the other issue (Pending images number) to task #151167470

**Comment by iamtiz** [comment]
Added the number of pending media items to the 'My account' > 'Files' tab

**Comment by ReaperTai** [comment]
I showed where it is in the imgur link in main message.  Here is a larger pic showing multiples. https://imgur.com/a/tjxiF

**Comment by iamtiz** [comment]
Assigned PT #151243851

**Comment by verenion** [comment]
Fix has been pushed.
