### ISSUE TITLE
Timeout!  Cannot reach the Nexus login server.

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#721]
## Bug/error being reported:
Having to constantly enter my login credentials in NMM.
## Expected result:
Log into NMM.

## Actual result:
The above error message saying the login attempt timed out.

**Comment by Pickysaurus** [comment]
Not a bug with the website - update your NMM https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases

**Comment by scjohnson1981** [comment]
Thanks for the info/link.  Had no idea my NMM was outdated.
