### ISSUE TITLE
New search does not start from page 1 and delete the filter does not remove it.

### ISSUE THREAD

**Issue by Lywzc** [Nexus-Mods/web-issues#723]
## Bug/error being reported:

When you start a new search in the search page, it will not start from page 1. Instead it will start from the last search's page.
Also, when I want to change the search parameter, just empty it does not remove the filter, you need to click on the x button on the filter, which is frustrating as it will search two times instead of one.
## Steps to reproduce:

1. Search for arrow in filename then navigate to page 2
2. Empty the filename and search for archery in description

## Expected result:

The arrow in filename filter should be removed and it should start at page 1.
## Actual result:

You end up with arrow in filename and archery in description and it starts at page 2.

**Comment by iamtiz** [comment]
Assigned #159727954

**Comment by patchling** [comment]
Here is the workaround I have been using: Just click the "go to first page" option in the spot where you tell it which page number to show.

I have been using this on so many sites I am unable to remember if I have needed to use it on nexusmods or not.

**Comment by Lywzc** [comment]
> Here is the workaround I have been using: Just click the "go to first page" option in the spot where you tell it which page number to show.
> 
> I have been using this on so many sites I am unable to remember if I have needed to use it on nexusmods or not.

But it is extremely strange that a new search would start at page 2 and clearing a search parameter does not delete it. No sane person would want this behaviour yet Nexusmods do. And after almost 2 years this bug still persist.

**Comment by Pickysaurus** [comment]
This will be addressed when we rework search.
