### ISSUE TITLE
Cannot reach the nexus login server

### ISSUE THREAD

**Issue by Fogaboga** [Nexus-Mods/web-issues#724]
## Bug/error being reported:

Cannot reach the nexus login server. I dont have any my firewall set up to have any interaction with NMM at all. I've uninstalled and reinstalled.
## Steps to reproduce:

1. open the app
2. try to login
3. fail to login
## Expected result:

I can use the app without any problems.
## Actual result:

I cant use the app at all.

**Comment by gustavo14994** [comment]
I have the same problem
![screenshot_50](https://user-images.githubusercontent.com/40768308/42172496-223baad2-7dea-11e8-879d-a0e1c571c539.png)

**Comment by Vildrak** [comment]
I also have this problem. Have you guys tried to report to Nexus ?

**Comment by TheDanTheDank** [comment]
I have the same issue. Manual download servers are also down, so I cannot use Nexus at all.

**Comment by Pickysaurus** [comment]
This is not the tracker for Nexus Mod Manager - you all need to update to the latest version. 
Link: https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases
