### ISSUE TITLE
Slow download speeds

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#725]
## Bug/error being reported:
Download speeds (Canada - North America Premium Server) are slow.  I have a just-upgraded 400Mb/sec cable internet connection & should therefore be getting way more than 2 MB/sec download speeds.

## Expected result:
Download speeds of 10 MB/sec+.

## Actual result:
Download speeds of 2 MB/sec if I'm lucky.

**Comment by Pickysaurus** [comment]
This should now be resolved.
