### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#727]
## Bug/error being reported:
Lots of broken images across Skyrim SE Nexus

## Expected result:
Various images displayed on Skyrim SE Nexus

## Actual result:
Broken images that either don't load at all or are very slow to load.

**Comment by Freso** [comment]
I went to the [front page](https://www.nexusmods.com/skyrimspecialedition) and all images loaded fine for me. Maybe be more specific with some examples of where you are seeing this?

**Comment by scjohnson1981** [comment]
The issue happens at random times.  It's been better in recent days but still happens from time to time.

**Comment by mrmason** [comment]
When you find an image that's broken please can you give us the URL of the image missing, and the URL of the page you saw it missing from ?

**Comment by scjohnson1981** [comment]
The issue has been happening across the entire Nexus network in recent weeks.  Kind of hard for me to provide URLs to broken images when the entire network has been on the fritz the past several weeks.  The North America Premium Server in particular has been sluggish/slow over the past several months despite my numerous reports regarding the issues with said server.  Again, the issue with broken images has been happening across the entire Nexus network & happens at random times.

**Comment by mrmason** [comment]
Right click on the image and press COPY URL. Paste it here, so we can investigate. Without that it makes us very hard to help.

**Comment by scjohnson1981** [comment]
https://staticdelivery.nexusmods.com/mods/1704/images/9651/9651-1525209203-928083713.jpeg

That's an image from Tera Armors Collection SE.  That mod page in particular is notorious for slow image load times/broken images half the time I visit that page to download updates/view images for the purpose of figuring out which armor is which in my Data folder.

**Comment by scjohnson1981** [comment]
If it's of any consolation, I use Google Chrome web browser.  I've refreshed my browser I don't know how many times but the issues with images persist.

**Comment by scjohnson1981** [comment]
Yes, I keep my browser up to date regularly too.

**Comment by mrmason** [comment]
Can you open up 'Developer Tools' and open the network tab.

When you see a broken images, can you take a look at what's going on in the network tab, and see what response you're getting on the broken images ?

**Comment by scjohnson1981** [comment]
How do I do this?  I'm seeing broken images all across my Tracking Centre:

https://user-images.githubusercontent.com/34541753/43355614-e1d459d6-9224-11e8-844d-d58db162ab70.png

This taken via Print Screen just now.

**Comment by iamtiz** [comment]
@scjohnson1981 To open the developer tools in Chrome you can type Ctrl + Shift + i
If you then reload a page on the Nexus website, you'll see the activity on the Network tab of the DevTools
