### ISSUE TITLE
Can't completely see mod names in NMM

### ISSUE THREAD

**Issue by Angelioh** [Nexus-Mods/web-issues#729]
## Bug/error being reported:
Can only see 1-3 letters of the mod and can only see the mod names by mouse overing

## Steps to reproduce:
Not quite sure, all I remember is re-installing NMM after a while

**Comment by Pickysaurus** [comment]
This bug tracker is not for NMM. It is for the Nexus Mods website.
Have you tried expanding the name fields like a spreadsheet column?
