### ISSUE TITLE
Clickable links in posts view (enhancement)

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#73]
The old site doesn't do this either, buut... 

It would be really nice if links pasted directly into a mod comment would be clickable. On the forum view they are detected and clickable, but on the mod page they just appear as normal text. 

I know that one can mark them as links from the forum view to make them clickable on both sides, but this editing capability is not available on the posts side. I prefer not to write or edit comments from the forums side for multiple reasons, including:

- it doesn't maintain the parent/child relationship in the posts side formatting

- it tends to add formatting that does _not_ render correctly on forums side (such as quotes)

- it appears to bypass author blocking 

I also know that if I knew the correct bbcode tags I could make them clickable from either side, but I don't know bbcode. That perhaps relates to sevencardz's request to allow markdown editing in comments (which he did not post here).

**Comment by Pickysaurus** [comment]
We're looking at adding a WYSIWYG editor to the comment section that should resolve this issue.
