### ISSUE TITLE
Captcha error I can't login

### ISSUE THREAD

**Issue by jjmerago1** [Nexus-Mods/web-issues#731]
## Bug/error being reported:
I enter my login info and it fails due to catcha error

## Steps to reproduce:
Tried turning off all popblockers and adblockers

## Expected result:
The login works

## Actual result:
Still says captcha error but there is no question or box to check
![nexus mods and community](https://user-images.githubusercontent.com/40816418/42257260-a69bff36-7f0a-11e8-8e61-98c947aec1d7.png)

**Comment by jmrboosties** [comment]
Same

**Comment by MiloszXD007** [comment]
Same

**Comment by chaosgoettinger** [comment]
@nexus-mods team , today will the captcha system change from recaptcha1 to recaptcha 2

wording : "
Troubleshooting
Important: Version 1.0 of the reCAPTCHA API is no longer supported, please upgrade to Version 2.0. "

source : https://developers.google.com/recaptcha/old/docs/troubleshooting

**Comment by kamikaziKAS** [comment]
I see this one is almost a month old but is there a fix? I'm getting this problem too.

**Comment by iamtiz** [comment]
Which captcha method is being displayed to you? The Google ReCaptcha, or the alternative one?
