### ISSUE TITLE
Can't hide a mod.

### ISSUE THREAD

**Issue by opusGlass** [Nexus-Mods/web-issues#733]
## Bug/error being reported:
Can't hide a mod because the dialog closes itself when I click.

## Steps to reproduce:
1) Manage -> Set mod to hidden
2) Click anywhere in the dialog.

## Expected result:
I expected to  be able to type a reason and then click "Hide Mod".
Failing that, I expected to be able to hide the mod without providing a reason.
Failing that, I expected to be able to hide the mod with or without a reason on the Managy My Mods page.
None is possible.

## Actual result:
The dialog completely disappears, the mod is still not hidden.

## The mod I'm trying to hide (for an update):
https://www.nexusmods.com/skyrim/mods/72706

**Comment by mrmason** [comment]
This seems to be related to #734

**Comment by mbestavros** [comment]
I also commented over on #734, but you may want to try using a different browser; it looks like this issue is a Firefox-specific CAPTCHA issue.

**Comment by opusGlass** [comment]
I'm on Google Chrome, but I will try Firefox.

**Comment by opusGlass** [comment]
Works in Firefox for me!

**Comment by mbestavros** [comment]
@opusGlass It looks like @mrmason might have just fixed it; you should try in Google Chrome again.

**Comment by opusGlass** [comment]
Ah yep, it is fixed in Chrome also. Thanks!

**Comment by mrmason** [comment]
No problem :)
