### ISSUE TITLE
Can't login to Nexusmods website

### ISSUE THREAD

**Issue by wasd12** [Nexus-Mods/web-issues#734]
## Bug/error being reported:
Problem with login

## Steps to reproduce:
1. Click on login
2. Click on Username container

## Expected result:
Being able to enter Username and password

## Actual result:
Can't type anything at all

![nexus](https://user-images.githubusercontent.com/40836413/42289799-864de638-7f8f-11e8-898f-c3e20274ecb1.gif)

**Comment by RickHodgett** [comment]
Console warning:
Form submission canceled because the form is not connected

**Comment by Dreifels** [comment]
same issue here. When click on captcha it closes and I'm back on mod's page. No way top log in and/or download. (Looks like a captcha issue, as this also pops up when close browser tab and visit page new)

**Comment by mbestavros** [comment]
Looks like this is a Firefox-specific issue; I was able to reproduce this on Firefox 61, but was able to log in without a hitch on Chrome 67 and Edge.

**Comment by opusGlass** [comment]
For the possibly related issue #733, where a the "Hide Mod" dialog closes when clicked, I am experiencing it in Google Chrome.

**Comment by mrmason** [comment]
Can you please try again now.

**Comment by mbestavros** [comment]
@mrmason Awesome, works like a charm! Was able to log in using Firefox again.

**Comment by mrmason** [comment]
Great - thanks for the clear bug reports guys - helped us fix it quickly!
