### ISSUE TITLE
Blocked users can still reply on the forum thread and their posts will appear on the mod page

### ISSUE THREAD

**Issue by dAb74** [Nexus-Mods/web-issues#735]
## Bug/error being reported:
Tested with another user who temporary blocked me for the sake of testing: if you block a user on your mod page, that user will still be able to reply via the forum thread if he finds it, and his reply will appear on the mod page. There's no way to block users on the forum, we can only add them to the ignore list. So  we can block them from accessing the files but we can't stop them from trashing the mod page.

## Steps to reproduce:
Block a test user from accessing a mod page and have him reply to the forum thread.

**Comment by Arthmoor** [comment]
Bumping this in hopes that someone is still paying attention. This isn't an enhancement issue. Users we are blocking from our file sections should not be capable of circumventing this by jumping to the forum side instead. There are users who are actively abusing this bug to do exactly that.

**Comment by Pickysaurus** [comment]
We're currently looking into a possible fix to this, but it may prevent any users from replying via the forum.

**Comment by Arthmoor** [comment]
This is an incredibly late reply, I know, but since this is still open I think it should be made clear that preventing users from replying to a topic they were blocked from by going to the forum is exactly what we're trying to get fixed here.

**Comment by Pickysaurus** [comment]
I have now set it so nobody can reply to mod page comment threads via the forum. This should fix this issue. If the change causes any problems I will revert it back though.
