### ISSUE TITLE
Posts tab Broken

### ISSUE THREAD

**Issue by BiRaitBec** [Nexus-Mods/web-issues#738]
Glitch on the posts tab, texts are mixed one with an other and there are many visual bugs in there -->

I think it's mainly due to spoiler tags i guess, had the same issue a year ago and was fixed by a staff member

http://prntscr.com/k4err4

On nexus i'm BiRaitBec

**Comment by BiRaitBec** [comment]
and here's the mod page involved with the issue: https://www.nexusmods.com/fallout4/mods/23556/?

**Comment by iamtiz** [comment]
Hi, could you point us to the comment page where the issue is? I've checked the first 10 pages and wasn't able to find it

**Comment by Pickysaurus** [comment]
This is an issue where a [Spoiler] tag was not closed correctly and overflowed into a post below it.
