### ISSUE TITLE
Videos Tab Defaults

### ISSUE THREAD

**Issue by DuIslingr** [Nexus-Mods/web-issues#74]
When clicking the videos tab when it appears on a file that doesn't have any vids posted by the mod author, but there are vids from users, it doesn't default to the user vids.

In these scenarios it should default to the User videos otherwise at first glance it seems like there are no videos at all despite the dropdown being there to show Mod Author or user vids. 

![screenshot from 2017-09-17 16-59-09](https://user-images.githubusercontent.com/19367043/30524870-ab09dcb6-9bc9-11e7-97c6-950d3766abdd.png)

**Comment by iamtiz** [comment]
assigned #155431571

**Comment by iamtiz** [comment]
done
