### ISSUE TITLE
Mobile site displays one character of author name

### ISSUE THREAD

**Issue by ViolentQuiche** [Nexus-Mods/web-issues#740]
## Bug/error being reported:
When browsing the mobile site, the mod homepage for a game only displays the first character of the author name even though there's definitely room to display more.

Screenshot: [https://imgur.com/a/24cXzOm](url)
Browser: Chrome 67.0.3396.87
OS: Android 7.0.0
URL: https://www.nexusmods.com/stardewvalley/mods/

**Comment by iamtiz** [comment]
Assigned #159400652

**Comment by iamtiz** [comment]
Fixed
