### ISSUE TITLE
Show images without overlays (feat. req.)

### ISSUE THREAD

**Issue by Freso** [Nexus-Mods/web-issues#741]
## Bug/error being reported:
When browsing through a mod's images, there is currently no option (that I've found) for showing the images without the overlay.

## Steps to reproduce:

If you go to https://www.nexusmods.com/fallout4/mods/3106/?tab=images and click the first image, you will get a nice screen with all the images in bottom, the image on top, and then "1/13" and navigation buttons etc. on an overlayed row on top of the image and "black - lens" (the image/name description) overlayed at the bottom of the image.

## Expected result:

A way to either make the image smaller so it isn't obstructed by the overlay, or a way to hide the overlay. (Ideally, both!)

## Actual result:

No option to do either of these things. :(

**Comment by Pickysaurus** [comment]
You can hide the images row by clicking on the grid icon in the bottom left. That's the closest you can get to what you are asking for.
