### ISSUE TITLE
[Feature Request] Markdown Syntax

### ISSUE THREAD

**Issue by nicolas-giuristante** [Nexus-Mods/web-issues#744]
Was there any plan to integrate some sort of markdown syntax on the Nexus website at some point? I'm sure both the comments section and mod descriptions would benefit from such implementation.

Although BBCode is present, I find it more elegant and practical to write down stuff using markdown syntax. I'm sure I'm not the only one thinking that. It would also be compatible with the `readme.md` from GitHub. I'm sure mod authors would appreciate this feature.

Also, maybe filtering or restricting some tags to mod authors would be a great idea... I can already see plenty of comments such as these appearing everywhere:

### I NEED HELP WITH MY CTD IN SKYRIM

Anyway, food for thoughts, if you feel like adding yet another feature to the website. Cheers!

**Comment by tktk11** [comment]
Writing readme and Description is boring everytime. If load a md file included in a mod file, it can be saved the trouble of updating.

**Comment by Muriel-Salvan** [comment]
Waiting to have this feature, I wrote a small tool to convert Markdown to the Nexus' flavor of BBCode.
You can find it here: https://github.com/Muriel-Salvan/md_to_bbcode
I use it for my mods publication, and I hope it can be useful to others, waiting for this ticket to be implemented.

**Comment by jfmherokiller** [comment]
thanks for this tool I might see if i can convert part of it to js. If i can we might be able to create some kind of magical userscript popup

**Comment by jfmherokiller** [comment]
this might be a somewhat good candidate atm  https://www.npmjs.com/package/markdown-to-bbcode

**Comment by Pickysaurus** [comment]
We're exploring Markdown as an option. It's currently use by Collections if you'd like to preview it.
