### ISSUE TITLE
Mobile site mod's current selection dropdown

### ISSUE THREAD

**Issue by MrTroubleMaker** [Nexus-Mods/web-issues#746]
## Bug/error being reported:
When viewing the site on 
Chrome 67.0.3396.87
Android 8.0.0; SM-G955U Build/R16NW 

The "current section" dropdown menu entries do not change the page to their corresponding description. 
This used to work, but has stopped working a few weeks ago. It still works fine on the desktop site.

### Example:
1. Go to a page like https://www.nexusmods.com/fallout4/mods/30028
2. Tap the current selection dropdown menu
3. Tap on any of the links ( Files, Images, Video, Post, Bugs, Logs or Stats)

## Expected result:
Example - Tap on "Images" should change the page to https://www.nexusmods.com/fallout4/mods/30028?tab=images

## Actual result:
Example -  Tap on "Images" does nothing

![clipboard01](https://user-images.githubusercontent.com/35054968/42728980-3477b5fe-8797-11e8-8cc7-a1b9eae530b3.jpg)

Thanks!

**Comment by MrTroubleMaker** [comment]
I forgot to add. This happens when the browser override zoom setting is enabled in accessibility. When that setting is turned off the drop down works as intended. I have been using that setting on for year or so and the site used to work with it, not any longer.
Thanks!

**Comment by iamtiz** [comment]
Hi, I can't seem to replicate this issue (with Chrome 68 on Android 6). Is this still happening for you?

**Comment by MrTroubleMaker** [comment]
Yes, but here is some more information I found out after some testing.

Chrome 68.0.3440.91
Android 8.0.0

When viewing the site from a link like
https://www.nexusmods.com/fallout4/mods/30028
with Chrome - Settings - Accessibility - Force enable zoom - checked. The "current selection" drop down links do not work. But work correctly with the "Force enable zoom - UNchecked"

If the link is changed to 
https://www.nexusmods.com/fallout4/mods/30028?tab=description
The "current selection" drop down links work for either the "Force enable zoom" - checked or Unchecked.

I think it has something to do with the "top link" having/needing  a ?tab=  for the other links to work with that accessibility setting.

I hope this helps, let me know if I can help out more. Thanks!

**Comment by Pickysaurus** [comment]
I have replicated this issue using the details you provided, thank you. 

I'm not sure off hand what would cause this, but you might want to view the site in "Desktop Mode" if you need to force zooming? At least until we're able to pin down the problem.

**Comment by Pickysaurus** [comment]
Fixed in #1306
