### ISSUE TITLE
CDN Server Timing Out

### ISSUE THREAD

**Issue by pushabi** [Nexus-Mods/web-issues#748]
## Bug/error being reported:
When trying to download mods for Dragon Age Origins the servers time out before the file downloads so I think the server is down. I've provided an example mod but it is happening on many, possibly all.

## Steps to reproduce:
1. Go to this URL: https://www.nexusmods.com/dragonage/mods/4689?tab=files

2. Try to manually download the file

## Expected result:
The file should download
## Actual result:
The server sends back an error.

**Comment by TheDanTheDank** [comment]
Trying to download Fallout 4 mods, both NMM login servers and manual download servers appear to be down.

**Comment by Drarck** [comment]
Yeah, same thing happens to me. i can't download nothing, not even the nexus manager.
i just wanted to install SDV mods, damn it.

**Comment by iceghost22** [comment]
Same issue here. Can't download any file at all :c

**Comment by Drarck** [comment]
does anyone know a way to download mods without the page for the time being?

**Comment by emmikeda** [comment]
Doesn't look like there's a solution yet...searching myself.

**Comment by mrmason** [comment]
This should be working now, I'll be taking steps today to try and stop this happening again.
