### ISSUE TITLE
Nexus uploader hangs

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#753]
## Bug/error being reported:
The Nexus uploader hangs when uploading files to the Nexus (Skyrim SE Nexus)

## Expected result:
File gets uploaded to Skyrim SE Nexus

## Actual result:
Upload hangs, forcing me to cancel the upload.  Totally RIDICULOUS.  Time for Nexus to find a new upload/virus scanning provider.  This has been a major issue ever since changes to the uploader/virus scanner were made a few years back.  This issue is rampant & all reports regarding said issue have been ignored.  Please fix this mess.

**Comment by iamtiz** [comment]
Do you mean the uploader gets stuck and never reaches 100%, or that after the file was uploaded it was unavailable for download because of the virus scan?
