### ISSUE TITLE
Broken ReCaptcha When Signing In.

### ISSUE THREAD

**Issue by Extintuate** [Nexus-Mods/web-issues#756]
1. Whenever I go to sign in to the nexus mod manager website, it lets me enter my username and password, but it won't let me do the ReCaptcha.

2. Startup NMM up being unlogged in, attempt to log in, get the bug.

3.  The Recaptcha will not allow you to use it when signing in.
![unknown](https://user-images.githubusercontent.com/41446944/42959463-804b6c90-8b4e-11e8-8a77-f17d7f3e1206.png)

4. The Recaptcha did not let me use it while signing in.

**Comment by SkyNinja** [comment]
I'm getting a totally different captch system which doesn't seem to function. I have a box with letters in them, a refresh button beside it, and an audio button below that. Usually, the audio and the text tell me two totally different things, and no matter what, they almost always fail.

**Comment by Baldrfe** [comment]
Same problem as SkyNinja. Captcha is always a PITA, but this one is particularly useless. Listen, I can sign in to banks, credit cards and many other sensitive sites without captcha. You think there might be a reason none of them use it?

**Comment by Pickysaurus** [comment]
We've made some changes which should've resolved this now.
