### ISSUE TITLE
Edit own reply to a comment on own mod's page, the page code gets corrupt

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#758]
## Bug/error being reported:
Edit own reply to a comment on own mod's page, the page code gets corrupt
## Steps to reproduce:
see https://www.nexusmods.com/skyrimspecialedition/mods/18553?tab=posts
reply 18 July 2018, 11:29PM
I had corrected my own response text and now is is buggy
### Example:
1. Step 
reply to a comment which has a spoiler
2. Step 2
save and exit
3. Step 3
then login again and change your text, save
## Expected result:
 same optic like t other
## Actual result:
corrupt code

**Comment by Pickysaurus** [comment]
https://imgur.com/ixJ3r7v
Taken a screenshot for completeness
