### ISSUE TITLE
Images in File Description (Unimportant)

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#76]
Mods that put an image in the file description on the files tab have bad formatting, the image pushes the download and other buttons to the side instead of lower. 

https://i.imgur.com/vV2nDf4.png

(mod page link: https://rd.nexusmods.com/skyrim/mods/76086/?tab=files)

**Comment by verenion** [comment]
Assigned PT#151166161

**Comment by verenion** [comment]
Fix has been pushed
