### ISSUE TITLE
Cannot upload images - keeps throwing error saying image is too small (1 byte) when images are 600 KB+ in size

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#760]
## Bug/error being reported:
Error stating images cannot be uploaded - 1 byte in size when the size shows as 600 KB+ on my SSD

## Expected result:
Upload of an image for a Skyrim SE port

## Actual result:
Error saying the image is too small (1 byte when the images are over 600 KB in size)

**Comment by scjohnson1981** [comment]
Yes.  I'm still having this issue & have been having this issue the past several weeks.  I've no idea why Nexus is saying the images are 1 KB when they show up as 600 KB+ on my machine.

**Comment by scjohnson1981** [comment]
Ran into the issue again when attempting to upload an image for Tales of Girls SE, a Skyrim SE port of an Oldrim mod I obtained permission to port over from abchune, the original author.  The first image I upload works fine.  Any subsequent images I try to upload result in an error message saying the image is too small (1 KB) when it clearly shows up as 1,450 KB (Rina.jpg).  Please fix this.  This has been an ongoing issue for weeks on end.  Very annoying to say the least.

**Comment by Pickysaurus** [comment]
So it only happens when using the bulk uploader to add more than one image at a time?

**Comment by scjohnson1981** [comment]
That is correct.  The first image uploads just fine.  Any additional images prompt the site to throw the error message in the title of my report here on Github.  Have no idea why since all I'm doing is saving the image from the Oldrim Nexus page in .jpeg format.

**Comment by scjohnson1981** [comment]
The issue I've reported here only seems to affect .jpg images.  Images saved in .png format upload just fine.  Please fix this mess.  I cannot upload more than a single image at a time within 24 hours thanks to this ridiculous bug.

**Comment by Pickysaurus** [comment]
I have just tried this, with JPG files as you describe - and I had no issues to speak of. Are you able to replicate the issue in another browser? I'm using Microsoft Edge to test and it's fine there.
