### ISSUE TITLE
Attack ad

### ISSUE THREAD

**Issue by Solusphere** [Nexus-Mods/web-issues#761]
I looked around for a Report Ads button, but couldn't find one, so hopefully this gets where it needs to go. When viewing the main page of nexusmods.com, without clicking on anything, I got redirected to a site with a flashing, beeping YOU HAVE A VIRUS message. I closed it immediately and re-enabled my adblocker for your site.

I have the redirect and URL in my history if that helps you track down the culprit. Obviously you probably shouldn't click on these.

https://zogclick.com/click?node=10&time=1532233980&id=12&pid=45&fid=45&sid=14483&rank=0&ad=eyJ0aXRsZSI6IiIsInVybCI6IiJ9

http://safety.microsoft.com.lfaqomr.vc8aq5fpjfzaypn2w4zf32t0nztk49wgda.stream/ow/en/index.php?os=Windows%2010&langcode=en&hul=t.n54ds6o8aw.stream&cep=Q9_wiH0mCSrMOom3NYDDZ0A-JWO_WRR8d9owxxIROsGRVnLWtzqz3eWdtm3bJzZLW1Zp4nRlowWdn3muR3rvdo-Xuoxa2vkcftMSsggKzclwQyAS2mT_jKgbKWayWASpPjJfefRbERqsNCxiEsq8xgBaF81C8YC-O5mQhOwpsGafPWW3bp0IOMZ9MPjxKMWH2GlU7xxDa7ROU7hglXyJeMCDXcUsJiDdxA01PhGWPg6ew2ui3Oucoj7uE4mE69_0JjDg71ukf9TWE7-Otx4VDpT3bPqaVC4D6_2K_2wMkTMC9YyXLjaJ9xT4w3DjsFBy690jW-JCW7HxOStzfqXd5V7PEqmiDY-_m2Q4OsrTl37eVndnEkVXNGWpvlLEcz3Oxz7deGLosxnwiaSBQPeayV_5ZGIO6IZ5Js_HAZWMCWmm_DCy4P79FLEmCnY1xXLpOG-FySi-lHIY28a4IlV7sw&zone=1806387-2919733628-0&cid=15322339862033051809240242024023584&time=1532233992&campaign=112312620&redirection_cost=0.025

**Comment by Pickysaurus** [comment]
Hi there,

Ad reports can be posted in the dedicated feedback forum here: https://forums.nexusmods.com/index.php?/forum/4100-report-bad-ads/
