### ISSUE TITLE
Unique DLs

### ISSUE THREAD

**Issue by SerjRozov** [Nexus-Mods/web-issues#762]
![10](https://user-images.githubusercontent.com/41565509/43170031-0bbfe07e-8fac-11e8-880e-9cced7b38192.jpg)

**Comment by iamtiz** [comment]
Hi, the unique downloads of the whole mod are only increased if a new user download any of the files. 
If they had previously downloaded a file, the counter for the mod won't increase. The one for the specific file will increase, though, if it's the first time they download it.
