### ISSUE TITLE
Very long file names prevent the ability to close the quick-search listing.

### ISSUE THREAD

**Issue by SirSalami** [Nexus-Mods/web-issues#763]
## Bug/error being reported:
Very long file names prevent the ability to close the quick-search listing.

(As reported by Phantoms#1991 on Discord)

## Steps to reproduce:
Search for a mod with a long file name, such as "Extra Smooth Agence de Modele High Poly Mesh Mod with Mountains including Eyecandy Staff of Magnus Refracting Potions Parallax Soulgems and Ftoppka Smelter"
(https://www.nexusmods.com/skyrimspecialedition/mods/1383)

## Expected result:
Truncation of mod name, or otherwise an ability to close the listing.

## Actual result:
Inability to close the quick-search listing.

Screenshot: https://media.discordapp.net/attachments/369484787347488768/471118913594327041/unknown.png?width=963&height=527

**Comment by iamtiz** [comment]
assigned #159400963

**Comment by iamtiz** [comment]
fixed
