### ISSUE TITLE
Import from Youtube button not working

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#764]
## Bug/error being reported:
When using the '[Import from YouTube](https://www.nexusmods.com/videos/import)' button, you are taken to the page to connect to your Google account, but are then forwarded back to the original page instead of being able to complete the import. 

## Steps to reproduce:
1 - Click the 'Import from Youtube' option from the Navbar (in Videos)
2 - Click the Youtube icon.
3 - Authorise access to your account (if applicable)
4 - You will land back at the import page without any option to import videos. 

## Expected result:
Dialogue to import videos from Youtube.

## Actual result:
Forwarded back to starting page.

**Comment by iamtiz** [comment]
Assigned #159400999

**Comment by Pickysaurus** [comment]
This looks to be fixed :)
