### ISSUE TITLE
FNIS SE 7.4.5 XXL Error, mod 3038

### ISSUE THREAD

**Issue by cfoster8** [Nexus-Mods/web-issues#765]
I'm getting the following error when I try to run FNIS through MO2 for skyrim se

ERROR(76): Could not find a part of the path 'F:\Games\steamapps\common\Skyrim\data\tools\GenerateFNIS_for_Users\temporary_logs'.

What stands out to me is that it's trying to write to ….common\skyrim….  The game is skyrim special edition.  That should read common\skyrim special edition....

I tried removing the mod and downloading a new copy.  I tried using an earlier version. Neither worked.  I don't know if this is an MO2 thing or entirely a FNIS issue.  But the animations that should have been
generated weren't created.

**Comment by Pickysaurus** [comment]
This is not a problem with the Nexus Mods website - you should report this to the developers of FNIS or MO2.
