### ISSUE TITLE
Cannot Buy Premium

### ISSUE THREAD

**Issue by Spawnandjesus** [Nexus-Mods/web-issues#768]
## Bug/error being reported:
Clicking anywhere on the site to purchase the premium upgrade reroutes to the forums, and displays:

"Sorry, you don't have permission for that!
You are not allowed to visit this community."

**Comment by Pickysaurus** [comment]
Hi there, please try logging out of the site and back in again.

**Comment by Spawnandjesus** [comment]
Hey Pickysaurus,

I logged out of Nexus main site, and logged back in. I still get a redirect to the forums, the forums alwas say I'm not allowed. That's for every single thing I click. I can't even click logout on the forums, it just refreshes and says I'm not allowed.

**Comment by Pickysaurus** [comment]
If you drop an email explaining it to support@nexusmods.com we'll take a
look into it Monday morning. The only other things that could work are:
- Clear browser cache and cookies
- Change your email address (this triggers a permissions update)
- Try accessing the page via a different network connection (such as a
mobile phone) or VPN

**Comment by rscottexe** [comment]
It's possible the IP address your ISP has given you is in the Nexus Mods ban list. If you include your IP address in the email sent to support it will help. You can find your IP address out by going to https://www.whatismyip.com/
