### ISSUE TITLE
phishing attempt stopped

### ISSUE THREAD

**Issue by arkane149** [Nexus-Mods/web-issues#769]
## Bug/error being reported:
went from  https://www.nexusmods.com/skyrim/mods/72725/?tab=posts to https://forums.nexusmods.com/index.php?showtopic=3689405 got message from google that deceptive site ahead attackers on raptor.com may trick you,ect... 

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Actual result:

I did send a report to google about this, hope it helps.

**Comment by Pickysaurus** [comment]
This is a false positive caused by a user's signature
