### ISSUE TITLE
Page Moderators Tagging Mods

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#770]
_Reported by AlexejheroYTB on Discord_

## Bug/error being reported:
If you tag a mod (the label turns orange), then you get added as a collaborator to the mod, if you try to press the check mark to add the tag, it sais that you've already tagged the mod. there's a simple workaround, to just press the cross, and then the check mark

## Steps to reproduce:
See above

## Expected result:
Mod page staff can approve tags

## Actual result:
Mod page staff are not able to approve tags

**Comment by AlexejheroYTB** [comment]
👍

**Comment by iamtiz** [comment]
Assigned #159523549

**Comment by iamtiz** [comment]
fixed
