### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#772]
## Bug/error being reported:
Getting a "Service Unavailable" error when attempting to navigate to any Nexus webpage

## Steps to reproduce:
1. Click any Nexus bookmark in my browser.

2. "Service Unavailable" error is promptly displayed.

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
Skyrim SE Nexus homepage on my screen.

## Actual result:
"Service Unavailable" error splashed across my screen instead.

**Comment by Pickysaurus** [comment]
Nexus was down for maintenance, it's now fixed.
