### ISSUE TITLE
Download button graphic missing

### ISSUE THREAD

**Issue by Playingskyrim** [Nexus-Mods/web-issues#773]
## Bug/error being reported:
Download button missing graphic

## Steps to reproduce:
Go to any mod page

**Comment by iamtiz** [comment]
Which browser are you using? I can't replicate the issue at the moment.

**Comment by Playingskyrim** [comment]
The latest version of Firefox. I just checked using Edge and the download button graphic is missing too, and a hyperlink is not active on the word 'Download'.

**Comment by Playingskyrim** [comment]
Up at the top of the screenshot, the word "Download". Ah, okay. The word simply points to the two options. I thought it was the word for the graphic button meant to go there (presents word if graphic is unavailable). So, looks like a non-issue, sorry about the trouble.
