### ISSUE TITLE
Art from Kotor 1 in preview picture of Knights of the Old Republic 2

### ISSUE THREAD

**Issue by DorkNow** [Nexus-Mods/web-issues#774]
## Bug/error being reported:
So, when you search for Knights of the Old Republic 2 for some reason there's picture from the first game in preview

## Steps to reproduce:
1. Search for Knights of the Old Republic
2. Find two games with pictures from first KotOR and get confused

**Comment by iamtiz** [comment]
![screenshot_2018-08-10 nexus mods and community](https://user-images.githubusercontent.com/3407947/43945103-0e032ef2-9c79-11e8-881a-8f4a2c8b17cb.png)

Hi, are these the artwork you are referring to?

**Comment by DorkNow** [comment]
Yeah, I'm talking about them. That wouldn't be a problem, but I often find myself clicking the wrong one, when I try to open one of game's sections through favorites menu

**Comment by Pickysaurus** [comment]
![kotr2](https://user-images.githubusercontent.com/31670524/44000893-fdb7e616-9e1f-11e8-88f2-c90bfb807eba.jpg)
I'm replacing the image with this one.

**Comment by Pickysaurus** [comment]
Fixed
