### ISSUE TITLE
ReCaptcha login bug

### ISSUE THREAD

**Issue by theSnak3** [Nexus-Mods/web-issues#777]
when i try to login to the website the reCaptcha don't pop up so i went and get help from the discord server one of the staff that was online pickysaurus sent me link here proof
![default](https://user-images.githubusercontent.com/32428160/43998381-969252bc-9dc2-11e8-901a-addd0f1e6ebc.PNG) so i tred it 
![capture](https://user-images.githubusercontent.com/32428160/43998383-a02c6128-9dc2-11e8-9389-fb5d989ff823.PNG) did not work can you just put the old one back?

**Comment by Pickysaurus** [comment]
This is not a bug with the site, as I have explained on Discord. It's something on your PC's end blocking the both reCaptchas. It's either anti-virus, firewall or a restriction from your internet provider blocking the content. Are you able to replicate this issue on another device, such as a smart phone or tablet? If you are able to do it from a mobile phone, please try both Wi-Fi and mobile data.
