### ISSUE TITLE
Game that hasn't been approved appearing in the list of games

### ISSUE THREAD

**Issue by TheTokenGeek** [Nexus-Mods/web-issues#78]
Final Fantasy XIII has not been approved in the admin panel, but is showing up in the list of games.

When you click on the game the following message is displayed:
```
Location not found!
corereq_r
array(1) {
  [0]=>
  string(16) "finalfantasyxiii"
}
classreq_r
array(1) {
  [0]=>
  string(16) "finalfantasyxiii"
}
main: \Libs\Common\Managers\finalfantasyxiii
sec: 
innermethod: 
```

![image](https://user-images.githubusercontent.com/20457347/30538520-4b481be2-9c66-11e7-8c66-108e7e4a07a2.png)

**Comment by verenion** [comment]
Assigned PT#151168416

**Comment by verenion** [comment]
Fix has been pushed
