### ISSUE TITLE
mods blocked  but not actually blocked 

### ISSUE THREAD

**Issue by willdoucetnew** [Nexus-Mods/web-issues#780]
## Bug/error being reported:

Certain mods are only visible under authors page. With description, "This mod contains content that you have blocked in your settings and will not be visible in any of your search results." 
Nothing is blocked in settings.  Clicking on nsfw tag shows zero mods. all other tags show mods.
## Expected result:

find judgment wenches by searching wenches, or judgment, or judgment wenches 
## Actual result:

judgment wenches not found

**Comment by iamtiz** [comment]
Hi, what's your username on Nexus Mods?

**Comment by willdoucetnew** [comment]
Willdoucet 


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Tiz <notifications@github.com> Date: 2018-08-15  11:08 AM  (GMT-04:00) To: Nexus-Mods/web-issues <web-issues@noreply.github.com> Cc: willdoucetnew <wdoucet@eastlink.ca>, Author <author@noreply.github.com> Subject: Re: [Nexus-Mods/web-issues] mods blocked but not actually blocked (#780) 
Hi, what's your username on Nexus Mods?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nexus-Mods/web-issues","title":"Nexus-Mods/web-issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Nexus-Mods/web-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iamtiz in #780: Hi, what's your username on Nexus Mods?"}],"action":{"name":"View Issue","url":"https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413208693"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413208693",
"url": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413208693",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Nexus-Mods/web-issues] mods blocked  but not actually blocked  (#780)",
"sections": [
{
"text": "",
"activityTitle": "**Tiz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@iamtiz",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 780,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 780\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413208693"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 368424666\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by iamtiz** [comment]
You are currently blocking 3 tags: "Saved games", "Translation" and "Not Lore-Friendly". 
Judgment Wenches is tagged as  "Not Lore-Friendly" on both Skyrim and SkyrimSE, so that would be the reason why it's being hidden.

You should be able to un-block that tag in your account page, specifically the "content blocking" tab:
https://www.nexusmods.com/users/myaccount?tab=content+blocking

Let me know if there's an issue with that page

**Comment by willdoucetnew** [comment]
Omg. Lol. Yes that worked thanks. I have not seen a link to content blocking, has does one typically find it?


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Tiz <notifications@github.com> Date: 2018-08-15  11:32 AM  (GMT-04:00) To: Nexus-Mods/web-issues <web-issues@noreply.github.com> Cc: willdoucetnew <wdoucet@eastlink.ca>, Author <author@noreply.github.com> Subject: Re: [Nexus-Mods/web-issues] mods blocked but not actually blocked (#780) 
You are currently blocking 3 tags: "Saved games", "Translation" and "Not Lore-Friendly".

Judgment Wenches is tagged as  "Not Lore-Friendly" on both Skyrim and SkyrimSE, so that would be the reason why it's being hidden.
You should be able to un-block that tag in your account page, specifically the "content blocking" tab:

https://www.nexusmods.com/users/myaccount?tab=content+blocking
Let me know if there's an issue with that page

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nexus-Mods/web-issues","title":"Nexus-Mods/web-issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Nexus-Mods/web-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iamtiz in #780: You are currently blocking 3 tags: \"Saved games\", \"Translation\" and \"Not Lore-Friendly\". \r\nJudgment Wenches is tagged as  \"Not Lore-Friendly\" on both Skyrim and SkyrimSE, so that would be the reason why it's being hidden.\r\n\r\nYou should be able to un-block that tag in your account page, specifically the \"content blocking\" tab:\r\nhttps://www.nexusmods.com/users/myaccount?tab=content+blocking\r\n\r\nLet me know if there's an issue with that page"}],"action":{"name":"View Issue","url":"https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413216235"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413216235",
"url": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413216235",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Nexus-Mods/web-issues] mods blocked  but not actually blocked  (#780)",
"sections": [
{
"text": "",
"activityTitle": "**Tiz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@iamtiz",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 780,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 780\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Nexus-Mods/web-issues/issues/780#issuecomment-413216235"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 368424666\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by iamtiz** [comment]
It's currently only found when browsing the settings page
