### ISSUE TITLE
filedelivery.nexusmods.com uses a Symantec TLS certificate -- soon to be distrusted by all major browsers

### ISSUE THREAD

**Issue by zJelly** [Nexus-Mods/web-issues#781]
## Bug/error being reported:
When trying to download a file with Firefox Nightly, an SSL error is encountered. Normal browsing does not appear to be affected.

This is due to the upcoming distrusting of most Symantec root certificates, which will affect Chrome, Firefox and Safari within a few months. More information can be found at:

https://www.ssllabs.com/ssltest/analyze.html?d=filedelivery.nexusmods.com

https://blog.mozilla.org/security/2018/07/30/update-on-the-distrust-of-symantec-tls-certificates/

https://support.apple.com/en-us/HT208860

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/eUAKwjihhBs%5B251-275%5D

The issue will start affecting Chrome and Firefox stable on **October 23rd 2018**

## Steps to reproduce:
Install Firefox Nightly
Ensure `security.pki.distrust_ca_policy` is set to `2` in about:config (this should be the default value now)
Attempt to download a file from nexusmods

## Expected result:
The file downloads

## Actual result:
An SSL error, requiring an exception to be added

**Comment by mrmason** [comment]
We're aware of this and will be sorting it soon

**Comment by Pickysaurus** [comment]
Resolved
