### ISSUE TITLE
Comments order different when logged in

### ISSUE THREAD

**Issue by nmeo** [Nexus-Mods/web-issues#784]
I noticed that when I am logged in the order of comments is different from when logged out. Attached are a couple of images from the Immersive Armors comments (https://www.nexusmods.com/skyrim/mods/19733?tab=posts) that show the difference. Looks like the sorting when logged in is based on just the initial post while when logged out it is based on the timestamp of the latest reply. Doesn't really matter which sorting happens in my opinion, but they should probably be consistent for when the user is both logged in and logged out.

![img1](https://user-images.githubusercontent.com/5437254/44275803-b20bdb80-a213-11e8-9867-6728ac000f54.png)
![img2](https://user-images.githubusercontent.com/5437254/44275804-b20bdb80-a213-11e8-9716-b30f4eb0a1e6.png)

**Comment by iamtiz** [comment]
Hi, the behaviour can be changed in your settings, at https://www.nexusmods.com/users/myaccount

If you go to "Global preferences" you'll find a "Replies to posts bump the original post" option you can turn on or off
