### ISSUE TITLE
Download speed limited to less than 20 kb/s 

### ISSUE THREAD

**Issue by Ayylmarie** [Nexus-Mods/web-issues#785]
## Once a mod is downloaded, the speed of the download dramatically drops
<!--Basically the download speed of files from this site (even as a registered user) and the download crashes randomly too.->

## Steps to reproduce:
<!--
1. Go to any mod or for the Nexus Mod Manager (or any other +6MB sized file) download link(s)
2. start the download
3. watch the download speed of your file
4. wait for the download to crash
5. hooray! you found the bug!
## Expected result:
Download speed between 30kb/s and 1 mb/s

## Actual result:
9 kb/s and dowload crashes after 1 minute

**Comment by iamtiz** [comment]
Hi, can you provide some more details in this topic? https://forums.nexusmods.com/index.php?/topic/5322760-reporting-download-problems/
