### ISSUE TITLE
Distribution Branches

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#786]
This is a feature request.

I'd like to be able to set up a file as available to select users. For example, I'd like to be able to upload a file to a "testing branch" and send testers a code they can use to see and download from that branch.

Similar to Steam's betas tab:

![2018-08-19 12_11_57](https://user-images.githubusercontent.com/1261664/44312197-27f57b80-a3a9-11e8-98c8-9129e76e2913.png)

**Comment by Greg-Nexus** [comment]
Moved to our Feedback page: https://feedback.nexusmods.com/posts/24/distribution-branches
