### ISSUE TITLE
Feature Request: Archive Old Versions / Remove Download Buttons

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#787]
This is a feature request.

I'd like to be able to truly archive an old file and remove both download buttons.

For example:

![2018-08-19 12_17_41](https://user-images.githubusercontent.com/1261664/44312249-11035900-a3aa-11e8-83f6-275e48788724.png)

In addition, you should be able to toggle off the download buttons for all old files.

**Comment by fireundubh** [comment]
To add to the original request:

An option to toggle off the download buttons for all old files.

**Comment by Pickysaurus** [comment]
We're currently considering design options for the files section of the mod page that would make old/outdated versions less visible and discourage users from downloading them.
