### ISSUE TITLE
Main mods page default sorts by "Endorsements", no URL for other sorting

### ISSUE THREAD

**Issue by ViolentQuiche** [Nexus-Mods/web-issues#788]
## Bug/error being reported:
I had a "frequently used" shortcut for https://www.nexusmods.com/stardewvalley/mods/ which used to take me to the Stardew Valley mods page sorted by publish date. This now redirects to the mods page sorted by endorsements, and I have to change the sort each time I visit.

### Example:
1. Navigate to https://www.nexusmods.com/stardewvalley/mods/
2. Redirected to https://nexusmods.com/stardewvalley/mods/
3. Mods are sorted by endorsements
4. Sort by > Date published
5. URL changes to https://www.nexusmods.com/stardewvalley/mods/?BH=0

## Expected result:
Show all Stardew Valley mods sorted by publish date.

## Actual result:
The URL updates to https://www.nexusmods.com/stardewvalley/mods/?BH=0 when sorted by publish date, although navigating directly to that address redirects to the default.

## Other info:
Browser: Chrome 68.0.3440.106 (Desktop) and Chrome 68.0.3440.91 (Mobile)

**Comment by iamtiz** [comment]
Hi, you can change the default sorting order in your preferences: https://www.nexusmods.com/users/myaccount > Search Preferences > Default sorting option
