### ISSUE TITLE
Empty space next to small hyperlinked image is also 'hyperlinked' when it shouldnt be

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#79]
Sorry for the atrocious title but its quite hard to describe briefly due to the details of the bug
My example: https://rd.nexusmods.com/skyrim/articles/51006/?
In this article I use BBC to resize the images to be smaller and attach a hyperlink to them to take users to the full size image if clicked. EG: 
[center][url=http://imgur.com/izwU0QR][img width=480,height=270]http://i.imgur.com/izwU0QR.png[/img][/url]

On the normal nexus site, this is fine and works as expected: ONLY when you click on the resized image will it take you to the link. 
On the RD site, having your mouse sitting over to the sides of the image where there's blank space still activates the hyperlink, making it very easy to accidentally click it and lose your place in the article. 

Minor issue, but worth reporting, especially if the images not displaying next to each other issue gets fixed and ends up conflicting with this issue.

**Comment by verenion** [comment]
Assigned PT#151514816

**Comment by verenion** [comment]
Fix has been pushed

**Comment by Nazenn** [comment]
Confirmed fixed, thank you very much :)
