### ISSUE TITLE
Received no confirmation email

### ISSUE THREAD

**Issue by bschwartz525** [Nexus-Mods/web-issues#792]
## Bug/error being reported:

Attempting to login with inactive account.  Should be receiving confirmation email, but none recieved.  Tried resending multiple times.
## Steps to reproduce:

Optimally an ordered list with the steps needed to reproduce the bug
Step1: Hit login
Step2: Wait forever.
Step3: File bug report
## Expected result:

An email.
## Actual result:

Really?

**Comment by iamtiz** [comment]
Have you checked the spam folder? There might be a chance our e-mails were filtered out.
Is the address starting with "bjs3" the one you are currently using?
