### ISSUE TITLE
Nexus Site page not loading correctly

### ISSUE THREAD

**Issue by TritonRM** [Nexus-Mods/web-issues#793]
## Bug/error being reported:
Can't get Nexus mods site to load correctly.
Using up to date version of Chrome. Tried in Microsoft Edge and it works fine, but I don't use Edge.

## Steps to reproduce:
Not sure just tried to visit the site just like I normally do

![nexusproblem](https://user-images.githubusercontent.com/42659801/44557211-899c4980-a70b-11e8-998f-8782ad2b1bb2.jpg)

**Comment by iamtiz** [comment]
Do you have any extensions / blocker active on your browser?

**Comment by TritonRM** [comment]
Just Ad-blocker Plus and Grammarly. The problem has fixed itself. Not sure what caused it.
