### ISSUE TITLE
Download speeds slower than molasses

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#794]
## Bug/error being reported:
Download speeds > 1 MB/sec

## Steps to reproduce:

Download any file from Nexus & watch download speeds slow to less than 1 MB/sec despite having lifetime Premium Nexus membership.

## Expected result:
Download speeds appropriate for a 400 Mb/sec cable internet connection.

## Actual result:
Download speeds the equivalent of dial-up internet.

**Comment by iamtiz** [comment]
Hi, please refer to this thread for download and speed issues: https://forums.nexusmods.com/index.php?/topic/5322760-reporting-download-problems/
