### ISSUE TITLE
[SEO] Clicking on "Description" tab on mods adds "?tab=description" meaning two separate URLs are used for the exact same content

### ISSUE THREAD

**Issue by Freso** [Nexus-Mods/web-issues#796]
## Bug/error being reported:
Very minor issue and not one that affects users per se, but as a web developer it bugs me. :) When you go to a mod it has one URL (e.g., <https://www.nexusmods.com/skyrimspecialedition/mods/1918>) and then when you click the "Description" tab you get another URL (e.g., <https://www.nexusmods.com/skyrimspecialedition/mods/1918?tab=description>) with the *exact* same content.

While humans browsing the pages won't really notice this, it may confuse e.g., search engines who think the two are different pages, which may in turn lead to decreased SEO since it thinks you're trying to push the same content via multiple pages/URLs.

## Steps to reproduce:

1. Go to https://www.nexusmods.com/skyrimspecialedition/mods/1918
2. Click "Description" tab

## Expected result:

Either the "Description" tab linking directly to https://www.nexusmods.com/skyrimspecialedition/mods/1918 (with no query parameters) or https://www.nexusmods.com/skyrimspecialedition/mods/1918?tab=description HTTP redirecting to https://www.nexusmods.com/skyrimspecialedition/mods/1918 (or the other way around).

**Comment by Pickysaurus** [comment]
We will be reviewing SEO in the next major update to mod pages.
