### ISSUE TITLE
Broken links to images in the description

### ISSUE THREAD

**Issue by piotrmil** [Nexus-Mods/web-issues#797]
## Bug/error being reported:
Links to images uploaded to nexus are broken, since you have changed names of the servers. 

For example, this https://static-4.nexusmods.com/15/mods/110/images/62186-1-1422763677.png
should become this: https://staticdelivery.nexusmods.com/mods/110/images/62186-1-1422763677.png

## Steps to reproduce:

1. Go to one of my mods: https://www.nexusmods.com/skyrim/mods/62186?tab=description#
2. See that the images I used to make the descriptions nicer are broken  (I might leave one untouched when I'll be fixing it, since I actually care about how it looks)
3. Go back in time to before you introduced the new layout
4. See that they work fine there.
5. Go back to the future.

## Expected result:
The system should account for the change of servers.

## Actual result:
It does not.

**Comment by Pickysaurus** [comment]
These should have been fixed
