### ISSUE TITLE
One of the registration process use the email as account name

### ISSUE THREAD

**Issue by cecton** [Nexus-Mods/web-issues#798]
## Bug/error being reported:

When you register your account during the checkout, the email address is used for the username/account name. Whenever you comment on nexusmods, anybody will see your email address. This is a serious privacy issue.

## Steps to reproduce:

1. Go to https://www.nexusmods.com/signup without being logged
2. **DO NOT click on the button "Register now"**
3. Scroll down to the bottom of the page
4. Click on the button "Become a supporter"
5. Click on the big icon
6. Click on "Add to cart"
7. Click on "Checkout"

There you are: the form will **not** allow you to enter the account name/ID. It will uses your email address instead. Making your email address visible to every user when you comment (for example).

## Expected result:

Being able to enter the account name manually.

## Actual result:

The email address is used automatically.

**Comment by Pickysaurus** [comment]
Hi cecton,

There was a warning on registering that explained this may happen if you did not follow the instructions offered.  

If you fire an email to support@nexusmods.com we'll be able to put it right for you though. :)

**Comment by cecton** [comment]
Hello Mike,

That one?

You are not logged in (and this is bad!). If you already have a Nexus
account, click here to login else you will end up making a new account →
<https://forums.nexusmods.com/index.php?app=nexus&module=payments&section=pay&do=login&id=8753706&secure_key=880ea6a14ea49e853634fbdc5015a024>
It doesn't really explain the issue I had. I think you should do something,
I can imagine people don't want everybody to see their address every time
they comment.

I removed the account by myself... I was very worried :)

Best

**Comment by iamtiz** [comment]
We changed the text on that message to make the issue clearer
