### ISSUE TITLE
Site Not Loading Properly

### ISSUE THREAD

**Issue by MrImJustAminorThreat** [Nexus-Mods/web-issues#799]
## Bug/error being reported:
Sometimes when the site loads the game page doesn't load properly, I thought this might just be because I have 3 game pages as part of my startup tabs, but I just had it happen when manually going to the page.

## Steps to reproduce:
I am unable to reproduce this issue, at least not on command, it has happened several times though. It is easily fixed by simply refreshing the page but felt I should still report it.

## Expected result:
The page loads as expected

## Actual result:
https://gyazo.com/a6fb5da3ecab8f8c0a711e2b986d3c02

**Comment by iamtiz** [comment]
Are you using any browser extensions? Sometimes blockers especially can interfere with css/javascript loading
