### ISSUE TITLE
Advanced Search, Placeholder

### ISSUE THREAD

**Issue by soraphis** [Nexus-Mods/web-issues#8]
site: http://www.nexusmods.com/games/mods/searchresults/?

Less a bug than a feature request ... or an advise:

this is the html code of the descripton-search field (**but it applies to any of the search fields**):

```html
<input class="std_txt" name="src_descr" id="src_descr" type="text" value="description contains..." title="description contains..." onblur="javascript:restoreField('src_descr','description contains...');" onmousedown="javascript:clearField('src_descr','description contains...');" onkeydown="javascript:clearField('src_descr','description contains...');">
```

based on what it does, this can be reduced to:

```html
<input class="std_txt" name="src_descr" id="src_descr" type="text" placeholder="description contains...">
```

**advantages**

- less and cleaner html and js code (less bandwith usage ;D)
- placeholder works with disabled javascript, and if #5 is fixed as i proposed it, this will make the search work without javascript (for users who disabled js)

also: because you've set the placeholder in the value of the fields, when submitting the form you are sending this to your server:

```
[...]
src_view:1
src_name:file name contains...
src_descr:description contains...
src_auth:author name contains...
src_upldr:uploader name contains...
src_game:0
[...]
```

so i assume on your server you are checking something like: ` if value !== "file name contains..."`

*btw: if the source would be open source i'd make pull requests*

**Comment by iamtiz** [comment]
Fixed

**Comment by soraphis** [comment]
Placeholder text is grey, to give it the same color as before:

```css
input::placeholder {
    color: #e6e6e6;
}```
