### ISSUE TITLE
Only notify about file uploads after virus scan has completed

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#80]
This is a suggested enhancement:
Currently, the site sends you an 'Update' as soon as a file is uploaded to the server. However, mod updates are usually unavailable at this point, because they are still being scanned by virustotal.com.
The site should only send an update notification if the file is actually available for download.

**Comment by mrmason** [comment]
The medium term plan is to locally scan files on upload so that we can make them live straight away and then send to VT afterwards for verification - If we can't get to that task in a reasonable time then we can look at changing the notifications.

**Comment by LadyMilla** [comment]
Local scanning would definitely speed up the process. Now it is quite annoying when you receive an update, visit a mod page, only to find that the file is still being scanned (and it is still being scanned 3 or 4 hours later). By the way, I would add one more thing to this suggestion: updates should only be sent when the mod page is visible (some of the mod authors hide their mod pages before updating them, and they only unhide them when everything is okay with the uploads/changes).

**Comment by RavenMind** [comment]
This may be related to [issue #425](https://github.com/Nexus-Mods/web-issues/issues/425).

**Comment by iamtiz** [comment]
Assigned #155936664

**Comment by iamtiz** [comment]
done.
