### ISSUE TITLE
Preview Contents button/link not working

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#800]
## Bug/error being reported:
The Preview Contents button/link is not working at all.

## Steps to reproduce:
1. Click "Preview Contents" on any mod page.
2. "The content could not be loaded" error message is displayed.

## Expected result:
A preview of the contents contained within an archive uploaded to the Nexus.

## Actual result:
"The content could not be loaded" error message is displayed with no further explanation instead.

**Comment by KramerGamer** [comment]
I confirm this.

**Comment by iamtiz** [comment]
fixed

**Comment by KramerGamer** [comment]
thank you
