### ISSUE TITLE
Opening changelog collapses file header

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#801]
## Bug/error being reported:
When clicking the version number to view changelog, it also collapses the file header, mean you have to expand it again to click the download button.
Reported by Artaious on Mod Author Discord.

## Steps to reproduce:
https://www.nexusmods.com/skyrimspecialedition/mods/2357?tab=files
#1 - Click 3.74 (or whatever current version is) with header expanded. 
#2 - Header will collapse.

## Expected result:
Header stays expanded.

## Actual result:
Header collapses.

**Comment by iamtiz** [comment]
fixed
