### ISSUE TITLE
cannot register on the site

### ISSUE THREAD

**Issue by engharat** [Nexus-Mods/web-issues#802]
## Bug/error being reported:
The registration seems to go fine until I try to activate the account: both the full link and the link which require adding manually the activation code fails with the following error:
"Oops! Something went wrong!"
Tried with another mail, same result.

**Comment by iamtiz** [comment]
What's the username you are using on the Nexus?

**Comment by engharat** [comment]
the chosen username is "blabla17".

Il giorno mer 29 ago 2018 alle ore 11:28 Tiz <notifications@github.com> ha
scritto:

**Comment by Pickysaurus** [comment]
I'm guessing the email account is breaking the links with the &sect thing?
Could you paste the contents of the email you had here? 
You can contact support@nexusmods.com to get this resolved manually :)
