### ISSUE TITLE
Nexus site keeps reverting Show 60 Items back to default 20

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#803]
## Bug/error being reported:
I keep having to reset my preference of Show 60 Items from the default Show 20 Items after a few days.

## Steps to reproduce:
1. Click the Show drop-down & select 60.

2. After a couple days or so, the Show 60 Items will reset to the default Show 20 Items on the Nexus sites.

## Expected result:
Show 60 Items stays as my preferred selection in the Show drop-down menu.

## Actual result:
Show 60 Items keeps resetting to the default Show 20 Items in the Show drop-down menu after a couple days or so.

**Comment by iamtiz** [comment]
What's your username on the Nexus?

**Comment by scjohnson1981** [comment]
ff7legend

**Comment by iamtiz** [comment]
Did you notice a pattern at all, like for example the preference being reset after visiting a certain page or a applying a certain fitler?

**Comment by iamtiz** [comment]
Assigned #160311738

**Comment by iamtiz** [comment]
I was able to replicate the issue by visiting the "download history" page: doing so apparently resets the preference to 20. I'm going to see of there are more of these circumstances, and then fix the issue

**Comment by scjohnson1981** [comment]
Awesome!  Glad you found the cause.  Look forward to a fix.

**Comment by iamtiz** [comment]
fixed
