### ISSUE TITLE
Skyrim SE Nexus uploader on the fritz

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#804]
## Bug/error being reported:
Frankly HD Dawnguard Armor & Weapons stuck in infinite uploading loop (Skyrim SE Nexus version)

## Steps to reproduce:
1. Head over to https://www.nexusmods.com/skyrimspecialedition/mods/19663

2. File not available for download after 3 attempts using different version numbers

## Expected result:
File available for download

## Actual result:
File stuck in infinite uploading loop & unavailable for download after 2+ hours

**Comment by m1ndflux** [comment]
Can't really add anything useful apart from the fact that this just happened to one of my mods too.

**Comment by mrmason** [comment]
@m1ndflux - please can you link the mod you uploaded so we can take a look ?

**Comment by m1ndflux** [comment]
@mrmason Of course, here you go: https://www.nexusmods.com/skyrimspecialedition/mods/14368?tab=files

**Comment by scjohnson1981** [comment]
It's not my mod.  I linked the mod in my OP above.  Also, this mod is also stuck in an infinite loop:

https://www.nexusmods.com/skyrimspecialedition/mods/14368

**Comment by mrmason** [comment]
Thanks, we're looking into it now. It looks like it has nothing to do with virus scanning, there seems to be a slowdown on distributing files to the file servers.

**Comment by mrmason** [comment]
We've found some files that have got stuck being distributed and have sorted that out. There is a few hours of backlog to work through so it might be a little while yet before these files are available to download but it should sort itself out soon and catch up - Sorry for the inconvenience!

**Comment by m1ndflux** [comment]
@mrmason No worries, thanks for the quick resolve. You rock!

**Comment by mrmason** [comment]
Should all be cleared now - thanks for bringing it to our attention!
