### ISSUE TITLE
Fallout 4 mods stuck in virus scan

### ISSUE THREAD

**Issue by Gentester** [Nexus-Mods/web-issues#805]
Mods stuck in infinite virus scan loop

https://www.nexusmods.com/fallout4/mods/9424?tab=files  
check here as this mod has been trying to update for 4 plus hours now

## Expected result:
to be able to download the file after a short period

## Actual result:
waiting 4 plus hours later

**Comment by scjohnson1981** [comment]
This is also the case over on Skyrim SE Nexus.  In fact, I suspect this will be the case across the entire Nexus network.  The sites haven't been working correctly for several days now.  Numerous issues with uploads/402 - Bad Gateway errors/slower than molasses download speeds (Kent, UK Premium Server)/etc across the entire Nexus network.

**Comment by mrmason** [comment]
This should be sorted now.

@scjohnson1981 - We haven't had any reports of any other issues with uploading ( other than #804 which is the same as this ) - If you have any more information regarding problems or slow downloads that are different to this one, please can you open up a new bug report and we can try and debug what's going on for you.
