### ISSUE TITLE
Media Tab - Videos section does not recognise the new YouTube URLs

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#806]
## Bug/error being reported:
When adding a video to the Media page of a mod page. Pasting the new YouTube short URL is not recognised.
Reported by Kinggath on discord.

## Steps to reproduce:
1) Go to media tab
2) Add video with URL http://youtu.be/t4PZkXQS8w
3) URL not long enough error is returned.
![image](https://user-images.githubusercontent.com/31670524/44921905-c5529700-ad3b-11e8-9fea-11ea20f32717.png)

## Expected result:
Video can be added

## Actual result:
URL rejected

**Comment by iamtiz** [comment]
Fixed
