### ISSUE TITLE
Download popup not opening at all.

### ISSUE THREAD

**Issue by Asmageddon** [Nexus-Mods/web-issues#807]
## Bug/error being reported:
I was merrily downloading mods for The Witcher 3, turned Firefox off, realized I forgot a prerequisite, and upon trying to download it, the download popup would not open - "Loading..." would be shown, after which page would remain grayed out, but nothing would appear.

Attempts to download the file in incognito mode have failed similarly, as have ones in Edge, and ones in Chrome(both incognito and not)

## Steps to reproduce:
No idea sorry :-(

For reference, this is the mod in question: https://www.nexusmods.com/witcher3/mods/2521, but I have since confirmed that the same is the case on other Witcher 3 mods, and on Payday 2 mods as well.

**Comment by masterhero92** [comment]
Same Here, its all mods not only that mod 
We want a fix quickly

**Comment by FullOfSpaghetti** [comment]
Everyone is experiencing it

**Comment by LadyMichael** [comment]
Same problem...hope they fix it quickly.

**Comment by mrmason** [comment]
Should be working now.
