### ISSUE TITLE
Cant Download any mod from the site suddenly !! just couple of minutes ago, whether through NMM or manual 

### ISSUE THREAD

**Issue by masterhero92** [Nexus-Mods/web-issues#808]
## Bug/error being reported:
Cant' download

## Expected result:
Wanted to Download

## Actual result:
Nothing happens

**Comment by ArnieV** [comment]
Same. Just suddenly couldn't download anything. At first I thought it was an issue with my browser, but evidently, I'm not an isolated case.

**Comment by l1qu1d101** [comment]
Same here, I go to download and nexus redirects to lthot.dk and cannot look it up on DNS server.

**Comment by FullOfSpaghetti** [comment]
Same here

**Comment by masterhero92** [comment]
we want a fix quickly, we can't wait for long

**Comment by LadyMichael** [comment]
Yeah...same problem here.

**Comment by lolface2317** [comment]
Having same problem

**Comment by l1qu1d101** [comment]
Manual download is working fine.

**Comment by lolface2317** [comment]
it isnt for me i just get the dimmed background and no download

**Comment by mrmason** [comment]
Should be working now!

**Comment by TurtleDruid** [comment]
same here

**Comment by FullOfSpaghetti** [comment]
that was fast lol

**Comment by l1qu1d101** [comment]
Yes fantastic working again you guys are the best thanks!
