### ISSUE TITLE
Admin function: Find Member or clickable user names in IP list (Enhancement)

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#81]
On rd.nexusmods.com/admin/:

The 'Users' section should have a 'Find member' search box. Right now if I want to find a member appearing the IP list, I have to switch to the forum and use the moderator functions there.

Alternative solution:
The problem:
- Pick any user on the TEST site
- Click 'Moderate' -> 'IP use'
The IP use list will appear. In this list click on any of the IP addresses. You'll get a list where the user names associated with the IP addresses are clickable. However, when you click on the user name, you'll be taken to that user's IP use list instead of its user profile. This is inconvenient because very often you need profile information (link to the forum profile, uploaded images, etc.) and NOT the IP use list (that is easily accessible from the Moderate menu anyway).

Solution:
- Clickable user names in the IP use list should take you to the user profiles.

**Comment by iamtiz** [comment]
Fixed
