### ISSUE TITLE
XML file with "AccessDenied" code is shown when trying to download a mod

### ISSUE THREAD

**Issue by Jimmylobo** [Nexus-Mods/web-issues#810]
## Bug/error being reported:
Instead of the file with the mod I requested, I get a strange XML with "AccessDenied" code.

## Steps to reproduce:
1. Log in with account "jimmyd".
2. Go to this URL: https://www.nexusmods.com/nomanssky/mods/693?tab=files
3. Click "Manual download" button in the "Better HD Clouds 4K 1.2 for NEXT" section.

## Expected result:
Mod file is downloaded.

## Actual result:
The following page is shown:
"Podany plik XML nie zawiera żadnych informacji o stylach z nim związanych. Poniżej wyświetlone jest drzewo dokumentu.
      `<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>40963F21C869F5FF</RequestId><HostId>rD3rwjK7qA2+cb1zvN8PpqW4TLftBsxF/G2Oy79Rq6eAKkgh2L5SKbWi3CuItbRNHmBUbq9nNyY=</HostId></Error>`"

(the translation of the first 2 sentences is as follows:
"Given XML file doesn't contain information about style related to it. Document tree is displayed below.")

Browser used: Firefox Quantum 61.0.2 (64 bit)
OS: Windows 10 Pro

**Comment by mrmason** [comment]
Can you please try now ?

**Comment by Slashztron** [comment]
i have the same problem with my mod page aswell when people reported trying to download my mod, do you want me to put in another issue or can i link it here as well?

**Comment by mrmason** [comment]
If you can link me the mod I'll take a look!

**Comment by Slashztron** [comment]
here is it the main file and the first optional file 
https://www.nexusmods.com/skyrimspecialedition/mods/19612?tab=files

**Comment by mrmason** [comment]
Thanks, give me a little bit of time I'm going to try and scan our file origin for missing files, if I'm unable to do that in the next couple of hours I'll revert the downloads to an alternate location.

**Comment by Slashztron** [comment]
ok thanks!

**Comment by Jimmylobo** [comment]
It works now. Thank you for such quick fix!

**Comment by ElectricWarrior77** [comment]
I am getting the same error on my mod page. Hearthfire Guards and Fortifications found here 
https://www.nexusmods.com/skyrimspecialedition/mods/10101?

The download button on my mod is not working and the manual download gives me and the players who use my mod the following error.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>830BE48901D82847</RequestId>
<HostId>
04oy8UXooj8AYpf3LHf0fI4awN7BcSLBMt442P2NwxpilvdaUBZupHUd+9y8WjMDK8L1580SUBQ=
</HostId>
</Error>

PLEASE get this corrected ASAP.

Thank you,

-EW

**Comment by mrmason** [comment]
I've implemented a fix for this for now, I need to make some more changes next week.
