### ISSUE TITLE
Nexus uploader stuck (again).

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#812]
## Bug/error being reported:
Nexus uploader stuck in an infinite uploading loop.

## Steps to reproduce:
Head over to https://www.nexusmods.com/skyrimspecialedition/mods/18964 & notice the hung file under Optional Files (Yellow ?)

## Expected result:
File available for download after a few minutes.

## Actual result:
File still stuck in an upload loop after 34 mins.

**Comment by mrmason** [comment]
What do you mean by upload loop ? Do you mean the file was awaiting virus scan ?

We use external virus scanning on files, so sometimes there can be a bit of a wait.

If it's another issue can you please explain in more details the steps where you were seeing problems ?

**Comment by iamtiz** [comment]
Same as #753
