### ISSUE TITLE
Image Comments don't jump to post.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#813]
## Bug/error being reported:
When getting notifications about replies to comments on an image/video it doesn't jump to the relevant post like it does on a mod page.

## Steps to reproduce:
Comment on an image/video.
Have another person reply to you get an "Update"
When clicking the update it loads the page without scrolling to the comment. (This does work for mod page comments)

Can be inconvenient when the image page has many other photos in the description. 

## Expected result:
Jump to comment reply.

## Actual result:
Load page at the default position.

**Comment by iamtiz** [comment]
Assigned #160281660

**Comment by iamtiz** [comment]
fixed
