### ISSUE TITLE
Mobile - Game Homepage

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#814]
## Bug/error being reported:
At mobile resolution, 5 files from the hot files + trending section are not shown at all. 

On PC the two top mods are shown with 5 popular mods underneath. This list is then continued in "More Trending"

On mobile the two top mods appear *without* the 5 other mods, but "More Trending" shows the same as PC. 

## Steps to reproduce:
Visit a game homepage, such as https://www.nexusmods.com/fallout4?tab=more+trending
On both PC and mobile to compare what mods you can see.

## Expected result:
All trending mods have a place on the page

## Actual result:
Trending mods #3 - #7 are not shown at mobile resolutions

# Reported by dikr at this topic: https://forums.nexusmods.com/index.php?/topic/6965566-hot-files-slider-not-working-on-android-multiple-browsers/

**Comment by iamtiz** [comment]
fixed
