### ISSUE TITLE
Bugged pages at Tracking Authors (like it was with tracked mods)

### ISSUE THREAD

**Issue by GioGr** [Nexus-Mods/web-issues#816]
## Bug/error being reported:
At tracking center, authors tab, i have 5 pages but the last 3 (3,4,5) are all the same

## Steps to reproduce:
go to tracking center, authors tab, (maybe have more than 1 page of tracked authors or more?)

### Example:
1. page 3
![image](https://user-images.githubusercontent.com/12425911/45404539-0ade6080-b668-11e8-9906-fe1567cb2df7.png)

2. page 4
![image](https://user-images.githubusercontent.com/12425911/45404557-1af64000-b668-11e8-8508-b3420d651ff0.png)

3. page 5
![image](https://user-images.githubusercontent.com/12425911/45404584-32352d80-b668-11e8-81e6-19a290d754d3.png)

## Expected result:
not have the last 3 same pages showing the same and are not even needed (4+5)

## Actual result:
example above

**Comment by iamtiz** [comment]
Hi, What's your username on the Nexus?

**Comment by iamtiz** [comment]
Fixed
