### ISSUE TITLE
At counting files tab do not count old files

### ISSUE THREAD

**Issue by GioGr** [Nexus-Mods/web-issues#817]
What the title says :)

**Comment by iamtiz** [comment]
If you mean old versions of the files, they have to be counted as they can still be downloaded. If there's a mismatch between the number of files and the counter on the tab please give us some more details

**Comment by GioGr** [comment]
any chance for 2 numbers and the one is without old files and the other is total?

cause my thought was that from the main tab (description) i would see how many files it has and its more than 1 then i go to files to check them or else just just download for nmm/mo

**Comment by iamtiz** [comment]
Assigned #160788860

**Comment by iamtiz** [comment]
Done
