### ISSUE TITLE
[Mobile] Files Tab - Version number is not clickable (tap-able?)

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#818]
## Bug/error being reported:
When viewing a file page on mobile, clicking the version number on a file does not display changelog like it does on the main site. 

## Steps to reproduce:
Go to any file page with a changelog filled in. 
Click file version number.

## Expected result:
Changelog modal appears

## Actual result:
Nothing

##Reported on Mod Author Discord: https://discordapp.com/channels/232168805038686208/232170227734020097/489524200890171423

**Comment by iamtiz** [comment]
Assigned #160788871

**Comment by iamtiz** [comment]
fixed
