### ISSUE TITLE
Admin function: Links to mods/images in IP use list are broken

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#82]
- Pick any user (preferably a mod author) on TEST site;
- Use Moderate -> IP use;
- Click on any **mod/image links** in the Details column;
- You'll get an error message.

The problem is caused by the fact that the '<game_name>/' part is missing from the links 
E.g. current and broken link: https://rd.nexusmods.com/mods/86765 
Correct link: https://rd.nexusmods.com/skyrim/mods/86765

**Comment by iamtiz** [comment]
Assigned PT #151485536

**Comment by iamtiz** [comment]
Fixed
