### ISSUE TITLE
"You are not allowed to visit this community"

### ISSUE THREAD

**Issue by leehelck** [Nexus-Mods/web-issues#820]
## Bug/error being reported:
every time i try to access the forum, i get this message (screenshot included). even when i try to report it i still get this message. this is very frustrating. what is going on here? i have numerous mods published and have received no notifications from anyone on your team. all of my mods are still up, and i have no problems accessing the normal website. any help with this issue is greatly appreciated. 
![capture](https://user-images.githubusercontent.com/43259698/45528422-205da280-b7ae-11e8-9be3-64acdae998e1.JPG)

**Comment by Pickysaurus** [comment]
Are you using a VPN or anything that alters your IP? This is usually the message when your IP is blocked. Send an email to support@nexusmods.com with your IP and we'll look into it further :)

**Comment by leehelck** [comment]
i just only recently figured that out yesterday. i have resolved the issue by turning off my vpn. thank you for replying to my message. have a good day.

**Comment by leehelck** [comment]
i figured that out the next day. thank you for replying. have a good day.
    On Monday, September 17, 2018, 3:29:44 AM EDT, Mike <notifications@github.com> wrote:  
 
 
Are you using a VPN or anything that alters your IP? This is usually the message when your IP is blocked. Send an email to support@nexusmods.com with your IP and we'll look into it further :)
