### ISSUE TITLE
Manual downloads

### ISSUE THREAD

**Issue by TheBlackCr0w** [Nexus-Mods/web-issues#822]
## Actual result:

![manual download problem](https://user-images.githubusercontent.com/43318491/45598004-b9550f00-b9a2-11e8-80ea-8e790123b580.png)

**Comment by TheBlackCr0w** [comment]
I hope the fact that it isn't showing the info I just put down isn't due to a mistake I made...

**Comment by Civil-Protection** [comment]
For me, upon clicking manual downloads it immediately brings the error code **SSL_ERROR_ACCESS_DENIED_ALERT** 
Browser: Most recent Firefox

The mod (MCM) goes immediately to the download page and brings up that error. Other random mods I tried, among them Settlement Blueprint Transfers, first show the "popup" where mod requirements and so on are listed but then bring the same error page and code upon clicking on the green download button. Not an expert, but seems to indicate to me there's a general problem with mods or the specific file servers / certs, I guess.

**Comment by TheBlackCr0w** [comment]
Civil-Protection do you think it will be fixed soon?

**Comment by Civil-Protection** [comment]
> 
> 
> Civil-Protection do you think it will be fixed soon?

Unknown, I'd argue it would be in the staff interest to get it fixed as I suspect that many people can now not download or more specifically update mods. I also do not know how long this problem has existed now, it's been a while. I currently cannot play with two notable mods I need to update (MCM and settlements related mod).

I'm guessing it will be fixed relatively soon (within a day or the next few days).

**Comment by mrmason** [comment]
I have updated SSL settings on the server today - please can you let me know if you're still seeing errors?

**Comment by TheBlackCr0w** [comment]
Yes it is.

**Comment by mrmason** [comment]
Yes it is ... still broken or
Yes it is ... working now ? 

:)

**Comment by TheBlackCr0w** [comment]
Still broken

**Comment by mrmason** [comment]
We're unable to reproduce this on any machine here. What firewall / anti-virus software are you running ? Can you try disabling it and see if it makes a difference ?

**Comment by TheBlackCr0w** [comment]
Frontier secure

**Comment by TheBlackCr0w** [comment]
Before a few days ago though I was able to download mods just fine

**Comment by TheBlackCr0w** [comment]
I will try disabling to see

**Comment by TheBlackCr0w** [comment]
It started downloading right away... Thank you very much for your advice and time sir.

**Comment by mrmason** [comment]
Can you take a look in the settings regarding SSL/TLS security and see if you can find anything about rejecting sites with TLS1.0 or anything like that so we can get an idea of what the problem might be ?

**Comment by TheBlackCr0w** [comment]
Sure I can try looking

**Comment by TheBlackCr0w** [comment]
I am unable to find the settings regarding SSL/TLS security. This is most likely due to the fact that I just have no idea where it is.

**Comment by TheBlackCr0w** [comment]
I just want to say this for possible people with the same problem in the future:

You can fix this by adding this website: 

files.nexus-cdn.com 

to your excepted websites on your browsing protection on frontier secure. This also fixed a problem with the Mod Organizer 1 Legacy version for me

**Comment by mrmason** [comment]
Nice one, thanks !
