### ISSUE TITLE
Blocking Author does not block Image/Video uploads.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#824]
## Bug/error being reported:
Blocking a user only filters their mods, not their other content.

## Steps to reproduce:
Block a user who has uploaded an image, refresh and images will still be visible.

## Expected result:
Images are hidden from blocked author

## Actual result:
Images still appear.

Reported at on Nexus Mods forums: https://forums.nexusmods.com/index.php?/topic/6995776-still-seeing-screenshots-of-a-person-i-have-blocked/

**Comment by iamtiz** [comment]
Assigned #160788908

**Comment by iamtiz** [comment]
It should work now
