### ISSUE TITLE
Buggy name filter on the donation points monthly report page

### ISSUE THREAD

**Issue by shadeMe** [Nexus-Mods/web-issues#826]
## Bug/error being reported:
Entering anything in the 'Mod Name' filter textbox on DP Monthly Report page causes the entire report to disappear.

## Steps to reproduce:
1. Open any generated report.
2. Enter something in the name filter.

## Expected result:
The list filters out the mods that do not contain the entered filter string in their name.

## Actual result:
The list disappears in its entirety.

**Comment by Pickysaurus** [comment]
This should be fixed.
