### ISSUE TITLE
Team added images notification

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#828]
## Bug/error being reported:
![image](https://user-images.githubusercontent.com/31670524/45829299-8a1c0600-bcf2-11e8-8df3-2128552c8a1f.png)
The layout of this notification is a little odd, perhaps limit it to a single image or treat it as the new game notification works :)

**Comment by iamtiz** [comment]
Assigned #160788939

**Comment by iamtiz** [comment]
fixed
