### ISSUE TITLE
Admin function: links to posts are broken in IP use list

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#83]
- Pick any user (preferably a mod author) on TEST site;
- Use Moderate -> IP use;
- Looks for an entry in the Details column that points to a forum post.
- Clicking on the link will open the topic, but will not take you to the post in question.

This can be fixed easily by appending the '#entry' + post_number string to the URL.
E.g. Entry in the Details column: 'Topic XXXXXXX, post YYYYYYYY'
Current link:
http://forums.nexusmods.com/index.php?showtopic=XXXXXXX
Correct link:
http://forums.nexusmods.com/index.php?showtopic=XXXXXXX#entryYYYYYYYY

**Comment by iamtiz** [comment]
Assigned PT #151485536

**Comment by iamtiz** [comment]
Fixed
