### ISSUE TITLE
Donate button is off-centre and low res

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#831]
## Bug/error being reported:
Donate button displayed on member profiles uses a very pixelated old Paypal button which is not centred.
![image](https://user-images.githubusercontent.com/31670524/45884641-57364880-bdac-11e8-900b-3329f0c28d02.png)

## Steps to reproduce:
Visit a user profile that has direct donations enabled.
Click donate button.

## Expected result:
Perhaps replace with standard Nexus Mods button "Donate via PayPal"?

## Actual result:
n/a

**Comment by Pickysaurus** [comment]
Looks like this is based off the option "Donate Premium Membership" button that appears to the left. Neither button appears to be properly spaced though. 
![image](https://user-images.githubusercontent.com/31670524/45957068-07ee5300-c00c-11e8-937e-1d149753e43d.png)

**Comment by iamtiz** [comment]
#160788955

**Comment by iamtiz** [comment]
Done
