### ISSUE TITLE
Tagging issue when searching mods

### ISSUE THREAD

**Issue by ramonomar** [Nexus-Mods/web-issues#833]
https://www.nexusmods.com/skyrimspecialedition/mods/?tags_yes[]=1039&BH=10&RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:1704,advfilt:true,include_adult:false,show_game_filter:false,page_size:20,open:true,tags_yes%5B%5D:1073&RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:1704,advfilt:true,include_adult:false,show_game_filter:false,page_size:20,open:true,page:1,sort_by:OLD_downloads,tags_yes%5B%5D:1039,tags_yes%5B%5D:1073

With this link the site was supposed to show mods with the "replacer" and "sexy/skimpy", but it only shows mods with "replacer" tag.

**Comment by iamtiz** [comment]
Hi, you should check the "Include adult files" checkbox, to allow mods tagged as "sexy/skimpy" to be displayed

![screenshot_2018-10-09 mods at skyrim special edition nexus - mods and community](https://user-images.githubusercontent.com/3407947/46657552-743e8a00-cba8-11e8-986d-a6370759fdd9.png)
