### ISSUE TITLE
Navigating Nexus Mods causes "Leaving Site" popups in Chrome

### ISSUE THREAD

**Issue by theicedevil** [Nexus-Mods/web-issues#834]
## Bug/error being reported:

I'm using Google Chrome and when I navigate Nexus Mods, Google Chrome keeps nagging me about "Leaving Site" which I have to click the "Leave" button in order to navigate further.  This happens every time I click on a Mod link or try to close that tab loaded into Nexus Mods.  This happens even when I'm not technically leaving the site.  I've been using Google Chrome for years and I never had this issue on this site until yesterday, and I haven't been able to duplicate the issue on any other site, just Nexus Mods.

![nexus mods issue](https://user-images.githubusercontent.com/43731196/46319585-64fb8300-c58f-11e8-9b9b-eee69b8e6ea7.png)

**Comment by Pickysaurus** [comment]
Can you try loading the site with addons disabled in your browser? This is a likely cause.
