### ISSUE TITLE
Download tracking is not working

### ISSUE THREAD

**Issue by FastBlackCat** [Nexus-Mods/web-issues#836]
For at least the last four days, when I go to my "My Download History" using the dropdown menu under "My Activity" on the drop down menu of the Mods category,  it tells me "We are building your download history" and never produces the listing.

**Comment by mrmason** [comment]
I'm assuming your user id is `1111357` - if so then I can see your download history correctly when I load it.

It's possible your adblocker is blocking the script that loads your history - can you check inside your browser console/net tab and check ?
