### ISSUE TITLE
Bug tracker displays optional files as last downloaded version

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#837]
## Bug/error being reported:

Bug tracker for mods displays last downloaded file from ANY group (which we don't care about) rather than last downloaded file from MAIN files.

Example here: https://www.nexusmods.com/skyrimspecialedition/mods/17751?tab=bugs

## Steps to reproduce:

1. Download main file of any mod
2. Then download any optional file of same mod
3. Report bug

## Expected result:

I want to see last downloaded file from MAIN files group.

## Actual result:

I see last downloaded file from OPTIONAL files group.

**Comment by iamtiz** [comment]
Good point. We'll change to avoid taking into account optional files, updates and miscellaneous files. Only main files and old files (as they could have been main files at the time) will be used.
Assigned #161080219

**Comment by iamtiz** [comment]
Done. Please note that the fix will only work for new bug reports, and not for the existing ones

**Comment by zax-ftw** [comment]
> Done. Please note that the fix will only work for new bug reports, and not for the existing ones
Just wanted to say that it's still taking optional files as version. Can you take a look at it again?
