### ISSUE TITLE
Multiple copies of the "Add a New Topic" window on the forum page

### ISSUE THREAD

**Issue by CameronHudson8** [Nexus-Mods/web-issues#838]
## Bug/error being reported:

Clicking "Add Topic" results in 2 + n  instances of the "Add a New Topic" form appearing, where n is the number of times you've clicked to another page of forum posts.
Edit: After retrying, I'm now getting 1 + n instances. Still not the desired behavior, though.

## Steps to reproduce:

1. Go to a forum page such as [https://www.nexusmods.com/skyrim/mods/141?tab=forum&BH=6](https://www.nexusmods.com/skyrim/mods/141?tab=forum&BH=6)
2. Navigate to another page of forum topics, such as by clicking the left or right arrows.
3. Click the "Add a Topic" button.

## Expected result:

A single "Add a New Topic" form.

## Actual result:

Multiple "Add a New Topic" forms.

![capture](https://user-images.githubusercontent.com/35085463/46577243-edff2980-c996-11e8-9bf8-f6d7cf1165ac.PNG)

**Comment by iamtiz** [comment]
Hi, does it happen every time, or only sometimes? Are you using any extension/plugin?

**Comment by CameronHudson8** [comment]
No plugins. I'm using Chrome. Replicated it on MacOS just now. I edited my original Issue, because now it seems that the first time I view a page of form topics and click "Add Topic", a single "Add a New Topic" form appears (instead of 2, as before), but after navigating to a different page of forum topics and again clicking "Add a New Topic", duplicate forms appear.

**Comment by iamtiz** [comment]
Ah, got it now

**Comment by iamtiz** [comment]
Assigned #161212939

**Comment by iamtiz** [comment]
Fixed
