### ISSUE TITLE
Changing File Category (From Main to Old) - Cache lags the change

### ISSUE THREAD

**Issue by m0lz** [Nexus-Mods/web-issues#84]
When changing a files category from Main file to Old file, after you submit the change on the new site, the file does not immediately change to the old category.

I refreshed a few times up to a couple of minutes after the submit, and the two files concerned were still listed under Main - Whereas for comparison I also opened up the files tab on the old site and the change had immediately registered them to Old files.

I went back to the new site about five minutes after making the change, and they eventually did change to being listed under old files without any further action from me .. So its probably another cache issue delaying the change. But when you want to get on with uploading new files so that they are not confused with the old, this issue holds things up because you want to be sure the main files just consists of the new ones first and old files have indeed been shifted.

**Comment by verenion** [comment]
Assigned PT#151365789

**Comment by verenion** [comment]
Fix has been pushed
