### ISSUE TITLE
mod site double in profile / mods with bad links and timeot forum

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#840]
I  goto
https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files
you get https://www.nexusmods.com/skyrimspecialedition/users/5872020?tab=user+files&BH=0
(setting is on 80) scroll down, you see the last mod (the oldest in history) is twce, while the last has bad links and  is shown w/o files
![screenshot-1](https://user-images.githubusercontent.com/40837496/46759993-0b066600-ccd1-11e8-8458-290fd67f22ea.jpg)
![screenhsot-2](https://user-images.githubusercontent.com/40837496/46760000-0fcb1a00-ccd1-11e8-95c9-a467d39498c9.jpg)
![nexus3](https://user-images.githubusercontent.com/40837496/46760004-12c60a80-ccd1-11e8-99cd-6f1c6c6c329b.jpg)
![nexus4](https://user-images.githubusercontent.com/40837496/46760009-148fce00-ccd1-11e8-9038-5dbecca0e7fc.jpg)

(also, within past days your forum server very often times out, error cloud flair, and fileupload or safe of changed text on description page does not work or extreme slow - several minutes lag)

If you compare the wrong and the right mod's showing, you see it is same mod and same text and both is a skyrimSE mod, but the last (wrong) listing and wrong link to the non existing file is to skyrim part. 

I'm pretty sure that such not was times ago, this is a new issue on server database

on any mod page / posts => "forum thread" gives timesout, not only now but extreme often withim past days.
Error 522 Ray ID: 467b8bc6defec29c • 2018-10-10 19:38:44 UTC Connection timed out
You Browser Working  - Frankfurt Cloudflare Working - forums.nexusmods.com Host Error

**Comment by iamtiz** [comment]
Hi, I've just checked into our database, and found a record of the duplication.

The original Skyrim mod (https://www.nexusmods.com/skyrim/mods/80465) was duplicated in SkyrimSE (https://www.nexusmods.com/skyrimspecialedition/mods/5028) on the 25th of November 2016, at 20:33:47 UTC. 

No actual file seems to be have ever been uploaded for the original Skyrim mod.
