### ISSUE TITLE
Whole site is acting weird

### ISSUE THREAD

**Issue by KenshinRyuu** [Nexus-Mods/web-issues#841]
URL: https://www.nexusmods.com/skyrim/
Username on the Nexus: KenshinRyuu
Bug/error being reported: Lots of green showing up, the text is distorted and sort of checkered in appearance. when zooming in and out sometimes the text fixes itself, sometimes not.
Steps to reproduce: just visited the main site
Expected result: everything displays normally
Actual result: lots of green showing up instead of background images, mod pictures vanish
Link to the affected mod/image (if relevant): https://www.nexusmods.com/skyrim/

**Comment by iamtiz** [comment]
Hi, can you attach a screenshot please?

**Comment by KenshinRyuu** [comment]
![image](https://user-images.githubusercontent.com/44085305/46865390-3de45300-cdd2-11e8-96be-7152b17991dc.png)
Honestly, I just want to know if I need to change Chrome's settings, it's the site acting up, or what ever because it's making it hard to bworse the site. It just started happening.

**Comment by iamtiz** [comment]
Have you tried disabling some of the plugins/extensions you are using? We can't replicate the issue

**Comment by KenshinRyuu** [comment]
I've turned off all my extensions and the stuff still shows up.
Jonathan.[image: ][image: ]

**Comment by iamtiz** [comment]
Does the issue appear when browsing in "incognito" mode too?

**Comment by KenshinRyuu** [comment]
What do you mean by Ingognito mode???? Is that in Chrome or on the site
itself???
Jonathan.[image: ][image: ]

**Comment by iamtiz** [comment]
It's on Chrome (and other browsers): https://support.google.com/chrome/answer/95464
