### ISSUE TITLE
Open off-site requirements URL in new tab

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#843]
## Bug/error being reported:
When opening an off-site requirement URL it would be useful to open it in an external tab. 

## Steps to reproduce:
N/A

## Actual result:

Suggested by Leonardo2 on the forums https://forums.nexusmods.com/index.php?/topic/7061876-nexus-feedback-thread/#entry64300056

**Comment by iamtiz** [comment]
Done
