### ISSUE TITLE
Download story in website showing a mod I didn't download.

### ISSUE THREAD

**Issue by Alekziee** [Nexus-Mods/web-issues#844]
## Bug/error being reported:
 I was checking the NM website looking for mods for Fallout 4 and I saw one that said I have downloaded it already. I didn't remember doing so , so I checked the download story and it said I did the 10th of this mod. However, I haven't downloaded nor played anything from Fallout 4 since August. I also checked the NMM to check the mods and it's not there. The following images show the mod I supposedly downloaded and the recent activity I had (In which the download of that mod doesn't appear)
![nexus](https://user-images.githubusercontent.com/44144635/46921169-bdc61500-cfac-11e8-88ee-275a5a48a2b3.jpg)
![nexus1](https://user-images.githubusercontent.com/44144635/46921170-bdc61500-cfac-11e8-9d36-c04533284456.jpg)

**Comment by iamtiz** [comment]
Hi, the "updated" column is displaying when the mod has been updated by their authors (so that users can tell if they have the latest version of it, or not). The "Last DL" column is the one you'd want to look to know when you last downloaded a mod
