### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by dmcaaa** [Nexus-Mods/web-issues#845]
## Bug/error being reported:
403 forbidden error

## Steps to reproduce:
Download a mod or vortex

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result
downloading to begin

## Actual result:
403 error

**Comment by iamtiz** [comment]
Hi, what file were you trying to download, and from which server?

**Comment by mrmason** [comment]
Please can you try downloading using the CDN - I am assuming this 403 error comes from downloading from one of the premium servers?

We're replacing the premium servers very soon - so this problem should stop occurring.

**Comment by mrmason** [comment]
Please can you try downloading using the CDN - I am assuming this 403 error comes from downloading from one of the premium servers?

We're replacing the premium servers very soon - so this problem should stop occurring.

**Comment by dmcaaa** [comment]
Thank you for your help. I downloaded vortex using the CDN and it worked. I
installed vortex no problems, but when I click the login button the
following message pops up: This file does not have a program associated
with it for performing this action. Please install a program or, if one is
already installed, create an association in the default programs control
panel.

I went into default programs, but I don't know what file it is under or
what program to associate to it?
