### ISSUE TITLE
Impossible to log in Nexusmods

### ISSUE THREAD

**Issue by KizuVR** [Nexus-Mods/web-issues#846]
## Bug/error being reported:
Can't log in

## Steps to reproduce:
-Press "LOG IN" in the front page
-Enter Username and Password
-Press Enter

## Expected result:
 The page is suppose to refresh and display the front page while logging you in.

## Actual result:
The page is refreshing the " Sign in to Nexusmods" page. Not the front page and you're not logged in.

**Comment by Pickysaurus** [comment]
Thanks for being patient, this is now resolved.
