### ISSUE TITLE
Video publishing option - featured mods

### ISSUE THREAD

**Issue by Dartious** [Nexus-Mods/web-issues#849]
## Bug/error being reported:
The featured mods selection for an uploaded video doesn't save.

## Steps to reproduce:
1. Pick a video on Nexus.
2. Hit "Manage" -> "Edit video information".
3. In the "Publishing options", select the featured mod from the dropdown list.
4. Agree to Terms and Conditions and save video details. 
5. The selection in question does not stick.

## Expected result:
The selected mod displays as the one being showcased in the video and the video, in turn, is added to the mod's page Videos section.

## Actual result:
Nothing, as if no changes were made.

**Comment by iamtiz** [comment]
This should now be fixed
