### ISSUE TITLE
New mod details page not public after content stored successfully

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#850]
https://www.nexusmods.com/skyrimspecialedition/mods/20645
uploaded new translation, made details page. ALl fine as long as I'm in "manage".
After "save" and get "saved successfully" I click "publish" and visit the mod page as user, there is nothing.
see screenshots

![01](https://user-images.githubusercontent.com/40837496/47184092-0887ba00-d32a-11e8-8ad9-e21314618296.jpg)
![02](https://user-images.githubusercontent.com/40837496/47184097-0c1b4100-d32a-11e8-994e-9c2a65417122.jpg)
![03](https://user-images.githubusercontent.com/40837496/47184106-11788b80-d32a-11e8-9074-412ff8b03227.jpg)

**Comment by Dreifels** [comment]
some hrs later:
I login to "manage" again, see the details page as (Screenshot 1)
as you can see on the screenshot left below, the line for transfer date still in on, means, there is a lag or mass of data transferred.
then I try to delete that, what first did not work because the "manage" page does not ome complete, as you see screenshot 2. The bottem with the click for save isn't there.
The I exit, go in someminutes later, and the details page is empty, means it got deleted.
I uploaded a new image, save, exit , control, and that time it was fine, screenshot 3, but then again the lower area withthe buttoms not shown.
After more than 1 hr work I got ist fine, at least.
![aaaa](https://user-images.githubusercontent.com/40837496/47189393-9e2c4500-d33c-11e8-8387-469942a7b73f.jpg)
![ddd](https://user-images.githubusercontent.com/40837496/47189397-a08e9f00-d33c-11e8-8156-469103bb68cc.jpg)
![eee](https://user-images.githubusercontent.com/40837496/47189399-a2586280-d33c-11e8-8db3-2ae17fa5a7b0.jpg)
![fff](https://user-images.githubusercontent.com/40837496/47189400-a3898f80-d33c-11e8-886a-9bbd5bfa5fb5.jpg)

**Comment by iamtiz** [comment]
Is this the same issue you described in this other repor: #835 ?

**Comment by Dreifels** [comment]
yes, it is related also to "Detailled Description not shown but got stored successfully", i thas different kinds how it is. The issue is not always same. sometimes I get not the page after "publish", but had it fine before, sometimes I have it while i be in "manage", als also it happens both, if I move/past from another page to mine "details", and the last was even when I past it from my pc.

My last workaround (after 45 min work) was, that I store and save and publish first a dummy text only, then "manage" again, put in the image, save, "publish", again "manage", add the right text, and so on.

I suspect that it is related to server load and/or overloading of bandwidth, as https://forum.... has BIG lags often and also mass of timeouts. (I posted here two screenshots of timeouts as sample, such I get several times day for day) The only working *relative* proper that are the mod pages, all w/o subdomain "forum." "manage" a mod page, expecially set up a new one, sometimes has big lags between click "save" and respond "successful". 

As this all had not been weeks go, earlier all was fine and fast, I believe it is related to the Nexus server down which was some weeks ago (I remember, that I got a message related and could not access for ~ 1-2 hrs. that time) .

**Comment by iamtiz** [comment]
Yes, it looks like all the issues come down to connection problems. Are you using any VPN, or have experienced similar problems with other websites?

**Comment by Dreifels** [comment]
1) no issue with any other connection, also no other issues with nexus. 
2) it's not my access or internet provider, as you can see, it is just the system or way *after* frankfurt to cloudfare. As Frankfurt is the main star for international routing, it is probability 99,9% that this is either caused by your hosting provider for forum.... and related operations, or it is a server issue (bandwith limit, CPU oveload), ins any case, you need to asky our hosting provider to investigate this.  
(Im doing professional IT hosting service for now 30 yeras and all I on check from here points to your responsibility. These are timeouts, and timeouts may have only these two reacons: server hardware or server connection resp. routing problem until next hop)

**Comment by Dreifels** [comment]
same issue again, lot of content in "details", several with "spoiler". All saves successfully. Shown fine if I click on "manage". After click on Publish there ALL content no longer shown. Browser refresh and new login etc. does not help. Looks like your system can't handle much content Login againand again click on "manage" then again all is shown fine.. Cheked from different systems. No one can see the content stored.

**Comment by Pickysaurus** [comment]
If this problem is still occurring please let us know by raising a new issue. 

I also noted you have images as raw PNG data, please avoid doing this as it causes problems saving.
