### ISSUE TITLE
Forbidden Error 403 nginx/1.11.5

### ISSUE THREAD

**Issue by us99506** [Nexus-Mods/web-issues#851]
When I try to download mod for example SSE fixes manually, I get Forbidden Error 403 with this in my browser:  http://fs-us.nexusmods.com/files/1704/(Skyrim%20Special%20Edition)%20SSE%20Fixes%20v3%20for%20SSE%201.5.50-10547-3-1-5-50.7z?md5=jt9YqkM4FLzN6eP5PLetTw&expires=1539933690

When I try to download with Manager I get "error transferring"  that file failed to download after 4 attempts.

I can down load if there is a vortex option but SSE fixes and others do not have that option.

I was able to download with no issues on some files on 10/17 but received the error on others.  I had no issues on 10/16.

I tried to manually download for Fallout 4, same issue.....

Please help

**Comment by iamtiz** [comment]
Have you tried changing the download location to another server?

**Comment by us99506** [comment]
That worked thanks


Thanks, Paul
-------- Original message --------From: Tiz <notifications@github.com> Date: 10/29/18  10:54 AM  (GMT-06:00) To: Nexus-Mods/web-issues <web-issues@noreply.github.com> Cc: us99506 <pggg65@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Nexus-Mods/web-issues] Forbidden Error 403 nginx/1.11.5 (#851) 
Have you tried changing the download location to another server?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nexus-Mods/web-issues","title":"Nexus-Mods/web-issues","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Nexus-Mods/web-issues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iamtiz in #851: Have you tried changing the download location to another server?"}],"action":{"name":"View Issue","url":"https://github.com/Nexus-Mods/web-issues/issues/851#issuecomment-433963854"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Nexus-Mods/web-issues/issues/851#issuecomment-433963854",
"url": "https://github.com/Nexus-Mods/web-issues/issues/851#issuecomment-433963854",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Nexus-Mods/web-issues] Forbidden Error 403 nginx/1.11.5 (#851)",
"sections": [
{
"text": "",
"activityTitle": "**Tiz**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@iamtiz",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 851,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Nexus-Mods/web-issues\",\n\"issueId\": 851\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Nexus-Mods/web-issues/issues/851#issuecomment-433963854"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 398330392\n}"
}
],
"themeColor": "26292E"
}
]
