### ISSUE TITLE
Changelog - version number sorting

### ISSUE THREAD

**Issue by andrelo1** [Nexus-Mods/web-issues#852]
## Bug/error being reported:
Version numbers in changelog are sorted in strange order.

## Expected result:
Version 1.40
Version 1.304
Version 1.303
Version 1.302
Version 1.301
Version 1.30

## Actual result:
Version 1.304
Version 1.303
Version 1.302
Version 1.301
Version 1.40
Version 1.30

**Comment by iamtiz** [comment]
Hi, is the order still displaying incorrectly for you? It's looking ok on our end, at the moment

![screenshot_2018-10-22 go to bed](https://user-images.githubusercontent.com/3407947/47283845-d81b7680-d5dc-11e8-94c2-de2bca24dada.png)

**Comment by andrelo1** [comment]
I changed version numbers recently :), now they go in correct order. I added dot after each digit.
If I change them back the order will be incorrect.
How it looked before:
Version 1.304
Version 1.303
Version 1.302
Version 1.301
Version 1.40
Version 1.30

I can change back and take screenshot if it is needed.

**Comment by iamtiz** [comment]
Ah, I see. We suggest you stick to the current way of versioning you are using (or a similar one, like 1.3.4, etc.), as it's more standard and less ambiguous. We treat versions with this logic 1.11 > 1.10 > 1.9, but some users could mean 1.9 as 1.90.
