### ISSUE TITLE
Thumbnails Not Updating

### ISSUE THREAD

**Issue by blchk** [Nexus-Mods/web-issues#854]
## Bug/error being reported:
Hello,

there appears to be an issue with the thumbnails of my mods. The primary image for two of them (https://www.nexusmods.com/dragonageinquisition/mods/2374 and https://www.nexusmods.com/dragonageinquisition/mods/2359) was changed over 24 hours ago. Both images are "starred" and placed at the very front of their respective assortment of images. Yet the thumbnails that are displayed for them while browsing categories are still not updated. I'm not sure whether the caching requires more time; a related note mentions a time frame of a couple of hours, which I took to mean anything below 24.

My Nexus-username: srnk

Thank you.

## Steps to reproduce:
1. Browse e. g. https://www.nexusmods.com/dragonageinquisition/mods/?BH=0 and sort by "Date published" or view my profile: https://www.nexusmods.com/users/53219096?tab=user+files
2. "Darkened Samite is Black" and "Great Bear Hide is Black" should have different thumbnails, not the comparisons that are displayed.

## Expected result:
See above.

## Actual result:
See above.

**Comment by blchk** [comment]
Looks like everything's displaying correctly now. Perhaps the thumbnails take several days to update, after all. I don't know. In any case, this can be closed.

**Comment by iamtiz** [comment]
Hi, we found and fixed an underlying issue, and also manually fixed all the entries affected by the bug, last Friday. 
There were other occurrences of the issue that happened during the weekend, though. 
We sent another patch today, and will monitor to see if it fixes the problem for good. 

While thumbnails may take some time to be refreshed everywhere on the site, this shouldn't take more than an hour in the worst case scenario
