### ISSUE TITLE
Bug Reports aren't expanding

### ISSUE THREAD

**Issue by lolzcalvin** [Nexus-Mods/web-issues#855]
## Bug/error being reported:
Navigating to bugs tab from any other tabs causes every bug report to not expand when you click on any one of them. However, refreshing the page where the bugs tab is active fixes the issue. This happens to any mod's page.

## Example walkthrough:
1. simply go to a mod's page, e.g. [Ak5C - A Nordic Relic](https://www.nexusmods.com/fallout4/mods/28418?tab=description)
2. now navigate to bugs tab
3. clicks on any one of the bug reports
4. the bug report doesn't expand
5. refresh the page while the bugs tab remains active
6. all good.

## Expected result:
Bug report should expand when being clicked on, be it navigated from other tabs or not.

## Actual result:
The bug reported above.

**Comment by iamtiz** [comment]
Fixed
