### ISSUE TITLE
There was an error while creating a comment thread

### ISSUE THREAD

**Issue by Moojuiceman** [Nexus-Mods/web-issues#857]
On the permissions tab for one of my mods, [INIfier](https://www.nexusmods.com/site/mods/30), when selecting either "A single comment topic and no discussion tab" or "A single comment topic and a discussions tab" and trying to save, a popup appears that just says "There was an error while creating a comment thread"

![image](https://user-images.githubusercontent.com/7610940/47593128-1b277200-d96e-11e8-8dfe-6971197825cf.png)

![image](https://user-images.githubusercontent.com/7610940/47593182-4611c600-d96e-11e8-8fca-d3ddf34812f9.png)

Selecting "Just a discussions tab" or "No comments" works normally.

**Comment by iamtiz** [comment]
Hi, there was a problem with the game forum not properly set for the "Nexus Mods" game-site. Could you try to change the commenting option again, and see if it's working correctly now? It should :)

**Comment by Moojuiceman** [comment]
Yep, working now. Seems odd that is was a problem with the parent 'Nexus Mods' option as I've seen [another mod](https://www.nexusmods.com/site/mods/21) in the same categories that had it working. Maybe that was set up before this issue started and existing comment threads weren't affected?

Either way this instance is fixed, so I'll close it.
