### ISSUE TITLE
Are your ads serving (what Avast is calling) HTML:DropBox-B?

### ISSUE THREAD

**Issue by quadraphone** [Nexus-Mods/web-issues#858]
## Bug/error being reported:
When I open a Nexusmods link in a new tab (Chrome) from a Nexusmods site, I get a warning about malware attempting to infect my computer - something called HTML:DropBox-B [PHISH], according to Avast - see screenshot.

## Steps to reproduce:
When I open a Nexusmods link in a new tab (Chrome) from a Nexusmods site, I get a warning about malware attempting to infect my computer - something called HTML:DropBox-B [PHISH], according to Avast - see screenshot.

**Comment by quadraphone** [comment]
![nexusmods com 2018-10-28_17-03-49](https://user-images.githubusercontent.com/22685164/47623018-f9e39480-dad9-11e8-95a2-0c3c2ace01e0.png)

**Comment by iamtiz** [comment]
Hi, we cannot tell at the moment if the issue is on our (ad provider's) end, or not.
We suggest that you run 'Spybot' (https://www.safer-networking.org/products/spybot-free-edition/?table) and see if the problem is elsewhere
