### ISSUE TITLE
Website functionality on tablet

### ISSUE THREAD

**Issue by Dartious** [Nexus-Mods/web-issues#859]
A couple of weeks ago something had happened to Nexus, what effectively broke some of its functionality when accessing the website from tablet (3rd gen iPad, iOS 9.3.5 Safari). The issues in question include and are probably not limited to:
a) being unable to use "Reply" feature on the mod page comments and in forum section (clicking the button plays the animation but doesn't produce any result; "Report" right next to it is working just fine);
b) being unable to add new topics in the forum section (attempting to do so leads to a new page with "Error: Page not found" message);
c) being unable to upload images (the button is not active, doesn't even play the click animation; video upload appears to be in order);
d) first few mod-related images which used to be displayed in "preview mode": downscaled and aligned horizontally at the top, – now appear in their original size one after the other aligned vertically, taking up quite some space on the page.

1. Open the mod page on a specified device (or any mobile device, I assume);
2. Try to reply to a comment/forum topic, create a new topic yourself, upload an image.
3. Witness the bugs described.

Expected result:
Unrestricted mobile website functionality.

Actual result:
A whole lot of limitations.

**Comment by Dartious** [comment]
Additionally, having logged out of my account on the aforementioned tablet, I can no longer sign back in: the gear meant to represent the loading progress for the «Log in» button on the login screen keeps spinning, the button never appears as the page never loads fully and thus I'm unable to send my credentials and enter. 
I've cleared out cookies and website data to no avail.

**Comment by Pickysaurus** [comment]
Hi @Dartious 

The problem your experiencing sounds like your browser is blocking the Javascript our site requires to operate properly. Please check any security/privacy settings that may be causing this. 

This may help for iOS: http://osxdaily.com/2012/11/18/disable-javascript-safari-ios/
And for Android: https://www.youtube.com/watch?v=3SS-9D7URBI
