### ISSUE TITLE
I can't find a way to check my notifications on desktop.

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#86]
In the mobile layout, clicking the "Menu" button opens a panel that has a "Notifications" button (though the button doesn't show an unread count -- should I file an issue?).

In the desktop layout, there is no apparent button or other readout for notifications. I can access my forum correspondence, but not notifications about files I'm tracking, comments on my content, and so on.

Desktop:
![Screenshot of the desktop layout. There are buttons to access my own profile, my site settings, and my forum correspondence; but no buttons or displays for site notifications.](https://user-images.githubusercontent.com/831497/30762649-ce371402-9fb0-11e7-9668-dfe5609ffaed.png)

Mobile:
![Screenshot of the mobile layout, taken on desktop in a resized browser window. The "Menu" button has been clicked, exposing a pane with buttons for my user profile, site settings, forum correspondence, and notifications. However, the notifications button has no unread count.](https://user-images.githubusercontent.com/831497/30762650-ce3cb560-9fb0-11e7-992c-01ae18cd4c17.png)

**Comment by mrmason** [comment]
It's the 'updates' option in the main grey menu - We could change one or the other to match the same name if it's confusing.

**Comment by DavidJCobb** [comment]
Ah, I see it now.

The name is a problem, but the larger issue is the _placement_. You've grouped it in with _menus_ intended to navigate sections of the site, and it has a very different function; you've grouped it away from the part of the header intended to show details about the logged-in user (including unread forum notifications).

People read the content on a website, but no one carefully pores over the layout and navigation -- not unless they're already hopelessly lost, and even then they'll likely ignore whatever seems irrelevant. At a glance, that grey section is a site nav; why scrutinize it closely enough to even see "Updates," let alone tell what that means, when I'm not looking for a section of the site?

**Comment by Saavaas** [comment]
I had trouble with this too, I thought the feature was removed until coming across this page. 
I agree that having the bell beside the gear in desktop view would be more intuitive, plus it is more familiar.

**Comment by Vyxenne** [comment]
It took me almost half an hour to find it, for two reasons:
1. It is mislabeled- in English, "Updates" does not mean "Notifications;" and
2. As others have observed, it is grossly out of place- it should be at the top-right corner of the page.

**Comment by RavenMind** [comment]
I'd like to echo the above. It was very difficult to find, and it is out of place there. Please consider moving up to top right as mentioned where there are some actual icons, not just a very flat, difficult to navigate conglomeration of menus with nothing to distinguish between them but the text. Thanks. :)

**Comment by iamtiz** [comment]
Assigned #155431620
