### ISSUE TITLE
Files are disabled for this game

### ISSUE THREAD

**Issue by Dalekkar** [Nexus-Mods/web-issues#860]
## Bug/error being reported:

Some mods i try to manually download for stardew valley keeps giving this error messaage

## Result:

![image](https://user-images.githubusercontent.com/37339135/47853607-de5fde80-dda4-11e8-86aa-1db7610f9e2c.png)

**Comment by daish0** [comment]
Having the same issue on FO4 mods for manual download links since like half an hour, or hour.

**Comment by renegadeX48** [comment]
having the same issue for skyrim mods too.

**Comment by dabigone20** [comment]
I've had the same issue with every mod I've tried to manually download this morning. I've tested with Fallout 4, Skyrim, Stardew Valley, and Subnautica.

**Comment by spud29** [comment]
having the same issue i think it's site-wide...

**Comment by daish0** [comment]
It's just getting fixed, should be working again.

**Comment by spud29** [comment]
can confirm it's fixed now

**Comment by iamtiz** [comment]
Fixed

**Comment by renegadeX48** [comment]
i can confirm it's fixed now
