### ISSUE TITLE
Slow downloads from Premium server.

### ISSUE THREAD

**Issue by RaikouTL** [Nexus-Mods/web-issues#861]
I feel legitimately scammed out of my money here. I payed for unlimited download speeds, yet I'm lucky to get 512KB/s. I have already tested if it was my internet, but it's not that. So could you explain why we should pay for this kind of garbage?

Steps I have taken to confirm it's not my internet:
- Called my ISP.
- Resetting my router.
- Windows Diagnostic Tool
- HP Network Fix
Steps I have taken to confirm it's not the computer:
- Turning it off and on again.
- Starting Vortex in administrator mode, while also allowing it through my firewall.
- Disabling my security software.
- Running diagnostics on my disk.
- Defragmenting said disk,

Seriously, I would demand a refund if I could.

**Comment by Pickysaurus** [comment]
Hey there,
If you're still encountering issues, we have some troubleshooting steps here: https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do

Once you have the information requested in that article, please post in the forums and we'll look into it.
