### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by godzslayer** [Nexus-Mods/web-issues#862]

**Comment by Pickysaurus** [comment]
I've afraid you've provided no useful information. 

Try this article for help https://help.nexusmods.com/article/79-why-am-i-getting-an-infinite-loading-wheel-on-the-login-page

**Comment by godzslayer** [comment]
What am I supposed to provide?  I created an account and then couldn't log into it

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 14, 2018 at 10:13 AM, Mike<notifications@github.com> wrote:   
I've afraid you've provided no useful information.

Try this article for help https://help.nexusmods.com/article/79-why-am-i-getting-an-infinite-loading-wheel-on-the-login-page

**Comment by Pickysaurus** [comment]
Please try resetting your password, failing that contact support@nexusmods.com from the email address linked to the account for further help. 

https://help.nexusmods.com/article/95-how-do-i-change-my-password

**Comment by godzslayer** [comment]
I did that it kept telling me my email or password is incorrect even tho they are both correct

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 14, 2018 at 10:18 AM, Mike<notifications@github.com> wrote:   
Please try resetting your password, failing that contact support@nexusmods.com from the email address linked to the account for further help.

https://help.nexusmods.com/article/95-how-do-i-change-my-password
