### ISSUE TITLE
Upload does not complete

### ISSUE THREAD

**Issue by Dreifels** [Nexus-Mods/web-issues#863]
try to upload a relative small file as update for an existing mod. The upload bar (green) is full, but wait more than 15 min and  I get nt the fínish, when click on "save" I get "no file uploaded" - Tried it several times, always same
![0000000](https://user-images.githubusercontent.com/40837496/47971150-dd71ca00-e08e-11e8-95eb-c6888b7a60e1.jpg)

**Comment by Pickysaurus** [comment]
Are you still seeing this issue?

**Comment by Pickysaurus** [comment]
Closed due to no reply.
