### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by yetanotherlogin** [Nexus-Mods/web-issues#864]
## Bug/error being reported:
MSSE reporting Trojan:script/Foretype.A!ml as soon as I click on the manual download button for the latest Arthmoor Darkwater Crossing for Skyrim SE update before the download commences.

## Steps to reproduce:
Go to Darkwater Crossing page
click manual download
Watch MSSE complain every time.

## Expected result:
Download

## Actual result:
MSSE Trojan warning

Using chrome.

**Comment by Pickysaurus** [comment]
False positive
