### ISSUE TITLE
Deleted mod pages should throw a 404 error but do not.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#865]
When a mod page is deleted, the site does not return a 404 Not Found error along with the notice that the page has been deleted. Instead, it issues a 200 OK message. This results in Google (and other search sites) being polluted with mod entries that will never be returned to those pages.

Example here: https://www.nexusmods.com/fallout4/mods/35746

**Comment by Pickysaurus** [comment]
This isn't currently possible on the site framework we are using, but will be addressed when migrating the site in future.
