### ISSUE TITLE
Legacy of the Dragonborn SSE: CTD's at saves during quest  "A Path to the heavens"

### ISSUE THREAD

**Issue by BudPang** [Nexus-Mods/web-issues#866]
## Bug/error being reported:
After progress of already one of the first stages of the quest there was a constant CTD on game save.
According to Wikia's description had the quest set on stage 100. This solved the CTD's but now the quest is stuck on a stage 50 task ("installing the floor"). Any setstage doesn't work.

## Steps to reproduce:
1. Progress through the quest and do other quests or something else during waiting periodes.
2. Save your game at each progress (and in between when waiting time is long, like days).

## Expected result:
Save of the game and then geting back in the game.

## Actual result:
CTD

**Comment by Pickysaurus** [comment]
I'm afraid this tracker is for report related to the Nexus Mods website, please post on the mod page in question where the author/community may be able to help you.
