### ISSUE TITLE
Hidden mods still have thumbnail metadata, which other sites can display

### ISSUE THREAD

**Issue by DavidJCobb** [Nexus-Mods/web-issues#869]
## Bug/error being reported:
A mod that has been hidden by its author still has a `<meta property="og:image" />` tag in its header with an image taken from the mod's images section. Linking to these mods on some websites (such as reddit's mobile site) allows those sites to display that image as a thumbnail despite the mod being hidden on-site. This is a potential privacy concern for mod authors, and would be fixed by not writing that tag to the page's header if the mod is hidden.

I would *assume* that this oversight would apply to mods removed by site staff as well.

## Steps to reproduce:
1. Hide a mod.
2. Link to the mod in a reddit post. ([Example here, but the image in question is a bit risque.](https://www.reddit.com/r/skyrimmods/comments/9xl1f0/realistic_uunp_bodyslide_preset/))
3. View the reddit post using a mobile web browser (or using a desktop browser that has a user-agent switcher set to a mobile user-agent).

## Expected result:
You do not see a thumbnail image of the mod on the reddit post, regardless of your platform and how you're accessing the site.

## Actual result:
You see a thumbnail image of the mod on the reddit post if you load reddit's mobile site. You do not see a thumbnail image of the mod on the reddit post if you load either of reddit's desktop sites (new or legacy).

**Comment by iamtiz** [comment]
Fixed
