### ISSUE TITLE
Tracking Centre only displays the first 20 tracked mods

### ISSUE THREAD

**Issue by LadyMilla** [Nexus-Mods/web-issues#87]
The issue is present in all browsers I use (Firefox 58, Chrome 60, MS Edge) so I exclude the possibility of a browser-related issue. The problem is:

I have 184 pages of tracked mods. No matter which site I open (including the root site), the Tracking centre only displays the 20 most recently tracked mods. Clicking on the page numbers reloads the list (the little spinning gear pops up), but the list still shows the 20 most recent mods (the page number changes correctly to the selected number). None of the other pages are different, jumping to a specific page does not work either.

Also, the 'Show' drop-down menu does not work either. No matter if I pick, 20, 30 or 60 items, only 20 items are shown in the list.

Related report:
https://github.com/Nexus-Mods/web-issues/issues/69

**Comment by verenion** [comment]
Assigned PT#151366627

**Comment by mrmason** [comment]
We've pushed a fix for this - please let us know if there are any more outstanding issues.
