### ISSUE TITLE
[Feature Request] Allow separators(add dates?) at download history

### ISSUE THREAD

**Issue by GioGr** [Nexus-Mods/web-issues#870]
What i basically want i to split my builds and be able to see them at download history so if i want that one i now it starts from this mod to this mod and i can download all these mods.

First idea was to reset(delete) download history but now i thought maybe with separators will be better (or maybe dates or something else).

Thanks :)

**Comment by Pickysaurus** [comment]
This issue has been closed due to inactivity. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
