### ISSUE TITLE
ERROR You are already blocking this tag, but there are no tags under 'Currently blocked tags'.

### ISSUE THREAD

**Issue by wolfgangalejandro** [Nexus-Mods/web-issues#872]
## Bug/error being reported:

Unable to stop blocking previously selected tags.
## Steps to reproduce:

1. Click on 'Change Your Settings' button next to user's avatar.
2. Click on 'Content Blocking' tab.
3. Click on any tag to start blocking it.
4. Click on any other tab, say 'Preferences' for example.
5. Click on 'Content Blocking' tab again and there are no tags under 'Currently blocked tags'.
6. Click on the same tag selected before, error pops up 'ERROR You are already blocking this tag'.
## Expected result:

All selected tags should show inside the box within 'Currently blocked tags' section.

## Actual result:

No tags shown.

**Comment by wolfgangalejandro** [comment]
![screenshot](https://user-images.githubusercontent.com/45464067/49238508-2a169f80-f3c6-11e8-87cc-4eafacb63ec6.png)

**Comment by wolfgangalejandro** [comment]
Deleted my account in order to try again. I suspect specific tags maybe breaking this function. Below I posted a combination of blocked tags that is working 100% so far. If I find the problematic tags combination I will post it also.

![screenshot 96](https://user-images.githubusercontent.com/45464067/49254083-e9328100-f3ed-11e8-92b3-5fd7efff2b49.png)

**Comment by Pickysaurus** [comment]
This issue has also been encountered by hpfan2342 
https://imgur.com/a/CuJqcnF
![image](https://user-images.githubusercontent.com/31670524/51173415-4b1b4d00-18ad-11e9-8cb4-34a630fe595f.png)

**Comment by Pickysaurus** [comment]
This should be resolved. Please reply or open a new issue if it is still happening.
