### ISSUE TITLE
Slower than molasses upload speeds

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#875]
## Bug/error being reported:
Upload of mod files are taking an eternity to upload.  I have 400 Mb/sec download & 20 Mb/sec upload speeds.  Yet it's taking forever to upload a 70 MB mod file to Skyrim SE Nexus.

## Steps to reproduce:
1. Drag a file to the Upload box on the Add A Mod page.
2. Watch as it takes an eternity for the upload to finish.
-->

## Expected result:
Reasonably fast upload of a 70 MB file typical of having 20 MB/sec upload speeds through my ISP

## Actual result:
Still waiting for my file to upload after 15+ minutes.  This isn't even counting the virus scan since the file itself is still uploading to Skyrim SE Nexus.

**Comment by Pickysaurus** [comment]
Are you still seeing this problem?

**Comment by scjohnson1981** [comment]
Off & on, yes.  Speeds have been better recently but there's still issues with upload lag from time to time.  Also, I've noticed an uptick in errors popping up when posting comments/replies on various mod pages.  "Error - Comment siblings not found..." or something to that effect.  Refreshing the page makes the error go away but said error pops randomly from time to time when posting comments/replies on mod pages.  Don't know if it has anything to do with the laggy uploading times I see from time to time but thought I'd mention it anyway.

**Comment by Pickysaurus** [comment]
I'm going to close this for now. If it gets super slow again, feel free to comment or open a new report. We are doing some background work on the uploader so it may improve in the near future.
