### ISSUE TITLE
When no new daily mods are available the tab under More Mods no longer switches to the New This Week/Latest tab

### ISSUE THREAD

**Issue by chocmake** [Nexus-Mods/web-issues#876]
## Bug/error being reported:
Opening a main mod page which has no new mods created for that day no longer automatically switches the tab under 'More Mods' to the New This Week or Latest tabs if a user isn't logged into the Nexus site.

Previously the behavior at the beginning of the Nexus redesign was to switch the default tab to the next tab which had results (either New This Week or if none for that week then the Latest tab). This was a nice QoL feature that also meant mods were still getting displayed by default when none were made that particular day/week.

## Steps to reproduce:
1. Be logged out of your Nexus account.
2. Open a mod page with little activity and no mods for that day (at the time of writing the [MGSV:GZ page](https://www.nexusmods.com/metalgearsolidvgz/) for example).
3. Observe under the 'More Mods' heading the default active tab is 'New Today' despite there being no results.

## Expected result:
The tab under 'More Mods' switching by default to the 'New This Week' if no mods for 'New Today' are available, or if none are available for the week alternatively switching to the 'Latest' tab. 

## Actual result:
The default tab has changed to remain at 'New Today' even when there are no results.

> Note: issue updated 2019-04-20 to reflect more reliably reproducible behavior (see below comments).

**Comment by chocmake** [comment]
Checking today the tabs appear to be back to the original behavior which is great. Was this fixed between when I reported it and today? Didn't see any update to this issue so wasn't sure if it was potentially some other explanation.

**Comment by chocmake** [comment]
Checking today on [this hub page](https://www.nexusmods.com/metalgearsolidvtpp) the same thing is occurring. Screenshot:

![screenshot](https://user-images.githubusercontent.com/34178938/52174148-ee43f000-27e3-11e9-8260-c78be532f6d4.png)

**Comment by chocmake** [comment]
@iamtiz Thoughts?

**Comment by chocmake** [comment]
Finally discovered what reliably reproduces this behavior: if you are logged out it reverts to the first tab even if the counter is `0` (as seen in above screenshot), while if one is logged into a Nexus account it correctly displays the second tab.

Using Firefox fwiw.

**Comment by Pickysaurus** [comment]
This done seem to happy as you described, although I'm unsure why you're browsing without being logged in if you have an account. 

Reopened issue.

**Comment by chocmake** [comment]
> I'm unsure why you're browsing without being logged in if you have an account.

I check the site in other browsers and also the site logs me out automatically after some weeks of the browser I primarily use (enough that at one point I manually edited the cookie expiry to avoid this but that cookie must have been overwritten at some point).

It was actually due to Nexus' auto logging out that I noticed what reliably reproduced it in the post above.
