### ISSUE TITLE
Feature Request: Block Creation Club content

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#878]
We seriously need the ability to block Creation Club-tagged content on Nexus.  I do not care for the Creation Club whatsoever & will not use it period.  We have the ability to block various other tags such as Nudity/Adult Content/etc but for whatever reason, we can't block Creation Club-tagged content in our Global Preferences.  Please consider adding the ability to block Creation Club-tagged content across the Nexus sites.  I could care less about said content & I'm sure there are many others who would agree/appreciate having the ability to block/filter out Creation Club content across the Nexus since said content is not everyone's cup of tea.  Thank you.

**Comment by iamtiz** [comment]
Hi, the "Creation Club content" tag is already blockable in your account preferences: https://www.nexusmods.com/users/myaccount?tab=content+blocking.

As this tag only applies to FO4 and SkyrimSE, you need to select one of these two games from the dropdown, for it to appear.
