### ISSUE TITLE
Link "turn off ads permanently" points to premium instead of supporter

### ISSUE THREAD

**Issue by firda-cze** [Nexus-Mods/web-issues#879]
## Bug/error being reported:
Your ad-block message is a lie.

## Steps to reproduce:
Firefox + uBlock Origins, go anywhere and follow the picture:
![obrazek](https://user-images.githubusercontent.com/11376520/49962318-3eee4980-ff15-11e8-93d5-e48af84505ec.png)
(click on the link to see the offer, which is already x2 - $2 to $4.00 to find out that *permanent* is for 50 libra ~ 5% of my month salary, which is more than what I can buy Fallout 4 + ALL DLCs for but less when 50% sales-off is in place (which I used)... not that much, will consider, but for now I am simply turning ad-block off for nexus. to be fair... you are not!!!

(and I am even fair enough to post this under my firda-cze / firdacz / firda account with a picture of my face)

## Expected result:

Be fair if you want me to be fair.

## Actual result:

Lie, LIE, LLLIIIIEEEEEEEE!!!!

**Comment by Pickysaurus** [comment]
You have selected the Premium Membership, our Supporter membership is the one the text refers to.

**Comment by firda-cze** [comment]
I have just clicked on the link provided (the "turn off ads permanently"),
so, maybe you should change the link to point where it should.

BTW, paid that L60 (another surprise: tax added).
Feel free to close this one.

**Comment by Pickysaurus** [comment]
Thanks :) I'll leave this open for now so the site development team can see
the potential link issue.

**Comment by iamtiz** [comment]
fixed
