### ISSUE TITLE
Feature Suggestion: Optional 'Recent Changes' section on main page

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#88]
In the header bit of the new layout that has Requirements/Permissions/Translations/Donations it might be nice to have a 'Recent Changes' drop down that shows the most recent changelog and date of last update. Hopefully would encourage players to actually read the update notes a little more often :P

**Comment by iamtiz** [comment]
Assigned #155936696

**Comment by iamtiz** [comment]
We added the changelog to the default ("about this mod") tab in mod pages

**Comment by Pickysaurus** [comment]
Thanks for implementing this change, however the changelog displayed is in reverse order
