### ISSUE TITLE
Slow Site Functions (modals)

### ISSUE THREAD

**Issue by TechAngel85** [Nexus-Mods/web-issues#881]
## Bug/error being reported:
Some of the functions on the site are painfully slow. This includes just about anything to do with the pop-out modals: updating Bug Report status, moving comments to Bug Reports, closing Bug Reports, etc. I can often do a task and then go get a cup of tea while I wait for the site to respond to the request. Most of the time it will take anywhere between 1-3 mins. I know this doesn't sound long, but websites should function within milliseconds/seconds, not minutes. Sometimes the request seems to time-out because the modal never goes away. Refreshing the page will usually result in seeing that the function worked, it just never refreshed. This has been an issue ever since the redesign of the site launched.

This is happening on a beefy Windows 7 machine using the latest version of Chrome and a 50Mbps connection. Only Nexus Mods seems to have this issue as other sites using modals are fast and responsive.

**Comment by iamtiz** [comment]
Hi, is this still happening for you? Can you point out a couple of examples where it happens? Thanks!

**Comment by Pickysaurus** [comment]
Closed as there has been no follow up. If the problem persists, please open a new issue.
