### ISSUE TITLE
Textbox Focus on Modals

### ISSUE THREAD

**Issue by TechAngel85** [Nexus-Mods/web-issues#882]
## Bug/error being reported:
The focus for textboxes does not change properly with modals when the focus is registered to another textbox on the page.

## Steps to reproduce:
1. On a mod page, click in the "Search" field and type something. Then click the "x" to close the search, but don't click anything else!
2. Now click on the "manage" button on a post to move it to "Bugs".
3. In the pop-up modal name field, attempt to type a name.

## Expected result:
To be able to type in the textbox on the modal.

## Actual result:
The typed characters appear in the "Search" field because the focus as not properly moved to the modal. Thus, the modal is hidden because the page refocuses to the "Search" box.

This is on Windows 7 using the latest version of Chrome.

**Comment by Pickysaurus** [comment]
I can confirm the developers are aware of this issue with the quicksearch box. Thanks!

**Comment by theFuzzyWarble** [comment]
It is still and issue and annoying one too!

**Comment by Pickysaurus** [comment]
Moved this to our internal bug tracker.
