### ISSUE TITLE
posts tab formatting broken

### ISSUE THREAD

**Issue by damandingmods** [Nexus-Mods/web-issues#885]
## Bug/error being reported:

The layout of the posts tab is badly broken. Looking at other issues there is a similar issue here: [https://github.com/Nexus-Mods/web-issues/issues/738]. Looks like a site moderator may need to identify and alter the post with broken tags.

DAmanding (nexus name) reporting on behalf of Kinggath
## Steps to reproduce:

Simply view the first page of the comments page on Sim Settlements: [https://www.nexusmods.com/fallout4/mods/21872?tab=posts](url)

**Comment by iamtiz** [comment]
Assigned #162856587

**Comment by iamtiz** [comment]
fixed
