### ISSUE TITLE
Text in [CODE] Tags Is Being Reformatted on Encountering Apostrophes

### ISSUE THREAD

**Issue by Vyxenne** [Nexus-Mods/web-issues#886]
## Bug/error being reported:
Whenever text inside of [CODE] Tags contains an apostrophe, the website spuriously toggles on/off pink colored text

## Steps to reproduce:
1. On a mod's "Posts" page, paste my load order between [CODE] tags so that the column spacing is consistent
2. Observe that several of my plugin (esp) files contain apostrophes in their names
3. Press "Submit" button to complete my post
4. Observe that the website editor has "toggled on" Pink Text on the first apostrophe
5. Observe that the website editor has "toggled off" Pink Text on the second apostrophe
6. Observe that the website editor has "toggled on" Pink Text on the third apostrophe
7. Observe that the website editor has "toggled off" Pink Text on the fourth apostrophe
8. Bite the bullet and artificially change my load order text by manually removing the apostrophes, making it impossible for readers to cut-n-paste those esp files into a search engine to find those mods

## Expected result:
I expected the website editor to treat apostrophes like it treats all other keyboard characters, not spontaneously render the text goofy-looking and difficult to understand by changing the text color every time it encounters a particular character

## Actual result:
(See above Title, Issue Description and Steps to Repropduce)
Here is my load order to assist you in duplicating the issue. The apostrophes are on lines 47, 94, 173 and 179:
[NexusBugReportPinkText.txt](https://github.com/Nexus-Mods/web-issues/files/2707902/NexusBugReportPinkText.txt)

**Comment by iamtiz** [comment]
Hi, I can't seem to replicate the behaviour you described on the website. Can you provide a link to the mod page where this is happening? 

![screenshot_2018-12-27 test1](https://user-images.githubusercontent.com/3407947/50479964-1f552780-09d1-11e9-88bf-929aca081583.png)

**Comment by Vyxenne** [comment]
The error occurred in a PM, not on a mod's posts page as I erroneously reported. I don't know how to link to a PM. If you would like to send me a Nexus PM I'll be glad to paste that load order into it between [code] tags so you can touch and feel it yourself.

Here are screenshots from the PM, only the lines that show the erroneous pink formatting toggle upon any apostrophe:
![loadorderpinkout](https://user-images.githubusercontent.com/33111596/50533993-342dda00-0afb-11e9-981a-1fbe20e080e8.png)

**Comment by iamtiz** [comment]
Unfortunately private messages are handled by the forum, which runs on an external piece of software. I'm not sure there's a workaround at the moment
