### ISSUE TITLE
Cannot download mods; file available soon message

### ISSUE THREAD

**Issue by sbdavies** [Nexus-Mods/web-issues#888]
## Steps to reproduce:
Click on any FO3 mod and look for download link(s)

### Example:
1. Search Nexus for "CRL9000 Sound Modification V046 - DLC Edition"
2. Look at "Main Files" 
3. Message appears under file description ("The file is currently being uploaded to our file servers and it will be ready to be downloaded soon.")

## Expected result:
See and click Download link 

## Actual result:
No Download link
![capture](https://user-images.githubusercontent.com/11233483/50784244-1b4fc200-127b-11e9-99d9-1410bd84ac8d.PNG)
![capture2](https://user-images.githubusercontent.com/11233483/50784252-1ee34900-127b-11e9-8f6f-a59d6741457c.PNG)-->

**Comment by SaikouDesuka** [comment]
Same problem on Skyrim SE

**Comment by mrmason** [comment]
should be working again now!
