### ISSUE TITLE
Font Anti-Aliasing issue with non chromium browsers

### ISSUE THREAD

**Issue by RoyBatty64** [Nexus-Mods/web-issues#889]
## Bug/error being reported:
Font Anti-Aliasing not working in non-chromium browsers

## Steps to reproduce:
View website with Palemoon, or another browser like Firefox ESR or Waterfox. Didn't check Opera, but possibly there too. Chromium has kludges built in to force AA on websites.

OS is Windows 7, not sure if related.

**Comment by Pickysaurus** [comment]
I'm not exactly sure what you mean. Here's a screenshot of Palemoon vs Chrome and they look basically the same. 
![image](https://user-images.githubusercontent.com/31670524/55385891-1327bb80-5526-11e9-9191-767e98a8c161.png)

**Comment by RoyBatty64** [comment]
Should reopen this, scroll the page down and the issue appears.

**Comment by Pickysaurus** [comment]
Reopened as requested. Still cannot replicate the issue.

**Comment by Pickysaurus** [comment]
Related forum thread.

https://forums.nexusmods.com/index.php?/topic/7106491-nexus-website-text-issues/
