### ISSUE TITLE
Hidden mods do not display removal reason

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#89]
Example: 

https://www.nexusmods.com/skyrimspecialedition/mods/6194/?

https://rd.nexusmods.com/skyrimspecialedition/mods/6194/?

Removal reasons (when the author bothers with them) are critical for figuring out wtf is going on, this is a major problem. 

(P.S. it would also be nice if there were removal reasons for mods that have been hidden by staff!)

**Comment by verenion** [comment]
Assigned PT#151366719

**Comment by iamtiz** [comment]
Fixed
