### ISSUE TITLE
Image Metadata on pages without a featured image

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#890]
## Bug/error being reported:
In some situations, posting links to pages that do not have image metadata (e.g. articles) the first image on the page is grabbed, which ends up being the Patreon logo.
![image](https://user-images.githubusercontent.com/31670524/51323544-6da19780-1a60-11e9-815e-7744aaf0f2cb.png)
https://www.nexusmods.com/skyrimspecialedition/articles/710

## Suggested change:
Use a placeholder Nexus Mods logo (such as the one below) as a default image metadata unless another is provided. 
![nexus_mods_logo_mark](https://user-images.githubusercontent.com/31670524/51323882-44cdd200-1a61-11e9-9653-55cd4c9b0bd6.png)

Reported by JosephRussell#6683 on Discord

**Comment by iamtiz** [comment]
Fixed, a standard image (https://www.nexusmods.com/Contents/Images/nexus_sites.jpg) will be included in the meta tags, if another one is not set
