### ISSUE TITLE
Comments Section - Jumplist and returning to page 1 in error

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#891]
## Bug/error being reported:
Replying to a comment resets page to page 1 and breaks the jump list for pages.

## Steps to reproduce:

1. Move to a comment section that has multiple pages.
2. Submit a reply to a comment on page 2+
3. You will be pushed back to page 1 and the "Jump" menu will have no pages listed. 

![image](https://user-images.githubusercontent.com/31670524/51633053-aeaa1800-1f48-11e9-97ee-d904bfe25710.png)

## Expected result:

Page does not change on reply and/or jump menu continues to work. 

## Actual result:

Forced back to page 1 with non-functional jump list. 

Reported by Kinggath (kinggath#3794) on Discord

**Comment by iamtiz** [comment]
fixed
