### ISSUE TITLE
Hidden Mod Fixes and Enhancements

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#892]
When you set a mod to hidden:

- You can set the hidden message text but you are provided with a textbox control instead of a textarea.
- You can set the hidden message text but you can't use BBCode to, for example, link to another mod. Ideally, you should be able to do a timed redirect to another mod page, if that mod is on the Nexus.
- You can't edit the hidden message text without first making the mod visible and setting the mod to hidden again, and when you do that, the hidden message text isn't restored to the editing control.

When you visit a hidden mod page:

- The hidden message box is labeled "Hidden file" but should be "Hidden mod." The text "This mod has been set to hidden by its author" also does not end with a period.
- The hidden message text uses a white font color on a bright orange background. This is hard to read.
- The hidden message text uses a 12px font. This is just barely legible.

As an enhancement, I would suggest showing more than just the hidden message and ads; also show a slider for similar mods. The hidden mod page is a bit barren. It should be useful.

**Comment by Duhenk** [comment]
the original files from the bbb's are not there, all games play fo4, skyrim, and oblivion. This "new" webside from nexus is all most as bad as steam. Why are the there?

**Comment by iamtiz** [comment]
We implemented some of the changes:
- The hidden message can now be edited (unless the mod has been hidden by the staff)
- We replaced the input field with a text area
- We renamed all the "file" occurences to "mod", in the pop-up and messages
- We are now also showing the date the mod was hidden (only from now on, as the information wasn't stored before)
- The font size has also been increased in the message panel
