### ISSUE TITLE
link back from mod forums thread to mod download page not working due to Nexus URL changes 

### ISSUE THREAD

**Issue by abitoftaste** [Nexus-Mods/web-issues#894]
## Bug/error being reported:

[link back from mod forums thread to mod download page](https://forums.nexusmods.com/index.php?/topic/806063-silt-striders/?p=6451061) not working due to Nexus URL changes happened after mod release (and I think the problem is for any old enough mod)

Problem is first post is not editable by mod author.
I think obsolete links could be easily upgraded directly in nexus database, or at least you should make first post editable by mod author so link back to the mod could be fixed by mod authors

Or, you could make some redirect rules to remap old URL format
to new one in the HTTP server

e.g. remap old link format
https://gamename.nexusmods.com/mods/42267
to current
https://www.nexusmods.com/gamename/mods/42267

**Comment by Pickysaurus** [comment]
Unfortunately there's no reliable way to update all the old forum threads at the moment. I have updated the one your reported.
