### ISSUE TITLE
Mod tags automatically becoming reset after mod author rejects them

### ISSUE THREAD

**Issue by AlexejheroYTB** [Nexus-Mods/web-issues#895]
## Bug/error being reported:

Some mod tags become reset (grey) after being manually rejected by a mod author (red).

## Steps to reproduce:
This is not reproducible every time, I have managed to reproduce it for [subnautica/16](https://www.nexusmods.com/subnautica/mods/16) and [subnautica/113](https://www.nexusmods.com/subnautica/mods/113), but i can no longer reproduce it for [subnautica/113](https://www.nexusmods.com/subnautica/mods/113)

1. Go to a mod page
2. Reject some tags

## Expected result:

All of the tags remain rejected

## Actual result:

Some tags are reset after a certain period of time (for me it's always been the same tags)

![](https://cdn.discordapp.com/attachments/474196645077319680/539525599081922560/unknown.png)

**Comment by Pickysaurus** [comment]
After discussing this issue, we feel that there isn't a good use case for resetting tags as if you mark them as rejected it's unlikely there's a good reason to allow users to vote on them again.
