### ISSUE TITLE
Suggestion: Add view for all mods with 'Update Available'

### ISSUE THREAD

**Issue by ViolentQuiche** [Nexus-Mods/web-issues#897]
It would be great to be able to see (either with a filter or a new view) all of your downloaded mods with an available update. The current 'Update Available' label seems to only appear if the mod is shown in the main /Mods view.

**Comment by Pickysaurus** [comment]
This issue has been closed due to inactivity. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
