### ISSUE TITLE
Moderate Menu cuts off for last bug comment

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#899]
## Bug/error being reported:
Drop down menu is cut off for last bug.

![image](https://user-images.githubusercontent.com/31670524/52561599-c7914500-2df3-11e9-9721-df1239772795.png)

The "From PMs" option is inaccessible, appears to be the container the comments are in blocking it from showing.

**Comment by iamtiz** [comment]
fixed
