### ISSUE TITLE
Editing a mod description with complex formatting breaks the formatting

### ISSUE THREAD

**Issue by JustHereToReportABug** [Nexus-Mods/web-issues#90]
**URL:** any mod URL, but mine was https://rd.nexusmods.com/fallout4/mods/18946
**Bug/error being reported:** Editing a mod description with complex formatting breaks the formatting
**Steps to reproduce:** Create a mod description on the old site with rich text formatting including BBCode etc.
**Expected result:** New site preserves old site's formatting when making minor edits to a mod description
**Actual result:** New site does not preserve formatting

So I spent about an hour fixing my mod description page after I edited it from the rd.nexusmods.com site. 

Most of the line breaks disappeared and all my text was jumbled together.  I think there is something different about how the two sites parse BBCode or HTML or whatever rich text input format you are using.

**Comment by verenion** [comment]
I've taken your BB Code and tried to replicate this on an unpublished mod on the old site and checked it on the RD site and the formatting remains the same. Can you still replicate this issue?

**Comment by verenion** [comment]
Assigned PT#151514775

**Comment by verenion** [comment]
A fix has been pushed for this issue.
