### ISSUE TITLE
Uploaded zip files getting excess numbers added to filename

### ISSUE THREAD

**Issue by shaggy1395** [Nexus-Mods/web-issues#900]
## Bug/error being reported:
Uploaded zip files getting excess numbers added to filename.  Since this breaks the mod's compatibility with the game in question (Farming Simulator 19), users who download the file are forced to manually rename the file for it to work.

## Steps to reproduce:
1. Step 1 - Generate mod file named MultipleMissions.zip
2. Step 2 - Upload as new mod
3. Step 3 - File downloaded from nexusmods site ends up as MultipleMissions.zip-54-1-0-1550212641.zip

## Expected result:
The file name should remain as uploaded, MultipleMissions.zip

## Actual result:
The filename is unexpectedly changed to MultipleMissions.zip-54-1-0-1550212641.zip without the uploader having control over this result.

**Comment by Pickysaurus** [comment]
This is something we are aware of and only currently impacts Farming Simulator mods. As a short term fix I would suggest "double zipping" your files by places the ZIP inside a RAR or 7z archive.

**Comment by fireundubh** [comment]
@Pickysaurus 
> This is something we are aware of and only currently impacts Farming Simulator mods. As a short term fix I would suggest "double zipping" your files by places the ZIP inside a RAR or 7z archive.

Also affects Skyrim Special Edition and Kingdom Come mods.

**Comment by Pickysaurus** [comment]
Perhaps I wasn't entirely clear. The numbers are added to all downloads but it only causes issues in Farming Simulator. Unless there an additional problem? @fireundubh

**Comment by fireundubh** [comment]
> The numbers are added to all downloads

I assume you mean all _new_ downloads? I have older files in other games that don't have numeric suffixes.

**Comment by Pickysaurus** [comment]
Yes @fireundubh , anything uploaded since we made the change will have these suffixes. Files from before that point have not been changed.
