### ISSUE TITLE
Download Manual keeps downloading the page html

### ISSUE THREAD

**Issue by SHiFTiNG-CORE** [Nexus-Mods/web-issues#902]
## Bug/error being reported:

I'm not sure if this bug is widespread because for me there are several of mods that I tried to download manually but the pop up download window downloads the page html instead of the mod file I tried:
https://www.nexusmods.com/skyrim/mods/96309?tab=files
https://www.nexusmods.com/skyrim/mods/96283?tab=files
https://www.nexusmods.com/skyrim/mods/73844/?tab=files
https://www.nexusmods.com/skyrim/mods/70834?tab=files

Pls help. I want to download mods as soon as possible to complete my game
![download](https://user-images.githubusercontent.com/25659037/53015470-2d31a100-3486-11e9-9a48-2b0afaca702f.png)

## Expected result:

New window pops up and the actual mod file ready to be downloaded

## Actual result:

New window pops up and downloads the page html instead of the mod file

**Comment by Pickysaurus** [comment]
This appears to be resolved. If you are still having the problem, please open another report.
