### ISSUE TITLE
No verification emails being sent to new address

### ISSUE THREAD

**Issue by LypheNKrysiz** [Nexus-Mods/web-issues#903]
## Bug/error being reported:
Lost access to old email acct. and not getting email acct verification at new address.

## Steps to reproduce:
1. Change email address
2. Try logging in.
3. Get this error: 
Error
You must validate your account first. Look into your e-mail box! If you did not receive our e-mail, we can send a new one
4. Click 'send new one' link.
5. Check email. No email no matter how many times do no. 4 and check email.

## Expected result:
I expect a verification email at the new address, as I no longer have access to the old address.

## Actual result:
No verification email at new address. Ever.

**Comment by Pickysaurus** [comment]
This is a problem with your email provider blocking our emails: https://help.nexusmods.com/article/102-i-am-not-receiving-emails-from-nexus-mods-what-can-i-do

Please contact support@nexusmods.com if you're still having issues
