### ISSUE TITLE
Captcha Login Error

### ISSUE THREAD

**Issue by Maxanadu** [Nexus-Mods/web-issues#904]
## Bug/error being reported:
Cannot Login to Website

## Steps to reproduce:
1) Click Login button
2) Put in credentials
3) Press enter
4) Fail captcha (that didn't exist)

## Expected result:
Logging in

## Actual result:
Not logging in

There have been several other posts like this but none have given a solution, just marked as solved.

**Comment by Pickysaurus** [comment]
The issues get closed because this is not a problem with the site but with your local setup. This article may help you figure it out https://help.nexusmods.com/article/79-why-am-i-getting-an-infinite-loading-wheel-on-the-login-page
