### ISSUE TITLE
Unpublished mods display "Moderator Locked" error in the comments section.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#905]
## Bug/error being reported:
When a mod is unpublished. The comments section has the following error. 
![image](https://user-images.githubusercontent.com/31670524/53347051-38fee680-3910-11e9-8f0f-884bdf23f94a.png)

This can be misleading as it implies moderator action again the file. If possible this should say "You cannot add comments to a mod until it is published." or similar. 

Reported by DaggerfallTeam via PM

**Comment by iamtiz** [comment]
Fixed
