### ISSUE TITLE
Total Downloads shown on My Files and Mods pages instead of Unique Downloads

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#907]
#102 should not have been closed as wontfix.

According to the [Nexus FAQs for Donation Points](https://www.nexusmods.com/modrewards#/faq):

> Unique download counters are perhaps the most objective metric we have on this site and are a direct representation of the popularity of a mod, even more so than endorsements. 

If this is true, modders should be able see our Unique Downloads on the My Files page, and we should be able to browse mods sorted by Unique Downloads.

**Comment by iamtiz** [comment]
Done

**Comment by fireundubh** [comment]
@iamtiz Can you also forward this change to the User Files page?

**Comment by FelesNoctis** [comment]
Seconding this. Just had a discussion about it!
