### ISSUE TITLE
RSS Feed comment counter

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#909]
## Bug/error being reported:
RSS for news posts always reports +1 comments compared to the actual count. This may be counting the news post itself as a comment. 

## Steps to reproduce:
Compare the counts shown at https://www.nexusmods.com/rss/news
To the counts shown here: https://www.nexusmods.com/news/

## Expected result:
Comment count shows total comments

## Actual result:
Comment count shows total comments +1

**Comment by iamtiz** [comment]
Fixed
