### ISSUE TITLE
Bad URLs are not being handled

### ISSUE THREAD

**Issue by JustHereToReportABug** [Nexus-Mods/web-issues#91]
**URL:** any "wrong" URL, such as https://rd.nexusmods.com/fallout5/
**Bug/error being reported:** some error code is displayed
**Steps to reproduce:** Go the the url above, or any subfolder that's not a real game
**Expected result:** Redirect to main nexumods.com page, like the old site does
**Actual result:** weird error code

I found this one out by accident because I made a typo.

**Comment by mrmason** [comment]
Assigned `PT#151476359`

**Comment by verenion** [comment]
A fix has been pushed for this. Instead of redirecting to the homepage, we are now correctly serving proper 404 response codes. We are going to look at the design of the 404 page, but that may come later.
