### ISSUE TITLE
File management - no shortcut link to managing mirrors.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#910]
https://www.nexusmods.com/skyrimspecialedition/users/myaccount?tab=files

This page has a number of shortcut links to manage things in a mod, but there isn't one for managing mirrors. Would be appreciated if we could get that. Thanks :)

Oh, and that appears to be for all games, not just SSE.

**Comment by Arthmoor** [comment]
I realized a bit later that it is there, but it's marked as "Requirements". Maybe just an alteration to the UI there to indicate Mirrors is also part of that?

**Comment by iamtiz** [comment]
Done
