### ISSUE TITLE
Add a timestamp to a "mod hidden" or "in moderation" message.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#911]
When a mod author hides a mod or a staff member places a mod into moderation, it would be helpful if a timestamp for when this was done was added to the message so that as users we can decide if it's worth waiting or if the message is stale and the mod should be dropped.

See forum discussion here: https://forums.nexusmods.com/index.php?/topic/7460656-the-need-for-time-stamps/

**Comment by iamtiz** [comment]
Mods under moderation now display the date they were put into review in their pages.
Hidden mods will also diplay such information, but only if they were hidden from last Friday on, since we didn't store that data at all, before that day.
