### ISSUE TITLE
Preview File Contents Display bug

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#912]
## Bug/error being reported:
Some nested folders do not display correctly when previewing the archive. 

## Steps to reproduce:
Example Mod page: https://www.nexusmods.com/stardewvalley/mods/3607?tab=files
File Structure is :
```
[CP] Shining Treasure
> Assets
```

The preview shows both folders on the top level. 
```
Assets
[CP] Shining Treasure

```
![image](https://user-images.githubusercontent.com/31670524/54130884-26ed6f80-4409-11e9-9507-976fa89b00b5.png)

## Expected result:
File preview matches archive structure.

## Actual result:
See above.

**Comment by iamtiz** [comment]
Fixed
