### ISSUE TITLE
Posts style incorrectly

### ISSUE THREAD

**Issue by cirion** [Nexus-Mods/web-issues#913]
## Bug/error being reported:

The contents in one of my mods' "Posts" tabs appears unstyled. The first few posts display correctly, but subsequent posts are missing the background, avatar images, etc.

## Steps to reproduce:

Visit https://www.nexusmods.com/shadowrunhongkong/mods/23/?tab=posts 

## Expected result:

See a nicely-styled list of posts.

## Actual result:

I see a few well-styled posts, and then the remainder are all indented at the same level without any backgrounds.

<img width="1177" alt="Screen Shot 2019-03-13 at 1 50 57 PM" src="https://user-images.githubusercontent.com/321492/54313979-b163d980-4597-11e9-9791-a4f3ffd4d7b8.png">

I'm not sure what's causing this, but the last proper-looking post has the text `@[member='seberin']` and a spoiler block, so maybe one of those is breaking the formatting on the rest of the page?

Edit: I see this behavior in Firefox, Chrome, and Safari.

**Comment by iamtiz** [comment]
Fixed
