### ISSUE TITLE
website stuck in mobile version on desktop

### ISSUE THREAD

**Issue by tjanke42** [Nexus-Mods/web-issues#914]
## Bug/error being reported:
A couple of days ago, I started getting the mobile version of nexusmods.com when viewing it on my pc.  The problem is only on chrome - firefox displays the desktop version, as expected.  
  
I disabled all chrome extensions and cleared cookies and cache, made no difference.

Chrome 72.0.3626.121 (and the version before, as well).

## Steps to reproduce:
Using chrome, go to https://nexusmods.com.  That's it.

## Expected result:
See the desktop version of the website.

## Actual result:
See the mobile version of the website.

**Comment by tjanke42** [comment]
Anyone?  Helloooo?  I've tried everything I can think of, a few suggestions would be most welcome.

**Comment by Pickysaurus** [comment]
Are you using a mobile internet connection of some kind? I've not been able to replicate this and drawn a blank on what would even be causing it. If it works in Firefox it's definitely something odd on your end I'm afraid.

**Comment by DeniUtah** [comment]
I just had this problem.  I bought a brand new pc.  My problem was somehow connected to setting up an option to sync my phone with my pc.  When I removed that sync, the desktop version returned.

**Comment by Pickysaurus** [comment]
@DeniUtah that's interesting. I'll see if I can replicate it based on that information

**Comment by DeniUtah** [comment]
> I just had this problem. I bought a brand new pc. My problem was somehow connected to setting up an option to sync my phone with my pc. When I removed that sync, the desktop version returned.

Well, I digress.  It has switched back to mobile view again.  Grrr

**Comment by Pickysaurus** [comment]
I'm closing this issue because we have been unable to replicate it. I suspect it's something specific to your local environment that is making the browser display the mobile site.

**Comment by Crystalwarrior** [comment]
Just occured to me out of nowhere right now, using Firefox. When I joined earlier today no such issue happened, desktop version was always present on github desktop.
