### ISSUE TITLE
Broken web page layout (Dragon Age Inquisition)

### ISSUE THREAD

**Issue by Nicholas-Steel** [Nexus-Mods/web-issues#915]
## Bug/error being reported:
https://www.nexusmods.com/dragonageinquisition seems to be missing layout formatting and imagery.

## Steps to reproduce:

1) visit https://www.nexusmods.com/dragonageinquisition with Firefox on a Windows 10 PC.

## Expected result:
The webpage to be coherent and sensible looking.

## Actual result:
The website layout and imagery is broken.
![image](https://user-images.githubusercontent.com/11567846/54474427-526cc180-4830-11e9-893a-ed6bfef927ae.png)

**Comment by CreeperLava** [comment]
I have the same problem, happens rarely though and a reload fixes it

**Comment by Nicholas-Steel** [comment]
It seems to be working now, so maybe the issue is indeed intermittent.
