### ISSUE TITLE
Editing mod details on mobile

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/web-issues#916]
## Bug/error being reported:
Many problems make editing mods on mobile frustrating and difficult.

1. File display is broken in all file categories but main files
![Screenshot_20190317-082037](https://user-images.githubusercontent.com/12874678/54486998-57615d80-4890-11e9-98c6-a5f6104c8812.png)

2. Mod description display is broken. It's not wide enough, there is a lot of wasted space that should be used. As is I have to turn my phone to be able to even see anything, and even then the margins are too wide -> not enough content on screen.
![Screenshot_20190317-082202](https://user-images.githubusercontent.com/12874678/54487000-57615d80-4890-11e9-89b6-de1467725980.png)

3. Tapping anywhere in the mod's description textbox scrolls the page back to the top, forcing you to find where you were yet again.
![Screenshot_20190317-082221](https://user-images.githubusercontent.com/12874678/54487001-57f9f400-4890-11e9-853c-23b82f4b4568.png)

**Comment by iamtiz** [comment]
The first two issues are fixed, I wasn't able to replicate the last one

**Comment by CreeperLava** [comment]
Thank you. The last one might also be dependant on the browser. I use firefox on mobile, and it seems to have that behaviour for other text boxes on Nexus. When you click on a text box, it scrolls the window so that the cursor is in the middle of the screen (vertically). I assume this behaviour might mess with the large description text box and cause some weird conflicts.

**Comment by Pickysaurus** [comment]
Judging by your last comment, this should be resolve.
