### ISSUE TITLE
Synchronize cursor between source and rich text (mod description textbox)

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#917]
## Bug/error being reported:
If I switch between the rich text and source modes of the "edit mod description" textbox, my cursor's position isn't saved. I have to find where I was every time I switch.

A feature I'd like to see added is to have :
1. The cursor show up at the same place in both modes
2. Automatically scroll to where your cursor is when you switch modes

**Comment by Pickysaurus** [comment]
Merged into #1205
