### ISSUE TITLE
Nexus Forums - stop sending unwanted notification emails 

### ISSUE THREAD

**Issue by skk50** [Nexus-Mods/web-issues#918]
## Bug/error being reported:
Every Week on a Sunday my nexus forum profile automatically changes notifications for: 

Notification method to use for replies to followed topics	 	 
Notification method to use for topics in followed forums

from "Notification List" to "Email" without my intervention and my email box fills up with crap. 

Please make it stop.

## Steps to reproduce:
Nexus Forums
Profile
NotificationOptions
Check AutoFollow topics I reply to [Immediate]
Check Notification method to use for replies to followed topics - Notifications List
Check Notification method to use for topics in followed forums - Notifications List

Wait until the next Sunday
See a shit tonne of crap in your mail box 

Nexus Forums
Profile
NotificationOptions
Notification method to use for replies to followed topics - now shows Email checked
Check Notification method to use for topics in followed forums - now shows Email checked

### Example:
Look at SKK50 profile 

## Expected result:
To not receive a shit tonne dump of email crap every Sunday

## Actual result:
Continuing to receive a shit tonne dump of email crap every Sunday

**Comment by Pickysaurus** [comment]
We're looking into this, as per our email conversation.

**Comment by Pickysaurus** [comment]
Hey skk50 did you get the emails again this week?

**Comment by Pickysaurus** [comment]
Hello again skk50,

If you didn't get the email spam again this week, would you be happy for me to close this issue?

**Comment by skk50** [comment]
Hello no unwanted emails this week. It looks like the issue has, errr,  fixed itself as they do.

Thanks

Sent from my iPhone

On 30 Apr 2019, at 13:09, Mike <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again skk50,

If you didn't get the email spam again this week, would you be happy for me to close this issue?

**Comment by skk50** [comment]
Hello this issue has re-occured. Evidential attachments

1. Screenshot of the last time I updated my nexus profile notifications: Nexus Notification Preferences Sat 21 April.PNG

2. Screenshot of my nexus profile notifications today: Nexus Notification Preferences Tue 14 may.PNG

2.1 To confirm I have not modified these settings since 21 April

3. Unwanted Email received.

regards SKK

**Comment by Pickysaurus** [comment]
Hi there,

It looks like attaching the images to an email did not append them to this issue. 

Regarding the issue itself, we're still unable to track down any possible cause. Looking back at historical reports (via the forums and old bug tracker) it seems the notification preferences of random users change from time to time. This was summarised to be a bug in the version of IPBoard and not something we'll be able to fix. I have re-raised it with the team to see if a fresh pair of eyes will do any good.

Kind regards,

**Comment by skk50** [comment]
A transient issue with the core forum engine sounds highly likely.

You can grab the images from here for your evidence file https://1drv.ms/f/s!AilAY21U00B4baSJRA-wlKkefCY

cheers Me.

**Comment by skk50** [comment]
Also if you are done inspecting the user account is it OK to reset the notification profile as the emails keep coming ?

From: SKK 50 <skk.50@outlook.com>
Sent: 15 May 2019 16:51
To: Nexus-Mods/web-issues <reply@reply.github.com>; Nexus-Mods/web-issues <web-issues@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Nexus-Mods/web-issues] Nexus Forums - stop sending unwanted notification emails (#918)

A transient issue with the core forum engine sounds highly likely.

You can grab the images from here for your evidence file https://1drv.ms/f/s!AilAY21U00B4baSJRA-wlKkefCY

cheers Me.
