### ISSUE TITLE
Duplicate in Enderal option

### ISSUE THREAD

**Issue by Verayth** [Nexus-Mods/web-issues#919]
We need a Mod Management option to "Duplicate in Enderal" from the Skyrim Nexus.  Hopefully this will get more mod authors supporting Enderal and also allow existing Enderal mods to be easily moved to the new area.

**Comment by Pickysaurus** [comment]
Unfortunately, we do not plan to add this option, however, if users have several mods that they'd like some help copying across, feel free to reach out to BigBizkit or me on the site and we'll help you.
