### ISSUE TITLE
Comment posting seems to bomb out alot

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#92]
I am losing a fairly high percentage of comments I post, it seems to mostly effect bug reports but I get it on the comment page too. My comment 'submits' but is lost and something like the below appears. On reloading the page it's as if I never commented. Happens on both PC (Windows 10, Edge) and Mobile (Android 8.0, Chrome)
![nexys](https://user-images.githubusercontent.com/31670524/30876388-646278c8-a2ee-11e7-926a-d3a5a3310d55.PNG)

**Comment by Pickysaurus** [comment]
I've also been getting this almost every time I reply to a bug report lately, it's annoying as hell :/
Sometimes instead of the above I get the following duplication of the previous comment.
![buggy](https://user-images.githubusercontent.com/31670524/30934917-fd52f5de-a3c6-11e7-9758-d451a3b04650.PNG)

**Comment by verenion** [comment]
Assigned PT#151476364
