### ISSUE TITLE
Last Page On multi-page content only accessible from dropdown

### ISSUE THREAD

**Issue by sweetsosweet** [Nexus-Mods/web-issues#920]
## Bug/error being reported:
The last page for any multi-paged content (posts, images), doesn't have a right arrow to navigate to it. You can only access it by clicking on the page drop-down box.

## Steps to reproduce:

1. Go to any content with multiple pages (even 2).
2. Click right arrow to navigate to the next page.
3. Arrow is no longer available on second to last page. (If there are 2 pages there is no right arrow in page 1, if there are 3 pages, there is no right arrow on page 2, etc) You have to click the drop-down to get to the actual last page.

## Expected result:
One more right arrow to get to the last page.

## Actual result:
Missing right arrow for the last page.  It makes it seem like you are at the end of a list of pages, even though there is one more remaining, which can cause users to miss additional content.

**Comment by Pickysaurus** [comment]
I can confirm this bug occurs at certain breakpoints.

**Comment by Pickysaurus** [comment]
Missing page 2 button
![image](https://user-images.githubusercontent.com/31670524/56501121-85783400-6505-11e9-8dda-7f59cd13f1d4.png)
Wider breakpoint
![image](https://user-images.githubusercontent.com/31670524/56501146-9de84e80-6505-11e9-8956-46fa6ef47e04.png)
Narrower breakpoint
![image](https://user-images.githubusercontent.com/31670524/56501165-b35d7880-6505-11e9-9654-a87a2ca0f53c.png)


Seems to be any breakpoint where the mods display in rows of 3.
