### ISSUE TITLE
User Permissions - Don't allow the page owner to be removed

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#922]
## Bug/error being reported:
When looking at the "User permissions" on a mod page (below). It's possible to click the X on the page owner. The name disappears but it doesn't actually remove the user from the mod. 

![image](https://user-images.githubusercontent.com/31670524/55225654-05fb8b80-520b-11e9-9d02-bfcefd5ab7ba.png)

Reloading the page will restore the page owner's name

## Expected result:
Page owner either does not appear or cannot be removed.

## Actual result:
Page owner can be removed (but it does nothing). 

### Reported by Alex#8056 on Discord.

**Comment by iamtiz** [comment]
Fixed
