### ISSUE TITLE
Profile pic bug

### ISSUE THREAD

**Issue by NexusTheBrony** [Nexus-Mods/web-issues#923]
## Bug/error being reported:
It seems as if my profile pic on the actual nexus site (not forums) is not loading and is still the default (for example the dragonborn in skyrim nexus). even tried using my gravatar

## Steps to reproduce:
unknown how to reproduce

## Expected result:
my profile pic (same as the 1 on forums and here) showing up or Nexus Mods

## Actual result:
still have default pic (like the dragonborn on skyrim nexus)

**Comment by Pickysaurus** [comment]
Hi there,

We had an issue with profile pictures that was fixed earlier today, could you please try re-uploading your avatar to the forum and it should now be properly reflected on the site.

Let us know if that doesn't work.
