### ISSUE TITLE
Cannot set default sorting option to "by unique downloads"

### ISSUE THREAD

**Issue by fireundubh** [Nexus-Mods/web-issues#924]
With the new "unique downloads" sorting option introduced in #907, that option was not made available to user search preferences, so users cannot use this option by default.

![2019-04-01 07_12_11](https://user-images.githubusercontent.com/1261664/55334262-beb10d00-544d-11e9-8249-3e8f63e9c846.jpg)

**Comment by iamtiz** [comment]
Fixed
