### ISSUE TITLE
Unable to Crop Mod Page Thumbnails

### ISSUE THREAD

**Issue by dhildebr** [Nexus-Mods/web-issues#926]
After adding a few new images to [one of my mod pages](https://www.nexusmods.com/skyrimspecialedition/mods/6359?tab=images), I can't seem to find the button to crop what portion of each image comprises the 16:9 thumbnail.

I recall being able to adjust cropping on either the user-facing images tab (nexusmods.com/XXX/mods/###?tab=images) or the media management page (nexusmods.com/XXX/mods/edit/?id=###&game_id=###&step=media). I can find "edit title" and "delete image," and on the latter page also "make banner" and "make primary image," but not the cropping button.

It may have just been moved, in which case y'all can just close this, but I think it's genuinely missing. You can see my new page header has yet to have its thumbnail cropped, as an egregious example of a 7:2 image trying to fit into a 16:9 space. The issue is not unique to this particular mod page.

**Comment by Pickysaurus** [comment]
Hi @dhildebr 

We temporarily removed this feature while we upgrade our image storage solution on the site.

There's a thread about it here https://forums.nexusmods.com/index.php?/topic/7472736-mod-images-thumbnail-cropping/

**Comment by Pickysaurus** [comment]
Thumbnail cropping will not be returning, however, we have restored header cropping.
