### ISSUE TITLE
Suggestion - Make Tracked mods visible or able to be filtered

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#928]
## Suggestion:
Be able to filter out tracked mods or highlight them similar to "Update Available" or "Downloaded" in the search. 

###Suggestion from anonymouselephant on the forums https://forums.nexusmods.com/index.php?/topic/7493626-tracking-list-option/#entry68892771

**Comment by clayne** [comment]
Definitely, a simple ☑ form checkbox that indicates "Downloaded" where one can turn it off to look for mods they have tracked but haven't downloaded yet would be immensely helpful for some of us who have 20+ pages of tracked mods (saved for later, etc).

**Comment by Pickysaurus** [comment]
#940 is related.
