### ISSUE TITLE
Deleted mods still show up in our comment tracking list.

### ISSUE THREAD

**Issue by Arthmoor** [Nexus-Mods/web-issues#929]
When we delete a mod, our comment tracking list still shows it as being there.

https://www.nexusmods.com/skyrimspecialedition/mods/trackingcentre?tab=comments

![thiswasdeleted](https://user-images.githubusercontent.com/1762652/56247503-35f7bb00-6062-11e9-8dd0-4e0c72f101dd.png)

I deleted WVA last night after it had been sitting hidden for ages. It should no longer be getting included on the list. The same is true for the USKP/UDGP/UHFP/UDBP on the Skyrim LE side as well and those have been gone for years.

**Comment by Pickysaurus** [comment]
Thanks Arthmoor, I've replicated the problem.

**Comment by Arthmoor** [comment]
This has been marked as closed but the issue has not been addressed as far as I can see. I still have deleted stuff in my list.

**Comment by Pickysaurus** [comment]
All tracking centre feedback has been moved to #1204
