### ISSUE TITLE
Nexus Site Redirect

### ISSUE THREAD

**Issue by TheRailgunMisaka** [Nexus-Mods/web-issues#930]
## Bug/error being reported:
Can't stay on the site for more than a few seconds before being redirected to a blank page, still titled NexusMods

## Steps to reproduce:
I'm not sure of the steps, I'm on chrome and haven't had this issue before.

### Example:
step 1, get on nexus mods site, any game, even the home.
step 2, be redirected. 

## Expected result:
Use the site.

## Actual result:
Not being able the site.

**Comment by D2Rakanishu** [comment]
Having the same issue, also tried on Microsoft edge with the same effect.

**Comment by mrmason** [comment]
We think this is down a bad advert being served - we have reported it to our advert publisher.
