### ISSUE TITLE
dying light  mods not working

### ISSUE THREAD

**Issue by adsrw** [Nexus-Mods/web-issues#931]
## Bug/error being reported:
  im using the dev and cheat mod and I have done what I needed to do but it is not working

## Expected result:
  I was hoping it would working but it does not

## Actual result:
 it is broken and I can not do anything about it

**Comment by Pickysaurus** [comment]
This tracker is for reported regarding the Nexus Mods website, please use the bug tracker or comments section for the mod you are trying to use to ask for help.
