### ISSUE TITLE
Nexus infected page downloading viruses!

### ISSUE THREAD

**Issue by AllUsernamesTakenn** [Nexus-Mods/web-issues#932]
## Expected result:
<!-- No viruses preferably....

## Actual result:
<!-- 8 viruses blocked by my anti-virus.

**Comment by AllUsernamesTakenn** [comment]
I don't know why the hell it didn't work, here is what i wrote:
The following page on Nexus mods downloads 8 viruses when visiting the description page: https://www.nexusmods.com/skyrim/mods/32669/?tab=description

**Comment by Pickysaurus** [comment]
Hi there,

I'm not seeing any problem with the page you linked, could you provide more information? 

I would also suggest you fully scan your PC for Malware to ensure it's not something local to your computer.

**Comment by AllUsernamesTakenn** [comment]
I did, twice. My computer came up clean. Are you saying there is nothing in
your downloads section after visiting the page? Nothing titled a bunch of
random letters and numbers .png?

**Comment by Pickysaurus** [comment]
No, nothing downloads both with and without adverts on my end. 

Would one of the downloads happen to be "1362233330.png" or "1362291642.png"?

If so, it looks like your browser may have attempted to download the broken images from that page. Which one are you using?

**Comment by AllUsernamesTakenn** [comment]
Yes that actually is one of the files. I am on safari, but this has never
happened with any other page... That is really weird.
Do you know what might be causing this?

**Comment by Pickysaurus** [comment]
I'm not sure, are you able to replicate it in a different browser. I suspect it is related to your local setup or internet connection in some way. 

I can't actually download those images because to me it's a broken link.

**Comment by Pickysaurus** [comment]
I am closing this issue as it seems to be more on your end than a site issue. If you require further advice feel free to email support@nexusmods.com
