### ISSUE TITLE
Premium membership preferences changes when visiting certain sites

### ISSUE THREAD

**Issue by highbot-core** [Nexus-Mods/web-issues#934]
## Bug/error being reported:
Premium membership preferences changes when visiting certain sites.

## Steps to reproduce:
1. Change "Number of items to show per page" for example to 80.
2. Visit mainpage for a game: i.E. https://www.nexusmods.com/skyrim
3. Under "More Mods"/"Popular last 30 days" press "View More - Popular (30 Days)"

## Expected result:
Showing 80 items per page.

## Actual result:
Showing the default 20 items per page and setting my preference about showing items to default. (20? per site)

So far it only changes if you get directed from the main page via "View More Button" to any site that views mods.

- Game main page -> MoreMods -> View More Button (New Today, New this Week, Popular 30days, Popular Alltime, More Treding, Random, Updated) changes my preferences.

- Pressing Explore More Mods on the right doesnt change my preferences.
- Pressing More Hot Mods on the right doesnt change my preferences.

**Comment by Pickysaurus** [comment]
Thanks for the report, I've been able to replicate this and have raised it with the team.
