### ISSUE TITLE
Infinite Save Loading

### ISSUE THREAD

**Issue by BiRaitBec** [Nexus-Mods/web-issues#935]
Url: https://www.nexusmods.com/fallout4/mods/23556/?
Username on the Nexus: BiRaitBec

Bug/error being reported:
Upon Saving the updated description in my mod page the wheel loading the save keeps going infinitely, without saving anything. The same happens in Microsoft Edge, Firefox and Chrome.

Steps to Reproduce:
- Go to mod description edit page and click the upper or lower save button.

Expected result:
Mod Page Description Should Save.

Actual result:
Mod Page Description is not saving.

**Comment by mrmason** [comment]
Please can you try again and let me know if it's working for you now ?

**Comment by BiRaitBec** [comment]
Yes, it's working perfectly now.

May i ask out of curiosity what was the problem? and how did you manage on fixing it?

**Comment by mrmason** [comment]
Cloudflare Web Application Firewall happened!
