### ISSUE TITLE
Upload Readme Hangs

### ISSUE THREAD

**Issue by lazworks** [Nexus-Mods/web-issues#937]
## Bug/error being reported:
For the last two days, when I try to drag and drop (or browse) a text file using the Manage Document page, the progress bar shows but never shows any progress.

## Steps to reproduce:

1. Navigate to https://www.nexusmods.com/neverwinter/mods/869
1. Select Documentation from the Manage dropdown menu.
2. Drag and drop a text file onto the "Drop a new readme file to replace the current one" area,
[DownloadRulesV2.txt](https://github.com/Nexus-Mods/web-issues/files/3120125/DownloadRulesV2.txt)

## Expected result:
File load completed.

## Actual result:
Progress bar shows, but no progress and the file is never loaded

**Comment by Pickysaurus** [comment]
Thanks for the report, it appears to be being blocked by CloudFlare. I've flagged it with the devs.

**Comment by lazworks** [comment]
Many thanks. Hope this can be resolved soon - I really need to upload the file.

**Comment by Pickysaurus** [comment]
You should still be able to copy/paste the text directly into the readme section. Or does that not work either?

**Comment by lazworks** [comment]
Many thanks for your suggestion.

If you mean the change log large edit box, then I can't use that because the documentation is not a change log. Unless there is another way to paste the text that I don't know about. or the result of using the large edit box will be still be the same as uploading the file.

Please let me know.

**Comment by Pickysaurus** [comment]
My mistake, I was thinking a readme could be input manually like a changelog. Sorry for the confusion.

**Comment by lazworks** [comment]
Many thanks for your rapid response - very much appreciated.

**Comment by lazworks** [comment]
Hi
Apologies for hassling, but any idea how long it will take to resolve this issue - still can't upload the doc file.
Many thanks.

**Comment by Pickysaurus** [comment]
We're still working on it. Are you able to copy and paste it into an article in the meantime? 

Here's the link: https://www.nexusmods.com/neverwinter/mods/edit/?id=869&game_id=180&step=articles

**Comment by lazworks** [comment]
Many thanks for being responsive - very much appreciated.

Unfortunately, an article doesn't work - I need the file to be present so that NIT can read the file programmatically.

**Comment by Pickysaurus** [comment]
Interesting, so is NIT directly addressing this file https://www.nexusmods.com/Contents/mods/180/readmes/869_DownloadRulesV2.txt ?

As a short term fix I might be able to get that file updated?

**Comment by lazworks** [comment]
Thanks for getting back to me.

Yes, NIT accesses the file directly when it is started. A short term fix would be very helpful. Hopefully by the next time I need to update it, the problem will be resolved.

**Comment by lazworks** [comment]
I changed my text file to include additional information and the upload now works - so I have managed to update the file.

Given this change, I don't know whether you want to keep this open or not.

**Comment by Pickysaurus** [comment]
Interesting, thanks for the update. It may be related to some changes made today. I will keep this issue open until I've had confirmation from the team. 

Glad it's finally sorted and thank you for being patient!

**Comment by lazworks** [comment]
Many thanks for your responsiveness - very much appreciated.

**Comment by Pickysaurus** [comment]
I have confirmed, the team have fixed the Cloudflare issue. Please don't hesitate to let us know if the issue resurfaces.
