### ISSUE TITLE
Better sorting options when searching mods

### ISSUE THREAD

**Issue by clayne** [Nexus-Mods/web-issues#939]
These are the current sorting options:

![image](https://user-images.githubusercontent.com/2467434/56917224-cc1ede80-6a6f-11e9-9717-56518227983c.png)

While they're certainly helpful, there's a problem with finding lesser known mods that people do consistently like but which aren't as popular as all the well known stuff out there that's been downloaded a 100k times. What would be helpful here are a couple of meta-metrics like:

* Downloads / Endorsements
* Unique downloads / Endorsements

As these are more indicative of how well liked a mod is even when the download numbers aren't that high. Now granted, not every mod is endorsed, and certainly as a mod becomes more popular it's probably less likely to be endorsed overall, but I think this would aid people in finding buried gems out there.

**Comment by patchling** [comment]
Would being able to search by the ratio of total downloads against unique downloads help with that? There would be the issue of some mods requiring multiple files/parts required to get the mod to work and others coming in an all-in-one package.

**Comment by clayne** [comment]
That would help too, although I think all that would really say is how many unique people have downloaded something vs how many may have redownloaded it at some point. I find that endorsements is a better metric to use because it shows someone went out of their way to endorse something they like. I know I do that - in fact I find sometimes I endorse the lesser known mods (more than the 100k+ downloaded ones) to try and increase their visibility.

**Comment by Greg-Nexus** [comment]
Closed: We're unlikely to make this change in the future. Users can currently filter results by Endorsements and limit the maximum number of Endorsements, which achieves the same result.
