### ISSUE TITLE
Bugs page has no filters (minor)

### ISSUE THREAD

**Issue by Thallassa** [Nexus-Mods/web-issues#94]
It'd also be nice if it was searchable. 

This is pretty minor because most mods don't even use their bugs page, but I present to you.... 

https://rd.nexusmods.com/skyrim/mods/69306/?tab=bugs

https://www.nexusmods.com/skyrim/mods/69306/?tab=14&navtag=https%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodbugs%2F%3Fid%3D69306&pUp=1 (old site has filters which helps). 

(I'm just trying to see if "spider silk" has been mentioned at all!)

**Comment by mrmason** [comment]
Upgrading this to a missing feature

**Comment by iamtiz** [comment]
Fixed
