### ISSUE TITLE
Cannot upload files.

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#941]
The Nexus uploader isn't working at all.  Just hangs & will not make uploaded files available.

## Steps to reproduce:
1. Upload a file to the Nexus
2. Watch as upload takes an eternity to upload.
3. Hit the Save File button.
4. Watch as uploaded files just sit in perpetual infinite uploading loop, never becoming available for download on the Nexus.

Files available for download after a few mins.

Files in perpetual infinite uploading loop after 20+ mins of initial upload to the Nexus.

**Comment by Pickysaurus** [comment]
Could you provide some more information, such as the name/type/size of the file you were trying to upload and to which mod page?

**Comment by scjohnson1981** [comment]
I was finally able to get the files to upload via a re-upload but it took over 40 mins before finally becoming available for download on the Nexus.  The file sizes were 51.4 MB (CBBE SE) & 54.6 MB (UUNP).  Both can be found here: 

https://www.nexusmods.com/skyrimspecialedition/mods/25428

The Nexus uploader has been buggy/glitchy for YEARS.  Numerous reports have been filed regarding the bugged/glitched uploader on Nexus but so far has yet to be fixed.  One cannot even re-upload a file half the time without having to change the version number since it tends to get stuck in a perpetual infinite virus scanning loop, which is beyond ridiculous.  Please fix the Nexus uploader.  As I just said, this has been an ongoing issue for years & I fail to see why such an issue has yet to be addressed.  It shouldn't take 40+ mins for 51.4 MB/54.6 MB uploads to go through a virus scan before being made available for download on the Nexus.  I could see this being the case for larger mods with large file sizes but not for 51.4 MB/54.6 MB uploads.

**Comment by Pickysaurus** [comment]
We are currently working on improvements to the upload system. That said, it's possible your location relative to our servers that is causing the delays. Are your download speeds also slow? 

In regards to the virus scanning, it can take several minutes if a lot of files have been uploaded as it is a queue. This is something we're looking at optimising. 

Hopefully, the changes in the future will rectify your issues.

**Comment by scjohnson1981** [comment]
Downloads are fine but Upload speeds have been getting progressively worse.  Please fix this.  Thank you.

**Comment by scjohnson1981** [comment]
Uploads have pretty much slowed to a literal crawl today.

**Comment by Sarissofoi** [comment]
Just made a account here so I can confirm it.
Can't upload files on Nexus - the upload process never finishes. Theya re small tweak files and still it takes forever.

**Comment by Pickysaurus** [comment]
Are you guys able to open the developer console in your browser and watch the network tab while uploading a file to see if you're getting errors?

**Comment by Sarissofoi** [comment]
Failed to load resource: net::ERR_CONNECTION_CLOSED
BBoC-1557410401.js:1846 POST https://rd-uploads.nexusmods.com/Uploads?File net::ERR_CONNECTION_CLOSED
BBoC-1557410401.js:1846 POST https://rd-uploads.nexusmods.com/Uploads?File net::ERR_CONNECTION_CLOSED
BBoC-1557410401.js:1846 POST https://rd-uploads.nexusmods.com/Uploads?File net::ERR_CONNECTION_CLOSED
﻿

​

**Comment by Sarissofoi** [comment]
Error: Could not establish connection. Receiving end does not exist.  ui-service.js:177:9
Error: Could not establish connection. Receiving end does not exist.  ui-service.js:177:9

first opera 2nd firefox

**Comment by Sarissofoi** [comment]
So anything new?

**Comment by scjohnson1981** [comment]
Uploads are slower than molasses when previously they used to be reasonably fast.  The uploader has been on the fritz for a couple of weeks now.

**Comment by Sarissofoi** [comment]
I can't even upload few kb minimods.
Something is fucked.

**Comment by Pickysaurus** [comment]
@scjohnson1981 are you seeing similar console errors? 

@Sarissofoi I am unable to replicate the problem you are having, are you able to try a different connection (such as 4G mobile data) to verify if it's specific to your setup? 

There is work ongoing on the system, but no changes have been put live yet so it should work the same as always.

**Comment by scjohnson1981** [comment]
Not that I know of.  Uploads are slow & I've been getting a few Handshake Errors in my browser when attempting to load the Nexus at times.

**Comment by Sarissofoi** [comment]
Its kind of strange. Can't upload files from any browser but if I use TOR and have some luck with RNG I can. Dunno what to think.
