### ISSUE TITLE
site logout after closing browser (same as #382)

### ISSUE THREAD

**Issue by festro** [Nexus-Mods/web-issues#943]
## Bug/error being reported:

login is not remembered
## Steps to reproduce:

login to site, close browser, and revisit site.
## Expected result:

the site would remember I previously logged in
## Actual result:

I'm asked to log in again, and re-enter the 2FA code sent to my email

**Comment by Pickysaurus** [comment]
Please allow Nexus Mods to store cookies or your session will not be saved. You will also be logged out if you are using incognito or private browsing mode.

**Comment by festro** [comment]
I'm not using incognito mode or blocking cookies but it still logs me out upon closing browser using Firefox shouldn't be my popup blocker because I added nexusmods domain to the exemptions list just to make sure with no change.
