### ISSUE TITLE
Do not get notifications for comments on mods

### ISSUE THREAD

**Issue by aaronth07** [Nexus-Mods/web-issues#944]
## Bug/error being reported:
I am not getting notifications when someone responds to one my comments on another mod, nor am I getting notifications for when someone posts a comment on my own mod. 

## Steps to reproduce:
Have someone comment on a mod that I have posted, or have someone reply to one of my own comments on a mod. 

### Examples:
1. In my mod, when someone posts a comment in the comment section, I get no notifications.
2. I post a comment on a mod, when someone replies to my comment, I get no notifications.
3. I reply to another's comment, when someone else replies to that comment, I get no notifications.

## Expected result:
I get a notification when someone posts a comment on my mod, replies to a comment I have posted, or replies to a comment I have replied to.

## Actual result:
I get no notifications when someone posts a comment on my mod, replies to a comment I have posted, or replies to a comment I have replied to.

**Comment by Pickysaurus** [comment]
Hi @aaronth07 
Can you please go to your settings and turn updates for comments on your files off and back on again? This may reset the flag on the account and resolve the issue.

Please let me if this works or not.

**Comment by aaronth07** [comment]
I have done that multiple times, the issue still happens.

**Comment by Pickysaurus** [comment]
To conform, are you referring to "updates" appearing at the top of the page or email notifications? The later is not a feature we have on the site side.

**Comment by aaronth07** [comment]
Both. I would of course prefer email notifications, but I don't get email
notifications, nor does the "Messages" ever update.

**Comment by Pickysaurus** [comment]
Do you get any updates at all (on the site)? When we add a new game or post a news article that should trigger one.

**Comment by Pickysaurus** [comment]
Related: https://forums.nexusmods.com/index.php?/topic/7456946-comments-on-mod-pages-not-always-hitting-my-updates-list-lately/
(Mod Author forum)

**Comment by aaronth07** [comment]
I just realized I was looking in the wrong place, I was looking in "Your
Messages" rather than "Updates". I still think that they should get
delivered to your email, as most people do not check the Nexus site
every day.
