### ISSUE TITLE
report a bug about tracking list

### ISSUE THREAD

**Issue by eternalinsane** [Nexus-Mods/web-issues#945]
## Bug/error being reported:
im add mods to tracking list but the mods not appear  and other mods added time ago, dont appear now, this bugs is in nexusmods.com in my account, and i no have idea to happening.

**Comment by Pickysaurus** [comment]
Hi there,

Can you please provide more information on this issue, including:
- Your Nexus Mods username
- Examples of mods that you have tried to track and do not appear
- Examples of old mods that have disappeared
- Can you confirm that if you go back to one of the mods pages the "Track" button remains in its active state? 
![image](https://user-images.githubusercontent.com/31670524/57781541-5169ea80-7722-11e9-9369-fd54ef4543b7.png)
^ This is the active state
