### ISSUE TITLE
Request - Allow the "&" symbol in mod names/file names

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#946]
Seriously, why is it that the "&" symbol cannot be used in mod names/file names on the Nexus sites?  This is beyond ridiculous.  I humbly request that mod authors be allowed to use the "&" symbol in mod names/file names on the Nexus sites.  Please consider allowing said symbol.  Thank you.

**Comment by Pickysaurus** [comment]
Suggestion noted, obviously for the time being using the full work "and" is a good substitute.

**Comment by Pickysaurus** [comment]
This issue has been closed due to inactivity. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
