### ISSUE TITLE
Tabs on settings page overflow if window is not wide enough

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#948]
## Bug/error being reported:
![2019-05-16_17-16-25](https://user-images.githubusercontent.com/12874678/57865713-6320c000-77fe-11e9-947b-f3fdb92e0526.png)

## Steps to reproduce:
1. Go to https://www.nexusmods.com/users/myaccount
2. Resize window horizontally
3. Observe

## Expected result:
I guess several levels of tabs, one under the other. Like this
![firefox_2019-05-16_17-16-18](https://user-images.githubusercontent.com/12874678/57866334-77b18800-77ff-11e9-9efe-bbbc6015d280.png)

**Comment by Pickysaurus** [comment]
What browser are you using? This doesn't occur for me on Google Chrome.

**Comment by CreeperLava** [comment]
This is with firefox, on a 4K monitor at 175% dpi. It does look very specific, it doesn't happen on my laptop at 100% dpi.

**Comment by Pickysaurus** [comment]
This isn't likely to be fixed before we rebuild these pages in Nexus Mods Next.
