### ISSUE TITLE
I can't deploy my mod

### ISSUE THREAD

**Issue by 760152027** [Nexus-Mods/web-issues#949]
Error: Unexpected token  in JSON at position 0.
*** When you report this, please include the file "D:\steam\steamapps\common\Skyrim Special Edition\data\vortex.deployment.json" ***
    at fs.readFileAsync.then.catch.err (C:\Program Files (x86)\Vortex\resources\app.asar\renderer.js:1277:208)
    at tryCatcher (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Program Files (x86)\Vortex\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>

**Comment by 760152027** [comment]
Fri, 17 May 2019 11:19:19 GMT - info: Vortex Version 0.17.11
Fri, 17 May 2019 11:19:20 GMT - info: using C:\Users\User\AppData\Roaming\Vortex as the storage directory
Fri, 17 May 2019 11:19:22 GMT - info: python not found not found: python
Fri, 17 May 2019 11:19:26 GMT - info: python not found not found: python
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=settings_interface
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=settings_application
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=about_dialog
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=diagnostics_files
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=dashboard
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=starter_dashlet
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=firststeps_dashlet
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=mod_management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=category_management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=profile_management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=nexus_integration
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=download_management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamemode_management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=announcement_dashlet
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=symlink_activator
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=symlink_activator_elevate
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=hardlink_activator
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=move_activator
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=updater
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=installer_fomod
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=installer_nested_fomod
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=settings_metaserver
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=test_runner
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=extension_manager
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=ini_prep
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=news_dashlet
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=sticky_mods
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=browser
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=changelog-dashlet
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=common-interpreters
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=documentation
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=feedback
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=fnis-integration
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-7daystodie
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-ahatintime
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-breakingwheel
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-darkestdungeon
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-darksouls
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-darksouls2
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-dragonage
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-dragonage2
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-dragons-dogma
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-enderal
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-factorio
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-fallout3
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-fallout4
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-fallout4vr
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-falloutnv
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-gardenpaws
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-grimrock
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-kenshi
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-kerbalspaceprogram
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-kingdomcome-deliverance
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-monster-hunter-world
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-morrowind
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-mount-and-blade
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-neverwinter-nights
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-nomanssky
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-oblivion
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-oni
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-pathfinderkingmaker
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-pillarsofeternity2
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-sims3
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-sims4
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-skyrim
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-skyrimse
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-skyrimvr
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-starbound
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-stardewvalley
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-starsector
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-stateofdecay
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-subnautica
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-subnauticabelowzero
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-sw-kotor
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-teso
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-warthunder
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-witcher
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-witcher2
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-witcher3
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-worldoftanks
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-x4foundations
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-xcom2
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=game-xrebirth
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-archive-invalidation
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-bsa-support
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-plugin-indexlock
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-plugin-management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-savegame-management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gamebryo-test-settings
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=gameinfo-steam
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=issue-tracker
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=local-gamesettings
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=meta-editor
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=mo-import
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=mod-dependency-manager
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=mod-highlight
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=modtype-dinput
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=modtype-dragonage
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=modtype-enb
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=modtype-gedosato
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=morrowind-plugin-management
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=mtframework-arc-support
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=nmm-import-tool
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=open-directory
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=test-gameversion
Fri, 17 May 2019 11:19:27 GMT - info: init extension name=theme-switcher
Fri, 17 May 2019 11:19:27 GMT - info: all extensions initialized
Fri, 17 May 2019 11:19:27 GMT - info: register protocol protocol=nxm
Fri, 17 May 2019 11:19:28 GMT - info: deregister protocol
Fri, 17 May 2019 11:19:28 GMT - info: deregister protocol
Fri, 17 May 2019 11:19:28 GMT - info: register protocol protocol=http
Fri, 17 May 2019 11:19:28 GMT - info: register protocol protocol=https
Fri, 17 May 2019 11:19:28 GMT - info: found game location=D:\origin\The Sims 4\, name=The Sims 4
Fri, 17 May 2019 11:19:28 GMT - info: found game location=D:\steam\steamapps\common\Skyrim Special Edition\, name=Skyrim Special Edition
Fri, 17 May 2019 11:19:28 GMT - info: potential match D:\origin\The Sims 4\Game\Bin\TS4_x64.exe
Fri, 17 May 2019 11:19:28 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
Fri, 17 May 2019 11:19:29 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\Data\skse64_2_00_15\skse64_loader.exe
Fri, 17 May 2019 11:19:29 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe
Fri, 17 May 2019 11:19:29 GMT - info: found game location=E:\steam\steamapps\common\MountBlade Warband, name=Mount & Blade: Warband
Fri, 17 May 2019 11:19:29 GMT - info: found game location=E:\steam\steamapps\common\Mount and Blade, name=Mount & Blade
Fri, 17 May 2019 11:19:29 GMT - info: found game location=E:\steam\steamapps\common\Mount & Blade With Fire and Sword, name=Mount & Blade: With Fire and Sword
Fri, 17 May 2019 11:19:29 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
Fri, 17 May 2019 11:19:29 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\Data\skse64_2_00_15\skse64_loader.exe
Fri, 17 May 2019 11:19:29 GMT - info: potential match D:\steam\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe
Fri, 17 May 2019 11:19:29 GMT - info: changed game mode newMode=skyrimse
Fri, 17 May 2019 11:19:29 GMT - info: read font C:\Program Files (x86)\Vortex\resources\app.asar\assets\fonts\icons.svg
Fri, 17 May 2019 11:19:30 GMT - info: updated loot masterlist false
Fri, 17 May 2019 11:19:33 GMT - info: set channel
Fri, 17 May 2019 11:19:37 GMT - info: no update available
Fri, 17 May 2019 11:19:38 GMT - error: Failed to deploy mods message=Error: Unexpected token

**Comment by Pickysaurus** [comment]
This is a Vortex issue, please report it on the Vortex issue tracker. https://github.com/Nexus-Mods/Vortex
