### ISSUE TITLE
"Mods requiring this file" is often misread

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#950]
The "Requirements" section on mod pages lists two categories, mods that are required by the file and mods that are requiring this file.

A lot of people misread and think they need to install all of the mods listed in the "requiring" section, even though that's not what it means.

Maybe the section can be put into a different spot or renamed.

**Comment by Pickysaurus** [comment]
This issue has been closed as we are no longer accepting suggestions via this tracker. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
