### ISSUE TITLE
Upload speeds getting progressively WORSE

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#951]
## Bug/error being reported:
Uploads are taking much longer than they should given my 400 Mb/sec download speed/20 Mb/sec upload speed.

## Expected result:
Upload of files within a reasonable amount of time.

## Actual result:
Uploads taking 2 hours plus in some cases.  The larger the file size, the slower the upload speed.  This has been an ongoing issue for MONTHS & needs to be fixed/addressed.  Thank you.

**Comment by Pickysaurus** [comment]
As mentioned in #875 we are currently working on changes to this system, however, I am not able to replicate the issues you are having. Could you try using a VPN to see if that makes any difference to your upload speed. It may be related to your distance from our servers or some kind of limiting/bad connection between our servers and your router.

**Comment by scjohnson1981** [comment]
I do not have access to a VPN.  Those cost money I do not have at present.  I'm using the Chicago Premium server if that's of any relevance.  Uploads have been in the toilet for quite some time & have been getting worse over time.

**Comment by mrmason** [comment]
What ISP are you with please @scjohnson1981 ?

**Comment by Pickysaurus** [comment]
Can you verify this is now resolved? We have now pushed the changes I mentioned to our upload system.

**Comment by scjohnson1981** [comment]
Upload speeds are vastly improved.  However, sometimes uploads get stuck in a perpetual infinite loading loop at times, forcing me to refresh the page, then try the upload again...
