### ISSUE TITLE
Error 525: SSL Handshake Failed

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#952]
## Bug/error being reported:
I keep getting Error 525: SSL Handshake Error messages in my browser (Google Chrome) when loading Nexus pages.

## Steps to reproduce:
<!--
1. Navigate to Skyrim SE Nexus.
2. Watch as page fails to load & splashes Error 525: SSL Handshake Failed across one's screen.

## Expected result:
Skyrim SE Nexus homepage

## Actual result:
Error 525: SSL Handshake Failed message splashed across my screen.  The Nexus has been sluggish/experiencing numerous issues loading/uploading mod files of late.  Beyond ridiculous for such a popular site.  Please fix this mess.

**Comment by Pickysaurus** [comment]
Are you still experiencing this? It sounds like a temporary Cloudflare problem that sometimes occurs during high traffic on the site.

**Comment by scjohnson1981** [comment]
It's off & on but it still happens from time to time.  Nexus Mods is the only website where I've encountered this issue though so it has to be something going on with the Nexus sites.

**Comment by Pickysaurus** [comment]
Have you tried a different browser or disabling any addons that may be interfering? Many of the issues you have reported seem do not seem to be reproducible or reported by other users. Perhaps there are issues with your local setup. e.g. Browser, addons, anti-virus, VPN software, router configuration, connection between your ISP and our servers etc.

**Comment by scjohnson1981** [comment]
I switched to Firefox from Chrome since Chrome is going to start disabling ad blockers.  With that in mind, I'm a lifetime Premium member of your sites so I've given you all my support via my purchase of a lifetime Premium membership several years back.  While the SSL Handshake Error seems to have disappeared, the sites have been sluggish at times & I've also been getting a few Error: Comment Siblings not found errors when posting comments to the sites.
