### ISSUE TITLE
Server Unreachable

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#953]
## Bug/error being reported:
Repeated "Server Unreachable" errors when downloading mods.

## Expected result:
Mod downloaded via my mod manager.

## Actual result:
"Server Unreachable" error displayed in my mod manager.

Seriously, what's going on with the Nexus sites?  This is beyond ridiculous.  First, uploads became slower than molasses & now I cannot download mods via my mod manager.  Never have I experienced such a BROKEN website like Nexus Mods.  No disrespect intended when I say that but Nexus Mods is a broken mess.  Please fix it.

**Comment by mrmason** [comment]
Hello,

Please can you provide any more information regarding this.

- what mod manager are you using ?
- do you have an example of a link that is failing ?
- do you have any problems downloading the same file from the website ?

**Comment by Pickysaurus** [comment]
@scjohnson1981 are you able to provide the information mrmason requested?

**Comment by scjohnson1981** [comment]
1. Nexus Mod Manger Community Edition

2. https://www.nexusmods.com/skyrimspecialedition/mods/27375?tab=files (Main File)

3. Yes.  Tried multiple times from different servers & got the same result.

**Comment by Pickysaurus** [comment]
This issue should be resolved.
