### ISSUE TITLE
Cannot submit a bug report

### ISSUE THREAD

**Issue by DynV** [Nexus-Mods/web-issues#955]
## Bug/error being reported:
I'd like to submit a bug report for a mod but am unable to do so.

## Steps to reproduce:
1. Go to Flashlight NVSE page (currently http://nexusmods.com/newvegas/mods/39968/ )
2. Try to submit a bug report for it.

## Expected result:
I'd like for the mod author / manager to see the bug then hopefully address it using the bug tracking interface.

## Actual result:
There's not even a Bugs tab as seen on other mods between tabs Forum& Logs.

**Comment by Pickysaurus** [comment]
This is not a bug. The author has chosen not to have a Bugs tab. Please report your issue in the posts section.
