### ISSUE TITLE
Cant upload files, stuck at uploading for hours

### ISSUE THREAD

**Issue by Colemanallen1987** [Nexus-Mods/web-issues#956]
Cant upload my mod to nexus, uploading bar fills up fast and it will just freeze at uploading, let sit for 6 hours yesterday, tried different browsers, tried different computer, tried different formats, rar and 7zip, im not making the files even smaller to upload.  File is 5.42 gb, my internet speed is good i use commercial since i work from home for apple, tried wifi and direct connected....not sure what to do at this point. I never get a error, just stays at uploading green bar...

**Comment by Lord-Akkrand** [comment]
I'm seeing this as well.  When I open the developer tools in Chrome, I can see this error:
rd-uploads.nexusmods.com/Uploads?File:1 Failed to load resource: the server responded with a status of 500 ()

But there's no indication on the main page that it's failed.

**Comment by mrmason** [comment]
This should be fixed now - please let me know if you're still having problems.

@Colemanallen1987 - If you're still experiencing issues uploading the large file then if you can provide us with an alternative link then we can get it uploaded for you.
