### ISSUE TITLE
Unescaped Apostrophes Break Search

### ISSUE THREAD

**Issue by Sniper296** [Nexus-Mods/web-issues#957]
## Bug/error being reported:
A search with an apostrophe goes unescaped in a `JSON.parse`.

```javascript
RH.out_items = JSON.parse('{"nav":true,"home":false,"type":0,"user_id":0,"game_id":1151,"advfilt":true,"search":{"filename":"Valdacil's Item Sorting"},"include_adult":true,"show_game_filter":false,"page_size":20}');
//-----------------------------------------------------------------------------------------------------------------------------------^
```

## Steps to reproduce:
1. Search "Valdacil's Item Sorting"
2. Click pagination button 2

## Expected result:
Next page loaded

## Actual result:
Nothing/console error

`TypeError: window.RH_ModList is undefined`

**Comment by Pickysaurus** [comment]
I'm not sure what problem you are facing exactly. The quicksearch (which is what you're referring to) isn't paginated, so you must be using a different app.

We do not provide support for the search API interface. It is likely to change at any time without notice.

**Comment by Sniper296** [comment]
![2019-06-05_17-56-02](https://user-images.githubusercontent.com/13880171/58975048-ead56b00-87bb-11e9-9d61-1776128df77d.gif)

**Comment by Pickysaurus** [comment]
Thank you for the GIF. I've passed this to the team.

**Comment by Pickysaurus** [comment]
Pivtol Reference 166696709

**Comment by Pickysaurus** [comment]
This issue will be fixed in a future version of the search
