### ISSUE TITLE
Pagination in Image/Video tabs ignores user setting

### ISSUE THREAD

**Issue by s-a-m** [Nexus-Mods/web-issues#958]
## Bug/error being reported:

In user options, "Number of items to show per page" is set to 80. Thus, I'd expect pages would have 80 items. However, that only happens in Search results. When I am in a mod profile and go the "Images" or "Videos" tabs, the max number of items per page is 24. For "Posts", there is another option ("Number of comments to show per page") which works as expected. 

## Steps to reproduce:

1. Set items per page in https://www.nexusmods.com/users/myaccount
2. Check the image tab of any mod with enough number of images (>24), e.g. https://www.nexusmods.com/newvegas/mods/43135?tab=images 
3. Check the video tab of any mod with enough number of videos (>24), e.g. https://www.nexusmods.com/newvegas/mods/43135?tab=videos

## Expected result:

I'd expect to see 80 items per page. Or at least to have another option to control the number of items showing in image/video lists. 

## Actual result:

I'm seeing 24 items per page.

**Comment by Pickysaurus** [comment]
This issue has been closed due to inactivity. If you'd like to request this feature again please use our new feedback portal: https://feedback.nexusmods.com/
