### ISSUE TITLE
Download history preview on mod pages doesn't show all required files

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/web-issues#959]
## Bug/error being reported:
When mod authors use the View Download History option in the "Manage" menu on comments. The history is not displayed correctly for the required files. It only shows one of the requirements when a mod has several.

## Steps to reproduce:
Go to this page: https://nexusmods.com/fallout4/mods/34208?tab=posts
Open the download history on a comment.
Notice that the required files only shows one of the requirements.

## Expected result:
A list of the last download of the required files.

## Actual result:
Only showing one of the required files.

**Comment by Pickysaurus** [comment]
Pivotal reference; https://www.pivotaltracker.com/story/show/166607670

**Comment by artifixer** [comment]
This issue is till active. Any hope it will be fixed?

**Comment by Pickysaurus** [comment]
Re-raised internally but it's not likely to be fixed until we move to the new comments system on mods (WIP)
