### ISSUE TITLE
Cant remove or add games on favorites list

### ISSUE THREAD

**Issue by Mcdoyes** [Nexus-Mods/web-issues#960]
wont let me remove any game from favorites list. was able to remove 1 and tried to add another but it re-added the removed game and said i reached the 8 limit max.

## Expected result:
remove game and add new game to favorites

## Actual result:
removed game was re-added and would not let me add new game, there was a problem with your request

![games](https://user-images.githubusercontent.com/51862711/59555121-6d57ea80-8f73-11e9-9135-a055699ad898.JPG)
![problems](https://user-images.githubusercontent.com/51862711/59555122-6d57ea80-8f73-11e9-809e-d90470706e99.JPG)

**Comment by Pickysaurus** [comment]
Hi there,
Is the issue still happening? Sometimes it takes a short time for the cache to update when you make changes to your favourites.

**Comment by Mcdoyes** [comment]
The issue is no longer happening I think it was because of the cache
updating, Thank you
