### ISSUE TITLE
Pages loading as text on white background 90% of the time

### ISSUE THREAD

**Issue by kirillian** [Nexus-Mods/web-issues#961]
## Bug/error being reported:

Any given page on nexusmods.com fails to load assets (CSS/JS) about 90% of the time- I can see in the developer console a failure with the following signature:
`BBoC-general-1560264864.css:1 Failed to load resource: the server responded with a status of 404 ()`

This appears to be similar to the issue reported in #501 , however, that issue has been closed for some time and I don't see other reports. Refreshing the page repeatedly eventually gets me a successful request of the CSS and JS after about an average of 10 refreshes. However, I typically browse using many tabs at once. Typically refreshing any of my tabs results in all tabs having failures, however, there seems to be a window wherein when i refresh one tab and get a success, refreshing my other tabs often (but not always) results in a successful loading of the CSS.

Screenshots are below.
Here are the steps I've tried thus far by looking at solutions and suggestions posted elsewhere:
- I turned off my adblocker
- I cleared out my cookies/session data/application and storage cache (there were no web workers to clear out, but i checked that too)
- I tried a different browser (this one in and of itself seems a pretty good indicator that it is a connection problem of some kind)
- I changed my DNS servers on my router and my local computer for kicks...cleared DNS cache out afterward.

## Steps to reproduce:
Load [Nexusmods.com](https://nexusmods.com). Note the white page with black text. This works for me about 90% of the time as previously noted. Due to this being connection related, I am not 100% certain that it will be reproduceable for you guys.

#### Screenshot of the homepage with missing assets. The developer console is pulled open so you can see the exception
![missing_assets_nexusmods](https://user-images.githubusercontent.com/318909/59736603-5f7ebf80-9228-11e9-88c0-b049731a9959.PNG)

#### I navigated to the broken assets link to see if I could directly request the assets
![broken_css_link](https://user-images.githubusercontent.com/318909/59736604-6279b000-9228-11e9-9773-4cf5e0bf8a11.PNG)

#### Here's a view of the homepage with my ad blocker off just to demonstrate that it seems to have the same problem regardless of ad blocker or not.
![broken_home_page_with_ad_blocker_off](https://user-images.githubusercontent.com/318909/59736607-64437380-9228-11e9-918d-cfd0e7a94ce5.PNG)

**Comment by Pickysaurus** [comment]
Thanks for the report. We've made some changes to the site which should prevent this from happening. Please lets us know if it persists for you.

**Comment by kirillian** [comment]
A cursory glance appears to show this working as intended. Thanks for the response and work!
