### ISSUE TITLE
NMM Mods

### ISSUE THREAD

**Issue by QuantumHRZN** [Nexus-Mods/web-issues#962]
### **Bug/error being reported:**
There was some kind of NMM folder with mods, if I delete there will be problems with mods?

### **Steps to reproduce:**
1. ![Безымянный](https://user-images.githubusercontent.com/52081688/59939043-1caf2880-9470-11e9-9d5e-f9c4ed1d7801.png)
2. And in these folders are installed mods for Fallout 4, when they are removed, will there be problems with mods?
3. These folders contain esp / meshes / textures / materials from mods and each of these folders contains information

**### Expected result:**

**Comment by Pickysaurus** [comment]
Nexus Mod Manager has not been supported by Nexus Mods since December 2016. Please raise you issue on the community-driven Github here: https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues
