### ISSUE TITLE
Uploading files on multiple tabs at the same time bugs out

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#963]
When you upload a file to two different mod pages within two separate tabs in Chrome, the first one that finishes uploading gets assigned to the first tab and the second tab fails.

Because of this bug, I uploaded the wrong archive to the wrong game without noticing.

This might have only happened because the second tab had a much smaller file to upload, so it finished first. Both of the file names were identical (BodySlide for LE and BodySlide for FO4).

**Comment by Pickysaurus** [comment]
Hi Ous,

Sorry about this. We're currently working on some changes to the upload system so I'll flag this up to our devs.

**Comment by mrmason** [comment]
We've traced this back to the files being the exact same name and being uplaoded at the same time, and likely being rebuilt at the same time.

As Pickysaurus says, we're soon to replace the current upload system ( in the background ) so we'll make sure that's not an issue on the new system.

**Comment by Pickysaurus** [comment]
The new upload system is now live. (And has been for a while) 

If the problem persists, please re-open the ticket.
