### ISSUE TITLE
Tracking Center Now Showing Tracked Mods, Only Empty Pages

### ISSUE THREAD

**Issue by Tolagarf** [Nexus-Mods/web-issues#965]
## Bug/error being reported:
Tracking center no longer showing any of the mods I'm tracking, only 21 empty pages. I can't seem to get this working at all.

## Steps to reproduce:
N/A

## Expected result:
Well obviously I expected the page to show tracked mods, but it shows nothing buy empty pages

## Actual result:
Only showing empty pages, 21 total
![2019-06-25 (2)](https://user-images.githubusercontent.com/35457171/60083267-b3f8d200-9735-11e9-86d1-d89f9e1c16f7.png)

**Comment by Pickysaurus** [comment]
Do you have any browser extensions blocking Javascript? That is the most likely cause for this kind of issue.

**Comment by Pickysaurus** [comment]
Can you also try this URL as it will show tracked mods for all games (not just Skyrim SE as shown in your screenshot) 
https://www.nexusmods.com/mods/trackingcentre

**Comment by Tolagarf** [comment]
Before I made this post I actually checked with both Edge and Brave browser. No ad blockers were running and java-script was enabled. Couldn't get it working on either... Today it's working! Not sure what's changed though, if it was something in Windows at my end or the website. Call me confused, but for now this issue can be closed
