### ISSUE TITLE
Payment(paypal)

### ISSUE THREAD

**Issue by LPDursit** [Nexus-Mods/web-issues#966]
## Bug/error being reported:
I payed per paypal for livetime so about 63euros atm and it said it didnt worked but it got paid from my paypal acc

**Comment by Pickysaurus** [comment]
Hi there, 

Please raise a support ticket via the site and we'll look into this for you. 

https://forums.nexusmods.com/index.php?app=nexus&module=support&section=new

If possible, please include the PayPal reference.
