### ISSUE TITLE
Cannot upload anything to Skyrim Special Edition mod.

### ISSUE THREAD

**Issue by RSK-Apocalypto** [Nexus-Mods/web-issues#967]
## Bug/error being reported:
I am the author and creator of https://www.nexusmods.com/skyrimspecialedition/mods/16224

When trying to upload images, the image says Upload Completed but is never added to the image list.  This happens regardless of the file type, size, or browser.  In addition, the current file I uploaded as of last night says

"code"not_found"
message"bucket nexus-files does not have file: 1704/16224/Amara the Succubus of Fire - CBBE and UUNP-16224-1-2-1562120888.7z"
status404"

when trying to download it.  It should be noted I can upload and edit files and images perfectly fine on my regular Skyrim edition of this mod, https://www.nexusmods.com/skyrim/mods/90420

## Steps to reproduce:
Uploaded mod file, uploaded 8 images, everything else refused to upload.

## Expected result:
The mod and images to appear correctly.

## Actual result:
Mod is corrupted and images don't appear.

**Comment by BiRaitBec** [comment]
have the same issue

**Comment by Pickysaurus** [comment]
Your file appears to have been uploaded successfully. It may have been a temporary issue caused by a large upload blocking the file queue.

**Comment by BiRaitBec** [comment]
I confirm that 2 files having the issue are not fixed and can be
downloaded, but still 3 files are having the problem which i hope they get
fixed aswell soon.

thanks sir

Il giorno lunedì 15 luglio 2019, Mike <notifications@github.com> ha scritto:
