### ISSUE TITLE
Cursor is sent to search textbox when something is written there

### ISSUE THREAD

**Issue by starkgate** [Nexus-Mods/web-issues#968]
## Bug/error being reported:
If you write something in the search textbox, then go into any other textbox and try to write something, it writes in the search textbox instead of the focused textbox. It's quite frustrating

## Steps to reproduce:

1. Write something in the search textbox
![Screenshot_2019-07-04_14-25-29](https://user-images.githubusercontent.com/12874678/60666723-03db4580-9e68-11e9-887b-f9085cf3ebd6.png)
2. Place the cursor in any other textbox (comment, mod description...)
![Screenshot_2019-07-04_14-26-34](https://user-images.githubusercontent.com/12874678/60666726-0473dc00-9e68-11e9-8793-d7622c9fe018.png)
3. Type something
4. Watch as the cursor gets sent back to the search textbox
To "fix", empty the search textbox.

## Expected result:
The text should be written in the focused textbox, not the search.

## Actual result:
The text is written in the search textbox.

**Comment by Pickysaurus** [comment]
We are aware of this issue and it should be fixed when we updated the site navigation.

**Comment by GioGr** [comment]
so frustrating... please fix soon :P
