### ISSUE TITLE
CDN Issue with mod

### ISSUE THREAD

**Issue by jmontesi4** [Nexus-Mods/web-issues#969]
## Bug/error being reported:
Trying to download a specific mod (https://www.nexusmods.com/kotor2/mods/1041) triggers a CDN error page (Manual Download) or an error message in Vortex (Vortex download)

Previewing the mod content does work
![1041ContentPreview](https://user-images.githubusercontent.com/7807761/60748793-8abf1980-9f5f-11e9-94a0-0aa1d5bc8144.png)

The mod's posts tab contains multiple posts about this issue (In one way or another) and an alternate download link.

## Steps to reproduce:
Try to download the mod

## Expected result:
Download/Save prompt
OR
Nexus Error page

## Actual result:
If downloading manually a CDN error page is displayed
![1041CDN](https://user-images.githubusercontent.com/7807761/60748760-36b43500-9f5f-11e9-966f-0e833e3da561.png)

**Comment by BiRaitBec** [comment]
have the same issue

**Comment by Pickysaurus** [comment]
Thanks for the report, we're looking into this issue. There's currently a 10GB file blocking the upload queue. It should be resolved once that is processed.
