### ISSUE TITLE
Cant unblock banned users from 'blocked authors' page

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#97]
I'd suspect this would be caused by the user being banned and chosing to have their mods deleted at that time. Its likely this would also be a problem for non banned users, but also just anyone who makes a file, is blocked on another users end and then deletes their file but I have no way of testing that.

That being said, if you try and unblock a user with no files you get a "This user is not an author" error and they remain blocked and their name is not removed

**Comment by Thallassa** [comment]
Can confirm.

**Comment by iamtiz** [comment]
Assigned #152140109

**Comment by iamtiz** [comment]
Fixed
