### ISSUE TITLE
Truncated Tracking Centre List

### ISSUE THREAD

**Issue by Grausamste** [Nexus-Mods/web-issues#971]
The final page of the Tracking Centre list appears truncated when viewing at 20 or 40 items per page. I am using Mozilla Firefox on my desktop PC and accessing the Nexus via my Premium account. The Tracking Centre is sorted by Last Upload. By default I am viewing 80 items per page, though the Tracking Centre only supports up to 60. When viewing the item list below 60 items per page the final page appears truncated, in my case missing 23 files. 

At 60 items per page:
![nexusTracking60ItemsPerPage](https://user-images.githubusercontent.com/52701613/60882923-781e3c00-a20e-11e9-9b76-1100b5c75b3a.png)

At 40 items per page:
![nexusTracking40ItemsPerPage](https://user-images.githubusercontent.com/52701613/60882924-781e3c00-a20e-11e9-91fb-4f7e2b683189.png)

At 20 items per page:
![nexusTracking20ItemsPerPage](https://user-images.githubusercontent.com/52701613/60882925-781e3c00-a20e-11e9-965b-b43cc9143593.png)

**Comment by Pickysaurus** [comment]
I'll flag this up to the team, thank you for the report.
