### ISSUE TITLE
Can't make more than one attempt at duplicating a LE mod to SE

### ISSUE THREAD

**Issue by cuyima** [Nexus-Mods/web-issues#972]
## Bug/error being reported:
It's impossible to do a second attempt at duplicating a mod to SE after deleting the first duplicate. Instead the "See in SkyrimSE" option will show and lead to a dead link.

## Steps to reproduce:
1. Create a mod on LE Nexus.
2. Clone it to SE.
3. Delete the clone.
4. Do a second attempt at cloning the page.

## Expected result:
Being able to duplicate the mod to SE again.

## Actual result:
Being blocked from duplicating the mod by the "See in SkyrimSE" option.

![Unbenannt](https://user-images.githubusercontent.com/52758909/60997296-c2aad000-a356-11e9-80bd-cad09b19f039.PNG)

![Unbenannt](https://user-images.githubusercontent.com/52758909/60997213-9a22d600-a356-11e9-9516-17d79d4166e2.PNG)

**Comment by Pickysaurus** [comment]
This is intended. Cloning mod pages is a one-time action. Please provide the URL of the deleted page if you'd like it to be restored.

**Comment by cuyima** [comment]
I don't really see the benefit of this interaction, because it is impossible to recover the cloned modpage by oneself once it's deleted.
I have now copied everything over to a new page manually, thanks for the offer though.
