### ISSUE TITLE
Files no more uploadable

### ISSUE THREAD

**Issue by BiRaitBec** [Nexus-Mods/web-issues#973]
{ "code": "not_found", "message": "bucket nexus-files does not have file: 1151/23556/2a. Optional Repack - Quality Overhaul - Part One-23556-1-0-1563197093.7z", "status": 404 }

all the files i upload have this issue while downloading

even if i re upload them

the mod page of mine is the following.
https://www.nexusmods.com/fallout4/mods/23556

**Comment by Pickysaurus** [comment]
I have answered this question for you on Discord. Massive files will take a long time to propagate across all CDN servers.
