### ISSUE TITLE
can not down load

### ISSUE THREAD

**Issue by hwybee4996** [Nexus-Mods/web-issues#974]
## Bug/error being reported:
can not download mods

### Example:
1. Step 1
2. Step 2
3. Step 3
-->

## Expected result:
a mod being downloaded

## Actual result:
https://cf-files.nexusmods.com/cdn/1704/27450/Yinkle%20Newmiller%20Necklaces%20SMP-27450-1-0-1563393086.7z?md5=1a5pQ6v0btPbk3QrDNVsSw&expires=1563428963&user_id=3 and no mod download

**Comment by mrmason** [comment]
I can't replicate this - the file downloads fine for me from - https://www.nexusmods.com/skyrimspecialedition/mods/27450?tab=files

**Comment by hwybee4996** [comment]
so when I click the manual download button weird page pops up with all kinds of stuff like this (gfvuygb%&* 9643hcfvierfvhb#) then a waring that says nexus site is not responding.  I install mods manually  then I used a mod manager (that I do not like to use) and got the download

**Comment by mrmason** [comment]
Can you please run a full scan of your computer with something like this - https://www.safer-networking.org/products/spybot-free-edition/download-mirror-1/

To ensure that you don't have a virus/spyware that is doing strange things with your browser?

**Comment by hwybee4996** [comment]
try on a different pc and done the same thing

**Comment by hwybee4996** [comment]
get this I use Microsoft Edge switched to google and it worked perfectly thank you for the hint (Browser)  the other pc I use  Microsoft Edge on I only use it for bank email very important stuff don't wonder in shady sites to void  virus/spyware

**Comment by hwybee4996** [comment]
yes I know e-mail can have virus/spyware to but I do not open anything that don't know what it is
