### ISSUE TITLE
Can't link new video for author review

### ISSUE THREAD

**Issue by raybo1** [Nexus-Mods/web-issues#975]
## Bug/error being reported:
I can't link my user-submitted video. Nor has the author or user Damanding been able to see it for author approval. Both the author and Damanding have checked the account settings.

![image](https://user-images.githubusercontent.com/52337374/61506850-7fcda580-a9b1-11e9-8346-35f2864933d6.png)

Mod page link:
https://www.nexusmods.com/fallout4/mods/39948?tab=description

Video link "youtube":
https://youtu.be/j78vOSYCSyU

Video only ends up here:
https://www.nexusmods.com/fallout4/videos/9898

## Steps to reproduce:
![video 2](https://user-images.githubusercontent.com/52337374/61506768-3da46400-a9b1-11e9-9511-2e9973005d3d.jpg)

Optimally an ordered list with the steps needed to reproduce the bug

### Example:
![RazeMySettlement](https://user-images.githubusercontent.com/52337374/61506791-4f860700-a9b1-11e9-8f12-f7a4c3d2e1f1.jpg)

## Expected result:
That the "Link a Video feature would work. The author would see it and be able to approve it and have it linked to the correct location on his mod page

## Actual result:
 The author never receives a notification to approve the video in order to link it to user-submitted videos.
![image](https://user-images.githubusercontent.com/52337374/61506918-b6a3bb80-a9b1-11e9-8b59-d209d5ab68c1.png)

Any help will be greatly appreciated.  I just want to support the author and have the video show up on his page :)

**Comment by raybo1** [comment]
Same problem, this video will not link either. The author and I can't get it to work.

https://www.nexusmods.com/fallout4/videos/9916

**Comment by Pickysaurus** [comment]
I have edited your first video and simply added the required mods to the "Featured mods" section and it appears in the approval section for the authors. 

I can see where the issue lies from your screenshots. You need to enter to mod name, not the URL.

**Comment by raybo1** [comment]
Damm, I am stupid.
I am glad you-all have such a great reporting setup where screenshots are simple to add.
My deepest apologies for taking up some of your time.
I will make it up to the community through community service by supporting the wonderful creators and making more videos for them. :)

Thank you very much.

**Comment by raybo1** [comment]
Thank you good Sir!

Damm, I am stupid.
I am glad you-all have such a great reporting setup where screenshots are simple to add.
My deepest apologies for taking up some of your time.
I will make it up to the community through community service by supporting the wonderful creators and making more videos for them. :)

Thank you very much.

**Comment by Pickysaurus** [comment]
No problem! You have actually highlighted that the field to add mods isn't particularly clear. I'll feed it back to our designer.
