### ISSUE TITLE
Image upload problems

### ISSUE THREAD

**Issue by FastBlackCat** [Nexus-Mods/web-issues#977]
When trying to upload an image to the Fallout 4 Nexus, when I hit the submit button, first I got this:

Error
There was an error while moving your image into the right folder

Then trying to submit a second time, got this:

Error
The image you uploaded couldn't be found.

I've tried to upload twice (30 minutes between) and it's happened both times.

**Comment by Reydragon1991** [comment]
Same for me

**Comment by Pickysaurus** [comment]
This issue should now be resolved.
