### ISSUE TITLE
Nexus Forums Error 522 - Connection Timed Out

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#978]
## Bug/error being reported:
Getting Error 522 - Connection Timed Out when trying to access the Nexus Forums/PM Messaging System

## Expected result:
Nexus PM Messaging System

## Actual result:
Error 522 - Connection Timed Out splashed across my screen in Firefox.

**Comment by Pickysaurus** [comment]
This was a temporary issue which should now be resolved.
