### ISSUE TITLE
Logging in/out while at search URL results in unloadable page

### ISSUE THREAD

**Issue by Nazenn** [Nexus-Mods/web-issues#98]
If you try and log in or out while you have an active search and are at the https://rd.nexusmods.com/skyrim/search/ address, the page goes to reload but stops and you end up with an unloaded white page. This page cannot be loaded by hitting refresh or enter in the address bar and you have to go to a non search page of the nexus for it to load.
The log in/out does process however which is something

**Comment by verenion** [comment]
Assigned PT#151593325

**Comment by verenion** [comment]
Fix has been pushed
