### ISSUE TITLE
SignUp Activation page does not exist #404

### ISSUE THREAD

**Issue by havarc** [Nexus-Mods/web-issues#980]
Literally at the edge of my patience here.

Tried to make an account for one single download, signed up with valid username and email.
Then I recieved the activation email and both of the activation links give me the 404.

Please, I beg you to allow limited downloads for unregistered users, maybe locked behind a recaptcha, maybe limited daily numbers (by IP) or whatever. It's absolutely ridiculous to have to create a dummy account and abandon it just for a single 67kB download (FNV 4GB patch).

**Comment by Pickysaurus** [comment]
I'm sorry to hear about your issues.

The most common cause of this is your email client corrupting the links required to complete registration. 

Please email support@nexusmods.com for any further account issues.
