### ISSUE TITLE
Author Search on Skyrim Nexus doesn't work

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/web-issues#981]
## Bug/error being reported:
Searching by mod author name doesn't work.

## Expected result:
A list of mods by Skyrim Nexus author sleepytigereyes

## Actual result:
This: https://www.nexusmods.com/skyrim/search/

**Comment by scjohnson1981** [comment]
Also, clicking on User Files doesn't work either.  Just brings up the Recent Activity page instead.

**Comment by Pickysaurus** [comment]
The only way I have been able to replicate these problems is by blocking JavaScript in my browser. So perhaps that is your issue? 
![SearchReport](https://user-images.githubusercontent.com/31670524/62457429-bf96da00-b772-11e9-9de4-01f4c2a9d10a.gif)

**Comment by scjohnson1981** [comment]
I don't have JavaScript blocked at all.  If that were the case, I wouldn't be able to view other web pages either.  This only occurs when searching by mod author on Skyrim Nexus.  Works just fine on Skyrim SE Nexus for the record.

**Comment by scjohnson1981** [comment]
If it's of any consolation, I'm using Mozilla Firefox.  Made the switch from Google Chrome due to Google's desire to disable ad blockers just so they can make a profit.  I'm a Premium Member (Lifetime) so ads wouldn't show up on the Nexus sites for me regardless if I have an ad blocker installed or not.

**Comment by Pickysaurus** [comment]
I'm able to run the search via both the quicksearch and advanced search.

Link for search results: https://www.nexusmods.com/skyrim/search/?BH=0&RH_ModList=nav:true,home:false,type:0,user_id:0,game_id:110,advfilt:true,include_adult:true,page_size:20,show_game_filter:false,open:true,search%5Bauthor%5D:sleepytigereyes

Perhaps you have tags blocked that prevent it from appearing?

**Comment by scjohnson1981** [comment]
It's not running for me & hasn't been for days.  Only affects Skyrim Nexus as far as I'm aware.  Skyrim SE Nexus works just fine.

**Comment by Pickysaurus** [comment]
Can you tell me what you get when clicking my link above?

Also can you please grab the URL after clicking this button on your blank search results?
![image](https://user-images.githubusercontent.com/31670524/62540148-d0b51900-b84e-11e9-920c-d56476741d4c.png)

**Comment by scjohnson1981** [comment]
That page loads up fine.  However, whenever I select Authors in the dropdown, then type "sleepytigereyes", all I get is a blank webpage in Firefox.  The issue seems to be isolated to whenever I type "sleepytigereyes" into the Search bar when searching by Authors.  Just tried typing in manngt & his mods pull up just fine.  No, sleepytigereyes hasn't blocked me from his mods since I've ported several of his mods over to Skyrim SE Nexus after obtaining proper permissions via Nexus PM.

**Comment by scjohnson1981** [comment]
Again, this issue only happens on Skyrim Nexus & only when I search using "sleepytigereyes" in the Search bar after selecting Authors from the drop down list.
