### ISSUE TITLE
Zipped files are not downloading correctly 

### ISSUE THREAD

**Issue by Jester93** [Nexus-Mods/web-issues#982]
Noticed issue with the mod Outcasts and Remnants downloading manually or through NMM neither works you cant even open the zipped archive.

**Comment by mrmason** [comment]
I've just flushed that file from all of the CDN nodes and can confirm the md5sum for all files is the same now as

`7d22c0a99b47e6dc41d6fd14afccbed4`

Please let me know if you spot any others
