### ISSUE TITLE
Mod Order in Catagories not updating

### ISSUE THREAD

**Issue by greyday01** [Nexus-Mods/web-issues#984]
## Bug/error being reported:
Mod order not updating in Categories

## Steps to reproduce:
In SkyrimNexus under Mod Categories/ Castles, Palaces, Mansions and Estates
When you sort by downloads the order doesn't change to reflect the number of downloads.
This has been going on for several weeks

https://www.nexusmods.com/skyrim/mods/categories/68/

**Comment by Pickysaurus** [comment]
I'm not able to replicate the issue. Here is a link to the results I get when sorting by downloads:
https://www.nexusmods.com/skyrim/mods/categories/68/?BH=0&RH_ModList=categories%5B%5D:68,categories%5B%5D:68,nav:true,home:false,type:0,user_id:0,game_id:110,advfilt:true,category_id:68,include_adult:true,page_size:20,show_game_filter:false,page:1,sort_by:OLD_downloads

Is there a specific example you're able to provide of the issue?

**Comment by greyday01** [comment]
Some examples on that page of out of order listings are:
P.12 Whiterun Stronghold, P.13 Nchuzzrezar, P.14 Adventurers Cease, P.14 Automatic Basement Furnishing.
________________________________

**Comment by Pickysaurus** [comment]
I see what you mean now. I believe the search system (which powers the page you're looking at) is currently using "old" stats. So download via mod manager are not always included in the count. It is something we're aware of and will be fixing in future.

**Comment by Pickysaurus** [comment]
This should be resolved now.
