### ISSUE TITLE
page button's not working

### ISSUE THREAD

**Issue by Blue-Enigma** [Nexus-Mods/web-issues#986]
## Bug/error being reported:
Apon clicking on: Jump, requirements, permisions and credit, changelogs, donation, page 1, 2, 3, etc. it will not respond to me doing so.

## Steps to reproduce:

1. Go to [Nexus Mods, fallout 4, catergory 51](https://www.nexusmods.com/fallout4/mods/categories/51/).
2. Click on next page/mod or jump to a different page.
3. (If on mod page) try to click on: requirements, permisions and credit, changelogs.

## Expected result:
To go to the next page or spesified page. To have the requirements, permisions and credit, changelogs dialogue boxes open.

## Actual result:
Nothing happens.

## Aditional Notes:
I am using Chrome to browse nexus mods, I have not had this problem in the past and have no idea why it is happening now, I also checked the page's script and noticed that the code didn't actually take you to another page at all. (I am only a novice at Javascript and HTML so I may be wrong).

**Comment by mrmason** [comment]
It sounds like the javascript isn't working for you - do you have anything blocking scripts in your browser ?

**Comment by Blue-Enigma** [comment]
The only thing I can think of would be ad-blocker, but I've uninstalled it and restarted chrome and doesn't seem to be recognising that ad-blocker is gone, still saying I'm blocking ad's. I haven't updated flash in a while but I doubt that would do anything to stop javascript.

**Comment by Blue-Enigma** [comment]
I also get this when ever I open page 2 via new tab.
![image](https://user-images.githubusercontent.com/54137330/63093629-f08ac200-bf5d-11e9-8af1-d48933b721db.png)

**Comment by Blue-Enigma** [comment]
![Untitled2](https://user-images.githubusercontent.com/54137330/63093779-5d05c100-bf5e-11e9-825e-4f5cb833247c.png)
