### ISSUE TITLE
Locked out of account after attempting to change email adress. 

### ISSUE THREAD

**Issue by ErrorUnknownGT** [Nexus-Mods/web-issues#987]
## Bug/error being reported:
Issue reported before, nothing came of it?
"There is no way to re-send the email verification for email change, or update the email. Upon login only the message "check your email" is displayed. then the account cannot be accessed."

## Steps to reproduce:
Have an established Nexus account and then:

1. Go to nexusmods.com and make sure you're logged in.
2. Click the cog wheel at the top right of the web-page.
3. Scroll down to the "Email Address" section and click "CHANGE YOUR E-MAIL"
4. Input a new email address which you don't have access to and all other information and click "SAVE CHANGES."
5. You will now be locked out of your account with no way to change the e-mail.

## Expected result:
That I would receive a conformation e-mail, but due to user error, must have entered the wrong e-mail. An option to update/change the e-mail would be great.

## Actual result:
I attempt to log in to my account "aAaZzZ000oOo" and receive the following error:

" Error
You must validate your account first. Look into your e-mail box! If you did not receive our e-mail, we can send a new one "

I am now locked out of my account with no option to update/change the e-mail.

**Comment by Pickysaurus** [comment]
Please contact support@nexusmods.com from your old account email and we'll look into correcting this for you.
