### ISSUE TITLE
Comment Pagination does not work in IE11 (JS errors in the console)

### ISSUE THREAD

**Issue by Vegasands** [Nexus-Mods/web-issues#988]
## Bug/error being reported:

Unable to navigate from page 1 to page 2 using buttons or the arrows or the jump
## Expected result:

display page 2 content
## Actual result:

Only page 1 content no change

**Comment by Pickysaurus** [comment]
I'm afraid you'll have to be more specific. Which page? Which buttons? etc.

**Comment by Pickysaurus** [comment]
Thank you for the details, I have been able to replicate this problem in Internet Explorer 11. I will flag this up to the team, however I **strongly** recommend using a more modern browser. IE is end of life and may have security flaws that will never be fixed. 

If you're using Windows 10 I suggest you try Microsoft Edge.

**Comment by Pickysaurus** [comment]
IE11 is no longer supported, so I am closing this issue.
