### ISSUE TITLE
Other users able to edit my mod descriptions

### ISSUE THREAD

**Issue by nilrythv** [Nexus-Mods/web-issues#989]
## Bug/error being reported:
 Got a notification saying my mod has apparently been edited by another user (AltheaR) that I've never interacted with before. As far as I know, the mod doesn't give anyone but me access so just wondering what's happened as I can't tell what has been changed. The links seem to be fine. 

## Steps to reproduce:
Unsure

## Expected result:
 Unsure 

## Actual result:
 when accessing the mod activity logs, this is the most recent activity
17 Aug 2019, 5:19AM | Action by: AltheaR
Attribute change
Description changed.
https://www.nexusmods.com/skyrim/mods/90577?tab=logs

**Comment by Pickysaurus** [comment]
AltheaR is a moderator. Did she not send you PM about the edits?

**Comment by nilrythv** [comment]
Nope, there's nothing new in my messages.

**Comment by Pickysaurus** [comment]
I have spoken to AltheaR, she should have now sent you a PM to clear things up. Sorry for the confusion!
