### ISSUE TITLE
Phishing add on site which automatically redirects to another site

### ISSUE THREAD

**Issue by Simplemust** [Nexus-Mods/web-issues#990]
Today on 24.08.2019 i discovered the harmful add/phishing attempt while browsing the 
scrap everything mod for fallout 4. ( https://www.nexusmods.com/fallout4/mods/5320 ).
what happened after reading for less than a minute was that i was redirected to a new site 
DONT CLICK ON THE FOLLOWING LINK THE SITE IS HARMFUL AND TRYING TO SCAM YOU
( https://eu.consumerdefinition.top/8a669fa9c7120f82ec1917fdb8c7516d/index.html?ip=2001%3A14ba%3A9e4%3Af4f1%3A7d88%3Aee50%3Af005%3A1830&siteid=YjY0NDYyNzExMzIwMzg3Mjg4NDkjMTU2NjY0NzI1MEA0OTc4QF81MDg0MmZkOTY5ZWM4ZjlmMTM4OWM0YTY2MmVlZjRmMg&trackid=20190824114738257 ).
After the site got opened i checked the service provider in question and they have been informed of this harmful add but aren't doing anything about it for now. The site is in finnish and is written in broken finnish aswell. i treid reloading the nexusmods page from the homepgae and the redirection happened again even from the homepage.
## Steps to reproduce:
To reproduce this you only have to wait for about 10-20 seconds and it should happen automatically. at least it did for me.

1. Open mod page or homepage
2. Wait for less than a minute to get redirected
3. The site informs you that you have been selected to win a prize from the service provider, in my case DNA. The prizes are random products like new phones.
-->

## Expected result:
What was meant to happen was obviously that i could problem search on my own and not get redirected since i have some bugs on my game atm that i'm trying  to fix myself.

## Actual result:
What happened was i got sent to a site that tries to scam me. 

Sorry if the post isn't according to the norm. it is my first time posting on this site

The attached file is a snipping tool image i took from the site incase the link posted doesn't work.

Hopefully this helps in removing/solving the problematic add/issue or whatever is causing this
problem 

![Scamming site](https://user-images.githubusercontent.com/54472848/63637001-f54b2680-c67f-11e9-9e32-cfc51b7cb228.PNG)

Sincerely 
Simplemust

**Comment by Pickysaurus** [comment]
Hi there,

Thank you for the report, we'll feed this back to our advertising providers. 

The best way to report any future bad ads is documented here: https://help.nexusmods.com/article/100-how-to-report-bad-or-inappropriate-ads
