### ISSUE TITLE
Cannot make an account

### ISSUE THREAD

**Issue by Forrce** [Nexus-Mods/web-issues#991]
## Bug/error being reported:
Nothing happens once clicking "create account" on the second step of the account creation process. None of the links on the website will work after clicking create account.

## Steps to reproduce:
Go to create a new account, enter in a username, email, and password, answer the registration question and confirm the captcha, then click create account.

**Comment by Pickysaurus** [comment]
Hi there,

Please try this in another browser. Failing that, contact support@nexusmods.com with your desired username and we'll make you an account manually.
