### ISSUE TITLE
Cannot save file.

### ISSUE THREAD

**Issue by Delgathar** [Nexus-Mods/web-issues#993]
## Bug/error being reported:
File name fits naming conventions but I cannot submit.

## Steps to reproduce:

Use brackets in file name or foreign characters.  I used the translated name of my mod "Sichere Behälter" and it was not accepted.  Neither was Safe Containers [Deutche]
[image](https://user-images.githubusercontent.com/9401098/63934127-a3f8b980-ca28-11e9-93ef-6164b4b95de4.png)

## Expected result:
I expected it to accept the file.  Especially after seeing a warning box saying my characters should be accepted.

## Actual result:
I got a warning box and could not continue.

**Comment by Pickysaurus** [comment]
Brackets are the symbols "(" and ")". You are using Square Brackets which are not allowed in file names.
