### ISSUE TITLE
"Preview File Contents" not working

### ISSUE THREAD

**Issue by jimokam** [Nexus-Mods/web-issues#994]
## Bug/error being reported:

While in the Files section of a mod page, clicking the "Preview File Contents" link results in "Content could not be loaded at this time".

## Steps to reproduce:

1. While on a mod page, select the files tab.
2. Click the "Preview File Contents" link for a file.

## Expected result:

Should show the file contents.  This is how I determine if the mod uses an ESP or ESL, uses archives or loose files, etc..

## Actual result:

Get the message, "Content could not be loaded at this time".

## Nexus Login:

BlackAlabaster

**Comment by mrmason** [comment]
Thanks for reporting this, we're aware of the problem and are working on getting content-previews working again.

**Comment by mrmason** [comment]
This should be working again now.
