### ISSUE TITLE
Cannot log in via the Nexus Forums site due to Captcha Fail

### ISSUE THREAD

**Issue by steve040** [Nexus-Mods/web-issues#996]
## Bug/error being reported:
As of 4 Sep 2019 I cannot log in to Nexus via the Forums site due to Captcha Fail. It doesn't matter which browser I use (Firefox, Edge or Internet Explorer). I have tried logging in from my home PC and at work, both fail (it is still possible to log in via the Nexus Mods site however). Other users are reporting similar issues in the Forums.

## Steps to reproduce:
Just follow the usual log on procedure from Nexus Forums.

## Expected result:
I expected to be logged in.

## Actual result:
An "Error: Captcha Fail" message appeared:
![Capture](https://user-images.githubusercontent.com/54966684/64394497-cda18880-d099-11e9-84ff-a5f04b593327.png)

**Comment by mrmason** [comment]
This should be fixed now
