### ISSUE TITLE
Autocorrect is too aggressive.

### ISSUE THREAD

**Issue by AnyOldName3** [Nexus-Mods/web-issues#997]
## Bug/error being reported:
Autocorrect on mod comments and the forums is too aggressive. This is definitely the site's autocorrect rather than a browser or OS issue. Apparently this causes the Mass Effect people a lot of trouble as there's a popular mod called ALOT. For example, consider the following exchange:

> user:
> > Hey, I've installed this mod and now everything's broken.
> 
> author:
> > Are you running ALOT?

Under the current system, it gets changed to

> Are you running a lot?

which doesn't have the same meaning at all.

Also, it apparently affects embedded code, too, and embedded code should be sacred and never autocorrected:

![](https://cdn.discordapp.com/attachments/388023491896672257/620665356989759510/unknown.png)
![](https://cdn.discordapp.com/attachments/388023491896672257/620665394147098643/unknown.png)

## Steps to reproduce:
Write `ALOT` in a mod comment, forum message, your signature or your status and submit/save it. It will be displayed as `a lot`.

## Expected result:
To see `ALOT`.

## Actual result:
Seeing `a lot`.

Autocorrect that changes the meaning of things is worse than having no autocorrect at all. It might be reasonable to:
* have some warning that autocorrect is going to be applied and a way to temporarily disable it.
* have none at all.
* have an option to disable it on your mod's comments, so if you know you're going to be asking if people have installed ALOT, you can opt to see the mess that people type if you'd prefer it.

It's definitely necessary to completely disable autocorrect within embedded code.

**Comment by Pickysaurus** [comment]
Hmm, it seems our bad word filter on the forums was trying to correct the common grammar mistake. I've removed the rule so it should work as intended again.

**Comment by AnyOldName3** [comment]
That change has partially fixed the problem. I can now write ALOT in the Nexus forums, but not in mod comments, and when I view the forum post as a mod comment, it's still changed to *a lot*.

https://forums.nexusmods.com/index.php?/topic/6627451-modorganizer-to-openmw/?p=73422753

**Comment by Pickysaurus** [comment]
The bad-word filter is cached on the site side and may take a little while to update, but it will catch up eventually.

**Comment by AnyOldName3** [comment]
Cool.

**Comment by CreeperLava** [comment]
I love you @AnyOldName3
