### ISSUE TITLE
PNG avatars with transparent background are not displayed

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/web-issues#998]
## Bug/error being reported:

PNG files with transparent background used as profile avatar are not displayed on main site comments section (and upper right corner). They work fine on old forums and in profile settings.

## Steps to reproduce:

Set PNG file with transparent background as profile avatar.

## Expected result:

Working avatar.

## Actual result:

Clickable profile name in place of avatar.

**Comment by Pickysaurus** [comment]
Do you have an example or screenshot of this?

**Comment by zax-ftw** [comment]
> 
> 
> Do you have an example or screenshot of this?

Did you fix it already? I can't replicate it anymore. Had GIF and PNG of same avatar, PNG didn't work previously and GIF was fine, now both load correctly.

**Comment by Pickysaurus** [comment]
We haven't made any changes since you opened the report, so maybe it was a temporary issue of some kind?
