### ISSUE TITLE
Updates for Tracked Mods and Tracked Authors are not appearing

### ISSUE THREAD

**Issue by TMPhoenix** [Nexus-Mods/web-issues#999]
## Bug/error being reported:
When going to updates -> see all -> all games, I expect to see all updates since the last time I cleared the list out.
Instead I now see 20 or 21 updates, which isn't even all the updates for 1 game, let alone all the mods I'm tracking. So, now I have to mess around with the tracking centre, which is not particularly performant. I think this may have  started after I checked out the beta last week.

## Steps to reproduce:
1. Have a bunch of mods with updates
2. Go to updates -> see all  
3. select all games (but even on 1 game I don't see all updates)

## Expected result:
I expect  to see all updates, on all games since the previous time I cleared out the updates, which I usually do once a week.

## Actual result:
It shows only a few updates

**Comment by Pickysaurus** [comment]
Are you blocking JavaScript? This works fine on my end.

**Comment by raybo1** [comment]
I think I have the same issue as TMPhoenix.

![image](https://user-images.githubusercontent.com/52337374/65009433-a7ba8600-d8da-11e9-9fcb-c47458e36d95.png)

yet all these should be there

![image](https://user-images.githubusercontent.com/52337374/65009456-c4ef5480-d8da-11e9-80f0-b3c73ed5341b.png)

**Comment by raybo1** [comment]
![image](https://user-images.githubusercontent.com/52337374/65009640-6d051d80-d8db-11e9-96f8-e29b34530909.png)

**Comment by raybo1** [comment]
I checked today.

No updated files ”mods” were in the update bar.

I did a test and said yes to comments, that worked so turned it off again.  For me notification for mods updates is also not working.

**Comment by Sabre142** [comment]
Confirmed getting no updates on tracked mods whatsoever.

**Comment by TMPhoenix** [comment]
I checked again and I am still not getting more than a handful of updates.

**Comment by Pickysaurus** [comment]
I think we're talking about two different things here. 

Updates, in general, are appearing as expected. 

Updates specifically for tracked mods and authors currently do not appear (we are looking into that)

**Comment by raybo1** [comment]
@Pickysaurus exactly! you have precisely defined what I am trying to say and report.

I greatly appreciated your response.

Thanks a ton!

**Comment by TMPhoenix** [comment]
While that is indeed the problem, some updates are still showing even on tracked files for me, it's just that instead of say the actual 40 or more updates on various games, it only shows 2 tracked files with new files, an article and a new game added to nexusmods.

**Comment by Pickysaurus** [comment]
This problem and #1000 should now be fixed.
